Script Name: 3RSI 3CCI BB 5orders DCA strategy+
Author: rrolik66
Description: This strategy is just an attempt to find the indicator values for the trading bot service that I use (link in profile). Due to the use of the “request.security” function in the code, the indicators can be redrawn, but this is not important in history. The strategy used only 5 orders for the "DCA" - bot, located at the same distance in the price overlap range. I...
PineScript code:

Pine Script™ strategy
3RSI 3CCI BB 5orders DCA strategy+
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  rrolik66
//@version=5
strategy(title="3RSI  3CCI  BB  5orders  DCA  strategy+",  overlay=true,  default_qty_type=strategy.cash,  initial_capital=0.1,  commission_type=strategy.commission.percent,  commission_value=0.075)
start_time  =  input.time(defval=timestamp('01  January  2021  00:00'),  title='Start  Time')
end_time  =  input.time(defval=timestamp('01  January  2022  00:00'),  title='End  Time')
src_bot  =  input.source(close,  'Source  Bot')
tradeDirection  =  input.string(title='Trade  Direction',  options=['Long  Bot',  'Short  Bot'],  defval='Long  Bot')
weight_order0  =  input.float(13.03,  title='1  order  (%)',  group='weight  of  orders  in  %',  inline='Input  0')  *  0.01
weight_order1  =  input.float(14.29,  title='2  order  (%)',  group='weight  of  orders  in  %',  inline='Input  0')  *  0.01
weight_order2  =  input.float(17.19,  title='3  order  (%)',  group='weight  of  orders  in  %',  inline='Input  1')  *  0.01
weight_order3  =  input.float(22.67,  title='4  order  (%)',  group='weight  of  orders  in  %',  inline='Input  1')  *  0.01
weight_order4  =  input.float(32.80,  title='5  order  (%)',  group='weight  of  orders  in  %',  inline='Input  2')  *  0.01
st_long_orders  =  input.float(title='Rate  cover  (%)',  minval=1,  defval=80,  group='Long  Bot',  inline='Input  1')  /  4  *  0.01
longTakeProfit  =  input.float(1.4,  step=0.05,  title='Take  Profit  (%)',  group='Long  Bot',  inline='Input  1')  *  0.01
entry_long_SL  =  input.bool(defval=false,  title='StopLoss',  group='Long  Bot',  inline='Input  2')
longStopLoss  =  input.float(80,  step=0.1,  title='for  Long  Bot  (%)',  group='Long  Bot',  inline='Input  2')  *  0.01
st_short_orders  =  input.float(title='Rate  cover  (%)',  minval=1,  defval=500,  group='Short  Bot',  inline='Input  1')  /  4  *  0.01
shortTakeProfit  =  input.float(1.4,  step=0.05,  title='Take  Profit  (%)',  group='Short  Bot',  inline='Input  1')  *  0.01
entry_short_SL  =  input.bool(defval=false,  title='StopLoss',  group='Short  Bot',  inline='Input  2')
shortStopLoss  =  input.float(500,  step=0.1,  title='forShortBot(%)',group='ShortBot',inline='Input2')*0.01
//inputsforindicators
src=input.source(close,'Source',group='indicators')
rsi1_input=input.bool(defval=true,title='RSI-1',group='RSI-1',inline='Input0')
rsi1_res=input.timeframe(title='resolution',defval='5',group='RSI-1',inline='Input0')
rsi1_low=input.int(65,minval=0,maxval=100,title='long<',group='RSI-1',inline='Input1')
rsi1_len_long=input.int(14,minval=1,title='Length',group='RSI-1',inline='Input1')
rsi1_up=input.int(37,minval=0,maxval=100,title='short>',group='RSI-1',inline='Input2')
rsi1_len_short=input.int(14,minval=1,title='Length',group='RSI-1',inline='Input2')
rsi2_input=input.bool(defval=true,title='RSI-2',group='RSI-2',inline='Input0')
rsi2_res=input.timeframe(title='resolution',defval='15',group='RSI-2',inline='Input0')
rsi2_low=input.int(72,minval=0,maxval=100,title='long<',group='RSI-2',inline='Input1')
rsi2_len_long=input.int(14,minval=1,title='Length',group='RSI-2',inline='Input1')
rsi2_up=input.int(37,minval=0,maxval=100,title='short>',group='RSI-2',inline='Input2')
rsi2_len_short=input.int(14,minval=1,title='Length',group='RSI-2',inline='Input2')
rsi3_input=input.bool(defval=true,title='RSI-3',group='RSI-3',inline='Input0')
rsi3_res=input.timeframe(title='resolution',defval='30',group='RSI-3',inline='Input0')
rsi3_low=input.int(74,minval=0,maxval=100,title='long<',group='RSI-3',inline='Input1')
rsi3_len_long=input.int(14,minval=1,title='Length',group='RSI-3',inline='Input1')
rsi3_up=input.int(34,minval=0,maxval=100,title='short>',group='RSI-3',inline='Input2')
rsi3_len_short=input.int(14,minval=1,title='Length',group='RSI-3',inline='Input2')
cci1_input=input.bool(defval=true,title='CCI-1',group='CCI-1',inline='Input0')
cci1_res=input.timeframe(title='resolution',defval='5',group='CCI-1',inline='Input0')
cci1_low=input.int(190,step=5,title='long<',group='CCI-1',inline='Input1')
cci1_len_long=input.int(20,minval=1,title='Length',group='CCI-1',inline='Input1')
cci1_up=input.int(-175,step=5,title='short>',group='CCI-1',inline='Input2')
cci1_len_short=input.int(20,minval=1,title='Length',group='CCI-1',inline='Input2')
cci2_input=input.bool(defval=true,title='CCI-2',group='CCI-2',inline='Input0')
cci2_res=input.timeframe(title='resolution',defval='15',group='CCI-2',inline='Input0')
cci2_low=input.int(195,step=5,title='long<',group='CCI-2',inline='Input1')
cci2_len_long=input.int(20,minval=1,title='Length',group='CCI-2',inline='Input1')
cci2_up=input.int(-205,step=5,title='short>',group='CCI-2',inline='Input2')
cci2_len_short=input.int(20,minval=1,title='Length',group='CCI-2',inline='Input2')
cci3_input=input.bool(defval=true,title='CCI-3',group='CCI-3',inline='Input0')
cci3_res=input.timeframe(title='resolution',defval='30',group='CCI-3',inline='Input0')
cci3_low=input.int(200,step=5,title='long<',group='CCI-3',inline='Input1')
cci3_len_long=input.int(20,minval=1,title='Length',group='CCI-3',inline='Input1')
cci3_up=input.int(-220,step=5,title='short>',group='CCI-3',inline='Input2')
cci3_len_short=input.int(20,minval=1,title='Length',group='CCI-3',inline='Input2')
bb_input=input.bool(defval=false,title='BB',group='BollingerBands',tooltip='(forlongtrading)thepriceisbelowthelowerband,(forshorttrading)thepriceisabowetheupperband,длялонгаценаподнижнейлинией,дляшортаценанадверхнейлинией',inline='Input0')
bb_res=input.timeframe(title='resolution',defval='5',group='BollingerBands',inline='Input0')
bb_dev=input.float(2.0,minval=0.1,maxval=50,step=0.1,title='Deviation',group='BollingerBands',inline='Input2')
bb_len=input.int(20,minval=1,title='Length',group='BollingerBands',inline='Input2')
cci_input=input.bool(defval=false,title='bandCCI',group='bandCCI',tooltip='thissettingsetsthetradingrangebythelevelofthe"CCI"indicator,этанастройказадаетдиапазонторговлипоуровнюиндикатора"CCI"(янеиспользую)',inline='Input0')
cci_res=input.timeframe(title='resolution',defval='60',group='bandCCI',inline='Input0')
cci_len=input.int(20,minval=1,title='CCILength',group='bandCCI',inline='Input1')
cci_low=input.int(-110,step=10,title='CCI>',group='bandCCI',inline='Input2')
cci_up=input.int(110,step=10,title='CCI<',group='bandCCI',inline='Input2')
show_signals=input.bool(defval=false,title='Showsignals',inline='Input')
//Inputtotradingconditions
longOK=tradeDirection=='LongBot'
shortOK=tradeDirection=='ShortBot'
within_window()=>
time>=start_timeandtime<=end_time
//getindicators
rsi1_sec_long=request.security(syminfo.tickerid,rsi1_res,ta.rsi(src,rsi1_len_long))
rsi1_sec_short=request.security(syminfo.tickerid,rsi1_res,ta.rsi(src,rsi1_len_short))
rsi2_sec_long=request.security(syminfo.tickerid,rsi2_res,ta.rsi(src,rsi2_len_long))
rsi2_sec_short=request.security(syminfo.tickerid,rsi2_res,ta.rsi(src,rsi2_len_short))
rsi3_sec_long=request.security(syminfo.tickerid,rsi3_res,ta.rsi(src,rsi3_len_long))
rsi3_sec_short=request.security(syminfo.tickerid,rsi3_res,ta.rsi(src,rsi3_len_short))
cci1_sec_long=request.security(syminfo.tickerid,cci1_res,ta.cci(src,cci1_len_long))
cci1_sec_short=request.security(syminfo.tickerid,cci1_res,ta.cci(src,cci1_len_short))
cci2_sec_long=request.security(syminfo.tickerid,cci2_res,ta.cci(src,cci2_len_long))
cci2_sec_short=request.security(syminfo.tickerid,cci2_res,ta.cci(src,cci2_len_short))
cci3_sec_long=request.security(syminfo.tickerid,cci3_res,ta.cci(src,cci3_len_long))
cci3_sec_short=request.security(syminfo.tickerid,cci3_res,ta.cci(src,cci3_len_short))
[basis,upper_bb,lower_bb]=request.security(syminfo.tickerid,bb_res,ta.bb(src,bb_len,bb_dev))
cci_sec=request.security(syminfo.tickerid,cci_res,ta.cci(src,cci_len))
//calculateindicators
floatrating_long=0
floatrating_long_num=0
floatrating_short=0
floatrating_short_num=0
floatrsi1_long=na
floatrsi1_short=na
ifnotna(rsi1_sec_long)andrsi1_inputandlongOK
rsi1_long:=rsi1_sec_long<rsi1_low?1:0
ifnotna(rsi1_sec_short)andrsi1_inputandshortOK
rsi1_short:=rsi1_sec_short>rsi1_up?1:0
ifnotna(rsi1_long)
rating_long+=rsi1_long
rating_long_num+=1
ifnotna(rsi1_short)
rating_short+=rsi1_short
rating_short_num+=1
floatrsi2_long=na
floatrsi2_short=na
ifnotna(rsi2_sec_long)andrsi2_inputandlongOK
rsi2_long:=rsi2_sec_long<rsi2_low?1:0
ifnotna(rsi2_sec_short)andrsi2_inputandshortOK
rsi2_short:=rsi2_sec_short>rsi2_up?1:0
ifnotna(rsi2_long)
rating_long+=rsi2_long
rating_long_num+=1
ifnotna(rsi2_short)
rating_short+=rsi2_short
rating_short_num+=1
floatrsi3_long=na
floatrsi3_short=na
ifnotna(rsi3_sec_long)andrsi3_inputandlongOK
rsi3_long:=rsi3_sec_long<rsi3_low?1:0
ifnotna(rsi3_sec_short)andrsi3_inputandshortOK
rsi3_short:=rsi3_sec_short>rsi3_up?1:0
ifnotna(rsi3_long)
rating_long+=rsi3_long
rating_long_num+=1
ifnotna(rsi3_short)
rating_short+=rsi3_short
rating_short_num+=1
floatcci1_long=na
floatcci1_short=na
ifnotna(cci1_sec_long)andcci1_inputandlongOK
cci1_long:=cci1_sec_long<cci1_low?1:0
ifnotna(cci1_sec_short)andcci1_inputandshortOK
cci1_short:=cci1_sec_short>cci1_up?1:0
ifnotna(cci1_long)
rating_long+=cci1_long
rating_long_num+=1
ifnotna(cci1_short)
rating_short+=cci1_short
rating_short_num+=1
floatcci2_long=na
floatcci2_short=na
ifnotna(cci2_sec_long)andcci2_inputandlongOK
cci2_long:=cci2_sec_long<cci2_low?1:0
ifnotna(cci2_sec_short)andcci2_inputandshortOK
cci2_short:=cci2_sec_short>cci2_up?1:0
ifnotna(cci2_long)
rating_long+=cci2_long
rating_long_num+=1
ifnotna(cci2_short)
rating_short+=cci2_short
rating_short_num+=1
floatcci3_long=na
floatcci3_short=na
ifnotna(cci3_sec_long)andcci3_inputandlongOK
cci3_long:=cci3_sec_long<cci3_low?1:0
ifnotna(cci3_sec_short)andcci3_inputandshortOK
cci3_short:=cci3_sec_short>cci3_up?1:0
ifnotna(cci3_long)
rating_long+=cci3_long
rating_long_num+=1
ifnotna(cci3_short)
rating_short+=cci3_short
rating_short_num+=1
floatbb_long=na
floatbb_short=na
ifnot(na(lower_bb)orna(src)orna(src[1]))andbb_inputandlongOK
bb_long:=src<lower_bb?1:0
ifnot(na(upper_bb)orna(src)orna(src[1]))andbb_inputandshortOK
bb_short:=src>upper_bb?1:0
ifnotna(bb_long)
rating_long+=bb_long
rating_long_num+=1
ifnotna(bb_short)
rating_short+=bb_short
rating_short_num+=1
floatcci_band=na
ifnotna(cci_sec)andcci_input
cci_band:=cci_sec<cci_upandcci_sec>cci_low?1:0
ifnotna(cci_band)
rating_long+=cci_band
rating_long_num+=1
rating_short+=cci_band
rating_short_num+=1
//BuySell
Buy_ok=rating_long_num!=0andlongOK?rating_long==rating_long_num:true
Sell_ok=rating_short_num!=0andshortOK?rating_short==rating_short_num:true
//Plotting
plotshape(Buy_okandshow_signalsandlongOK,title='Buy',text='Long',textcolor=color.new(color.white,0),style=shape.labelup,location=location.belowbar,color=color.new(color.green,0),size=size.tiny)
plotshape(Sell_okandshow_signalsandshortOK,title='Sell',text='Short',textcolor=color.new(color.white,0),style=shape.labeldown,location=location.abovebar,color=color.new(color.red,0),size=size.tiny)
//Figureinentryordersprice
longEntryPrice0=src_bot
longEntryPrice1=longEntryPrice0*(1-st_long_orders)
longEntryPrice2=longEntryPrice0*(1-st_long_orders*2)
longEntryPrice3=longEntryPrice0*(1-st_long_orders*3)
longEntryPrice4=longEntryPrice0*(1-st_long_orders*4)
longEntryqty0=strategy.initial_capital*weight_order0/longEntryPrice0
longEntryqty1=strategy.initial_capital*weight_order1/longEntryPrice1
longEntryqty2=strategy.initial_capital*weight_order2/longEntryPrice2
longEntryqty3=strategy.initial_capital*weight_order3/longEntryPrice3
longEntryqty4=strategy.initial_capital*weight_order4/longEntryPrice4
shortEntryPrice0=src_bot
shortEntryPrice1=shortEntryPrice0*(1+st_short_orders)
shortEntryPrice2=shortEntryPrice0*(1+st_short_orders*2)
shortEntryPrice3=shortEntryPrice0*(1+st_short_orders*3)
shortEntryPrice4=shortEntryPrice0*(1+st_short_orders*4)
shortcontracts=strategy.initial_capital/shortEntryPrice0
shortEntryqty0=shortcontracts*weight_order0
shortEntryqty1=shortcontracts*weight_order1
shortEntryqty2=shortcontracts*weight_order2
shortEntryqty3=shortcontracts*weight_order3
shortEntryqty4=shortcontracts*weight_order4
long_entry_price=strategy.opentrades.entry_price(0)
short_entry_price=strategy.opentrades.entry_price(0)
longTP=strategy.position_avg_price*(1+longTakeProfit)
longSL=long_entry_price*(1-longStopLoss)
shortTP=strategy.position_avg_price*(1-shortTakeProfit)
shortSL=short_entry_price*(1+shortStopLoss)
plot(series=strategy.position_size>0andlongOK?longTP:na,color=color.new(color.red,0),style=plot.style_circles,linewidth=3,title='LongTakeProfit')
plot(series=strategy.position_size>0andentry_long_SLandlongOK?longSL:na,color=color.new(color.black,0),style=plot.style_circles,linewidth=1,title='LongStopLoss')
plot(series=strategy.position_size<0andshortOK?shortTP:na,color=color.new(color.green,0),style=plot.style_circles,linewidth=3,title='LongTakeProfit')
plot(series=strategy.position_size<0andentry_short_SLandshortOK?shortSL:na,color=color.new(color.black,0),style=plot.style_circles,linewidth=1,title='LongStopLoss')
//Submitentryorders
ifstrategy.opentrades==0andlongOKandwithin_window()
strategy.order(id='Long0',direction=strategy.long,qty=longEntryqty0,limit=longEntryPrice0,when=Buy_ok)
strategy.order(id='Long1',direction=strategy.long,qty=longEntryqty1,limit=longEntryPrice1,when=Buy_ok)
strategy.order(id='Long2',direction=strategy.long,qty=longEntryqty2,limit=longEntryPrice2,when=Buy_ok)
strategy.order(id='Long3',direction=strategy.long,qty=longEntryqty3,limit=longEntryPrice3,when=Buy_ok)
strategy.order(id='Long4',direction=strategy.long,qty=longEntryqty4,limit=longEntryPrice4,when=Buy_ok)
ifstrategy.opentrades==0andshortOKandwithin_window()
strategy.order(id='Short0',direction=strategy.short,qty=shortEntryqty0,limit=shortEntryPrice0,when=Sell_ok)
strategy.order(id='Short1',direction=strategy.short,qty=shortEntryqty1,limit=shortEntryPrice1,when=Sell_ok)
strategy.order(id='Short2',direction=strategy.short,qty=shortEntryqty2,limit=shortEntryPrice2,when=Sell_ok)
strategy.order(id='Short3',direction=strategy.short,qty=shortEntryqty3,limit=shortEntryPrice3,when=Sell_ok)
strategy.order(id='Short4',direction=strategy.short,qty=shortEntryqty4,limit=shortEntryPrice4,when=Sell_ok)
//exitposition
if(strategy.position_size>0)andnotentry_long_SLandlongOK
strategy.exit(id='exit_Long',limit=longTP,qty=strategy.position_size,when=strategy.position_size[1]>0)
if(strategy.position_size>0)andentry_long_SLandlongOK
strategy.exit(id='exit_Long',limit=longTP,stop=longSL,qty=strategy.position_size,when=strategy.position_size[1]>0)
if(strategy.position_size<0)andnotentry_short_SLandshortOK
strategy.exit(id='exit_Short',limit=shortTP,qty=math.abs(strategy.position_size),when=strategy.position_size[1]<0)
if(strategy.position_size<0)andentry_short_SLandshortOK
strategy.exit(id='exit_Short',limit=shortTP,stop=shortSL,qty=math.abs(strategy.position_size),when=strategy.position_size[1]<0)
//Cleanup
ifta.crossunder(strategy.opentrades,0.5)
strategy.close_all()
strategy.cancel_all()
Expand (304 lines)
