Script Name: 4 MA Strategy + Position Management
Author: tweakerID
Description: // This is a simple crossover Moving Average strategy, good for long term crypto trades.
// It buys when the MA "X" crosses up the MA "Y", viceversa for shorts.
// Both MAs are selectable from the Inputs section in the front panel.
// There is also a Position Management option thats
// sizes positions to have the same USD risk (using leverage) on each...
PineScript code:

Pine Script™ strategy
4 MA Strategy + Position Management
//@version=4
//  This  is  a  simple  crossover  Moving  Average  strategy,  good  for  long  term  crypto  trades.
//  It  buys  when  the  MA  "X"  crosses  up  the  MA  "Y",  viceversa  for  shorts.
//  Both  MAs  are  selectable  from  the  Inputs  section  in  the  front  panel.
//  There  is  also  a  Position  Management  option  thats
//  sizes  positions  to  have  the  same  USD  risk  (using  leverage)  on  each  trade,
//  based  on  the  percentage  distance  to  the  stop  loss  level.
//  If  you  turn  this  option  on  you  will  see  how  the  profit
//  grows  exponentially  while  the  drawdown  percentage  almost  remains  the  same.
strategy("4  MA  Strat",  overlay=true,  pyramiding=1,
          default_qty_type=strategy.percent_of_equity,
          default_qty_value=100,
          commission_value  =  0.04,
          initial_capital=10000,
          process_orders_on_close=false)
direction  =  input(0,  title  =  "Strategy  Direction",  type=input.integer,  minval=-1,  maxval=1)
strategy.risk.allow_entry_in(direction  ==  0  ?  strategy.direction.all  :(direction<0?strategy.direction.short:strategy.direction.long))
//Inputss
PSMGMT=input(defval=false,title="PositionManagement")
risk_per_trade=input(defval=5,title="RiskPerTrade%(forPSMGMT)",step=0.5)*.01
//SL&TPInputs
i_SL=input(true,title="UseSwingLo/HiStopLoss&TakeProfit")
i_SwingLookback=input(10,title="SwingLo/HiLookback")
i_SLExpander=input(defval=0,step=1,title="SLExpander")
i_MAFilter=input(false,title="UseMA4asBull/Bearfilter")
//MATypeSelector
MAtype=input(false,title="----------------MASelector-----------------")
MA1Period=input(9,title="MA1Period")
MA1Type=input(title="MA1Type",defval="EMA",options=["RMA","SMA","EMA","WMA","HMA","ALMA"])
MA2Period=input(21,title="MA2Period")
MA2Type=input(title="MA2Type",defval="EMA",options=["RMA","SMA","EMA","WMA","HMA","ALMA"])
MA3Period=input(50,title="MA3Period")
MA3Type=input(title="MA3Type",defval="SMA",options=["RMA","SMA","EMA","WMA","HMA","ALMA"])
MA4Period=input(100,title="MA4Period")
MA4Type=input(title="MA4Type",defval="SMA",options=["RMA","SMA","EMA","WMA","HMA","ALMA"])
//MASelector
MA1=ifMA1Type=="SMA"
sma(close,MA1Period)
else
ifMA1Type=="EMA"
ema(close,MA1Period)
else
ifMA1Type=="WMA"
wma(close,MA1Period)
else
ifMA1Type=="RMA"
rma(close,MA1Period)
else
ifMA1Type=="HMA"
hma(close,MA1Period)
else
ifMA1Type=="ALMA"
alma(close,MA1Period,0.85,6)

MA2=ifMA2Type=="SMA"
sma(close,MA2Period)
else
ifMA2Type=="EMA"
ema(close,MA2Period)
else
ifMA2Type=="WMA"
wma(close,MA2Period)
else
ifMA2Type=="RMA"
rma(close,MA2Period)
else
ifMA2Type=="HMA"
hma(close,MA2Period)
else
ifMA2Type=="ALMA"
alma(close,MA2Period,0.85,6)

MA3=ifMA3Type=="SMA"
sma(close,MA3Period)
else
ifMA3Type=="EMA"
ema(close,MA3Period)
else
ifMA3Type=="WMA"
wma(close,MA3Period)
else
ifMA3Type=="RMA"
rma(close,MA3Period)
else
ifMA3Type=="HMA"
hma(close,MA3Period)
else
ifMA3Type=="ALMA"
alma(close,MA3Period,0.85,6)

MA4=ifMA4Type=="SMA"
sma(close,MA4Period)
else
ifMA4Type=="EMA"
ema(close,MA4Period)
else
ifMA4Type=="WMA"
wma(close,MA4Period)
else
ifMA4Type=="RMA"
rma(close,MA4Period)
else
ifMA4Type=="HMA"
hma(close,MA4Period)
else
ifMA4Type=="ALMA"
alma(close,MA4Period,0.85,6)

//XYLogic
x=input(title="x",defval="close",options=["MA1","MA2","MA3","MA4","close"])
y=input(title="y",defval="MA1",options=["MA1","MA2","MA3","MA4","close"])
X=ifx=="MA1"
MA1
else
ifx=="MA2"
MA2
else
ifx=="MA3"
MA3
else
ifx=="MA4"
MA4
else
ifx=="close"
close

Y=ify=="MA1"
MA1
else
ify=="MA2"
MA2
else
ify=="MA3"
MA3
else
ify=="MA4"
MA4
else
ify=="close"
close
//SL&TPCalculations
SwingLow=lowest(i_SwingLookback)
SwingHigh=highest(i_SwingLookback)
bought=strategy.position_size!=strategy.position_size[1]
LSL=valuewhen(bought,SwingLow,0)-((valuewhen(bought,atr(14),0)/5)*i_SLExpander)
SSL=valuewhen(bought,SwingHigh,0)+((valuewhen(bought,atr(14),0)/5)*i_SLExpander)
islong=strategy.position_size>0
isshort=strategy.position_size<0
SL=islong?LSL:isshort?SSL:na
//PositionManagementCalculations
capital=strategy.equity
distance_to_long_stop_loss=1-(LSL/strategy.position_avg_price)
distance_to_short_stop_loss=(SSL/strategy.position_avg_price)-1
PS=(capital*risk_per_trade)/distance_to_long_stop_loss
SPS=(capital*risk_per_trade)/distance_to_short_stop_loss
PSqty=PS/close
SPSqty=SPS/close
//StrategyCalculations
MAFilter=close>MA4
BUY=crossover(X,Y)
SELL=crossunder(X,Y)
BUY2=crossover(X,Y)andMAFilter
SELL2=crossunder(X,Y)andnotMAFilter
//Entries
strategy.entry("long",true,qty=PSMGMT?PSqty:na,when=noti_MAFilter?BUY:BUY2)
strategy.entry("short",false,qty=PSMGMT?SPSqty:na,when=noti_MAFilter?SELL:SELL2)
//Exits
ifi_SL//andSL!=na
strategy.exit("longexit","long",stop=LSL)
strategy.exit("shortexit","short",stop=SSL)
ifi_MAFilter
strategy.close("long",when=SELL)
strategy.close("short",when=BUY)
//Plots
plot(i_SL?SL:na,color=color.red,style=plot.style_cross,title="SL")
plot(MA1,color=color.green,linewidth=1,title="MA1")
plot(MA2,color=color.yellow,linewidth=2,title="MA2")
plot(MA3,color=color.red,linewidth=3,title="MA3")
plot(MA4,color=color.white,linewidth=3,title="MA4")
plotshape(BUY?1:na,style=shape.triangleup,location=location.belowbar,color=color.green,title="BullishSetup")
plotshape(SELL?1:na,style=shape.triangledown,location=location.abovebar,color=color.red,title="BearishSetup")
//DebuggingPlots
plot(SSL,transp=100,title="SwingHigh")
plot(bought?1:0,transp=100,title="bought")
plot(PSqty,title="PSqty",transp=100)
plot(SPSqty,title="SPSqty",transp=100)
plot(PS,title="PS",transp=100)
plot(SPS,title="SPS",transp=100)
plot(distance_to_long_stop_loss,title="distancetoLSL",transp=100)
plot(distance_to_short_stop_loss,title="distancetoSSL",transp=100)
plot(capital,title="equity",transp=100)
Expand (209 lines)
