Script Name: 5212 EMA Strategy
Author: JepanK
Description: ver 01
23 December 2021

This strategy using :
- 3 EMA period 50, 100, 200
- stochastic RSI slow

Long Cond :
- Stochastic RSI cross below 20
- EMA 50 > 100 > 200

Short Cond :
- Stochastic RSI cross above 80
- EMA 50 < 100 < 200

Sleeping Mode
- EMA 50 between EMA 100 & EMA 200
PineScript code:

Pine Script™ strategy
5212 EMA Strategy
//@version=5
strategy(title='5212  EMA  Strategy',  shorttitle='5212  EMA',  overlay=true,  pyramiding=0,  default_qty_type=strategy.percent_of_equity,  default_qty_value=10,  calc_on_every_tick=false)
//**Backtest  Date  sof
useStartPeriodTime    =  input.bool(true                                              ,  'Start  Date  &  Time'      ,  group='Date  Range'        ,  inline='Start  Period')
startPeriodTime          =  input.time(timestamp('16  Apr  2021')      ,  ''                                        ,  group='Date  Range'        ,  inline='Start  Period')
useEndPeriodTime        =  input.bool(false                                            ,  'End  Date  &  Time'          ,  group='Date  Range'        ,  inline='End  Period')
endPeriodTime              =  input.time(timestamp('31  Dec  2222')      ,  ''                                        ,  group='Date  Range'        ,  inline='End  Period')
enableHighlight          =  input.bool(false                                            ,  'Highlight'                      ,  group='Date  Range'        ,  inline='Highlight')
highlightType              =  input.string('Anchors'                                ,  ''                                        ,  group='Date  Range'        ,  inline='Highlight'        ,  options=['Anchors',  'Background'])
highlightColor            =  input.color(color.white                              ,  ''                                        ,  group='Date  Range'        ,  inline='Highlight')
start  =  useStartPeriodTime  ?  startPeriodTime  >=  time  :  false
end  =  useEndPeriodTime  ?  endPeriodTime  <=  time  :  false
calcPeriod  =  not  start  and  not  end
var  line  startAnchor        =  line.new(na,  na,  na,  na,  xloc.bar_time,  extend.both,  highlightColor,  width=2)
var  line  endAnchor            =  line.new(na,  na,  na,  na,  xloc.bar_time,  extend.both,  highlightColor,  width=2)
useBgcolor  =  false
if  enableHighlight
        if  highlightType  ==  'Anchors'
                if  useStartPeriodTime
                        line.set_xy1(startAnchor,  startPeriodTime,  low)
                        line.set_xy2(startAnchor,  startPeriodTime,  high)
                if  useEndPeriodTime
  line.set_xy1(endAnchor,calcPeriod?time:line.get_x1(endAnchor),low)
line.set_xy2(endAnchor,calcPeriod?time:line.get_x1(endAnchor),high)
ifhighlightType=='Background'
useBgcolor:=true
useBgcolor
bgcolor(useBgcolorandcalcPeriod?color.new(highlightColor,90):na,editable=false)
//**BacktestDateeof
src=input(close,'Source',group='Support')
showEMA=input(true,'ShowEMA',group='Support')
//**StochasticRSIsof
smoothK=input.int(6,"K",group='StochasticRSI',minval=1)
smoothD=input.int(6,"D",group='StochasticRSI',minval=1)
lengthRSI=input.int(28,"RSILength",group='StochasticRSI',minval=1)
lengthStoch=input.int(28,"StochLength",group='StochasticRSI',minval=1)
rsi1=ta.rsi(src,lengthRSI)
k=ta.sma(ta.stoch(rsi1,rsi1,rsi1,lengthStoch),smoothK)
d=ta.sma(k,smoothD)
//**STochasticRSIeof
//**EMAsof
emain01=input.int(50,"EMAmaGirang",group='MovingAverageExponential',minval=1)
emain02=input.int(100,"EMAmaMuda",group='MovingAverageExponential',minval=1)
emain03=input.int(200,"EMAmaTua",group='MovingAverageExponential',minval=1)
ema01=ta.ema(src,emain01)
ema02=ta.ema(src,emain02)
ema03=ta.ema(src,emain03)
plot(showEMA?ema01:na,'EMAmaGirang',color=color.new(color.orange,0))
plot(showEMA?ema02:na,'EMAmaMuda',color=color.new(color.blue,0))
plot(showEMA?ema03:na,'EMAmaTua',color=color.new(color.red,0))
//**EMAeof
//**Conditionsof
emaLong=ema01>ema02andema02>ema03andlow>ema03
emaShort=ema01<ema02andema02<ema03andhigh<ema03
longCond=ta.crossover(k,d)andk<=23andemaLong
shortCond=ta.crossunder(k,d)andk>=77andemaShort
longClose=ta.crossunder(k,d)andk<=77
shortClose=ta.crossover(k,d)andk>=23
longCross=ta.crossover(ema01,ema02)
shortCross=ta.crossunder(ema01,ema02)
//**Conditioneof
//**Strategysof
ifcalcPeriodandlongCond
strategy.entry('long',strategy.long,when=longCond,comment='ENLong')
strategy.close('long',when=shortClose,comment='EXLong')
strategy.close('long',when=shortCross,comment='MDShort')
ifcalcPeriodandshortCond
strategy.entry('short',strategy.short,when=shortCond,comment='ENShort')
strategy.close('short',when=longClose,comment='EXShort')
strategy.close('short',when=longCross,comment='MDLong')
ifcalcPeriod==falseandta.crossover(ema01,ema02)orta.crossunder(ema01,ema02)
strategy.cancel('long')
strategy.cancel('short')
//**Strategyeof
//**Labelsof
entryText=str.tostring(strategy.position_avg_price,'##.###')
longText='Long Entry : '+entryText
shortText='Short Entry : '+entryText
noTrade='SleepingMode'
LongTrade=strategy.position_size>0
ShortTrade=strategy.position_size<0
Tekslabel=LongTrade?longText:ShortTrade?shortText:noTrade
xPosition=timenow+math.round(ta.change(time)*1)
yPosition=ta.highest(1)
labelColor=LongTrade?color.new(color.aqua,0):ShortTrade?color.new(color.red,0):color.new(color.gray,0)
textColor=LongTrade?color.new(color.black,0):ShortTrade?color.new(color.white,0):color.new(color.white,0)
lab_l=label.new(
xPosition,yPosition,Tekslabel,
color=labelColor,
textcolor=textColor,
style=label.style_label_left,
textalign=text.align_left,
xloc=xloc.bar_time,yloc=yloc.price)
label.delete(lab_l[1])
//**Strategyeof
Expand (116 lines)
