Script Name: 72s Strat- Backtesting Adaptive HMA+ pt.1
Author: io72signals
Description: This is a follow up to my previous publication of  Adaptive HMA+  few months ago, as a mean to provide some kind of initial backtesting tools. Which can be use to explore many possible strategies, optimise its settings to better conform user's pair/tf, and hopefully able to help tweaking your general strategy.

If you haven't read the study or use the indicator,...
PineScript code:

Pine Script™ strategy
72s Strat: Backtesting Adaptive HMA+ pt.1
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  2020  ©  io72signals  /  Antorio  Bergasdito
//@version=4
strategy("72s  Strategy:  Adaptive  Hull  Moving  Average+  pt.1",  shorttitle="72s  Strat:  Adaptive  HMA+  pt.1",  overlay=true,
          pyramiding=1,  initial_capital=1000,  commission_type=strategy.commission.cash_per_order,  commission_value=.5,
          slippage=3,  max_bars_back=1000)
atrBase    =  atr(21)
src            =  close
adaptPct  =  0.03141
//{  INPUTS
orderSize      =  input(0.1,  title="Order  Size  (in  Lot)",  step=.1,  group="ORDERS")
minProfit      =  input(1,  step=.1,  title="Base  Minimum  Profit  before  exit  (ATR)",  group="ORDERS")  *  atrBase
takeProfit    =  input(3,  step=.1,  title="Default  Target  Profit  (ATR)",  group="ORDERS")  *  atrBase
useSL              =  input(true,  title="Use  StopLoss",  group="ORDERS")
SLInput          =  input("Half  Distance  Zone",  title="Base  StopLoss  Point",
                                  options=["One  Distance  Zone",  "Half  Distance  Zone",  "Last  High/Low",  "ATR  Only"],  group="ORDERS")
maxSL              =  input(4.5,  step=.1,  title="Maximum  StopLoss  (ATR)",  group="ORDERS")  *  atrBase
doubleUp        =  input(false,  "Activate  2nd  order  with  xHMA+  exits",  group="ORDERS")        //If  enable,  set  pyramiding  to  at  least:  2
minLength      =  input(172,  title="Minimum:",  group="Adaptive  HMA+  Period",  inline="HMA+")
maxLength      =  input(233,  title="Maximum:",  group="Adaptive  HMA+  Period",  inline="HMA+")
flat                =  input(17,  title="Flat  Market  when  xHMA's  slope  below",  group="Market  Movement")
atrFast          =  input(14,  "Charged  if  ATR",  group="Market  Movement",  inline="volality",  minval=2,  maxval=34)
atrSlow          =  input(46,  ">=  ATR",  group="Market  Movement",  inline="volality",  minval=21,  maxval=120)
showZone        =  input(false,  title="Show  Adaptive  HMA+  Distance  Zone",  group="DISTANCE  ZONE")
mult                =  input(2.7,  title="Distance  (Envelope)  Multiplier",  step=.1,  group="DISTANCE  ZONE")
minorMin        =  input(89,  title="Minimum:",  group="Minor  Adaptive  HMA+  Period",  inline="mHMA+")
minorMax        =  input(121,  title="Maximum:",  group="Minor  Adaptive  HMA+  Period",  inline="mHMA+")
showMA            =  input(true,  title="Show  MA?",  group="OTHER")
useBg              =  input(true,  title="Background  color  to  differentiate  movement",  group="OTHER")
rsi                  =  rsi(input(close,"RSI  Source",  inline="RSI",  group="OTHER"),  input(14,  "RSI  Length",  inline="RSI",  group="OTHER"))
//}...inputs
//{  ADAPTIVE  HMA+
//Condition  to  adapt  to:
charged  =  atr(atrFast)  >  atr(atrSlow)                      //<--Volatility  Meter.  Change  it  to  whatever  match  your  strat/pair/tf.
//Dynamics
var  float  dynamicLength  =  avg(minLength,maxLength)
var  float  minorLength      =  avg(minorMin,minorMax)
dynamicLength      :=  iff(charged,  max(minLength,  dynamicLength  *  (1  -  adaptPct)),  min(maxLength,  dynamicLength  *  (1  +  adaptPct)))
minorLength          :=  iff(charged,  max(minorMin,  minorLength  *  (1  -  adaptPct)),  min(minorMax,  minorLength  *  (1  +  adaptPct)))
//Slope  calculation  to  determine  whether  market  is  in  trend,  or  in  consolidation  or  choppy,  or  might  about  to  change  current  trend
pi  =  atan(1)  *  4
highestHigh  =  highest(34),  lowestLow  =  lowest(34)
slope_range  =  25  /  (highestHigh  -  lowestLow)  *  lowestLow
calcslope(_ma)=>
        dt  =  (_ma[2]  -  _ma)  /  src  *  slope_range
        c  =  sqrt(1  +  dt  *  dt)
        xAngle  =  round(180  *  acos(1  /  c)  /  pi)
        maAngle  =  iff(dt  >  0,  -xAngle,  xAngle)
        maAngle

//MA  coloring+  to  mark  market  dynamics
dynColor(_ma,_col1a,_col1b,_col2a,_col2b,_col0)  =>
        slope  =  calcslope(_ma)
        slope  >=  flat  ?  charged?  _col1a  :  _col1b  :
          slope  <  flat  and  slope  >  -flat  ?  _col0  :
          slope  <=  -flat  ?  charged?  _col2a  :  _col2b  :  _col0
//Adaptive  HMA
xhma(_src,_length)  =>  _return  =  wma(2  *  wma(_src,  _length  /  2)  -  wma(_src,  _length),  floor(sqrt(_length)))
dynamicHMA  =  xhma(src,int(dynamicLength))              //<--Batman  -  Our  main  xHMA+
minorHMA  =  xhma(src,int(minorLength))                      //<--Robin    -  Faster  minor  xHMA+  (Optional).  Can  be  use  to  assist  for
                                                                                                //                        faster  entry,  slower  exit  point,  or  pullbacks  info  too.
_slope  =  calcslope(dynamicHMA)
plotchar(_slope,  "slope  is:",  "",  location.top)  //<--Output  current  slope  to  Data  Window,  for  our  reference  when  optimizing  Strategy
//Envelope  the  main  DynamicHMA  with  ATR  band,  just  one  way  to  approximate  current  price  distance  to  MA.  Other  usages/methods  may  vary.
upperTL  =  dynamicHMA  +  mult  *  atr(40)                ,    lowerTL  =  dynamicHMA  -  mult  *  atr(40)                      //<--Half  distance  zone
topTL  =  dynamicHMA  +  (mult*2)  *  atr(40)            ,    botTL  =  dynamicHMA  -  (mult*2)  *  atr(40)                  //<--One  distance  zone
stopupperTL  =  dynamicHMA  +  (mult/2)  *  atr(40),    stoplowerTL  =  dynamicHMA  -  (mult/2)  *  atr(40)      //<--Half  of  the  half.  If  need  ie.  tighter  SL  or  trailing
//Plotting  Distance  Zone
plot(showZone?upperTL:na,  color=color.green,  transp=72)
plot(showZone?lowerTL:na,  color=color.red,      transp=72)
plot(showZone?topTL:na,  color=color.gray,  transp=72)
plot(showZone?botTL:na,  color=color.gray,  transp=72)
sutl  =  plot(showZone?stopupperTL:na,  color=color.white,  transp=100)
sltl  =  plot(showZone?stoplowerTL:na,  color=color.white,  transp=100)
colZone  =  showZone?  color.purple:color.new(color.white,100)
fill(sutl,  sltl,  color=colZone,  transp=90)
plot(showMA?dynamicHMA:na,  "Adaptive  HMA+",  dynColor(dynamicHMA,  #6fbf73,  #c0f5ae,  #eb4d5c,  #f2b1d4,  color.yellow),  3)
plot(showMA?minorHMA:na,      "minor  HMA+",        dynColor(minorHMA,      #6fbf73,  #c0f5ae,  #eb4d5c,  #f2b1d4,  color.yellow),  1)
//Backgroud  color  to  differentiate  market  condition
notgreat  =  _slope  <  flat  and  _slope  >  -flat
bgcolor(useBg?  charged?  na  :  #afb4b9  :  na)
//EMA  200.  (Not  being  use  in  here.  But  since  they've  been  a  BFF  since  long,  thought  I'm  just  gonna  put  it  here..)
emma200  =  ema(close,200)  //,  plot(emma200)
//}...adaptive  HMA+
//{  SIGNALS
//Base;  When  HMA+  turn  to  a  darker  color  and  market  is  out  from  low  volatility
upSig  =  _slope  >=    flat  and  charged
dnSig  =  _slope  <=  -flat  and  charged
//Default  buy/sell,  when  market  switchs  to  the  above  base  condition,  and  typical  price  is  still  in  tolerated  distance,  and  RSI  is  on  the  right  side.
buy    =  upSig  and  not  upSig[1]  and  close>dynamicHMA  and  low<=upperTL    and  (rsi>51    andrsi<=70)
sell=dnSigandnotdnSig[1]andclose<dynamicHMAandhigh>=lowerTLand(rsi<49andrsi>=30)
//Alternativebuy/sell,whenpriceisabitfarfromMA,andRSIisstillonthesamesidebutalreadyonoversold/overbought(relatively).
overBuy=upSigandnotupSig[1]andrsi>70andclose>dynamicHMAandhl2>upperTLandminorHMA>dynamicHMA
overSell=dnSigandnotdnSig[1]andrsi<30andclose<dynamicHMAandhl2<lowerTLandminorHMA<dynamicHMA
//Alternativeadditionalbuy/sellwithdifferentexitsatRobin's.
secondBuy=(buyoroverBuy)andrsi[1]<rsi
secondSell=(selloroverSell)andrsi[1]>rsi
//Plot'emup
atrPos=0.2*atr(5)
plotshape(buy?dynamicHMA-atrPos:na,color=color.green,location=location.absolute,style=shape.labelup,text="buy",textcolor=color.white,size=size.small)
plotshape(sell?dynamicHMA+atrPos:na,color=color.red,location=location.absolute,style=shape.labeldown,text="sell",textcolor=color.white,size=size.small)
plotshape(overBuy?dynamicHMA-atrPos:na,color=color.green,location=location.absolute,style=shape.labelup,text="overBuy",textcolor=color.white,size=size.small)
plotshape(overSell?dynamicHMA+atrPos:na,color=color.red,location=location.absolute,style=shape.labeldown,text="overSell",textcolor=color.white,size=size.small)
plotshape(doubleUpandsecondBuy?dynamicHMA-atrPos*8:na,color=color.green,location=location.absolute,style=shape.labelup,text="+buy",textcolor=color.white,size=size.small)
plotshape(doubleUpandsecondSell?dynamicHMA+atrPos*8:na,color=color.red,location=location.absolute,style=shape.labeldown,text="+sell",textcolor=color.white,size=size.small)
//Alert
ifbuy
alert("Buysignalat"+tostring(close),alert.freq_once_per_bar_close)
ifsell
alert("Sellsignalat"+tostring(close),alert.freq_once_per_bar_close)
ifoverBuy
alert("OverBuysignalat"+tostring(close),alert.freq_once_per_bar_close)
ifoverSell
alert("OverSellsignalat"+tostring(close),alert.freq_once_per_bar_close)
ifdoubleUpandsecondBuy
alert("2ndBuysignalat"+tostring(close),alert.freq_once_per_bar_close)
ifdoubleUpandsecondSell
alert("2ndSellsignalat"+tostring(close),alert.freq_once_per_bar_close)
//}...signals
//{ORDERS
//(IuseLotjustbecauseit'showIusuallytrade,matchesmyflowwhenthinking/planning.Changethe"qty"in"strategy.entry()"belowtouseotherUOM.)
//Forexpairsare100,000unitsper1lot.Unitsper1lotvaryonnon-forexpairs,pleasecheckwithyourbrokerandchangeaccordinglyifnecessary.
//(ie:InMT4andMT5rightclickasymbolandthenclickSpecification.TheContractSizefieldtellshowmanyunitsareinonelot.)
standard1LotUnits=
syminfo.type=="forex"?100000:
syminfo.ticker=="XAUUSD"?100:
syminfo.ticker=="XAGUSD"?5000:
syminfo.type=="crypto"?1:1000
lotSize=standard1LotUnits*orderSize
pip()=>syminfo.mintick*(syminfo.type=="forex"?10:1)
//{StopLoss
SLHighMax=high+maxSL,SLLowMax=low-maxSL//<--MaximumStopLoss.IfachosenSL-pointfrominputabovehappen
//tobeoutsidethismaxpoint,thenthisonewillbeuseasSL.
lastHigh=highest(high,48)+(5*pip())//<--LastHigh/Low.IfuseasSL-point,adjustthelookbacklength
lastLow=lowest(low,48)-(5*pip())//accordingtowhereyourcomfortlies(andposition-size).
//DeliveringSLfrominputs
SLBuy=SLInput=="OneDistanceZone"?botTL:SLInput=="HalfDistanceZone"?lowerTL:
SLInput=="LastHigh/Low"?lastLow:SLInput=="ATROnly"?SLLowMax:SLLowMax
SLSell=SLInput=="OneDistanceZone"?topTL:SLInput=="HalfDistanceZone"?upperTL:
SLInput=="LastHigh/Low"?lastHigh:SLInput=="ATROnly"?SLHighMax:SLHighMax
//}---stopLoss
//
floatentryPrice=na,floatnormOrder=0,floatriskOrder=0
floatbuyTP=na,floatsellTP=na,floatbuySL=na,floatsellSL=na
entryPrice:=nz(entryPrice[1]),normOrder:=nz(normOrder[1]),riskOrder:=nz(riskOrder[1])
buyTP:=nz(buyTP[1]),sellTP:=nz(sellTP[1]),buySL:=nz(buySL[1]),sellSL:=nz(sellSL[1])
//ThispartwillalsomakeyourTP/SLchangedynamicallyifthere'sanewsignalwhileyouhaveanopenposition.
//IfyouwanttofirethisTP/SLonlyinanewposition,thenadd"strategy.position_size==0"
if(buyorselloroverBuyoroverSell)//andstrategy.position_size==0
entryPrice:=close
ifbuyorsellandstrategy.position_size==0
normOrder:=1
ifoverBuyoroverSellandstrategy.position_size==0
riskOrder:=1
buyTP:=high+takeProfit
sellTP:=low-takeProfit
ifbuyoroverBuy
buySL:=SLLowMax<SLBuy?SLBuy:SLLowMax
ifselloroverSell
sellSL:=SLHighMax>SLSell?SLSell:SLHighMax
//TrailingMinimum-Profit.--Justasimplehelpertopreventprematureexitrule.Oratleasttohavea
//changetogetbreak-even(aftercommission)ifmarketturnsitsbackonus,beforeheadingtostoplossarea.
minBuyProfit=strategy.position_avg_price+minProfit
minSellProfit=strategy.position_avg_price-minProfit
//{ExitPoints
//TP/SLExits
stopLossBuy=useSL?low<=buySL:na
stopLossSell=useSL?high>=sellSL:na
takeProfitBuy=high>=buyTP
takeProfitSell=low<=sellTP
//SimplifiedRSIExits
RSIexitBuy=crossunder(rsi,70)orrsi<50
RSIexitSell=crossover(rsi,30)orrsi>50
//ExitConditions
exitBuy=(close>=minBuyProfitand(RSIexitBuyorcrossunder(close,dynamicHMA)))orstopLossBuyortakeProfitBuy
exitSell=(close<=minSellProfitand(RSIexitSellorcrossover(close,dynamicHMA)))orstopLossSellortakeProfitSell
exitoverBuy=(close>=minBuyProfitand(crossunder(rsi,45)or(open<stopupperTLandhl2<stopupperTL)))or(open<dynamicHMAandrsi<60)
orstopLossBuyortakeProfitBuy
exitoverSell=(close<=minSellProfitand(crossover(rsi,55)or(open>stoplowerTLandhl2>stoplowerTL)))or(open>dynamicHMAandrsi>40)
orstopLossSellortakeProfitSell
//Alternative2ndExitsatRobin's(orSL)
exitSecondBuy=(close>=minBuyProfitandcrossunder(close,minorHMA))orstopLossBuy
exitSecondSell=(close<=minSellProfitandcrossover(close,minorHMA))orstopLossSell

//PlottingandAlertforExits
inBuyExit=strategy.position_size>0and((normOrder==1andexitBuy)or(riskOrder==1andexitoverBuy))
inSellExit=strategy.position_size<0and((normOrder==1andexitSell)or(riskOrder==1andexitoverSell))
in2ndBuyExit=strategy.position_size>0and(doubleUpandexitSecondBuy)
in2ndSellExit=strategy.position_size<0and(doubleUpandexitSecondSell)
ifinBuyExitorinSellExit
ifnormOrder==1andexitBuy
normOrder:=0,alert("CloseBuyPosition/sat"+tostring(close),alert.freq_once_per_bar_close)
ifnormOrder==1andexitSell
normOrder:=0,alert("CloseSellPosition/sat"+tostring(close),alert.freq_once_per_bar_close)
ifriskOrder==1andexitoverBuy
riskOrder:=0,alert("CloseoverBuyPosition/sat"+tostring(close),alert.freq_once_per_bar_close)
ifriskOrder==1andexitoverSell
riskOrder:=0,alert("CloseoverSellPosition/sat"+tostring(close),alert.freq_once_per_bar_close)
ifin2ndBuyExit
alert("Close2ndBuyPosition/sat"+tostring(close),alert.freq_once_per_bar_close)
ifin2ndSellExit
alert("Close2ndSellPosition/sat"+tostring(close),alert.freq_once_per_bar_close)

plotchar(inBuyExit,color=color.green,location=location.abovebar,char="ⓧ",size=size.tiny)
plotchar(inSellExit,color=color.red,location=location.belowbar,char="ⓧ",size=size.tiny)
plotchar(in2ndBuyExit,color=color.teal,location=location.abovebar,char="ⓧ",size=size.tiny)
plotchar(in2ndSellExit,color=color.maroon,location=location.belowbar,char="ⓧ",size=size.tiny)
//}---exitpoints
//{Actions
//ENTRIES
strategy.entry("buy",strategy.long,qty=lotSize,when=buy)
strategy.entry("sell",strategy.short,qty=lotSize,when=sell)
strategy.entry("overBuy",strategy.long,qty=lotSize,when=overBuy)
strategy.entry("overSell",strategy.short,qty=lotSize,when=overSell)
ifdoubleUp
strategy.entry("2ndBuy",strategy.long,qty=lotSize,when=secondBuy)
strategy.entry("2ndSell",strategy.short,qty=lotSize,when=secondSell)
//EXITS
//Weusejust"strategy.close"becausewealreadysetlimitconditionsaboveforSLandTP,firesatcandleclose.Ifyouwantto
//separateexitdataorexitattheexactSL/TPyoucanaddsuchas:strategy.exit("exitbuy",from_entry="buy",stop=buySL,limit=buyTP)
//accordingly.AnddeletestopLossBuy,stopLossSell,takeProfitBuy,takeProfitSelldefinitionsfromabove.
strategy.close("buy",when=exitBuy,comment="closebuy")
strategy.close("sell",when=exitSell,comment="closesell")
strategy.close("overBuy",when=exitoverBuy,comment="closeoverBuy")
strategy.close("overSell",when=exitoverSell,comment="closeoverSell")
ifdoubleUp
strategy.close("2ndBuy",when=exitSecondBuy,comment="close2ndBuy")
strategy.close("2ndSell",when=exitSecondSell,comment="close2ndSell")
//}---actions
orderCol=strategy.position_size>0?color.green:strategy.position_size<0?color.red:na
//plot(strategy.position_size>0?minBuyProfit:strategy.position_size<0?minSellProfit:na,color=orderCol,style=plot.style_linebr,linewidth=1,title="MinimumProfit")
plot(strategy.position_size!=0?entryPrice:na,style=plot.style_cross,transp=50)
plot(useSLandstrategy.position_size>0?buySL:useSLandstrategy.position_size<0?sellSL:na,color=color.red,style=plot.style_cross,linewidth=1,title="StopLoss",transp=50)
plot(strategy.position_size>0?buyTP:strategy.position_size<0?sellTP:na,color=color.green,style=plot.style_cross,linewidth=1,title="TakeProfit",transp=50)
//}...orders
//{------------------------------------------------------------------------
//Belowisjustfancystuffapproximatinggaininpips.Youprobablydon'tneedthis.
//(AlsoI'mnottoosurethisistherightwaycalculatingpipgaininpine.Ifsomebodyknowshow,kindlycorrectmeplease)
mUnit=lotSize*pip()
ppip=round((strategy.grossprofit-strategy.grossprofit[1])/syminfo.pointvalue/mUnit,1)
lpip=round((strategy.grossloss-strategy.grossloss[1])/syminfo.pointvalue/mUnit,1)
pipGain=round((strategy.grossprofit/syminfo.pointvalue)/mUnit)
pipLoss=round((strategy.grossloss/syminfo.pointvalue)/mUnit)
avg_ppip=round((pipGain/strategy.wintrades),1)
pctProfit=round(strategy.wintrades/strategy.closedtrades*100,2)
maxDD=ceil(strategy.max_drawdown/syminfo.pointvalue/mUnit)//checkifourmargincanhandleDD'spips*orderSize
vartxt2=""
txt="Totaltrades:"+tostring(strategy.closedtrades)+"\n("+tostring(pctProfit)+"%)Win:"+tostring(strategy.wintrades)+"/Loss:"+tostring(strategy.losstrades)+
"\nAveragewinpipspertrade:"+tostring(avg_ppip)+"pips\n\nApproximate(*giventake)\nTotalPipGain:"+tostring(pipGain)+"pips"+
"\nTotalPipLoss:"+tostring(pipLoss)+"pips"+"\n\nMaxDrawdownsofar:"+tostring(maxDD)+"pips"
ifstrategy.wintrades>strategy.wintrades[1]
txt2:="\n\nLastclosedtrade:Bagged"+tostring(ppip)+"pips👻"
ifstrategy.losstrades>strategy.losstrades[1]
txt2:="\n\nLastclosedtrade:Blew"+tostring(lpip)+"pips😪"
txt+=txt2
labelpvtLabel=label.new(time,lowestLow,text=txt,
color=color.new(color.white,100),xloc=xloc.bar_time,style=label.style_label_left,textcolor=color.gray,textalign=text.align_left)
label.set_x(pvtLabel,label.get_x(pvtLabel)+((time-time[1])*21))
label.delete(pvtLabel[1])
//}
Expand (313 lines)
