Script Name: [CM]EMA Trend Cross STRAT
Author: ColinMccann18
Description: VISUALLY REPRESENTS THE CROSSING OF 8,13,21,55 EMA'S FROM KROWNS TA PROGRAM

Hello everybody!  I was curious and wanted to see how the Strat described in one of the modules would look coded. So here we are, a clear cut visual representation of the methods talked about in the course from the EMA Module. Enjoy!

(Instructions)
Whenever the 8,13,21 all cross above...
PineScript code:

Pine Script™ strategy
[CM]EMA Trend Cross STRAT
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  ColinMccann18
//@version=4
//  +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//  --------------------------------------------------------------RULES------------------------------------------------------------------------------
//  -  VISUALLY  REPRESENTS  THE  CROSSING  OF  8,13,21,55  EMA'S  FROM  KROWNS  PROGRAM
strategy(title="CM  EMA  Trend  Cross  STRAT",  shorttitle="CM  EMA  Strat",  overlay=true)
ema8    =  ema(close,8)
ema13  =  ema(close,  13)
ema21  =  ema(close,  21)
ema55  =  ema(close,  55)
//PLOT
plot(ema8,    title="EMA  1",linewidth=2,  color=#00eeff)
plot(ema13,  title="EMA  2",linewidth=2,  color=#fff900)
plot(ema21,  title="EMA  3",linewidth=2,  color=#42ff0f)
plot(ema55,  title="EMA  4",linewidth=2,  color=#8b49ff)
//LOGIC---------------------------------------------------------------------------------------------------------------------------------
emacrossover  =  crossover(ema21,  ema55)  and  ema8  and  ema13  >  ema55
emacrossunder  =  crossunder(ema21,  ema55)  and  ema8  and  ema13  <  ema55
//Long----------------------------------------------------------------------------------------------------------------------------------
longCondition  =  emacrossover
closelongCondition  =  emacrossunder
strategy.entry("Long",  strategy.long,  qty=na,  when=longCondition)
strategy.close("Close  Long",  when=closelongCondition)
//Short----------------------------------------------------------------------------------------------------------------------------------
shortCondition  =  emacrossunder
closeshortCondition  =  emacrossover
strategy.entry("Short",  strategy.short,qty=na,  when=shortCondition)
strategy.close("Close  Short",  when=closeshortCondition)
Expand (39 lines)
