Script Name: [DuDu95] SSL 4C MACD Laugerre RSI Strategy
Author: DuDu95
Description: Hello Guys! Nice to meet you all!
Before I start, my nickname has changed to 'DuDu95'!!
This is the Strategy introduced by youtube channel.
I made this based on the open source indicator by kevinmck100, vkno422, KivancOzbilgic. Thank you All!

### Entry Logic
1. Long Entry Logic
- close > SSL Hybrid baseline upper k (keltner channel)
- macd signal > 0 and current...
PineScript code:

Pine Script™ strategy
[DuDu95] SSL 4C MACD Laugerre RSI Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  DuDu95
//  Thanks  to  myncrypto,  jason5480,  kevinmck100
//  @version=5
strategy(title                    =  '[DuDu95]  SSL  4C  MACD  Laugerre  RSI  Strategy',
            shorttitle                =  '[D]  SMR  Strategy',
            overlay                      =  true,
            pyramiding                =  0,
            currency                    =  currency.USD,
            default_qty_type    =  strategy.percent_of_equity,
            default_qty_value  =  100,
            commission_value    =  0.1,
            initial_capital      =  100000,
            max_bars_back          =  500,
            max_lines_count      =  150,
            max_labels_count    =  300)
//  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//                                            Time,  Direction,  Etc  -  Basic  Settings  Inputs
//  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//  1.  Time:  Based  on  UTC  +09:00
i_start                                  =  input.time  (defval  =  timestamp("20  Jan  1990  00:00  +0900"),  title  =  "Start  Date",  tooltip  =  "Choose  Backtest  Start  Date",  inline  =  "Start  Date",  group  =  "Time"  )
i_end                                      =  input.time  (defval  =  timestamp("20  Dec  2030  00:00  +0900"),  title  =  "End  Date",  tooltip  =  "Choose  Backtest  End  Date",  inline  =  "End  Date",  group  =  "Time"  )
inTime                                    =  time  >=  i_start  and  time  <=  i_end
//  2.  Inputs  for  direction:  Long?  Short?  Both?
i_longEnabled                      =  input.bool  (defval  =  true  ,  title  =  "Long?",  tooltip  =  "Enable  Long  Position  Trade?",  inline  =  "Long  /  Short",  group  =  "Long  /  Short"  )
i_shortEnabled                    =  input.bool  (defval  =  true  ,  title  =  "Short?",  tooltip  =  "Enable  Short  Position  Trade?",  inline  =  "Long  /  Short",  group  =  "Long  /  Short"  )
//  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//                                            Filter  -  Inputs,  Indicaotrs
//  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//  3.  Use  Filters?  What  Filters?
i_ATRFilterOn                      =  input.bool  (defval  =  false  ,  title  =  "ATR  Filter  On?",  tooltip  =  "ATR  Filter  On?  Order  will  not  be  made  unless  filter  condition  is  fulfilled",  inline  =  "1",  group  =    "Filters")
i_ATRFilterLen                    =  input.int    (defval  =  14  ,        title  =  "Length  for  ATR  Filter",  minval  =  1  ,  maxval  =  100  ,  step  =  1  ,  tooltip  =  "",  inline  =  "2",  group  =  "Filters")
i_ATRSMALen                          =  input.int    (defval  =  40  ,        title  =  "SMA  Length  for  ATR  SMA",  minval  =  1  ,  maxval  =  100000  ,  step  =  1  ,  tooltip  =  "ATR  should  be  bigger  than  this",  inline  =  "2",  group  =  "Filters")
bool  i_ATRFilter                =  ta.atr(i_ATRFilterLen)  >=  ta.sma(ta.atr(length  =  i_ATRFilterLen),  i_ATRSMALen)  ?  true  :  false
bool  filterFulfilled        =  not  i_ATRFilterOn  or  i_ATRFilter
//  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//                                            Strategy  Logic  (Entry  &  Exit  Condition)  -  Inputs,  Indicators  for  Strategy
//  ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//  Inputs  for  Strategy  Indicators
////  1.  SSL  Hybrid  Baseline
i_useTrueRange                      =  input.bool      (defval  =  true,  title  =  "use  true  range  for  Keltner  Channel?",  tooltip  =  "",  inline  =  "1",  group  =  "1:  SSL  Hybrid")
i_maType                                  =  input.string  (defval  ='EMA',  title='Baseline  Type',  options=['SMA',  'EMA',  'DEMA',  'TEMA',  'LSMA',  'WMA',  'VAMA',  'TMA',  'HMA',  'McGinley'],  inline="2",  group  =  "1:  SSL  Hybrid")
i_len                                        =  input.int        (defval  =30,        title='Baseline  Length',  inline="2",  group  =  "1:  SSL  Hybrid")
i_multy                                    =  input.float    (defval  =  0.2,    title='Base  Channel  Multiplier',  minval  =  0,maxval=100,step=0.05,inline="3",group="1:SSLHybrid")
i_volatility_lookback=input.int(defval=10,title='Volatilitylookbacklength(forVAMA)',inline='4',group="1:SSLHybrid")
tema(src,len)=>
ema1=ta.ema(src,len)
ema2=ta.ema(ema1,len)
ema3=ta.ema(ema2,len)
3*ema1-3*ema2+ema3
f_ma(type,src,len)=>
floatresult=0
iftype=='TMA'
result:=ta.sma(ta.sma(src,math.ceil(len/2)),math.floor(len/2)+1)
result
iftype=='LSMA'
result:=ta.linreg(src,len,0)
result
iftype=='SMA'//Simple
result:=ta.sma(src,len)
result
iftype=='EMA'//Exponential
result:=ta.ema(src,len)
result
iftype=='DEMA'//DoubleExponential
e=ta.ema(src,len)
result:=2*e-ta.ema(e,len)
result
iftype=='TEMA'//TripleExponential
e=ta.ema(src,len)
result:=3*(e-ta.ema(e,len))+ta.ema(ta.ema(e,len),len)
result
iftype=='WMA'//Weighted
result:=ta.wma(src,len)
result
iftype=='VAMA'//VolatilityAdjusted
///Copyright©2019topresent,JorisDuyck(JD)
mid=ta.ema(src,len)
dev=src-mid
vol_up=ta.highest(dev,i_volatility_lookback)
vol_down=ta.lowest(dev,i_volatility_lookback)
result:=mid+math.avg(vol_up,vol_down)
result
iftype=='HMA'//Hull
result:=ta.wma(2*ta.wma(src,len/2)-ta.wma(src,len),math.round(math.sqrt(len)))
result
iftype=='McGinley'
mg=0.0
mg:=na(mg[1])?ta.ema(src,len):mg[1]+(src-mg[1])/(len*math.pow(src/mg[1],4))
result:=mg
result
result
////1-1.SSLHybridKeltnerBaselineChannel
BBMC=f_ma(i_maType,close,i_len)//BaseLone
Keltma=f_ma(i_maType,close,i_len)
range_1=i_useTrueRange?ta.tr:high-low
rangema=ta.ema(range_1,i_len)
upperk=Keltma+rangema*i_multy
lowerk=Keltma-rangema*i_multy
////2.4ColorMACD
i_fastMA=input.int(defval=12,title='MACDfastMA',minval=7,inline='1',group='2:4ColorMACD')
i_slowMA=input.int(defval=26,title='MACDslowMA',minval=7,inline='1',group='2:4ColorMACD')
i_signalLength=input.int(defval=9,title='MACDsignalLength',minval=1,inline='2',group='2:4ColorMACD')
[currMacd,_,_]=ta.macd(source=close[0],fastlen=i_fastMA,slowlen=i_slowMA,siglen=9)
[prevMacd,_,_]=ta.macd(source=close[1],fastlen=i_fastMA,slowlen=i_slowMA,siglen=9)
signalLine=ta.sma(currMacd,i_signalLength)
////3.LaguerreRSI
i_src=input(defval=close,title='LaguerreRSIsource',inline='1',group='3:LaguerreRSI')
i_alpha=input.float(defval=0.2,title='Alpha',inline='2',minval=0,maxval=1,step=0.1,group='3:LaguerreRSI')
i_overbought=input.int(defval=80,title='OverboughtLevel?',minval=50,maxval=99,inline='4',group='3:LaguerreRSI')
i_oversold=input.int(defval=20,title='OverboughtLevel?',minval=0,maxval=50,inline='4',group='3:LaguerreRSI')
//i_colorchange=input.bool(defval=false,title='ChangeColor?',inline='3',group='3:LaguerreRSI')
floatLaRSIResult=0
gamma=1-i_alpha
L0=0.0
L0:=(1-gamma)*i_src+gamma*nz(L0[1])
L1=0.0
L1:=-gamma*L0+nz(L0[1])+gamma*nz(L1[1])
L2=0.0
L2:=-gamma*L1+nz(L1[1])+gamma*nz(L2[1])
L3=0.0
L3:=-gamma*L2+nz(L2[1])+gamma*nz(L3[1])
cu=(L0>L1?L0-L1:0)+(L1>L2?L1-L2:0)+(L2>L3?L2-L3:0)
cd=(L0<L1?L1-L0:0)+(L1<L2?L2-L1:0)+(L2<L3?L3-L2:0)
temp=cu+cd==0?-1:cu+cd
LaRSI=temp==-1?0:cu/temp
LaRSIResult:=LaRSI*100
//EntryConditionforLongandShort
////1.Condition1:SSLHybrid
boolbullSSL=close>upperk
boolbearSSL=close<lowerk
////2.Condition2:4ColorMACD
boolbullSignalMACD=signalLine>0
boolbearSignalMACD=signalLine<0
boolbull4cMACD=currMacd>prevMacdandprevMacd>0
boolbear4cMACD=currMacd<prevMacdandprevMacd<0
////3.Condition3
boolbullLaRSI=LaRSIResult<i_overbought
boolbearLaRSI=LaRSIResult>i_oversold
//Plot:Indicators
////1.SSLHybrid
varbullSSLColor=#00c3ff
varbearSSLColor=#ff0062
color_bar=color.new(color=close>upperk?bullSSLColor:close<lowerk?bearSSLColor:color.gray,transp=0)
plot(series=BBMC,title='MABaseline',color=color_bar,linewidth=1,style=plot.style_line)
i_show_color_bar=input.bool(defval=true,title="ColorBars",inline="2",group="Strategy:Drawings")
barcolor(i_show_color_bar?color_bar:na)
up_channel=plot(upperk,color=color_bar,title='BaselineUpperChannel')
low_channel=plot(lowerk,color=color_bar,title='BasilineLowerChannel')
fill(up_channel,low_channel,color.new(color=color_bar,transp=90))
////2.MACDLine
varbull4cMACDColor=color.lime
varbear4cMACDColor=color.orange
MACDbgColor=color.new(color=bull4cMACDandbullSignalMACD?bull4cMACDColor:bear4cMACDandbearSignalMACD?bear4cMACDColor:na,transp=notbull4cMACDandnotbear4cMACD?100:80)
bgcolor(color=MACDbgColor,title="MACDCondition")
//plotColor=currMacd>0?currMacd>prevMacd?color.lime:color.green:currMacd<prevMacd?color.maroon:color.red
//plot(currMacd,style=plot.style_columns,color=color.new(plotColor,20),linewidth=3)
//plot(0,title='Zeroline',linewidth=1,color=color.new(color.gray,0))
//plot(signalLine,color=color.new(color.white,0),title='Signal')
////3.LaguerreRSI
varoverboughtColor=color.blue
varoversoldColor=color.aqua
LaRSIColor=color.new(color=LaRSIResult>i_overbought?overboughtColor:LaRSIResult<i_oversold?oversoldColor:na,transp=90)
bgcolor(color=LaRSIColor,title="LaRSICondition")
//lineColor=i_colorchange?LaRSI>LaRSI[1]?color.green:color.red:color.teal
//plot(LaRSIResult,title='LaRSI',linewidth=2,color=color.new(color=lineColor,transp=0))
//plot(i_oversold,linewidth=1,color=color.new(color.maroon,0))
//plot(i_overbought,linewidth=1,color=color.new(color.maroon,0))
//////Entry,Exit
//Long,ShortLogicwithIndicator
//BasicCond+Long,ShortEntryCondition
boollongCond=(i_longEnabledandinTime)and(bullSSLandbullSignalMACDandbull4cMACDandbullLaRSI)
boolshortCond=(i_shortEnabledandinTime)and(bearSSLandbearSignalMACDandbear4cMACDandbearLaRSI)
//BasicCond+Long,ShortExitCondition
boolcloseLong=(i_longEnabled)and(bearSSLorbearSignalMACD)
boolcloseShort=(i_shortEnabled)and(bullSSLorbullSignalMACD)
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//PositionControl
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//Long,ShortEntryCondition+NotenteredPositionYet
boolopenLong=longCondandnot(strategy.opentrades.size(strategy.opentrades-1)>0)andfilterFulfilled
boolopenShort=shortCondandnot(strategy.opentrades.size(strategy.opentrades-1)<0)andfilterFulfilled
boolenteringTrade=openLongoropenShort
floatentryBarIndex=bar_index
//Long,ShortEntryFulfilledorAlreadyEntered
boolinLong=openLongorstrategy.opentrades.size(strategy.opentrades-1)>0andnotcloseLong
boolinShort=openShortorstrategy.opentrades.size(strategy.opentrades-1)<0andnotcloseShort
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//StopLoss-Inputs,Indicaotrs
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
////UseSL?TSL?
i_useSLTP=input.bool(defval=true,title="EnableSL&TP?",tooltip="",inline="1",group="StopLoss")
i_tslEnabled=input.bool(defval=false,title="EnableTrailingSL?",tooltip="EnableStopLoss&TakeProfit?\n\EnableTrailingSL?",inline="1",group="StopLoss")
//i_breakEvenAfterTP=input.bool(defval=false,title='EnableBreakEvenAfterTP?',tooltip='WhenTakeProfitpricetargetishit,movetheStopLosstotheentryprice(ortoamorestrictpricedefinedbytheStopLoss%/ATRMultiplier).',inline='2',group='StopLoss/TakeProfit')
////SlOptions
i_slType=input.string(defval="ATR",title="StopLossType",options=["Percent","ATR","PreviousLL/HH"],tooltip="StopLossbasedon%?ATR?",inline="3",group="StopLoss")
i_slATRLen=input.int(defval=14,title="ATRLength",minval=1,maxval=200,step=1,inline="4",group="StopLoss")
i_slATRMult=input.float(defval=3,title="ATRMultiplier",minval=1,maxval=200,step=0.1,tooltip="",inline="4",group="StopLoss")
i_slPercent=input.float(defval=3,title="Percent",tooltip="",inline="5",group="StopLoss")
i_slLookBack=input.int(defval=30,title="Lowest/HighestPriceBeforeEntry",group="StopLoss",inline="6",minval=1,maxval=200,step=1,tooltip="LookbacktofindtheLowestPrice.\nStopLossisdeterminedbytheLowestpriceofthelookbackperiod.TakeProfitisderivedfromthisalsobymultiplyingtheStopLossvaluebytheRisk:Rewardmultiplier.")
//FunctionsforStopLoss
floatopenAtr=ta.valuewhen(condition=enteringTrade,source=ta.atr(i_slATRLen),occurrence=0)
floatopenLowest=ta.valuewhen(condition=openLong,source=ta.lowest(low,i_slLookBack),occurrence=0)
floatopenHighest=ta.valuewhen(condition=openShort,source=ta.highest(high,i_slLookBack),occurrence=0)
f_getLongSLPrice(source)=>
switchi_slType
"Percent"=>source*(1-(i_slPercent/100))
"ATR"=>source-(i_slATRMult*openAtr)
"PreviousLL/HH"=>openLowest
=>na
f_getShortSLPrice(source)=>
switchi_slType
"Percent"=>source*(1+(i_slPercent/100))
"ATR"=>source+(i_slATRMult*openAtr)
"PreviousLL/HH"=>openHighest
=>na
//CalculateStopLoss
varfloatlongSLPrice=na
varfloatshortSLPrice=na
boollongTPExecuted=false
boolshortTPExecuted=false
longSLPrice:=if(inLongandi_useSLTP)
if(openLong)
f_getLongSLPrice(close)
else
//1.TrailingStopLoss
ifi_tslEnabled
stopLossPrice=f_getLongSLPrice(high)
math.max(stopLossPrice,nz(longSLPrice[1]))
//2.NormalStopLoss
else
nz(source=longSLPrice[1],replacement=0)
else
na
shortSLPrice:=if(inShortandi_useSLTP)
if(openShort)
f_getShortSLPrice(close)
else
//1.TrailingStopLoss
ifi_tslEnabled
stopLossPrice=f_getShortSLPrice(low)
math.min(stopLossPrice,nz(shortSLPrice[1]))
//2.NormalStopLoss
else
nz(source=shortSLPrice[1],replacement=999999.9)
else
na
//Plot:StopLossofLong,ShortEntry
varlongSLPriceColor=color.new(color.maroon,0)
plot(series=longSLPrice,title='LongStopLoss',color=longSLPriceColor,linewidth=1,style=plot.style_linebr,offset=1)
varshortSLPriceColor=color.new(color.maroon,0)
plot(series=shortSLPrice,title='ShortStopLoss',color=shortSLPriceColor,linewidth=1,style=plot.style_linebr,offset=1)
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//TakeProfit-Inputs,Indicaotrs
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
i_useTPExit=input.bool(defval=true,title="UseTakeProfit?",tooltip="",inline="1",group="TakeProfit")
i_RRratio=input.float(defval=1.8,title="R:RRatio",minval=0.1,maxval=200,step=0.1,tooltip="R:RRatio>RiskRewardRatio?ItwillautomaticallysetTakeProfit%basedonStopLoss",inline="2",group="TakeProfit")
i_tpQuantityPerc=input.float(defval=50,title='TakeProfitQuantity%',minval=0.0,maxval=100,step=1.0,tooltip='%ofpositionclosedwhentptargetismet.',inline="34",group='TakeProfit')
varfloatlongTPPrice=na
varfloatshortTPPrice=na
f_getLongTPPrice()=>
close+i_RRratio*math.abs(close-f_getLongSLPrice(close))
f_getShortTPPrice()=>
close-i_RRratio*math.abs(close-f_getShortSLPrice(close))
longTPPrice:=if(inLongandi_useSLTP)
if(openLong)
f_getLongTPPrice()
else
nz(source=longTPPrice[1],replacement=f_getLongTPPrice())
else
na
shortTPPrice:=if(inShortandi_useSLTP)
if(openShort)
f_getShortTPPrice()
else
nz(source=shortTPPrice[1],replacement=f_getShortTPPrice())
else
na
//Plot:TakeProfitofLong,ShortEntry
varlongTPPriceColor=color.new(color.teal,0)
plot(series=longTPPrice,title='LongTakeProfit',color=longTPPriceColor,linewidth=1,style=plot.style_linebr,offset=1)
varshortTPPriceColor=color.new(color.teal,0)
plot(series=shortTPPrice,title='ShortTakeProfit',color=shortTPPriceColor,linewidth=1,style=plot.style_linebr,offset=1)
//Plot:EntryPrice
varposColor=color.new(color.white,0)
plot(series=strategy.opentrades.entry_price(strategy.opentrades-1),title='PositionEntryPrice',color=posColor,linewidth=1,style=plot.style_linebr)
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//Quantity-Inputs
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
i_useRiskManangement=input.bool(defval=true,title="UseRiskManangement?",tooltip="",inline="1",group="Quantity")
i_riskPerTrade=input.float(defval=3,title="RiskPerTrade(%)",minval=0,maxval=100,step=0.1,tooltip="UseRiskManangementbyQuantityControl?",inline="2",group="Quantity")
//i_leverage=input.float(defval=2,title="Leverage",minval=0,maxval=100,step=0.1,tooltip="Leverage",inline="3",group="Quantity")
floatqtyPercent=na
floatentryQuantity=na
f_calQtyPerc()=>
if(i_useRiskManangement)
riskPerTrade=(i_riskPerTrade)/100//1번거래시3%손실
stopLossPrice=openLong?f_getLongSLPrice(close):openShort?f_getShortSLPrice(close):na
riskExpected=math.abs((close-stopLossPrice)/close)//손절가랑6%차이
riskPerTrade/riskExpected//0~1
else
1
f_calQty(qtyPerc)=>
math.min(math.max(0.000001,strategy.equity/close*qtyPerc),1000000000)

//TPExecution
longTPExecuted:=strategy.opentrades.size(strategy.opentrades-1)>0and(longTPExecuted[1]orstrategy.opentrades.size(strategy.opentrades-1)<strategy.opentrades.size(strategy.opentrades-1)[1]orstrategy.opentrades.size(strategy.opentrades-1)[1]==0andhigh>=longTPPrice)
shortTPExecuted:=strategy.opentrades.size(strategy.opentrades-1)<0and(shortTPExecuted[1]orstrategy.opentrades.size(strategy.opentrades-1)>strategy.opentrades.size(strategy.opentrades-1)[1]orstrategy.opentrades.size(strategy.opentrades-1)[1]==0andlow<=shortTPPrice)
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//PlotLabel,Boxes,Results,Etc
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
i_showSimpleLabel=input.bool(false,"ShowSimpleLabelforEntry?",group="Strategy:Drawings",inline="1",tooltip="")
i_showLabels=input.bool(true,"ShowTradeExitLabels",group="Strategy:Drawings",inline="1",tooltip="UsefullabelstoidentifyProfit/Lossandcumulativeportfoliocapitalaftereachtradecloses.\n\nAlsonotethatTradingViewlimitsthemaxnumberof'boxes'thatcanbedisplayedonachart(max500).ThismeanswhenyoulookbackfarenoughonthechartyouwillnotseetheTP/SLboxes.Howeveryoucancheckthisoptiontoidentifywheretradesexited.")
i_showDashboard=input.bool(true,"ShowDashboard",group="Strategy:Drawings",inline="2",tooltip="ShowBacktestResults.BacktestDates,Win/LoseRates,Etc.")
//Plot:LabelforLong,ShortEntry
varopenLongColor=color.new(#2962FF,0)
varopenShortColor=color.new(#FF1744,0)
varentryTextColor=color.new(color.white,0)
if(openLongandi_showSimpleLabel)
label.new(x=bar_index,y=na,text='Open',yloc=yloc.belowbar,color=openLongColor,style=label.style_label_up,textcolor=entryTextColor)
entryBarIndex:=bar_index
if(openShortandi_showSimpleLabel)
label.new(x=bar_index,y=na,text='Close',yloc=yloc.abovebar,color=openShortColor,style=label.style_label_down,textcolor=entryTextColor)
entryBarIndex:=bar_index
floatprevEntryPrice=strategy.closedtrades.entry_price(strategy.closedtrades-1)
floatpnl=strategy.closedtrades.profit(strategy.closedtrades-1)
floatprevExitPrice=strategy.closedtrades.exit_price(strategy.closedtrades-1)
f_enteringTradeLabel(x,y,qty,entryPrice,slPrice,tpPrice,rrRatio,direction)=>
ifi_showLabels
labelStr=("TradeStart"
+"\nDirection:"+direction
+"\nRiskPerTrade:"+str.tostring(i_useRiskManangement?i_riskPerTrade:100,"#.##")+"%"
+"\nExpectedRisk:"+str.tostring(math.abs((close-slPrice)/close)*100,"#.##")+"%"
+"\nEntryPositionQty:"+str.tostring(math.abs(qty*100),"#.##")+"%"
+"\nEntryPrice:"+str.tostring(entryPrice,"#.##"))
+"\nStopLossPrice:"+str.tostring(slPrice,"#.##")
+"\nTakeProfitPrice:"+str.tostring(tpPrice,"#.##")
+"\nRisk-RewardRatio:"+str.tostring(rrRatio,"#.##")
label.new(x=x,y=y,text=labelStr,color=color.new(color.blue,60),textcolor=color.white,style=label.style_label_up)
f_exitingTradeLabel(x,y,entryPrice,exitPrice,direction)=>
ifi_showLabels
labelStr=("TradeResult"
+"\nDirection:"+direction
+"\nEntryPrice:"+str.tostring(entryPrice,"#.##")
+"\nExitPrice:"+str.tostring(exitPrice,"#.##")
+"\nGain%:"+str.tostring(direction=='Long'?-(entryPrice-exitPrice)/entryPrice*100:(entryPrice-exitPrice)/entryPrice*100,"#.##")+"%")
label.new(x=x,y=y,text=labelStr,color=pnl>0?color.new(color.green,60):color.new(color.red,60),textcolor=color.white,style=label.style_label_down)
f_fillCell(_table,_column,_row,_title,_value,_bgcolor,_txtcolor)=>
_cellText=_title+""+_value
table.cell(_table,_column,_row,_cellText,bgcolor=_bgcolor,text_color=_txtcolor,text_size=size.auto)
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//Orders
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
if(inTime)
if(openLong)
qtyPercent:=f_calQtyPerc()
entryQuantity:=f_calQty(qtyPercent)
strategy.entry(id="Long",direction=strategy.long,qty=entryQuantity,comment='Long('+syminfo.ticker+'):Started',alert_message='Long('+syminfo.ticker+'):Started')
f_enteringTradeLabel(x=bar_index+1,y=close-3*ta.tr,entryPrice=close,qty=qtyPercent,slPrice=longSLPrice,tpPrice=longTPPrice,rrRatio=i_RRratio,direction="Long")
if(openShort)
qtyPercent:=f_calQtyPerc()
entryQuantity:=f_calQty(qtyPercent)
strategy.entry(id="Short",direction=strategy.short,qty=entryQuantity,comment='Short('+syminfo.ticker+'):Started',alert_message='Short('+syminfo.ticker+'):Started')
f_enteringTradeLabel(x=bar_index+1,y=close-3*ta.tr,entryPrice=close,qty=qtyPercent,slPrice=shortSLPrice,tpPrice=shortTPPrice,rrRatio=i_RRratio,direction="Short")
if(closeLong)
strategy.close(id='Long',comment='CloseLong',alert_message='Long:Closedatmarketprice')
strategy.position_size>0?f_exitingTradeLabel(x=bar_index,y=close+3*ta.tr,entryPrice=prevEntryPrice,exitPrice=prevExitPrice,direction='Long'):na
if(closeShort)
strategy.close(id='Short',comment='CloseShort',alert_message='Short:Closedatmarketprice')
strategy.position_size<0?f_exitingTradeLabel(x=bar_index,y=close+3*ta.tr,entryPrice=prevEntryPrice,exitPrice=prevExitPrice,direction='Short'):na
if(inLong)
strategy.exit(id='LongTP/SL',from_entry='Long',qty_percent=i_tpQuantityPerc,limit=longTPPrice,stop=longSLPrice,alert_message='Long('+syminfo.ticker+'):TakeProfitorStopLossexecuted')
strategy.exit(id='LongSL',from_entry='Long',stop=longSLPrice,alert_message='Long('+syminfo.ticker+'):StopLossexecuted')
if(inShort)
strategy.exit(id='ShortTP/SL',from_entry='Short',qty_percent=i_tpQuantityPerc,limit=shortTPPrice,stop=shortSLPrice,alert_message='Short('+syminfo.ticker+'):TakeProfitorStopLossexecuted')
strategy.exit(id='ShortSL',from_entry='Short',stop=shortSLPrice,alert_message='Short('+syminfo.ticker+'):StopLossexecuted')

ifstrategy.position_size[1]>0andstrategy.position_size==0
f_exitingTradeLabel(x=bar_index,y=close+3*ta.tr,entryPrice=prevEntryPrice,exitPrice=prevExitPrice,direction='Long')

ifstrategy.position_size[1]<0andstrategy.position_size==0
f_exitingTradeLabel(x=bar_index,y=close+3*ta.tr,entryPrice=prevEntryPrice,exitPrice=prevExitPrice,direction='Short')
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
//BacktestResultDashboard
//░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░
ifi_showDashboard
varbgcolor=color.new(color=color.black,transp=100)
vargreenColor=color.new(color=#02732A,transp=0)
varredColor=color.new(color=#D92332,transp=0)
varyellowColor=color.new(color=#F2E313,transp=0)
//KeeptrackofWins/Lossesstreaks
newWin=(strategy.wintrades>strategy.wintrades[1])and(strategy.losstrades==strategy.losstrades[1])and(strategy.eventrades==strategy.eventrades[1])
newLoss=(strategy.wintrades==strategy.wintrades[1])and(strategy.losstrades>strategy.losstrades[1])and(strategy.eventrades==strategy.eventrades[1])
varipintwinRow=0
varipintlossRow=0
varipintmaxWinRow=0
varipintmaxLossRow=0
ifnewWin
lossRow:=0
winRow:=winRow+1
ifwinRow>maxWinRow
maxWinRow:=winRow

ifnewLoss
winRow:=0
lossRow:=lossRow+1
iflossRow>maxLossRow
maxLossRow:=lossRow
//Preparestatstable
vartabledashTable=table.new(position.top_right,1,15,border_width=1)


ifbarstate.islastconfirmedhistory
dollarReturn=strategy.netprofit
f_fillCell(dashTable,0,0,"Start:",str.format("{0,date,long}",strategy.closedtrades.entry_time(0)),bgcolor,color.white)//+str.format("{0,time,HH:mm}",strategy.closedtrades.entry_time(0))
f_fillCell(dashTable,0,1,"End:",str.format("{0,date,long}",strategy.opentrades.entry_time(0)),bgcolor,color.white)//+str.format("{0,time,HH:mm}",strategy.opentrades.entry_time(0))
_profit=(strategy.netprofit/strategy.initial_capital)*100
f_fillCell(dashTable,0,2,"NetProfit:",str.tostring(_profit,'##.##')+"%",_profit>0?greenColor:redColor,color.white)
_numOfDaysInStrategy=(strategy.opentrades.entry_time(0)-strategy.closedtrades.entry_time(0))/(1000*3600*24)
f_fillCell(dashTable,0,3,"PercentPerDay",str.tostring(_profit/_numOfDaysInStrategy,'#########################.#####')+"%",_profit>0?greenColor:redColor,color.white)
_winRate=(strategy.wintrades/strategy.closedtrades)*100
f_fillCell(dashTable,0,4,"PercentProfitable:",str.tostring(_winRate,'##.##')+"%",_winRate<50?redColor:_winRate<75?greenColor:yellowColor,color.white)
f_fillCell(dashTable,0,5,"ProfitFactor:",str.tostring(strategy.grossprofit/strategy.grossloss,'##.###'),strategy.grossprofit>strategy.grossloss?greenColor:redColor,color.white)
f_fillCell(dashTable,0,6,"TotalTrades:",str.tostring(strategy.closedtrades),bgcolor,color.white)
f_fillCell(dashTable,0,8,"MaxWinsInARow:",str.tostring(maxWinRow,'######'),bgcolor,color.white)
f_fillCell(dashTable,0,9,"MaxLossesInARow:",str.tostring(maxLossRow,'######'),bgcolor,color.white)
Expand (492 lines)
