Script Name: [KL] Double Bollinger Bands Strategy (for Crypto-FOREX)
Author: DojiEmoji
Description: This strategy uses a setup consisting of two Bollinger Bands based on the 20 period 20-SMA +/-
(a) upper/lower bands of two standard deviations apart, and
(b) upper/lower bands of one standard deviation apart.

We consider price at +/- one standard deviation apart from 20-SMA as the "Neutral Zone".

If price closes above Neutral Zone after a period of...
PineScript code:

Pine Script™ strategy
[KL] Double Bollinger Bands Strategy (for Crypto/FOREX)
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  DojiEmoji  (kevinhhl)
//@version=4
strategy("[KL]  Double  BB  Strategy",overlay=true,pyramiding=1)
ENUM_LONG              =  "LONG"
LONG_MSG_ENTER    =  input("Long  +1  entered",  type=input.string,  title="Alert  MSG  for  buying  (Long  position)")
LONG_MSG_EXIT      =  input("Long  -1  closed",  type=input.string,  title="Alert  MSG  for  closing  (Long  position)")
ENUM_SHORT            =  "SHORT"
SHORT_MSG_ENTER  =  input("Short  -1  entered",  type=input.string,  title="Alert  MSG  for  selling  (Short  position)")
SHORT_MSG_EXIT    =  input("Short  +1  covered",  type=input.string,  title="Alert  MSG  for  covering  (Short  position)")
//  Timeframe  {
backtest_timeframe_start        =  input(defval  =  timestamp("01  Apr  2020  13:30  +0000"),  title  =  "Backtest  Start  Time",  type  =  input.time)
USE_ENDTIME                                  =  input(false,title="Define  backtest  end-time  (If  false,  will  test  up  to  most  recent  candle)")
backtest_timeframe_end            =  input(defval  =  timestamp("19  Apr  2021  19:30  +0000"),  title  =  "Backtest  End  Time  (if  checked  above)",  type  =  input.time)
within_timeframe                        =  time  >=  backtest_timeframe_start  and  (time  <=  backtest_timeframe_end  or  not  USE_ENDTIME)
//  }  Timeframe
//  Bollinger  bands  {
BOLL_length          =  20,  BOLL_src  =  close,  SMA20  =  sma(BOLL_src,  BOLL_length)
BOLL_sDEV              =  stdev(BOLL_src,  BOLL_length)
BOLL_upper1          =  SMA20  +  BOLL_sDEV,  BOLL_lower1  =  SMA20  -  BOLL_sDEV
BOLL_upper2          =  SMA20  +  BOLL_sDEV*2,  BOLL_lower2  =  SMA20  -  BOLL_sDEV*2
SMA_20_plot          =  plot(SMA20,  "Basis",  color=#872323,  offset  =  0)
BOLL_upper1_plot  =  plot(BOLL_upper1,"BOLLUpper1",color=color.new(color.navy,50),offset=0)
BOLL_lower1_plot=plot(BOLL_lower1,"BOLLLower1",color=color.new(color.navy,50),offset=0)
BOLL_upper2_plot=plot(BOLL_upper2,"BOLLUpper2",color=color.new(color.navy,50),offset=0)
BOLL_lower2_plot=plot(BOLL_lower2,"BOLLLower2",color=color.new(color.navy,50),offset=0)
fill(BOLL_upper2_plot,BOLL_upper1_plot,title="Background",color=color.new(#198787,85))
fill(BOLL_upper1_plot,SMA_20_plot,title="Background",color=color.new(#198787,75))
fill(SMA_20_plot,BOLL_lower1_plot,title="Background",color=color.new(#198787,75))
fill(BOLL_lower1_plot,BOLL_lower2_plot,title="Background",color=color.new(#198787,85))
//{Bollingerbands
//Quantativemethods-usedforsettingstoplossesandentry/exitsignals{
cv=stdev(close,20)/sma(close,20)
len_drift=input(14,title="lookbackperiodfordriftcalc.")
percentage_chng=log(close/close[1])
drift=sma(percentage_chng,len_drift)-pow(stdev(percentage_chng,len_drift),2)*0.5
//}Quantmethods
//Trailingstoploss{
ATR_X2_TSL=atr(input(14,title="LengthofATRfortrailingstoploss"))*input(2.0,title="ATRMultiplierfortrailingstoploss",type=input.float)
TSL_source_long=low,TSL_source_short=high
varstop_loss_price_long=float(0)
varstop_loss_price_short=float(2147483647)
varpos_opened_long=false//tobeupdatedinMAINloop
varpos_opened_short=false//tobeupdatedinMAINloop
stop_loss_price_long:=pos_opened_long?max(stop_loss_price_long,TSL_source_long-ATR_X2_TSL):TSL_source_long-ATR_X2_TSL
stop_loss_price_short:=pos_opened_short?min(stop_loss_price_short,TSL_source_short+ATR_X2_TSL):TSL_source_short+ATR_X2_TSL
//tightenTSL
is_consol=cv<sma(cv,50)
TIGHTEN_TSL=input(true,title="Tightenstoplosswhenpricemovessharplyinfavorabledirection")
ifTIGHTEN_TSL
ifnotis_consol
ifpos_opened_longandcv>cv[1]
stop_loss_price_long:=max(stop_loss_price_long*(1+percentage_chng*0.5),stop_loss_price_long[1])
ifpos_opened_shortandcv>cv[1]
stop_loss_price_short:=min(stop_loss_price_long*(1+percentage_chng*0.5),stop_loss_price_short[1])
//PlotTSL
TSL_transp_long=pos_opened_longandwithin_timeframe?0:100
TSL_transp_short=pos_opened_shortandwithin_timeframe?0:100
plot(stop_loss_price_long,color=color.new(color.green,TSL_transp_long))
plot(stop_loss_price_short,color=color.new(color.red,TSL_transp_short))
//}Trailingstoploss
//Signalsforentry{
is_neutral=close<BOLL_upper1andclose>BOLL_lower1
below_neutral=close<BOLL_lower1andclose>BOLL_lower2
above_neutral=close>BOLL_upper1andclose<BOLL_upper2
atr14=atr(14)
entry_signal_long=is_consolandclose>BOLL_upper1andatr14>sma(atr14,5)anddrift>0
entry_signal_short=is_consolandclose<BOLL_lower1andatr14>sma(atr14,5)anddrift<0
//}Signalsforentry
//MAIN:
ifwithin_timeframe
//EXIT::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
ifpos_opened_long
strategy.exit(ENUM_LONG,stop=stop_loss_price_long,comment="SL")
ifpos_opened_short
strategy.exit(ENUM_SHORT,stop=stop_loss_price_short,comment="SL")

end_of_rally=close<BOLL_upper1andstrategy.position_avg_price>stop_loss_price_longandlow<low[1]
ifpos_opened_longand(TSL_source_long<=stop_loss_price_longorend_of_rallyandnotis_consol)
pos_opened_long:=false
alert(LONG_MSG_EXIT,alert.freq_once_per_bar)
strategy.close(ENUM_LONG,comment=close<strategy.position_avg_price?"stoploss":"takeprofit")
ifpos_opened_shortand(TSL_source_short>=stop_loss_price_short)
pos_opened_short:=false
alert(SHORT_MSG_EXIT,alert.freq_once_per_bar)
strategy.close(ENUM_SHORT,comment=close>strategy.position_avg_price?"stoploss":"takeprofit")
//ENTRY:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
ifentry_signal_longandclose>stop_loss_price_long
pos_opened_long:=true
alert(LONG_MSG_ENTER,alert.freq_once_per_bar)
strategy.entry(ENUM_LONG,strategy.long,comment="long")
ifentry_signal_short
pos_opened_short:=true
alert(SHORT_MSG_ENTER,alert.freq_once_per_bar)
strategy.entry(ENUM_SHORT,strategy.short,comment="short")
//CLEANUP:
ifnotpos_opened_long
stop_loss_price_long:=float(0)
ifnotpos_opened_short
stop_loss_price_short:=float(2147483647)
Expand (115 lines)
