Script Name: [Maclen] Money Flow Strategy
Author: MaclenMtz
Description: This is a strategy based on a smoothed overbought and oversold indicator of money flow.

It was design on BTCUSDT Perpetual Futures of Binance with a timeframe of 1D.

Feel free to comment and publish any idea to improve this strategy.
PineScript code:

Pine Script™ strategy
[Maclen] Money Flow Strategy
//@version=4
//For  Binance  BTCUSDT  Futures  timeframe  1D
palanca  =  input(defval  =  5,  title  =  "Leverage")
porc_cap  =  input(defval  =  80,  title  =  "%  Capital  for  Operation")/100
strategy("Money  Flow  Strategy",  shorttitle="MoneyFlow",  overlay=false,  slippage=5,initial_capital=100,currency=currency.USD,  default_qty_type=strategy.fixed,  default_qty_value=0.1,  pyramiding=0,  commission_type=strategy.commission.percent,
          commission_value=0.08)
//----------------------------Backtest  window-----------------------------
//Input  Backtesting  Range
fromMonth  =  input(defval  =  1,        title  =  "From  Month"            ,  minval  =  1,  maxval  =  12)
fromDay      =  input(defval  =  1,        title  =  "From  Day"                ,  minval  =  1,  maxval  =  31)
fromYear    =  input(defval  =  2020,  title  =  "From  Year"              ,  minval  =  1970)
thruMonth  =  input(defval  =  1,        title  =  "Thru  Month"            ,  minval  =  1,  maxval  =  12)
thruDay      =  input(defval  =  1,        title  =  "Thru  Day"                ,  minval  =  1,  maxval  =  31)
thruYear    =  input(defval  =  2021,  title  =  "Thru  Year"              ,  minval  =  1970)
//Funtion
start          =  timestamp(fromYear,  fromMonth,  fromDay,  00,  00)                //  backtest  start  window
finish        =  timestamp(thruYear,  thruMonth,  thruDay,  23,  59)                //  backtest  finish  window
window()    =>  time  >=  start  andtime<=finish?true:false//createfunction"withinwindowoftime"
//______________________________Logica____________________________________________
length=input(title="Length",type=input.integer,defval=40,minval=1,maxval=2000)
src=hlc3
upper=sum(volume*(change(src)<=0?0:src),length)
lower=sum(volume*(change(src)>=0?0:src),length)
mf=rsi(upper,lower)
smooth=input(30,"SmoothPeriod")
mf_S=ema(mf,smooth)
plot(mf_S,"MF_S",color=#459915)
sobrecompra=input(defval=61,title="Overbought")
sobreventa=input(defval=42,title="Oversold")
overbought=hline(sobrecompra,title="Overbought",color=#c0c0c0)
oversold=hline(sobreventa,title="Oversold",color=#c0c0c0)
fill(overbought,oversold,color=#9915ff,transp=90,title="Background")
lLong=input(59,"limit_exitLong")
lShort=input(44,"limit_exitShort")
Cierre1=hline(lLong,title="c_Long",color=#c0c0c0)
Cierre2=hline(lShort,title="c_Short",color=#c0c0c0)
fill(Cierre1,Cierre2,color=#D500FF,transp=90,title="Background")
//----------------Long/Short----------------------
long=crossunder(mf_S,sobreventa)
short=crossover(mf_S,sobrecompra)
cLong=mf[1]>lLongandmf>lLong
cShort=mf[1]<lShortandmf<lShort
//-------------Operation-------------------------
contrato=((strategy.equity)*palanca*porc_cap)/close
strategy.entry("BUY",strategy.long,qty=contrato,when=longandwindow())
strategy.entry("SELL",strategy.short,qty=contrato,when=shortandwindow())
cl=input(false,"ClosewithLimitofOBoOS💹")
if(cl==true)
strategy.close("BUY",when=cLong)
strategy.close("SELL",when=cShort)
//-------TrailingandSL-----------
sl_inp=input(12.0,title='StopLoss%')/100
tp_inp=input(25.0,title='TakeProfit%')/100
toff=input(2,title="trailoffset")/100
sl_buy=strategy.position_avg_price/(1+sl_inp)
trail_buy=strategy.position_avg_price*(1+tp_inp)
trail_offset_buy=(strategy.position_avg_price-(strategy.position_avg_price/(1+toff)))/syminfo.mintick
sl_sell=strategy.position_avg_price*(1+sl_inp)
trail_sell=strategy.position_avg_price/(1+tp_inp)
trail_offset_sell=((strategy.position_avg_price*(1+toff))-strategy.position_avg_price)/syminfo.mintick
tts=input(true,"TTPandSL💹")
if(tts==true)
strategy.exit("exitBuy","BUY",trail_price=trail_buy,trail_offset=trail_offset_buy,stop=sl_buy)
strategy.exit("exitSell","SELL",trail_price=trail_sell,trail_offset=trail_offset_sell,stop=sl_sell)
Expand (98 lines)
