Script Name: Adaptive Price Channel Strategy
Author: HomeCryptoTrader
Description: This strategy is an adaptive price channel strategy based on the Average True Range (ATR) indicator and the Average Directional Index (ADX). It aims to identify sideways markets and trends in the price movements and make trades accordingly.

The strategy uses a length parameter for the ATR and ADX indicators, which determines the length of the calculation for...
PineScript code:

Pine Script™ strategy
Adaptive Price Channel Strategy
//@version=5
strategy("Adaptive  Price  Channel  Strategy",  overlay=true)
length  =  input(20,  title="Length")
exit_length  =  input(10,  title="Exit  After  X  Periods")
atr_multiplier  =  input(3.2,  title="ATR  Multiplier")
startDate  =  input.time(defval  =  timestamp("2019-01-15T08:15:15+00:00"),  title  =  "Start  Date")
endDate  =  input.time(defval  =  timestamp("2023-04-01T08:15:00+00:00"),  title  =  "End  Date")
hh  =  ta.highest(high,  length)
ll  =  ta.lowest(low,  length)
atr  =  ta.atr(length)
//  calculate  +DI  and  -DI
upMove  =  high  -  high[1]
downMove  =  low[1]  -  low
plusDM  =  na(upMove[1])  ?  na  :  (upMove  >  downMove  and  upMove  >  0  ?  upMove  :  0)
minusDM  =  na(downMove[1])  ?  na  :  (downMove  >  upMove  and  downMove  >  0  ?  downMove  :  0)
plusDI  =  ta.rma(plusDM,  length)  /  atr  *  100
minusDI  =  ta.rma(minusDM,  length)  /  atr  *  100
//  calculate  ADX
dx  =  math.abs(plusDI  -  minusDI)  /  (plusDI  +  minusDI)  *  100
adx  =  ta.rma(dx,  length)
var  int  barSinceEntry  =  na
if  (not  na(close[length])  and  time  >=  startDate  and  time  <=  endDate)
        if  (adx  <  25)  //  Sideways  market
                if  (close  >  hh  -  atr_multiplier  *  atr)
                        strategy.entry("PChLE",  strategy.long,  comment="PChLE")
                        barSinceEntry  :=  0
                else  if  (close  <  ll  +  atr_multiplier  *  atr)
                        strategy.entry("PChSE",  strategy.short,  comment="PChSE")
                        barSinceEntry  :=  0
        else  if  (adx  >=  25  and  plusDI  >  minusDI)  //  Bullish  market
                if  (close  >  hh  -  atr_multiplier  *  atr)
                        strategy.entry("PChLE",  strategy.long,  comment="PChLE")
                        barSinceEntry  :=  0
        else  if  (adx  >=  25  and  plusDI  <  minusDI)  //  Bearish  market
                if  (close  <  ll  +  atr_multiplier  *  atr)
                        strategy.entry("PChSE",  strategy.short,  comment="PChSE")
                        barSinceEntry  :=  0
if  (na(barSinceEntry))
        barSinceEntry  :=  barSinceEntry[1]  +  1
else  if  (barSinceEntry  >=  exit_length)
        strategy.close("PChLE")
        strategy.close("PChSE")
        barSinceEntry  :=  na
plot(hh,  title="Highest  High",  color=color.green,  linewidth=2)
plot(ll,  title="Lowest  Low",  color=color.red,  linewidth=2)
Expand (56 lines)
