Script Name: ADX - RSI Strategy by Trade Rush (created by SirPoggy)
Author: UnknownUnicorn20967364
Description: This is one of many new strategies coming soon which were seen on Trade Rush
 This one is the ADX / RSI Strategy seen here:
  https:www.youtube.com/watch?v=uSkGE0ujyn4

 While the strategy has been modified slightly to use the DMI instead of the ADX, the core of the strategy is essentially the same
 Long signals are generated when the RSI is above 70, close is...
PineScript code:

Pine Script™ strategy
ADX / RSI Strategy by Trade Rush (created by SirPoggy)
//@version=4
//
//  Strategy  Coded  by  SirPoggy
strategy("[SirPoggy]  Simple  and  Effective  RSI  Strategy",  overlay=true,currency=currency.USD,process_orders_on_close=true,default_qty_type=strategy.percent_of_equity,initial_capital=500,default_qty_value=100,pyramiding=1,calc_on_order_fills=false,calc_on_every_tick=true)
//
//
//  User  Inputs
//
showbox=  input(title="Show  Status  Box?",group="Main  Strategy  Settings",  type=input.bool,  defval=true)
backtest=  input(title="Show  Backtest  Results?",group="Main  Strategy  Settings",  type=input.bool,  defval=true)
showwin  =  input(title="Show  Win  /  Loss  labels?",  type=input.bool,  defval=true,group="Main  Strategy  Settings")
enableLong=  input(title="Enable  Long  Entries?",group="Main  Strategy  Settings",  type=input.bool,  defval=true)
enableShort=  input(title="Enable  Short  Entries?",group="Main  Strategy  Settings",  type=input.bool,  defval=true)
//MAIN  TREND  Strategy
useslowema  =  input(title="Enable  Global  Trend",  type=input.bool,  defval=false,group="Main  Strategy  Settings",group="Main  Strategy  Settings")
emalen  =  input(200,  minval=1,  title="Global  Trend  Length",group="Main  Strategy  Settings")
emaslow  =  ema(close,emalen)
lookback=  input(10,group="Main  Strategy  Settings",title="Universal  Lookback  Period  for  Strategies")
plot(emaslow,"Global  Trend  EMA",transp=  useslowema  ?  0  :  100,color=color.white)
//RSI  Strategy  Options
usersi  =  input(title="Enable  RSI  Strategy",group="🔘  RSI  Strategy  Settings  🔘",  type=input.bool,  defval=false)
rsitype  =  input(title="RSI  Strategy  Type",group="🔘  RSI  Strategy  Settings  🔘",  defval="Standard",  options=["Standard",  "Reversal","50/50  Method","Strict  Standard","Strict  50/50","Strict  Reversal"],tooltip="Standard  -  RSI  Value  is  higher  than  the  overbought  (def:  70)  threshold  for  Longs,  higher  than  oversold  (def:  30)  for  shorts  \n\nEMA  -  Compares  a  12  and  26  period  RSI  EMA  to  determine  long  and  short  entries.\n\nReversal  -  RSI  Value  above  oversold  threshold  for  longs  and  above  overbought  threshold  for  longs\n\n50/50  Method  -  Any  cross  on  the  RSI  at  50  is  a  signal  for  long  or  short  depending  on  the  direction")
rsistrat  =  input(title="RSI  Strategy  Settings",group="🔘  RSI  Strategy  Settings  🔘",  defval="Standard",  options=["Standard",  "More  Sensitive"],tooltip="Standard  -  Sets  RSI  to  14  period\n\nMore  Sensitive  -  Sets  RSI  to  8")
//
//  ADX  Strategy  Settings
useadx  =  input(title="Enable  ADX  Strategy",  type=input.bool,group="🔘  ADX  Strategy  Settings  🔘",  defval=false)
adxtype  =  input(title="ADX  Strategy  Settings",group="🔘  ADX  Strategy  Settings  🔘",  defval="Standard",  options=["Less  Sensitive","Standard",  "More  Sensitive"],tooltip="Standard  -  Sets  ADX  strategy  to  14  period\n\nMore  Sensitive  -  Sets  ADX  strategy  to  8\n\nLess  Sensitive  -  Sets  ADX  to  21  period")
adxroc  =  input(title="Use  ADX  Rate  of  Change?",group="🔘  ADX  Strategy  Settings  🔘",type=input.bool,  defval=false)
//  Pullback  Settings
usepullback=  input(title="Enable  EMA  Pullback  Requirement?",group="Pullback  Filter",  type=input.bool,  defval=false)
ema_pullback_len  =  input(title="EMA  Lengths  for  Pullback  Filter",group="Pullback  Filter",  defval="5/20",  options=["5/20","20/50","50/100","200/250"])
//
//
//RSI  STRATEGY
//
len  =  rsistrat  ==  "More  Sensitive"  ?  8  :  rsistrat  ==  "Extreme"  ?  2  :  14
rsisrc  =  close
up  =  rma(max(change(rsisrc),  0),  len)
down  =  rma(-min(change(rsisrc),  0),  len)
rsi  =  down  ==  0  ?  100  :  up  ==  0  ?  0  :  100  -  (100  /  (1  +  up  /  down))
//RSI  Signals
rsiL  =  false
rsiS  =  false
if  rsitype  ==  "Standard"  ?  rsi  >=  70  :  rsitype  ==  "Reversal"  ?  rsi  >=  30  :  rsitype  ==  "Strict  Standard"  ?  crossover(rsi,rsitype  ==  "Extreme"  ?  90  :  70)  :  rsitype  ==    "Strict  Reversal"  ?  crossover(rsi,rsitype  ==  "Extreme"  ?  10  :  30)  :  rsitype  ==    "Strict  50/50"  ?  crossover(rsi,50)  :  rsi  >=  50
        rsiL  :=  true
if  rsitype  ==  "Standard"  ?  rsi  <=  30  :  rsitype  ==  "Reversal"  ?  rsi  <=  70  :  rsitype  ==  "Strict  Standard"  ?  crossunder(rsi,rsitype  ==  "Extreme"  ?  10  :  30)  :  rsitype  ==    "Strict  Reversal"  ?  crossunder(rsi,rsitype  ==  "Extreme"  ?  90  :  70)  :  rsitype  ==    "Strict  50/50"  ?  crossunder(rsi,50)  :  rsi  <=  50
        rsiS  :=  true
//
//  ADX  STRATEGY
//
lenadxsig  =  adxtype  ==  "Standard"  ?  14  :  adxtype  ==  "More  Sensitive"  ?  8  :  21
lenadx  =  adxtype  ==  "Standard"  ?  14  :  adxtype  ==  "More  Sensitive"  ?  8  :  21
upadx  =  change(high)
downadx  =  -change(low)
plusDM  =  na(upadx)  ?  na  :  (upadx  >  downadx  and  upadx  >  0  ?  upadx  :  0)
minusDM  =  na(downadx)  ?  na  :  (downadx  >  upadx  and  downadx  >  0  ?  downadx  :  0)
trur  =  rma(tr,  lenadx)
plus  =  fixnan(100  *  rma(plusDM,  lenadx)  /  trur)
minus  =  fixnan(100  *  rma(minusDM,  lenadx)  /  trur)
sum  =  plus  +  minus
adx  =  100  *  rma(abs(plus  -  minus)  /  (sum  ==  0  ?  1  :  sum),  lenadxsig)
adxL_N  =  false
adxS_N  =  false
if  adx  >  25  and  plus  >  25  and  minus  <  20
        adxL_N  :=  true
if  adx  >  25  and  plus  <  20  and  minus  >  25
        adxS_N  :=  true

adxL  =  adxL_N  and  (adxroc  ?  roc(adx,lookback)  >  0  :  true)  and  (adxroc  ?  roc(plus,lookback)  >  0  :  true)  and  (adxroc  ?  roc(minus,lookback)  <  0  :  true)
adxS  =  adxS_N  and  (adxroc  ?  roc(adx,lookback)  <  0  :  true)  and  (adxroc  ?  roc(plus,lookback)  <  0  :  true)  and  (adxroc  ?  roc(minus,lookback)  >  0  :  true)
//
//  END  ADX  Strategy
//
//
//  Order  Parameters
//
//  Close  /  Open  Trade  Messages
enableOA=  input(title="Enable  New  Trade  Alerts?",  type=input.bool,  defval=false,group="Alert  Settings")
enableTA=  input(title="Enable  Take  Profit  Alerts?",  type=input.bool,  defval=false,group="Alert  Settings")
enableSA=  input(title="Enable  Stop  Loss  Alerts?",  type=input.bool,  defval=false,group="Alert  Settings")
opentradelong  =  input(title="Long  Open  Trade  Alert",  type=input.string,  defval="Open  Long",group="Alert  Settings")
closelongmess  =  input(title="Long  SL  Alert",  type=input.string,  defval="Long  Stop  Loss",group="Alert  Settings")
closelongmessT  =  input(title="Long  TP  Alert",  type=input.string,  defval="Long  Take  Profit",group="Alert  Settings")
opentradeshort  =  input(title="Short  Open  Trade  Alert",  type=input.string,  defval="Open  Short",group="Alert  Settings")
closeshortmess  =  input(title="Short  SL  Alert",  type=input.string,  defval="Short  Stop  Loss",group="Alert  Settings")
closeshortmessT  =  input(title="Short  TP  Alert",  type=input.string,  defval="Short  Take  Profit",group="Alert  Settings")
//  Entry  Price
entry  =  ((strategy.position_size[0]  >  strategy.position_size[1])  or  (strategy.position_size[0]  <  strategy.position_size[1]))  and  strategy.position_size[1]  ==  0
ep  =  0.0
ep  :=  na(ep)  ?  na  :  ep[1]
islong  =  strategy.position_size  >  0
isshort  =  strategy.position_size  <  0
isnotin  =  strategy.position_size  ==  0
//
//  Step  4:  Order  Parameters
//
//
//  Step  5:  Long  and  Short  Conditions
//
//  The  Fixed  Percent  Stop  Loss  Code
//  User  Options  to  Change  Inputs  (%)
entry_barL  =  barssince(strategy.position_size[0]  >  strategy.position_size[1])
entry_barS  =  barssince(strategy.position_size[0]  <  strategy.position_size[1])
stoptype  =  input(title="Stop  Loss  Method",  defval="ATR  Based",  options=["Percent  Based","ATR  Based","Average  of  ATR  &  %"],group="Close  Strategy  Settings")
//
//  PULLBACK  CONFIRM
//
ema_pullback_1  =  ema_pullback_len  ==  "5/20"  ?  ema(close,5)  :  ema_pullback_len  ==  "20/50"  ?  ema(close,20)  :  ema_pullback_len  ==  "50/100"  ?  ema(close,50)  :  ema(close,200)
ema_pullback_2  =  ema_pullback_len  ==  "5/20"  ?  ema(close,20)  :  ema_pullback_len  ==  "20/50"  ?  ema(close,50)  :  ema_pullback_len  ==  "50/100"  ?  ema(close,100)  :  ema(close,250)
plot(ema_pullback_1,"Pullback  EMA",color=color.blue,transp=  usepullback  ?  0  :  100)
pullback_L  =  close  <  ema_pullback_1  and  close  >  ema_pullback_2  and  roc(close,10)  <  0
pullback_S  =  close  >  ema_pullback_1  and  close  <  ema_pullback_2  and  roc(close,10)  >  0
//
//  END  PULLBACK  CONFIRM
//
//  Date  Range  Backtest  Filter
//  DATE  RANGE
//  Calculate  start/end  date  and  time  condition
limitresults=  input(title="Limit  Results  to  Date  Range?",  type=input.bool,  defval=false)
startDate    =  input(timestamp("2021-05-01T00:00:00"),  title="Backtest  Start  Date",  type  =  input.time)
finishDate  =  input(timestamp("2021-06-01T00:00:00"),  title="Backtest  End  Date",  type  =  input.time)
inDateRange    =  (limitresults  ?    time  >=  startDate  and  time  <=  finishDate  :  0==0)
//
//MAIN  VARIABLES  LONG
inuptrend  =  useslowema  ?  close  >  emaslow  :  0==0
//
//MAIN  VARIABLES  SHORT
//
indowntrend  =  useslowema  ?  close  <  emaslow  :  0==0
longCondition  =  false
shortCondition  =  false
//  LONG  CONDITIONS
for  i  =  1  to  lookback  +  1
        if  enableLong?
(useslowema?inuptrend[i]:0==0)and
(usersi?rsiL[i]:0==0)and
(useadx?adxL[i]:0==0)and
(usepullback?pullback_L:0==0)
:1==0
longCondition:=true
//SHORTCONDITIONS
fori=1tolookback+1
ifenableShort?
(useslowema?indowntrend[i]:0==0)and
(usersi?rsiS[i]:0==0)and
(useadx?adxS[i]:0==0)and
(usepullback?pullback_S:0==0)
:1==0
shortCondition:=true
long=isnotinandlongCondition[0]and(notlongCondition[1]andisnotin[1])
short=isnotinandshortCondition[0]and(notlongCondition[1]andisnotin[1])
iflongandinDateRange
strategy.entry("Long",strategy.long,when=long,comment="EnterLong")
ep:=close
ifenableOA
alert(opentradelong)

ifshortandinDateRange
strategy.entry("Short",strategy.short,when=short,comment="EnterShort")
ep:=close
ifenableOA
alert(opentradeshort)
//KillTradeFunctions
killtrade=input(title="AttempttoKillTradeAfterXBars",group="CloseStrategySettings",defval="Disable",options=["Disable","5","10","15","20","25","30","35","40","45","50","55","60","65","70","75","80","85","90","95","100"],tooltip="ThisoptionifsettoN/Adoesnothing.Ifsettoavalue,willattempttoclosetradeinprofitafterXbars.")
killwhenL=killtrade=="Disable"?na:tonumber(killtrade)-entry_barL
killnowL=killtrade=="Disable"?na:killwhenL<=0
killwhenS=killtrade=="Disable"?na:tonumber(killtrade)-entry_barS
killnowS=killtrade=="Disable"?na:killwhenS<=0
//TakeProfitandStopLossCalculations
stopPer=input(2,title='StopLossPercentage',type=input.float,group="CloseStrategySettings")/100
stopATR_mult=input(1.4,step=0.2,title='ATRMultiplier',type=input.float,group="CloseStrategySettings")
taketype="RiskBased"
takePer=input(1.5,step=0.2,title='TakeProfitRiskMultiplier',type=input.float,group="CloseStrategySettings")
atr=atr(14)
stopATR_L=0.0
profitATR_L=0.0
stopATR_L:=na(stopATR_L)?na:stopATR_L[1]
profitATR_L:=na(profitATR_L)?na:profitATR_L[1]
stopATR_S=0.0
profitATR_S=0.0
stopATR_S:=na(stopATR_S)?na:stopATR_S[1]
profitATR_S:=na(profitATR_S)?na:profitATR_S[1]
iflongandinDateRange
stopATR_L:=ep-(atr*stopATR_mult)
profitATR_L:=ep+(atr*(stopATR_mult*takePer))
ifshortandinDateRange
stopATR_S:=ep+(atr*stopATR_mult)
profitATR_S:=ep-(atr*(stopATR_mult*takePer))
longStop2=stoptype=="AverageofATR&%"?avg(stopATR_L,ep*(1-stopPer)):stoptype=="ATRBased"?stopATR_L:stoptype=="PercentBased"?ep*(1-stopPer):na
shortStop2=stoptype=="AverageofATR&%"?avg(stopATR_S,ep*(1+stopPer)):stoptype=="ATRBased"?stopATR_S:stoptype=="PercentBased"?ep*(1+stopPer):na
longTake2=stoptype=="AverageofATR&%"?avg(profitATR_L,ep*(1+(stopPer*takePer))):stoptype=="ATRBased"?profitATR_L:ep*(1+(stopPer*takePer))
shortTake2=stoptype=="AverageofATR&%"?avg(profitATR_S,ep*(1-(stopPer*takePer))):stoptype=="ATRBased"?profitATR_S:ep*(1-(stopPer*takePer))
//EXITCONTIDIONS
ifbarssince(entry)>=1and(low<=longStop2andislong)
strategy.close(comment="SLLong",id="Long")
ifenableSA
alert(closelongmess)
showwin?label.new(x=bar_index[1]-3,y=low-low*0.03,text="LOSS",color=color.red,textcolor=color.white,style=label.style_label_center,size=size.normal,textalign=text.align_left):na
ifbarssince(entry)>=1and(killtrade=="Disable"?high>=longTake2andislong:killnowLandislong?((close>ep)orhigh>=longTake2andislong):0==1)
strategy.close(comment="TPLong",id="Long")
ifenableTA
alert(closelongmessT)
showwin?label.new(x=bar_index[1]-3,y=high+high*0.03,text="WIN",color=color.green,textcolor=color.white,style=label.style_label_center,size=size.normal,textalign=text.align_left):na
ifbarssince(entry)>=1and(high>=shortStop2andisshort)
strategy.close(comment="SLShort",id="Short")
ifenableSA
alert(closeshortmess)
showwin?label.new(x=bar_index[1]-3,y=high+high*0.03,text="LOSS",color=color.red,textcolor=color.white,style=label.style_label_center,size=size.normal,textalign=text.align_left):na
ifbarssince(entry)>=1and(killtrade=="Disable"?low<=shortTake2andisshort:killnowSandisshort?((close<ep)or(low<=shortTake2andisshort)):0==1)
strategy.close(comment="TPShort",id="Short")
ifenableTA
alert(closeshortmessT)
showwin?label.new(x=bar_index[1]-3,y=low-low*0.03,text="WIN",color=color.green,textcolor=color.white,style=label.style_label_center,size=size.normal,textalign=text.align_left):na
//PLOTFIXEDSLTPLINE
LongFixedSL=plot(strategy.position_size>0?longStop2:na,style=plot.style_linebr,color=color.red,linewidth=1,title="LongFixedSL",offset=0)
ShortFixedSL=plot(strategy.position_size<0?shortStop2:na,style=plot.style_linebr,color=color.red,linewidth=1,title="ShortFixedSL",offset=0)
LongTakeProfit=plot(strategy.position_size>0?longTake2:na,style=plot.style_linebr,color=color.green,linewidth=1,title="LongTakeProfit",offset=0)
ShortTakeProfit=plot(strategy.position_size<0?shortTake2:na,style=plot.style_linebr,color=color.green,linewidth=1,title="ShortTakeProfit",offset=0)
LongEP=plot(strategy.position_size>0?ep:na,style=plot.style_linebr,color=color.green,linewidth=1,title="LongEntryPrice",offset=0)
ShortEP=plot(strategy.position_size<0?ep:na,style=plot.style_linebr,color=color.green,linewidth=1,title="ShortEntryPrice",offset=0)
//Fillthebackgroundareas
fill(LongEP,LongFixedSL,
color=color.red,transp=80,title="LossArea")
fill(LongEP,LongTakeProfit,
color=color.green,transp=80,title="WinArea")
fill(ShortEP,ShortFixedSL,
color=color.red,transp=80,title="LossArea")
fill(ShortEP,ShortTakeProfit,
color=color.green,transp=80,title="WinArea")
//
//EndStep6C:CloseConditions
//
//
//PrintBox
//
//LongPrint
inrsiL=usersi?rsiL?"🟢-RSI\n\n":"🔴-RSI\n\n":na
inadxL=useadx?adxL?"🟢-ADX\n\n":"🔴-ADX\n\n":na
//ShortPrint
inrsiS=usersi?rsiS?"🟢-RSI\n\n":"🔴-RSI\n\n":na
inadxS=useadx?adxS?"🟢-ADX\n\n":"🔴-ADX\n\n":na
print="Ticker:"+syminfo.ticker+"\n\n"
+(islong?"🟢InLongTradefor"+tostring(entry_barL)+"bars\n\n":na)
+(isshort?"🔴InShortTradefor"+tostring(entry_barS)+"bars\n\n":na)
+(enableLong?"LongSignals\n__________\n\n"
+inrsiL
+inadxL
+(enableShort?"\n\n\n":na):na)
+(enableShort?"ShortSignals\n__________\n\n"
+inrsiS
+inadxS
+"\n\n\n":na)
+(backtest?"\n\n\nBacktestResults\n__________\n\n"
+"WinningTrades:"+tostring(strategy.wintrades)+"\n"
+"LosingTrades:"+tostring(strategy.losstrades)+"\n\n"
+"Win%:"+tostring(round((strategy.wintrades/(strategy.wintrades+strategy.losstrades))*100))+"\n\n":na)

box=showbox?label.new(x=time+100*(time-time[1]),y=close,text=print,xloc=xloc.bar_time,yloc=yloc.price,color=color.navy,textcolor=color.white,style=label.style_label_center,size=size.normal,textalign=text.align_left):na
label.delete(box[1])
//
//
//
Expand (344 lines)
