Script Name: All Candlestick Patterns Strategy
Author: Traaaderz
Description: This strategy uses the tradingview built in candlestick recognition.
PineScript code:

Pine Script™ strategy
All Candlestick Patterns Strategy
//@version=4
strategy(shorttitle="All  Candlestick  Patterns  Strategy",  title="All  Candlestick  Patterns  Strategy",  overlay=true,  initial_capital=600)
//custom  script
stopLoss  =  input(0.015,  minval=0.0001,  step=0.0025,  title="Stop  Loss"),
var  _tradeDirection  =  ""
if  (strategy.position_size  !=  0)
        _tradeDirection  :=  ""
//custom  script  end
C_DownTrend  =  true
C_UpTrend  =  true
var  trendRule1  =  "SMA50"
var  trendRule2  =  "SMA50,  SMA200"
var  trendRule  =  input(trendRule1,  "Detect  Trend  Based  On",  options=[trendRule1,  trendRule2,  "No  detection"])
if  trendRule  ==  trendRule1
        priceAvg  =  sma(close,  50)
        C_DownTrend  :=  close  <  priceAvg
        C_UpTrend  :=  close  >  priceAvg
if  trendRule  ==  trendRule2
        sma200  =  sma(close,  200)
        sma50  =  sma(close,  50)
        C_DownTrend  :=  close  <  sma50  and  sma50  <  sma200
        C_UpTrend  :=  close  >  sma50  and  sma50  >  sma200
C_Len  =  14  //  ema  depth  for  bodyAvg
C_ShadowPercent  =  5.0  //  size  of  shadows
C_ShadowEqualsPercent  =  100.0
C_DojiBodyPercent  =  5.0
C_Factor  =  2.0  //  shows  the  number  of  times  the  shadow  dominates  the  candlestick  body
C_BodyHi  =  max(close,  open)
C_BodyLo  =  min(close,  open)
C_Body  =  C_BodyHi  -  C_BodyLo
C_BodyAvg  =  ema(C_Body,  C_Len)
C_SmallBody  =  C_Body  <  C_BodyAvg
C_LongBody  =  C_Body  >  C_BodyAvg
C_UpShadow  =  high  -  C_BodyHi
C_DnShadow  =  C_BodyLo  -  low
C_HasUpShadow  =  C_UpShadow  >  C_ShadowPercent  /  100  *  C_Body
C_HasDnShadow  =  C_DnShadow  >  C_ShadowPercent  /  100  *  C_Body
C_WhiteBody  =  open  <  close
C_BlackBody  =  open  >  close
C_Range  =  high-low
C_IsInsideBar  =  C_BodyHi[1]  >  C_BodyHi  and  C_BodyLo[1]  <  C_BodyLo
C_BodyMiddle  =  C_Body  /  2  +  C_BodyLo
C_ShadowEquals  =  C_UpShadow  ==  C_DnShadow  or  (abs(C_UpShadow  -  C_DnShadow)  /  C_DnShadow  *  100)  <  C_ShadowEqualsPercent  and  (abs(C_DnShadow  -  C_UpShadow)  /  C_UpShadow  *  100)  <  C_ShadowEqualsPercent
C_IsDojiBody  =  C_Range  >  0  and  C_Body  <=  C_Range  *  C_DojiBodyPercent  /  100
C_Doji  =  C_IsDojiBody  and  C_ShadowEquals
CandleType  =  input(title  =  "Pattern  Type",  defval="Both",  options=["Bullish",  "Bearish",  "Both"])
patternLabelPosLow  =  low  -  (atr(30)  *  0.6)
patternLabelPosHigh  =  high  +  (atr(30)  *  0.6)
AbandonedBabyInput  =  input(title  =  "Abandoned  Baby"  ,defval=true)
DarkCloudCoverInput  =  input(title  =  "Dark  Cloud  Cover"  ,defval=true)
DojiInput  =  input(title  =  "Doji"  ,defval=true)
DojiStarInput  =  input(title  =  "Doji  Star"  ,defval=true)
DownsideTasukiGapInput  =  input(title  =  "Downside  Tasuki  Gap"  ,defval=true)
DragonflyDojiInput  =  input(title  =  "Dragonfly  Doji"  ,defval=true)
EngulfingInput  =  input(title  =  "Engulfing"  ,defval=true)
EveningDojiStarInput  =  input(title  =  "Evening  Doji  Star"  ,defval=true)
EveningStarInput  =  input(title  =  "Evening  Star"  ,defval=true)
FallingThreeMethodsInput  =  input(title  =  "Falling  Three  Methods"  ,defval=true)
FallingWindowInput  =  input(title  =  "Falling  Window"  ,defval=true)
GravestoneDojiInput  =  input(title  =  "Gravestone  Doji"  ,defval=true)
HammerInput  =  input(title  =  "Hammer"  ,defval=true)
HangingManInput  =  input(title  =  "Hanging  Man"  ,defval=true)
HaramiCrossInput  =  input(title  =  "Harami  Cross"  ,defval=true)
HaramiInput  =  input(title  =  "Harami"  ,defval=true)
InvertedHammerInput  =  input(title  =  "Inverted  Hammer"  ,defval=true)
KickingInput  =  input(title  =  "Kicking"  ,defval=true)
LongLowerShadowInput  =  input(title  =  "Long  Lower  Shadow"  ,defval=false)
LongUpperShadowInput  =  input(title  =  "Long  Upper  Shadow"  ,defval=false)
MarubozuBlackInput  =  input(title  =  "Marubozu  Black"  ,defval=true)
MarubozuWhiteInput  =  input(title  =  "Marubozu  White"  ,defval=true)
MorningDojiStarInput  =  input(title  =  "Morning  Doji  Star"  ,defval=true)
MorningStarInput  =  input(title  =  "Morning  Star"  ,defval=true)
OnNeckInput  =  input(title  =  "On  Neck"  ,defval=true)
PiercingInput  =  input(title  =  "Piercing"  ,defval=true)
RisingThreeMethodsInput  =  input(title  =  "Rising  Three  Methods"  ,defval=true)
RisingWindowInput  =  input(title  =  "Rising  Window"  ,defval=true)
ShootingStarInput  =  input(title  =  "Shooting  Star"  ,defval=true)
SpinningTopBlackInput  =  input(title  =  "Spinning  Top  Black"  ,defval=false)
SpinningTopWhiteInput  =  input(title  =  "SpinningTopWhite",defval=false)
ThreeBlackCrowsInput=input(title="ThreeBlackCrows",defval=true)
ThreeWhiteSoldiersInput=input(title="ThreeWhiteSoldiers",defval=true)
TriStarInput=input(title="Tri-Star",defval=true)
TweezerBottomInput=input(title="TweezerBottom",defval=true)
TweezerTopInput=input(title="TweezerTop",defval=true)
UpsideTasukiGapInput=input(title="UpsideTasukiGap",defval=true)
C_OnNeckBearishNumberOfCandles=2
C_OnNeckBearish=false
ifC_DownTrendandC_BlackBody[1]andC_LongBody[1]andC_WhiteBodyandopen<close[1]andC_SmallBodyandC_Range!=0andabs(close-low[1])<=C_BodyAvg*0.05
C_OnNeckBearish:=true
ifC_OnNeckBearishandOnNeckInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishOnNeck="OnNeck\nOnNeckisatwo-linecontinuationpatternfoundinadowntrend.Thefirstcandleislongandred,thesecondcandleisshortandhasagreenbody.Theclosingpriceofthesecondcandleiscloseorequaltothefirstcandle'slowprice.Thepatternhintsatacontinuationofadowntrend,andpenetratingthelowofthegreencandlestickissometimesconsideredaconfirmation."
label.new(bar_index,patternLabelPosHigh,text="ON",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishOnNeck)

C_RisingWindowBullishNumberOfCandles=2
C_RisingWindowBullish=false
ifC_UpTrend[1]and(C_Range!=0andC_Range[1]!=0)andlow>high[1]
C_RisingWindowBullish:=true
ifC_RisingWindowBullishandRisingWindowInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishRisingWindow="RisingWindow\nRisingWindowisatwo-candlebullishcontinuationpatternthatformsduringanuptrend.BothcandlesinthepatterncanbeofanytypewiththeexceptionoftheFour-PriceDoji.Themostimportantcharacteristicofthepatternisapricegapbetweenthefirstcandle'shighandthesecondcandle'slow.Thatgap(window)betweentwobarssignifiessupportagainstthesellingpressure."
_tradeDirection:="bullish"
label.new(bar_index,patternLabelPosLow,text="RW",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishRisingWindow)
C_FallingWindowBearishNumberOfCandles=2
C_FallingWindowBearish=false
ifC_DownTrend[1]and(C_Range!=0andC_Range[1]!=0)andhigh<low[1]
C_FallingWindowBearish:=true
ifC_FallingWindowBearishandFallingWindowInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishFallingWindow="FallingWindow\nFallingWindowisatwo-candlebearishcontinuationpatternthatformsduringadowntrend.Bothcandlesinthepatterncanbeofanytype,withtheexceptionoftheFour-PriceDoji.Themostimportantcharacteristicofthepatternisapricegapbetweenthefirstcandle'slowandthesecondcandle'shigh.Theexistenceofthisgap(window)meansthatthebearishtrendisexpectedtocontinue."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="FW",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishFallingWindow)
C_FallingThreeMethodsBearishNumberOfCandles=5
C_FallingThreeMethodsBearish=false
ifC_DownTrend[4]and(C_LongBody[4]andC_BlackBody[4])and(C_SmallBody[3]andC_WhiteBody[3]andopen[3]>low[4]andclose[3]<high[4])and(C_SmallBody[2]andC_WhiteBody[2]andopen[2]>low[4]andclose[2]<high[4])and(C_SmallBody[1]andC_WhiteBody[1]andopen[1]>low[4]andclose[1]<high[4])and(C_LongBodyandC_BlackBodyandclose<close[4])
C_FallingThreeMethodsBearish:=true
ifC_FallingThreeMethodsBearishandFallingThreeMethodsInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishFallingThreeMethods="FallingThreeMethods\nFallingThreeMethodsisafive-candlebearishpatternthatsignifiesacontinuationofanexistingdowntrend.Thefirstcandleislongandred,followedbythreeshortgreencandleswithbodiesinsidetherangeofthefirstcandle.Thelastcandleisalsoredandlonganditclosesbelowthecloseofthefirstcandle.Thisdecisivefifthstronglybearishcandlehintsthatbullscouldnotreversethepriordowntrendandthatbearshaveregainedcontrolofthemarket."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="FTM",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishFallingThreeMethods)
C_RisingThreeMethodsBullishNumberOfCandles=5
C_RisingThreeMethodsBullish=false
ifC_UpTrend[4]and(C_LongBody[4]andC_WhiteBody[4])and(C_SmallBody[3]andC_BlackBody[3]andopen[3]<high[4]andclose[3]>low[4])and(C_SmallBody[2]andC_BlackBody[2]andopen[2]<high[4]andclose[2]>low[4])and(C_SmallBody[1]andC_BlackBody[1]andopen[1]<high[4]andclose[1]>low[4])and(C_LongBodyandC_WhiteBodyandclose>close[4])
C_RisingThreeMethodsBullish:=true
ifC_RisingThreeMethodsBullishandRisingThreeMethodsInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishRisingThreeMethods="RisingThreeMethods\nRisingThreeMethodsisafive-candlebullishpatternthatsignifiesacontinuationofanexistinguptrend.Thefirstcandleislongandgreen,followedbythreeshortredcandleswithbodiesinsidetherangeofthefirstcandle.Thelastcandleisalsogreenandlonganditclosesabovethecloseofthefirstcandle.Thisdecisivefifthstronglybullishcandlehintsthatbearscouldnotreversetheprioruptrendandthatbullshaveregainedcontrolofthemarket."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="RTM",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishRisingThreeMethods)
C_TweezerTopBearishNumberOfCandles=2
C_TweezerTopBearish=false
ifC_UpTrend[1]and(notC_IsDojiBodyor(C_HasUpShadowandC_HasDnShadow))andabs(high-high[1])<=C_BodyAvg*0.05andC_WhiteBody[1]andC_BlackBodyandC_LongBody[1]
C_TweezerTopBearish:=true
ifC_TweezerTopBearishandTweezerTopInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishTweezerTop="TweezerTop\nTweezerTopisatwo-candlepatternthatsignifiesapotentialbearishreversal.Thepatternisfoundduringanuptrend.Thefirstcandleislongandgreen,thesecondcandleisred,anditshighisnearlyidenticaltothehighofthepreviouscandle.Thevirtuallyidenticalhighs,togetherwiththeinverteddirections,hintthatbearsmightbetakingoverthemarket."
_tradeDirection:="bearish"


label.new(bar_index,patternLabelPosHigh,text="TT",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishTweezerTop)
C_TweezerBottomBullishNumberOfCandles=2
C_TweezerBottomBullish=false
ifC_UpTrend[1]and(notC_IsDojiBodyor(C_HasUpShadowandC_HasDnShadow))andabs(low-low[1])<=C_BodyAvg*0.05andC_BlackBody[1]andC_WhiteBodyandC_LongBody[1]
C_TweezerBottomBullish:=true
ifC_TweezerBottomBullishandTweezerBottomInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishTweezerBottom="TweezerBottom\nTweezerBottomisatwo-candlepatternthatsignifiesapotentialbullishreversal.Thepatternisfoundduringadowntrend.Thefirstcandleislongandred,thesecondcandleisgreen,itslowsnearlyidenticaltothelowofthepreviouscandle.Thevirtuallyidenticallowstogetherwiththeinverteddirectionshintthatbullsmightbetakingoverthemarket."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="TB",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishTweezerBottom)
C_DarkCloudCoverBearishNumberOfCandles=2
C_DarkCloudCoverBearish=false
if(C_UpTrend[1]andC_WhiteBody[1]andC_LongBody[1])and(C_BlackBodyandopen>=high[1]andclose<C_BodyMiddle[1]andclose>open[1])
C_DarkCloudCoverBearish:=true
ifC_DarkCloudCoverBearishandDarkCloudCoverInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishDarkCloudCover="DarkCloudCover\nDarkCloudCoverisatwo-candlebearishreversalcandlestickpatternfoundinanuptrend.Thefirstcandleisgreenandhasalargerthanaveragebody.Thesecondcandleisredandopensabovethehighofthepriorcandle,creatingagap,andthenclosesbelowthemidpointofthefirstcandle.Thepatternshowsapossibleshiftinthemomentumfromtheupsidetothedownside,indicatingthatareversalmighthappensoon."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosHigh,text="DCC",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishDarkCloudCover)
C_DownsideTasukiGapBearishNumberOfCandles=3
C_DownsideTasukiGapBearish=false
ifC_LongBody[2]andC_SmallBody[1]andC_DownTrendandC_BlackBody[2]andC_BodyHi[1]<C_BodyLo[2]andC_BlackBody[1]andC_WhiteBodyandC_BodyHi<=C_BodyLo[2]andC_BodyHi>=C_BodyHi[1]
C_DownsideTasukiGapBearish:=true
ifC_DownsideTasukiGapBearishandDownsideTasukiGapInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishDownsideTasukiGap="DownsideTasukiGap\nDownsideTasukiGapisathree-candlepatternfoundinadowntrendthatusuallyhintsatthecontinuationofthedowntrend.Thefirstcandleislongandred,followedbyasmallerredcandlewithitsopeningpricethatgapsbelowthebodyofthepreviouscandle.Thethirdcandleisgreenanditclosesinsidethegapcreatedbythefirsttwocandles,unabletocloseitfully.Thebull’sinabilitytoclosethatgaphintsthatthedowntrendmightcontinue."
_tradeDirection:="bearish"





label.new(bar_index,patternLabelPosHigh,text="DTG",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishDownsideTasukiGap)
C_UpsideTasukiGapBullishNumberOfCandles=3
C_UpsideTasukiGapBullish=false
ifC_LongBody[2]andC_SmallBody[1]andC_UpTrendandC_WhiteBody[2]andC_BodyLo[1]>C_BodyHi[2]andC_WhiteBody[1]andC_BlackBodyandC_BodyLo>=C_BodyHi[2]andC_BodyLo<=C_BodyLo[1]
C_UpsideTasukiGapBullish:=true
ifC_UpsideTasukiGapBullishandUpsideTasukiGapInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishUpsideTasukiGap="UpsideTasukiGap\nUpsideTasukiGapisathree-candlepatternfoundinanuptrendthatusuallyhintsatthecontinuationoftheuptrend.Thefirstcandleislongandgreen,followedbyasmallergreencandlewithitsopeningpricethatgapsabovethebodyofthepreviouscandle.Thethirdcandleisredanditclosesinsidethegapcreatedbythefirsttwocandles,unabletocloseitfully.Thebear’sinabilitytoclosethegaphintsthattheuptrendmightcontinue."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="UTG",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishUpsideTasukiGap)
C_EveningDojiStarBearishNumberOfCandles=3
C_EveningDojiStarBearish=false
ifC_LongBody[2]andC_IsDojiBody[1]andC_LongBodyandC_UpTrendandC_WhiteBody[2]andC_BodyLo[1]>C_BodyHi[2]andC_BlackBodyandC_BodyLo<=C_BodyMiddle[2]andC_BodyLo>C_BodyLo[2]andC_BodyLo[1]>C_BodyHi
C_EveningDojiStarBearish:=true
ifC_EveningDojiStarBearishandEveningDojiStarInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishEveningDojiStar="EveningDojiStar\nThiscandlestickpatternisavariationoftheEveningStarpattern.Itisbearishandcontinuesanuptrendwithalong-bodied,greencandleday.ItisthenfollowedbyagapandaDojicandleandconcludeswithadownwardclose.Theclosewouldbebelowthefirstday’smidpoint.ItismorebearishthantheregulareveningstarpatternbecauseoftheexistenceoftheDoji."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="EDS",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishEveningDojiStar)
C_DojiStarBearishNumberOfCandles=2
C_DojiStarBearish=false
ifC_UpTrendandC_WhiteBody[1]andC_LongBody[1]andC_IsDojiBodyandC_BodyLo>C_BodyHi[1]
C_DojiStarBearish:=true
ifC_DojiStarBearishandDojiStarInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishDojiStar="DojiStar\nThisisabearishreversalcandlestickpatternthatisfoundinanuptrendandconsistsoftwocandles.Firstcomesalonggreencandle,followedbyaDojicandle(except4-PriceDoji)thatopensabovethebodyofthefirstone,creatingagap.Itisconsideredareversalsignalwithconfirmationduringthenexttradingday."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="DS",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishDojiStar)
C_DojiStarBullishNumberOfCandles=2
C_DojiStarBullish=false
ifC_DownTrendandC_BlackBody[1]andC_LongBody[1]andC_IsDojiBodyandC_BodyHi<C_BodyLo[1]
C_DojiStarBullish:=true
ifC_DojiStarBullishandDojiStarInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishDojiStar="DojiStar\nThisisabullishreversalcandlestickpatternthatisfoundinadowntrendandconsistsoftwocandles.Firstcomesalongredcandle,followedbyaDojicandle(except4-PriceDoji)thatopensbelowthebodyofthefirstone,creatingagap.Itisconsideredareversalsignalwithconfirmationduringthenexttradingday."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="DS",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishDojiStar)
C_MorningDojiStarBullishNumberOfCandles=3
C_MorningDojiStarBullish=false
ifC_LongBody[2]andC_IsDojiBody[1]andC_LongBodyandC_DownTrendandC_BlackBody[2]andC_BodyHi[1]<C_BodyLo[2]andC_WhiteBodyandC_BodyHi>=C_BodyMiddle[2]andC_BodyHi<C_BodyHi[2]andC_BodyHi[1]<C_BodyLo
C_MorningDojiStarBullish:=true
ifC_MorningDojiStarBullishandMorningDojiStarInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishMorningDojiStar="MorningDojiStar\nThiscandlestickpatternisavariationoftheMorningStarpattern.Athree-daybullishreversalpattern,whichconsistsofthreecandlestickswilllooksomethinglikethis:Thefirstbeingalong-bodiedredcandlethatextendsthecurrentdowntrend.NextcomesaDojithatgapsdownontheopen.Afterthatcomesalong-bodiedgreencandle,whichgapsupontheopenandclosesabovethemidpointofthebodyofthefirstday.ItismorebullishthantheregularmorningstarpatternbecauseoftheexistenceoftheDoji."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="MDS",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishMorningDojiStar)
C_PiercingBullishNumberOfCandles=2
C_PiercingBullish=false
if(C_DownTrend[1]andC_BlackBody[1]andC_LongBody[1])and(C_WhiteBodyandopen<=low[1]andclose>C_BodyMiddle[1]andclose<open[1])
C_PiercingBullish:=true
ifC_PiercingBullishandPiercingInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishPiercing="Piercing\nPiercingisatwo-candlebullishreversalcandlestickpatternfoundinadowntrend.Thefirstcandleisredandhasalargerthanaveragebody.Thesecondcandleisgreenandopensbelowthelowofthepriorcandle,creatingagap,andthenclosesabovethemidpointofthefirstcandle.Thepatternshowsapossibleshiftinthemomentumfromthedownsidetotheupside,indicatingthatareversalmighthappensoon."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="P",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishPiercing)
C_HammerBullishNumberOfCandles=1
C_HammerBullish=false
ifC_SmallBodyandC_Body>0andC_BodyLo>hl2andC_DnShadow>=C_Factor*C_BodyandnotC_HasUpShadow
ifC_DownTrend
C_HammerBullish:=true
ifC_HammerBullishandHammerInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishHammer="Hammer\nHammercandlesticksformwhenasecuritymovesloweraftertheopen,butcontinuestorallyintocloseabovetheintradaylow.Thecandlestickthatyouareleftwithwilllooklikeasquareattachedtoalongstick-likefigure.ThiscandlestickiscalledaHammerifithappenstoformduringadecline."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="H",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishHammer)
C_HangingManBearishNumberOfCandles=1
C_HangingManBearish=false
ifC_SmallBodyandC_Body>0andC_BodyLo>hl2andC_DnShadow>=C_Factor*C_BodyandnotC_HasUpShadow
ifC_UpTrend
C_HangingManBearish:=true
ifC_HangingManBearishandHangingManInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishHangingMan="HangingMan\nWhenaspecifiedsecuritynotablymovesloweraftertheopen,butcontinuestorallytocloseabovetheintradaylow,aHangingMancandlestickwillform.Thecandlestickwillresembleasquare,attachedtoalongstick-likefigure.ItisreferredtoasaHangingManifthecandlestickformsduringanadvance."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="HM",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishHangingMan)
C_ShootingStarBearishNumberOfCandles=1
C_ShootingStarBearish=false
ifC_SmallBodyandC_Body>0andC_BodyHi<hl2andC_UpShadow>=C_Factor*C_BodyandnotC_HasDnShadow
ifC_UpTrend
C_ShootingStarBearish:=true
ifC_ShootingStarBearishandShootingStarInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishShootingStar="ShootingStar\nThissingledaypatterncanappearduringanuptrendandopenshigh,whileitclosesnearitsopen.Ittradesmuchhigheraswell.Itisbearishinnature,butlookslikeanInvertedHammer."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="SS",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishShootingStar)
C_InvertedHammerBullishNumberOfCandles=1
C_InvertedHammerBullish=false
ifC_SmallBodyandC_Body>0andC_BodyHi<hl2andC_UpShadow>=C_Factor*C_BodyandnotC_HasDnShadow
ifC_DownTrend
C_InvertedHammerBullish:=true
ifC_InvertedHammerBullishandInvertedHammerInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishInvertedHammer="InvertedHammer\nIfinadowntrend,thentheopenislower.Wheniteventuallytradeshigher,butclosesnearitsopen,itwilllooklikeaninvertedversionoftheHammerCandlestick.Thisisaone-daybullishreversalpattern."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="IH",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishInvertedHammer)
C_MorningStarBullishNumberOfCandles=3
C_MorningStarBullish=false
ifC_LongBody[2]andC_SmallBody[1]andC_LongBody
ifC_DownTrendandC_BlackBody[2]andC_BodyHi[1]<C_BodyLo[2]andC_WhiteBodyandC_BodyHi>=C_BodyMiddle[2]andC_BodyHi<C_BodyHi[2]andC_BodyHi[1]<C_BodyLo
C_MorningStarBullish:=true
ifC_MorningStarBullishandMorningStarInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishMorningStar="MorningStar\nAthree-daybullishreversalpattern,whichconsistsofthreecandlestickswilllooksomethinglikethis:Thefirstbeingalong-bodiedredcandlethatextendsthecurrentdowntrend.Nextcomesashort,middlecandlethatgapsdownontheopen.Aftercomesalong-bodiedgreencandle,whichgapsupontheopenandclosesabovethemidpointofthebodyofthefirstday."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="MS",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishMorningStar)
C_EveningStarBearishNumberOfCandles=3
C_EveningStarBearish=false
ifC_LongBody[2]andC_SmallBody[1]andC_LongBody
ifC_UpTrendandC_WhiteBody[2]andC_BodyLo[1]>C_BodyHi[2]andC_BlackBodyandC_BodyLo<=C_BodyMiddle[2]andC_BodyLo>C_BodyLo[2]andC_BodyLo[1]>C_BodyHi
C_EveningStarBearish:=true
ifC_EveningStarBearishandEveningStarInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishEveningStar="EveningStar\nThiscandlestickpatternisbearishandcontinuesanuptrendwithalong-bodied,greencandleday.Itisthenfollowedbyagappedandsmall-bodiedcandleday,andconcludeswithadownwardclose.Theclosewouldbebelowthefirstday’smidpoint."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="ES",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishEveningStar)
C_MarubozuWhiteBullishNumberOfCandles=1
C_MarubozuShadowPercentWhite=5.0
C_MarubozuWhiteBullish=C_WhiteBodyandC_LongBodyandC_UpShadow<=C_MarubozuShadowPercentWhite/100*C_BodyandC_DnShadow<=C_MarubozuShadowPercentWhite/100*C_BodyandC_WhiteBody
ifC_MarubozuWhiteBullishandMarubozuWhiteInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishMarubozuWhite="MarubozuWhite\nAMarubozuWhiteCandleisacandlestickthatdoesnothaveashadowthatextendsfromitscandlebodyateithertheopenortheclose.MarubozuisJapanesefor“close-cropped”or“close-cut.”OthersourcesmaycallitaBaldorShavenHeadCandle."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="MW",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishMarubozuWhite)
C_MarubozuBlackBearishNumberOfCandles=1
C_MarubozuShadowPercentBearish=5.0
C_MarubozuBlackBearish=C_BlackBodyandC_LongBodyandC_UpShadow<=C_MarubozuShadowPercentBearish/100*C_BodyandC_DnShadow<=C_MarubozuShadowPercentBearish/100*C_BodyandC_BlackBody
ifC_MarubozuBlackBearishandMarubozuBlackInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishMarubozuBlack="MarubozuBlack\nThisisacandlestickthathasnoshadow,whichextendsfromthered-bodiedcandleattheopen,theclose,orevenatboth.InJapanese,thenamemeans“close-cropped”or“close-cut.”ThecandlestickcanalsobereferredtoasBaldorShavenHead."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="MB",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishMarubozuBlack)
C_DojiNumberOfCandles=1
C_DragonflyDoji=C_IsDojiBodyandC_UpShadow<=C_Body
C_GravestoneDojiOne=C_IsDojiBodyandC_DnShadow<=C_Body
ifC_DojiandnotC_DragonflyDojiandnotC_GravestoneDojiOneandDojiInput
varttDoji="Doji\nWhentheopenandcloseofasecurityareessentiallyequaltoeachother,adojicandleforms.Thelengthofbothupperandlowershadowsmayvary,causingthecandlestickyouareleftwithtoeitherresembleacross,aninvertedcross,oraplussign.Dojicandlesshowtheplayoutofbuyer-sellerindecisioninatug-of-warofsorts.Aspricemoveseitheraboveorbelowtheopeninglevelduringthesession,thecloseiseitheratorneartheopeninglevel."



label.new(bar_index,patternLabelPosLow,text="D",style=label.style_label_up,color=color.gray,textcolor=color.white,tooltip=ttDoji)
C_GravestoneDojiBearishNumberOfCandles=1
C_GravestoneDojiBearish=C_IsDojiBodyandC_DnShadow<=C_Body
ifC_GravestoneDojiBearishandGravestoneDojiInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishGravestoneDoji="GravestoneDoji\nWhenadojiisatorisclosetotheday’slowpoint,adojilinewilldevelop."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="GD",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishGravestoneDoji)
C_DragonflyDojiBullishNumberOfCandles=1
C_DragonflyDojiBullish=C_IsDojiBodyandC_UpShadow<=C_Body
ifC_DragonflyDojiBullishandDragonflyDojiInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishDragonflyDoji="DragonflyDoji\nSimilartootherDojidays,thisparticularDojialsoregularlyappearsatpivotalmarketmoments.ThisisaspecificDojiwhereboththeopenandclosepriceareatthehighofagivenday."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="DD",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishDragonflyDoji)
C_HaramiCrossBullishNumberOfCandles=2
C_HaramiCrossBullish=C_LongBody[1]andC_BlackBody[1]andC_DownTrend[1]andC_IsDojiBodyandhigh<=C_BodyHi[1]andlow>=C_BodyLo[1]
ifC_HaramiCrossBullishandHaramiCrossInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishHaramiCross="HaramiCross\nThiscandlestickpatternisavariationoftheHaramiBullishpattern.Itisfoundduringadowntrend.Thetwo-daycandlestickpatternconsistsofaDojicandlethatisentirelyencompassedwithinthebodyofwhatwasonceared-bodiedcandle."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="HC",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishHaramiCross)
C_HaramiCrossBearishNumberOfCandles=2
C_HaramiCrossBearish=C_LongBody[1]andC_WhiteBody[1]andC_UpTrend[1]andC_IsDojiBodyandhigh<=C_BodyHi[1]andlow>=C_BodyLo[1]
ifC_HaramiCrossBearishandHaramiCrossInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishHaramiCross="HaramiCross\nThiscandlestickpatternisavariationoftheHaramiBearishpattern.Itisfoundduringanuptrend.Thisisatwo-daycandlestickpatternwithaDojicandlethatisentirelyencompassedwithinthebodythatwasonceagreen-bodiedcandle.TheDojishowsthatsomeindecisionhasenteredthemindsofsellers,andthepatternhintsthatthetrendmightreverse."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="HC",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishHaramiCross)
C_HaramiBullishNumberOfCandles=2
C_HaramiBullish=C_LongBody[1]andC_BlackBody[1]andC_DownTrend[1]andC_WhiteBodyandC_SmallBodyandhigh<=C_BodyHi[1]andlow>=C_BodyLo[1]
ifC_HaramiBullishandHaramiInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishHarami="Harami\nThistwo-daycandlestickpatternconsistsofasmall-bodiedgreencandlethatisentirelyencompassedwithinthebodyofwhatwasonceared-bodiedcandle."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="BH",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishHarami)
C_HaramiBearishNumberOfCandles=2
C_HaramiBearish=C_LongBody[1]andC_WhiteBody[1]andC_UpTrend[1]andC_BlackBodyandC_SmallBodyandhigh<=C_BodyHi[1]andlow>=C_BodyLo[1]
ifC_HaramiBearishandHaramiInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishHarami="Harami\nThisisatwo-daycandlestickpatternwithasmall,red-bodiedcandlethatisentirelyencompassedwithinthebodythatwasonceagreen-bodiedcandle."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="BH",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishHarami)
C_LongLowerShadowBullishNumberOfCandles=1
C_LongLowerShadowPercent=75.0
C_LongLowerShadowBullish=C_DnShadow>C_Range/100*C_LongLowerShadowPercent
ifC_LongLowerShadowBullishandLongLowerShadowInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishLongLowerShadow="LongLowerShadow\nToindicatesellerdominationofthefirstpartofasession,candlestickswillpresentwithlonglowershadowsandshortuppershadows,consequentlyloweringprices."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="LLS",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishLongLowerShadow)
C_LongUpperShadowBearishNumberOfCandles=1
C_LongShadowPercent=75.0
C_LongUpperShadowBearish=C_UpShadow>C_Range/100*C_LongShadowPercent
ifC_LongUpperShadowBearishandLongUpperShadowInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishLongUpperShadow="LongUpperShadow\nToindicatebuyerdominationofthefirstpartofasession,candlestickswillpresentwithlonguppershadows,aswellasshortlowershadows,consequentlyraisingbiddingprices."
_tradeDirection:="bearish"





label.new(bar_index,patternLabelPosHigh,text="LUS",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishLongUpperShadow)
C_SpinningTopWhiteNumberOfCandles=1
C_SpinningTopWhitePercent=34.0
C_IsSpinningTopWhite=C_DnShadow>=C_Range/100*C_SpinningTopWhitePercentandC_UpShadow>=C_Range/100*C_SpinningTopWhitePercentandnotC_IsDojiBody
C_SpinningTopWhite=C_IsSpinningTopWhiteandC_WhiteBody
ifC_SpinningTopWhiteandSpinningTopWhiteInput
varttSpinningTopWhite="SpinningTopWhite\nWhitespinningtopsarecandlesticklinesthataresmall,green-bodied,andpossessshadows(upperandlower)thatendupexceedingthelengthofcandlebodies.Theyoftensignalindecisionbetweenbuyerandseller."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="STW",style=label.style_label_up,color=color.gray,textcolor=color.white,tooltip=ttSpinningTopWhite)
C_SpinningTopBlackNumberOfCandles=1
C_SpinningTopBlackPercent=34.0
C_IsSpinningTop=C_DnShadow>=C_Range/100*C_SpinningTopBlackPercentandC_UpShadow>=C_Range/100*C_SpinningTopBlackPercentandnotC_IsDojiBody
C_SpinningTopBlack=C_IsSpinningTopandC_BlackBody
ifC_SpinningTopBlackandSpinningTopBlackInput
varttSpinningTopBlack="SpinningTopBlack\nBlackspinningtopsarecandlesticklinesthataresmall,red-bodied,andpossessshadows(upperandlower)thatendupexceedingthelengthofcandlebodies.Theyoftensignalindecision."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosLow,text="STB",style=label.style_label_up,color=color.gray,textcolor=color.white,tooltip=ttSpinningTopBlack)
C_ThreeWhiteSoldiersBullishNumberOfCandles=3
C_3WSld_ShadowPercent=5.0
C_3WSld_HaveNotUpShadow=C_Range*C_3WSld_ShadowPercent/100>C_UpShadow
C_ThreeWhiteSoldiersBullish=false
ifC_LongBodyandC_LongBody[1]andC_LongBody[2]
ifC_WhiteBodyandC_WhiteBody[1]andC_WhiteBody[2]
C_ThreeWhiteSoldiersBullish:=close>close[1]andclose[1]>close[2]andopen<close[1]andopen>open[1]andopen[1]<close[2]andopen[1]>open[2]andC_3WSld_HaveNotUpShadowandC_3WSld_HaveNotUpShadow[1]andC_3WSld_HaveNotUpShadow[2]
ifC_ThreeWhiteSoldiersBullishandThreeWhiteSoldiersInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishThreeWhiteSoldiers="ThreeWhiteSoldiers\nThisbullishreversalpatternismadeupofthreelong-bodied,greencandlesinimmediatesuccession.Eachoneopenswithinthebodybeforeitandthecloseisneartothedailyhigh."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="3WS",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishThreeWhiteSoldiers)
C_ThreeBlackCrowsBearishNumberOfCandles=3
C_3BCrw_ShadowPercent=5.0
C_3BCrw_HaveNotDnShadow=C_Range*C_3BCrw_ShadowPercent/100>C_DnShadow
C_ThreeBlackCrowsBearish=false
ifC_LongBodyandC_LongBody[1]andC_LongBody[2]
ifC_BlackBodyandC_BlackBody[1]andC_BlackBody[2]
C_ThreeBlackCrowsBearish:=close<close[1]andclose[1]<close[2]andopen>close[1]andopen<open[1]andopen[1]>close[2]andopen[1]<open[2]andC_3BCrw_HaveNotDnShadowandC_3BCrw_HaveNotDnShadow[1]andC_3BCrw_HaveNotDnShadow[2]
ifC_ThreeBlackCrowsBearishandThreeBlackCrowsInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishThreeBlackCrows="ThreeBlackCrows\nThisisabearishreversalpatternthatconsistsofthreelong,red-bodiedcandlesinimmediatesuccession.Foreachofthesecandles,eachdayopenswithinthebodyofthedaybeforeandcloseseitheratornearitslow."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="3BC",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishThreeBlackCrows)
C_EngulfingBullishNumberOfCandles=2
C_EngulfingBullish=C_DownTrendandC_WhiteBodyandC_LongBodyandC_BlackBody[1]andC_SmallBody[1]andclose>=open[1]andopen<=close[1]and(close>open[1]oropen<close[1])
ifC_EngulfingBullishandEngulfingInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishEngulfing="Engulfing\nAttheendofagivendownwardtrend,therewillmostlikelybeareversalpattern.Todistinguishthefirstday,thiscandlestickpatternusesasmallbody,followedbyadaywherethecandlebodyfullyovertakesthebodyfromthedaybefore,andclosesinthetrend’soppositedirection.Althoughsimilartotheoutsidereversalchartpattern,itisnotessentialforthispatterntocompletelyovertaketherange(hightolow),ratheronlytheopenandtheclose."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="BE",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishEngulfing)
C_EngulfingBearishNumberOfCandles=2
C_EngulfingBearish=C_UpTrendandC_BlackBodyandC_LongBodyandC_WhiteBody[1]andC_SmallBody[1]andclose<=open[1]andopen>=close[1]and(close<open[1]oropen>close[1])
ifC_EngulfingBearishandEngulfingInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishEngulfing="Engulfing\nAttheendofagivenuptrend,areversalpatternwillmostlikelyappear.Duringthefirstday,thiscandlestickpatternusesasmallbody.Itisthenfollowedbyadaywherethecandlebodyfullyovertakesthebodyfromthedaybeforeitandclosesinthetrend’soppositedirection.Althoughsimilartotheoutsidereversalchartpattern,itisnotessentialforthispatterntofullyovertaketherange(hightolow),ratheronlytheopenandtheclose."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="BE",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishEngulfing)
C_AbandonedBabyBullishNumberOfCandles=3
C_AbandonedBabyBullish=C_DownTrend[2]andC_BlackBody[2]andC_IsDojiBody[1]andlow[2]>high[1]andC_WhiteBodyandhigh[1]<low
ifC_AbandonedBabyBullishandAbandonedBabyInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishAbandonedBaby="AbandonedBaby\nThiscandlestickpatternisquiterareasfarasreversalpatternsgo.Thefirstofthepatternisalargedowncandle.Nextcomesadojicandlethatgapsbelowthecandlebeforeit.Thedojicandleisthenfollowedbyanothercandlethatopensevenhigherandswiftlymovestotheupside."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="AB",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishAbandonedBaby)
C_AbandonedBabyBearishNumberOfCandles=3
C_AbandonedBabyBearish=C_UpTrend[2]andC_WhiteBody[2]andC_IsDojiBody[1]andhigh[2]<low[1]andC_BlackBodyandlow[1]>high
ifC_AbandonedBabyBearishandAbandonedBabyInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishAbandonedBaby="AbandonedBaby\nAbearishabandonedbabyisaspecificcandlestickpatternthatoftensignalsadownwardreversaltrendintermsofsecurityprice.Itisformedwhenagapappearsbetweenthelowestpriceofadoji-likecandleandthecandlestickofthedaybefore.Theearliercandlestickisgreen,tall,andhassmallshadows.Thedojicandleisalsotailedbyagapbetweenitslowestpricepointandthehighestpricepointofthecandlethatcomesnext,whichisred,tallandalsohassmallshadows.Thedojicandleshadowsmustcompletelygapeitherbeloworabovetheshadowsofthefirstandthirddayinordertohavetheabandonedbabypatterneffect."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="AB",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishAbandonedBaby)
C_TriStarBullishNumberOfCandles=3
C_3DojisBullish=C_Doji[2]andC_Doji[1]andC_Doji
C_BodyGapUpBullish=C_BodyHi[1]<C_BodyLo
C_BodyGapDnBullish=C_BodyLo[1]>C_BodyHi
C_TriStarBullish=C_3DojisBullishandC_DownTrend[2]andC_BodyGapDnBullish[1]andC_BodyGapUpBullish
ifC_TriStarBullishandTriStarInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishTriStar="Tri-Star\nAbullishTriStarcandlestickpatterncanformwhenthreedojicandlesticksmaterializeinimmediatesuccessionatthetail-endofanextendeddowntrend.Thefirstdojicandlemarksindecisionbetweenbullandbear.Theseconddojigapsinthedirectionoftheleadingtrend.Thethirdchangestheattitudeofthemarketoncethecandlestickopensinthedirectionoppositetothetrend.Eachdojicandlehasashadow,allcomparativelyshallow,whichsignifyaninterimcutbackinvolatility."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="3S",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishTriStar)
C_TriStarBearishNumberOfCandles=3
C_3Dojis=C_Doji[2]andC_Doji[1]andC_Doji
C_BodyGapUp=C_BodyHi[1]<C_BodyLo
C_BodyGapDn=C_BodyLo[1]>C_BodyHi
C_TriStarBearish=C_3DojisandC_UpTrend[2]andC_BodyGapUp[1]andC_BodyGapDn
ifC_TriStarBearishandTriStarInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishTriStar="Tri-Star\nThisparticularpatterncanformwhenthreedojicandlesticksappearinimmediatesuccessionattheendofanextendeduptrend.Thefirstdojicandlemarksindecisionbetweenbullandbear.Theseconddojigapsinthedirectionoftheleadingtrend.Thethirdchangestheattitudeofthemarketoncethecandlestickopensinthedirectionoppositetothetrend.Eachdojicandlehasashadow,allcomparativelyshallow,whichsignifyaninterimcutbackinvolatility."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="3S",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishTriStar)
C_KickingBullishNumberOfCandles=2
C_MarubozuShadowPercent=5.0
C_Marubozu=C_LongBodyandC_UpShadow<=C_MarubozuShadowPercent/100*C_BodyandC_DnShadow<=C_MarubozuShadowPercent/100*C_Body
C_MarubozuWhiteBullishKicking=C_MarubozuandC_WhiteBody
C_MarubozuBlackBullish=C_MarubozuandC_BlackBody
C_KickingBullish=C_MarubozuBlackBullish[1]andC_MarubozuWhiteBullishKickingandhigh[1]<low
ifC_KickingBullishandKickingInputand(("Bullish"==CandleType)orCandleType=="Both")
varttBullishKicking="Kicking\nThefirstdaycandlestickisabearishmarubozucandlestickwithnexttonoupperorlowershadowandwherethepriceopensattheday’shighandclosesattheday’slow.Theseconddayisabullishmarubozupattern,withnexttonoupperorlowershadowandwherethepriceopensattheday’slowandclosesattheday’shigh.Additionally,theseconddaygapsupextensivelyandopensabovetheopeningpriceofthedaybefore.Thisgaporwindow,astheJapanesecallit,liesbetweendayoneanddaytwo’sbullishcandlesticks."
_tradeDirection:="bullish"

label.new(bar_index,patternLabelPosLow,text="K",style=label.style_label_up,color=color.blue,textcolor=color.white,tooltip=ttBullishKicking)
C_KickingBearishNumberOfCandles=2
C_MarubozuBullishShadowPercent=5.0
C_MarubozuBearishKicking=C_LongBodyandC_UpShadow<=C_MarubozuBullishShadowPercent/100*C_BodyandC_DnShadow<=C_MarubozuBullishShadowPercent/100*C_Body
C_MarubozuWhiteBearish=C_MarubozuBearishKickingandC_WhiteBody
C_MarubozuBlackBearishKicking=C_MarubozuBearishKickingandC_BlackBody
C_KickingBearish=C_MarubozuWhiteBearish[1]andC_MarubozuBlackBearishKickingandlow[1]>high
ifC_KickingBearishandKickingInputand(("Bearish"==CandleType)orCandleType=="Both")
varttBearishKicking="Kicking\nAbearishkickingpatternwilloccur,subsequentlysignalingareversalforanewdowntrend.Thefirstdaycandlestickisabullishmarubozu.Theseconddaygapsdownextensivelyandopensbelowtheopeningpriceofthedaybefore.Thereisagapbetweendayoneandtwo’sbearishcandlesticks."
_tradeDirection:="bearish"

label.new(bar_index,patternLabelPosHigh,text="K",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishKicking)
varttAllCandlestickPatterns="AllCandlestickPatterns\n"
label.new(bar_index,patternLabelPosLow,text="Collection",style=label.style_label_up,color=color.gray,textcolor=color.white,tooltip=ttAllCandlestickPatterns)
strategy.entry("long",strategy.long,when=_tradeDirection=="bullish")
strategy.close("long",when=_tradeDirection=="bearish"or(close<openandclose<strategy.position_avg_price*(1-stopLoss))orclose>strategy.position_avg_price)
strategy.entry("short",strategy.short,when=_tradeDirection=="bearish")
strategy.close("short",when=_tradeDirection=="bullish"or(close>openandclose>strategy.position_avg_price*(1+stopLoss))orclose<strategy.position_avg_price)
Expand (713 lines)
