Script Name: All in One Strategy
Author: Solutions1978
Description: True improvement over my previous script. This script adds in all of the complementary indicators, makes it truly easy to adjust the inputs, and has produced a real world net gain using the TradingView bots paired with any broker's API that is supported.

It has a selection for which strategy you'd like to use and due to limitations in Pine I cannot program in...
PineScript code:

Pine Script™ strategy
All in One Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//@version=4
//  ██████╗██████╗  ███████╗  █████╗  ████████╗███████╗██████╗          ██████╗  ██╗      ██╗
//██╔════╝██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗        ██╔══██╗╚██╗  ██╔╝
//██║          ██████╔╝█████╗    ███████║      ██║      █████╗    ██║    ██║        ██████╔╝  ╚████╔╝
//██║          ██╔══██╗██╔══╝    ██╔══██║      ██║      ██╔══╝    ██║    ██║        ██╔══██╗    ╚██╔╝
//╚██████╗██║    ██║███████╗██║    ██║      ██║      ███████╗██████╔╝        ██████╔╝      ██║
//  ╚═════╝╚═╝    ╚═╝╚══════╝╚═╝    ╚═╝      ╚═╝      ╚══════╝╚═════╝          ╚═════╝        ╚═╝

//███████╗  ██████╗  ██╗          ██╗      ██╗████████╗██╗  ██████╗  ███╗      ██╗███████╗  ██╗  █████╗  ███████╗  █████╗
//██╔════╝██╔═══██╗██║          ██║      ██║╚══██╔══╝██║██╔═══██╗████╗    ██║██╔════╝███║██╔══██╗╚════██║██╔══██╗
//███████╗██║      ██║██║          ██║      ██║      ██║      ██║██║      ██║██╔██╗  ██║███████╗╚██║╚██████║        ██╔╝╚█████╔╝
//╚════██║██║      ██║██║          ██║      ██║      ██║      ██║██║      ██║██║╚██╗██║╚════██║  ██║  ╚═══██║      ██╔╝  ██╔══██╗
//███████║╚██████╔╝███████╗╚██████╔╝      ██║      ██║╚██████╔╝██║  ╚████║███████║  ██║  █████╔╝      ██║    ╚█████╔╝
//╚══════╝  ╚═════╝  ╚══════╝  ╚═════╝        ╚═╝      ╚═╝  ╚═════╝  ╚═╝    ╚═══╝╚══════╝  ╚═╝  ╚════╝        ╚═╝      ╚════╝

strategy(shorttitle='Ain1v4',title='All  in  One  Strategy',  overlay=true,  scale=scale.left,  initial_capital  =  1000,  process_orders_on_close=true,  default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  100,  commission_type=strategy.commission.percent,  commission_value=0.18,  calc_on_every_tick=true)
kcolor  =  color.new(#0094FF,  60)
dcolor  =  color.new(#FF6A00,  60)
//  -----------------    Strategy  Inputs  -------------------------------------------------------------
//Backtest  dates  with  auto  finish  date  of  today
start  =  input(defval  =  timestamp("22  June  2021  00:00  -0500"),  title  =  "Start  Time",  type  =  input.time)
finish  =  input(defval  =  timestamp("31  December  2021  00:00  -0600"),  title  =  "End  Time",  type  =  input.time)
window()    =>  time  >=  start  and  time  <=  finish  ?  true  :  false              //  create  function  "within  window  of  time"
//  Strategy  Selection  -  Long,  Short,  or  Both
stratinfo  =  input(true,  "Long/Short  for  Mixed  Market,  Long  for  Bull,  Short  for  Bear")
strat  =  input(title="Trade  Types",  defval="Long/Short",  options=["Long  Only",  "Long/Short",  "Short  Only"])
strat_val  =  strat  ==  "Long  Only"  ?  1  :  strat  ==  "Long/Short"  ?  0  :  -1
//  Risk  Management  Inputs
sl=  input(10.0,  "Stop  Loss  %",  minval  =  0,  maxval  =  100,  step  =  0.01)
stoploss  =  sl/100
tp  =  input(20.0,  "Target  Profit  %",  minval  =  0,  maxval  =  100,  step  =  0.01)
TargetProfit  =  tp/100
ld  =  input(2,  "Stop  Trading  After  This  Many  Losing  Days",  type=input.integer,  minval=0,  maxval=100,  step=1)
strategy.risk.max_cons_loss_days(count=ld)
ml  =  input(10,  "Maximum  %  of  Equity  Lost  to  Halt  Trading",  type=input.integer,  minval=1,  maxval=100,  step=1)
strategy.risk.max_drawdown(value=ml,  type=strategy.percent_of_equity)
useXRSI  =  input(false,  "Use  RSI  crossing  back,  select  only  one  strategy")
useCRSI  =  input(false,  "Use  Tweaked  Connors  RSI,  select  only  one")
RSIInfo  =  input(true,  "These  are  the  RSI  Strategy  Inputs,  RSI  Length  applies  to  MACD,  set  OB  and  OS  to  45  for  using  Stoch  and  EMA  strategies.")
length  =  input(14,  "RSI  Length",  minval=1)
overbought=  input(62,  "Overbought")
oversold=  input(35,  "Oversold")
cl1  =  input(3,  "Connor's  MA  Length  1",  minval=1,  step=1)
cl2  =  input(20,  "Connor's  MA  Lenght  2",  minval=1,  step=1)
cl3  =  input(50,  "Connor's  MA  Lenght  3",  minval=1,  step=1)
//  MACD  and  EMA  Inputs
useMACD  =  input(false,  "Use  MACD  Only,  select  only  one  strategy")
useEMA    =  input(false,  "Use  EMA  Only,  select  only  one  strategy  (EMA  uses  Stochastic  inputs  too)")
MACDInfo=input(true,  "These  are  the  MACD  strategy  variables")
fastLength  =  input(5,  minval=1,  title="EMA  Fast  Length")
slowLength  =  input(10,  minval=1,  title="EMA  Slow  Length")
ob_min  =  input(52,  "Overbought  Lookback  Minimum  Value",  minval=0,  maxval=200)
ob_lb  =  input(25,  "Overbought  Lookback  Bars",  minval=0,  maxval=100)
os_min  =  input(50,  "Oversold  Lookback  Minimum  Value",  minval=0,  maxval=200)
os_lb  =  input(35,  "Oversold  Lookback  Bars",  minval=0,  maxval=100)
source  =  input(title="Source",  type=input.source,  defval=close)
RSI  =  rsi(source,  length)
//  Price  Movement  Inputs
PriceInfo  =  input(true,  "Price  Change  Percentage  Cross  Check  Inputs  for  all  Strategies,  added  logic  to  avoid  early  sell.  This  is  different  from  setting  of  max  loss  in  risk  management.")
lkbk  =  input(5,"Max  Lookback  Period")
//  EMA  and  SMA  Background  Inputs
useStoch        =  input(false,  "Use  Stochastic  Strategy,  choose  only  one")
StochInfo      =  input(true,  "Stochastic  Strategy  Inputs")
smoothK          =  input(3,  "K",  minval=1)
periodK          =  input(14,  "K  Period",  minval=1)
periodD          =  input(3,  "D  Period",  minval=1)
k_mode            =  input("SMA",  "K  Mode",  options=["SMA",  "EMA",  "WMA"])
high_source  =  input(high,"High  Source")
low_source=  input(low,"Low  Source")
//  Selections  to  show  or  hide  the  overlays
showZones  =  input(true,  title="Show  Bullish/Bearish  Zones")
showStoch  =  input(true,  title="Show  Stochastic  Overlays")
showRSIBS  =  input(true,  title="Show  RSI  Buy  Sell  Zones")
showMACD  =  input(true,  title="Show  MACD")
color_bars=input(true,  "Color  Bars")
//  -----------------------  Dynamic  RSI  --------------------------------------
//  Define  f_print  function  to  show  key  recommendations  for  RSI
f_print(_text)  =>
        //  Create  label  on  the  first  bar.
        var  _label  =  label(na),
        label.delete(_label),
_label:=label.new(
time+(time-time[1]),
ohlc4,
_text,
xloc.bar_time,
yloc.price,
color(na),
label.style_none,
color.gray,
size.large,
text.align_left
)


//DisplayhighestandlowestRSIvalues
AvgHigh(src,cnt,val)=>
total=0.0
count=0
fori=0tocnt
ifsrc[i]>val
count:=count+1
total:=total+src[i]
round(total/count)

RSI_high=AvgHigh(RSI,ob_lb,ob_min)
AvgLow(src,cnt,val)=>
total=0.0
count=0
fori=5tocntby5
ifsrc[i]<val
count:=count+1
total:=total+src[i]
round(total/count)
RSI_low=AvgLow(RSI,os_lb,os_min)
f_print("RecommendedRSISettings:"+"\nOverbought="+tostring(RSI_high)+"\nOversold="+tostring(RSI_low))
//PlotOversoldandOverboughtLines
over=hline(oversold,title="Oversold",color=color.green)
under=hline(overbought,title="Overbought",color=color.red)
fillcolor=color.new(#9915FF,90)
fill(over,under,fillcolor,title="BandBackground")
//------------------BackgroundColorsbasedonEMAIndicators-----------------------------------
rsi_ema=ema(RSI,length)
emaA=ema(rsi_ema,fastLength)
emaFast=2*emaA-ema(emaA,fastLength)
emaB=ema(rsi_ema,slowLength)
emaSlow=2*emaB-ema(emaB,slowLength)
//NewBullishandBearishSignalRulelogiccheck
out=ema(RSI,length)
//bullishsignalrule:
bullishRule=emaFast>emaSlowandout>=out[1]
//bearishsignalrule:
bearishRule=emaFast<emaSlowandout<=out[1]
EMAShortSell=crossunder(rsi_ema,emaFast)andcrossunder(rsi_ema,emaSlow)andbearishRuleandwindow()
EMAShortBuy=crossover(rsi_ema,emaFast)andcrossover(rsi_ema,emaSlow)andbullishRuleandwindow()
EMALongBuy=crossover(rsi_ema,emaSlow)andcrossover(rsi_ema,emaFast)andbullishRuleandwindow()
EMALongSell=crossunder(emaFast,emaSlow)andbearishRuleandwindow()
//currenttradingState
ruleState=0
ruleState:=bullishRule?1:bearishRule?-1:nz(ruleState[1])
ruleColor=ruleState==1?color.new(color.blue,90):ruleState==-1?color.new(color.red,90):ruleState==0?color.new(color.gray,90):na
bgcolor(showZones?ruleColor:na,title="Bullish/BearishZones")
//------------------PricePercentageChangeCalculation---------------------------------------
perc_change(lkbk)=>
overall_change=((close[0]-open[lkbk])/open[lkbk])*100
highest_high=0.0
lowest_low=0.0
fori=lkbkto0
highest_high:=i==lkbk?high:high[i]>high[(i+1)]?high[i]:highest_high[1]
lowest_low:=i==lkbk?low:low[i]<low[(i+1)]?low[i]:lowest_low[1]

start_to_high=((highest_high-open[lkbk])/open[lkbk])*100
start_to_low=((lowest_low-open[lkbk])/open[lkbk])*100
previous_to_high=((highest_high-open[1])/open[1])*100
previous_to_low=((lowest_low-open[1])/open[1])*100
previous_bar=((close[1]-open[1])/open[1])*100

[overall_change,start_to_high,start_to_low,previous_to_high,previous_to_low,previous_bar]

//Callthefunction
[overall,to_high,to_low,last_high,last_low,last_bar]=perc_change(lkbk)
//Plotthefunction
//plot(overall*50,color=color.white,title='OverallPercentageChange',linewidth=3)
//plot(to_high*50,color=color.green,title='PercentageChangefromStarttoHigh',linewidth=2)
//plot(to_low*50,color=color.red,title='PercentageChangefromStarttoLow',linewidth=2)
//plot(last_high*100,color=color.teal,title="PrevioustoHigh",linewidth=2)
//plot(last_low*100,color=color.maroon,title="PrevioustoClose",linewidth=2)
//plot(last_bar*100,color=color.orange,title="PreviousBar",linewidth=2)
//hline(0,title='CenterLine',color=color.orange,linewidth=2)
true_dip=overall<0andto_high>0andto_low<0andlast_high>0andlast_low<0andlast_bar<0
true_peak=overall>0andto_high>0andto_low>0andlast_high>0andlast_low<0andlast_bar>0
//------------------StochasticIndicatorOverlay-----------------------------------------------
//Calculation
//Usehighesthighsandlowestlows
h_high=highest(high_source,lkbk)
l_low=lowest(low_source,lkbk)
stoch=stoch(close,high_source,low_source,periodK)
k=
k_mode=="EMA"?ema(stoch,smoothK):
k_mode=="WMA"?wma(stoch,smoothK):
sma(stoch,smoothK)
d=sma(k,periodD)
k_c=change(k)
d_c=change(d)
kd=k-d
//Plot
signalColor=k>oversoldandd<overboughtandk>dandk_c>0andd_c>0?kcolor:
k<overboughtandd>oversoldandk<dandk_c<0andd_c<0?dcolor:na
kp=plot(showStoch?k:na,"K",color=kcolor)
dp=plot(showStoch?d:na,"D",color=dcolor)
fill(kp,dp,color=signalColor,title="K-D")
signalUp=showStoch?notna(signalColor)andkd>0:na
signalDown=showStoch?notna(signalColor)andkd<0:na
//plot(signalUp?kd:na,"SignalUp",color=kcolor,transp=90,style=plot.style_columns)
//plot(signalDown?(kd+100):na,"SignalDown",color=dcolor,transp=90,style=plot.style_columns,histbase=100)
StochBuy=crossover(k,d)andk_c>0andd_c>0andk<RSIandd<RSIandwindow()
StochSell=crossunder(k,d)andk_c<0andd_c<0andk<RSIandd<RSIandwindow()
//--------------AddPriceMovementtoStrategyforbettervisualization-------------------------
//Calculations
h1=vwma(high,length)
l1=vwma(low,length)
hp=h_high[1]
lp=l_low[1]
//Plot
varplot_color=#353535
varsig=0
if(h1>hp)
sig:=1
plot_color:=color.lime
elseif(l1<lp)
sig:=-1
plot_color:=color.maroon
//plot(1,title="PriceMovementBars",style=plot.style_columns,color=plot_color)
//plot(sig,title="Signal1or-1",display=display.none)
//---------------------------------------RSIPlot----------------------------------------------
//ShowRSIandEMAcrosseswitharrowsandRSIColor(tweakedConnorsRSI)
//ImprovesstrategysettingeasebyshowingwhereEMA5crossesEMA10fromabovetoconfirmoverboughtconditionsortrendreversals
//Thisshowswhereyoushouldentershortsorexitlongs
//TweakedConnorsRSICalculation
connor_ob=overbought
connor_os=oversold
ma1=sma(close,cl1)
ma2=sma(close,cl2)
ma3=sma(close,cl3)
//BuySellZonesusingtweakedConnorsRSI(RSIvaluesof80and20forCryptoaswellasma3,ma20,andma50arethetweaks)
RSI_SELL=ma1>ma2andopen>ma3andRSI>=connor_obandtrue_peakandwindow()
RSI_BUY=ma2<ma3andma3>closeandRSI<=connor_osandtrue_dipandwindow()
//ColorDefinition
col=useCRSI?(close>ma2andclose<ma3andRSI<=connor_os?color.lime:close<ma2andclose>ma3andRSI<=connor_ob?color.red:color.yellow):color.yellow
//PlotcoloredRSILine
plot(RSI,title="RSI",linewidth=3,color=col)
//-------------------MACDStrategy-------------------------------------------------
[macdLine,signalLine,_]=macd(close,fastLength,slowLength,length)
bartrendcolor=macdLine>signalLineandk>50andRSI>50?color.teal:macdLine<signalLineandk<50andRSI<50?color.maroon:macdLine<signalLine?color.yellow:color.gray
barcolor(color=color_bars?bartrendcolor:na)
MACDBuy=macdLine>signalLineandRSI<RSI_lowandoverall<0andwindow()
MACDSell=macdLine<signalLineandRSI>RSI_highandoverall>0andwindow()
//plotshape(showMACD?MACDBuy:na,title="MACDBuy",style=shape.arrowup,text="MACDBuy",color=color.green,textcolor=color.green,size=size.small)
//plotshape(showMACD?MACDSell:na,title="MACDSell",style=shape.arrowdown,text="MACDSell",color=color.red,textcolor=color.red,size=size.small)
MACColor=MACDBuy?color.new(color.teal,50):MACDSell?color.new(color.maroon,50):na
bgcolor(showMACD?MACColor:na,title="MACDSignals")
//--------------------------------EntryandExitLogic------------------------------------
//EntryLogic
XRSI_OB=crossunder(RSI,overbought)andoverall<0andwindow()
RSI_OB=RSI>overboughtandtrue_peakandwindow()
XRSI_OS=crossover(RSI,oversold)andoverall>0andwindow()
RSI_OS=RSI<oversoldandtrue_dipandwindow()
//StrategyEntryandExitwithbuiltinRiskManagement
if(strategy.opentrades==0andstrat_val>-1)
OtherLong=rsi_ema>RSIandk<d
GoLong=useStoch?StochBuy:useXRSI?OtherLongandXRSI_OS:useMACD?OtherLongandMACDBuy:useCRSI?OtherLongandRSI_BUY:useEMA?EMALongBuy:RSI_OS
if(GoLong)
strategy.entry("LONG",strategy.long)
if(strategy.opentrades==0andstrat_val<1)
OtherShort=rsi_ema<RSIandd<k
GoShort=useStoch?StochSell:useXRSI?OtherShortandXRSI_OB:useMACD?OtherShortandMACDSell:useCRSI?OtherShortandRSI_SELL:useEMA?EMAShortSell:OtherShortandRSI_OB
if(GoShort)
strategy.entry("SHORT",strategy.short)
longStopPrice=strategy.position_avg_price*(1-stoploss)
longTakePrice=strategy.position_avg_price*(1+TargetProfit)
shortStopPrice=strategy.position_avg_price*(1+stoploss)
shortTakePrice=strategy.position_avg_price*(1-TargetProfit)
//plot(series=(strategy.position_size>0)?longTakePrice:na,color=color.green,style=plot.style_circles,linewidth=3,title="LongTakeProfit")
//plot(series=(strategy.position_size<0)?shortTakePrice:na,color=color.green,style=plot.style_circles,linewidth=3,title="ShortTakeProfit")
//plot(series=(strategy.position_size>0)?longStopPrice:na,color=color.red,style=plot.style_cross,linewidth=2,title="LongStopLoss")
//plot(series=(strategy.position_size<0)?shortStopPrice:na,color=color.red,style=plot.style_cross,linewidth=2,title="ShortStopLoss")
if(strategy.position_size>0)
strategy.exit(id="ExitLong",from_entry="LONG",stop=longStopPrice,limit=longTakePrice)

if(strategy.position_size<0)
strategy.exit(id="ExitShort",from_entry="SHORT",stop=shortStopPrice,limit=shortTakePrice)
StochLong2=strategy.position_size<0andstrat_val>-1
OtherLong2=strategy.position_size<0andstrat_val>-1andrsi_ema>RSIandk<d
CloseShort=useStoch?StochLong2andStochBuy:useXRSI?OtherLong2andXRSI_OS:useMACD?OtherLong2andMACDBuy:useCRSI?OtherLong2andRSI_BUY:useEMA?EMAShortBuy:RSI_OS
StochShort2=strategy.position_size>0andstrat_val<1
OtherShort2=strategy.position_size>0andstrat_val<1andrsi_ema<RSIandd<k
CloseLong=useStoch?StochShort2andStochSell:useXRSI?OtherShort2andXRSI_OB:useMACD?OtherShort2andMACDSell:useCRSI?OtherShort2andRSI_SELL:useEMA?EMALongSell:OtherShort2andRSI_OB
if(CloseLong)
strategy.close("LONG")

if(CloseShort)
strategy.close("SHORT")
Expand (363 lines)
