Script Name: All in One Strategy no RSI Label - For higher dollar crypto
Author: Solutions1978
Description: This is the All in One Strategy without the RSI suggestion label that will work well for any of the crypto currencies trading above $500 so the overlay shows up better. I am using ETH as an example on this.

Based on some comments on my previously published script that has been replaced I have added Alert Conditions to this version that can be used in other bots....
PineScript code:

Pine Script™ strategy
All in One Strategy no RSI Label - For higher dollar crypto
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//@version=4
//  ██████╗██████╗  ███████╗  █████╗  ████████╗███████╗██████╗          ██████╗  ██╗      ██╗
//██╔════╝██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗        ██╔══██╗╚██╗  ██╔╝
//██║          ██████╔╝█████╗    ███████║      ██║      █████╗    ██║    ██║        ██████╔╝  ╚████╔╝
//██║          ██╔══██╗██╔══╝    ██╔══██║      ██║      ██╔══╝    ██║    ██║        ██╔══██╗    ╚██╔╝
//╚██████╗██║    ██║███████╗██║    ██║      ██║      ███████╗██████╔╝        ██████╔╝      ██║
//  ╚═════╝╚═╝    ╚═╝╚══════╝╚═╝    ╚═╝      ╚═╝      ╚══════╝╚═════╝          ╚═════╝        ╚═╝

//███████╗  ██████╗  ██╗          ██╗      ██╗████████╗██╗  ██████╗  ███╗      ██╗███████╗  ██╗  █████╗  ███████╗  █████╗
//██╔════╝██╔═══██╗██║          ██║      ██║╚══██╔══╝██║██╔═══██╗████╗    ██║██╔════╝███║██╔══██╗╚════██║██╔══██╗
//███████╗██║      ██║██║          ██║      ██║      ██║      ██║██║      ██║██╔██╗  ██║███████╗╚██║╚██████║        ██╔╝╚█████╔╝
//╚════██║██║      ██║██║          ██║      ██║      ██║      ██║██║      ██║██║╚██╗██║╚════██║  ██║  ╚═══██║      ██╔╝  ██╔══██╗
//███████║╚██████╔╝███████╗╚██████╔╝      ██║      ██║╚██████╔╝██║  ╚████║███████║  ██║  █████╔╝      ██║    ╚█████╔╝
//╚══════╝  ╚═════╝  ╚══════╝  ╚═════╝        ╚═╝      ╚═╝  ╚═════╝  ╚═╝    ╚═══╝╚══════╝  ╚═╝  ╚════╝        ╚═╝      ╚════╝
strategy(shorttitle='Ain1  No  Label',title='All  in  One  Strategy  no  RSI  Label',  overlay=true,  scale=scale.left,  initial_capital  =  1000,  process_orders_on_close=true,  default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  100,  commission_type=strategy.commission.percent,  commission_value=0.18,  calc_on_every_tick=true)
kcolor  =  color.new(#0094FF,  60)
dcolor  =  color.new(#FF6A00,  60)
//  -----------------    Strategy  Inputs  -------------------------------------------------------------
//Backtest  dates  with  auto  finish  date  of  today
start=input(defval=timestamp("01April202100:00-0500"),title="StartTime",type=input.time)
finish=input(defval=timestamp("31December202100:00-0600"),title="EndTime",type=input.time)
window()=>time>=startandtime<=finish?true:false//createfunction"withinwindowoftime"
//StrategySelection-Long,Short,orBoth
stratinfo=input(true,"Long/ShortforMixedMarket,LongforBull,ShortforBear")
strat=input(title="TradeTypes",defval="Long/Short",options=["LongOnly","Long/Short","ShortOnly"])
strat_val=strat=="LongOnly"?1:strat=="Long/Short"?0:-1
//RiskManagementInputs
sl=input(10.0,"StopLoss%",minval=0,maxval=100,step=0.01)
stoploss=sl/100
tp=input(20.0,"TargetProfit%",minval=0,maxval=100,step=0.01)
TargetProfit=tp/100
useXRSI=input(false,"UseRSIcrossingback,selectonlyonestrategy")
useCRSI=input(false,"UseTweakedConnorsRSI,selectonlyone")
RSIInfo=input(true,"ThesearetheRSIStrategyInputs,RSILengthappliestoMACD,setOBandOSto45forusingStochandEMAstrategies.")
length=input(14,"RSILength",minval=1)
overbought=input(62,"Overbought")
oversold=input(35,"Oversold")
cl1=input(3,"Connor'sMALength1",minval=1,step=1)
cl2=input(20,"Connor'sMALenght2",minval=1,step=1)
cl3=input(50,"Connor'sMALenght3",minval=1,step=1)
//MACDandEMAInputs
useMACD=input(false,"UseMACDOnly,selectonlyonestrategy")
useEMA=input(false,"UseEMAOnly,selectonlyonestrategy(EMAusesStochasticinputstoo)")
MACDInfo=input(true,"ThesearetheMACDstrategyvariables")
fastLength=input(5,minval=1,title="EMAFastLength")
slowLength=input(10,minval=1,title="EMASlowLength")
ob_min=input(52,"OverboughtLookbackMinimumValue",minval=0,maxval=200)
ob_lb=input(25,"OverboughtLookbackBars",minval=0,maxval=100)
os_min=input(50,"OversoldLookbackMinimumValue",minval=0,maxval=200)
os_lb=input(35,"OversoldLookbackBars",minval=0,maxval=100)
source=input(title="Source",type=input.source,defval=close)
RSI=rsi(source,length)
//PriceMovementInputs
PriceInfo=input(true,"PriceChangePercentageCrossCheckInputsforallStrategies,addedlogictoavoidearlysell")
lkbk=input(5,"MaxLookbackPeriod")
//EMAandSMABackgroundInputs
useStoch=input(false,"UseStochasticStrategy,chooseonlyone")
StochInfo=input(true,"StochasticStrategyInputs")
smoothK=input(3,"K",minval=1)
smoothD=input(3,"D",minval=1)
k_mode=input("SMA","KMode",options=["SMA","EMA","WMA"])
high_source=input(high,"HighSource")
low_source=input(low,"LowSource")
HTF=input("","CurerntorHighertimeframeonly",type=input.resolution)
//Selectionstoshoworhidetheoverlays
showZones=input(true,title="ShowBullish/BearishZones")
showStoch=input(true,title="ShowStochasticOverlays")
showRSIBS=input(true,title="ShowRSIBuySellZones")
showMACD=input(true,title="ShowMACD")
color_bars=input(true,"ColorBars")
//------------------DynamicRSICalculation----------------------------------------
AvgHigh(src,cnt,val)=>
total=0.0
count=0
fori=0tocnt
ifsrc[i]>val
count:=count+1
total:=total+src[i]
round(total/count)

RSI_high=AvgHigh(RSI,ob_lb,ob_min)
AvgLow(src,cnt,val)=>
total=0.0
count=0
fori=0tocnt
ifsrc[i]<val
count:=count+1
total:=total+src[i]
round(total/count)
RSI_low=AvgLow(RSI,os_lb,os_min)
//------------------PricePercentageChangeCalculation-----------------------------------------
perc_change(lkbk)=>
overall_change=((close[0]-open[lkbk])/open[lkbk])*100
highest_high=0.0
lowest_low=0.0
fori=lkbkto0
highest_high:=i==lkbk?high:high[i]>high[(i+1)]?high[i]:highest_high[1]
lowest_low:=i==lkbk?low:low[i]<low[(i+1)]?low[i]:lowest_low[1]

start_to_high=((highest_high-open[lkbk])/open[lkbk])*100
start_to_low=((lowest_low-open[lkbk])/open[lkbk])*100
previous_to_high=((highest_high-open[1])/open[1])*100
previous_to_low=((lowest_low-open[1])/open[1])*100
previous_bar=((close[1]-open[1])/open[1])*100

[overall_change,start_to_high,start_to_low,previous_to_high,previous_to_low,previous_bar]

//Callthefunction
[overall,to_high,to_low,last_high,last_low,last_bar]=perc_change(lkbk)
//Plotthefunction
//plot(overall*50,color=color.white,title='OverallPercentageChange',linewidth=3)
//plot(to_high*50,color=color.green,title='PercentageChangefromStarttoHigh',linewidth=2)
//plot(to_low*50,color=color.red,title='PercentageChangefromStarttoLow',linewidth=2)
//plot(last_high*100,color=color.teal,title="PrevioustoHigh",linewidth=2)
//plot(last_low*100,color=color.maroon,title="PrevioustoClose",linewidth=2)
//plot(last_bar*100,color=color.orange,title="PreviousBar",linewidth=2)
//hline(0,title='CenterLine',color=color.orange,linewidth=2)
true_dip=overall<0andto_high>0andto_low<0andlast_high>0andlast_low<0andlast_bar<0
true_peak=overall>0andto_high>0andto_low>0andlast_high>0andlast_low<0andlast_bar>0
alertcondition(true_dip,title='TrueDip',message='Dip')
alertcondition(true_peak,title='TruePeak',message='Peak')
//------------------BackgroundColorsbasedonEMAIndicators-----------------------------------
//Usesstandardlengthsof9and21,ifyouwantcontroldeletetheconstantdefinitionanduncommenttheinputs
haClose(gap)=>(open[gap]+high[gap]+low[gap]+close[gap])/4
rsi_ema=rsi(haClose(0),length)
v2=ema(rsi_ema,length)
v3=2*v2-ema(v2,length)
emaA=ema(rsi_ema,fastLength)
emaFast=2*emaA-ema(emaA,fastLength)
emaB=ema(rsi_ema,slowLength)
emaSlow=2*emaB-ema(emaB,slowLength)
//plot(rsi_ema,color=color.white,title='RSIEMA',linewidth=3)
//plot(v2,color=color.green,title='v2',linewidth=2)
//plot(v3,color=color.red,title='v3',linewidth=2)
//plot(emaFast,color=color.teal,title="EMAFast",linewidth=2)
//plot(emaSlow,color=color.maroon,title="EMASlow",linewidth=2)
EMABuy=crossunder(emaFast,v2)andwindow()
EMASell=crossover(emaFast,emaSlow)andwindow()
alertcondition(EMABuy,title='EMABuy',message='EMABuyCondition')
alertcondition(EMASell,title='EMASell',message='EMASellCondition')
//bullishsignalrule:
bullishRule=emaFast>emaSlow
//bearishsignalrule:
bearishRule=emaFast<emaSlow
//currenttradingState
ruleState=0
ruleState:=bullishRule?1:bearishRule?-1:nz(ruleState[1])
ruleColor=ruleState==1?color.new(color.blue,90):ruleState==-1?color.new(color.red,90):ruleState==0?color.new(color.gray,90):na
bgcolor(showZones?ruleColor:na,title="Bullish/BearishZones")
//------------------StochasticIndicatorOverlay-----------------------------------------------
//Calculation
//Usehighesthighsandlowestlows
h_high=highest(high_source,lkbk)
l_low=lowest(low_source,lkbk)
stoch=stoch(RSI,RSI_high,RSI_low,length)
k=
k_mode=="EMA"?ema(stoch,smoothK):
k_mode=="WMA"?wma(stoch,smoothK):
sma(stoch,smoothK)
d=sma(k,smoothD)
k_c=change(k)
d_c=change(d)
kd=k-d
//Plot
signalColor=k>oversoldandd<overboughtandk>dandk_c>0andd_c>0?kcolor:
k<overboughtandd>oversoldandk<dandk_c<0andd_c<0?dcolor:na
kp=plot(showStoch?k:na,"K",color=kcolor)
dp=plot(showStoch?d:na,"D",color=dcolor)
fill(kp,dp,color=signalColor,title="K-D")
signalUp=showStoch?notna(signalColor)andkd>0:na
signalDown=showStoch?notna(signalColor)andkd<0:na
//plot(signalUp?kd:na,"SignalUp",color=kcolor,transp=90,style=plot.style_columns)
//plot(signalDown?(kd+100):na,"SignalDown",color=dcolor,transp=90,style=plot.style_columns,histbase=100)
//StochBuy=crossover(k,d)andkd>0andto_low<0andwindow()
//StochSell=crossunder(k,d)andkd<0andto_high>0andwindow()
StochBuy=crossover(k,d)andwindow()
StochSell=crossunder(k,d)andwindow()
alertcondition(StochBuy,title='StochBuy',message='KCrossingD')
alertcondition(StochSell,title='StochSell',message='DCrossingK')
//--------------AddPriceMovement-------------------------
//Calculations
h1=vwma(high,length)
l1=vwma(low,length)
hp=h_high[1]
lp=l_low[1]
//Plot
varplot_color=#353535
varsig=0
if(h1>hp)
sig:=1
plot_color:=color.lime
elseif(l1<lp)
sig:=-1
plot_color:=color.maroon
//plot(1,title="PriceMovementBars",style=plot.style_columns,color=plot_color)
//plot(sig,title="Signal1or-1",display=display.none)
//---------------------------------------RSIPlot----------------------------------------------
//PlotOversoldandOverboughtLines
over=hline(oversold,title="Oversold",color=color.green)
under=hline(overbought,title="Overbought",color=color.red)
fillcolor=color.new(#9915FF,90)
fill(over,under,fillcolor,title="BandBackground")
//ShowRSIandEMAcrosseswitharrowsandRSIColor(tweakedConnorsRSI)
//ImprovesstrategysettingeasebyshowingwhereEMA5crossesEMA10fromabovetoconfirmoverboughtconditionsortrendreversals
//Thisshowswhereyoushouldentershortsorexitlongs
//TweakedConnorsRSICalculation
connor_ob=overbought
connor_os=oversold
ma1=sma(close,cl1)
ma2=sma(close,cl2)
ma3=sma(close,cl3)
//BuySellZonesusingtweakedConnorsRSI(RSIvaluesof80and20forCryptoaswellasma3,ma20,andma50arethetweaks)
RSI_SELL=ma1>ma2andopen>ma3andRSI>=connor_obandtrue_peakandwindow()
RSI_BUY=ma2<ma3andma3>closeandRSI<=connor_osandtrue_dipandwindow()
alertcondition(RSI_BUY,title='ConnorsBuy',message='ConnorsRSIBuy')
alertcondition(RSI_SELL,title='ConnorsSell',message='ConnorsRSISell')
//ColorDefinition
col=useCRSI?(close>ma2andclose<ma3andRSI<=connor_os?color.lime:close<ma2andclose>ma3andRSI<=connor_ob?color.red:color.yellow):color.yellow
//PlotcoloredRSILine
plot(RSI,title="RSI",linewidth=3,color=col)
//-------------------MACDStrategy-------------------------------------------------
[macdLine,signalLine,_]=macd(close,fastLength,slowLength,length)
bartrendcolor=macdLine>signalLineandk>50andRSI>50?color.teal:macdLine<signalLineandk<50andRSI<50?color.maroon:macdLine<signalLine?color.yellow:color.gray
barcolor(color=color_bars?bartrendcolor:na)
MACDBuy=macdLine>signalLineandRSI<RSI_lowandoverall<0andwindow()
MACDSell=macdLine<signalLineandRSI>RSI_highandoverall>0andwindow()
//plotshape(showMACD?MACDBuy:na,title="MACDBuy",style=shape.arrowup,text="MACDBuy",color=color.green,textcolor=color.green,size=size.small)
//plotshape(showMACD?MACDSell:na,title="MACDSell",style=shape.arrowdown,text="MACDSell",color=color.red,textcolor=color.red,size=size.small)
MACColor=MACDBuy?color.new(color.teal,50):MACDSell?color.new(color.maroon,50):na
bgcolor(showMACD?MACColor:na,title="MACDSignals")
//--------------------------------EntryandExitLogic------------------------------------
//EntryLogic
XRSI_OB=crossunder(RSI,overbought)andoverall<0andwindow()
RSI_OB=RSI>overboughtandtrue_peakandwindow()
XRSI_OS=crossover(RSI,oversold)andoverall>0andwindow()
RSI_OS=RSI<oversoldandtrue_dipandwindow()
alertcondition(XRSI_OB,title='ReverseRSISell',message='RSICrossingbackunderOB')
alertcondition(XRSI_OS,title='ReverseRSIBuy',message='RSICrossingbackoverOS')
alertcondition(RSI_OS,title='RSIBuy',message='RSICrossoverOS')
alertcondition(RSI_SELL,title='RSISell',message='RSICrossunderOB')
//StrategyEntryandExitwithbuiltinRiskManagement
GoLong=strategy.position_size==0andstrat_val>-1andrsi_ema>RSIandk<d?(useXRSI?XRSI_OS:useMACD?MACDBuy:useCRSI?RSI_BUY:useStoch?StochBuy:RSI_OS):false
GoShort=strategy.position_size==0andstrat_val<1andrsi_ema<RSIandd<k?(useXRSI?XRSI_OB:useMACD?MACDSell:useCRSI?RSI_SELL:useStoch?StochSell:RSI_OB):false
if(GoLong)
strategy.entry("LONG",strategy.long)
if(GoShort)
strategy.entry("SHORT",strategy.short)
longStopPrice=strategy.position_avg_price*(1-stoploss)
longTakePrice=strategy.position_avg_price*(1+TargetProfit)
shortStopPrice=strategy.position_avg_price*(1+stoploss)
shortTakePrice=strategy.position_avg_price*(1-TargetProfit)
//plot(series=(strategy.position_size>0)?longTakePrice:na,color=color.green,style=plot.style_circles,linewidth=3,title="LongTakeProfit")
//plot(series=(strategy.position_size<0)?shortTakePrice:na,color=color.green,style=plot.style_circles,linewidth=3,title="ShortTakeProfit")
//plot(series=(strategy.position_size>0)?longStopPrice:na,color=color.red,style=plot.style_cross,linewidth=2,title="LongStopLoss")
//plot(series=(strategy.position_size<0)?shortStopPrice:na,color=color.red,style=plot.style_cross,linewidth=2,title="ShortStopLoss")
if(strategy.position_size>0)
strategy.exit(id="ExitLong",from_entry="LONG",stop=longStopPrice,limit=longTakePrice)

if(strategy.position_size<0)
strategy.exit(id="ExitShort",from_entry="SHORT",stop=shortStopPrice,limit=shortTakePrice)
CloseLong=strat_val>-1andstrategy.position_size>0andrsi_ema>RSIandd>k?(useXRSI?XRSI_OB:useMACD?MACDSell:useCRSI?RSI_SELL:RSI_OB):false
if(CloseLong)
strategy.close("LONG")

CloseShort=strat_val<1andstrategy.position_size<0andrsi_ema<RSIandk>d?(useXRSI?XRSI_OS:useMACD?MACDBuy:useCRSI?RSI_BUY:RSI_OS):false
if(CloseShort)
strategy.close("SHORT")
Expand (355 lines)
