Script Name: Atrend by OTS
Author: prim722
Description: Atrend is a indiactor used to identify long and short term trends it uses MACD, RSI, ATR, and a DEMA along with some pieces from supertrend, the indicator works good on 1-4 hour time frame
PineScript code:

Pine Script™ strategy
Atrend by OTS
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  prim722
//  ©  OTS  Music
//@version=4
strategy("Atrend  by  OTS",  overlay=true)
fastLength  =  input(12)
slowlength  =  input(26)
MACDLength  =  input(9)
MACD  =  ema(close,  fastLength)  -  ema(close,  slowlength)
aMACD  =  ema(MACD,  MACDLength)
delta  =  MACD  -  aMACD
if  (crossover(delta,  0))
        strategy.entry("MACD  buy",  strategy.long,  comment="MACD  buy")
if  (crossunder(delta,  0))
        strategy.entry("MACD  sell",  strategy.short,  comment="MACD  sell")
//plot(strategy.equity,  title="equity",  color=color.red,  linewidth=2,  style=plot.style_areabr)
length  =  input(  18  )
overSold  =  input(  30  )
overBought  =  input(  70  )
price  =  close
vrsi  =  rsi(price,  length)
co  =  crossover(vrsi,  overSold)
cu  =  crossunder(vrsi,  overBought)
if  (not  na(vrsi))
        if  (co)
                strategy.entry("RSI  buy",  strategy.long,  comment="RSI  buy")
        if  (cu)
                strategy.entry("RSI  sell",  strategy.short,  comment="RSI  sell")
//plot(strategy.equity,  title="equity",  color=color.red,  linewidth=2,  style=plot.style_areabr)
Periods  =  input(title="ATR  Period",  type=input.integer,  defval=10)
src  =  input(hl2,  title="Source")
Multiplier  =  input(title="ATR  Multiplier",  type=input.float,  step=0.1,  defval=3.0)
changeATR=  input(title="Change  ATR  Calculation  Method  ?",type=input.bool,defval=true)
showsignals=input(title="ShowBuy/SellSignals?",type=input.bool,defval=false)
highlighting=input(title="HighlighterOn/Off?",type=input.bool,defval=false)
atr2=sma(tr,Periods)
atr=changeATR?atr(Periods):atr2
up=src-(Multiplier*atr)
up1=nz(up[1],up)
up:=close[1]>up1?max(up,up1):up
dn=src+(Multiplier*atr)
dn1=nz(dn[1],dn)
dn:=close[1]<dn1?min(dn,dn1):dn
trend=1
trend:=nz(trend[1],trend)
trend:=trend==-1andclose>dn1?1:trend==1andclose<up1?-1:trend
upPlot=plot(trend==1?up:na,title="UpTrend",style=plot.style_line,linewidth=2,color=color.white)
buySignal=trend==1andtrend[1]==-1
plotshape(buySignal?up:na,title="UpTrendBegins",location=location.absolute,style=shape.circle,size=size.tiny,color=color.green,transp=0)
plotshape(buySignalandshowsignals?up:na,title="",text="",location=location.absolute,style=shape.labelup,size=size.tiny,color=color.white,textcolor=color.white,transp=0)
dnPlot=plot(trend==1?na:dn,title="DownTrend",style=plot.style_line,linewidth=2,color=color.gray)
sellSignal=trend==-1andtrend[1]==1
plotshape(sellSignal?dn:na,title="DownTrendBegins",location=location.absolute,style=shape.circle,size=size.tiny,color=color.red,transp=0)
plotshape(sellSignalandshowsignals?dn:na,title="",text="",location=location.absolute,style=shape.labeldown,size=size.tiny,color=color.red,textcolor=color.white,transp=0)
mPlot=plot(ohlc4,title="",style=plot.style_circles,linewidth=0)
longFillColor=highlighting?(trend==1?color.white:color.white):color.white
shortFillColor=highlighting?(trend==-1?color.gray:color.white):color.white
fill(mPlot,upPlot,title="UpTrendHighligter",color=longFillColor)
fill(mPlot,dnPlot,title="DownTrendHighligter",color=shortFillColor)
alertcondition(buySignal,title="ATrendBuy",message="ATrendBuy!")
alertcondition(sellSignal,title="ATrendSell",message="ATrendSell!")
changeCond=trend!=trend[1]
alertcondition(changeCond,title="ATrendDirectionChange",message="ATrendhaschangeddirection!")
length1=input(25,minval=1)
srcb=input(close,title="Source")
e1=ema(srcb,length1)
e2=ema(e1,length)
dema=2*e1-e2
plot(dema,"DEMA",color.red)
Expand (74 lines)
