Script Name: BB+K strategy
Author: wsk719
Description: Applying Bollinger Bands and K-bar strategies
Suitable for long time periods
Suitable for forex trading, when the forex deviation is too large, the Fed will intervene and thus correct

Strategy: Enter when the price hits the upper or lower BB track and there is a reversal of the strong signal, and exit when it hits the other track and there is a reversal signal.
PineScript code:

Pine Script™ strategy
BB+K strategy
//@version=4
strategy("BB策略",  overlay=true,pyramiding  =  100)
length  =  input(20,  minval=1)
src  =  input(close,  title="Source")
mult  =  input(2.0,  minval=0.001,  maxval=50,  title="StdDev")
basis  =  sma(src,  length)
dev  =  mult  *  stdev(src,  length)
upper  =  basis  +  dev
lower  =  basis  -  dev
offset  =  input(0,  "Offset",  type  =  input.integer,  minval  =  -500,  maxval  =  500)
plot(basis,  "Basis",  color=#872323,  offset  =  offset)
p1  =  plot(upper,  "Upper",  color=color.teal,  offset  =  offset)
p2  =  plot(lower,  "Lower",  color=color.teal,  offset  =  offset)
fill(p1,  p2,  title  =  "Background",  color=#198787,  transp=95)
diff=upper-lower
//plot(upper*0.9985,  "Upper",  color=color.white,  offset  =  offset)
//plot(lower*1.0015,  "Lower",  color=color.white,  offset  =  offset)
//Engulfing  Candles
openBarPrevious  =  open[1]
closeBarPrevious  =  close[1]
openBarCurrent  =  open
closeBarCurrent  =  close
//If  current  bar  open  is  less  than  equal  to  the  previous  bar  close  AND  current  bar  open  is  less  than  previous  bar  open  AND  current  bar  close  is  greater  than  previous  bar  open  THEN  True
bullishEngulfing  =  openBarCurrent  <=  closeBarPrevious  and  openBarCurrent  <  openBarPrevious  and
      closeBarCurrent  >  openBarPrevious
//If  current  bar  open  is  greater  than  equaltopreviousbarcloseANDcurrentbaropenisgreaterthanpreviousbaropenANDcurrentbarcloseislessthanpreviousbaropenTHENTrue
bearishEngulfing=openBarCurrent>=closeBarPreviousandopenBarCurrent>openBarPreviousand
closeBarCurrent<openBarPrevious
//bullishEngulfing/bearishEngulfingreturnavalueof1or0;if1thenplotonchart,if0thendon'tplot
//plotshape(bullishEngulfing,style=shape.triangleup,location=location.belowbar,color=color.green,size=size.tiny)
//plotshape(bearishEngulfing,style=shape.triangledown,location=location.abovebar,color=color.red,size=size.tiny)
//alertcondition(bullishEngulfing,title="BullishEngulfing",message="[CurrencyPair][TimeFrame],Bullishcandleengulfingpreviouscandle")
//alertcondition(bearishEngulfing,title="BearishEngulfing",message="[CurrencyPair][TimeFrame],Bearishcandleengulfingpreviouscandle")
//LongUpperShadow-Bearish
C_Len=14//emadepthforbodyAvg
C_ShadowPercent=5.0//sizeofshadows
C_ShadowEqualsPercent=100.0
C_DojiBodyPercent=5.0
C_Factor=2.0//showsthenumberoftimestheshadowdominatesthecandlestickbody
C_BodyHi=max(close,open)
C_BodyLo=min(close,open)
C_Body=C_BodyHi-C_BodyLo
C_BodyAvg=ema(C_Body,C_Len)
C_SmallBody=C_Body<C_BodyAvg
C_LongBody=C_Body>C_BodyAvg
C_UpShadow=high-C_BodyHi
C_DnShadow=C_BodyLo-low
C_HasUpShadow=C_UpShadow>C_ShadowPercent/100*C_Body
C_HasDnShadow=C_DnShadow>C_ShadowPercent/100*C_Body
C_WhiteBody=open<close
C_BlackBody=open>close
C_Range=high-low
C_IsInsideBar=C_BodyHi[1]>C_BodyHiandC_BodyLo[1]<C_BodyLo
C_BodyMiddle=C_Body/2+C_BodyLo
C_ShadowEquals=C_UpShadow==C_DnShadowor(abs(C_UpShadow-C_DnShadow)/C_DnShadow*100)<C_ShadowEqualsPercentand(abs(C_DnShadow-C_UpShadow)/C_UpShadow*100)<C_ShadowEqualsPercent
C_IsDojiBody=C_Range>0andC_Body<=C_Range*C_DojiBodyPercent/100
C_Doji=C_IsDojiBodyandC_ShadowEquals
patternLabelPosLow=low-(atr(30)*0.6)
patternLabelPosHigh=high+(atr(30)*0.6)
C_LongUpperShadowBearishNumberOfCandles=1
C_LongShadowPercent=75.0
C_LongUpperShadowBearish=C_UpShadow>C_Range/100*C_LongShadowPercent
//alertcondition(C_LongUpperShadowBearish,title="LongUpperShadow",message="NewLongUpperShadow-Bearishpatterndetected.")
//ifC_LongUpperShadowBearish
//varttBearishLongUpperShadow="LongUpperShadow\nToindicatebuyerdominationofthefirstpartofasession,candlestickswillpresentwithlonguppershadows,aswellasshortlowershadows,consequentlyraisingbiddingprices."
//label.new(bar_index,patternLabelPosHigh,text="LUS",style=label.style_label_down,color=color.red,textcolor=color.white,tooltip=ttBearishLongUpperShadow)
//gcolor(highest(C_LongUpperShadowBearish?1:0,C_LongUpperShadowBearishNumberOfCandles)!=0?color.red:na,offset=-(C_LongUpperShadowBearishNumberOfCandles-1))
C_Len1=14//emadepthforbodyAvg
C_ShadowPercent1=5.0//sizeofshadows
C_ShadowEqualsPercent1=100.0
C_DojiBodyPercent1=5.0
C_Factor1=2.0//showsthenumberoftimestheshadowdominatesthecandlestickbody
C_BodyHi1=max(close,open)
C_BodyLo1=min(close,open)
C_Body1=C_BodyHi1-C_BodyLo1
C_BodyAvg1=ema(C_Body1,C_Len1)
C_SmallBody1=C_Body1<C_BodyAvg1
C_LongBody1=C_Body1>C_BodyAvg1
C_UpShadow1=high-C_BodyHi1
C_DnShadow1=C_BodyLo1-low
C_HasUpShadow1=C_UpShadow1>C_ShadowPercent1/100*C_Body1
C_HasDnShadow1=C_DnShadow1>C_ShadowPercent1/100*C_Body1
C_WhiteBody1=open<close
C_BlackBody1=open>close
C_Range1=high-low
C_IsInsideBar1=C_BodyHi1[1]>C_BodyHi1andC_BodyLo1[1]<C_BodyLo1
C_BodyMiddle1=C_Body1/2+C_BodyLo1
C_ShadowEquals1=C_UpShadow1==C_DnShadow1or(abs(C_UpShadow1-C_DnShadow1)/C_DnShadow1*100)<C_ShadowEqualsPercent1and(abs(C_DnShadow1-C_UpShadow1)/C_UpShadow1*100)<C_ShadowEqualsPercent1
C_IsDojiBody1=C_Range1>0andC_Body1<=C_Range1*C_DojiBodyPercent1/100
C_Doji1=C_IsDojiBody1andC_ShadowEquals1
patternLabelPosLow1=low-(atr(30)*0.6)
patternLabelPosHigh1=high+(atr(30)*0.6)
C_LongLowerShadowBullishNumberOfCandles1=1
C_LongLowerShadowPercent1=75.0
C_LongLowerShadowBullish1=C_DnShadow1>C_Range1/100*C_LongLowerShadowPercent1
//alertcondition1(C_LongLowerShadowBullish1,title="LongLowerShadow",message="NewLongLowerShadow-Bullishpatterndetected.")
//Makeinputoptionsthatconfigurebacktestdaterange
startDate=input(title="StartDate",type=input.integer,
defval=1,minval=1,maxval=31)
startMonth=input(title="StartMonth",type=input.integer,
defval=1,minval=1,maxval=12)
startYear=input(title="StartYear",type=input.integer,
defval=2018,minval=1800,maxval=2100)
endDate=input(title="EndDate",type=input.integer,
defval=1,minval=1,maxval=31)
endMonth=input(title="EndMonth",type=input.integer,
defval=11,minval=1,maxval=12)
endYear=input(title="EndYear",type=input.integer,
defval=2030,minval=1800,maxval=2100)
//Lookiftheclosetimeofthecurrentbar
//fallsinsidethedaterange
inDateRange=(time>=timestamp(syminfo.timezone,startYear,
startMonth,startDate,0,0))and
(time<timestamp(syminfo.timezone,endYear,endMonth,endDate,0,0))

//多單
if((bullishEngulfingorC_LongLowerShadowBullish1)andinDateRangeandcross(low,lower))
strategy.entry("L",strategy.long,qty=1000,stop=(low[1]))
//strategy.close("L",comment="Lexit",when=cross(basis,close),qty_percent=50)
ifcrossunder(close,upper*0.9985)
strategy.close("L",comment="Lexit",qty_percent=100)
//空單
if(((bullishEngulfing==0)orC_LongUpperShadowBearish)andinDateRangeandcross(close,upper))
strategy.entry("S",strategy.short,qty=1000,stop=(high[1]))
//strategy.close("S",comment="Sexit",when=cross(basis,close),qty_percent=50)
ifcrossunder(lower*1.0015,close)
strategy.close("S",comment="Sexit",qty_percent=100)
Expand (136 lines)
