Script Name: Bollinger Pair Trade
Author: ozdemirtrading
Description: NYSE:MA-1.6*NYSE:V

Revision:        1
Author: @ozdemirtrading

Revision 2 Considerations :
 - Simplify and clean up plotting

Disclaimer: This strategy is currently working on the 5M chart. Change the length input to accommodate your needs.
For the backtesting of more than 3 months, you may need to upgrade your membership.

Description:

The general idea of the...
PineScript code:

Pine Script™ strategy
Bollinger Pair Trade
//  5M  time-frame  only  (using  20  steps  1H  bollinger  band)
//@version=4
strategy("BT-5M-1H",  overlay=true,default_qty_value=100,  initial_capital=10000)
//  Source  and  length
length  =  240  //  5M  Timeframe  -  1H  BOLLINGER  BAND  -  20*12  STEPS  FOR  5M  CHART
src  =  close
/////////////////////////////////////////////////////////////////////////////////
//  Author:  @ozdemirtrading
//  Revision:                2  (graph  update)
//  revision  bugfix:  close  interval
////////////////////////////////////////////////////////////////////////////////////
//  CHECK  MY  VIDEO  THAT  I  USE  THIS  STRATEGY:
//  Setup  &  Run  Your  Fully  Functional  PAIR  TRADING  BOT  in  Less  Than  30  MIN!
//  https://www.youtube.com/watch?v=-jfJ6g-fZpI
//My  GitHub:
//https://github.com/ozdemirozcelik
//
//PAIRS-API  repo.:
//https://github.com/ozdemirozcelik/pai...
//
//PAIRS-IBKR  repo.:
//https://github.com/ozdemirozcelik/pai...
//  Revision  3  Considerations  :
//    -  Simplify  and  clean  up  plotting
//  Disclaimer:  This  strategy  is  currently  working  on  the  5M  chart.  Change  the  length  input  to  accommodate  your  needs.
//  For  the  backtesting  of  more  than  3  months,  you  may  need  to  upgrade  your  membership.
//  Description:
//  The  general  idea  of  the  strategy  is  very  straightforward:  it  takes  positions  according  to  the  lower  and  upper  Bollinger  bands.
//  But  I  am  mainly  using  this  strategy  for  pair  trading  stocks.  Do  not  forget  that  you  will  get  better  results  if  you  trade  with  cointegrated  pairs.
//  Bollinger  band:  Moving  average  &  standard  deviation  are  calculated  based  on  20  bars  on  the  1H  chart  (approx  240  bars  on  a  5m  chart).    X-day  moving  averages  (20  days  as  default)  are  also  used  in  the  background  in  some  of  the  exit  strategy  choices.
//  You  can  define  position  entry  levels  as  the  multipliers  of  standard  deviation  (for  exp:  mult2  as  2  *  standard  deviation).
//  There  are  4  choices  for  the  exit  strategy:
//    SMA:  Exit  when  touches  simple  moving  average  (SMA)
//    SKP:  Skip  SMA  and  do  not  stop  if  moving  towards  20D  SMA,  and  exit  if  it  touches  the  other  side  of  the  band
//    SKPXDSMA:  Skip  SMA  if  moving  towards  20D  SMA,  and  exit  if  it  touches  20D  SMA
//    NoExit:  Exit  if  it  touches  the  upper  &  lower  band  only.
//  Options:
//  -  Strategy  hard  stop:  if  trade  loss  reaches  a  point  defined  as  a  percent  of  the  initial  capital.  Stop  taking  new  positions.  (not  recommended  for  pair  trade)
//  -  Loss  per  trade:  close  position  if  the  loss  is  at  a  defined  level  but  keeps  watching  for  new  positions.
//  -  Enable  expected  profit  for  trade  (expected  profit  is  calculated  as  the  distance  to  SMA)  (recommended  for  pair  trade)
//  -  Enable  VIX  threshold  for  the  following  options:  (recommended  for  volatile  periods)
//          -  Stop  trading  if  VIX  for  the  previous  day  closes  above  the  threshold
//          -  Reverse  active  trade  direction  if  VIX  for  the  previous  day  is  above  the  threshold
//          -  Take  reverse  positions  (assuming  the  Bollinger  band  is  going  to  expand)  for  all  trades
//  Backtesting:
//  Close  positions  after  a  defined  interval:  mark  this  if  you  want  the  close  the  final  trade  for  backtesting  purposes.  Unmark  it  to  get  live  signals.
//  Use  custom  interval:  Backtest  specific  time  periods.
//  Other  Options:
//  -  Use  EMA:  use  an  exponential  moving  average  for  the  calculations  instead  of  simple  moving  average
//  -  Not  against  XDSMA:  do  not  take  a  position  against  20D  SMA  (if  X  is  selected  as  20)  (recommended  for  pairs  with  a  clear  trend)
//  -  Not  in  XDSMA  1  DEV:  do  not  take  a  position  in  20D  SMA  1*standart  deviation  band  (recommended  if  you  need  to  decrease  #  of  trades  and  increase  profit  for  trade)
//  -  Not  in  XDSMA  2  DEV:  do  not  take  a  position  in  20D  SMA  2*standart  deviation  band
//  Session  management:
//  -  Not  in  session:  Session  start  and  end  times  can  be  defined  here.  If  you  do  not  want  to  trade  in  certain  time  intervals,  mark  that  session.(helps  to  reduce  slippage  and  get  more  realistic  backtest  results)
/////////////////////////////////////////////////////////////////////////////////
//  ***  Inputs  ***  //
//  Input  for  the  strategy's  maximum  drawdown  per  trade  (in  %  of  strategy  equity)
maxPercDd  =  input(title="Hard  Stop  Strategy  if  any  trade  loss  is  (%)",  type=input.integer,  defval=100,  minval=1,  maxval=100)
//  Use  the  input's  value  with  the  maximum  drawdown  function
strategy.risk.max_drawdown(value=maxPercDd,  type=strategy.percent_of_equity)
//  Stop  Loss  amount
sl_pertrade  =  input(title="Loss  per  trade($)",  type=input.integer,  defval=400,  minval=10,  maxval=5000)
//  Enable  Stop  Loss
enable_stop  =  input(title="Enable  stoplosspertrade?",type=input.bool,defval=false)
//Expectedprofitamount
expprofit_pertrade=input(title="ExpProfitpertrade($)",type=input.integer,defval=20,minval=10,maxval=10000)
//EnableExpectedProfitPerTrade
enable_expprofit=input(title="Enableexpectedprofitpertrade?",type=input.bool,defval=false)
//VIXthreshold
threshold_vix=input(30,'vixthreshold')
//EnableVIXthreshold
//StoppositionswhenVIX(dailyclose)reachesthreshold
enable_vix_stop=input(title="Enablevixthreshold?",type=input.bool,defval=false)
//Enablereversefirsttrade
//ReversepositionswhenVIX(dailyclose)reachesthreshold,exitSMA
enable_vix_reverse=input(title="Enablefirstreversetrade?",type=input.bool,defval=false)
//EnableReversetrade
//TradeagainstSMAifreversetrade
enable_vix_trade=input(title="Enableallreversetrade?",type=input.bool,defval=false)
//Exitchoice
//SMA:Exitatstandartmovingaverage(20x30mor1h)
//SKP:SkipSMAifmovingtowards20DSMA,andexitat2DEV
//SKPXDSMA:SkipSMAifmovingtowards20DSMA,andexitat20DSMA
//NoExit:Exitat2DEV
exitchoice=input(title="ExitType",defval="SMA",options=["SMA","SKP","SKPXDSMA","NOEXT"])
//SKPRef#ofdays
//Change20DSMAtoXDSMA
skprefchoice=input(title="SKPRef#ofdays",defval="20",options=["10","20","50"])
//entryexitinput
entrychoice=input(title="Entry",defval="mult2",options=["mult","mult2","mult3"])
//stddev&finetuninginputs
exit_band=input(0.0,minval=0,maxval=0.5,step=0.05)
mult=input(1.0,minval=0.001,maxval=10,step=0.1)
mult2=input(2.0,minval=0.001,maxval=10,step=0.1)
mult3=input(3.0,minval=0.001,maxval=10,step=0.1)
//BTperiod
//datechoice=input(title="BTPeriod",defval="1Y",options=["SOM","1M","3M","6M","1Y","2Y","3Y"])
datechoice=input(title="BTPeriod",defval="1Y",options=["SOM","1M","3M","6M","1Y"])
//Closeafterintervalends
closeafterinterval=input(title="Closepositionsafterinterval?",type=input.bool,defval=true)
//Usecustominterval
custominterval=input(title="Usecustominterval?",type=input.bool,defval=false)
//BTstartdate-enddate
startDay=input(title="StartDate",type=input.integer,defval=5,minval=1,maxval=31)
startMonth=input(title="StartMonth",type=input.integer,defval=2,minval=1,maxval=12)
startYear=input(title="StartYear",type=input.integer,defval=2022,minval=1800,maxval=2100)
endDay=input(title="EndDate",type=input.integer,defval=24,minval=1,maxval=31)
endMonth=input(title="EndMonth",type=input.integer,defval=5,minval=1,maxval=12)
endYear=input(title="EndYear",type=input.integer,defval=2022,minval=1800,maxval=2100)
//BooleanInputs
//isEMA:UseEMAinstedofSMA
//notagainstSMA:NonewpositionagainstSMA
//notXDSMA_1:NonewpositionsinsidexDEV
isEMA=input(title="UseEMA?",type=input.bool,defval=false)
notagainstSMA=input(title="NotagainstXDSMA?",type=input.bool,defval=false)
notXDSMA_1=input(title="NotinXDSMA1DEV?",type=input.bool,defval=false)
notXDSMA_2=input(title="NotinXDSMA2DEV?",type=input.bool,defval=false)
//sessiontimeframeinputs
timeframe_1=input(title="Notinsession1",type=input.bool,defval=true)
timeframe_2=input(title="Notinsession2",type=input.bool,defval=false)
timeframe_3=input(title="Notinsession3",type=input.bool,defval=false)
timeframe_4=input(title="Notinsession4",type=input.bool,defval=true)
session1_start=input(title="Session1_start",defval="0930",options=["0930","0935","0940","0945","0950","0955","1000","1005","1010","1015","1020","1025","1030","1035","1040","1045","1050","1055","11:00"])
session2_start=input(title="Session2_start",defval="0935",options=["0931","0932","0933","0934","0935","0940","0945","0950","0955","1000","1005","1010","1015","1020","1025","1030","1035","1040","1045","1050","1055","11:00"])
session3_start=input(title="Session3_start",defval="1200",options=["1030","1040","1050","1100","1110","1120","1130","1140","1150","1200","1210","1220","1230","1240","1250","1300"])
session4_start=input(title="Session4_start",defval="1555",options=["1200","1215","1230","1245","1300","1315","1330","1345","1400","1430","1445","1500","1515","1530","1535","1540","1545","1550","1555"])
session4_end=input(title="Session4_end",defval="1600",options=["1500","1515","1530","1535","1540","1545","1550","1555","1600"])
//***EndofInputs***//
//VIXmodifications
vix=security("CBOE:VIX",timeframe.period,close)
vix_d=security("CBOE:VIX",'1D',close)
reverse_pair=0//setinitialtrademode
if(enable_vix_stopandthreshold_vix<vix_d)
reverse_pair:=1//changetoreversetrademode
//timeframecalculationsforsessions
session1=session1_start+"-"+session2_start
session2=session2_start+"-"+session3_start
session3=session3_start+"-"+session4_start
session4=session4_start+"-"+session4_end
t1=time(timeframe.period,session1)//t=time(timeframe.period,"1130-1600:1234567")foralldays
time_cond_1=(notna(t1)andnottimeframe_1)
bgcolor(notna(t1)andtimeframe_1?color.red:na)
t2=time(timeframe.period,session2)
time_cond_2=(notna(t2)andnottimeframe_2)
bgcolor(notna(t2)andtimeframe_2?color.red:na)
t3=time(timeframe.period,session3)
time_cond_3=(notna(t3)andnottimeframe_3)
bgcolor(notna(t3)andtimeframe_3?color.red:na)
t4=time(timeframe.period,session4)
time_cond_4=(notna(t4)andnottimeframe_4)
bgcolor(notna(t4)andtimeframe_4?color.red:na)
//datecalculationsforbacktestperiod
TimeNow=timenow
YearNow=year(TimeNow)
MonthNow=month(TimeNow)
DayNow=dayofmonth(TimeNow)
Year1M=YearNow
Month1M=MonthNow
Day1M=DayNow
Year3M=YearNow
Month3M=MonthNow
Day3M=DayNow
Year6M=YearNow
Month6M=MonthNow
Day6M=DayNow
Year1Y=YearNow-1
Month1Y=MonthNow
Day1Y=DayNow
Year2Y=YearNow-2
Month2Y=MonthNow
Day2Y=DayNow
Year3Y=YearNow-3
Month3Y=MonthNow
Day3Y=DayNow
if(MonthNow<4)
Year3M:=Year3M-1
Month3M:=Month3M+9
if(MonthNow<2)
Month1M:=Month1M+11
Year1M:=Year1M-1
else
Month1M:=Month1M-1
else
Month3M:=Month3M-3
Month1M:=Month1M-1
if(MonthNow<7)
Year6M:=Year6M-1
Month6M:=Month6M+6
else
Month6M:=Month6M-6
datestart0=timestamp(syminfo.timezone,YearNow,MonthNow,1,0,0,0)
datestart1=timestamp(syminfo.timezone,Year1M,Month1M,Day1M,0,0,0)
datestart3=timestamp(syminfo.timezone,Year3M,Month3M,Day3M,0,0,0)
datestart6=timestamp(syminfo.timezone,Year6M,Month6M,Day6M,0,0,0)
datestart12=timestamp(syminfo.timezone,Year1Y,Month1Y,Day1Y,0,0,0)
datestart24=timestamp(syminfo.timezone,Year2Y,Month2Y,Day2Y,0,0,0)
datestart36=timestamp(syminfo.timezone,Year3Y,Month3Y,Day3Y,0,0,0)
startDate=(datechoice=="SOM"?datestart0:datechoice=="1M"?datestart1:datechoice=="3M"?datestart3:datechoice=="6M"?datestart6:datechoice=="1Y"?datestart12:datechoice=="2Y"?datestart24:datechoice=="3Y"?datestart36:na)
//stddevlines&plots
basis=sma(src,length)
ifisEMA
basis:=ema(src,length)
basis_low=basis-exit_band*stdev(src,length)
basis_up=basis+exit_band*stdev(src,length)
dev=mult*stdev(src,length)
upper=basis+dev
lower=basis-dev
dev2=mult2*stdev(src,length)
upper2=basis+dev2
lower2=basis-dev2
dev3=mult3*stdev(src,length)
upper3=basis+dev3
lower3=basis-dev3
//xDavgvariables
skpchoice=(skprefchoice=="10"?10:skprefchoice=="20"?20:skprefchoice=="50"?50:na)
basis_D=sma(src,skpchoice)//forxdaysSMA
ifisEMA
basis_D=ema(src,skpchoice)//forxdaysEMA
dev_D=stdev(src,skpchoice)
daysMA=security(syminfo.tickerid,'D',basis_D)
upper_D=security(syminfo.tickerid,'D',basis_D+dev_D)
lower_D=security(syminfo.tickerid,'D',basis_D-dev_D)
upper_D2=security(syminfo.tickerid,'D',basis_D+2*dev_D)
lower_D2=security(syminfo.tickerid,'D',basis_D-2*dev_D)
//enableifyouwanttoplotxDavglines
//plot(daysMA,color=color.silver,title="XDSMA",offset=0,linewidth=3)
//plot(upper_D,color=color.yellow,title="2XSTDUP",offset=0,linewidth=3)
//plot(lower_D,color=color.yellow,title="2XSTDDOWN",offset=0,linewidth=3)
//plot(upper_D2,color=color.red,title="2XSTDUP",offset=0,linewidth=3)
//plot(lower_D2,color=color.red,title="2XSTDDOWN",offset=0,linewidth=3)
//plotstddevlines
plot(basis,color=color.black)//sma
plot(basis_low,color=color.gray)//sma
plot(basis_up,color=color.gray)//sma
p1a=plot(upper,color=color.orange)
p1b=plot(lower,color=color.orange)
p2a=plot(upper2,color=color.red)
p2b=plot(lower2,color=color.red)
p3a=plot(upper3,color=color.black)
p3b=plot(lower3,color=color.black)
//specifystopconditionsandsignals
posSize=abs(strategy.position_size)
pipsExit=100*(sl_pertrade/posSize),
ifenable_stopandposSize>0
strategy.exit("longexit","le",loss=pipsExit,comment="StopLoss(-"+str.format("{0,number,#.#}",sl_pertrade)+"$)")//takeprofitorstoploss
strategy.exit("shortexit","se",loss=pipsExit,comment="StopLoss(-"+str.format("{0,number,#.#}",sl_pertrade)+"$)")//takeprofitorstoploss
//exitsignal&bandwidthmodification
exitSignal_low=cross(src,basis_low)
exitSignal_up=cross(src,basis_up)
exitSignal=(exitSignal_loworexitSignal_up)
//specifycrossoverconditionsandsignals
signallow=(entrychoice=="mult"?lower:entrychoice=="mult2"?lower2:entrychoice=="mult3"?lower3:na)
signalhigh=(entrychoice=="mult"?upper:entrychoice=="mult2"?upper2:entrychoice=="mult3"?upper3:na)
longentry=cross(src,signallow)
shortentry=cross(src,signalhigh)
longEntrySignal=longentry
shortEntrySignal=shortentry
//exitatXDSMAmodificationforSKP
exitSignal_D=cross(src,daysMA)
//checkthebacktestinterval
inDateRange=false
if(custominterval)
inDateRange:=(time>=timestamp(syminfo.timezone,startYear,startMonth,startDay,0,0))and(time<timestamp(syminfo.timezone,endYear,endMonth,endDay,0,0))
else

if(closeafterinterval)
inDateRange:=(time>=startDate)and(time<=timestamp(syminfo.timezone,YearNow,MonthNow,DayNow,0,0))
else
inDateRange:=(time>=startDate)
datecheck=(inDateRange)
//applyexpectedprofitconditions
vardef_pos_size=0.0
varexp_profit=0.0
varisProfit=true
price_dif=abs(src-basis)
if(strategy.position_size!=0)//keepgetthelatestpositionsize
def_pos_size:=abs(strategy.position_size)

exp_profit:=price_dif*def_pos_size
if(enable_expprofit)
if(strategy.closedtrades!=0)//checktheinitialpositionsize,executethefirsttrade,thereshouldbeatleastonetrade
isProfit:=exp_profit>=expprofit_pertrade

if(enable_expprofit)
if((src>signalhigh)and(strategy.position_size==0))//waituntilitisoutexpectedprofitregion
ifisProfit
shortEntrySignal:=1
else
shortEntrySignal:=0


if((src<signallow)and(strategy.position_size==0))//waituntilitisoutexpectedprofitregion
ifisProfit
longEntrySignal:=1
else
longEntrySignal:=0
//nonewpositionsforbooleanflags
if(strategy.position_size==0)
if(src<daysMA)andnotagainstSMA
shortEntrySignal:=0

if(src>daysMA)andnotagainstSMA
longEntrySignal:=0

if(src<upper_D)andnotXDSMA_1
shortEntrySignal:=0

if(src>lower_D)andnotXDSMA_1
longEntrySignal:=0

if(src<upper_D2)andnotXDSMA_2
shortEntrySignal:=0

if(src>lower_D2)andnotXDSMA_2
longEntrySignal:=0
//executetradeifconditionsaresatisfied
//timeconditionsforreversemode
//timeconditionsingeneral
time_cond_all=(time_cond_2ortime_cond_3ortime_cond_4)
if(time_cond_allanddatecheck)
if(reverse_pair)//vix_stopisselectedandthresholdconditionsaresatisfied
if(enable_vix_reverse)//reversepositionsandnonewpositionsafterclose

if(strategy.position_size!=0andexitSignal)//closeatSMAforreversemode
strategy.close_all(true,comment="CloseReverse")
elseif((strategy.position_size>0)and(src<basis))
strategy.entry("se",strategy.short,comment="EnterShort(rev_1)(vix:"+str.format("{0,number,#.#}",vix_d)+")")
elseif((strategy.position_size<0)and(src>basis))
strategy.entry("le",strategy.long,comment="EnterLong(rev_1)(vix:"+str.format("{0,number,#.#}",vix_d)+")")

elseif(enable_vix_tradeand(strategy.position_size==0))//enableifyouwanttotakenewpositionsinreversemode

if(longEntrySignal)
strategy.entry("se",strategy.short,comment="EnterShort(rev_all)(vix:"+str.format("{0,number,#.#}",vix_d)+")")

if(shortEntrySignal)
strategy.entry("le",strategy.long,comment="EnterLong(rev_all)(vix:"+str.format("{0,number,#.#}",vix_d)+")")

else

strategy.close_all(true,comment="CloseVIX")

//ifnotreversemode
else
if(longEntrySignal)
//NONEWPOSITIONSAGAINSTXDSMAIFSELECTED
if(notagainstSMAand(strategy.position_size<=0)and(src>daysMA))
strategy.close_all(true,comment="NotAgainstXDSMA")
elseifisProfit
strategy.entry("le",strategy.long,comment="EnterLong(exp_profit:"+str.format("{0,number,#.#}",exp_profit)+"$)")

if(shortEntrySignal)
//NONEWPOSITIONSAGAINSTXDSMAIFSELECTED
if(notagainstSMAand(strategy.position_size>0)and(src<daysMA))
strategy.close_all(true,comment="NotAgainstXDSMA")
elseifisProfit
strategy.entry("se",strategy.short,comment="EnterShort(exp_profit:"+str.format("{0,number,#.#}",exp_profit)+"$)")

//exitconditions
isLong=(strategy.position_size>0)
isShort=(strategy.position_size<0)
isFlat=(strategy.position_size==0)
exittype=(exitchoice=="SKPXDSMA"?2:exitchoice=="SKP"?1:exitchoice=="SMA"?0:exitchoice=="NOEXT"?-1:na)
isSKPXDSMA=(exittype>1)
isSKP=(exittype==1)
isSMA=(exittype==0)
isNOEXT=(exittype<0)
if(datecheckandtime_cond_allandexitSignal)
if(isSMA)
strategy.close_all(true,comment="CloseSMA")


if(isSKPandisLongand(basis>daysMA))
strategy.close_all(true,comment="CloseSKP")


if(isSKPandisShortand(basis<daysMA))
strategy.close_all(true,comment="CloseSKP")


if(isSKPXDSMAandexitSignal_DandisLongand(basis>daysMA))
strategy.close_all(true,comment="CloseXDSMA")


if(isSKPXDSMAandexitSignal_DandisShortand(basis<daysMA))
strategy.close_all(true,comment="CloseXDSMA")


//exitopenmarketpositionwhendaterangeends
if(closeafterintervalandnotdatecheck)
strategy.close_all(true,comment="IntervalEnd")

Expand (539 lines)
