Script Name: Bollinger Bands Breakout Strategy
Author: TradeChartist
Description: Bollinger Bands Breakout Strategy  is the strategy version of  Bollinger Bands Filter  study version, which can be found under my scripts page. The strategy goes long when price closes above the upper band and goes short signal when price closes below the lower band.

Bollinger Bands is a classic indicator that uses a simple moving average of 20 periods, along...
PineScript code:

Pine Script™ strategy
Bollinger Bands Breakout Strategy
//@version=4
//┌─────  ••••  ─────┐//
//      TradeChartist    //
//└─────  ••••  ─────┘//
//Bollinger  Bands  is  a  classic  indicator  that  uses  a  simple  moving  average  of  20  periods  along  with  upper  and  lower  bands  that  are  2  standard  deviations  away  from  the  basis  line.
//These  bands  help  visualize  price  volatility  and  trend  based  on  where  the  price  is  in  relation  to  the  bands.
//This  Bollinger  Bands  filter  plots  a  long  signal  when  price  closes  above  the  upper  band  and  plots  a  short  signal  when  price  closes  below  the  lower  band.
//It  doesn't  take  into  account  any  other  parameters  such  as  Volume/RSI/fundamentals  etc,  so  user  must  use  discretion  based  on  confirmations  from  another  indicator  or  based  on  fundamentals.
//This  filter's  default  is  55  SMA  and  1  standard  deviation,  but  can  be  changed  based  on  asset  type
//It  is  definitely  worth  reading  the  22  rules  of  Bollinger  Bands  written  by  John  Bollinger.
strategy(shorttitle="BB  Breakout  Strategy",  title="Bollinger  Bands  Filter",  overlay=true,
                          pyramiding=1,  currency=currency.NONE  ,
                          initial_capital  =  100000,  default_qty_type  =  strategy.percent_of_equity,
                          default_qty_value=100)
src                  =  input(close,  title  =  "Source")
length            =  input(55,  minval=1,  title  =  "SMA  length")//  20  for  classis  Bollinger  Bands  SMA  line  (basis)
mult                =  input(1.,  minval=0.236,  maxval=2,  title="Standard  Deviation")//2  for  Classic  Bollinger  Bands  //Maxval  =  2  as  higher  the  deviation,  higher  the  risk
basis              =  sma(src,  length)
dev                  =  mult  *  stdev(src,length)
Show                =  input("Both",  options  =  ["Longs  Only",  "Shorts  Only",  "Both"],  title  =  "Trade  Type")
CC                    =  input(true,  "Color  Bars")
upper              =  basis  +  dev
lower              =  basis  -  dev
//Conditions  for  Long  and  Short  -  Extra  filter  condition  can  be  used  such  as  RSI  or  CCI  etc.
short              =  src<lower//  and  rsi(close,14)<40
long                =  src>upper//  and  rsi(close,14)>60
L1=barssince(long)
S1=barssince(short)
longSignal=L1<S1andnot(L1<S1)[1]
shortSignal=S1<L1andnot(S1<L1)[1]
//PlotsandFills
////Long/Shortshapeswithtext
//plotshape(S1<L1andnot(S1<L1)[1]?close:na,text="sᴇʟʟ",textcolor=#ff0100,color=#ff0100,style=shape.triangledown,size=size.small,location=location.abovebar,transp=0,title="SELL",editable=true)
//plotshape(L1<S1andnot(L1<S1)[1]?close:na,text="ʙᴜʏ",textcolor=#008000,color=#008000,style=shape.triangleup,size=size.small,location=location.belowbar,transp=0,title="BUY",editable=true)
//plotshape(shortSignal?close:na,color=#ff0100,style=shape.triangledown,size=size.small,location=location.abovebar,transp=0,title="ShortSignal",editable=true)
//plotshape(longSignal?close:na,color=#008000,style=shape.triangleup,size=size.small,location=location.belowbar,transp=0,title="LongSignal",editable=true)
p1=plot(upper,color=#ff0000,display=display.all,transp=75,title="UpperBand")
p2=plot(lower,color=#008000,display=display.all,transp=75,title="LowerBand")
p=plot(basis,color=L1<S1?#008000:S1<L1?#ff0000:na,linewidth=2,editable=false,title="Basis")
fill(p,p1,color=color.teal,transp=85,title="TopFill")//fillforbasis-upper
fill(p,p2,color=color.orange,transp=85,title="BottomFill")//fillforbasis-lower
//Barcolor
bcol=src>upper?color.new(#8ceb07,0):
src<lower?color.new(#ff0000,0):
src>basis?color.green:
src<basis?color.red:na
barcolor(CC?bcol:na,editable=false,title="ColorBars")
////Alerts----//Use'Onceperbarclose'
//alertcondition(condition=longSignal,title="Long-BBFilter",message='BBFilterLong@{{close}}')//Use'Onceperbarclose'
//alertcondition(condition=shortSignal,title="Short-BBFilter",message='BBFilterShort@{{close}}')//Use'Onceperbarclose'
Notestart1=input(true,"╔═══TimeRangetoBackTest═══╗")
//===INPUTBACKTESTRANGE===
FromMonth=input(defval=1,title="FromMonth",minval=1,maxval=12)
FromDay=input(defval=1,title="FromDay",minval=1,maxval=31)
FromYear=input(defval=2018,title="FromYear",minval=2015)
ToMonth=input(defval=1,title="ToMonth",minval=1,maxval=12)
ToDay=input(defval=1,title="ToDay",minval=1,maxval=31)
ToYear=input(defval=9999,title="ToYear",minval=2010)
//===FUNCTIONEXAMPLE===
start=timestamp(FromYear,FromMonth,FromDay,00,00)//backteststartwindow
finish=timestamp(ToYear,ToMonth,ToDay,23,59)//backtestfinishwindow
window()=>
time>=startandtime<=finish?true:false
if(window()and(Show=="LongsOnly"orShow=="Both"))
strategy.entry("Long",long=true,when=longSignal)
strategy.close("Long",when=shortSignal,comment="CloseLong")
if(window()and(Show=="ShortsOnly"orShow=="Both"))
strategy.entry("Short",long=false,when=shortSignal)
strategy.close("Short",when=longSignal,comment="CloseShort")
Expand (116 lines)
