Script Name: Booz Strategy
Author: ArnoldTrader_
Description: Booz Backtesting : Booz Backtesting is a method for analyzing the performance of your current trading strategy . Booz Backtesting aims to help you generate results and evaluate risk and return without risking real capital.

The Booz Backtesting is the Booz Super Swing Indicator equivalent but gives you the ability to backtest data on different charts.

This is an...
PineScript code:

Pine Script™ strategy
Booz Strategy
////////////////////////////////////////////////////////////////////////////////
//  ArnoldTrader  -  Estrategia  Booz
//  Creado  por  Arnold  para  la  Comunidad
//  Versión  1.2  -  Última  actualización:  2023-06-22
////////////////////////////////////////////////////////////////////////////////
//@timeframe=120
//  Esta  es  la  versión  de  ArnoldTrader  de  la  Estrategia  Booz,  creada  por  Arnold  para  la  Comunidad.
//  La  estrategia  utiliza  una  combinación  de  promedios  móviles  y  filtros  de  tendencia  para  identificar  posibles  operaciones.
//  También  incluye  entradas  personalizables  para  el  stop  loss,  take  profit,  apalancamiento  y  período  de  backtest.
//  ¡Feliz  trading!
//@version=4
strategy("Estrategia  Booz",  "",  true,  default_qty_type=strategy.percent_of_equity,  default_qty_value=100,  margin_long=0,  margin_short=0)
//  -----------------------------  Inputs  -------------------------------------  //
source_ma_type  =  input("EMA",  "Tipo  de  MA  Fuente",  options=["SMA",  "EMA"])
source_ma_length  =  input(50,  "Longitud  de  la  MA  Fuente")
fast_ma_length  =  input(50,  "Longitud  de  la  MA  Rápida")
slow_ma_length  =  input(100,  "Longitud  de  la  MA  Lenta")
use_trend_filter  =  input(true,  "Filtro  de  Tendencia")
trend_filter_ma_type=input("EMA","TipodeMAFiltrodeTendencia",options=["SMA","EMA"])
trend_filter_ma_length=input(200,"PeríododelaMAFiltrodeTendencia")
show_mas=input(true,"MostrarMAs")
swing_trading_mode=input(false,"MododeTradingSwing")
//--------------------------Calculations----------------------------------//
fast_ma=ema(close,fast_ma_length)
slow_ma=ema(close,slow_ma_length)
source_ma=source_ma_type=="EMA"?ema(close,source_ma_length):
sma(close,source_ma_length)
trend_filter_ma=trend_filter_ma_type=="EMA"?ema(close,trend_filter_ma_length):
sma(close,trend_filter_ma_length)
//---------------------------Conditions-----------------------------------//
uptrend=notuse_trend_filterorclose>trend_filter_ma
buy_cond=crossover(fast_ma,slow_ma)anduptrend
downtrend=notuse_trend_filterorclose<trend_filter_ma
sell_cond=crossunder(fast_ma,slow_ma)anddowntrend
//----------------------------Plotting------------------------------------//
bgcolor(use_trend_filteranddowntrend?color.red:use_trend_filter?color.green:na)
plot(show_mas?fast_ma:na,"MARápida",color.green)
plot(show_mas?slow_ma:na,"MALenta",color.red)
plot(show_mas?source_ma:na,"MAFuente",color.purple)
plot(show_mas?trend_filter_ma:na,"MAFiltrodeTendencia",color.blue)
//----------------------------Trading------------------------------------//
//Inputs
sl_perc=input(1.0,"StopLoss(en%)",group="ControldeBacktest")/100
tp_perc=input(1.0,"TakeProfit(en%)",group="ControldeBacktest")/100
leverage=input(1,"Apalancamiento",maxval=100,group="ControldeBacktest")
bt_start_time=input(timestamp("20210101"),"HoradeiniciodeBacktest",input.time,group="ControldeBacktest")
bt_end_time=input(timestamp("20291231"),"HoradefinalizacióndeBacktest",input.time,group="ControldeBacktest")
//TradingWindow
in_trading_window=time>=bt_start_timeandtime<=bt_end_time
trade_qty=(strategy.equity*leverage)/close
//LongSide
strategy.entry("Compra",strategy.long,trade_qty,when=buy_condandin_trading_window)
long_tp=strategy.position_avg_price*(1+tp_perc)
long_sl=strategy.position_avg_price*(1-sl_perc)
ifnotswing_trading_mode
strategy.exit("CierreCompra","Compra",limit=long_tp,stop=long_sl)
//ShortSide
strategy.entry("Venta",strategy.short,trade_qty,when=sell_condandin_trading_window)
short_tp=strategy.position_avg_price*(1-tp_perc)
short_sl=strategy.position_avg_price*(1+sl_perc)
ifnotswing_trading_mode
strategy.exit("CierreVenta","Venta",limit=short_tp,stop=short_sl)
Expand (76 lines)
