Script Name: BTC-USD - RSI
Author: Rawadabdo
Description: IF RSI (14) reaches 68 ... sell 1 lot size ( with TP 250 points and SL 500 points)
IF RSI (14) reaches 27 ... buy 1 lot size ( with TP 250points and SL 500 points)
IF RSI (14) reaches 80 ... sell 1 lot size ( with TP 250 points and SL 500 points)
IF RSI (14) reaches 18 ... buy 1 lot size ( with TP 250points and SL 500 points)
PineScript code:

Pine Script™ strategy
BTC/USD - RSI
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  Rawadabdo
//  Ramy's  Algorithm
//@version=5
strategy("BTC/USD  -  RSI",  overlay=false,  initial_capital  =  5000)
//  User  input
length  =  input(title  =  "Length",  defval=14,  tooltip="RSI  period")
first_buy_level  =  input(title  =  "Buy  Level  1",  defval=27,  tooltip="Level  where  1st  buy  triggers")
second_buy_level  =  input(title  =  "Buy  Level  2",  defval=18,  tooltip="Level  where  2nd  buy  triggers")
first_sell_level  =  input(title  =  "Sell  Level  1",  defval=68,  tooltip="Level  where  1st  sell  triggers")
second_sell_level  =  input(title  =  "Sell  Level  2",  defval=80,  tooltip="Level  where  2nd  sell  triggers")
takeProfit=  input(title="target  Pips",  defval=2500,  tooltip="Fixed  pip  stop  loss  distance")
stopLoss  =  input(title="Stop  Pips",  defval=5000,  tooltip="Fixedpipstoplossdistance")
lot=input(title="LotSize",defval=1,tooltip="TradingLotsize")
//GetRSI
vrsi=ta.rsi(close,length)
//EntryConditions
long1=(vrsi<=first_buy_levelandvrsi>second_buy_level)
long2=(vrsi<=second_buy_level)
short1=(vrsi>=first_sell_levelandvrsi<second_sell_level)
short2=(vrsi>=second_sell_level)
//EntryOrders
//BuyOrders
if(long1andstrategy.position_size==0)
strategy.entry("Long",strategy.long,qty=lot,comment="Buy")
if(long2andstrategy.position_size==0)
strategy.entry("Long",strategy.long,qty=lot,comment="Buy")
//ShortOrders
if(short1andstrategy.position_size==0)
strategy.entry("Short",strategy.short,qty=lot,comment="Sell")
if(short2andstrategy.position_size==0)
strategy.entry("Short",strategy.short,qty=lot,comment="Sell")

//Exitourtradeifourstoplossortakeprofitishit
strategy.exit(id="LongExit",from_entry="Long",qty=lot,profit=takeProfit,loss=stopLoss)
strategy.exit(id="ShortExit",from_entry="Short",qty=lot,profit=takeProfit,loss=stopLoss)
//plotdatatothechart
hline(first_sell_level,"OverboughtZone",color=color.red,linestyle=hline.style_dashed,linewidth=2)
hline(second_sell_level,"OverboughtZone",color=color.green,linestyle=hline.style_dashed,linewidth=2)
hline(first_buy_level,"OversoldZone",color=color.red,linestyle=hline.style_dashed,linewidth=2)
hline(second_buy_level,"OversoldZone",color=color.green,linestyle=hline.style_dashed,linewidth=2)
plot(vrsi,title="RSI",color=color.blue,linewidth=2)
Expand (60 lines)
