Script Name: Buy&Sell Bullish Engulfing - The Quant Science
Author: thequantscience
Description: 🇺🇸
 GENERAL OVERVIEW
 Buy&Sell Bullish Engulfing - The Quant Science  It is a Buy&Sell strategy based on the 'Bullish Engulfing' candlestick pattern. The main goal of the strategy is to achieve a consistent and sustainable return over time, with a manageable level of risk.

 Bullish Engulfing
The template was developed at the top of the Indicator provided by...
PineScript code:

Pine Script™ strategy
Buy&Sell Bullish Engulfing - The Quant Science
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  thequantscience
//  ██████╗  ██╗      ██╗██╗          ██╗          ██╗███████╗██╗    ██╗        ███████╗███╗      ██╗  ██████╗  ██╗      ██╗██╗          ███████╗██╗███╗      ██╗  ██████╗
//  ██╔══██╗██║      ██║██║          ██║          ██║██╔════╝██║    ██║        ██╔════╝████╗    ██║██╔════╝  ██║      ██║██║          ██╔════╝██║████╗    ██║██╔════╝
//  ██████╔╝██║      ██║██║          ██║          ██║███████╗███████║        █████╗    ██╔██╗  ██║██║    ███╗██║      ██║██║          █████╗    ██║██╔██╗  ██║██║    ███╗
//  ██╔══██╗██║      ██║██║          ██║          ██║╚════██║██╔══██║        ██╔══╝    ██║╚██╗██║██║      ██║██║      ██║██║          ██╔══╝    ██║██║╚██╗██║██║      ██║
//  ██████╔╝╚██████╔╝███████╗███████╗██║███████║██║    ██║        ███████╗██║  ╚████║╚██████╔╝╚██████╔╝███████╗██║          ██║██║  ╚████║╚██████╔╝
//  ╚═════╝    ╚═════╝  ╚══════╝╚══════╝╚═╝╚══════╝╚═╝    ╚═╝        ╚══════╝╚═╝    ╚═══╝  ╚═════╝    ╚═════╝  ╚══════╝╚═╝          ╚═╝╚═╝    ╚═══╝  ╚═════╝

//@version=5
strategy(
          "Buy&Sell  Bullish  Engulfing  -  The  Quant  Science",
          overlay  =  true,
          default_qty_type  =  strategy.percent_of_equity,
          default_qty_value  =  100,
          pyramiding  =  1,
          currency  =  currency.EUR,
          initial_capital  =  10000,
          commission_type  =  strategy.commission.percent,
          commission_value  =  0.07,
          process_orders_on_close  =  true,
          close_entries_rule  =  "ANY"
          )
startDate    =  input.int(title="D:  ",  defval=1,        minval=1,        maxval=31,      inline  =  'Start',  group  =  "START  DATE  BACKTESTING",  tooltip  =  "D  is  Day,  M  is  Month,  Y  is  Year.")
startMonth  =  input.int(title="M:  ",  defval=1,        minval=1,        maxval=12,      inline  =  'Start',  group  =  "START  DATE  BACKTESTING",  tooltip  =  "D  is  Day,  M  is  Month,  Y  is  Year.")
startYear    =  input.int(title="Y:  ",  defval=2022,  minval=1800,  maxval=2100,  inline  =  'Start',  group  =  "START  DATE  BACKTESTING",  tooltip  =  "D  is  Day,  M  is  Month,  Y  is  Year.")
endDate        =  input.int(title="D:  ",  defval=31,    minval=1,maxval=31,inline='End',group="ENDDATEBACKTESTING",tooltip="DisDay,MisMonth,YisYear.")
endMonth=input.int(title="M:",defval=12,minval=1,maxval=12,inline='End',group="ENDDATEBACKTESTING",tooltip="DisDay,MisMonth,YisYear.")
endYear=input.int(title="Y:",defval=2023,minval=1800,maxval=2100,inline='End',group="ENDDATEBACKTESTING",tooltip="DisDay,MisMonth,YisYear.")
inDateRange=(time>=timestamp(syminfo.timezone,startYear,startMonth,startDate,0,0))and(time<timestamp(syminfo.timezone,endYear,endMonth,endDate,0,0))
PROFIT=input.float(defval=1,minval=0,title="Targetprofit(%):",step=0.10,group="TAKEPROFIT-STOPLOSS")
STOPLOSS=input.float(defval=1,minval=0,title="StopLoss(%):",step=0.10,group="TAKEPROFIT-STOPLOSS")
varfloatequity_trades=0
equity_trades:=strategy.initial_capital
varfloatequity=0
varfloatqty_order=0
t_ordersize="Percentagesizeofeachneworder.With'ReinvestmentProfit'activate,thesizewillbecalculateontheequity,with'ReinvestmentProfit'deactivatethesizewillbecalculateontheinitialcapital."
orders_size=input.float(defval=2,title="Orderssize(%):",minval=0.10,step=0.10,maxval=100,group="RISKMANAGEMENT",tooltip=t_ordersize)
qty_order:=((equity_trades*orders_size)/100)/close
C_DownTrend=true
C_UpTrend=true
vartrendRule1="SMA50"
vartrendRule2="SMA50,SMA200"
vartrendRule=input.string(trendRule1,"DetectTrendBasedOn",options=[trendRule1,trendRule2,"Nodetection"],group="BULLISHENGULFING")
iftrendRule==trendRule1
priceAvg=ta.sma(close,50)
C_DownTrend:=close<priceAvg
C_UpTrend:=close>priceAvg
iftrendRule==trendRule2
sma200=ta.sma(close,200)
sma50=ta.sma(close,50)
C_DownTrend:=close<sma50andsma50<sma200
C_UpTrend:=close>sma50andsma50>sma200
C_Len=14
C_ShadowPercent=5.0
C_ShadowEqualsPercent=100.0
C_DojiBodyPercent=5.0
C_Factor=2.0
C_BodyHi=math.max(close,open)
C_BodyLo=math.min(close,open)
C_Body=C_BodyHi-C_BodyLo
C_BodyAvg=ta.ema(C_Body,C_Len)
C_SmallBody=C_Body<C_BodyAvg
C_LongBody=C_Body>C_BodyAvg
C_UpShadow=high-C_BodyHi
C_DnShadow=C_BodyLo-low
C_HasUpShadow=C_UpShadow>C_ShadowPercent/100*C_Body
C_HasDnShadow=C_DnShadow>C_ShadowPercent/100*C_Body
C_WhiteBody=open<close
C_BlackBody=open>close
C_Range=high-low
C_IsInsideBar=C_BodyHi[1]>C_BodyHiandC_BodyLo[1]<C_BodyLo
C_BodyMiddle=C_Body/2+C_BodyLo
C_ShadowEquals=C_UpShadow==C_DnShadowor(math.abs(C_UpShadow-C_DnShadow)/C_DnShadow*100)<C_ShadowEqualsPercentand(math.abs(C_DnShadow-C_UpShadow)/C_UpShadow*100)<C_ShadowEqualsPercent
C_IsDojiBody=C_Range>0andC_Body<=C_Range*C_DojiBodyPercent/100
C_Doji=C_IsDojiBodyandC_ShadowEquals
patternLabelPosLow=low-(ta.atr(30)*0.6)
patternLabelPosHigh=high+(ta.atr(30)*0.6)
label_color_bullish=input.color(color.rgb(43,255,0),title="LabelColorBullish",group="BULLISHENGULFING")
C_EngulfingBullishNumberOfCandles=2
C_EngulfingBullish=C_DownTrendandC_WhiteBodyandC_LongBodyandC_BlackBody[1]andC_SmallBody[1]andclose>=open[1]andopen<=close[1]and(close>open[1]oropen<close[1])
ifC_EngulfingBullish
varttBullishEngulfing="Engulfing\nAttheendofagivendownwardtrend,therewillmostlikelybeareversalpattern.Todistinguishthefirstday,thiscandlestickpatternusesasmallbody,followedbyadaywherethecandlebodyfullyovertakesthebodyfromthedaybefore,andclosesinthetrend’soppositedirection.Althoughsimilartotheoutsidereversalchartpattern,itisnotessentialforthispatterntocompletelyovertaketherange(hightolow),ratheronlytheopenandtheclose."
label.new(bar_index,patternLabelPosLow,text="BE",style=label.style_label_up,color=label_color_bullish,textcolor=color.white,tooltip=ttBullishEngulfing)
bgcolor(ta.highest(C_EngulfingBullish?1:0,C_EngulfingBullishNumberOfCandles)!=0?color.new(#21f321,90):na,offset=-(C_EngulfingBullishNumberOfCandles-1))
varfloatc=0
varfloato=0
varfloatc_exit=0
varfloatc_stopl=0
ifC_EngulfingBullishandstrategy.opentrades==0andinDateRange
c:=strategy.equity
o:=close
c_exit:=c+(c*PROFIT/100)
c_stopl:=c-(c*STOPLOSS/100)
strategy.entry(id="LONG",direction=strategy.long,qty=qty_order,limit=o)
ifta.crossover(strategy.equity,c_exit)
strategy.exit(id="CLOSE-LONG",from_entry="LONG",limit=close)
ifta.crossunder(strategy.equity,c_stopl)
strategy.exit(id="CLOSE-LONG",from_entry="LONG",limit=close)
Expand (115 lines)
