Script Name: Buy-Sell Signal Template-Boilerplate Strategy [JacobMagleby]
Author: JacobMagleby
Description: This script allows the user to connect an external indicator output/plot value to allow for a no-code solution to setup a simple buy/sell signal strategy. For those of you who do not know how to program, do not be intimidated as this is a very easy setup process.

Maybe you want to buy when the 'RSI' value drops below '30' and then sell when the 'RSI' value climbs...
PineScript code:

Pine Script™ strategy
Buy/Sell Signal Template/Boilerplate Strategy [JacobMagleby]
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  ExoMaven
//@version=5
strategy(title  =  "Buy/Sell  Signal  Template/Boilerplate  Strategy[ExoMaven]",  shorttitle  =  "Buy/Sell  Signal  Template  Strategy[V1]",  overlay  =  true)
source  =  input.source(title  =  "Source",  defval  =  ohlc4,  group  =  "Source  Settings")
buy_type  =  input.string(title  =  "Buy  Type",  defval  =  "Greater  Than",  options  =  ["Greater  Than",  "Less  Than"],  group  ="SignalSettings")
buy_value=input.float(title="BuyValue",defval=50,group="SignalSettings")
sell_type=input.string(title="SellType",defval="LessThan",options=["LessThan","GreaterThan"],group="SignalSettings")
sell_value=input.float(title="SellValue",defval=50,group="SignalSettings")
buy_above_or_below=buy_type=="GreaterThan"?source>buy_valueandsource[1]<buy_value:source<buy_valueandsource[1]>buy_value
sell_above_or_below=sell_type=="LessThan"?source<sell_valueandsource[1]>sell_value:source>sell_valueandsource[1]<sell_value
buy=buy_above_or_belowandbarstate.isconfirmed
sell=sell_above_or_belowandbarstate.isconfirmed
ifbuy
strategy.close_all()
strategy.entry(id="Buy",direction=strategy.long)
ifsell
strategy.close_all()
strategy.entry(id="Sell",direction=strategy.short)
Expand (27 lines)
