Script Name: Channel Break [for free bot]
Author: AlgoTrading_CC
Description: I present to you a script for testing the channel breakout strategy for the Bitmex exchange.
Cryptocurrency itself is a trending tool, which is why breakout strategies generate the largest profits, and the channel breakout strategy is one of the most effective trend strategies.

The optimization result shows the result of trading on a volume of 20% of the deposit....
PineScript code:

Pine Script™ strategy
Channel Break [for free bot]
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  Strategy  testing  and  optimisation  for  free  Bitmex  trading  bot
//  ©  algotradingcc
//@version=4
strategy("Channel  Break  [for  free  bot]",  overlay=true,  default_qty_type=  strategy.percent_of_equity,  initial_capital  =  1000,  default_qty_value  =  20,  commission_type=strategy.commission.percent,  commission_value=0.075)
//Options
buyPeriod  =  input(13,  "Channel  Period  for  Long  position")
sellPeriod  =  input(18,  "Channel  Period  for  Short  position")
isMiddleExit  =  input(true,  "Is  exit  on  Base  Line?")
takeProfit  =  input(46,  "Take  Profit  (%)  for  position")
stopLoss  =  input(9,  "Stop  Loss  (%)  for  position")
//  Test  Start
startYear  =  input(2005,  "Test  Start  Year")
startMonth  =  input(1,  "Test  Start  Month")
startDay  =  input(1,  "Test  Start  Day")
startTest  =  timestamp(startYear,startMonth,startDay,0,0)
//Test  End
endYear  =  input(2050,  "Test  EndYear")
endMonth=input(12,"TestEndMonth")
endDay=input(30,"TestEndDay")
endTest=timestamp(endYear,endMonth,endDay,23,59)
timeRange=time>startTestandtime<endTest?true:false
//Long&ShortLevels
BuyEnter=highest(buyPeriod)
BuyExit=isMiddleExit?(highest(buyPeriod)+lowest(buyPeriod))/2:lowest(buyPeriod)
SellEnter=lowest(sellPeriod)
SellExit=isMiddleExit?(highest(sellPeriod)+lowest(sellPeriod))/2:highest(sellPeriod)
//PlotData
plot(BuyEnter,style=plot.style_line,linewidth=2,color=color.blue,title="BuyEnter")
plot(BuyExit,style=plot.style_line,linewidth=1,color=color.blue,title="BuyExit",transp=50)
plot(SellEnter,style=plot.style_line,linewidth=2,color=color.red,title="SellEnter")
plot(SellExit,style=plot.style_line,linewidth=1,color=color.red,title="SellExit",transp=50)
//CalcTakeProfits&StopLoss
TP=0.0
SL=0.0
ifstrategy.position_size>0
TP:=strategy.position_avg_price*(1+takeProfit/100)
SL:=strategy.position_avg_price*(1-stopLoss/100)
ifstrategy.position_size>0andSL>BuyExit
BuyExit:=SL

ifstrategy.position_size<0
TP:=strategy.position_avg_price*(1-takeProfit/100)
SL:=strategy.position_avg_price*(1+stopLoss/100)
ifstrategy.position_size<0andSL<SellExit
SellExit:=SL


//LongPosition
iftimeRangeandstrategy.position_size<=0
strategy.entry("Long",strategy.long,stop=BuyEnter)
strategy.exit("LongExit","Long",stop=BuyExit,limit=TP,when=strategy.position_size>0)
//ShortPosition
iftimeRangeandstrategy.position_size>=0
strategy.entry("Short",strategy.short,stop=SellEnter)

strategy.exit("ShortExit","Short",stop=SellExit,limit=TP,when=strategy.position_size<0)
//Close&CancelwhenoverEndoftheTest
iftime>endTest
strategy.close_all()
strategy.cancel_all()
Expand (76 lines)
