Script Name: Cipher_B (Finandy support)
Author: Cherepanov_V
Description: In this version of the script you can force to cancel your position after some amount of time indepedently on price action. For example, your bot open a short position with SL=1% and TP=2.4% but price did not reach any of this level over the course of to say 8 hours. In this case, position will be closed regardless of the price.
Other interesting features are...
PineScript code:

Pine Script™ strategy
Cipher_B (Finandy support)
//@version=4
strategy(title  =  'Cipher_B',  overlay=true,initial_capital=10,default_qty_type  =  strategy.cash,default_qty_value  =50,commission_type  =  strategy.commission.percent,commission_value  =0.04,currency="EUR")
//  PARAMETERS  {
//  WaveTrend
wtShow  =  input(true,  title  =  'Show  WaveTrend',  type  =  input.bool)
wtBuyShow  =  input(true,  title  =  'Show  Buy  dots',  type  =  input.bool)
wtGoldShow  =  input(true,  title  =  'Show  Gold  dots',  type  =  input.bool)
wtSellShow  =  input(true,  title  =  'Show  Sell  dots',  type  =  input.bool)
wtDivShow  =  input(true,  title  =  'Show  Div.  dots',  type  =  input.bool)
vwapShow  =  input(true,  title  =  'Show  Fast  WT',  type  =  input.bool)
wtChannelLen  =  input(9,  title  =  'WT  Channel  Length',  type  =  input.integer)
wtAverageLen  =  input(12,  title  =  'WT  Average  Length',  type  =  input.integer)
wtMASource  =  input(hlc3,  title  =  'WT  MA  Source',  type  =  input.source)
wtMALen  =  input(3,  title  =  'WT  MA  Length',  type  =  input.integer)
//  WaveTrend  Overbought  &  Oversold  lines
obLevel  =  input(53,  title  =  'WT  Overbought  Level  1',  type  =  input.integer)
obLevel2  =  input(60,  title  =  'WT  Overbought  Level  2',  type  =  input.integer)
obLevel3  =  input(100,  title  =  'WT  Overbought  Level  3',  type  =  input.integer)
osLevel  =  input(-53,  title  =  'WT  Oversold  Level  1',  type  =  input.integer)
osLevel2  =  input(-60,  title  =  'WT  Oversold  Level  2',  type  =  input.integer)
osLevel3  =  input(-75,  title  =  'WT  Oversold  Level  3',  type  =  input.integer)
//  Divergence  WT
wtShowDiv  =  input(true,  title  =  'Show  WT  Regular  Divergences',  type  =  input.bool)
wtShowHiddenDiv  =  input(false,  title  =  'Show  WT  Hidden  Divergences',  type  =  input.bool)
showHiddenDiv_nl  =  input(true,  title  =  'Not  apply  OB/OS  Limits  on  Hidden  Divergences',  type  =  input.bool)
wtDivOBLevel  =  input(45,  title  =  'WT  Bearish  Divergence  min',  type  =  input.integer)
wtDivOSLevel  =  input(-65,  title  =  'WT  Bullish  Divergence  min',  type  =  input.integer)
//  Divergence  extra  range
wtDivOBLevel_addshow  =  input(false,  title  =  'Show  2nd  WT  Regular  Divergences',  type  =  input.bool)
wtDivOBLevel_add  =  input(15,  title  =  'WT  2nd  Bearish  Divergence',  type  =  input.integer)
wtDivOSLevel_add  =  input(-40,  title  =  'WT  2nd  Bullish  Divergence  15  min',  type  =  input.integer)
//  RSI+MFI
rsiMFIShow  =  input(true,  title  =  'Show  MFI',  type  =  input.bool)
rsiMFIperiod  =  input(60,title  =  'MFI  Period',  type  =  input.integer)
rsiMFIMultiplier  =  input(150,  title  =  'MFI  Area  multiplier',  type  =  input.float)
rsiMFIPosY  =  input(2.5,  title  =  'MFI  Area  Y  Pos',  type  =  input.float)
//  RSI
rsiShow  =  input(false,  title  =  'Show  RSI',  type  =  input.bool)
rsiSRC  =  input(close,  title  =  'RSI  Source',  type  =  input.source)
rsiLen  =  input(14,  title  =  'RSI  Length',  type  =  input.integer)
rsiOversold  =  input(30,  title  =  'RSI  Oversold',  minval  =  50,  maxval  =  100,  type  =  input.integer)
rsiOverbought  =  input(60,  title  =  'RSI  Overbought',  minval  =  0,  maxval  =  50,  type  =  input.integer)
//  Divergence  RSI
rsiShowDiv  =  input(false,  title  =  'Show  RSI  Regular  Divergences',  type  =  input.bool)
rsiShowHiddenDiv  =  input(false,  title  =  'Show  RSI  Hidden  Divergences',  type  =  input.bool)
rsiDivOBLevel  =  input(60,  title  =  'RSI  Bearish  Divergence  min',  type  =  input.integer)
rsiDivOSLevel  =  input(30,  title  =  'RSI  Bullish  Divergence  min',  type  =  input.integer)
//  RSI  Stochastic
stochShow  =  input(true,  title  =  'Show  Stochastic  RSI',  type  =  input.bool)
stochUseLog  =  input(true,  title='  Use  Log?',  type  =  input.bool)
stochAvg  =  input(false,  title='Use  Average  of  both  K  &  D',  type  =  input.bool)
stochSRC  =  input(close,  title  =  'Stochastic  RSI  Source',  type  =  input.source)
stochLen  =  input(14,  title  =  'Stochastic  RSI  Length',  type  =  input.integer)
stochRsiLen  =  input(14,  title  =  'RSI  Length  ',  type  =  input.integer)
stochKSmooth  =  input(3,  title  =  'Stochastic  RSI  K  Smooth',  type  =  input.integer)
stochDSmooth  =  input(3,  title  =  'Stochastic  RSI  D  Smooth',  type  =  input.integer)
//  Divergence  stoch
stochShowDiv  =  input(false,  title  =  'Show  Stoch  Regular  Divergences',  type  =  input.bool)
stochShowHiddenDiv  =  input(false,  title  =  'Show  Stoch  Hidden  Divergences',  type  =  input.bool)
//  Schaff  Trend  Cycle
tcLine  =  input(false,  title="Show  Schaff  TC  line",  type=input.bool)
tcSRC  =  input(close,  title  =  'Schaff  TC  Source',  type  =  input.source)
tclength  =  input(10,  title="Schaff  TC",  type=input.integer)
tcfastLength  =  input(23,  title="Schaff  TC  Fast  Lenght",  type=input.integer)
tcslowLength  =  input(50,  title="Schaff  TC  Slow  Length",  type=input.integer)
tcfactor  =  input(0.5,  title="Schaff  TC  Factor",  type=input.float)
//  Sommi  Flag
sommiFlagShow  =  input(false,  title  =  'Show  Sommi  flag',  type  =  input.bool)
sommiShowVwap  =  input(false,  title  =  'Show  Sommi  F.  Wave',  type  =  input.bool)
sommiVwapTF  =  input('720',  title  =  'Sommi  F.  Wave  timeframe',  type  =  input.string)
sommiVwapBearLevel  =  input(0,  title  =  'F.  Wave  Bear  Level  (less  than)',  type  =  input.integer)
sommiVwapBullLevel  =  input(0,  title  =  'F.  Wave  Bull  Level  (more  than)',  type  =  input.integer)
soomiFlagWTBearLevel  =  input(0,  title  =  'WT  Bear  Level  (more  than)',  type  =  input.integer)
soomiFlagWTBullLevel  =  input(0,  title  =  'WT  Bull  Level  (less  than)',  type  =  input.integer)
soomiRSIMFIBearLevel  =  input(0,  title  =  'Money  flow  Bear  Level  (less  than)',  type  =  input.integer)
soomiRSIMFIBullLevel  =  input(0,  title  =  'Money  flow  Bull  Level  (more  than)',  type  =  input.integer)
//  Sommi  Diamond
sommiDiamondShow  =  input(false,  title  =  'Show  Sommi  diamond',  type  =  input.bool)
sommiHTCRes  =  input('60',  title  =  'HTF  Candle  Res.  1',  type  =  input.string)
sommiHTCRes2  =  input('240',  title  =  'HTF  Candle  Res.  2',  type  =  input.string)
soomiDiamondWTBearLevel  =  input(0,  title  =  'WT  Bear  Level  (More  than)',  type  =  input.integer)
soomiDiamondWTBullLevel  =  input(0,  title  =  'WT  Bull  Level  (Less  than)',  type  =  input.integer)
//  macd  Colors
macdWTColorsShow  =  input(false,  title  =  'Show  MACD  Colors',  type  =  input.bool)
macdWTColorsTF  =  input('240',  title  =  'MACD  Colors  MACD  TF',  type  =  input.string)
darkMode  =  input(false,  title  =  'Dark  mode',  type  =  input.bool)
//  Colors
colorRed  =  #ff0000
colorPurple  =  #e600e6
colorGreen  =  #3fff00
colorOrange  =  #e2a400
colorYellow  =  #ffe500
colorWhite  =  #ffffff
colorPink  =  #ff00f0
colorBluelight  =  #31c0ff
colorWT1  =  #90caf9
colorWT2  =  #0d47a1
colorWT2_  =  #131722
colormacdWT1a  =  #4caf58
colormacdWT1b  =  #af4c4c
colormacdWT1c  =#7ee57e
colormacdWT1d=#ff3535
colormacdWT2a=#305630
colormacdWT2b=#310101
colormacdWT2c=#132213
colormacdWT2d=#770000
//}PARAMETERS
//FUNCTIONS{

//Divergences
f_top_fractal(src)=>src[4]<src[2]andsrc[3]<src[2]andsrc[2]>src[1]andsrc[2]>src[0]
f_bot_fractal(src)=>src[4]>src[2]andsrc[3]>src[2]andsrc[2]<src[1]andsrc[2]<src[0]
f_fractalize(src)=>f_top_fractal(src)?1:f_bot_fractal(src)?-1:0
f_findDivs(src,topLimit,botLimit,useLimits)=>
fractalTop=f_fractalize(src)>0and(useLimits?src[2]>=topLimit:true)?src[2]:na
fractalBot=f_fractalize(src)<0and(useLimits?src[2]<=botLimit:true)?src[2]:na
highPrev=valuewhen(fractalTop,src[2],0)[2]
highPrice=valuewhen(fractalTop,high[2],0)[2]
lowPrev=valuewhen(fractalBot,src[2],0)[2]
lowPrice=valuewhen(fractalBot,low[2],0)[2]
bearSignal=fractalTopandhigh[2]>highPriceandsrc[2]<highPrev
bullSignal=fractalBotandlow[2]<lowPriceandsrc[2]>lowPrev
bearDivHidden=fractalTopandhigh[2]<highPriceandsrc[2]>highPrev
bullDivHidden=fractalBotandlow[2]>lowPriceandsrc[2]<lowPrev
[fractalTop,fractalBot,lowPrev,bearSignal,bullSignal,bearDivHidden,bullDivHidden]

//RSI+MFI
f_rsimfi(_period,_multiplier,_tf)=>security(syminfo.tickerid,_tf,sma(((close-open)/(high-low))*_multiplier,_period)-rsiMFIPosY)

//WaveTrend
f_wavetrend(src,chlen,avg,malen,tf)=>
tfsrc=security(syminfo.tickerid,tf,src)
esa=ema(tfsrc,chlen)
de=ema(abs(tfsrc-esa),chlen)
ci=(tfsrc-esa)/(0.015*de)
wt1=security(syminfo.tickerid,tf,ema(ci,avg))
wt2=security(syminfo.tickerid,tf,sma(wt1,malen))
wtVwap=wt1-wt2
wtOversold=wt2<=osLevel
wtOverbought=wt2>=obLevel
wtCross=cross(wt1,wt2)
wtCrossUp=wt2-wt1<=0
wtCrossDown=wt2-wt1>=0
wtCrosslast=cross(wt1[2],wt2[2])
wtCrossUplast=wt2[2]-wt1[2]<=0
wtCrossDownlast=wt2[2]-wt1[2]>=0
[wt1,wt2,wtOversold,wtOverbought,wtCross,wtCrossUp,wtCrossDown,wtCrosslast,wtCrossUplast,wtCrossDownlast,wtVwap]
//SchaffTrendCycle
f_tc(src,length,fastLength,slowLength)=>
ema1=ema(src,fastLength)
ema2=ema(src,slowLength)
macdVal=ema1-ema2
alpha=lowest(macdVal,length)
beta=highest(macdVal,length)-alpha
gamma=(macdVal-alpha)/beta*100
gamma:=beta>0?gamma:nz(gamma[1])
delta=gamma
delta:=na(delta[1])?delta:delta[1]+tcfactor*(gamma-delta[1])
epsilon=lowest(delta,length)
zeta=highest(delta,length)-epsilon
eta=(delta-epsilon)/zeta*100
eta:=zeta>0?eta:nz(eta[1])
stcReturn=eta
stcReturn:=na(stcReturn[1])?stcReturn:stcReturn[1]+tcfactor*(eta-stcReturn[1])
stcReturn
//StochasticRSI
f_stochrsi(_src,_stochlen,_rsilen,_smoothk,_smoothd,_log,_avg)=>
src=_log?log(_src):_src
rsi=rsi(src,_rsilen)
kk=sma(stoch(rsi,rsi,rsi,_stochlen),_smoothk)
d1=sma(kk,_smoothd)
avg_1=avg(kk,d1)
k=_avg?avg_1:kk
[k,d1]
//MACD
f_macd(src,fastlen,slowlen,sigsmooth,tf)=>
fast_ma=security(syminfo.tickerid,tf,ema(src,fastlen))
slow_ma=security(syminfo.tickerid,tf,ema(src,slowlen))
macd=fast_ma-slow_ma,
signal=security(syminfo.tickerid,tf,sma(macd,sigsmooth))
hist=macd-signal
[macd,signal,hist]
//MACDColorsonWT
f_macdWTColors(tf)=>
hrsimfi=f_rsimfi(rsiMFIperiod,rsiMFIMultiplier,tf)
[macd,signal,hist]=f_macd(close,28,42,9,macdWTColorsTF)
macdup=macd>=signal
macddown=macd<=signal
macdWT1Color=macdup?hrsimfi>0?colormacdWT1c:colormacdWT1a:macddown?hrsimfi<0?colormacdWT1d:colormacdWT1b:na
macdWT2Color=macdup?hrsimfi<0?colormacdWT2c:colormacdWT2a:macddown?hrsimfi<0?colormacdWT2d:colormacdWT2b:na
[macdWT1Color,macdWT2Color]

//Gethighertimeframecandle
f_getTFCandle(_tf)=>
_open=security(heikinashi(syminfo.tickerid),_tf,open,barmerge.gaps_off,barmerge.lookahead_off)
_close=security(heikinashi(syminfo.tickerid),_tf,close,barmerge.gaps_off,barmerge.lookahead_off)
_high=security(heikinashi(syminfo.tickerid),_tf,high,barmerge.gaps_off,barmerge.lookahead_off)
_low=security(heikinashi(syminfo.tickerid),_tf,low,barmerge.gaps_off,barmerge.lookahead_off)
hl2=(_high+_low)/2.0
newBar=change(_open)
candleBodyDir=_close>_open
[candleBodyDir,newBar]
//Sommiflag
f_findSommiFlag(tf,wt1,wt2,rsimfi,wtCross,wtCrossUp,wtCrossDown)=>
[hwt1,hwt2,hwtOversold,hwtOverbought,hwtCross,hwtCrossUp,hwtCrossDown,hwtCrosslast,hwtCrossUplast,hwtCrossDownlast,hwtVwap]=f_wavetrend(wtMASource,wtChannelLen,wtAverageLen,wtMALen,tf)

bearPattern=rsimfi<soomiRSIMFIBearLeveland
wt2>soomiFlagWTBearLeveland
wtCrossand
wtCrossDownand
hwtVwap<sommiVwapBearLevel

bullPattern=rsimfi>soomiRSIMFIBullLeveland
wt2<soomiFlagWTBullLeveland
wtCrossand
wtCrossUpand
hwtVwap>sommiVwapBullLevel

[bearPattern,bullPattern,hwtVwap]

f_findSommiDiamond(tf,tf2,wt1,wt2,wtCross,wtCrossUp,wtCrossDown)=>
[candleBodyDir,newBar]=f_getTFCandle(tf)
[candleBodyDir2,newBar2]=f_getTFCandle(tf2)
bearPattern=wt2>=soomiDiamondWTBearLeveland
wtCrossand
wtCrossDownand
notcandleBodyDirand
notcandleBodyDir2
bullPattern=wt2<=soomiDiamondWTBullLeveland
wtCrossand
wtCrossUpand
candleBodyDirand
candleBodyDir2
[bearPattern,bullPattern]

//}FUNCTIONS
//CALCULATEINDICATORS{
//RSI
rsi=rsi(rsiSRC,rsiLen)
rsiColor=rsi<=rsiOversold?colorGreen:rsi>=rsiOverbought?colorRed:colorPurple
//RSI+MFIArea
rsiMFI=f_rsimfi(rsiMFIperiod,rsiMFIMultiplier,timeframe.period)
rsiMFIColor=rsiMFI>0?#3ee145:#ff3d2e
//CalculatesWaveTrend
[wt1,wt2,wtOversold,wtOverbought,wtCross,wtCrossUp,wtCrossDown,wtCross_last,wtCrossUp_last,wtCrossDown_last,wtVwap]=f_wavetrend(wtMASource,wtChannelLen,wtAverageLen,wtMALen,timeframe.period)

//StochasticRSI
[stochK,stochD]=f_stochrsi(stochSRC,stochLen,stochRsiLen,stochKSmooth,stochDSmooth,stochUseLog,stochAvg)
//SchaffTrendCycle
tcVal=f_tc(tcSRC,tclength,tcfastLength,tcslowLength)
//Sommiflag
[sommiBearish,sommiBullish,hvwap]=f_findSommiFlag(sommiVwapTF,wt1,wt2,rsiMFI,wtCross,wtCrossUp,wtCrossDown)
//Sommidiamond
[sommiBearishDiamond,sommiBullishDiamond]=f_findSommiDiamond(sommiHTCRes,sommiHTCRes2,wt1,wt2,wtCross,wtCrossUp,wtCrossDown)
//macdcolors
[macdWT1Color,macdWT2Color]=f_macdWTColors(macdWTColorsTF)
//WTDivergences
[wtFractalTop,wtFractalBot,wtLow_prev,wtBearDiv,wtBullDiv,wtBearDivHidden,wtBullDivHidden]=f_findDivs(wt2,wtDivOBLevel,wtDivOSLevel,true)

[wtFractalTop_add,wtFractalBot_add,wtLow_prev_add,wtBearDiv_add,wtBullDiv_add,wtBearDivHidden_add,wtBullDivHidden_add]=f_findDivs(wt2,wtDivOBLevel_add,wtDivOSLevel_add,true)
[wtFractalTop_nl,wtFractalBot_nl,wtLow_prev_nl,wtBearDiv_nl,wtBullDiv_nl,wtBearDivHidden_nl,wtBullDivHidden_nl]=f_findDivs(wt2,0,0,false)
wtBearDivHidden_=showHiddenDiv_nl?wtBearDivHidden_nl:wtBearDivHidden
wtBullDivHidden_=showHiddenDiv_nl?wtBullDivHidden_nl:wtBullDivHidden
wtBearDivColor=(wtShowDivandwtBearDiv)or(wtShowHiddenDivandwtBearDivHidden_)?colorRed:na
wtBullDivColor=(wtShowDivandwtBullDiv)or(wtShowHiddenDivandwtBullDivHidden_)?colorGreen:na
wtBearDivColor_add=(wtShowDivand(wtDivOBLevel_addshowandwtBearDiv_add))or(wtShowHiddenDivand(wtDivOBLevel_addshowandwtBearDivHidden_add))?#9a0202:na
wtBullDivColor_add=(wtShowDivand(wtDivOBLevel_addshowandwtBullDiv_add))or(wtShowHiddenDivand(wtDivOBLevel_addshowandwtBullDivHidden_add))?#1b5e20:na
//RSIDivergences
[rsiFractalTop,rsiFractalBot,rsiLow_prev,rsiBearDiv,rsiBullDiv,rsiBearDivHidden,rsiBullDivHidden]=f_findDivs(rsi,rsiDivOBLevel,rsiDivOSLevel,true)
[rsiFractalTop_nl,rsiFractalBot_nl,rsiLow_prev_nl,rsiBearDiv_nl,rsiBullDiv_nl,rsiBearDivHidden_nl,rsiBullDivHidden_nl]=f_findDivs(rsi,0,0,false)
rsiBearDivHidden_=showHiddenDiv_nl?rsiBearDivHidden_nl:rsiBearDivHidden
rsiBullDivHidden_=showHiddenDiv_nl?rsiBullDivHidden_nl:rsiBullDivHidden
rsiBearDivColor=(rsiShowDivandrsiBearDiv)or(rsiShowHiddenDivandrsiBearDivHidden_)?colorRed:na
rsiBullDivColor=(rsiShowDivandrsiBullDiv)or(rsiShowHiddenDivandrsiBullDivHidden_)?colorGreen:na

//StochDivergences
[stochFractalTop,stochFractalBot,stochLow_prev,stochBearDiv,stochBullDiv,stochBearDivHidden,stochBullDivHidden]=f_findDivs(stochK,0,0,false)
stochBearDivColor=(stochShowDivandstochBearDiv)or(stochShowHiddenDivandstochBearDivHidden)?colorRed:na
stochBullDivColor=(stochShowDivandstochBullDiv)or(stochShowHiddenDivandstochBullDivHidden)?colorGreen:na
//SmallCirclesWTCross
signalColor=wt2-wt1>0?color.red:color.lime
//Buysignal.
buySignal=wtCrossandwtCrossUpandwtOversold
buySignalDiv=(wtShowDivandwtBullDiv)or
(wtShowDivandwtBullDiv_add)or
(stochShowDivandstochBullDiv)or
(rsiShowDivandrsiBullDiv)

buySignalDiv_color=wtBullDiv?colorGreen:
wtBullDiv_add?color.new(colorGreen,60):
rsiShowDiv?colorGreen:na
//Sellsignal
sellSignal=wtCrossandwtCrossDownandwtOverbought

sellSignalDiv=(wtShowDivandwtBearDiv)or
(wtShowDivandwtBearDiv_add)or
(stochShowDivandstochBearDiv)or
(rsiShowDivandrsiBearDiv)

sellSignalDiv_color=wtBearDiv?colorRed:
wtBearDiv_add?color.new(colorRed,60):
rsiBearDiv?colorRed:na
//GoldBuy
lastRsi=valuewhen(wtFractalBot,rsi[2],0)[2]
wtGoldBuy=((wtShowDivandwtBullDiv)or(rsiShowDivandrsiBullDiv))and
wtLow_prev<=osLevel3and
wt2>osLevel3and
wtLow_prev-wt2<=-5and
lastRsi<30

//}CALCULATEINDICATORS
//DRAW{
bgcolor(darkMode?color.new(#000000,80):na)
zLine=plot(0,color=color.new(colorWhite,50))
//MFIBAR
rsiMfiBarTopLine=plot(rsiMFIShow?-95:na,title='MFIBarTOPLine',transp=100)
rsiMfiBarBottomLine=plot(rsiMFIShow?-99:na,title='MFIBarBOTTOMLine',transp=100)
fill(rsiMfiBarTopLine,rsiMfiBarBottomLine,title='MFIBarColors',color=rsiMFIColor,transp=75)
Global=input(title="UseGlobaltrend?",defval=true,type=input.bool,group="TrendSettings")
regimeFilter_frame=input(title="Globaltrendtimeframe",defval="5",options=['D','60','5'],group="TrendSettings")
regimeFilter_length=input(title="Globaltrendlength",defval=1700,type=input.integer,group="TrendSettings")
localFilter_length=input(title="Localtrendfilterlength",defval=20,type=input.integer,group="TrendSettings")
localFilter_frame=input(title="Localtrendfiltertimeframe",defval="60",options=['D','60','5'],group="TrendSettings")
Div_1=input(title="Onlydivergenciesforlong",defval=true,type=input.bool,group="TrendSettings")
Div_2=input(title="Onlydivergenciesforshort",defval=true,type=input.bool,group="TrendSettings")
sommi_diamond_on=input(title="Sommidiamondalerts",defval=false,type=input.bool,group="TrendSettings")
Cancel_all=input(title="Cancelallpositionsifpricecrosseslocalsma?(yellowline)",defval=false,type=input.bool,group="TrendSettings")
a_1=input(title="TPlong",defval=0.95,step=0.5,type=input.float,group="TP/SLSettings")
a_1_div=input(title="TPlongdiv",defval=0.95,step=0.5,type=input.float,group="TP/SLSettings")
a_2=input(title="TPshort",defval=0.95,step=1,type=input.float,group="TP/SLSettings")
b_1=input(title="SLlong",defval=5,step=0.1,type=input.float,group="TP/SLSettings")
b_2=input(title="SLshort",defval=5,step=0.1,type=input.float,group="TP/SLSettings")
RSI_filter_checkbox=input(title="RSIfilterON",defval=false,type=input.bool,group="TrendSettings")
Price_filter_checkbox=input(title="PricefilterON",defval=false,type=input.bool,group="TrendSettings")
Price_filter_1_long=input(title="LongPricefilterfrom",defval=1000,type=input.integer,group="TrendSettings")
Price_filter_2_long=input(title="LongPricefilterto",defval=1200,type=input.integer,group="TrendSettings")
Price_filter_1_short=input(title="ShortPricefilterfrom",defval=1000,type=input.integer,group="TrendSettings")
Price_filter_2_short=input(title="ShortPricefilterto",defval=1200,type=input.integer,group="TrendSettings")
Local_filter_checkbox=input(title="UseLocaltrend?",defval=true,type=input.bool,group="TrendSettings")
slope_checkbox=input(title="UseSlopefilter?",defval=false,type=input.bool,group="SlopeSettings")
slope_number_long=input(title="Slopenumberlong",defval=-0.3,step=0.01,type=input.float,group="SlopeSettings")
slope_number_short=input(title="Slopenumbershort",defval=0.16,step=0.01,type=input.float,group="SlopeSettings")
slope_period=input(title="Slopeperiod",defval=300,type=input.integer,group="SlopeSettings")
long_on=input(title="Onlylong?",defval=true,type=input.bool,group="PositionSettings")
short_on=input(title="Onlyshort?",defval=true,type=input.bool,group="PositionSettings")
volume_ETH_spot_checkbox=input(title="Volumefilter?",defval=false,type=input.bool,group="VolumeSettings")
volume_ETH_spot_number_more=input(title="Volumenomorethan:",defval=3700,type=input.integer,group="VolumeSettings")
volume_ETH_spot_number_less=input(title="Volumenolessthan:",defval=600,type=input.integer,group="VolumeSettings")
limit_checkbox=input(title="Shiftopenposition?",defval=false,type=input.bool,group="ShiftSettings")
limit_shift=input(title="Howmany%toshift?",defval=0.5,step=0.01,type=input.float,group="ShiftSettings")
cancel_in=input(title="Cancelpositionin#bars?",defval=false,type=input.bool,group="CancelSettings")
cancel_in_num=input(title="Numberofbars",defval=96,type=input.integer,group="CancelSettings")
//Nameofticker
_str=tostring(syminfo.ticker)
_chars=str.split(_str,"")
int_len=array.size(_chars)
int_beg=max(0,_len-4)
string[]_substr=array.new_string(0)
if_beg<_len
_substr:=array.slice(_chars,0,_beg)
string_return=array.join(_substr,"")
//Hoursma
basis=security(syminfo.tickerid,localFilter_frame,ema(close,localFilter_length))
plot(basis,title="Localtrendcurve",color=color.yellow,style=plot.style_linebr)
//TrendcalculationwithEMA
f_sec(_market,_res,_exp)=>security(_market,_res,_exp[barstate.isconfirmed?0:1])
ema=sma(close,regimeFilter_length)
emaValue=f_sec("BTCUSDTPERP",regimeFilter_frame,ema)
marketPrice=f_sec("BTCUSDTPERP",regimeFilter_frame,close)
regimeFilter=Global?(marketPrice>emaValueormarketPrice[1]>emaValue[1]):true
reverse_regime=Global?(marketPrice<emaValueormarketPrice[1]<emaValue[1]):true
bgcolor(Global?regimeFilter?color.green:color.red:color.yellow)
//Localtrend
regimeFilter_local=Local_filter_checkbox?close>basis:true//orclose[1]>basis[1]
reverse_regime_local=Local_filter_checkbox?close<basis:true//orclose[1]<basis[1]
//RSIfilter
up=rma(max(change(close),0),14)
down=rma(-min(change(close),0),14)
rsi_=down==0?100:up==0?0:100-(100/(1+up/down))
rsiMA=ema(rsi_,12)
//localincline
sma=security(syminfo.tickerid,'60',ema(close,15))
slope=(sma-sma[slope_period])/slope_period
slope_filter_long=slope_checkbox?slope>slope_number_long:true
slope_filter_short=slope_checkbox?slope<slope_number_short:true
varlong_check=true
varshort_check=true
ifRSI_filter_checkbox
long_check:=rsiMA<40
short_check:=rsiMA>60
//
validlow=Div_1?buySignalDivorwtGoldBuy:buySignalorbuySignalDivorwtGoldBuy
validhigh=Div_2?sellSignalDiv:sellSignalorsellSignalDiv
//checkvolumeofETHUSDT
volume_ETH_spot=volume
volume_ETH_spot_filter=volume_ETH_spot_checkbox?volume_ETH_spot<volume_ETH_spot_number_moreandvolume_ETH_spot>volume_ETH_spot_number_less:true
//Checkifwehaveconfirmationforoursetup
varPrice_long=true
ifPrice_filter_checkbox
Price_long:=close>Price_filter_1_longandclose<Price_filter_2_long
varPrice_short=true
ifPrice_filter_checkbox
Price_short:=close>Price_filter_1_shortandclose<Price_filter_2_short
validlong=sommi_diamond_on?sommiBullishDiamondandstrategy.position_size==0andbarstate.isconfirmedandregimeFilter_localandregimeFilter:validlowandstrategy.position_size==0andbarstate.isconfirmedandregimeFilter_localandPrice_longandlong_checkandslope_filter_longandvolume_ETH_spot_filter
validshort=sommi_diamond_on?sommiBearishDiamondandstrategy.position_size==0andbarstate.isconfirmedandreverse_regime_localandreverse_regime:validhighandstrategy.position_size==0andbarstate.isconfirmedandreverse_regime_localandPrice_shortandshort_checkandslope_filter_shortandvolume_ETH_spot_filter
//Savetradestop&target&positionsizeifavalidsetupisdetected
vartradeStopPrice=0.0
vartradeTargetPrice=0.0
varTP=0.0
varlimit_price=0.0
//Detectvalidlongsetups&triggeralert
ifvalidlong
ifbuySignalDivorwtGoldBuy
limit_price:=limit_checkbox?close*(1-limit_shift*0.01):close
tradeStopPrice:=limit_price*(1-b_1*0.01)
tradeTargetPrice:=limit_price*(1+a_1_div*0.01)
TP:=a_1_div

else
limit_price:=limit_checkbox?close*(1-limit_shift*0.01):close
tradeStopPrice:=limit_price*(1-b_1*0.01)
tradeTargetPrice:=limit_price*(1+a_1*0.01)
TP:=a_1
//ifvalidlong
//ifbuySignalDivorwtGoldBuy
//limit_price:=close
//tradeStopPrice:=limit_price*(1-b_1*0.01)
//tradeTargetPrice:=limit_price*(1+a_1_div*0.01)
//TP:=a_1_div

//else
//limit_price:=close
//tradeStopPrice:=limit_price*(1-b_1*0.01)
//tradeTargetPrice:=limit_price*(1+a_1*0.01)
//TP:=a_1
//Detectvalidshortsetups&triggeralert
ifvalidshort
limit_price:=limit_checkbox?close*(1+limit_shift*0.01):close
tradeStopPrice:=limit_price*(1+b_2*0.01)
tradeTargetPrice:=limit_price*(1-a_2*0.01)
TP:=a_2
//ifvalidshort
//limit_price:=close
//tradeStopPrice:=limit_price*(1+b_2*0.01)
//tradeTargetPrice:=limit_price*(1-a_2*0.01)
//TP:=a_2
ifcancel_inandbarssince(validlong)==cancel_in_numorbarssince(validshort)==cancel_in_num
strategy.cancel_all()
iflong_on
strategy.entry(id="Long",long=strategy.long,limit=limit_price,when=validlong,comment='{\n'+'"name":"",\n'+'"secret":"",\n'+'"side":"buy",\n'+'"symbol":'+'"'+_return+'"'+',\n'+'"positionSide":"long"\n'+'}')
ifshort_on
strategy.entry(id="Short",long=strategy.short,limit=limit_price,when=validshort,comment='{\n'+'"name":"",\n'+'"secret":"",\n'+'"side":"sell",\n'+'"symbol":'+'"'+_return+'"'+',\n'+'"positionSide":"short",\n'+'"sl":{\n'+'"enabled":true\n'+'}\n'+'}')
//condition:=true
//ifCancel_allandstrategy.position_size>0and(reverse_regime_localorreverse_regime)
//strategy.close_all(when=strategy.position_size!=0,comment='{\n'+'"name":"",\n'+'"secret":"",\n'+'"side":"sell",\n'+'"symbol":'+'"'+_return+'"'+',\n'+'"positionSide":"flat"\n'+'}')
ifCancel_allandstrategy.position_size>0andreverse_regime_local
strategy.close_all(when=strategy.position_size!=0,comment='{\n'
+'"name":"",\n'
+'"secret":"",\n'
+'"side":"sell",\n'
+'"symbol":'+'"'+_return+'"'+',\n'
+'"positionSide":"flat"\n'
+'}')
ifCancel_allandstrategy.position_size<0andregimeFilter_local
strategy.close_all(when=strategy.position_size!=0,comment='{\n'
+'"name":"",\n'
+'"secret":"",\n'
+'"side":"buy",\n'
+'"symbol":'+'"'+_return+'"'+',\n'
+'"positionSide":"flat"\n'
+'}')

ifcancel_inandstrategy.position_size>0andbarssince(validlong)>cancel_in_num
strategy.close_all(when=strategy.position_size!=0,comment='{\n'
+'"name":"",\n'
+'"secret":"",\n'
+'"side":"sell",\n'
+'"symbol":'+'"'+_return+'"'+',\n'
+'"positionSide":"flat"\n'
+'}')
ifcancel_inandstrategy.position_size<0andbarssince(validshort)>cancel_in_num
strategy.close_all(when=strategy.position_size!=0,comment='{\n'
+'"name":"",\n'
+'"secret":"",\n'
+'"side":"buy",\n'
+'"symbol":'+'"'+_return+'"'+',\n'
+'"positionSide":"flat"\n'
+'}')
//Exittradeswheneverourstoportargetishit
strategy.exit(id="LongExit",from_entry="Long",limit=tradeTargetPrice,stop=tradeStopPrice,when=strategy.position_size>0)
strategy.exit(id="ShortExit",from_entry="Short",limit=tradeTargetPrice,stop=tradeStopPrice,when=strategy.position_size<0)
Expand (588 lines)
