Script Name: Combo 2-20 EMA & Bull And Bear Balance
Author: HPotter
Description: This is combo strategies for get a cumulative signal.

 First strategy
 This indicator plots 2/20 exponential moving average. For the Mov
 Avg X 2/20 Indicator, the EMA bar will be painted when the Alert criteria is met.

 Second strategy
    This new indicator analyzes the balance between bullish and
    bearish sentiment.
    One can cay that it is an...
PineScript code:

Pine Script™ strategy
Combo 2/20 EMA & Bull And Bear Balance
//@version=5
////////////////////////////////////////////////////////////
//    Copyright  by  HPotter  v1.0  23/05/2022
//  This  is  combo  strategies  for  get  a  cumulative  signal.
//
//  First  strategy
//  This  indicator  plots  2/20  exponential  moving  average.  For  the  Mov
//  Avg  X  2/20  Indicator,  the  EMA  bar  will  be  painted  when  the  Alert  criteria  is  met.
//
//  Second  strategy
//        This  new  indicator  analyzes  the  balance  between  bullish  and
//        bearish  sentiment.
//        One  can  cay  that  it  is  an  improved  analogue  of  Elder  Ray  indicator.
//        To  get  more  information  please  see  "Bull  And  Bear  Balance  Indicator"
//        by  Vadim  Gimelfarb.
//
//  WARNING:
//  -  For  purpose  educate  only
//  -  This  script  to  change  bars  colors.
////////////////////////////////////////////////////////////
EMA20(Length)  =>
        pos  =  0.0
        xPrice  =  close
        xXA  =  ta.ema(xPrice,  Length)
        nHH  =  math.max(high,  high[1])
        nLL  =  math.min(low,  low[1])
        nXS  =  nLL  >  xXA  or  nHH  <  xXA  ?  nLL  :  nHH
        iff_1  =  nXS  <  close[1]  ?  1  :  nz(pos[1],  0)
        pos  :=  nXS>close[1]?-1:iff_1
pos
BBB(SellLevel,BuyLevel)=>
pos=0.0
value=close<open?
close[1]>open?math.max(close-open,high-low):high-low:
close>open?
close[1]>open?math.max(close[1]-low,high-close):math.max(open-low,high-close):
high-close>close-low?
close[1]>open?math.max(close[1]-open,high-low):high-low:
high-close<close-low?
close>open?math.max(close-low,high-close):open-low:
close>open?math.max(close[1]-open,high-close):
close[1]<open?math.max(open-low,high-close):high-low

value2=close<open?
close[1]<open?math.max(high-close[1],close-low):math.max(high-open,close-low):
close>open?
close[1]>open?high-low:math.max(open-close[1],high-low):
high-close>close-low?
close[1]<open?math.max(high-close[1],close-low):high-open:
high-close<close-low?
close[1]>open?high-low:math.max(open-close,high-low):
close[1]>open?math.max(high-open,close-low):
close[1]<open?math.max(open-close,high-low):high-low
nBBB=value2-value
pos:=nBBB<SellLevel?-1:
nBBB>=BuyLevel?1:nz(pos[1],0)
pos
strategy(title='Combo2/20EMA&BullAndBearBalance',shorttitle='Combo',overlay=true)
varI1='●═════2/20EMA═════●'
Length=input.int(14,minval=1,group=I1)
varI2='●═════BullAndBearBalance═════●'
SellLevel=input.float(-15,step=0.01,group=I2)
BuyLevel=input.float(15,step=0.01,group=I2)
varmisc='●═════MISC═════●'
reverse=input.bool(false,title='Tradereverse',group=misc)
vartimePeriodHeader='●═════TimeStart═════●'
d=input.int(1,title='FromDay',minval=1,maxval=31,group=timePeriodHeader)
m=input.int(1,title='FromMonth',minval=1,maxval=12,group=timePeriodHeader)
y=input.int(2005,title='FromYear',minval=0,group=timePeriodHeader)
StartTrade=time>timestamp(y,m,d,00,00)?true:false
posEMA20=EMA20(Length)
prePosBBB=BBB(SellLevel,BuyLevel)
iff_1=posEMA20==-1andprePosBBB==-1andStartTrade?-1:0
pos=posEMA20==1andprePosBBB==1andStartTrade?1:iff_1
iff_2=reverseandpos==-1?1:pos
possig=reverseandpos==1?-1:iff_2
ifpossig==1
strategy.entry('Long',strategy.long)
ifpossig==-1
strategy.entry('Short',strategy.short)
ifpossig==0
strategy.close_all()
barcolor(possig==-1?#b50404:possig==1?#079605:#0536b3)
Expand (86 lines)
