Script Name: Combo Backtest 123 Reversal & Line Regression Intercept
Author: HPotter
Description: This is combo strategies for get a cumulative signal.

 First strategy
 This System was created from the Book "How I Tripled My Money In The
 Futures Market" by Ulf Jensen, Page 183. This is reverse type of strategies.
 The strategy buys at market, if close price is higher than the previous close
 during 2 days and the meaning of 9-days Stochastic Slow...
PineScript code:

Pine Script™ strategy
Combo Backtest 123 Reversal & Line Regression Intercept
//@version=4
////////////////////////////////////////////////////////////
//    Copyright  by  HPotter  v1.0  25/01/2021
//  This  is  combo  strategies  for  get  a  cumulative  signal.
//
//  First  strategy
//  This  System  was  created  from  the  Book  "How  I  Tripled  My  Money  In  The
//  Futures  Market"  by  Ulf  Jensen,  Page  183.  This  is  reverse  type  of  strategies.
//  The  strategy  buys  at  market,  if  close  price  is  higher  than  the  previous  close
//during2daysandthemeaningof9-daysStochasticSlowOscillatorislowerthan50.
//Thestrategysellsatmarket,ifclosepriceislowerthanthepreviouscloseprice
//during2daysandthemeaningof9-daysStochasticFastOscillatorishigherthan50.
//
//Secondstrategy
//LinearRegressionInterceptisoneoftheindicatorscalculatedbyusingthe
//LinearRegressiontechnique.LinearregressionindicatesthevalueoftheY
//(generallytheprice)whenthevalueofX(thetimeseries)is0.Linear
//RegressionInterceptisusedalongwiththeLinearRegressionSlopetocreate
//theLinearRegressionLine.TheLinearRegressionInterceptalongwiththeSlope
//createstheRegressionline.
//
//WARNING:
//-Forpurposeeducateonly
//-Thisscripttochangebarscolors.
////////////////////////////////////////////////////////////
Reversal123(Length,KSmoothing,DLength,Level)=>
vFast=sma(stoch(close,high,low,Length),KSmoothing)
vSlow=sma(vFast,DLength)
pos=0.0
pos:=iff(close[2]<close[1]andclose>close[1]andvFast<vSlowandvFast>Level,1,
iff(close[2]>close[1]andclose<close[1]andvFast>vSlowandvFast<Level,-1,nz(pos[1],0)))
pos
LRI(Length,xSeria)=>
pos=0.0
xX=Length*(Length-1)*0.5
xDivisor=xX*xX-Length*Length*(Length-1)*(2*Length-1)/6
xXY=0.0
fori=0toLength-1
xXY:=xXY+(i*xSeria[i])
xSlope=(Length*xXY-xX*sum(xSeria,Length))/xDivisor
xLRI=(sum(xSeria,Length)-xSlope*xX)/Length
pos:=iff(close>xLRI,1,
iff(close<xLRI,-1,nz(pos[1],0)))
pos
strategy(title="ComboBacktest123Reversal&LineRegressionIntercept",shorttitle="Combo",overlay=true)
line1=input(true,"----123Reversal----")
Length=input(14,minval=1)
KSmoothing=input(1,minval=1)
DLength=input(3,minval=1)
Level=input(50,minval=1)
//-------------------------
line2=input(true,"----LineRegressionIntercept----")
LengthLRI=input(14,minval=1)
xSeria=input(title="Source",type=input.source,defval=close)
reverse=input(false,title="Tradereverse")
posReversal123=Reversal123(Length,KSmoothing,DLength,Level)
posLRI=LRI(LengthLRI,xSeria)
pos=iff(posReversal123==1andposLRI==1,1,
iff(posReversal123==-1andposLRI==-1,-1,0))
possig=iff(reverseandpos==1,-1,
iff(reverseandpos==-1,1,pos))
if(possig==1)
strategy.entry("Long",strategy.long)
if(possig==-1)
strategy.entry("Short",strategy.short)
if(possig==0)
strategy.close_all()
barcolor(possig==-1?#b50404:possig==1?#079605:#0536b3)
Expand (70 lines)
