Script Name: Combo Backtest 123 Reversal & RSI based on ROC
Author: HPotter
Description: This is combo strategies for get a cumulative signal.

 First strategy
 This System was created from the Book "How I Tripled My Money In The
 Futures Market" by Ulf Jensen, Page 183. This is reverse type of strategies.
 The strategy buys at market, if close price is higher than the previous close
 during 2 days and the meaning of 9-days Stochastic Slow...
PineScript code:

Pine Script™ strategy
Combo Backtest 123 Reversal & RSI based on ROC
//@version=4
////////////////////////////////////////////////////////////
//    Copyright  by  HPotter  v1.0  17/06/2021
//  This  is  combo  strategies  for  get  a  cumulative  signal.
//
//  First  strategy
//  This  System  was  created  from  the  Book  "How  I  Tripled  My  Money  In  The
//  Futures  Market"  by  Ulf  Jensen,  Page  183.  This  is  reverse  type  of  strategies.
//  The  strategy  buysatmarket,ifclosepriceishigherthanthepreviousclose
//during2daysandthemeaningof9-daysStochasticSlowOscillatorislowerthan50.
//Thestrategysellsatmarket,ifclosepriceislowerthanthepreviouscloseprice
//during2daysandthemeaningof9-daysStochasticFastOscillatorishigherthan50.
//
//Secondstrategy
//Thisisthenew-ageindicatorwhichisversionofRSIcalculatedupon
//theRate-of-changeindicator.
//Thename"RelativeStrengthIndex"isslightlymisleadingastheRSI
//doesnotcomparetherelativestrengthoftwosecurities,butrather
//theinternalstrengthofasinglesecurity.Amoreappropriatename
//mightbe"InternalStrengthIndex."Relativestrengthchartsthatcompare
//twomarketindices,whichareoftenreferredtoasComparativeRelativeStrength.
//Andinitsturn,theRate-of-Change("ROC")indicatordisplaysthedifference
//betweenthecurrentpriceandthepricex-timeperiodsago.Thedifferencecan
//bedisplayedineitherpointsorasapercentage.TheMomentumindicatordisplays
//thesameinformation,butexpressesitasaratio.
//
//WARNING:
//-Forpurposeeducateonly
//-Thisscripttochangebarscolors.
////////////////////////////////////////////////////////////
Reversal123(Length,KSmoothing,DLength,Level)=>
vFast=sma(stoch(close,high,low,Length),KSmoothing)
vSlow=sma(vFast,DLength)
pos=0.0
pos:=iff(close[2]<close[1]andclose>close[1]andvFast<vSlowandvFast>Level,1,
iff(close[2]>close[1]andclose<close[1]andvFast>vSlowandvFast<Level,-1,nz(pos[1],0)))
pos
RSI_ROC(RSILength,ROCLength,BuyZone,SellZone)=>
pos=0.0
xPrice=close
nRes=rsi(roc(xPrice,ROCLength),RSILength)
pos:=iff(nRes<BuyZone,-1,
iff(nRes>SellZone,1,nz(pos[1],0)))
pos
strategy(title="ComboBacktest123Reversal&RSIbasedonROC",shorttitle="Combo",overlay=true)
line1=input(true,"----123Reversal----")
Length=input(14,minval=1)
KSmoothing=input(1,minval=1)
DLength=input(3,minval=1)
Level=input(50,minval=1)
//-------------------------
line2=input(true,"----RSIbasedonROC----")
RSILength=input(20,minval=1)
ROCLength=input(20,minval=1)
BuyZone=input(30,minval=1)
SellZone=input(70,minval=1)
reverse=input(false,title="Tradereverse")
posReversal123=Reversal123(Length,KSmoothing,DLength,Level)
posRSI_ROC=RSI_ROC(RSILength,ROCLength,BuyZone,SellZone)
pos=iff(posReversal123==1andposRSI_ROC==1,1,
iff(posReversal123==-1andposRSI_ROC==-1,-1,0))
possig=iff(reverseandpos==1,-1,
iff(reverseandpos==-1,1,pos))
if(possig==1)
strategy.entry("Long",strategy.long)
if(possig==-1)
strategy.entry("Short",strategy.short)
if(possig==0)
strategy.close_all()
barcolor(possig==-1?#b50404:possig==1?#079605:#0536b3)
Expand (73 lines)
