Script Name: Combo Backtest 123 Reversal & Perfomance index
Author: HPotter
Description: This is combo strategies for get a cumulative signal.

 First strategy
 This System was created from the Book "How I Tripled My Money In The
 Futures Market" by Ulf Jensen, Page 183. This is reverse type of strategies.
 The strategy buys at market, if close price is higher than the previous close
 during 2 days and the meaning of 9-days Stochastic Slow...
PineScript code:

Pine Script™ strategy
Combo Backtest 123 Reversal & Perfomance index
//@version=4
////////////////////////////////////////////////////////////
//    Copyright  by  HPotter  v1.0  15/04/2021
//  This  is  combo  strategies  for  get  a  cumulative  signal.
//
//  First  strategy
//  This  System  was  created  from  the  Book  "How  I  Tripled  My  Money  In  The
//  Futures  Market"  by  Ulf  Jensen,  Page  183.  This  is  reverse  type  of  strategies.
//  The  strategy  buys  at  market,  if  close  price  is  higher  than  the  previous  close
//  during  2  days  and  the  meaning  of  9-days  Stochastic  Slow  Oscillator  is  lower  than  50.
//  The  strategy  sells  at  market,  if  close  price  is  lower  than  the  previous  close  price
//  during  2  days  and  the  meaning  of  9-days  Stochastic  Fast  Oscillator  is  higher  than  50.
//
//  Second  strategy
//  The  Performance  indicator  or  a  more  familiar  term,  KPI  (key  performance  indicator),
//  is  an  industry  term  that  measures  the  performance.  Generally  used  by  organizations,
//  they  determine  whether  the  company  is  successful  or  not,  and  the  degree  of  success.
//  It  is  used  on  a  business’  different  levels,  to  quantify  theprogressorregressofa
//department,ofanemployeeorevenofacertainprogramoractivity.Foramanager
//it’sextremelyimportanttodeterminewhichKPIsarerelevantforhisactivity,and
//whatisimportantalmostalwaysdependsonwhichdepartmenthewantstomeasurethe
//performancefor.Sotheindicatorssetforthefinancialteamwillbedifferentthan
//theonesforthemarketingdepartmentandsoon.
//
//SimilartotheKPIscompaniesusetomeasuretheirperformanceonamonthly,quarterly
//andyearlybasis,thestockmarketmakesuseofaperformanceindicatoraswell,although
//onthemarket,theperformanceindexiscalculatedonadailybasis.Thestockmarket
//performanceindicatesthedirectionofthestockmarketasawhole,orofaspecificstock
//andgivestradersanoverallimpressionoverthefuturesecurityprices,helpingthemdecide
//thebestmove.Achangeintheindicatorgivesinformationaboutfuturetrendsastockcould
//adopt,informationaboutasectororevenonthewholeeconomy.Thefinancialsectoristhe
//mostrelevantdepartmentoftheeconomyandtheindicatorsprovideinformationonitsoverall
//health,sowhenastockpricemovesupwards,theindicatorsareasignalofgoodnews.Onthe
//otherhand,ifthepriceofaparticularstockdecreases,thatisbecausebadnewsaboutits
//performanceareoutandtheygeneratenegativesignalstothemarket,causingthepricetogo
//downwards.Onecouldstatethatthemovementofthesecuritypricesandconsequently,themovement
//oftheindicatorsareanoverallevaluationofacountry’seconomictrend.
//
//WARNING:
//-Forpurposeeducateonly
//-Thisscripttochangebarscolors.
////////////////////////////////////////////////////////////
Reversal123(Length,KSmoothing,DLength,Level)=>
vFast=sma(stoch(close,high,low,Length),KSmoothing)
vSlow=sma(vFast,DLength)
pos=0.0
pos:=iff(close[2]<close[1]andclose>close[1]andvFast<vSlowandvFast>Level,1,
iff(close[2]>close[1]andclose<close[1]andvFast>vSlowandvFast<Level,-1,nz(pos[1],0)))
pos
PI(Period)=>
pos=0.0
xKPI=(close-close[Period])*100/close[Period]
pos:=iff(xKPI>0,1,
iff(xKPI<0,-1,nz(pos[1],0)))
pos
strategy(title="ComboBacktest123Reversal&Perfomanceindex",shorttitle="Combo",overlay=true)
line1=input(true,"----123Reversal----")
Length=input(14,minval=1)
KSmoothing=input(1,minval=1)
DLength=input(3,minval=1)
Level=input(50,minval=1)
//-------------------------
line2=input(true,"----Perfomanceindex----")
Period=input(14,minval=1)
reverse=input(false,title="Tradereverse")
posReversal123=Reversal123(Length,KSmoothing,DLength,Level)
posPI=PI(Period)
pos=iff(posReversal123==1andposPI==1,1,
iff(posReversal123==-1andposPI==-1,-1,0))
possig=iff(reverseandpos==1,-1,
iff(reverseandpos==-1,1,pos))
if(possig==1)
strategy.entry("Long",strategy.long)
if(possig==-1)
strategy.entry("Short",strategy.short)
if(possig==0)
strategy.close_all()
barcolor(possig==-1?#b50404:possig==1?#079605:#0536b3)
Expand (81 lines)
