Script Name: Combo Backtest 123 Reversal & Inertia Strategy
Author: HPotter
Description: This is combo strategies for get a cumulative signal.

 First strategy
 This System was created from the Book "How I Tripled My Money In The
 Futures Market" by Ulf Jensen, Page 183. This is reverse type of strategies.
 The strategy buys at market, if close price is higher than the previous close
 during 2 days and the meaning of 9-days Stochastic Slow...
PineScript code:

Pine Script™ strategy
Combo Backtest 123 Reversal & Inertia Strategy
//@version=4
////////////////////////////////////////////////////////////
//    Copyright  by  HPotter  v1.0  27/11/2020
//  This  is  combo  strategies  for  get  a  cumulative  signal.
//
//  First  strategy
//  This  System  was  created  from  the  Book  "How  I  Tripled  My  Money  In  The
//  Futures  Market"  by  Ulf  Jensen,  Page  183.  This  is  reverse  type  of  strategies.
//  The  strategy  buys  at  market,  if  close  price  is  higher  than  the  previous  close
//  during  2  days  and  the  meaning  of  9-days  Stochastic  Slow  Oscillator  is  lower  than  50.
//  The  strategy  sells  at  market,  if  close  price  is  lower  than  the  previous  close  price
//  during  2  days  and  the  meaning  of  9-days  Stochastic  Fast  Oscillator  is  higher  than  50.
//
//  Second  strategy
//  The  inertia  indicator  measures  the  market,  stock  or  currency  pair  momentum  and
//  trend  by  measuring  the  security  smoothed  RVI  (Relative  Volatility  Index).
//  The  RVI  is  a  technical  indicator  that  estimates  the  general  direction  of  the
//  volatility  of  an  asset.
//  The  inertia  indicator  returns  a  value  that  is  comprised  between  0  and  100.
//  Positiveinertiaoccurswhentheindicatorvalueishigherthan50.Aslongas
//theinertiavalueisabove50,thelong-termtrendofthesecurityisup.Theinertia
//isnegativewhenitsvalueislowerthan50,inthiscasethelong-termtrendis
//downandshouldstaydowniftheinertiastaysbelow50.
//
//YoucanchangelongtoshortintheInputSettings
//Please,useitonlyforlearningorpapertrading.Donotforrealtrading.
//
//WARNING:
//-Forpurposeeducateonly
//-Thisscripttochangebarscolors.
////////////////////////////////////////////////////////////
Reversal123(Length,KSmoothing,DLength,Level)=>
vFast=sma(stoch(close,high,low,Length),KSmoothing)
vSlow=sma(vFast,DLength)
pos=0.0
pos:=iff(close[2]<close[1]andclose>close[1]andvFast<vSlowandvFast>Level,1,
iff(close[2]>close[1]andclose<close[1]andvFast>vSlowandvFast<Level,-1,nz(pos[1],0)))
pos
Inertia(Period,Smooth)=>
pos=0.0
nU=0.0
nD=0.0
xPrice=close
StdDev=stdev(xPrice,Period)
d=iff(close>close[1],0,StdDev)
u=iff(close>close[1],StdDev,0)
nU:=(13*nz(nU[1],0)+u)/14
nD:=(13*nz(nD[1],0)+d)/14
nRVI=100*nU/(nU+nD)
nRes=ema(nRVI,Smooth)
pos:=iff(nRes>50,1,
iff(nRes<50,-1,nz(pos[1],0)))
pos
strategy(title="ComboBacktest123Reversal&InertiaStrategy",shorttitle="Combo",overlay=true)
Length=input(14,minval=1)
KSmoothing=input(1,minval=1)
DLength=input(3,minval=1)
Level=input(50,minval=1)
//-------------------------
Period=input(10,minval=1)
Smooth=input(14,minval=1)
reverse=input(false,title="Tradereverse")
posReversal123=Reversal123(Length,KSmoothing,DLength,Level)
posInertia=Inertia(Period,Smooth)
pos=iff(posReversal123==1andposInertia==1,1,
iff(posReversal123==-1andposInertia==-1,-1,0))
possig=iff(reverseandpos==1,-1,
iff(reverseandpos==-1,1,pos))
if(possig==1)
strategy.entry("Long",strategy.long)
if(possig==-1)
strategy.entry("Short",strategy.short)
if(possig==0)
strategy.close_all()
barcolor(possig==-1?#b50404:possig==1?#079605:#0536b3)
Expand (77 lines)
