Script Name: Combo Backtest 123 Reversal & Qstick Indicator
Author: HPotter
Description: This is combo strategies for get a cumulative signal.

 First strategy
 This System was created from the Book "How I Tripled My Money In The
 Futures Market" by Ulf Jensen, Page 183. This is reverse type of strategies.
 The strategy buys at market, if close price is higher than the previous close
 during 2 days and the meaning of 9-days Stochastic Slow...
PineScript code:

Pine Script™ strategy
Combo Backtest 123 Reversal & Qstick Indicator
//@version=4
////////////////////////////////////////////////////////////
//    Copyright  by  HPotter  v1.0  24/05/2021
//  This  is  combo  strategies  for  get  a  cumulative  signal.
//
//  First  strategy
//  This  System  was  created  from  the  Book  "How  I  Tripled  My  Money  In  The
//  Futures  Market"  by  Ulf  Jensen,  Page  183.  This  is  reverse  type  of  strategies.
//  The  strategy  buys  at  market,  if  close  price  is  higher  than  the  previous  close
//  during  2  days  and  the  meaning  of  9-days  Stochastic  Slow  Oscillator  is  lower  than  50.
//  The  strategy  sells  at  market,  if  close  price  is  lower  than  the  previous  close  price
//  during  2  days  and  the  meaning  of  9-days  Stochastic  Fast  Oscillator  is  higher  than  50.
//
//  Second  strategy
//  A  technical  indicator  developed  by  Tushar  Chande  to  numerically  identify
//  trends  in  candlestick  charting.  It  is  calculated  bytakingan'n'period
//movingaverageofthedifferencebetweentheopenandclosingprices.A
//Qstickvaluegreaterthanzeromeansthatthemajorityofthelast'n'days
//havebeenup,indicatingthatbuyingpressurehasbeenincreasing.
//TransactionsignalscomefromwhentheQstickindicatorcrossesthroughthe
//zeroline.Crossingabovezeroisusedastheentrysignalbecauseitisindicating
//thatbuyingpressureisincreasing,whilesellsignalscomefromtheindicator
//crossingdownthroughzero.Inaddition,an'n'periodmovingaverageoftheQstick
//valuescanbedrawntoactasasignalline.Transactionsignalsarethengenerated
//whentheQstickvaluecrossesthroughthetriggerline.
//
//WARNING:
//-Forpurposeeducateonly
//-Thisscripttochangebarscolors.
////////////////////////////////////////////////////////////
Reversal123(Length,KSmoothing,DLength,Level)=>
vFast=sma(stoch(close,high,low,Length),KSmoothing)
vSlow=sma(vFast,DLength)
pos=0.0
pos:=iff(close[2]<close[1]andclose>close[1]andvFast<vSlowandvFast>Level,1,
iff(close[2]>close[1]andclose<close[1]andvFast>vSlowandvFast<Level,-1,nz(pos[1],0)))
pos
Qstick(Length)=>
pos=0.0
xR=close-open
xQstick=sma(xR,Length)
pos:=iff(xQstick>0,1,
iff(xQstick<0,-1,nz(pos[1],0)))
pos
strategy(title="ComboBacktest123Reversal&QstickIndicator",shorttitle="Combo",overlay=true)
line1=input(true,"----123Reversal----")
Length=input(14,minval=1)
KSmoothing=input(1,minval=1)
DLength=input(3,minval=1)
Level=input(50,minval=1)
//-------------------------
line2=input(true,"----QstickIndicator----")
LengthQ=input(14,minval=1)
reverse=input(false,title="Tradereverse")
posReversal123=Reversal123(Length,KSmoothing,DLength,Level)
posQstick=Qstick(LengthQ)
pos=iff(posReversal123==1andposQstick==1,1,
iff(posReversal123==-1andposQstick==-1,-1,0))
possig=iff(reverseandpos==1,-1,
iff(reverseandpos==-1,1,pos))
if(possig==1)
strategy.entry("Long",strategy.long)
if(possig==-1)
strategy.entry("Short",strategy.short)
if(possig==0)
strategy.close_all()
barcolor(possig==-1?#b50404:possig==1?#079605:#0536b3)
Expand (70 lines)
