Script Name: Combo 2-20 EMA & Bill  Awesome Oscillator (AC)
Author: HPotter
Description: This is combo strategies for get a cumulative signal.

 First strategy
 This indicator plots 2/20 exponential moving average. For the Mov
 Avg X 2/20 Indicator, the EMA bar will be painted when the Alert criteria is met.

 Second strategy
   This indicator plots the oscillator as a histogram where blue denotes
    periods suited for buying and red . for...
PineScript code:

Pine Script™ strategy
Combo 2/20 EMA & Bill Awesome Oscillator (AC)
//@version=5
////////////////////////////////////////////////////////////
//    Copyright  by  HPotter  v1.0  27/04/2022
//  This  is  combo  strategies  for  get  a  cumulative  signal.
//
//  First  strategy
//  This  indicator  plots  2/20  exponential  moving  average.  For  the  Mov
//  Avg  X  2/20  Indicator,  the  EMA  bar  will  be  painted  when  the  Alert  criteria  is  met.
//
//  Second  strategy
//        This  indicator  plots  the  oscillator  as  a  histogram  where  blue  denotes
//        periods  suited  for  buying  and  red  .  for  selling.  If  the  current  value
//        of  AO  (Awesome  Oscillator)  is  above  previous,  the  period  is  considered
//        suited  for  buying  and  the  period  is  marked  blue.  If  the  AO  value  is  not
//        above  previous,  the  period  is  considered  suited  for  selling  and  the
//        indicator  marks  it  as  red.
//
//  WARNING:
//  -  For  purpose  educate  only
//  -  This  script  to  change  bars  colors.
////////////////////////////////////////////////////////////
EMA20(Length)  =>
        pos  =  0.0
        xPrice  =  close
        xXA  =  ta.ema(xPrice,  Length)
        nHH  =  math.max(high,  high[1])
        nLL  =  math.min(low,  low[1])
        nXS  =  nLL  >  xXA  or  nHH  <  xXA  ?  nLL  :  nHH
        iff_1  =  nXS  <  close[1]  ?  1  :  nz(pos[1],  0)
        pos  :=  nXS  >  close[1]  ?  -1  :  iff_1
        pos
AC(nLengthSlow,nLengthFast,nLengthMA,nLengthEMA,nLengthWMA,bShowWMA,bShowMA,bShowEMA)  =>
        pos  =  0.0
        xSMA1_hl2  =  ta.sma(hl2,  nLengthFast)
        xSMA2_hl2  =  ta.sma(hl2,  nLengthSlow)
        xSMA1_SMA2  =  xSMA1_hl2  -  xSMA2_hl2
        xSMA_hl2  =  ta.sma(xSMA1_SMA2,  nLengthFast)
        nRes  =    xSMA1_SMA2  -  xSMA_hl2
        xResWMA  =  ta.wma(nRes,  nLengthWMA)
        xResMA  =  ta.sma(nRes,  nLengthMA)
        xResEMA  =  ta.ema(nRes,  nLengthEMA)
        xSignalSeries  =  bShowWMA  ?  xResWMA  :
                                          bShowMA  ?  xResMA  :
                                            bShowEMA  ?  xResEMA  :  na
        pos  :=    xSignalSeries[2]  <  0  and  xSignalSeries[1]  >  0?  1:
                          xSignalSeries[2]  >  0  and  xSignalSeries[1]  <  0  ?  -1  :  nz(pos[1],  0)
        pos
strategy(title='Combo  2/20  EMA  &  Bill    Awesome  Oscillator  (AC)',  shorttitle='Combo',  overlay=true)
var  I1  =  '●═════  2/20  EMA  ═════●'
Length  =  input.int(14,  minval=1,  group=I1)
var  I2  =  '●═════    Awesome  Oscillator  (AC)  ═════●'
nLengthSlow  =  input.int(34,  minval=1,  title="Length  Slow",  group=I2)
nLengthFast  =  input.int(5,  minval=1,  title="Length  Fast",  group=I2)
nLengthMA  =  input.int(15,  minval=1,  title="MA",  group=I2)
nLengthEMA  =  input.int(15,  minval=1,  title="EMA",  group=I2)
nLengthWMA  =  input.int(15,  minval=1,  title="WMA",  group=I2)
bShowWMA  =  input.bool(  defval=true,  title="trading  WMA",  group=I2)
bShowMA  =  input.bool(  defval=false,  title="trading  MA",  group=I2)
bShowEMA  =  input.bool(  defval=false,  title="trading  EMA",  group=I2)
var  misc  =  '●═════  MISC  ═════●'
reverse  =  input.bool(false,  title='Trade  reverse',  group=misc)
var  timePeriodHeader  =  '●═════  Time  Start  ═════●'
d  =  input.int(1,  title='From  Day',  minval=1,  maxval=31,  group=timePeriodHeader)
m  =  input.int(1,  title='From  Month',  minval=1,  maxval=12,  group=timePeriodHeader)
y  =  input.int(2005,  title='From  Year',  minval=0,  group=timePeriodHeader)
StartTrade  =time>timestamp(y,m,d,00,00)?true:false
posEMA20=EMA20(Length)
prePosAC=AC(nLengthSlow,nLengthFast,nLengthMA,nLengthEMA,nLengthWMA,bShowWMA,bShowMA,bShowEMA)
iff_1=posEMA20==-1andprePosAC==-1andStartTrade?-1:0
pos=posEMA20==1andprePosAC==1andStartTrade?1:iff_1
iff_2=reverseandpos==-1?1:pos
possig=reverseandpos==1?-1:iff_2
ifpossig==1
strategy.entry('Long',strategy.long)
ifpossig==-1
strategy.entry('Short',strategy.short)
ifpossig==0
strategy.close_all()
barcolor(possig==-1?#b50404:possig==1?#079605:#0536b3)
Expand (82 lines)
