Script Name: Combination Parabolic MA-IIR-ALMA Strategy, and other goodies
Author: SnorkelSteve
Description: Okay, so this is a lot. It started mostly with me combining indicators and looking for ideal entry criteria.

It is also a collection of conditions, whether used or unused, for my current chosen "best" strategy. It is currently set how I like it, but it has changed with time, and will continue to do so. Within, there are variables that are unused, but offer some...
PineScript code:

Pine Script™ strategy
Combination Parabolic MA/IIR/ALMA Strategy, and other goodies
//The  plotchar  UP/DOWN  Arrows    is  the  crossover  of  the  fastest  MA  and  fastest  IIR  MAs
//
//The  dots  at  the  bottom  are  the  two  simple  averages  crossing  over
//SupertrendMA_strategy
//The  count  over/under  the  candles  is  the  count  of  bars  that  the  SMAs  on  their
//respective  resolution  are  fanning  out.
//
//The  colored  background  indicates  a  squeeze,  lime=kinda  tight  :  green=very  tight  squeeze.    based  on  the  3  IIRs
//
//To  answer  my  own  question  in  a  forum,  looking  at  the  code,  i  couldn't  figure  out  how  to  get  it  from  another  timeframe
//and  run  the  same  calculations  with  the  same  results.    My  answer  in  the  end  was  to  scale  the  chosen  MA  length
//in  the  corresponding  CurrentPeriod/ChosenMAPeriod  proportion.    This  results  in  the  same  line  in  the  same  place  when  browsing  through  the
//different  time  resolutions.    Somebody  might  find  this  invaluable
//
//The  counts  are  for  MA's  fanning  out,  or  going  parabolic.    Theres  IIRs,  Almas,  one  done  of  the  other.    A  lot.
//The  arrows  above  and  below  bars  are  from  standard  RSI  numbers  for  OB/OS
//
//The  IIRs  changes  color  depending  on  their  slope,  which  can  be  referenced  easily  with  a  variable.
//
//The  backgrond  on  a  bar-by-bar  basis  is  colored  when  2  sets  of  moving  averages  are  in  a  squeeze,  aka
//when  price  is  consolidating.
//
//This  aims  to  help  the  trader  combine  conditions  and  entry  criteria  of  the  trade  and  explore  these  options  visually.
//They  detail  things  from  all  time-frames  on  the  current  one.    I  prefer  it  because  of  the  fractal  nature  of  price-action,  both  large  and  small,
//either  yesterday  or  last  year.    For  best  results,  go  long  in  short-term  trades  when  the  long-term  trend  is  also  up.
//and  other  profitable  insights.    This  is  also  a  great  example  of  an  automation  algorith.
//
//The  pretty  ribbon  is  my  script  called  'Trading  With  Colors'.  Use  them  together  for  fanciest  results.    55/233  is  my  Fib  Cross  (golden/death)    Compare  it  to  the  classic  50/200  if
//you  get  bored.    I  believe  it  simply  works  better,  at  least  for  Crypto.
//
//Evidently,  I  am  a  day-trader.    But  this  yields  higher  profits  on  larger  time-frames  anyways,  so  do  play  around  with  it.  Find  what  works  for  you.
//Thanks  and  credit  for  code  snippets  goes  to:
//matryskowal
//ChrisMoody,  probably  twice
//Alex  Orekhov  (everget)
//author=LucF  and  midtownsk8rguy,  for  PineCoders
//If  you  use  code  from  this,  real  quick  search  for  perhaps  the  original  and  give  them  a  shoutout  too.    I  may  have  missed  something
//Author:  Sean  Duffy
//@version=4
strategy(title  =  "Combination  Parabolic  MA/IIR/ALMA  Strategy",
                  shorttitle  =  "MA-QuickE",
                  overlay  =  true,
                  backtest_fill_limits_assumption  =  0,
                  default_qty_type  =  strategy.cash,
                  default_qty_value  =  1000,
                  initial_capital  =  1000,
                  currency  =  currency.USD,
                  linktoseries  =  true)
                //    calc_on_order_fills  =  true,
                //    calc_on_every_tick  =  true,
//  Input  Variables
showFIBMAs  =  input(false,  type=input.bool,  title="═══════════════  Show  Fibby  MAs  ═══════════════")
maRes  =  input(960,  type=input.integer,  title="MA-Cross  Resolution")
mal1  =  input(8,  type=input.integer,  title="MA#1  Length")
mal2  =  input(13,  type=input.integer,  title="MA#2  Length")
mal3  =  input(34,  type=input.integer,  title="MA#3  Length")
loosePercentClose  =  input(1.1,  type=input.float,  title="SMA  LooseSqueeze  Percent")
showIIRs  =  input(false,  type=input.bool,  title="═══════════════════  Show  IIRs  ═══════════════════")
iirRes  =  input(60,  type=input.integer,  title="IIR  Resolution")
percentClose  =  input(title="IIR  Squeeze  PercentClose",  type=input.float,  defval=.8)
iirlength1  =  input(title="IIR  Length  1",  type=input.integer,  defval=34)
iirlength2  =  input(title="IIR  Length  2",  type=input.integer,  defval=144)//input(title="ATR  Period",  type=input.integer,  defval=1)
iirlength3  =  input(title="IIR  Length  3",  type=input.integer,  defval=720)//input(title="ATR  Period",  type=input.integer,  defval=1)
showIIR1  =  input(true,  type=input.bool,  title="Show  IIR1")
showIIR2  =  input(true,  type=input.bool,  title="Show  IIR2")
showIIR3  =  input(true,  type=input.bool,  title="Show  IIR3")
showCounts  =  input(true,  type=input.bool,  title="═════════════  Show  Parabolic  MA  Counts  ════════════")
showSignals  =  input(false,  type=input.bool,  title="══════════════  Show  Buy/Sell  Signals  ══════════════")
showBackground  =  input(false,  type=input.bool,  title="══════════════  Show  Background  Colors  ══════════════")
//runStrategy  =  input(true,  type=input.bool,  title="══════════════  Run  Strategy    ══════════════")
debug  =  input(false,  type=input.bool,  title="══════════════  Show  Debug  ══════════════")
runStrat  =  input(false,  type=input.bool,  title="══════════════  Run  Strategy  ══════════════")
barLookbackPeriod  =  input(title="══  Bar  Lookback  Period  ══",  type=input.integer,  defval=5)
percentageLookbackPeriod  =  input(title="══  Percentage  Lookback  Period  ══",  type=input.integer,  defval=1)
bullcolor  =  color.green
bearcolor  =  color.red
color  bgcolor  =  na
var  bool  slope1Green  =  na
var  bool  slope2Green  =  na
var  bool  slope3Green  =  na
var  bool  buySignal  =  na
var  bool  sellSignal  =  na
var  bool  bigbuySignal  =  na
var  bool  bigsellSignal  =  na
bool  smbuySignal  =  false
bool  smsellSignal  =  false
var  bool  insqueeze  =  na
var  bool  intightsqueeze  =  na
var  bool  infastsqueeze  =  na
var  bool  awaitingEntryIn  =  false
//  My  counting  variables
var  int  count1  =  0
var  float  madist1  =  0
var  int  count2  =  0
var  float  madist2  =  0
var  int  sinceSmSignal  =  0
var  entryPrice  =  0.0
var  entryBarIndex  =  0
var  stopLossPrice  =  0.0
//  var  updatedEntryPrice  =  0.0
//  var  alertOpenPosition  =  false
//  var  alertClosePosition  =  false
//  var  label  stopLossPriceLabel  =  na
//  var  line  stopLossPriceLine  =  na
positionType  =  "LONG"  //  Strategy  type,  and  the  only  current  option
hasOpenPosition  =  strategy.opentrades  !=  0
hasNoOpenPosition  =  strategy.opentrades  ==  0
strategyClose()  =>
        if  (hasOpenPosition  and  runStrat)
                if  positionType  ==  "LONG"
                        strategy.close("LONG",  when=true)
                else
                        strategy.close("SHORT",  when=true)
strategyOpen()  =>
        if  (hasNoOpenPosition  and  runStrat)
                if  positionType  ==  "LONG"
                        strategy.entry("LONG",  strategy.long,  when=true)
                else
                        strategy.entry("SHORT",  strategy.short,  when=true)
checkEntry()  =>
        buysignal  =  false
        if  (hasNoOpenPosition)
                strategyOpen()
                buysignal  :=  true
        //  if  (slope1Green  and  (trend1Green  or  trend2Green)  and  awaitingEntryIn  and  hasNoOpenPosition)
        //          strategyOpen()
        //  buysignal:=true
buysignal
checkExit()=>
sellsignal=false
//if(trend1Green==falseandtrend2Green==false)//tolaterhavequickerexitstrategy
//sellsignal:=true
//strategyClose()
if(hasOpenPosition)
sellsignal:=true
strategyClose()
sellsignal
multiplier(_adjRes,_adjLength)=>//returnsadjustedlengthbasedonchosen/currentTF
multiplier=_adjRes/timeframe.multiplier
adjLength=(round(_adjLength*multiplier)>1000?99:round(_adjLength*multiplier))

//resetthevarvariablesbeforenewcalculations
buySignal:=false
sellSignal:=false
smbuySignal:=false
smsellSignal:=false
bigbuySignal:=false
bigsellSignal:=false
ma1=sma(close,multiplier(maRes,mal1))
ma2=sma(close,multiplier(maRes,mal2))
ma3=sma(close,multiplier(maRes,mal3))
madist1:=abs(ma1-ma2)
madist2:=abs(ma1-ma3)//checkifMA'sarefanning/goingparabolic
if(ma1>=ma2andma2>=ma3andmadist1[0]>madist1[1])//andabs(dataB-dataC>=madist2)//dataAmustbehigherthanb,anddistancebetweengaining,samewithC
count1:=count1+1
else
count1:=0
if(ma1<=ma2andma2<=ma3andmadist1[0]>madist1[1])//<=madist2anddataB<=dataC)//andabs(dataB-dataC>=madist2)//dataAmustbehigherthanb,anddistancebetweengaining,samewithC
count2:=count2+1
else
count2:=0
crossoverAB=crossover(ma1,ma2)
crossunderAB=crossunder(ma1,ma2)
plot(showFIBMAs?ma1:na,linewidth=3)
plot(showFIBMAs?ma2:na)
plot(showFIBMAs?ma3:na)
//FastSqueeseCheckWORKINPROGRESS
//
floatsinglePercent=close/100
ifmax(madist1,madist2)<=singlePercent*loosePercentClose
bgcolor:=color.yellow
infastsqueeze:=true
else
infastsqueeze:=false
//IIRMOVINGAVERAGE
f(a)=>a[0]//fixesmutableerror
iirma(iirlength,iirsrc)=>
cf=2*tan(2*3.14159*(1/iirlength)/2)
a0=8+8*cf+4*pow(cf,2)+pow(cf,3)
a1=-24-8*cf+4*pow(cf,2)+3*pow(cf,3)
a2=24-8*cf-4*pow(cf,2)+3*pow(cf,3)
a3=-8+8*cf-4*pow(cf,2)+pow(cf,3)
//----
c=pow(cf,3)/a0
d0=-a1/a0
d1=-a2/a0
d2=-a3/a0
//----
out=0.
out:=nz(c*(iirsrc+iirsrc[3])+3*c*(iirsrc[1]+iirsrc[2])+d0*out[1]+d1*out[2]+d2*out[3],iirsrc)
f(out)
iirma1=iirma(multiplier(iirRes,iirlength1),close)
iirma2=iirma(multiplier(iirRes,iirlength2),close)
iirma3=iirma(multiplier(iirRes,iirlength3),close)
//adjustslengthforcurrentresolutionnow,lengthislengthened/shortenedaccordingly,upholdingexactplacementoflines
//iirmaD1=security(syminfo.tickerid,tostring(iirRes),iirma1,barmerge.gaps_on,barmerge.lookahead_on)
//iirmaD2=security(syminfo.tickerid,tostring(iirRes),iirma2,barmerge.gaps_on,barmerge.lookahead_on)
//iirmaD3=security(syminfo.tickerid,tostring(iirRes),iirma3,barmerge.gaps_on,barmerge.lookahead_on)
slope1color=slope1Green?color.lime:color.blue
slope2color=slope2Green?color.lime:color.blue
slope3color=slope3Green?color.lime:color.blue
plot(showIIR1andshowIIRs?iirma1:na,title="IIR1",color=slope1color,linewidth=2,transp=30)
plot(showIIR2andshowIIRs?iirma2:na,title="IIR2",color=slope2color,linewidth=3,transp=30)
plot(showIIR3andshowIIRs?iirma3:na,title="IIR3",color=slope3color,linewidth=4,transp=30)
//checksslopeofIIRstocreateabooleanvariableandandcoloritdifferently
if(iirma1[0]>=iirma1[1])
slope1Green:=true
else
slope1Green:=false
if(iirma2[0]>=iirma2[1])
slope2Green:=true
else
slope2Green:=false
if(iirma3[0]>=iirma3[1])
slope3Green:=true
else
slope3Green:=false
//calculatespacebetweenIIRsandthenifthepricejumpsaboveboth
//floatsinglePercent=close/100//=asinglepercent
varfloatdistIIR1=na
varfloatdistIIR2=na
distIIR1:=abs(iirma1-iirma2)
distIIR2:=abs(iirma1-iirma3)
if(distIIR1[0]<percentClose*singlePercentandclose[0]>=iirma1[0])
ifclose[0]>=iirma2[0]andclose[0]>=iirma3[0]
bgcolor:=color.green
insqueeze:=true
intightsqueeze:=true
else
bgcolor:=color.lime
insqueeze:=true
intightsqueeze:=false
else
insqueeze:=false
intightsqueeze:=false
//if(true)//sinceSmSignal>0)//cuttingdownonfastestMAsnoise
//sinceSmSignal:=sinceSmSignal+1
//if(crossoverAB)
////checkEntry()
////smbuySignal:=true
//sinceSmSignal:=0
//if(crossunderAB)//andallNOTgreennot(slope1Greenandslope2Greenandslope3Green)
////checkExit()
////smsellSignal:=true
//sinceSmSignal:=0
//else
//sinceSmSignal:=sinceSmSignal+1
f_draw_infopanel(_x,_y,_line,_text,_color)=>
_rep_text=""
for_l=0to_line
_rep_text:=_rep_text+"\n"
_rep_text:=_rep_text+_text
varlabel_la=na
label.delete(_la)
_la:=label.new(
x=_x,y=_y,
text=_rep_text,xloc=xloc.bar_time,yloc=yloc.price,
color=color.black,style=label.style_labelup,textcolor=_color,size=size.normal)
posx=timenow+round(change(time)*60)
posy=highest(50)
//CONSTRUCTIONZONE
//TODO:programwaytoeliminatenoiseandfalsesignals
//MAYBEDO:programittodifferentiatebetweenamovingaveragebumpandacross
//Ithinkthebestwaywouldbetocalculatethetangentline...OR
//Taketheslopeofbothgoingbackacouplebarsandifit'scloseenough,itsabounceoff
//andanexcellententrysignal
//programinquickestexit,2barsnexttoeachotherbothclosingunder,astoavoidasinglewickfrom
//promptingtoclosethetrade
//Someothertime,haveitmoveSMAupordowndependingonwhethertrendingupordown.ThenusethoseMAcrosses
//THISCHECKSTHESLOPEFROMCURRENTPRICETOBACK10BARS
checkSlope(_series)=>(_series[0]/_series[10])*100//itnowreturnsitasapercentage
doNewX=input(true,type=input.bool,title="══════════ShowmiscMACrossStrategy══════════")
//Okay,iseethisbelookinitsbestonthe15,programmingthatshiteinnow
iirX=input(55,title="IIRxLength:",type=input.integer)
iirXperiod=input(30,title="IIRxPeriod/TF:",type=input.integer)
iirX2=input(13,title="IIRx2Length:",type=input.integer)
iirX2period=input(5,title="IIRx2Period/TF:",type=input.integer)//15
almaXperiod=input(defval=55,title="AlmaofIIR1Period:",type=input.integer)
almaXalpha=input(title="AlmaAlphaValue:",defval=.8,maxval=.95,type=input.float)//dontforgettotry.99
almaXsigma=input(title="AlmaSigmaValue:",defval=500,type=input.float)
iirmaOTF=iirma(multiplier(iirXperiod,iirX),close)
iirma2OTF=iirma(multiplier(iirX2period,iirX2),close)
smaOTF=alma(iirmaOTF,almaXperiod,almaXalpha,almaXsigma)//maybedonttouch,itsprecise//ItooktheALMAoftheIIRMA,andihopethatsnotcheating;)
//Icouldhaveremovedthis.themultiplierfunctionadjuststhelengthtofitthecurrenttimeframewhiledisplayingthesame
//smaXOTF=security(syminfo.tickerid,smaXperiod,smaOTF,barmerge.gaps_on,barmerge.lookahead_on)
//iirmaXOTF=security(syminfo.tickerid,iirXperiod,iirmaOTF,barmerge.gaps_on,barmerge.lookahead_on)
//iirmaX2OTF=security(syminfo.tickerid,iirX2period,iirma2OTF,barmerge.gaps_on,barmerge.lookahead_on)
//plot(doNewX?smaOTF:na,title="FastMAX-Over:",color=color.blue,linewidth=1,transp=40)Usedforcrossover,looksnoisytho
plot(doNewX?iirmaOTF:na,title="IIRMAx:",color=color.purple,linewidth=1,transp=30)
plot(doNewX?iirma2OTF:na,title="IIRMAx:",color=color.purple,linewidth=2,transp=20)
iirma2Up=checkSlope(iirma2OTF)>0//justanotherslopeup/downvariable.
//calculatespacesbetweenaverages
distiiralma=abs(iirmaOTF-smaOTF)
crossoverFast=crossover(iirmaOTF,smaOTF)//and(iirmaOTF[1]<=smaOTF[1])
crossunderFast=crossunder(iirmaOTF,smaOTF)//and(iirmaOTF[1]>=smaOTF[1])
if(crossoverFastandiirma2Up==true)//and(count1!=0))//orclose[0]<(lowest(barLookbackPeriod)+singlePercent*3)))//mustbeatmostafewpercentupfromarecentlow.Avoidbuyinghighs:P
buySignal:=true
strategyOpen()
//if(slope1Greenandslope2Greenandslope3Greenandinfastsqueeze==false)
//checkEntry()
if(crossunderFast)
sellSignal:=true
checkExit()
//IfeellikeIdidn'tcitetheOGauthorforthispanelcorrectly.IhopeIdid,butthereareextentionsofhis/herworkinmultipleplaces.
//Icouldhavegottenitconfused.
if(debug)
f_draw_infopanel(posx,posy,18,"distiiralmafromIIR:"+tostring(distiiralma),color.lime)
//f_draw_infopanel(posx,posy,16,"distiirs:"+tostring(distiirX1),color.lime)
f_draw_infopanel(posx,posy,14,"ValueofiirmaOTF:"+tostring(iirmaOTF),color.lime)
f_draw_infopanel(posx,posy,6,"slopeX:"+tostring(abs(100-checkSlope(iirmaOTF))),color.lime)
f_draw_infopanel(posx,posy,12,"valueofsmaOTF:"+tostring(smaOTF),color.lime)
f_draw_infopanel(posx,posy,6,"slopeAlma:"+tostring(abs(100-checkSlope(smaOTF))),color.lime)
f_draw_infopanel(posx,posy,2,"slopeIIR2"+tostring(abs(100-checkSlope(iirma2OTF))),color.lime)
f_draw_infopanel(posx,posy,2,"slopeIIR2"+tostring(abs(100-checkSlope(iirma2OTF))),color.lime)
//Ikeptthisseparatebecauseitdiscludesthecalculations.Itshardtoholdatrainofthoughtwhilefishingfortherightsection
bgcolor(showBackground?bgcolor:na)
plotshape(showSignals?buySignal:na,location=location.bottom,style=shape.circle,text="",size=size.tiny,color=color.blue,transp=60)
plotshape(showSignals?sellSignal:na,location=location.bottom,style=shape.circle,text="",size=size.tiny,color=color.red,transp=60)
plotchar(showSignalsandsmbuySignal,title="smBuy",location=location.belowbar,char='↑',size=size.tiny,color=color.green,transp=0)
plotchar(showSignalsandsmsellSignal,title="smSell",location=location.abovebar,char='↓',size=size.tiny,color=color.orange,transp=0)
//cannotdisplayavariable.Canonlymatchthecounttoacorrespondingplotchar
//todisplayanon-constantvariable,usethedebugbox,whichwassokindlyofferedupbyourcommunity.
plotchar(showCountsandcount1==1,title='',char='1',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1==2,title='',char='2',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1==3,title='',char='3',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1==4,title='',char='4',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1==5,title='',char='5',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1==6,title='',char='6',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1==7,title='',char='7',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1==8,title='',char='8',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1==9,title='',char='9',location=location.belowbar,color=#2c9e2c,transp=0)
plotchar(showCountsandcount1>=10,title='',char='$',location=location.belowbar,color=#2c9e2c,transp=0)

plotchar(showCountsandcount2==1,title='',char='1',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2==2,title='',char='2',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2==3,title='',char='3',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2==4,title='',char='4',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2==5,title='',char='5',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2==6,title='',char='6',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2==7,title='',char='7',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2==8,title='',char='8',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2==9,title='',char='9',location=location.abovebar,color=#e91e63,transp=0)
plotchar(showCountsandcount2>=10,title='',char='$',location=location.abovebar,color=#e91e63,transp=0)
showRSIind=input(true,type=input.bool,title="═══════════════════ShowRSIArrows═══════════════════")
//Getuserinput
rsiSource=input(title="RSISource",type=input.source,defval=close)
rsiLength=input(title="RSILength",type=input.integer,defval=14)
rsiOverbought=input(title="RSIOverboughtLevel",type=input.integer,defval=80)
rsiOversold=input(title="RSIOversoldLevel",type=input.integer,defval=20)
//GetRSIvalue
rsiValue=rsi(rsiSource,rsiLength)
isRsiOB=rsiValue>=rsiOverbought
isRsiOS=rsiValue<=rsiOversold
//Plotsignalstochart
plotshape(isRsiOB,title="Overbought",location=location.abovebar,color=color.red,transp=0,style=shape.triangledown)
plotshape(isRsiOS,title="Oversold",location=location.belowbar,color=color.green,transp=0,style=shape.triangleup)
//resetthevarvariablesbeforenewcalculations
buySignal:=false
sellSignal:=false
smbuySignal:=false
smsellSignal:=false
bigbuySignal:=false
bigsellSignal:=false
Expand (418 lines)
