Script Name: Coral Trend Pullback Strategy (TradeIQ)
Author: kevinmck100
Description: Description:

Strategy is taken from the TradeIQ YouTube video called "I Finally Found 80% Win Rate Trading Strategy For Crypto".
Check out the full video for further details/clarification on strategy entry/exit conditions.

The default settings are exactly as TradeIQ described in his video.
However I found some better results by some tweaking settings,...
PineScript code:

Pine Script™ strategy
Coral Trend Pullback Strategy (TradeIQ)
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  kevinmck100
//  @description
//
//  Strategy  is  taken  from  the  TradeIQ  YouTube  video  called  "I  Finally  Found  80%  Win  Rate  Trading  Strategy  For  Crypto"
//  Check  out  the  full  video  for  further  details/clarification  on  strategy  entry/exit  conditions.
//
//  It  incorporates  the  following  features:
//
//            -  Risk  management:    Configurable  X%  loss  per  stop  loss
//                                                    Configurable  R:R  ratio
//
//            -  Trade  entry:            Conditions  outlines  below
//
//            -  Trade  exit:              Conditions  outlined  below
//
//            -  Backtesting:            Configurable  backtesting  range  by  date
//
//            -  Trade  drawings:      TP/SL  boxes  drawn  for  all  trades  (can  be  turned  on  and  off)
//                                                    Trade  exit  information  labels  (can  be  turned  on  and  off)
//                                                    NOTE:  Trade  drawings  will  only  be  applicable  when  using  overlay  strategies
//
//            -  Debugging:                Includes  section  with  useful  debugging  techniques
//
//  Strategy  conditions:
//
//            -  Trade  entry:            LONG:      C1:  Coral  Trend  is  bullish
//                                                                    C2:  At  least  1  candle  where  low  is  above  Coral  Trend  since  last  cross  above  Coral  Trend
//                                                                    C3:  Pullback  happens  and  price  closes  below  Coral  Trend
//                                                                    C4:  Coral  Trend  colour  remains  bullish  for  duration  of  pullback
//                                                                    C5:  After  valid  pullback,  price  then  closes  above  Coral  Trend
//                                                                    C6:  Optional  confirmation  indicators  (choose  either  C6.1  or  C6.2  or  NONE):
//                                                                            C6.1:  ADX  and  DI  (Single  indicator)
//                                                                                    C6.1.1:  Green  line  is  above  red  line
//                                                                                    C6.1.2:  Blue  line  >  20
//                                                                                    C6.1.3:  Blue  trending  up  over  last  1  candle
//                                                                            C6.2:  Absolute  Strengeh  Histogram  +  HawkEye  Volume  Indicator  (Two  indicators  combined)
//                                                                                    C6.2.1:  Absolute  Strengeh  Histogram  colour  is  blue
//                                                                                    C6.2.2:  HawkEye  Volume  Indicator  colour  is  green
//                                                    SHORT:    C1:  Coral  Trend  is  bearish
//                                                                    C2:  At  least  1  candle  where  high  is  below  Coral  Trend  since  last  cross  below  Coral  Trend
//                                                                    C3:  Pullback  happens  and  price  closes  above  Coral  Trend
//                                                                    C4:  Coral  Trend  colour  remains  bearish  for  duration  of  pullback
//                                                                C5:Aftervalidpullback,pricethenclosesbelowCoralTrend
//C6:Optionalconfirmationindicators(chooseeitherC6.1orC6.2orNONE):
//C6.1:ADXandDI(Singleindicator)
//C6.1.1:Redlineisabovegreenline
//C6.1.2:Blueline>20
//C6.1.3:Bluetrendingupoverlast1candle
//C6.2:AbsoluteStrengehHistogram+HawkEyeVolumeIndicator(Twoindicatorscombined)
//C6.2.1:AbsoluteStrengehHistogramcolourisred
//C6.2.2:HawkEyeVolumeIndicatorcolourisred
//NOTE:AlltheoptionalconfirmationindicatorscannotbeoverlayedwithCoralTrendsofeelfreetoaddeachseparatelytothechartforvisualpurposes
//
//
//-Tradeexit:StopLoss:CalculatedbyrecentswinglowoverpreviousXcandles(configurablewith"LocalHigh/LowLookback")
//TakeProfit:CalculatedfromR:Rmultiplier*StopLosssize
//
//@credits
//
//CoralTrendIndicator[LazyBear]by@LazyBear
//AbsoluteStrengthHistogram|jhby@jiehonglim
//Indicator:HawkEyeVolumeIndicatorby@LazyBear
//ADXandDIby@BeikabuOyaji
//@version=5
INITIAL_CAPITAL=1000
DEFAULT_COMMISSION=0.02
MAX_DRAWINGS=500
IS_OVERLAY=true
strategy("CoralTrendPullbackStrategy(TradeIQ)","CoralTrendPullback",overlay=IS_OVERLAY,initial_capital=INITIAL_CAPITAL,currency=currency.NONE,max_labels_count=MAX_DRAWINGS,max_boxes_count=MAX_DRAWINGS,max_lines_count=MAX_DRAWINGS,default_qty_type=strategy.cash,commission_type=strategy.commission.percent,commission_value=DEFAULT_COMMISSION)
//=============================================================================
//INPUTS
//=============================================================================
//---------------
//RiskManagement
//---------------
riskReward=input.float(1.5,"Risk:Reward        1:",group="Strategy:RiskManagement",inline="RM1",minval=0,step=0.1,tooltip="Previoushighorlow(long/shortdependant)isusedtodetermineTPlevel.'Risk:Reward'ratioisthenusedtocalculateSLbasedofprevioushigh/lowlevel.\n\nInshort,thehighertheR:Rratio,thesmallertheSLsinceTPtargetisfixedbyprevioushigh/lowpricedata.")
accountRiskPercent=input.float(1,"PortfolioRisk%        ",group="Strategy:RiskManagement",inline="RM2",minval=0,step=0.1,tooltip="PercentageofportfolioyouloseiftradehitsSL.\n\nYouthenstandtogain\nPortfolioRisk%*Risk:Reward\niftradehitsTP.")
localHlLookback=input.int(5,"LocalHigh/LowLookback   ",group="Strategy:StopLossSettings",inline="SL1",minval=1,tooltip="ThisstrategycalculatestheStopLossvaluefromtherecentlocalhigh/low.Thislookbackperioddeterminesthenumberofcandlestoincludeforthelocalhigh/low.")
//----------
//DateRange
//----------
startYear=input.int(2010,"StartDate  ",group="Strategy:DateRange",inline="DR1",minval=1900,maxval=2100)
startMonth=input.int(1,"",group="Strategy:DateRange",inline="DR1",options=[1,2,3,4,5,6,7,8,9,10,11,12])
startDate=input.int(1,"",group="Strategy:DateRange",inline="DR1",options=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])
endYear=input.int(2100,"EndDate  ",group="Strategy:DateRange",inline="DR2",minval=1900,maxval=2100)
endMonth=input.int(1,"",group="Strategy:DateRange",inline="DR2",options=[1,2,3,4,5,6,7,8,9,10,11,12])
endDate=input.int(1,"",group="Strategy:DateRange",inline="DR2",options=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])
//----------------
//DrawingSettings
//----------------
showTpSlBoxes=input.bool(true,"ShowTP/SLBoxes",group="Strategy:Drawings",inline="D1",tooltip="ShoworhideTPandSLpositionboxes.\n\nNote:TradingViewlimitsthemaximumnumberofboxesthatcanbedisplayedto500sotheymaynotappearforallpricedataundertest.")
showLabels=input.bool(false,"ShowTradeExitLabels",group="Strategy:Drawings",inline="D2",tooltip="UsefullabelstoidentifyProfit/Lossandcumulativeportfoliocapitalaftereachtradecloses.\n\nAlsonotethatTradingViewlimitsthemaxnumberof'boxes'thatcanbedisplayedonachart(max500).ThismeanswhenyoulookbackfarenoughonthechartyouwillnotseetheTP/SLboxes.Howeveryoucancheckthisoptiontoidentifywheretradesexited.")
//------------------
//IndicatorSettings
//------------------
//CoralTrend
ctSm=input.int(25,"SmoothingPeriod       ",group="LeadingIndicator:CoralTrandSettings",inline="CT1")
ctCd=input.float(0.4,"ConstantD          ",group="LeadingIndicator:CoralTrandSettings",inline="CT2",step=0.1)
//Confirmationindicatorinputs
confirmationInd=input.string("ADXandDI","EntryConfirmationMethod  ",group="ConfirmationIndicator:IndicatorSelection",inline="IS1",options=["None","ADXandDI","AbsoluteStrengthHistogram+HawkEyeVolume"],tooltip="Selectoneofthepossibleconfirmationindicator(s)whichcanbeusedtoconfirmentrysignalsfromthemainCoralTrendindicatorconditions.Seestrategyconditionstounderstandthelogicbehindeachconfirmationindicator")
//ADXandDI
adxLen=input.int(14,"ADXLength         ",group="ConfirmationIndicator:ADXandDISettings",inline="AD1")
midLine=input.int(20,"MidLine           ",group="ConfirmationIndicator:ADXandDISettings",inline="AD2",tooltip="MidlineonstandardADXandDIindicator.InthisstrategytheDImustbeabovethislineforentryconfirmation.")
//AbsoluteStrengthHistogram
ashLength=input.int(9,"PeriodofEvaluation     ",group="ConfirmationIndicator:AbsoluteStrengthHistogramSettings",inline="ASH1")
ashSmooth=input.int(6,"PeriodofSmoothing     ",group="ConfirmationIndicator:AbsoluteStrengthHistogramSettings",inline="ASH2")
ashSrc=input.source(close,"Source           ",group="ConfirmationIndicator:AbsoluteStrengthHistogramSettings",inline="ASH3")
ashMode=input.string("RSI","IndicatorMethod       ",group="ConfirmationIndicator:AbsoluteStrengthHistogramSettings",inline="ASH4",options=["RSI","STOCHASTIC","ADX"])
sahMaType=input.string("SMA","MA             ",group="ConfirmationIndicator:AbsoluteStrengthHistogramSettings",inline="ASH5",options=["ALMA","EMA","WMA","SMA","SMMA","HMA"])
ashAlmaOffset=input.float(0.85,"*ArnaudLegoux(ALMA)Offset",group="ConfirmationIndicator:AbsoluteStrengthHistogramSettings",inline="ASH6",minval=0,step=0.01)
ashAlmaSigma=input.int(6,"*ArnaudLegoux(ALMA)Sigma",group="ConfirmationIndicator:AbsoluteStrengthHistogramSettings",inline="ASH7",minval=0)
//HawkEyeVolumeIndicator
hevLength=input.int(200,"Length           ",group="ConfirmationIndicator:HawkEyeVolumeSettings",inline="HV1")
hevDivisor=input.float(1.6,"Divisor           ",group="ConfirmationIndicator:HawkEyeVolumeSettings",inline="HV2",step=0.1)
//=============================================================================
//INDICATORS
//=============================================================================
//-----------
//CoralTrend
//-----------
src=close
di=(ctSm-1.0)/2.0+1.0
c1=2/(di+1.0)
c2=1-c1
c3=3.0*(ctCd*ctCd+ctCd*ctCd*ctCd)
c4=-3.0*(2.0*ctCd*ctCd+ctCd+ctCd*ctCd*ctCd)
c5=3.0*ctCd+1.0+ctCd*ctCd*ctCd+3.0*ctCd*ctCd
varfloati1=na
varfloati2=na
varfloati3=na
varfloati4=na
varfloati5=na
varfloati6=na
i1:=c1*src+c2*nz(i1[1])
i2:=c1*i1+c2*nz(i2[1])
i3:=c1*i2+c2*nz(i3[1])
i4:=c1*i3+c2*nz(i4[1])
i5:=c1*i4+c2*nz(i5[1])
i6:=c1*i5+c2*nz(i6[1])
bfr=-ctCd*ctCd*ctCd*i6+c3*i5+c4*i4+c5*i3
bfrC=bfr>nz(bfr[1])?color.new(color.green,50):bfr<nz(bfr[1])?color.new(color.red,50):color.new(color.blue,50)
plot(bfr,"Trend",linewidth=3,style=plot.style_stepline,color=bfrC)
//----------
//ADXandDI
//----------
TrueRange=math.max(math.max(high-low,math.abs(high-nz(close[1]))),math.abs(low-nz(close[1])))
DirectionalMovementPlus=high-nz(high[1])>nz(low[1])-low?math.max(high-nz(high[1]),0):0
DirectionalMovementMinus=nz(low[1])-low>high-nz(high[1])?math.max(nz(low[1])-low,0):0
SmoothedTrueRange=0.0
SmoothedTrueRange:=nz(SmoothedTrueRange[1])-nz(SmoothedTrueRange[1])/adxLen+TrueRange
SmoothedDirectionalMovementPlus=0.0
SmoothedDirectionalMovementPlus:=nz(SmoothedDirectionalMovementPlus[1])-nz(SmoothedDirectionalMovementPlus[1])/adxLen+DirectionalMovementPlus
SmoothedDirectionalMovementMinus=0.0
SmoothedDirectionalMovementMinus:=nz(SmoothedDirectionalMovementMinus[1])-nz(SmoothedDirectionalMovementMinus[1])/adxLen+DirectionalMovementMinus
DIPlus=SmoothedDirectionalMovementPlus/SmoothedTrueRange*100
DIMinus=SmoothedDirectionalMovementMinus/SmoothedTrueRange*100
DX=math.abs(DIPlus-DIMinus)/(DIPlus+DIMinus)*100
ADX=ta.sma(DX,adxLen)
//---------------------------
//AbsoluteStrengthHistogram
//---------------------------
ashMa(ashType,ashSrc,ashLen)=>
floatresult=0
ifashType=='SMA'//Simple
result:=ta.sma(ashSrc,ashLen)
result
ifashType=='EMA'//Exponential
result:=ta.ema(ashSrc,ashLen)
result
ifashType=='WMA'//Weighted
result:=ta.wma(ashSrc,ashLen)
result
ifashType=='SMMA'//Smoothed
ashWma=ta.wma(ashSrc,ashLen)
ashSma=ta.sma(ashSrc,ashLen)
result:=na(ashWma[1])?ashSma:(ashWma[1]*(ashLen-1)+ashSrc)/ashLen
result
ifashType=='HMA'//Hull
result:=ta.wma(2*ta.wma(ashSrc,ashLen/2)-ta.wma(ashSrc,ashLen),math.round(math.sqrt(ashLen)))
result
ifashType=='ALMA'//ArnaudLegoux
result:=ta.alma(ashSrc,ashLen,ashAlmaOffset,ashAlmaSigma)
result
result
Price=ashSrc
Price1=ashMa('SMA',Price,1)
Price2=ashMa('SMA',Price[1],1)
//RSI
Bulls0=0.5*(math.abs(Price1-Price2)+Price1-Price2)
Bears0=0.5*(math.abs(Price1-Price2)-(Price1-Price2))
//STOCHASTIC
Bulls1=Price1-ta.lowest(Price1,ashLength)
Bears1=ta.highest(Price1,ashLength)-Price1
//ADX
Bulls2=0.5*(math.abs(high-high[1])+high-high[1])
Bears2=0.5*(math.abs(low[1]-low)+low[1]-low)
Bulls=ashMode=='RSI'?Bulls0:ashMode=='STOCHASTIC'?Bulls1:Bulls2
Bears=ashMode=='RSI'?Bears0:ashMode=='STOCHASTIC'?Bears1:Bears2
AvgBulls=ashMa(sahMaType,Bulls,ashLength)
AvgBears=ashMa(sahMaType,Bears,ashLength)
SmthBulls=ashMa(sahMaType,AvgBulls,ashSmooth)
SmthBears=ashMa(sahMaType,AvgBears,ashSmooth)
isTrendBullish=SmthBulls>SmthBears?true:false
//------------------------
//HawkEyeVolumeIndicator
//------------------------
hevRange1=high-low
hevRangeAvg=ta.sma(hevRange1,hevLength)
hevVolumeA=ta.sma(volume,hevLength)
hevHigh1=high[1]
hevLow1=low[1]
hevMid1=hl2[1]
hevU1=hevMid1+(hevHigh1-hevLow1)/hevDivisor
hevD1=hevMid1-(hevHigh1-hevLow1)/hevDivisor
rEnabled1=hevRange1>hevRangeAvgandclose<hevD1andvolume>hevVolumeA
rEnabled2=close<hevMid1
rEnabled=rEnabled1orrEnabled2
gEnabled1=close>hevMid1
gEnabled2=hevRange1>hevRangeAvgandclose>hevU1andvolume>hevVolumeA
gEnabled3=high>hevHigh1andhevRange1<hevRangeAvg/1.5andvolume<hevVolumeA
gEnabled4=low<hevLow1andhevRange1<hevRangeAvg/1.5andvolume>hevVolumeA
gEnabled=gEnabled1orgEnabled2orgEnabled3orgEnabled4
grEnabled1=hevRange1>hevRangeAvgandclose>hevD1andclose<hevU1andvolume>hevVolumeAandvolume<hevVolumeA*1.5andvolume>volume[1]
grEnabled2=hevRange1<hevRangeAvg/1.5andvolume<hevVolumeA/1.5
grEnabled3=close>hevD1andclose<hevU1
grEnabled=grEnabled1orgrEnabled2orgrEnabled3
//=============================================================================
//STRATEGYLOGIC
//=============================================================================
//---------
//FUNCTIONS
//---------
percentAsPoints(pcnt)=>
math.round(pcnt/100*close/syminfo.mintick)

calcStopLossPrice(pointsOffset,isLong)=>
priceOffset=pointsOffset*syminfo.mintick
ifisLong
close-priceOffset
else
close+priceOffset
calcProfitTrgtPrice(pointsOffset,isLong)=>
calcStopLossPrice(-pointsOffset,isLong)


printLabel(barIndex,msg)=>label.new(barIndex,close,msg)
printTpSlHitBox(left,right,slHit,tpHit,entryPrice,slPrice,tpPrice)=>
ifshowTpSlBoxes
box.new(left=left,top=entryPrice,right=right,bottom=slPrice,bgcolor=slHit?color.new(color.red,60):color.new(color.gray,90),border_width=0)
box.new(left=left,top=entryPrice,right=right,bottom=tpPrice,bgcolor=tpHit?color.new(color.green,60):color.new(color.gray,90),border_width=0)
line.new(x1=left,y1=entryPrice,x2=right,y2=entryPrice,color=color.new(color.yellow,20))
line.new(x1=left,y1=slPrice,x2=right,y2=slPrice,color=color.new(color.red,20))
line.new(x1=left,y1=tpPrice,x2=right,y2=tpPrice,color=color.new(color.green,20))

printTpSlNotHitBox(left,right,entryPrice,slPrice,tpPrice)=>
ifshowTpSlBoxes
box.new(left=left,top=entryPrice,right=right,bottom=slPrice,bgcolor=color.new(color.gray,90),border_width=0)
box.new(left=left,top=entryPrice,right=right,bottom=tpPrice,bgcolor=color.new(color.gray,90),border_width=0)
line.new(x1=left,y1=entryPrice,x2=right,y2=entryPrice,color=color.new(color.yellow,20))
line.new(x1=left,y1=slPrice,x2=right,y2=slPrice,color=color.new(color.red,20))
line.new(x1=left,y1=tpPrice,x2=right,y2=tpPrice,color=color.new(color.green,20))

printTradeExitLabel(x,y,posSize,entryPrice,pnl)=>
ifshowLabels
labelStr="PositionSize:"+str.tostring(math.abs(posSize),"#.##")+"\nPNL:"+str.tostring(pnl,"#.##")+"\nCapital:"+str.tostring(strategy.equity,"#.##")+"\nEntryPrice:"+str.tostring(entryPrice,"#.##")
label.new(x=x,y=y,text=labelStr,color=pnl>0?color.new(color.green,60):color.new(color.red,60),textcolor=color.white,style=label.style_label_down)
printVerticalLine(col)=>line.new(bar_index,close,bar_index,close*1.01,extend=extend.both,color=col)
//----------
//CONDITIONS
//----------
inDateRange=time>=timestamp(syminfo.timezone,startYear,startMonth,startDate,0,0)andtime<timestamp(syminfo.timezone,endYear,endMonth,endDate,0,0)
//Condition1:CoralTrendcolormatchestrenddirection(long=green,short=red)
isCoralBullish=bfr>nz(bfr[1])
isCoralBearish=bfr<nz(bfr[1])
//Condition2:Atleast1candlecompletelyabove/below(long/short)CoralTrendsincelastcrossabove/below(long/short)CoralTrend(couldpotentiallytryalsowithonlycloseabove)
sincePrePullbackBullBreakout=ta.barssince(ta.crossover(close,bfr))
sincePrePullbackBearBreakout=ta.barssince(ta.crossunder(close,bfr))
prePullbackBullBreakout=ta.barssince(low>bfrandhigh>bfr)<sincePrePullbackBullBreakout[1]
prePullbackBearBreakout=ta.barssince(low<bfrandhigh<bfr)<sincePrePullbackBearBreakout[1]
//Condition3:Pullbackclosesbelow/above(long/short)CoralTrend
barssinceBullPullbackStart=ta.barssince(ta.crossunder(close,bfr))
barssinceBearPullbackStart=ta.barssince(ta.crossover(close,bfr))
barssincePullbackStart=isCoralBullish?barssinceBullPullbackStart:isCoralBearish?barssinceBearPullbackStart:na
//Condition4:CoralTrendcolourmatchedtrenddirectionfordurationofpullback
sinceBullish=ta.barssince(ta.crossover(bfr,nz(bfr[1])))
sinceBearish=ta.barssince(ta.crossunder(bfr,nz(bfr[1])))
barssinceCoralflip=isCoralBullish?sinceBullish:isCoralBearish?sinceBearish:na
isPullbackValid=barssincePullbackStart<barssinceCoralflip
//Condition5:Aftervalidpullback,pricethenclosesabove/below(long/short)CoralTrend
entryBreakout=(isCoralBullishandta.crossover(close,bfr))or(isCoralBearishandta.crossunder(close,bfr))
//Condition6:Confirmationindicators(6.1or6.2,optionaldependingonsettings)confirmstradeentry
//6.1:ADXandDI
//6.1.1:Greenandredmatchtrend(long=(green>red),short=(red>green))
//6.1.2:Blue>20
//6.1.3:Bluetrendingupoverlast1candle
//6.2:AbsoluteStrengehHistogram+HawkEyeVolumeIndicator
//6.2.1:AbsoluteStrengehHistogramcolourmatchestrend(long=blue,short=red)
//6.2.2:HawkEyeVolumeIndicatorcolourmatchestrend(long=green,short=red)
varlongTradeConfirmed=false
varshortTradeConfirmed=false
ifconfirmationInd=="ADXandDI"
isAdxUp=ADX>ADX[1]
isAdxValid=ADX>midLineandisAdxUp
longTradeConfirmed:=DIPlus>DIMinusandisAdxValid
shortTradeConfirmed:=DIMinus>DIPlusandisAdxValid
elseifconfirmationInd=="AbsoluteStrengthHistogram+HawkEyeVolume"
isAshBullish=SmthBulls>SmthBears?true:false
isHevBullish=notgrEnabledandgEnabled?true:false
isHevBearish=notgrEnabledandrEnabled?true:false
longTradeConfirmed:=isAshBullishandisHevBullish
shortTradeConfirmed:=notisAshBullishandisHevBearish
elseifconfirmationInd=="None"
longTradeConfirmed:=true
shortTradeConfirmed:=true
//Combineallentryconditions
goLong=inDateRangeandisCoralBullishandprePullbackBullBreakoutandisPullbackValidandentryBreakoutandlongTradeConfirmed
goShort=inDateRangeandisCoralBearishandprePullbackBearBreakoutandisPullbackValidandentryBreakoutandshortTradeConfirmed
//Tradeentryandexitvariables
vartradeEntryBar=bar_index
varprofitPoints=0.
varlossPoints=0.
varslPrice=0.
vartpPrice=0.
varinLong=false
varinShort=false
varentryPrice=0.
//Entrydecisions
openLong=(goLongandnotinLong)
openShort=(goShortandnotinShort)
flippingSides=(goLongandinShort)or(goShortandinLong)
enteringTrade=openLongoropenShort
inTrade=inLongorinShort
//Exitcalculations
entryPrice:=close
longSlPrice=ta.lowest(localHlLookback)
shortSlPrice=ta.highest(localHlLookback)
slAmount=isCoralBullish?entryPrice-longSlPrice:shortSlPrice-entryPrice
slPercent=math.abs((1-(entryPrice-slAmount)/entryPrice)*100)
tpPercent=slPercent*riskReward
//Riskcalculations
riskAmt=strategy.equity*accountRiskPercent/100
entryQty=math.abs(riskAmt/slPercent*100)/close
ifopenLong
ifstrategy.position_size<0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)
printTradeExitLabel(bar_index+1,math.max(tpPrice,slPrice),strategy.position_size,strategy.position_avg_price,strategy.openprofit)
strategy.entry("Long",strategy.long,qty=entryQty,alert_message="LongEntry")
enteringTrade:=true
inLong:=true
inShort:=false
ifopenShort
ifstrategy.position_size>0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)
printTradeExitLabel(bar_index+1,math.max(tpPrice,slPrice),strategy.position_size,strategy.position_avg_price,strategy.openprofit)
strategy.entry("Short",strategy.short,qty=entryQty,alert_message="ShortEntry")
enteringTrade:=true
inShort:=true
inLong:=false
ifenteringTrade
profitPoints:=percentAsPoints(tpPercent)
lossPoints:=percentAsPoints(slPercent)
slPrice:=calcStopLossPrice(lossPoints,openLong)
tpPrice:=calcProfitTrgtPrice(profitPoints,openLong)
tradeEntryBar:=bar_index
strategy.exit("TP/SL",profit=profitPoints,loss=lossPoints,comment_profit="TPHit",comment_loss="SLHit",alert_profit="TPHitAlert",alert_loss="SLHitAlert")
//=============================================================================
//DRAWINGS
//=============================================================================
//-----------
//TP/SLBoxes
//-----------
slHit=(inShortandhigh>=slPrice)or(inLongandlow<=slPrice)
tpHit=(inLongandhigh>=tpPrice)or(inShortandlow<=tpPrice)
exitTriggered=slHitortpHit
ctEntryPrice=strategy.closedtrades.entry_price(strategy.closedtrades-1)
pnl=strategy.closedtrades.profit(strategy.closedtrades-1)
posSize=strategy.closedtrades.size(strategy.closedtrades-1)
//Printboxesfortradesclosedatprofitorloss
if(inTradeandexitTriggered)
inShort:=false
inLong:=false
printTpSlHitBox(tradeEntryBar,bar_index,slHit,tpHit,ctEntryPrice,slPrice,tpPrice)
printTradeExitLabel(bar_index,math.max(tpPrice,slPrice),posSize,ctEntryPrice,pnl)
//PrintTP/SLboxforcurrentopentrade
ifbarstate.islastconfirmedhistoryandstrategy.position_size!=0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)

////=============================================================================
////DEBUGGING
////=============================================================================
//Datawindowplots
plotchar(prePullbackBullBreakout,"prePullbackBullBreakout","")
plotchar(prePullbackBearBreakout,"prePullbackBearBreakout","")
plotchar(barssincePullbackStart,"barssincePullbackStart","")
plotchar(isCoralBullish,"isCoralBullish","")
plotchar(isCoralBearish,"isCoralBearish","")
plotchar(barssinceCoralflip,"barssinceCoralflip","")
plotchar(isPullbackValid,"isPullbackValid","")
plotchar(entryBreakout,"entryBreakout","")
plotchar(slHit,"slHit","")
plotchar(tpHit,"tpHit","")
plotchar(slPrice,"slPrice","")
//Labelplots
//plotDebugLabels=false
//ifplotDebugLabels
//ifbar_index==tradeEntryBar
//printLabel(bar_index,"Positionsize:"+str.tostring(entryQty*close,"#.##"))
Expand (473 lines)
