Script Name: Custom Strategy omar achbehe
Author: ch0294123
Description: //@version=4
strategy("Custom Strategy", shorttitle="CustStrat", overlay=true)

// Input settings
length = input(56, minval=1, title="WMA Length")
atrlen = input(100, minval=1, title="ATR Length")
mult1 = input(2, title="Multiplier 1")
mult2 = input(3, title="Multiplier 2")
nlookback = input(20, minval=1, title="Number of Lookback")
scale = input(1, title="Scale...
PineScript code:

Pine Script™ strategy
Custom Strategy omar achbehe
//@version=4
strategy("Custom  Strategy  omar  achbehe",  shorttitle="CustStrat",  overlay=true)
//  Input  settings
length  =  input(56,  minval=1,  title="WMA  Length")
atrlen  =  input(100,  minval=1,  title="ATR  Length")
mult1  =  input(2,  title="Multiplier  1")
mult2  =input(3,title="Multiplier2")
nlookback=input(20,minval=1,title="NumberofLookback")
scale=input(1,title="ScaleofATR")
nATR=input(14,title="ATRParameter")
periods=input(21,minval=1,title="MAPeriods")
pc=input(true,title="MABAND")
LRG_Channel_TF_mins_D_W_M=input("30",title="LRGChannelTimeframe")
Range2=input(1,title="Range2")
SML_Channel_TF_mins_D_W_M=input("240",title="SMLChannelTimeframe")
Zingzag_length=input(7,title="ZigzagLength")
Zigzag2=input(false,title="ShowZigzag")
source=close
range=tr
src=close
//CustomFunctions
wma(source,length)=>
sum=0.0
norm=0.0
fori=0tolength-1
sum:=sum+source[i]*(length-i)
norm:=norm+(length-i)
sum/norm
hld=iff(close>sma(high,periods)[1],1,iff(close<sma(low,periods)[1],-1,0))
hlv=valuewhen(hld!=0,hld,1)
hi=pcandhlv==-1?sma(high,periods):na
lo=pcandhlv==1?sma(low,periods):na
SELL=security(syminfo.tickerid,LRG_Channel_TF_mins_D_W_M,highest(Range2))
BUY=security(syminfo.tickerid,LRG_Channel_TF_mins_D_W_M,lowest(Range2))
M_HIGH=security(syminfo.tickerid,SML_Channel_TF_mins_D_W_M,high)
M_LOW=security(syminfo.tickerid,SML_Channel_TF_mins_D_W_M,low)
hls=rma(hl2,Zingzag_length)
isRising=hls>=hls[1]
zigzag1=isRisingandnotisRising[1]?lowest(Zingzag_length):notisRisingandisRising[1]?highest(Zingzag_length):na
zigzag=hlv==-1?high:hlv==1?low:na
//Conditions
up1=wma(source,length)+wma(range,atrlen)*mult1
up2=wma(source,length)+wma(range,atrlen)*mult2
dn1=wma(source,length)-wma(range,atrlen)*mult1
dn2=wma(source,length)-wma(range,atrlen)*mult2
Hcon=high>=up1
Lcon=low<=dn1
//StrategyLogic
strategy.entry("Long",strategy.long,when=Hcon)
strategy.entry("Short",strategy.short,when=Lcon)
strategy.exit("ExitLong",from_entry="Long",when=Lcon)
strategy.exit("ExitShort",from_entry="Short",when=Hcon)
//PlotsandShapes
plot(up1,color=color.white)
plot(dn1,color=color.white)
plot(hi,title="SwingHighPlot",color=color.black,style=plot.style_line,linewidth=1)
plot(lo,title="SwingLowPlot",color=color.black,style=plot.style_line,linewidth=1)
plot(M_HIGH,color=M_HIGH!=M_HIGH[1]?na:color.fuchsia,style=plot.style_line,linewidth=2)
plot(M_LOW,color=M_LOW!=M_LOW[1]?na:color.fuchsia,style=plot.style_line,linewidth=2)
plot(zigzag1,color=color.black)
plot(notZigzag2?na:zigzag,color=color.red,style=plot.style_line,linewidth=3)
bgcolor(Hcon?color.red:Lcon?color.green:na,transp=100)
Expand (71 lines)
