Script Name: Customizable Non-Repainting HTF MACD MFI Scalper Bot Strategy
Author: MauricioZuniga
Description: This script was originally shared by  Wunderbit   as a free open source script for the community to work with.

WHAT THIS SCRIPT DOES:
It is intended for use on an algorithmic bot trading platform but can be used for scalping and manual trading.
This strategy is based on the trend-following momentum indicator . It includes the Money Flow index as an additional...
PineScript code:

Pine Script™ strategy
Customizable Non-Repainting HTF MACD MFI Scalper Bot Strategy
//(c)  Wunderbit  Trading
//Modified  by  Mauricio  Zuniga  -  Trade  at  your  own  risk
//This  script  was  originally  shared  on  Wunderbit  website  as  a  free  open  source  script  for  the  community.  (https://www.tradingview.com/u/Wunderbit/)
//
//WHAT  THIS  SCRIPT  DOES:
//      This  is  a  scalping  script  originally  intended  to  be  used  on  altorightmic  bot  trading.
//      This  strategy  is  based  on  the  trend-following  momentum  indicator.  It  includes  the  Money  Flow  index  as  an  additional  point  for  entry.
//HOW  IT  DOES  IT:
//      It  uses  a  combination  of  MACD  and  MFI  indicators  to  create  entry  signals.    Parameters  for  each  indicator  have  been  surfaced  for  user  configurability.
//      Take  profits  are  fixed,  but  stop  loss  uses  ATR  configuration  to  minimize  losses  and  close  profitably.
//HOW  IS  MY  VERSION  ORIGINAL:
//      I  started  trying  to  deploy  this  script  myself  in  my  algorithmic  tradingg  but  ran  into  some  issues  which  I  have  tried  to  address  in  this  version.
//      Delayed  Signals  :  The  script  has  been  refactored  to  use  a  time  frame  drop  down.    The  higher  time  frame  can  be  run  on  a  faster  chart  (recommended  on  one  minute  chart  for  fastest  signal  confirmation  and  relay  to  algotrading  platform.
//      Repainting  Issues  :  All  indicators  have  been  recoded  to  use  the  security  function  that  checks  to  see  if  the  current  calculation  is  in  realtime,  if  it  is,  then  it  uses  the  previous  bar  for  calculation.
//      If  you  are  still  experiencing  repainting  issues  based  on  intended  (or  non  intended  use),  please  provide  a  report  with  screenshot  and  explanation  so  I  can  try  to  address.
//      Filtering  :    I  have  added  to  additional  filters  an  ABOVE  EMA  Filter  and  a  BELOW  RSI  Filter  (both  can  be  turned  on  and  off)
//      Customizable  Long  and  Clos  Messages  :  This  allows  someone  to  use  the  script  for  algorithmic  trading  without  having  to  alter  code.    It  also  means  you  can  use  one  indicator  for  all  of  your  different  alterts  required  for  your  bots.
//HOW  TO  USE  IT:
//      Find  a  pair  with  high  volatility  -  I  have  found  it  works  particularly  well  with  3L  and  3S  tokens  for  crypto.  although  it  the  limitation  is  that  confrigurations  I  have  found  to  work  typically  have  low  R/R  ratio,  but  very  high  win  rate  and  profit  factor.
//      Ieally  set  one  minute  chart  for  bots,  but  you  can  use  other  charts  for  manual  trading.    The  signal  will  be  delayed  by  one  bar  but  I  have  found  configurations  that  still  test  well.
//      Select  a  time  frame  in  configuration  for  your  indicator  calculations.
//      I  like  ot  use  5  and  15  minutes  for  scalping  scenarios,  but  I  am  interested  in  hearing  back  from  other  community  memebers.
//      Optimize  your  indicator  without  filters  (trendFilter  and  RSI  Filter)
//      Use  the  TrendFilter  and  RSI  Filter  to  further  refine  your  signals  for  entry.
//@version=4
strategy("Customizable  HTF  MACD  Strategy  v1.2",  overlay=false,  pyramiding=0,  commission_type=strategy.commission.percent,  commission_value=0.07,  default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  100,  currency  =  currency.USD)
openlongcomment  =  "Comment  In  Here"
closelongcomment  =  ""
openshortcomment  =  ""
closeshortcommment  =  ""
//RES
res  =  input(title="Resolution",  type=input.resolution,  defval="5",  group="Strategy",  inline="1")
ribbon_period  =  input(19,  "Period",  step=1,  group="Strategy",  inline="1")
olc  =  input(title="Open  Long  Comment",  type=input.string,  defval="",group="Strategy",  inline="2")
clc  =  input(title="Close  Long  Comment",  type=input.string,  defval="",group="Strategy",  inline="2")
if  not(olc  ==  "")
        openlongcomment  :=  olc
if  not(clc  ==  "")
        closelongcomment  :=  clc
//  FUNCTIONS
Ema(src,p)  =>
        ema  =  0.
        sf  =  2/(p+1)
        ema  :=  nz(ema[1]  +  sf*(src  -  ema[1]),src)
Sma(src,p)  =>  a  =  cum(src),  (a  -  a[max(p,0)])/max(p,0)
Atr(p,  res)  =>
        atr  =  0.
        highHTF  =  security(syminfo.tickerid,  res,  high[barstate.isrealtime  ?  1  :  0])
        lowHTF  =  security(syminfo.tickerid,  res,  low[barstate.isrealtime  ?  1  :  0])
        closeHTF  =  security(syminfo.tickerid,  res,  close[barstate.isrealtime  ?  1  :  0])
        Tr  =  max(highHTF  -  lowHTF,  max(abs(highHTF  -  closeHTF[1]),  abs(lowHTF  -  closeHTF[1])))
        atr  :=  nz(atr[1]  +  (Tr  -  atr[1])/p,Tr)
htfClose  =  security(syminfo.tickerid,  res,  close[barstate.isrealtime  ?  1  :  0])
leadLine1  =  ema(htfClose,  ribbon_period)
leadLine2  =  sma(htfClose,  ribbon_period)
//  p3  =  plot(leadLine1,  color=  #53b987,  title="EMA",  transp  =  50,  linewidth  =  1)
//  p4  =  plot(leadLine2,  color=  #eb4d5c,  title="SMA",  transp  =  50,  linewidth  =  1)
//  fill(p3,  p4,  transp  =  60,  color  =  leadLine1  >  leadLine2  ?  #53b987  :  #eb4d5c)
//Upward  Trend
UT=leadLine2  <  leadLine1
DT=leadLine2>leadLine1
//  MACD
fast_length  =  input(title="Fast  Length",  type=input.integer,  defval=7,  group="MACD",  inline='1')
slow_length  =  input(title="Slow  Length",  type=input.integer,  defval=23,  group="MACD",  inline='1')
signal_length  =  input(title="Signal  Smoothing",  type=input.integer,  minval  =  1,  maxval  =  50,  defval  =  10,  group="MACD",  inline='2')
src  =  input(title="Source",  type=input.source,  defval=close,  group="MACD",  group="MACD",  inline='2')
sma_source  =  input(title="Simple  MA(Oscillator)",  type=input.bool,  defval=false,  group="MACD",  inline='3')
sma_signal  =  input(title="Simple  MA(Signal  Line)",  type=input.bool,  defval=false,  group="MACD",  inline='3')
//  Plot  colors
col_grow_above  =  #26A69A
col_grow_below  =  #FFCDD2
col_fall_above  =  #B2DFDB
col_fall_below  =  #EF5350
col_macd  =  #0094ff
col_signal  =  #ff6a00
srcHTF  =  security(syminfo.tickerid,  res,  src[barstate.isrealtime  ?  1  :  0])
//  Calculating
fast_ma  =  sma_source  ?  Sma(srcHTF,  fast_length)  :  Ema(srcHTF,  fast_length)
slow_ma  =  sma_source  ?  Sma(srcHTF,  slow_length)  :  Ema(srcHTF,  slow_length)
macd  =  fast_ma  -  slow_ma
signal  =  sma_signal  ?  Sma(macd,  signal_length)  :  Ema(macd,  signal_length)
hist=macd-signal
//plot(hist,title="Histogram",style=plot.style_columns,color=(hist>=0?(hist[1]<hist?col_grow_above:col_fall_above):(hist[1]<hist?col_grow_below:col_fall_below)),transp=0)
plot(macd,title="MACD",color=col_macd,transp=0)
plot(signal,title="Signal",color=col_signal,transp=0)
///MFI
MFIsource=hlc3
sourceHTF=security(syminfo.tickerid,res,MFIsource[barstate.isrealtime?1:0])
length=input(15,minval=1,group="MFI",inline='1')
lower=input(12,minval=0,maxval=50,group="MFI",inline='1')
upper=input(80,minval=50,maxval=100,group="MFI",inline='1')
//DrawMFI_f=input(true,title="DrawMFI?",type=bool)
HighlightBreaches=input(true,title="HighlightOversold/Overbought?")
volumeHTF=security(syminfo.tickerid,res,volume[barstate.isrealtime?1:0])
//MFI
upper_s=sum(volumeHTF*(change(sourceHTF)<=0?0:sourceHTF),length)
lower_s=sum(volumeHTF*(change(sourceHTF)>=0?0:sourceHTF),length)
mf=rsi(upper_s,lower_s)
mfp=plot(mf,color=color.new(color.gray,0),linewidth=1)
top=hline(upper,color=color.new(color.gray,100),linewidth=1,editable=false)
bottom=hline(lower,color=color.new(color.gray,100),linewidth=1,editable=false)
hline(0,color=color.new(color.black,100),editable=false)
hline(100,color=color.new(color.black,100),editable=false)
//Breaches
b_color=(mf>upper)?color.new(color.red,70):(mf<lower)?color.new(color.green,60):na
bgcolor(HighlightBreaches?b_color:na)
fill(top,bottom,color=color.gray,transp=75)
//TAKEPROFITANDSTOPLOSS
useTP1=input(false,title="UseTPI",group="TP/SL",inline='1',type=input.bool)
long_tp1_inp=input(1,title='LongTP1%',step=0.1,group="TP/SL",inline='1')/100
long_tp1_qty=input(20,title="LongTP1Qty",step=1,group="TP/SL",inline='1')
long_trailing=input(1.3,title='TrailingStop',step=0.1,group="TP/SL",inline='1',tooltip="")/100
long_take_level_1=strategy.position_avg_price*(1+long_tp1_inp)
//StopLoss
multiplier=input(2,"SLMult",minval=1,step=0.1,group="TP/SL",inline='2')
ATR_period=input(40,"ATRPd",minval=1,step=1,group="TP/SL",inline='2')
//FILTERLOGIC
aboveTrend=input(false,title="UseTrend",group="Filters",inline='1',type=input.bool)
TrendLength=input(3,minval=1,title="TrendMA",group="Filters",inline='1',type=input.integer)
aboveTrendFilter=sma(htfClose,TrendLength)
useRSI=input(false,title="UseRSI",group="Filters",inline='2',type=input.bool)
RSILength=input(34,minval=1,title="RSILength",group="Filters",inline='2')//usedtocalculateRSI
belowRSIFilter=input(50,minval=1,title="BuyBelowRSIFilter",group="Filters",inline='2')//onlybuyifitsbelowthisRSI-doesn'tseemtoworkasexpected
rsi=rsi(htfClose,RSILength)
ifnot(useRSI)
belowRSIFilter:=100
ifnot(aboveTrend)
aboveTrendFilter:=0//shouldneverhave0movingaveragesoshouldalwaysbeabove

//Strategy
entry_long=(crossover(macd,signal)or(crossover(mf,lower)andleadLine2<leadLine1))andrsi<belowRSIFilterandclose>aboveTrendFilter
entry_price_long=valuewhen(entry_long,close,0)
//SL_floating_long=entry_price_long-((entry_price_long)*multiplier/100)//*Atr(ATR_period,res)
//SL_floating_long=entry_price_long-multiplier*Atr(ATR_period,res)
SL_floating_long=entry_price_long-multiplier*Atr(ATR_period,res)
exit_long=close<SL_floating_long
/////BACKTESTPERIOD///////
testStartYear=input(2018,"BacktestStartYear")
testStartMonth=input(1,"BacktestStartMonth")
testStartDay=input(1,"BacktestStartDay")
testPeriodStart=timestamp(testStartYear,testStartMonth,testStartDay,0,0)
testStopYear=input(9999,"BacktestStopYear")
testStopMonth=input(12,"BacktestStopMonth")
testStopDay=input(31,"BacktestStopDay")
testPeriodStop=timestamp(testStopYear,testStopMonth,testStopDay,0,0)
testPeriod()=>
time>=testPeriodStartandtime<=testPeriodStop?true:false
iftestPeriod()
ifUT
strategy.entry("long",strategy.long,when=entry_long==true,comment=openlongcomment)
if(useTP1)
strategy.exit("TP1","long",qty_percent=long_tp1_qty,limit=long_take_level_1)
strategy.exit("Trailstop","long",comment=closelongcomment,trail_points=entry_price_long*long_trailing/syminfo.mintick,trail_offset=entry_price_long*long_trailing/syminfo.mintick)
strategy.close("long",exit_long==true,comment=closelongcomment)
Expand (194 lines)
