Script Name: Customizable OCC Non Repainting Scalper Bot v7.0b
Author: MauricioZuniga
Description: This strategy is intended to be used on an automated trading platform and  should be run on a one minute chart for fastest confirmations and signal relay  to crypto automation platform.  The strategy has been modded to only go long at this time to focus on profitability for one direction.  The open long and close long text fields allow you to use your own webhook...
PineScript code:

Pine Script™ strategy
Customizable OCC Non Repainting Scalper Bot v7.0b
//@version=5
//

strategy(title='Open  Open  Cross  Strategy  R7.1b  revised  by  MZ'
          ,  shorttitle='OCC  Strategy  R7.1'
          ,  overlay=true
          ,  pyramiding=0
          ,  default_qty_type=strategy.percent_of_equity
          ,  default_qty_value=100
          ,  calc_on_every_tick=true
          ,  process_orders_on_close=true
          ,  commission_value=0.08)
//  For  Testing  &  Debug
//  security  wrapper  for  repeat  calls
//reso(exp,  use,  res)  =>
//        security_1  =    request.security(syminfo.tickerid,  res,  exp[barstate.isrealtime  ?  1  :  0],  gaps=barmerge.gaps_off,  lookahead=barmerge.lookahead_on)
//        use  ?  security_1  :  exp[barstate.isrealtime  ?  1  :  0]

//As  opposed  to  the  recommendation  that  TV  gives,  I  am  trying  to  get  the  fastest  non  repainting  by  ensuring  that  barclose  -  barisconfirmed,  we  get  the  most  recent  values.
//Otherwise,  the  strategy  is  looking  at  the  most  recent  previous  period  until  the  bar  close  -  this  was  altered  from  the  version  I  was  given
reso(exp,  use,  res)  =>  //v3
        //security_1  =    request.security(syminfo.tickerid,  res,  exp[barstate.isconfirmed  ?  0  :  1],  gaps=barmerge.gaps_off,  lookahead=barmerge.lookahead_on)
        security_1=request.security(syminfo.tickerid,res,exp[barstate.isconfirmed?0:1],gaps=barmerge.gaps_off)[barstate.isconfirmed?0:1]
use?security_1:exp[barstate.isconfirmed?0:1]
//ThseIalsocreatedfromsimilarconceptforrepaintsecuritycalcsImakethroughoutthestrategy
rp_security(_symbol,_res,_src)=>request.security(_symbol,_res,_src[barstate.isconfirmed?0:1])[barstate.isconfirmed?0:1]
rp_security_merged(_symbol,_res,_src)=>request.security(_symbol,_res,_src[barstate.isconfirmed?0:1],gaps=barmerge.gaps_on)[barstate.isconfirmed?0:1]
//ReturnsMAinputselectionvariant,defaulttoSMAifblankortypo.
variant(type,src,len,offSig,offALMA)=>
v1=ta.sma(src,len)//Simple
v2=ta.ema(src,len)//Exponential
v3=2*v2-ta.ema(v2,len)//DoubleExponential
v4=3*(v2-ta.ema(v2,len))+ta.ema(ta.ema(v2,len),len)//TripleExponential
v5=ta.wma(src,len)//Weighted
v6=ta.vwma(src,len)//VolumeWeighted
v7=0.0
sma_1=ta.sma(src,len)//Smoothed
v7:=na(v7[1])?sma_1:(v7[1]*(len-1)+src)/len
v8=ta.wma(2*ta.wma(src,len/2)-ta.wma(src,len),math.round(math.sqrt(len)))//Hull
v9=ta.linreg(src,len,offSig)//LeastSquares
v10=ta.alma(src,len,offALMA,offSig)//ArnaudLegoux
v11=ta.sma(v1,len)//Triangular(extremesmooth)
//SuperSmootherfilter
//©2013JohnF.Ehlers
a1=math.exp(-1.414*3.14159/len)
b1=2*a1*math.cos(1.414*3.14159/len)
c2=b1
c3=-a1*a1
c1=1-c2-c3
v12=0.0
v12:=c1*(src+nz(src[1]))/2+c2*nz(v12[1])+c3*nz(v12[2])
type=='EMA'?v2:type=='DEMA'?v3:type=='TEMA'?v4:type=='WMA'?v5:type=='VWMA'?v6:type=='SMMA'?v7:type=='HullMA'?v8:type=='LSMA'?v9:type=='ALMA'?v10:type=='TMA'?v11:type=='SSMA'?v12:v1
//===INPUTS===
useRes=input(defval=true,title='UseAltRes?',group="Strategy",inline="1",tooltip="ThisStrategymodifiedtouseLONGonly")
intRes=input(defval=3,title='MultRes',group="Strategy",inline="1")
calcOffset=input(defval=0,title='IntervalOffset',group="Strategy",inline="1")
offset=input(defval=0,title='CrossOffset',group="Strategy",inline="1")
stratRes=timeframe.ismonthly?str.tostring(timeframe.multiplier*intRes,'###M'):timeframe.isweekly?str.tostring(timeframe.multiplier*intRes,'###W'):timeframe.isdaily?str.tostring(timeframe.multiplier*intRes,'###D'):timeframe.isintraday?str.tostring(timeframe.multiplier*intRes,'####'):'60'
basisType=input.string(defval='TEMA',title='MAType:',group="Basis",inline="1",options=['SMA','EMA','DEMA','TEMA','WMA','VWMA','SMMA','HullMA','LSMA','ALMA','SSMA','TMA'])
basisLen=input.int(defval=8,title='MAPeriod',minval=1,group="Basis",inline="1")
offsetSigma=input.int(defval=6,title='OffsetLSMA/SigmaALMA',minval=0,group="Strategy",group="Basis",inline="2")
offsetALMA=input.float(defval=0.85,title='OffsetALMA',minval=0,step=0.01,group="Basis",inline="2")
scolor=input(true,title='ShowTrend?',group="Basis",inline="3")
delayOffset=0//input.int(defval=0,title='DelayO/CMA',minval=0,step=1,group="Basis",inline="3")
tradeType='LONG'//input.string('LONG',title='Whattradesshouldbetaken:',options=['LONG','SHORT','BOTH','NONE'],group="Basis",inline="3")
enableTrailing=input.bool(defval=true,title='Trailing',tooltip='Enableordisablethetrailingfortakeprofit.',group='TrailingProfit',inline='1')
longTakeProfitPerc=input.float(title="LongTP(%)",minval=0.0,step=0.1,defval=4,group='TrailingProfit',inline='1')*0.01
trailingTakeProfitDeviationPerc=input.float(defval=0.5,title='TTPDev%%',minval=0.01,maxval=100,step=0.1,tooltip='Thesteptofollowthepricewhenthetakeprofitlimitisreached.',group='TrailingProfit',inline='1')/100
longLossPerc=input.float(6,title="FixedSL(%)",minval=0.0,step=0.1,defval=1,tooltip="Use100toturnoff-Stoploss%evenifATRdidnotcatchit")*0.01
longStopPrice=strategy.position_avg_price*(1-longLossPerc)
belowStopLoss=strategy.position_avg_price<=longStopPrice
longTPPrice=strategy.position_avg_price*(1+longTakeProfitPerc)
aboveTakeProfit=strategy.position_avg_price>=longTPPrice

//Filteroutfalsepositivesviamovingaverage-tryusingLSMA3MINvaryinglength
useVariantFilter=input.bool(false,title="UseMA",group="Filters",inline='1')
VariantFilterType=input.string(defval='LSMA',title='Type:',group="Filters",inline="1",options=['SMA','EMA','DEMA','TEMA','WMA','VWMA','SMMA','HullMA','LSMA','ALMA','SSMA','TMA'])
VariantTimeFrame=input.timeframe(defval='3',title='TF:',group="Filters",inline='1')
VariantFilterLength=input.int(20,minval=1,title="Len",group="Filters",inline='1')//usedtocalculateRSI
//aboveVariant=input.float(0,title="MinATR",minval=0.0,step=0.001,defval=1,group="Filters",inline='3',tooltip="Use0toturnoff-canremoveperiodsoflowvolatilitywherelesslikelyprofitable")
variantFilter=reso(variant(VariantFilterType,close[barstate.isrealtime?1:0],VariantFilterLength,offsetSigma,offsetALMA),true,VariantTimeFrame)//reso(variant(VariantFilterType,close[1],VariantFilterLength,offsetSigma,offsetALMA),1,VariantTimeFrame)
passesVariantFilter=(close[barstate.isrealtime?1:0]>=variantFilter)ornot(useVariantFilter)
variantFilterP=plot(variantFilter,title='VariantFilter',color=color.blue,linewidth=4,style=plot.style_line,transp=20)
//Thisseemstoworkratherwellwhenyouarefilteringlongertimeperiods(30-40length)andstartfilteringbelow55-45,whichmeansthatitsnotoverboughtht
useRSI=input.bool(false,title="UseRSI",group="Filters",inline='2')
rsiTimeFrame=input.timeframe(defval='30',title='TF:',group="Filters",inline='2')
RSILength=input.int(20,minval=1,title="RSILength",group="Filters",inline='2')//usedtocalculateRSI
aboveRSIFilter=input.int(40,minval=1,title="BuyAboveRSI",group="Filters",inline='2')
belowRSIFilter=input.int(75,minval=1,title="BuyBelowRSI",group="Filters",inline='2')//onlybuyifitsbelowthisRSI-doesn'tseemtoworkasexpected
rsiTmp=ta.rsi(close[barstate.isconfirmed?0:1],RSILength)
//rsiRisingLen=input.int(2,minval=1,title="RisingLen",group="Filters",inline='2')//onlybuyifitsbelowthisRSI-doesn'tseemtoworkasexpected
//rsiMinROC=input.float(-5,minval=-5,title="Rising",group="Filters",inline='2')//onlybuyifitsbelowthisRSI-doesn'tseemtoworkasexpected
rsi=rp_security(syminfo.tickerid,rsiTimeFrame,rsiTmp)//rp_security(sys,_res,_src)
passesRSIfilter=(rsi<=belowRSIFilterandrsi>=aboveRSIFilter)ornot(useRSI)
//andta.rising(ta.sma(rsi,rsiRisingLen),2)andta.roc(rsi,rsiRisingLen)>rsiMinROC)
//FilterviaminATRsoyoucanmakesurethatthereisenoughvolatilitytomakeaprofitabletrade
useATR=input.bool(false,title="UseATR",group="Filters",inline='3')
ATRLength=input.int(34,minval=1,title="ATRLength",group="Filters",inline='3')//usedtocalculateRSI
minATR=input.float(0,title="MinATR",minval=0.0,step=0.001,defval=1,group="Filters",inline='3',tooltip="Use0toturnoff-canremoveperiodsoflowvolatilitywherelesslikelyprofitable")
atr=ta.atr(ATRLength)
isAboveATR=atr>=minATRornot(useATR)
//=======ADXFILTER=======
useADX=input.bool(true,title="UseADX",group="Filters",inline='adx1')
useDiplus=input.bool(false,title="UptrendOnly",group="Filters",inline='adx1')
adxTF=input.timeframe("5",title="ADXTF",group="Filters",inline='adx1_2')
length=input(14,title="Length",group="Filters",inline='adx1_2')
smoothing=input(40,title="Smooth",group="Filters",inline='adx1_2')
adxMin=input(20,title="Min",group="Filters",inline='adx1_2')
adxMax=input(100,title="Max",group="Filters",inline='adx1_2')
[diplus,diminus,adx]=ta.dmi(length,smoothing)
adxHTF=rp_security(syminfo.tickerid,adxTF,adx)
diplusHTF=rp_security(syminfo.tickerid,adxTF,diplus)
diminusHTF=rp_security(syminfo.tickerid,adxTF,diminus)
diCalc=diplusHTF-diminusHTF
diEMA=ta.ema(diCalc,2)
//upTrendTrue=diplusHTF-diminusHTF>0
upTrendTrue=diEMA>0
adxMsg='\ndiplus:'+str.tostring(diplusHTF)+'\ndiminus:'+str.tostring(diminusHTF)+'\nadx:'+str.tostring(adxHTF)+'\ndiEMA:'+str.tostring(diEMA)+'\ndiUptrend:'+str.tostring(upTrendTrue)
passesADXFilters=(adxHTF>=adxMinandadxHTF<=adxMax)ornot(useADX)
passUptrendOnlyFilter=upTrendTrueornot(useDiplus)
//ENDADX-usepassesADXFiltersandpassUpTrendOnlyFilter

//=======ADX2FILTER=======
//ADX2Filter-asecondfilterthatcouldbeusedonahighertimeframeetc
useADX2=input.bool(false,title="UseADX2",group="Filters",inline='Adx2')
useDiplus2=input.bool(false,title="UptrendOnly",group="Filters",inline='Adx2',tooltip="IfyouwanttouseasecondADXfilterforahighertimeframe,etc")
adxTF2=input.timeframe("5",title="ADXTF",group="Filters",inline='Adx23')
length2=input(14,title="Length",group="Filters",inline='Adx23')
smoothing2=input(40,title="Smooth",group="Filters",inline='Adx23')
adxMin2=input(20,title="Min",group="Filters",inline='Adx23')
adxMax2=input(100,title="Max",group="Filters",inline='Adx23')
[diplus2,diminus2,adx2]=ta.dmi(length2,smoothing2)
adxHTF2=rp_security(syminfo.tickerid,adxTF2,adx2)
diplusHTF2=rp_security(syminfo.tickerid,adxTF2,diplus2)
diminusHTF2=rp_security(syminfo.tickerid,adxTF2,diminus2)
diCalc2=diplusHTF2-diminusHTF2
diEMA2=ta.ema(diCalc2,2)
upTrendTrue2=diEMA2>0//diplusHTF2-diminusHTF2>0
//adxMsg2='\ndiplus2:'+str.tostring(diplusHTF2)+'\ndiminus2:'+str.tostring(diminusHTF2)+'\nadx2:'+str.tostring(adxHTF2)
adxMsg2='\ndiplus2:'+str.tostring(diplusHTF2)+'\ndiminus2:'+str.tostring(diminusHTF2)+'\nadx2:'+str.tostring(adxHTF2)+'\ndiEMA2:'+str.tostring(diEMA2)+'\ndiUptrend2:'+str.tostring(upTrendTrue2)
passesADXFilters2=(adxHTF2>=adxMin2andadxHTF2<=adxMax2)ornot(useADX2)
passUptrendOnlyFilter2=upTrendTrue2ornot(useDiplus2)
//ENDADX-usepassesADXFiltersandpassUpTrendOnlyFilter
//Concatbothadxmsgs
adxMsg:=adxMsg+adxMsg2
//===/INPUTS===
passesFilters=isAboveATRandpassesRSIfilterandpassesVariantFilterandpassesADXFiltersandpassUptrendOnlyFilterandpassesADXFilters2andpassUptrendOnlyFilter2
//Constantscoloursthatincludefullynon-transparentoption.
green100=#008000FF
lime100=#00FF00FF
red100=#FF0000FF
blue100=#0000FFFF
aqua100=#00FFFFFF
darkred100=#8B0000FF
gray100=#808080FF
//===BASEFUNCTIONS===
//===/BASEFUNCTIONS===
//===SERIESSETUP===
//closeNRP=rp_security(syminfo.tickerid,str.tostring(intRes),close)
//openNRP=rp_security(syminfo.tickerid,str.tostring(intRes),open)
//closeSeries=variant(basisType,open[barstate.isconfirmed?0:1],basisLen,offsetSigma,offsetALMA)
//openSeries=variant(basisType,open[barstate.isconfirmed?0:1],basisLen,offsetSigma,offsetALMA)
closeSeries=variant(basisType,open[0],basisLen,offsetSigma,offsetALMA)//wearerunningonebarbehindsoweassumethecurrentopenisthepreviousbarsclose
openSeries=variant(basisType,open[1],basisLen,offsetSigma,offsetALMA)//thismightnotworkforotherassetssuchascurrencies-willhavetolookintoit
//===/SERIES===
//===PLOTTING===
closeSeriesAlt=0.0
openSeriesAlt=0.0
closeTrade=false
xlong=false
xshort=false
modulus=intRes
//modulus:=1
//onlyupdatecalcifitsattheendoftheperiodorbeginningofnext
if((bar_index+calcOffset)%modulus==0andbarstate.isconfirmed)or((bar_index+calcOffset+1)%intRes==0)//andbarstate.isconfirmed//ifitisthecurrentperiodandalsothenextminuteafterthecurrentperiodthenrecalc
closeSeriesAlt:=reso(closeSeries,useRes,stratRes)
openSeriesAlt:=reso(openSeries,useRes,stratRes)
else
closeSeriesAlt:=closeSeriesAlt[1]
openSeriesAlt:=openSeriesAlt[1]
//closeSeriesAlt:=reso(closeSeries,useRes,stratRes)
//openSeriesAlt:=reso(openSeries,useRes,stratRes)
//closeTrade:=ta.crossunder(reso(closeSeries,useRes,stratRes),reso(openSeries,useRes,stratRes))//specialcalcthatdoesnotoverridesrepaintfixforclosingtrades
//xlong=closeSeriesAlt>openSeriesAltandpassesFilters'
//xlong:=(ta.crossover(closeSeriesAlt,openSeriesAlt)[offset])andpassesFilters//and(bar_index+intRes+1%(intRes)==0)//
xlong:=(ta.crossover(closeSeriesAlt,openSeriesAlt)[offset])andpassesFilters//and(bar_index+intRes+1%(intRes)==0)
//xlong:=ta.crossover(closeSeriesAlt,openSeriesAlt)[2]andpassesFilters//and(bar_index+intRes+1%(intRes)==0)//
//closeTrade=ta.crossunder(closeSeriesAlt,openSeriesAlt)
//xlong:=closeSeries[0]>openSeries[0]andcloseSeriesAlt[0]>openSeriesAlt[0]
xshort:=closeSeries<longStopPrice//ta.crossunder(closeSeriesAlt,openSeriesAlt)
trendColour=closeSeriesAlt>openSeriesAlt?color.green:color.red
bcolour=closeSeriesAlt>openSeriesAlt?color.green:color.red
barcolor(scolor?bcolour:na,title='BarColours')
closeP=plot(closeSeriesAlt,title='CloseSeries',color=trendColour,linewidth=2,style=plot.style_line,transp=20)
openP=plot(openSeriesAlt,title='OpenSeries',color=trendColour,linewidth=2,style=plot.style_line,transp=20)
fill(closeP,openP,color=trendColour,transp=80)
//DEBUG
//if(bar_index%(intRes)==0)
//label.new(bar_index,na,"BarIndex"+str.tostring(bar_index)+"\nRSI="+str.tostring(rsi,format.mintick)+"\nATR="+str.tostring(atr,format.mintick),yloc=yloc.abovebar,style=label.style_none,textcolor=color.white,size=size.normal)
longCond=xlong//alternative:longCond[1]?false:(xlongorxlong[1])andclose>closeSeriesAltandclose>=open
shortCond=xshort//alternative:shortCond[1]?false:(xshortorxshort[1])andclose<closeSeriesAltandclose<=open
//===/ALERTconditions.>
showData=true
iflongCondandstrategy.position_size==0andshowData
label.new(bar_index,na,"RSI="+str.tostring(rsi,format.mintick)+"\nATR="+str.tostring(atr,format.mintick)+adxMsg,yloc=yloc.abovebar,style=label.style_none,textcolor=color.white,size=size.normal)
//===STRATEGY===
//stoploss-Thesearedepracratedandreplacedbyfixedstoplossandtrailingprofit
slPercentage=0//input.int(defval=0,title='InitialStopLossPoints(zerotodisable)',minval=0)
tpPercentage=0//input.int(defval=0,title='InitialTargetProfitPoints(zerofordisable)',minval=0)
//Includebarlimitingalgorithm
ebar=input.int(defval=10000,title='NumberofBarsforBackTesting',minval=0)
dummy=input(false,title='-SETtoZEROforDailyorLongerTimeframes')
//
//Calculatehowmanymarssincelastbar
tdays=(timenow-time)/60000.0//numberofminutessincelastbar
tdays:=timeframe.ismonthly?tdays/1440.0/5.0/4.3/timeframe.multiplier:timeframe.isweekly?tdays/1440.0/5.0/timeframe.multiplier:timeframe.isdaily?tdays/1440.0/timeframe.multiplier:tdays/timeframe.multiplier//numberofbarssincelastbar
//
//setupexitparameters
TP=tpPercentage>0?tpPercentage:na
SL=slPercentage>0?slPercentage:na
exitLong=belowStopLossorshortCond==trueoraboveTakeProfit
openlongcomment=""
closelongcomment=""
olc=input.string(title="OpenLongComment",defval="",group="Strategy",inline="2")
clc=input.string(title="CloseLongComment",defval="",group="Strategy",inline="2")
ifnot(olc=="")
openlongcomment:=olc
ifnot(clc=="")
closelongcomment:=clc

//LOGICforTrailingProfit============================================================================================================
boollongIsActive=longCondorstrategy.position_size>0
floatlongTakeProfitPrice=na
longTakeProfitPrice:=iflongIsActive
iflongCondandnot(strategy.position_size>0)
close*(1+longTakeProfitPerc)
else
nz(longTakeProfitPrice[1],close*(1+longTakeProfitPerc))
else
na
longTrailingTakeProfitStepTicks=longTakeProfitPrice*trailingTakeProfitDeviationPerc/syminfo.mintick
//ENDTRAILNGPROFIT
//Makesurewearewithinthebarrange,Setupentriesandexit
//entrysignalonbarstateisconfirmed,butexitshouldbeonanytick
//passesfiltervaralreadychecksifbarstateisconfirmed
if(ebar==0ortdays<=ebar)andtradeType!='NONE'
strategy.entry('long',strategy.long,when=longCond==trueandtradeType!='SHORT',comment=openlongcomment)
//strategy.entry('short',strategy.short,when=shortCond==trueandtradeType!='LONG')
strategy.close('long',when=exitLongandtradeType=='LONG',comment=closelongcomment)
//strategy.close('short',when=longCond==trueandtradeType=='SHORT')
//strategy.exit('long',from_entry='long',profit=TP,loss=SL,comment=closelongcomment)//longTPPrice
//strategy.exit('XS',from_entry='short',profit=TP,loss=SL)
if(strategy.position_size>0)andclose>longTPPriceorexitLongorcloseTrade
//strategy.exit(id="long",profit=longTPPrice,comment=closelongcomment)
//submitexitordersfortrailingtakeprofitprice
strategy.exit(id='LongTrailingProfit',from_entry='long',comment=closelongcomment,limit=enableTrailing?na:longTakeProfitPrice,trail_price=enableTrailing?longTakeProfitPrice:na,trail_offset=enableTrailing?longTrailingTakeProfitStepTicks:na,when=longIsActive,alert_message='Long('+syminfo.ticker+'):TakeProfitactivated')

//===/STRATEGY===
//eof
//
//Revision:5
//OriginalAuthor:@JayRogers
//RevisionAuthor:JustUncleLrevisions3,4,5
//
//***USEATYOUROWNRISK***
//-Therearedrawing/paintingissuesinpinescriptwhenworkingacrossresolutions/timeframesthatIsimply
//cannotfixhere..Iwillnotbeputtinganyfurthereffortintodevelopingthisuntilsuchatimewhen
//workaroundsbecomeavailable.
//NOTE:Re-paintinghasbeenobservedinfrequentlywithdefaultsettingsandseemsOKuptoAlternate
//multiplierof5.
//Non-repaintingmodeisavailablebysetting"DelayOpen/CloseMA"to1ormore,butthereported
//performancewilldropdramatically.
//
//R5.1ChangesbyJustUncleL
//-UpgradedtoVersion3Pinescript.
//-AddedoptiontoselectTradetype(Long,Short,BothorNone)
//-Addedbarcolouringworkaroundpatch.
//-Smallcodechangestoimproveefficiency.
//-NOTE:Toenablenon-Repaintingmodeset"DelayOpen/CloseMA"to1ormore.
//9-Aug-2017
//-CorrectiononSuperSmoothMAcalculation.
//
//R5ChangesbyJustUncleL
//-Correctedcrossovercalculations,sometimesgavefalsesignals.
//-CorrectedAlternateTimecalculationtoallowforDaily,WeeklyandMonthlycharts.
//-OpenPublicrelease.
//R4ChangesByJustUncleL
//-ChangethewaytheAlternateresolutioninselected,useaMultiplierofthebaseTimeFrameinstead,
//thismakesiteasytoswitchbetweenbasetimeframes.
//-AddedTMAandSSMAmovingaverageoptions.ButDEMAisstillgivingthebestresults.
//-Using"calc_on_every_tick=false"ensuresresultsbetweenbacktestingandrealtimearesimilar.
//-AddedOptiontoDisablethecoloringofthebars.
//-Updateddefaultsettings.
//
//R3ChangesbyJustUncleL:
//-Returnedasimplifiedversionoftheopen/closechannel,itshowsstrengthofcurrenttrend.
//-AddedTargetProfitOption.
//-Addedoptiontoreducethenumberofhistoricalbars,overcomesthetoomanytradeslimiterror.
//-Simplifiedthestrategycode.
//-RemovedTrailingStopoption,notrequiredandinmyopiondoesnotworkwellinTradingView,
//italsogivesfalseandunrealisticperformanceresultsinbacktesting.
//
//R2Changes:
//-Simplifiedandcleanedupplotting,nowjustshowsaMovingAveragederivedfromtheaverageofopen/close.
//-Triedveryhardtoalleviatepaintingissuescausedbyreferencingalternateresolution..
//
//Description:
//-StrategybasedaroundOpen-CloseCrossovers.
//Setup:
//-Ihavegenerallyfoundthatsettingthestrategyresolutionto3-4xthatofthechartyouareviewing
//tendstoyieldthebestresults,regardlessofwhichMAoptionyoumaychoose(ifany)BUTcancause
//alotoffalsepositives-beawareofthis
//-Don'taimforperfection.JustaimtogetareasonablysnugfitwiththeO-Cband,withgoodrunsof
//greenandred.
//-Optiontoeitherusebasicopenandcloseseriesdata,orpickyourpoisonwithawidearrayofMAtypes.
//-Optionaltrailingstopfordamagemitigationifdesired(canbetoggledon/off)
//-Positionsgettakenautomagicallyfollowingacrossover-whichiswhyit'sbettertosettheresolution
//ofthescriptgreaterthanthatofyourchart,sothatthetradesgettakensoonerratherthanlater.
//-Ifyoumakeuseofthestops,besuretotakeyourtimetweakingthevalues.Cuttingittoofine
//willcostyouprofitsbutkeepyousafer,whilelettingthemloosecouldleadtomoredrawdownthanyou
//canhandle.
//-Toenablenon-Repaintingmodeset"DelayOpen/CloseMA"to1ormore.
//

Expand (355 lines)
