Script Name: Davin's 10-200MA Pullback on SPY Strategy v2.0
Author: Gold_D_Roger
Description: Strategy:
Using 10 and 200 Simple moving averages, we capitalize on price pullbacks on a general uptrend to scalp 1 - 5% rebounds. 200 MA is used as a general indicator for bullish sentiment, 10 MA is used to identify pullbacks in the short term for buy entries.

An optional bonus: market crash of 20% from 52 days high is regarded as a buy the dip signal.
An...
PineScript code:

Pine Script™ strategy
Davin's 10/200MA Pullback on SPY Strategy v2.0
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  Gold_D_Roger
//note:  spreading  1  statement  overmultiplelinesneeds1apce+1tab|multilinefunctionis1tab
//Recommendedtickers:SPY(D),QQQ(D)andbigindexes,AAPL(4H)
//@version=5
strategy("Davin's10/200MAPullbackonSPYStrategyv2.0",
overlay=true,
initial_capital=10000,
default_qty_type=strategy.percent_of_equity,
default_qty_value=10,//10%ofequityoneachtrade
commission_type=strategy.commission.cash_per_contract,
commission_value=0.1)//Insertyourbroker'srate,IBis0.005USDortiered
//Bestparameters
//SPYD
//Stoploss0.15
//commissionof0.005USDusingInteractivebrokers
//Exitonlowerclose
//Buymorewhenx%down-->14%
//DONOTincludestopconditionusingMAcrossover
//GetUserInput
i_ma1=input.int(title="MALength1",defval=200,step=10,group="StrategyParameters",tooltip="Long-termMA200")
i_ma2=input.int(title="MALength2",defval=10,step=10,group="StrategyParameters",tooltip="Short-termMA10")
i_ma3=input.int(title="MALength3",defval=50,step=1,group="StrategyParameters",tooltip="MAforcrossoversignals`")
i_stopPercent=input.float(title="StopLossPercent",defval=0.15,step=0.01,group="StrategyParameters",tooltip="Hardstoplossof10%")
i_startTime=input.time(title="Startfilter",defval=timestamp("01Jan201313:30+0000"),group="Timefilter",tooltip="Startdateandtimetobegin")
i_endTime=input.time(title="Endfilter",defval=timestamp("01Jan209919:30+0000"),group="Timefilter",tooltip="Enddateandtimetostop")
i_lowerClose=input.bool(title="Exitonlowerclose",defval=true,group="StrategyParameters",tooltip="Waitforlowercloseafterabove10SMAbeforeexiting")//optimiseexitstrat,booleantypecreatestickboxtypeinputs
i_contrarianBuyTheDip=input.bool(title="Buywhenevermorethanx%drawdown",defval=true,group="StrategyParameters",tooltip="Buythedip!Wheneverx%ormoredrawdownonSPY")
i_contrarianTrigger=input.int(title="Trigger%droptobuythedip",defval=14,step=1,group="StrategyParameters",tooltip="%droptotriggercontrarianBuytheDip!")
//14%tobebestforSPY1D
//20%bestforAMZN1D
i_stopByCrossover_MA2_3=input.bool(title="IncludestopconditionusingMAcrossover",defval=false,group="StrategyParameters",tooltip="SellwhencrossoverofMA2/1happens")
//Getindicatorvalues
ma1=ta.sma(close,i_ma1)//param1
ma2=ta.sma(close,i_ma2)//param2
ma3=ta.sma(close,i_ma3)//param3
ma_9=ta.ema(close,9)//param2
ma_20=ta.ema(close,20)//param3
//Checkfilter(s)
f_dateFilter=time>+i_startTimeandtime<=i_endTime//makesuredateentriesarewithinacceptablerange
//Highestpriceoftheprev52days:https://www.tradingcode.net/tradingview/largest-maximum-value/#:~:text=()%20versus%20ta.-,highest(),max()%20and%20ta.
highest52=ta.highest(high,52)
overall_change=((highest52-close[0])/highest52)*100
//Checkbuy/sellconditions
varfloatbuyPrice=0//intialisebuyPrice,thiswillchangewhenweenteratrade;float=decimalnumberdatatype0.0
buyCondition=(close>ma1andclose<ma2andstrategy.position_size==0andf_dateFilter)or(strategy.position_size==0andi_contrarianBuyTheDip==trueandoverall_change>i_contrarianTriggerandf_dateFilter)//higherthan200sma,lowerthanshorttermma(pullback)+avoidpyramidingpositions
sellCondition=close>ma2andstrategy.position_size>0and(noti_lowerCloseorclose<low[1])//checkifwealreadyintrade+closeabove10MA;
//thirdcondition:EITHERi_lowerClosenotturnedonORclosingpricehastobe<previouscandle'sLOW[1]
stopDistance=strategy.position_size>0?((buyPrice-close)/close):na//checkifintrade>calc%dropdistfromentry,ifnotna
stopPrice=strategy.position_size>0?(buyPrice-(buyPrice*i_stopPercent)):na//calcSLpriceifintrade,ifnot,na
stopCondition=(strategy.position_size>0andstopDistance>i_stopPercent)or(strategy.position_size>0and(i_stopByCrossover_MA2_3==trueandma3<ma1))
//Enterpositions
ifbuyCondition
strategy.entry(id="Long",direction=strategy.long)//longonly

ifbuyCondition[1]//ifbuyConditionistrueprevcandle
buyPrice:=open//entryprice=currentbaropeningprice
//Exitposition
ifsellConditionorstopCondition
strategy.close(id="Long",comment="Exit"+(stopCondition?"Stoploss=true":""))//ifcondition?"Valuefortrue":"valueforfalse"
buyPrice:=na//resetbuyPrice
//Plot
plot(buyPrice,color=color.lime,style=plot.style_linebr)
plot(stopPrice,color=color.red,style=plot.style_linebr,offset=-1)
plot(ma1,color=color.blue)//defval=200
plot(ma2,color=color.white)//defval=10
plot(ma3,color=color.yellow)//defval=50
Expand (85 lines)
