Script Name: DEMA-EMA & VOLATILITY (VAMS)
Author: Qorbanjf
Description: The biggest issue with momentum following strategies is over signaling during whipsaw periods. I created this strategy that measure momentum with DEMA (Fast Moving) and EMA (Slow moving). In order to mitigate over signaling during whipsaw periods I implemented the average true range percentage (ATRP) to measure realized volatility. If momentum is picking up while...
PineScript code:

Pine Script™ strategy
DEMA/EMA & VOLATILITY (VAMS)
//  This  source  code  is  subject  to  the  terms  of  theMozillaPublicLicense2.0athttps://mozilla.org/MPL/2.0/
//©Qorbanjf
//@version=4
strategy("ORIGINDEMA/EMA&VOLLONGONLY",shorttitle="ORIGINDEMA/EMA&VOLLONG",overlay=true,initial_capital=10000,default_qty_value=10000)
//DEMA
length=input(10,minval=1,title="DEMALENGTH")
src=input(close,title="Source")
e1=ema(src,length)
e2=ema(e1,length)
dema1=2*e1-e2
plot(dema1,"DEMA",color=color.yellow)
//EMA
len=input(25,minval=1,title="EMALength")
srb=input(close,title="Source")
offset=input(title="Offset",type=input.integer,defval=0,minval=-500,maxval=500)
ema1=ema(srb,len)
plot(ema1,title="EMA",color=color.blue,offset=offset)
//Inputs
atrTimeFrame=input("D",title="ATRTimeframe",type=input.resolution)
atrLookback=input(defval=14,title="ATRLookbackPeriod",type=input.integer)
useMA=input(title="ShowMovingAverage?",type=input.bool,defval=true)
maType=input(defval="EMA",options=["EMA","SMA"],title="MovingAverageType")
maLength=input(defval=20,title="MovingAveragePeriod",minval=1)
//longLossPerc=input(title="LongStopLoss(%)",
//type=input.float,minval=0.0,step=0.1,defval=1)*0.01
longTrailPerc=input(title="Trailstoploss(%)",
type=input.float,minval=0.0,step=0.1,defval=50)*0.01
longProfitPerc=input(title="LongTakeProfit(%)",
type=input.float,minval=0.0,step=0.1,defval=3000)/100
//===INPUTBACKTESTRANGE===
FromMonth=input(defval=1,title="FromMonth",minval=1,maxval=12)
FromDay=input(defval=1,title="FromDay",minval=1,maxval=31)
FromYear=input(defval=2017,title="FromYear",minval=2000)
ToMonth=input(defval=1,title="ToMonth",minval=1,maxval=12)
ToDay=input(defval=1,title="ToDay",minval=1,maxval=31)
ToYear=input(defval=9999,title="ToYear",minval=2017)
//ATRLogic//atrValue=atr(atrLookback)//atrp=(atrValue/close)*100//plot(atrp,color=color.white,linewidth=2,transp=30)
atrValue=security(syminfo.tickerid,atrTimeFrame,atr(atrLookback))
atrp=(atrValue/close)*100
//MovingAverageLogic
ma(maType,src,length)=>
maType=="EMA"?ema(src,length):sma(src,length)//TernaryOperator(ifmaTypeequalsEMA,thendoemacalc,elsedosmacalc)
maFilter=security(syminfo.tickerid,atrTimeFrame,ma(maType,atrp,maLength))
//variablesforenterposition
enterLong=crossover(dema1,ema1)andatrp<maFilter
//variablesforexitposition
sale=crossunder(dema1,ema1)
//stoploss
//longStopPrice=strategy.position_avg_price*(1-longLossPerc)
//trailstop
//Determinetrailstoplossprices
longStopTrail=0.0
longStopTrail:=if(strategy.position_size>0)
stopValue=close*(1-longTrailPerc)
max(stopValue,longStopTrail[1])
else
0
//TakeprofitPercentage
longExitPrice=strategy.position_avg_price*(1+longProfitPerc)
//Entertradeswhenconditionsaremet
strategy.entry(id="long",
long=strategy.long,
when=enterLong,
comment="long")
//
strategy.close("long",when=sale,comment="Sell")
//placeexitorders(onlyexecutedaftertradesareactive)
strategy.exit(id="sell",
limit=longExitPrice,
stop=longStopTrail,
comment="SL/TP")
Expand (91 lines)
