Script Name: DMI (Multi timeframe) DI Strategy [KL]
Author: DojiEmoji
Description: Directional Movement Index Strategy 

 Entry conditions: 
- (a) when DI+ > DI- on timeframe #1, and 
- (b) Confirmation: when DI+ > DI- on timeframe #2
In the shown example, timeframe1 was same as the chart (1H) and timeframe2 was 1D.

 Stop Loss:   ATR based trailing stop

 About DMI 
Can refer to  Investopedia  for general understanding.
 Applications of DMI in...
PineScript code:

Pine Script™ strategy
DMI (Multi timeframe) DI Strategy [KL]
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
//ThissourcecodeissubjecttothetermsoftheMozillaPublicLicense2.0athttps://mozilla.org/MPL/2.0/
//©DojiEmoji
//@version=5
strategy("DI+/-multiTFStrat[KL]",overlay=true,pyramiding=1,initial_capital=1000000000,default_qty_type=strategy.percent_of_equity,default_qty_value=5)
varstringGROUP_ALERT="Alerts"
varstringGROUP_SL="Stoploss"
varstringGROUP_ORDER="Ordersize"
varstringGROUP_TP="Profittaking"
varstringGROUP_HORIZON="Timehorizonofbacktests"
varstringGROUP_IND="DirectionalIndicatorDI+DI-"
//ADXIndicator{
adx_len=input(14,group=GROUP_IND,tooltip="Typically14")
tf1=input.timeframe("",title="DI+/-inTimeframe1",group=GROUP_IND,tooltip="Main:DI+>DI-")
tf2=input.timeframe("1D",title="DI+/-inTimeframe2",group=GROUP_IND,tooltip="Confirmation:DI+>DI-")
//adx_thres=input(20,group=GROUP_IND)//thresholdnotusedinthisstrategy
get_ADX(_high,_close,_low)=>
//(high,close,mid)->[plus_DM,minus_DM]
//BasedonTradingViewuserBeikabuOyaji'simplementation
_tr=math.max(math.max(_high-_low,math.abs(_high-nz(_close[1]))),math.abs(_low-nz(_close[1])))
smooth_tr=0.0
smooth_tr:=nz(smooth_tr[1])-nz(smooth_tr[1])/adx_len+_tr
smooth_directional_mov_plus=0.0
smooth_directional_mov_plus:=nz(smooth_directional_mov_plus[1])-nz(smooth_directional_mov_plus[1])/adx_len+(_high-nz(_high[1])>nz(_low[1])-_low?math.max(_high-nz(_high[1]),0):0)
smooth_directional_mov_minus=0.0
smooth_directional_mov_minus:=nz(smooth_directional_mov_minus[1])-nz(smooth_directional_mov_minus[1])/adx_len+(nz(_low[1])-_low>_high-nz(_high[1])?math.max(nz(_low[1])-_low,0):0)
plus_DM=smooth_directional_mov_plus/smooth_tr*100
minus_DM=smooth_directional_mov_minus/smooth_tr*100
//DX=math.abs(plus_DM-minus_DM)/(plus_DM+minus_DM)*100//DXnotusedinthisstrategy
[plus_DM,minus_DM]
nrp_security(_symbol,_tf,_src)=>
//Wrapperfunctionaroundrequest.security()-don'tusedevelopingbars
request.security(_symbol,_tf,_src[barstate.isrealtime?1:0],gaps=barmerge.gaps_off,lookahead=barmerge.lookahead_off)
//DI+/-fromtimeframes1and2
[plus_DM_tf1,minus_DM_tf1]=get_ADX(nrp_security(syminfo.tickerid,tf1,high),nrp_security(syminfo.tickerid,tf1,close),nrp_security(syminfo.tickerid,tf1,low))
[plus_DM_tf2,minus_DM_tf2]=get_ADX(nrp_security(syminfo.tickerid,tf2,high),nrp_security(syminfo.tickerid,tf2,close),nrp_security(syminfo.tickerid,tf2,low))
//}endofblock:ADXIndicator
varstringENUM_LONG="LONG"
varstringLONG_MSG_ENTER=input.string("Longentered",title="AlertMSGforbuying(Longposition)",group=GROUP_ALERT)
varstringLONG_MSG_EXIT=input.string("Longclosed",title="AlertMSGforclosing(Longposition)",group=GROUP_ALERT)
backtest_timeframe_start=input.time(defval=timestamp("01Apr202013:30+0000"),title="BacktestStartTime",group=GROUP_HORIZON)
within_timeframe=time>=backtest_timeframe_start
//Signalsforentry
_uptrend_confirmed=plus_DM_tf1>minus_DM_tf1andplus_DM_tf2>minus_DM_tf2
entry_signal_long=_uptrend_confirmed
plotshape(_uptrend_confirmed,style=shape.triangleup,location=location.bottom,color=color.green)
plotshape(not_uptrend_confirmed,style=shape.triangledown,location=location.bottom,color=color.red)
//Trailingstoploss("TSL"){
tsl_multi=input.float(2.0,title="ATRMultiplierfortrailingstoploss",group=GROUP_SL)
SL_buffer=ta.atr(input.int(14,title="LengthofATRfortrailingstoploss",group=GROUP_SL))*tsl_multi
TSL_source_long=low
varstop_loss_price_long=float(0)
varpos_opened_long=false
stop_loss_price_long:=pos_opened_long?math.max(stop_loss_price_long,TSL_source_long-SL_buffer):TSL_source_long-SL_buffer
//MAIN:{
ifpos_opened_longandTSL_source_long<=stop_loss_price_long
pos_opened_long:=false
alert(LONG_MSG_EXIT,alert.freq_once_per_bar)
strategy.close(ENUM_LONG,comment=close<strategy.position_avg_price?"stoploss":"takeprofit")
//(2)Updatethestoplosstolatesttrailingamt.
ifpos_opened_long
strategy.exit(ENUM_LONG,stop=stop_loss_price_long,comment="SL")
//(3)INITIALENTRY:
ifwithin_timeframeandentry_signal_long
pos_opened_long:=true
alert(LONG_MSG_ENTER,alert.freq_once_per_bar)
strategy.entry(ENUM_LONG,strategy.long,comment="long")
//Plotting:
TSL_transp_long=pos_opened_longandwithin_timeframe?0:100
plot(stop_loss_price_long,color=color.new(color.green,TSL_transp_long))
//CLEANUP:Settingvariablesbacktodefaultvaluesoncenolongerinuse
ifta.change(strategy.position_size)andstrategy.position_size==0
pos_opened_long:=false
ifnotpos_opened_long
stop_loss_price_long:=float(0)
//}endofMAINblock
Expand (97 lines)