Script Name: Donchian Channel Strategy Idea
Author: QuantCT
Description: This strategy idea is a variation of the "Donchian Channel" trading strategy. It is built with a highest-high band, a lowest-low band, and a baseline which is average the highest-high and the lowest-low bands. This strategy is very useful in trending instruments on 1W and 1D timeframes. This is the implementation used in the QuantCT app.

You can set the operation...
PineScript code:

Pine Script™ strategy
Donchian Channel Strategy Idea
//ThissourcecodeissubjecttothetermsoftheMozillaPublicLicense2.0athttps://mozilla.org/MPL/2.0/
//©QuantCT
//@version=4
strategy("DonchianChannelStrategyIdea",
shorttitle="Donchian",
overlay=true,
pyramiding=0,
default_qty_type=strategy.percent_of_equity,
default_qty_value=100,
initial_capital=1000,
commission_type=strategy.commission.percent,
commission_value=0.075)
//____Inputs
high_period=input(title="HighPeriod",defval=10)
low_period=input(title="LowPeriod",defval=10)
long_only=input(title="LongOnly",defval=false)
slp=input(title="Stop-loss(%)",minval=1.0,maxval=25.0,defval=5.0)
use_sl=input(title="UseStop-Loss",defval=false)
//____Logic
highest_high=highest(high,high_period)
lowest_low=lowest(low,low_period)
base_line=(highest_high+lowest_low)/2

enter_long=(close>highest_high[1])
exit_long=(close<base_line)
enter_short=(close<lowest_low[1])
exit_short=(close>base_line)
strategy.entry("Long",strategy.long,when=enter_long)
strategy.close("Long",when=exit_long)
if(notlong_only)
strategy.entry("Short",strategy.short,when=enter_short)
strategy.close("Short",when=exit_short)

//____SL
sl_long=strategy.position_avg_price*(1-(slp/100))
sl_short=strategy.position_avg_price*(1+(slp/100))
if(use_sl)
strategy.exit(id="SL",from_entry="Long",stop=sl_long)
strategy.exit(id="SL",from_entry="Short",stop=sl_short)

//____Plots
colors=
strategy.position_size>0?#27D600:
strategy.position_size<0?#E30202:
color.orange
highest_high_plot=plot(highest_high,color=colors)
lowest_low_plot=plot(lowest_low,color=colors)
plot(base_line,color=color.silver)
fill(highest_high_plot,lowest_low_plot,color=colors,transp=90)
Expand (65 lines)
