Script Name: Double Bollinger Strategy
Author: tweakerID
Description: From "Bitcoin Trading Strategies: Algorithmic Trading Strategies For Bitcoin And Cryptocurrency That Work" by David Hanson.

*Works better with 1hr time frame and some input optimisations.

"Double Bollinger Band Scalping System
Recommended Timeframe: 1 minute or 5 minute *

Required Indicators:
// - RSI with a length of 14 (default settings)
// - Bollinger...
PineScript code:

Pine Script™ strategy
Double Bollinger Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  From  "Bitcoin  Trading  Strategies:  Algorithmic  Trading  Strategies  For  Bitcoin  And  Cryptocurrency  That  Work"  by  David  Hanson.
//  "Double  Bolinger  Band  Scalping  System
//  Recommended  Timeframe:  1  minute  or  5  minute
//  Required  Indicators:
//  -  RSI  with  a  length  of  14  (default  settings)
//  -  Bolinger  band  #1  settings:  Length  =  50,  stDev  =  1  Hide  the  basis/middle  line  (basis  line  not  needed  for  this  strategy)
//  Note:  This  is  the  slower  bolinger  band  in  the  directions
//  -  Bolinger  band  #2  settings:  Length  20,  stDev  =  1  Hide  the  basis/middle  line  (basis  line  not  needed  for  this  strategy)
//  Note:  This  is  the  faster  bolinger  band  in  the  directions
//  Enter  Long/Buy  Trade  When:
//  -  RSI  is  above  the  level  50
//  -  A  candle  closes  above  the  top  of  the  faster  bolinger  band
//  Enter  a  long  when  a  candle  then  closes  above  the  top  of  the  slower  bolinger  band,  and  price  is  above  the  top  of  both  bands
//  Place  a  stop  loss  under  the  low  of  the  entry  candle  Example  of  a  long  trade  using  this  strategy
//  Exit  Long  Trade  When:  A  candle  closes  below  the  top  band  of  the  fast  bolinger  band
//  Enter  Short/Sell  Trade  When:
//  -  RSI  is  below  the  level  50
//  -  A  candle  closes  below  the  bottom  of  the  faster  bolinger  band
//  Enter  a  short  when  a  candle  then  closes  below  the  bottom  of  the  slower  bolinger  band,  and  price  is  below  both  bands
//  Place  a  stop  loss  above  the  high  of  the  entry  candle  Example  of  a  short  trade  using  this  strategy
//  Exit  Short  Trade  When:  Price  closes  inside  the  bottom  of  the  faster  bolinger  band"
//  ©  tweakerID
//@version=4
strategy("Double  Bollinger  Strategy",
          overlay=true,
          default_qty_type=strategy.percent_of_equity,
          default_qty_value=100,
          initial_capital=10000,
          commission_value=0.04,
          calc_on_every_tick=false,
          slippage=0)
direction  =  input(0,  title  =  "Strategy  Direction",  type=input.integer,  minval=-1,  maxval=1)
strategy.risk.allow_entry_in(direction  ==  0  ?  strategy.direction.all  :  (direction  <  0  ?  strategy.direction.short  :  strategy.direction.long))
///////////////////////  STRATEGY  INPUTS  ////////////////////////////////////////
title1=input(true,  "-----------------Strategy  Inputs-------------------")
i_RSI=input(14,  title="RSI  Length")
lengthS  =  input(45,  minval=1,  title="Slow  BB  Band  Length")
lengthF  =  input(31,  minval=1,  title="Fast  BB  Band  Length")
///////////////////////  BACKTESTER  /////////////////////////////////////////////
title2=input(true,  "-----------------General  Inputs-------------------")
//  Backtester  General  Inputs
i_SL=input(true,  title="Use  Stop  Loss  and  Take  Profit")
i_SLType=input(defval="Strategy  Stop",  title="Type  Of  Stop",  options=["Strategy  Stop",  "Swing  Lo/Hi",  "ATR  Stop"])
i_SPL=input(defval=10,  title="Swing  Point  Lookback")
i_PercIncrement=input(defval=1,  step=.1,  title="Swing  Point  SL  Perc  Increment")*0.01
i_ATR  =  input(14,  title="ATR  Length")
i_ATRMult  =  input(5,  step=.1,  title="ATR  Multiple")
i_TPRRR  =  input(2,  step=.1,  title="Take  Profit  Risk  Reward  Ratio")
TS=input(false,  title="Trailing  Stop")
//  Bought  and  Sold  Boolean  Signal
bought  =  strategy.position_size  >  strategy.position_size[1]
  or  strategy.position_size  <  strategy.position_size[1]
//  Price  Action  Stop  and  Take  Profit
LL=(lowest(i_SPL))*(1-i_PercIncrement)
HH=(highest(i_SPL))*(1+i_PercIncrement)
LL_price  =  valuewhen(bought,  LL,  0)
HH_price  =  valuewhen(bought,  HH,  0)
entry_LL_price  =  strategy.position_size  >  0  ?  LL_price  :  na
entry_HH_price  =  strategy.position_size  <  0  ?  HH_price  :  na
tp=strategy.position_avg_price  +  (strategy.position_avg_price  -  entry_LL_price)*i_TPRRR
stp=strategy.position_avg_price  -  (entry_HH_price  -  strategy.position_avg_price)*i_TPRRR
//  ATR  Stop
ATR=atr(i_ATR)*i_ATRMult
ATRLong  =  ohlc4  -  ATR
ATRShort  =  ohlc4  +  ATR
ATRLongStop  =  valuewhen(bought,  ATRLong,  0)
ATRShortStop  =  valuewhen(bought,  ATRShort,  0)
LongSL_ATR_price  =  strategy.position_size  >  0  ?  ATRLongStop  :  na
ShortSL_ATR_price  =  strategy.position_size  <  0  ?  ATRShortStop  :  na
ATRtp=strategy.position_avg_price  +  (strategy.position_avg_price  -  LongSL_ATR_price)*i_TPRRR
ATRstp=strategy.position_avg_price  -  (ShortSL_ATR_price  -  strategy.position_avg_price)*i_TPRRR
//  Strategy  Stop
float  LongStop  =  valuewhen(bought,low[1],0)*(1-i_PercIncrement)
float  ShortStop  =valuewhen(bought,high[1],0)*(1+i_PercIncrement)
floatStratTP=na
floatStratSTP=na
///////////////////////STRATEGYLOGIC/////////////////////////////////////////
//RSI
RSI=rsi(close,i_RSI)
//BOLL1
[middleS,upperS,lowerS]=bb(close,lengthS,1)
p1=plot(upperS,"SlowBBUpperBand",color=color.teal)
p2=plot(lowerS,"SlowBBLowerBand",color=color.teal)
fill(p1,p2,title="SlowBBBackground",color=color.blue,transp=95)
//BOLL2
[middleF,upperF,lowerF]=bb(close,lengthF,1)
p1F=plot(upperF,"FastBBUpperBand",color=color.gray)
p2F=plot(lowerF,"FastBBLowerBand",color=color.gray)
fill(p1F,p2F,title="FastBBBackground",color=color.white,transp=95)
BUY=bar_index>40and(RSI>50)and(close>upperF)andcrossover(close,upperS)
SELL=bar_index>40and(RSI<50)and(close<lowerF)andcrossunder(close,lowerS)
longexit=close<upperF
shortexit=close>lowerF
//TradingInputs
i_strategyClose=input(true,title="UseStrategyCloseLogic")
DPR=input(true,"AllowDirectPositionReverse")
reverse=input(false,"ReverseTrades")
//Entries
ifreverse
ifnotDPR
strategy.entry("long",strategy.long,when=SELLandstrategy.position_size==0)
strategy.entry("short",strategy.short,when=BUYandstrategy.position_size==0)
else
strategy.entry("long",strategy.long,when=SELL)
strategy.entry("short",strategy.short,when=BUY)
else
ifnotDPR
strategy.entry("long",strategy.long,when=BUYandstrategy.position_size==0)
strategy.entry("short",strategy.short,when=SELLandstrategy.position_size==0)
else
strategy.entry("long",strategy.long,when=BUY)
strategy.entry("short",strategy.short,when=SELL)
ifi_strategyClose
strategy.close("long",when=longexit)
strategy.close("short",when=shortexit)

SL=i_SLType=="SwingLo/Hi"?entry_LL_price:i_SLType=="ATRStop"?LongSL_ATR_price:LongStop
SSL=i_SLType=="SwingLo/Hi"?entry_HH_price:i_SLType=="ATRStop"?ShortSL_ATR_price:ShortStop
TP=i_SLType=="SwingLo/Hi"?tp:i_SLType=="ATRStop"?ATRtp:StratTP
STP=i_SLType=="SwingLo/Hi"?stp:i_SLType=="ATRStop"?ATRstp:StratSTP
//TrailingStop
dif=(valuewhen(strategy.position_size>0andstrategy.position_size[1]<=0,high,0))
-strategy.position_avg_price
trailOffset=strategy.position_avg_price-SL
vartstop=float(na)
ifstrategy.position_size>0
tstop:=high-trailOffset-dif
iftstop<tstop[1]
tstop:=tstop[1]
else
tstop:=na
StrailOffset=SSL-strategy.position_avg_price
varStstop=float(na)
Sdif=strategy.position_avg_price-(valuewhen(strategy.position_size<0
andstrategy.position_size[1]>=0,low,0))
ifstrategy.position_size<0
Ststop:=low+StrailOffset+Sdif
ifStstop>Ststop[1]
Ststop:=Ststop[1]
else
Ststop:=na
strategy.exit("TP&SL","long",limit=TP,stop=TS?tstop:SL,when=i_SL)
strategy.exit("TP&SL","short",limit=STP,stop=TS?Ststop:SSL,when=i_SL)
///////////////////////PLOTS//////////////////////////////////////////////////
plot(i_SLandstrategy.position_size>0andnotTS?SL:i_SLandstrategy.position_size>0andTS?tstop:na,title='SL',style=plot.style_cross,color=color.red)
plot(i_SLandstrategy.position_size<0andnotTS?SSL:i_SLandstrategy.position_size<0andTS?Ststop:na,title='SSL',style=plot.style_cross,color=color.red)
plot(i_SLandstrategy.position_size>0?TP:na,title='TP',style=plot.style_cross,color=color.green)
plot(i_SLandstrategy.position_size<0?STP:na,title='STP',style=plot.style_cross,color=color.green)
//Drawpriceactionsetuparrows
plotshape(BUY?1:na,style=shape.triangleup,location=location.belowbar,
color=color.green,title="BullishSetup",size=size.auto)
plotshape(SELL?1:na,style=shape.triangledown,location=location.abovebar,
color=color.red,title="BearishSetup",size=size.auto)
Expand (189 lines)
