Script Name: Easy System 420
Author: SeaSide420
Description: In this strategy, 15 indicators are used, each giving its results as a numerical value, which then is added or subtracted from the total points, gathered from all 15 indicators.
 Many thanks to RafaelZioni for his great work making the EasySys1 script which i modified to create this script.
Onchart is drawn some of the indicators, but not all, a info panel is...
PineScript code:

Pine Script™ strategy
Easy System 420
//@version=4
strategy(title="Easy  Sys  420",  shorttitle="EasySys420",overlay=true,default_qty_type=strategy.percent_of_equity,default_qty_value=100,commission_type=strategy.commission.percent,commission_value=0.01,slippage=1)
hilow  =  ((high  -  low)*100)
openclose  =  ((close  -  open)*100)
vol1  =  (volume  /  hilow)
spreadvol  =  (openclose  *  vol1)
VPT  =  spreadvol  +  cum(spreadvol)
window_len  =  28
v_len  =  14
price_spread  =  stdev(high-low,  window_len)
vp  =    spreadvol  +  cum(spreadvol)
smooth  =  sma(vp,  v_len)
v_spread  =  stdev(vp  -  smooth,  window_len)
shadow  =  (vp  -  smooth)  /  v_spread  *  price_spread
out1  =  shadow  >  0  ?  high  +  shadow  :  low  +  shadow
//  INPUTS  //
src                  =  input(open,title="Source")
EnterPoints  =  input(15,minval=0,maxval=24,title="EnterPoints")
Period            =  input(14,minval=2,maxval=1000,title="Hull  MA  Period")
AF_initial    =  input(0.02,minval=0.00,maxval=1,step=0.01,title="AF_initial")
AF_increment=  input(0.02,minval=0.00,maxval=1,step=0.01,title="AF_increment")
AF_maximum    =  input(0.2,minval=0.0,maxval=1,step=0.1,title="AF_maximum")
len                  =  input(5,title="Length")
Depth              =  input(12,title="Depth")
Deviation      =  input(5,title="Deviation")
st_mult          =  input(3,minval=0,maxval=100,step=0.1,  title="SuperTrend  Multiplier")
st_period      =  input(7,minval=1,title="SuperTrend  Period")
multi              =  input(0.5,minval=0.0,maxval=3.0,step=0.1,title="Divergence  Channel  Width  Factor  (Stddev)")
uDiv                =  input(true,title="Show  Divergence  Channel")
uHid                =  input(true,title="Show  Hidden  Divergence")
uReg                =  input(true,title="Show  Regular  Divergence")
disp_panels  =  input(true,  title="Display  info  panels?")
info_label_pos=input(title="Info  panel  position",defval=-10,minval=-1000,maxval=1000)
info_label_size=input(size.normal,  options=[size.tiny,  size.small,  size.normal,  size.large,  size.huge],  title="Info  panel  label  size")
vpt=ema(out1,len)
uDiv  :=  uReg  or  uHid  ?  uDiv  :  false
up_lev  =  vpt  -  (st_mult  *  atr(st_period))
dn_lev  =  vpt  +  (st_mult  *  atr(st_period))
up_trend      =  0.0
up_trend      :=  src[1]  >  up_trend[1]      ?  max(up_lev,  up_trend[1])      :  up_lev
down_trend  =  0.0
down_trend  :=  src[1]  <  down_trend[1]  ?  min(dn_lev,  down_trend[1])  :  dn_lev
//  Calculate  trend  var
trend10  =  0
trend10  :=  src  >  down_trend[1]  ?  1:  src  <  up_trend[1]  ?  -1  :  nz(trend10[1],  1)
//  Calculate  SuperTrend  Line
st_line  =  trend10  ==1  ?  up_trend  :  down_trend
//
f_top_fractal(_src)  =>
        _src[4]  <  _src[2]  and  _src[3]  <  _src[2]  and  _src[2]  >  _src[1]  and
              _src[2]  >  _src[0]
f_bot_fractal(_src)  =>
        _src[4]  >  _src[2]  and  _src[3]  >  _src[2]  and  _src[2]  <  _src[1]  and
              _src[2]  <  _src[0]
f_fractalize(_src)  =>
        f_bot_fractal__1  =  f_bot_fractal(_src)
        f_top_fractal(_src)  ?  1  :  f_bot_fractal__1  ?  -1  :  0
//
ST_high  =  st_line
ST_low  =  st_line
offset_  =  multi  *  stdev(st_line,  20)
fractal_top_ST  =  f_fractalize(ST_high)  >  0  ?  ST_high[2]  :  na
fractal_bot_ST  =  f_fractalize(ST_low)  <  0  ?  ST_low[2]  :  na
ST_high_prev  =  valuewhen(fractal_top_ST,  ST_high[2],  1)
ST_high_price  =  valuewhen(fractal_top_ST,  high[2],  1)
ST_low_prev  =  valuewhen(fractal_bot_ST,  ST_low[2],  1)
ST_low_price  =  valuewhen(fractal_bot_ST,  low[2],  1)
regular_bearish_div  =  fractal_top_ST  and  high[2]  >  ST_high_price  and  ST_high[2]  <  ST_high_prev  and
    ST_high  >  0
hidden_bearish_div  =  fractal_top_ST  and  high[2]  <  ST_high_price  and  ST_high[2]  >  ST_high_prev  and
      ST_high  >  0
regular_bullish_div  =  fractal_bot_ST  and  low[2]  <  ST_low_price  and  ST_low[2]  >  ST_low_prev  and
      ST_low  <  0
hidden_bullish_div  =  fractal_bot_ST  and  low[2]  >  ST_low_price  and  ST_low[2]  <  ST_low_prev  and
ST_low<0
color1=trend10==1?color.lime:color.orange
plot(title='STHigh',series=uDiv?ST_high:na,color=color1)
plot(title='STLow',series=uDiv?ST_low:na,color=color1)
plot(title='STHF',series=uDiv?fractal_top_ST+offset_:na,color=color.red,offset=-2)
plot(title='STLF',series=uDiv?fractal_bot_ST-offset_:na,color=color.green,offset=-2)
plot(title='STHD',series=uDiv?fractal_top_ST+offset_:na,style=plot.style_circles,color=regular_bearish_divanduRegorhidden_bearish_divanduHid?color.maroon:color.red,linewidth=5,offset=-2)
plot(title='STLD',series=uDiv?fractal_bot_ST-offset_:na,style=plot.style_circles,color=regular_bullish_divanduRegorhidden_bullish_divanduHid?color.green:color.blue,linewidth=5,offset=-2)
plotshape(title='+RBD',series=regular_bearish_divanduReg?ST_high[2]+offset_:na,text='Regular',style=shape.labeldown,location=location.absolute,color=color.maroon,textcolor=color.white,offset=-2)
plotshape(title='+HBD',series=hidden_bearish_divanduHid?ST_high[2]+offset_:na,text='hidden',style=shape.labeldown,location=location.absolute,color=color.maroon,textcolor=color.white,offset=-2)
plotshape(title='-RBD',series=regular_bullish_divanduReg?ST_low[2]-offset_:na,text='Regular',style=shape.labelup,location=location.absolute,color=color.green,textcolor=color.white,offset=-2)
plotshape(title='-HBD',series=hidden_bullish_divanduHid?ST_low[2]-offset_:na,text='hidden',style=shape.labelup,location=location.absolute,color=color.green,textcolor=color.white,offset=-2)
//ZigZag
lastlow=0.0,lasthigh=0.0
lastlow:=nz(lastlow[1])
lasthigh:=nz(lasthigh[1])
data(x)=>
d=security(syminfo.tickerid,timeframe.period,x,gaps=barmerge.gaps_off,lookahead=barmerge.lookahead_off)
d
getLow(x,y,z,a)=>
lastlow=y
v=data(x)
m=v==lastlowordata(z)-v>a*syminfo.mintick
ifv!=lastlow
lastlow:=v
ifm
v:=0.0
[v,lastlow]
getHigh(x,y,z,a)=>
lasthigh=y
v=data(x)
m=v==lasthighorv-data(z)>a*syminfo.mintick
ifv!=lasthigh
lasthigh:=v
ifm
v:=0.0
[v,lasthigh]
[v,e]=getLow(lowest(Depth),lastlow,low,Deviation)
lastlow:=e
zBB=v!=0.0
[v1,e1]=getHigh(highest(Depth),lasthigh,high,Deviation)
lasthigh:=e1
zSS=v1!=0.0
zigzagDirection=-1
zigzagHigh=0
zigzagLow=0
zigzagDirection:=zBB?0:zSS?1:nz(zigzagDirection[1],-1)
virtualLow=zigzagLow[1]+1
ifnotzBBor(zBBandzigzagDirection==zigzagDirection[1]andlow>low[virtualLow])
zigzagLow:=nz(zigzagLow[1])+1
virtualHigh=zigzagHigh[1]+1
ifnotzSSor(zSSandzigzagDirection==zigzagDirection[1]andhigh<high[virtualHigh])
zigzagHigh:=nz(zigzagHigh[1])+1
a=bar_index-zigzagLow
b=bar_index-zigzagHigh
varcolorc=na,c:=fixnan(a<b[1]?color.lime:a>b[1]?color.red:na)
linezigzag=line.new(bar_index-zigzagLow,low[zigzagLow],bar_index-zigzagHigh,high[zigzagHigh],color=c,style=line.style_solid,width=4)
if(zigzagDirection==zigzagDirection[1])
line.delete(zigzag[1])

zzPrevHigh=zigzagHigh[1]
zzPrevLow=zigzagLow[1]
ifnotna(zzPrevHigh[1])
zzPrevHigh:=zzPrevHigh[1]+1
ifnotna(zzPrevLow[1])
zzPrevLow:=zzPrevLow[1]+1
ifzigzagDirection!=zigzagDirection[1]
ifzigzagDirection==1
zzPrevHigh:=zigzagHigh[1]+1
ifzigzagDirection==0
zzPrevLow:=zigzagLow[1]+1

//sma
sma20=sma(src,20)
smapoint=0
smapoint:=src>sma20?smapoint+1:smapoint-1
//AO
ao=sma(hl2,5)-sma(hl2,34)
aopoint=ao>0?1:ao<0?-1:0
//momentum
mom=src-src[14]
mompoint=mom>0?1:mom<0?-1:0
//MACD
fast_ma=ema(src,12)
slow_ma=ema(src,26)
macd=fast_ma-slow_ma
signal=ema(macd,9)
hist=macd-signal
histpoint=hist>hist[1]?3:-3
//Bullbear
Length=30
r1=iff(close[1]<open,max(open-close[1],high-low),high-low)
r2=iff(close[1]>open,max(close[1]-open,high-low),high-low)
bull=iff(close==open,iff(high-close==close-low,iff(close[1]>open,max(high-open,close-low),r1),iff(high-close>close-low,iff(close[1]<open,max(high-close[1],close-low),high-open),r1)),iff(close<open,iff(close[1]<open,max(high-close[1],close-low),max(high-open,close-low)),r1))
bear=iff(close==open,iff(high-close==close-low,iff(close[1]<open,max(open-low,high-close),r2),iff(high-close>close-low,r2,iff(close[1]>open,max(close[1]-low,high-close),open-low))),iff(close<open,r2,iff(close[1]>open,max(close[1]-low,high-close),max(open-low,high-close))))
colors=iff(sma(bull-bear,Length)>0,color.green,color.red)
bbpoint=sma(bull-bear,Length)>0?1:-1
//UO
length7=7,
length14=14,
length28=28
average(bp,tr_,length)=>sum(bp,length)/sum(tr_,length)
high_=max(high,src[1])
low_=min(low,src[1])
bp=src-low_
tr_=high_-low_
avg7=average(bp,tr_,length7)
avg14=average(bp,tr_,length14)
avg28=average(bp,tr_,length28)
uoout=100*(4*avg7+2*avg14+avg28)/7
uopoint=uoout>70?1:uoout<30?-1:0
//IC
conversionPeriods=9
basePeriods=26
laggingSpan2Periods=52
displacement=26
donchian(len)=>avg(lowest(len),highest(len))
baseLine=donchian(basePeriods)
icpoint=src>baseLine?2:-2
//HMA
hullma=hma(src,Period)
hmapoint=src>hullma?1:-1
//
trendDetectionLength=4
floattrend=na
floatwave=na
floatvol=na
mov=src>src[1]?1:src<src[1]?-1:0
trend:=(mov!=0)and(mov!=mov[1])?mov:nz(trend[1])
isTrending=rising(src,trendDetectionLength)orfalling(src,trendDetectionLength)
wave:=(trend!=nz(wave[1]))andisTrending?trend:nz(wave[1])
vol:=wave==wave[1]?(nz(vol[1])+volume):volume
up1=wave==1?vol:0
dn1=wave==1?0:vol
Weis=up1>dn1?2:-2
//
stochlen=14
roclen=20
ccilen=21
dilen=5
dirmov(len)=>
up=change(high)
down=-change(low)
truerange=rma(tr,len)
plus=fixnan(100*rma(up>downandup>0?up:0,len)/truerange)
minus=fixnan(100*rma(down>upanddown>0?down:0,len)/truerange)
[plus,minus]
f_draw_infopanel(_x,_y,_line,_text,_color)=>
_rep_text=""
for_l=0to_line
_rep_text:=_rep_text+"\n"
_rep_text:=_rep_text+_text
varlabel_la=na
label.delete(_la)
_la:=label.new(
x=_x,y=_y,
text=_rep_text,xloc=xloc.bar_time,yloc=yloc.price,
color=color.black,style=label.style_labelup,textcolor=_color,size=size.normal)
TD=0
TS=0
TD:=src>src[4]?nz(TD[1])+1:0
TS:=src<src[4]?nz(TS[1])+1:0
TDUp=TD-valuewhen(TD<TD[1],TD,1)
TDDn=TS-valuewhen(TS<TS[1],TS,1)
stoch=stoch(src,high,low,stochlen)
roc=roc(src,roclen)
Roc=roc>0?1:-1
cci=cci(src,ccilen)
CCI=cci>0?1:-1
[plus,minus]=dirmov(dilen)
dmi=plus-minus
DMI=dmi>=0?2:-2
//
Zig=a<b?1:-1
//
STT=trend10==1?3:-3
//startwithuptrend
uptrend=true
newtrend=false
EP=high
SAR=low
AF=AF_initial
ifnotna(uptrend[1])andnotna(newtrend[1])
ifuptrend[1]
EP:=max(high,EP[1])
else
EP:=min(low,EP[1])
ifnewtrend[1]
AF:=AF_initial
else
ifEP!=EP[1]
AF:=min(AF_maximum,AF[1]+AF_increment)
else
AF:=AF[1]
SAR:=SAR[1]+AF*(EP-SAR[1])
ifuptrend[1]
ifnewtrend
SAR:=max(high,EP[1])
EP:=min(low,low[1])
else
SAR:=min(SAR,low[1])
ifnotna(low[2])
SAR:=min(SAR,low[2])
ifSAR>low
uptrend:=false
newtrend:=true
SAR:=max(high,EP[1])
EP:=min(low,low[1])
else
uptrend:=true
newtrend:=false
else
ifnewtrend
SAR:=min(low,EP[1])
EP:=max(high,high[1])
else
SAR:=max(SAR,high[1])
ifnotna(high[2])
SAR:=max(SAR,high[2])
ifSAR<high
uptrend:=true
newtrend:=true
SAR:=min(low,EP[1])
EP:=max(high,high[1])
else
uptrend:=false
newtrend:=false

x=src-SAR
sar=x>0?3:-3
totalpoints=sar+STT+Zig+Roc+DMI+CCI+Weis+smapoint+aopoint+mompoint+histpoint+bbpoint+icpoint+hmapoint
color2=trend10==1?color.lime:color.red
Bgcolor=input(true,title="Bgcolor")
bgcolor(Bgcolor?color2:na)
info_panel_x=timenow-round(change(time)*info_label_pos)
info_panel_y=src
BuyPoints=EnterPoints
SellPoints=EnterPoints-(EnterPoints*2)
info_title="--EasySys420--"+"\n\"
info_div1="\n\SupTrend"+tostring(trend10)
info_div2="\n\SAR"+tostring(sar)
info_div3="\n\STT"+tostring(STT)
info_div4="\n\Zig"+tostring(Zig)
info_div5="\n\Roc"+tostring(Roc)
info_div6="\n\DMI"+tostring(DMI)
info_div7="\n\CCI"+tostring(CCI)
info_div8="\n\Weis"+tostring(Weis)
info_div9="\n\SMA"+tostring(smapoint)
info_div10="\n\AO"+tostring(aopoint)
info_div11="\n\MOM"+tostring(mompoint)
info_div12="\n\Hist"+tostring(histpoint)
info_div13="\n\BB"+tostring(bbpoint)
info_div14="\n\Ichi"+tostring(icpoint)
info_div15="\n\HMA"+tostring(hmapoint)
info_div16="\n\------------------"
info_current_close="\n\Totalpoints:"+tostring(totalpoints)+"\n\------------------"
info_current_buy="\n\Buying@:"+tostring(BuyPoints)
info_current_sell="\n\Selling@:"+tostring(SellPoints)
info_text=info_title+info_div1+info_div2+info_div3+info_div4+info_div5+info_div6+info_div7+info_div8+info_div9+info_div10+info_div11+info_div12+info_div13+info_div14+info_div15+info_div16+info_current_close+info_current_buy+info_current_sell
info_panel=disp_panels?label.new(x=info_panel_x,y=info_panel_y,text=info_text,xloc=xloc.bar_time,yloc=yloc.price,color=color.yellow,style=label.style_labelup,textcolor=color.black,size=info_label_size):na
label.delete(info_panel[1])
if(totalpoints>BuyPointsandtrend10==1orZig==1andtrend10==1)
strategy.entry("BUY",strategy.long)
if(totalpoints<SellPointsandtrend10==-1orZig==-1andtrend10==-1)
strategy.entry("SELL",strategy.short)
///L'-,
//,'-./MM../L'-,
//._,--dMMMM\/MMM`../'-,
//:_,--,)MMMMMMMMM),.`QMM,<>/_'-,'
//;___,--.\MM(`-')M//MM\`,',.;.-'*;.'
//|\MMMMMM)\MM\,dM//MMM/___<,;`.)`--'/
//|\MM()MMMM)__/MM(/MP'___,\\``.`./__,,'
//|MMMM/MMMMMM(/MMMMP'__,\|/`.`-,_\/
//|MM/MMM---'`--'_\|-'|/`./.\----.___
//|/MM'`--'__,-\""|-'|_,`.__)..F.)-.
//|`--'\\|-'|_,_,-/J...J-'-.`-.,
//|__\`.|||\/_|....\`-.F
//|___/\|`|'__\|/-'F....\'`
//|\\\/|__/\||,-'__,-J.....\
//||/|/__,-\)\/|_,-__,--'|..__.----,'
//||/___\|'.|/__,--'`.-;;;;;;;;;\
//|___\\||`__,--'/;;;;;;;;;;;;.
//|\\|-'\'__,--'/;;;;;;;;;;;;;;\
//\||/|__,--'`--;;/\;-'\
//\||/__,--'//\\
//\|__,--'//\\
//\|__,--'_,-;M-K,,;-;\
//<;;;;;;;;'-;;;;
//~pricelessartworkbySeaSide420
Expand (376 lines)
