Script Name: EMA SCALPEUR LONG V2
Author: YukalMoon
Description: THIS IS A TRY TO FIND THE BEST EMAS FOR SCALPING
YOU HAVE 4 EMAS, YOU CAN CHOOSE 2 FOR THE ENTER
This a try to find the best EMAs for scalping
you have 4 EMAs, 2 to find the best enter possible and 2 others to find the best way out possible
PineScript code:

Pine Script™ strategy
EMA SCALPEUR LONG V2
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  YukalMoon
//@version=5
strategy(title="EMA  SCALPEUR",  overlay=true,  initial_capital  =  1000)
////  input  controls
EMA_L  =  input.int  (title  =  "EMA_L",  defval  =  9,  minval  =  1,  maxval  =  100,  step  =1)
EMA_L2  =  input.int  (title  =  "EMA_L2",  defval  =  26,  minval  =  1,  maxval  =  100,  step  =1)
EMA_S  =  input.int  (title  =  "EMA_S",  defval  =  100,  minval  =  1,  maxval  =  100,  step  =1)
EMA_S2  =  input.int  (title  =  "EMA_S2",  defval  =  55,  minval  =  1,  maxval  =  100,  step  =1)
///  mise  en  place  de  ema
shortest  =  ta.ema(close,  9)
short  =  ta.ema(close,  26)
longer  =  ta.ema(close,  100)
longest  =  ta.ema(close,  55)
plot(shortest,  color  =  color.red)
plot(short,  color  =  color.orange)
plot(longer,  color  =  color.aqua)
plot(longest,  color  =  color.yellow)
plot(close)
////  trading  indicators
EMA1  =  ta.ema  (close,EMA_L)
EMA2  =  ta.ema  (close,EMA_L2)
EMA3  =  ta.ema  (close,  EMA_S)
EMA4  =  ta.ema  (close,  EMA_S2)
buy  =  ta.crossover(EMA1,  EMA2)
//sell  =  ta.crossunder(EMA1,  EMA2)
buyexit  =  ta.crossunder(EMA3,  EMA4)
//sellexit  =  ta.crossover(EMA3,  EMA4)
/////strategy
strategy.entry  ("long",  strategy.long,  when  =  buy,  comment  =  "EXIT-LONG")
//strategy.entry  ("short",  strategy.short,  when  =  sell,  comment  =  "ENTER-SHORT")
/////  market  exit
strategy.close  ("long",  when  =  buyexit,  comment  =  "ENTER-LONG")
//strategy.close  ("short",    when  =  sellexit,  comment  =  "EXIT-SHORT")
Expand (65 lines)
