Script Name: Fibonacci Zone DCA Strategy - R3c0nTrader
Author: R3c0nTrader
Description: Credits:
Thank you "eykpunter" for granting me permission to use "Fibonacci Zones" to create this strategy
Thank you "junyou0424" for granting me permission to use "DCA Bot with SuperTrend Emulator" which I used for adding bot inputs, calculations, and strategy

Pre-requisites:
You can use this script without a 3Commas account and see how 3Commas DCA Bot would...
PineScript code:

Pine Script™ strategy
Fibonacci Zone DCA Strategy - R3c0nTrader
//  ©  Fibonacci  Zone  DCA  Strategy  -  R3c0nTrader  ver  2022-07-09
//  For  backtesting  with  3Commas  DCA  Bot  settings
//  Thank  you  "eykpunter"  for  granting  me  permission  to  use  "Fibonacci  Zones"  to  create  this  strategy
//  Thank  you  "junyou0424"  for  granting  me  permission  to  use  "DCA  Bot  with  SuperTrend  Emulator"  which  I  used  for  adding  bot  inputs,  calculations,  and  strategy
//@version=5
strategy('Fibonacci  Zone  DCA  Strategy  -  R3c0nTrader',  shorttitle='Fibonacci  Zone  DCA  Strategy',  overlay=true,  pyramiding=999,  default_qty_type=strategy.cash,  initial_capital=10000,  commission_value=0.0,  use_bar_magnifier=true,  process_orders_on_close=true)
//  Strategy  Inputs
//  Start  and  End  Dates
i_startTime  =  input.time(defval=timestamp('01  Jan  2015  00:00  +0000'),  title='Start  Time',  group="Date  Range")
i_endTime  =  input.time(defval=timestamp('31  Dec  2050  23:59  +0000'),  title='End  Time',  group="Date  Range")
inDateRange  =  time  >=  i_startTime  and  time  <=  i_endTime
//  Start:  Fibonacci  Settings----------------------------------------------------
sourceInput  =  input.source(close,  "Source",  group="Fibonacci  Trade  Entry  Settings")
per  =  input(14,  title='Fibonacci  length',  tooltip='Number  of  bars  to  look  back.  Recommended  for  beginners  to  set  ADX  Smoothing  and  DI  Length  to  the  same  value  as  this.',  group="Fibonacci  Trade  Entry  Settings")
hl  =  ta.highest(high,  per)    //Top-High  Fib  Border
ll  =  ta.lowest(low,  per)        //Top-Low  Fib  Border
dist  =  hl  -  ll                            //Range  of  the  channel
hf  =  hl  -  dist  *  0.236            //Bottom-High  Fib  Border
cfh  =  hl  -  dist  *  0.382          //Top-Center  Fib  Border
cfl  =  hl  -  dist  *  0.618          //Bottom-Center  Fib  Border
lf  =  hl  -  dist  *  0.764            //Top-Low  Fib  Border
//  Start:  ADX  Settings
lensig  =  input.int(14,  title="ADX  Smoothing",  tooltip='Fibonacci  signals  work  best  when  market  is  trending.  ADX  is  used  to  measure  trend  strength.  Default  value  is  14.  Recommend  for  beginners  to  match  this  with  Fibonacci  length  and  DI  Length',minval=1,  maxval=50,  group="Fibonacci  Trade  Entry  Settings")
len  =  input.int(14,  minval=1,  title="DI  Length",  tooltip='Fibonacci  signals  work  best  when  market  is  trending.  DI  Length  is  used  to  calculate  ADX  to  measure  trend  strength.  Default  value  is  14.  Recommend  for  beginners  to  match  this  with  Fibonacci  length  and  ADX  Smoothing.',  group="Fibonacci  Trade  Entry  Settings")
adx_min  =  input.int(25,  title='Min  ADX  value  to  open  trade',  tooltip='Use  this  to  set  the  minium  ADX  value  (trend  strength)  to  open  trade.  25  or  higher  is  recommended  for  beginners.  0  to  20  is  a  weak  trend.  25  to  35  is  a  strong  trend.  35  to  45  is  a  very  strong  trend.  45  to  100  is  an  extremely  strong  trend.',  group="Fibonacci  Trade  Entry  Settings")
adx_max  =  input.int(100,  title='Max  ADX  value  to  open  trade',  tooltip='Use  this  to  set  the  maximum  ADX  value  (trend  strength)  to  open  trade.  100  is  recommended  for  beginners.  0  to  20  is  a  weak  trend.  25  to  35  is  a  strong  trend.  35  to  45  is  a  very  strong  trend.  45  to  100  is  an  extremely  strong  trend.',  group="Fibonacci  Trade  Entry  Settings")
up  =  ta.change(high)
down  =  -ta.change(low)
plusDM  =  na(up)  ?  na  :  (up  >  down  and  up  >  0  ?  up  :  0)
minusDM  =  na(down)  ?  na  :  (down  >  up  and  down  >  0  ?  down  :  0)
trur  =  ta.rma(ta.tr,  len)
di_plus  =  fixnan(100  *  ta.rma(plusDM,  len)  /  trur)
di_minus  =  fixnan(100  *  ta.rma(minusDM,  len)  /  trur)
sum  =  di_plus  +  di_minus
adx  =  100  *  ta.rma(math.abs(di_plus  -  di_minus)  /  (sum  ==  0  ?  1  :  sum),  lensig)
adx_inrange  =  adx  >=  adx_min  and  adx  <=  adx_max
//  End:  ADX  Settings
//  Input  to  setup  Buy  signals  when  the  source  crosses  a  fib  border
entry_trigger  =  input.string("1-Crosses",  title="Buy  signals  when  the  source:  [cont.]",  options=["1-Crosses",  "2-Crosses  up",  "3-Crosses  down"],  tooltip="'Crosses'  includes  up  and  down  movements.  'Crosses  Up'  only  includes  up  movements.  'Crosses  Down'  only  includes  down  movements"  ,  group="Fibonacci  Trade  Entry  Settings")
e_trig  =  0
if  entry_trigger  ==  "1-Crosses"
        e_trig  :=  1
else  if  entry_trigger  ==  "2-Crosses  up"
        e_trig  :=  2
else  if  entry_trigger  ==  "3-Crosses  down"
        e_trig  :=  3
entry_choice  =  input.string("6-Bottom-Low  Fib  Border",  title="...The  Fib  line:",  options=["1-Top-High  Fib  Border",  "2-Bottom-High  Fib  Border",  "3-Top-Center  Fib  Border",  "4-Bottom-Center  Fib  Border",  "5-Top-Low  Fib  Border",  "6-Bottom-Low  Fib  Border"],
      tooltip='There  are  three  fib  zones  and  each  zone  has  2  borders  (Top  &  Bottom).  The  options  are  listed  from  the  top  zone  to  the  bttom  zone.  The  bottom  zone  is  the  Downtrend  zone;  the  middle  zone  is  the  Ranging  zone;  The  top  fib  zone  is  the  Uptrend  zone;',
      group="Fibonacci  Trade  Entry  Settings")
fib_level  =  float(0)
if  entry_choice  ==  "1-Top-High  Fib  Border"
        fib_level  :=  hl
else  if  entry_choice  ==  "2-Bottom-High  Fib  Border"
        fib_level  :=  hf
else  if  entry_choice  ==  "3-Top-Center  Fib  Border"
        fib_level  :=  cfh
else  if  entry_choice  ==  "4-Bottom-Center  Fib  Border"
        fib_level  :=  cfl
else  if  entry_choice  ==  "5-Top-Low  Fib  Border"
        fib_level  :=  lf
else  if  entry_choice  ==  "6-Bottom-Low  Fib  Border"
        fib_level  :=  ll
//  Start:  Bullish  +DI  option
di_choice  =  input.bool(false,  title="Only  open  trades  on  bullish  +DI  (Positive  Directional  Index)?  (off  for  contrarian  traders)",
    tooltip='Default  is  disabled.  If  you  want  to  be  more  selective  (you  want  a  bullish  confirmation),  enable  this  and  it  will  only  open  trades  when  the  +DI  (Positive  Directional  Index)  is  higher  than  the  -DI  (Negative  Directional  Index).  Contrarian  traders  (buy  the  dip)  should  leave  this  disabled',
    group="Fibonacci  Trade  Entry  Settings")
di_min  =  input.int(0,  title='Min  +DI  value  to  open  trade',
    tooltip='Default  is  zero.  Use  this  to  set  the  minium  +DI  value  to  open  the  trade.  Try  incrementing  this  value  if  you  want  to  be  more  selective  and  filter  for  more  bullish  moves  (e.g.  20-25).  For  Contrarian  traders,  uncheck  "Only  open  trades  on  bullish  DI"  option  and  set  Min  +DI  to  zero',
    group="Fibonacci  Trade  Entry  Settings")
di_max  =  input.int(100,  title='Max  +DI  value  to  open  trade',
    tooltip='Default  is  100.  Use  this  to  set  the  maxium  +DI  value  to  open  trade.  For  Contrarian  traders,  uncheck  "Only  open  trades  on  bullish  DI"  option  and  try  a  Max  +DI  value  no  higher  than  20  or  25',
    group="Fibonacci  Trade  Entry  Settings")
di_neg_min  =  input.int(0,  title='Min  -DI  value  to  open  trade',
    tooltip='Default  is  zero.  Use  this  to  set  the  minium  -DI  value  to  open  the  trade.  Try  incrementing  this  value  if  you  want  to  be  more  selective  and  filter  for  more  bearish  moves  (e.g.  25  or  higher).',
    group="Fibonacci  Trade  Entry  Settings")
di_neg_max  =  input.int(100,  title='Max  -DI  value  to  open  trade',
    tooltip='Default  is  100.  Use  this  to  set  the  maximum  -DI  value  to  open  trade.',
    group="Fibonacci  Trade  Entry  Settings")
di_inrange  =  di_plus  >=  di_min  and  di_plus  <=  di_maxanddi_minus>=di_neg_minanddi_minus<=di_neg_max
//End:Bullish+DIoption
//End:FibonacciSettings------------------------------------------------------
//Start:SafetyOrderSettings-------------------------------------------------
base_order=input(100.0,title='Baseorder',group="SafetyOrderSettings")
safe_order=input(200.0,title='Safetyorder',group="SafetyOrderSettings")
price_deviation=input.float(6.0,title='Pricedeviationtoopensafetyorders(%)',step=0.25,minval=0.0,group="SafetyOrderSettings")/100
safe_order_volume_scale=input.float(2.0,step=0.5,title='Safetyordervolumescale',group="SafetyOrderSettings")
safe_order_step_scale=input.float(1,step=0.1,title='Safetyorderstepscale',group="SafetyOrderSettings")
max_safe_order=input(5,title='Maxsafetyorders',group="SafetyOrderSettings")
//End:SafetyOrderSettings---------------------------------------------------
//End:TradeEntrySettings----------------------------------------------------
//Start:TradeExitSettings---------------------------------------------------
//Truncatefunction
truncate(number,decimals)=>
factor=math.pow(10,decimals)
int(number*factor)/factor
//Start:TradeExitSettings---------------------------------------------------
//Start:FibonacciExit--------------------------------------------------------
fib_tp_trigger=input.string("1-Crosses",title="TakeProfitwhenthesource:[cont.]",options=["1-Crosses","2-Crossesup","3-Crossesdown","4-ReachesTargetTakeProfit(%)"],tooltip=
"'Crosses'includesupanddownmovements.'CrossesUp'onlyincludesupmovements.'CrossesDown'onlyincludesdownmovements",group="FibonacciTradeExitSettings")
fib_tp=0
iffib_tp_trigger=="1-Crosses"
fib_tp:=1
elseiffib_tp_trigger=="2-Crossesup"
fib_tp:=2
elseiffib_tp_trigger=="3-Crossesdown"
fib_tp:=3
elseiffib_tp_trigger=="4-ReachesTargetTakeProfit(%)"
fib_tp:=4
//TakeProfitDrop-downmenuoption
//Declaretake_profit
take_profit=float(0.03)
tp_choice=input.string("1-Top-HighFibBorder",title="...TheFibline:",options=["1-Top-HighFibBorder","2-Bottom-HighFibBorder","3-Top-CenterFibBorder","4-Bottom-CenterFibBorder"],tooltip=
'Selecthowtoexityourtradeandtakeprofit.Thenspecifybelowthisoptiontheconditiontoexit."Top-HighFibBorder"isthetop-mostFibonaccilineinthegreenuptrendzone."Bottom-HighFibBorder"isthebottomFibonaccilineinthegreenuptrendzone.Youcanfindtheselinesonthe"Style"tabandtogglethemoff/ontolocatetheselinesformoreclarity',
group="FibonacciTradeExitSettings")
iftp_choice=="1-Top-HighFibBorder"
take_profit:=float(hl)
elseiftp_choice=="2-Bottom-HighFibBorder"
take_profit:=float(hf)
elseiftp_choice=="3-Top-CenterFibBorder"
take_profit:=float(cfh)
elseiftp_choice=="4-Bottom-CenterFibBorder"
take_profit:=float(cfl)
//InputforTTP%
iffib_tp==4
take_profit:=input.float(3.0,title='TargetTakeProfit(%)',step=0.5,minval=0.0,tooltip='Onlyusedif"TargetTakeProfit(%)"isselectedabove.',group="FibonacciTradeExitSettings")/100
//End:FibonacciExit----------------------------------------------------------
//Trailing
trailing=input.float(0.0,title='Trailingdeviation.Default=0.0(%)',step=0.1,minval=0.0,group="FibonacciTradeExitSettings")/100
//Calculateourkeylevels
varcurrent_so=0
varinitial_order=0.0
varprevious_high_value=0.0
varoriginal_ttp_value=0.0
//FibonacciTakeProfitConditions
fb_tp_condition=false
iffib_tp==1
fb_tp_condition:=ta.cross(sourceInput,take_profit)
elseiffib_tp==2
fb_tp_condition:=ta.crossover(sourceInput,take_profit)
elseiffib_tp==3
fb_tp_condition:=ta.crossunder(sourceInput,take_profit)
//End:TradeExitSettings-----------------------------------------------------
//Start:WHENTOBUYLOGIC-----------------------------------------------------
//DetermineifFibEntryTriggerwasmet
e_trig_bool=bool(false)
ife_trig==1
e_trig_bool:=ta.cross(sourceInput,fib_level)
elseife_trig==2
e_trig_bool:=ta.crossover(sourceInput,fib_level)
elseife_trig==3
e_trig_bool:=ta.crossunder(sourceInput,fib_level)
else
e_trig_bool:=false
//FirstFibEntryCalculationforwhentobuy
buy=bool(false)
use_fib=e_trig_boolandadx_inrange
//IfoptionenabledforentertradesonlywhenDIispositive,thenopentradebasedonusersettings
ifdi_choiceanddi_inrangeandinDateRangeanduse_fib
buy:=(di_plus>di_minus)?true:false
elseifdi_inrangeandinDateRangeanduse_fib
buy:=true
else
buy:=false
ifbuyandstrategy.position_size==0andsourceInput>0
strategy.entry('Long@'+str.tostring(sourceInput)+'💎✋🤚',strategy.long,qty=base_order/sourceInput)
initial_order:=sourceInput
current_so:=1
previous_high_value:=0.0
original_ttp_value:=0
//End:WHENTOBUYLOGIC-------------------------------------------------------
//Start:FibBasedStopLoss---------------------------------------------------
tp_choice_fibstoploss=input.bool(false,title='UseFib-basedStopLoss?',tooltip='UsethistousethesettingsbelowtoexitthetradewhenthesourcecrosseseaFibBorder',group="FibBasedStopLoss")
fib_exit_trigger=input.string("1-Crosses",title="FibStopLosssignalswhenthesource:[cont.]",options=["1-Crosses","2-Crossesup","3-Crossesdown"],
tooltip="IgnoredifaboveoptionforFib-basedStopLossisnotenabled.'Crosses'includesupanddownmovements.'CrossesUp'onlyincludesupmovements.'CrossesDown'onlyincludesdownmovements",group="FibBasedStopLoss")
fib_exit=0
iffib_exit_trigger=="1-Crosses"
fib_exit:=1
elseiffib_exit_trigger=="2-Crossesup"
fib_exit:=2
elseiffib_exit_trigger=="3-Crossesdown"
fib_exit:=3
fib_exit_choice=input.string("6-Bottom-LowFibBorder",title="...TheFibline:",options=["1-Top-HighFibBorder","2-Bottom-HighFibBorder","3-Top-CenterFibBorder","4-Bottom-CenterFibBorder","5-Top-LowFibBorder","6-Bottom-LowFibBorder"],
tooltip='Therearethreefibzonesandeachzonehas2borders(Top&Bottom).Theoptionsarelistedfromthebottomzonetothetopzone.ThebottomzoneistheDowntrendzone;themiddlezoneistheRangingzone;ThetopfibzoneistheUptrendzone;',
group="FibBasedStopLoss")
fib_exit_level=float(0)
iffib_exit_choice=="1-Top-HighFibBorder"
fib_exit_level:=hl
elseiffib_exit_choice=="2-Bottom-HighFibBorder"
fib_exit_level:=hf
elseiffib_exit_choice=="3-Top-CenterFibBorder"
fib_exit_level:=cfh
elseiffib_exit_choice=="4-Bottom-CenterFibBorder"
fib_exit_level:=cfl
elseiffib_exit_choice=="5-Top-LowFibBorder"
fib_exit_level:=lf
elseiffib_exit_choice=="6-Bottom-LowFibBorder"
fib_exit_level:=ll
//DeterminewhichFibBasedStopLosswasselected
exit_trig_bool=bool(false)
iffib_exit==1
exit_trig_bool:=ta.cross(sourceInput,fib_exit_level)
elseiffib_exit==2
exit_trig_bool:=ta.crossover(sourceInput,fib_exit_level)
elseiffib_exit==3
exit_trig_bool:=ta.crossunder(sourceInput,fib_exit_level)
else
exit_trig_bool:=false
//DetermineifFibStopLossconditionismet
iftp_choice_fibstoplossandexit_trig_bool
strategy.close_all(comment='Fibstoploss@'+str.tostring(strategy.position_avg_price))
current_so:=0
previous_high_value:=0
original_ttp_value:=0
//original_ttp_value
//End:FibBasedStopLoss-----------------------------------------------------
//Start:TakeProfitLevel-----------------------------------------------------
//take_profit=float(na)
take_profit_level=float(na)
//ConditionswhentotakeprofitandwhichFibstrategyistheactivestrategy
iffib_tp==4andstrategy.position_size>0
take_profit_level:=strategy.position_avg_price*(1+take_profit)
else
take_profit_level:=take_profit
//End:TakeProfitLevel-------------------------------------------------------
//Start:SafetyOrderthresholdlogic------------------------------------------
threshold=0.0

ifsafe_order_step_scale==1.0
threshold:=initial_order-initial_order*price_deviation*safe_order_step_scale*current_so
elseifcurrent_so<=max_safe_order
threshold:=initial_order-initial_order*((price_deviation*math.pow(safe_order_step_scale,current_so)-price_deviation)/(safe_order_step_scale-1))
elseifcurrent_so>max_safe_order
threshold:=initial_order-initial_order*((price_deviation*math.pow(safe_order_step_scale,max_safe_order)-price_deviation)/(safe_order_step_scale-1))

//Averagedownwhenlowestcandlevaluecrossesbelowthreshold
ifcurrent_so>0andlow<=thresholdandcurrent_so<=max_safe_orderandprevious_high_value==0.0
//TriggerasafetyorderattheSafetyOrder"threshold"price
strategy.entry('😨🙏SO'+str.tostring(current_so)+'@'+str.tostring(threshold),direction=strategy.long,qty=safe_order*math.pow(safe_order_volume_scale,current_so-1)/threshold)
current_so+=1
//End:SafetyOrderthresholdlogic---------------------------------------------
//Start:TakeProfit-----------------------------------------------------------
//Takeprofitwhentakeprofitlevelisequaltoorhigherthanthehighofthecandle
vartrailing_price=float(0.0)
varstopValue=float(0.0)
iftake_profit_level<=highandstrategy.position_size>0orprevious_high_value>0.0or(fb_tp_conditionandstrategy.position_size>0)
iftrailing>0.0
//'trailing_price'willcontainthelargestpercentage-basedstopvalue
trailing_price:=if(strategy.position_size>0)
//'stopValue'willupdateeverycandlecloseandcontainapercentage-basedstopvalue
stopValue:=close*(1-trailing)
//The'max'functioniswhatallowsthepercentage-basedstopto'Trail'.
//IfthestopValueishigherthantheprevioustrailing_price(whichwastheoldstopValue)thenwekeepthehighervalue
//Thetrailing_pricecanonlyincreaseorremainthesame.
math.max(stopValue,trailing_price[1])
else
0
ifprevious_high_value>0.0
ifhigh>=previous_high_value
previous_high_value:=sourceInput
ifclose<=trailing_price
previous_high_percent=(previous_high_value-original_ttp_value)*1.0/original_ttp_value
current_high_percent=(close-original_ttp_value)*1.0/original_ttp_value
strategy.close_all(comment='Close(trailing)@'+str.tostring(truncate(current_high_percent*100,3))+'%')
current_so:=0
previous_high_value:=0
original_ttp_value:=0
trailing_price:=0
stopValue:=0
else
previous_high_value:=high
original_ttp_value:=high
else
strategy.close_all(comment='💰Close@'+str.tostring(high))
current_so:=0
previous_high_value:=0
original_ttp_value:=0
trailing_price:=0
stopValue:=0
//End:TakeProfit-------------------------------------------------------------
//Start:Plots-----------------------------------------------------------------
//PlotTrailingStopLossandassociatedoriginalTTPvalue
plot(original_ttp_value>0?original_ttp_value:na,style=plot.style_linebr,color=color.white,linewidth=4,title="OriginalTTPValue",editable=true)
plot(stopValue>0?stopValue:na,style=plot.style_linebr,color=color.red,linewidth=4,title="StopValue",editable=true)
plot(trailing_price>0?trailing_price:na,style=plot.style_linebr,color=color.yellow,linewidth=4,title="Trailingstoploss",editable=true)
//PlotFibonacciAreas
fill(plot(hl,title='Top-HighFibBorder',color=color.new(#00FFFF,50),linewidth=1),plot(hf,title='Bottom-HighFibBorder',color=color.new(#38761d,50),linewidth=1),color=color.new(#00FFFF,80),title='UptrendFibonacciZone@23.6%')//uptrendzone
fill(plot(cfh,title='Top-CenterFibBorder',color=color.new(#0589f4,50),linewidth=1),plot(cfl,title='Bottom-CenterFibBorder',color=color.new(#2018ff,50),linewidth=1),color=color.new(color.blue,80),title='RangingFibonacciZone@61.8%')//rangingzone
fill(plot(lf,title='Top-LowFibBorder',color=color.new(color.yellow,50),linewidth=1),plot(ll,title='Bottom-LowFibBorder',color=color.new(#bf00ff,50),linewidth=1),color=color.new(color.orange,80),title='DowntrendFibonacciZone@76.4%')//downtrendzone
//PlotTP
plot(strategy.position_size>0?take_profit_level:na,style=plot.style_linebr,color=color.green,linewidth=3,title="TakeProfit")
//PlotAllSafetyOrderlinesexceptforlastoneasbrightblue
plot(strategy.position_size>0andcurrent_so<=max_safe_orderandcurrent_so>0?threshold:na,style=plot.style_linebr,color=color.new(#00ffff,0),linewidth=3,title="SafetyOrder")
//PlotLastSafetyOrderLineasRed
plot(strategy.position_size>0andcurrent_so>max_safe_order?threshold:na,style=plot.style_linebr,color=color.red,linewidth=3,title="NoSafetyOrdersLeft")
//PlotAveragePositionPriceLineasOrange
plot(strategy.position_size>0?strategy.position_avg_price:na,style=plot.style_linebr,color=color.orange,linewidth=3,title="AvgPositionPrice")
//FillTPAreaandSOArea
h1=plot(strategy.position_avg_price,color=color.new(#000000,100),title="AvgPricePlotArea",display=display.none,editable=false)
h2=plot(take_profit_level,color=color.new(#000000,100),title="TakeProfitPlotArea",display=display.none,editable=false)
h3=plot(threshold,color=color.new(#000000,100),title="SOPlotArea",display=display.none,editable=false)
//FillTPAreaandSOArea
fill(h1,h2,color=color.new(#38761d,80),title="TakeProfitPlotArea")
//CurrentSOArea
fill(h1,h3,color=color.new(#3d85c6,80),title="SOPlotArea")
Expand (344 lines)
