Script Name: Full Forex scalper Strategy
Author: exlux99
Description: THis is a FOREX scalping system that can be optimized with almost all majors and crosses pairs.

Its made of multiple elements such as :
MACD
Stochastic RSI
Fast VW moving average
Slow VW moving average
Time management( forex sessions as inputs)

Rules for entry
Long
Last 2 MACD values were ascending, fast moving average is below moving average and stochastic RSI...
PineScript code:

Pine Script™ strategy
Full Forex scalper Strategy
//@version=4
strategy("FOrex  scalper  Strategy",  overlay=true)
fromDay  =  input(defval  =  1,  title  =  "From  Day",  minval  =  1,  maxval  =  31)
fromMonth  =  input(defval  =  1,  title  =  "From  Month",  minval  =  1,  maxval  =  12)
fromYear  =  input(defval  =  2020,  title  =  "From  Year",  minval  =  1970)

//  To  Date  Inputs
toDay  =  input(defval  =  1,  title  =  "To  Day",  minval  =  1,  maxval  =  31)
toMonth  =  input(defval  =  12,  title  =  "To  Month",  minval  =  1,  maxval  =  12)
toYear  =  input(defval  =  2021,  title  =  "To  Year",  minval  =  1970)

//  Calculate  start/end  date  and  time  condition
DST  =  1  //day  light  saving  for  usa
//---  Europe
London  =  iff(DST==0,"0000-0900","0100-1000")
//---  America
NewYork  =  iff(DST==0,"0400-1400","0500-1500")
//---  Pacific
Sydney  =  iff(DST==0,"1300-2200","1400-2300")
//---  Asia
Tokyo  =  iff(DST==0,"1500-2400","1600-0100")
customTime  =iff(DST==0,"0000-1200","0100-1300")
customTime2  =iff(DST==0,"0900-1200","1000-1300")
//--  Time  In  Range
timeinrange(res,  sess)  =>  time(res,  sess)  !=  0
london  =  timeinrange(timeframe.period,  London)
newyork  =  timeinrange(timeframe.period,  NewYork)
c_time  =  timeinrange(timeframe.period,customTime)
c_time2  =  timeinrange(timeframe.period,customTime2)
startDate  =  timestamp(fromYear,  fromMonth,  fromDay,  00,  00)
finishDate  =  timestamp(toYear,  toMonth,  toDay,  00,  00)
time_cond  =  time  >=  startDate  and  time  <=  finishDate  and  (london  or  newyork)
fastLength  =  input(21)
slowlength  =  input(58)
MACDLength  =  input(8)
smallEMA=ema(close,fastLength)
largeEMA=ema(close,slowlength)
MACD=smallEMA-largeEMA
aMACD=ema(MACD,MACDLength)
delta=MACD-aMACD
smoothK=input(12,minval=1)
smoothD=input(5,minval=1)
lengthRSI=input(8,minval=1)
lengthStoch=input(20,minval=1)
src=input(close,title="RSISource")
vFast=stoch(close,high,low,8)
vSlow=sma(vFast,5)
rsi1=rsi(src,lengthRSI)
k=sma(stoch(rsi1,rsi1,rsi1,lengthStoch),smoothK)
d=sma(k,smoothD)
fiftyVWMA=vwma(close,55)
twohunVWMA=vwma(close,144)
tp=input(0.0044,"tpin0.x->EX0.01=1%")
sl=input(0.005,"slin0.x")
timerange=input(true,"Europe+NewYorkonly?")
if(timerange==trueandc_timeandnot(c_time2))
ifMACD>MACD[1]andMACD[1]>MACD[2]andfiftyVWMA<twohunVWMAandtime_cond
ifvFast>vSlowandk<30//and(vSlow<40)
strategy.entry("long",strategy.long,comment='long',alert_message='long')
ifMACD<MACD[1]andMACD[1]<MACD[2]andfiftyVWMA>twohunVWMAandtime_cond
ifvFast<vSlowandk>70//and(vSlow>60)//and(rsi1>60)
strategy.entry("short",strategy.short,comment='short',alert_message='short')


if(timerange==false)
ifMACD>MACD[1]andMACD[1]>MACD[2]andfiftyVWMA<twohunVWMA
ifvFast>vSlowandk<30//and(vSlow<40)
strategy.entry("long",strategy.long,comment='long',alert_message='long')
ifMACD<MACD[1]andMACD[1]<MACD[2]andfiftyVWMA>twohunVWMA
ifvFast<vSlowandk>70//and(vSlow>60)//and(rsi1>60)
strategy.entry("short",strategy.short,comment='short',alert_message='short')

strategy.exit("long_tp/sl","long",profit=close*tp/syminfo.mintick,loss=close*sl/syminfo.mintick,comment='long_tp/sl',alert_message='closelong')
strategy.exit("short_tp/sl","short",profit=close*tp/syminfo.mintick,loss=close*sl/syminfo.mintick,comment='short_tp/sl',alert_message='closeshort')
if(not(c_time)andtimerange==true)//ornewyork))
strategy.close("long",comment="long_time",alert_message='closelong')
strategy.close("short",comment="short_time",alert_message='closeshort')
//plot(strategy.equity,title="equity",color=red,linewidth=2,style=areabr)
Expand (100 lines)
