Script Name: Full strategy AllinOne with risk management MACD RSI PSAR ATR MA
Author: SoftKill21
Description: Hey, I am glad to present you one of the strategies where I put a lot of time in it.

This strategy can be adapted to all type of timecharts like scalping, daytrading or swing.

The context is the next one :
First we have the ATR to calculate our TP/SL points. At the same time we have another rule once we enter(we enter based on % risk from total equity, in this...
PineScript code:

Pine Script™ strategy
Full strategy AllinOne with risk management MACD RSI PSAR ATR MA
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  SoftKill21
//@version=4
strategy("EURUSD  1min  strat  RISK  %%  ",  overlay=false,  initial_capital  =  1000)
//  BACKTESTING  RANGE

//  From  Date  Inputs
fromDay  =  input(defval  =  1,  title  =  "From  Day",  minval  =  1,  maxval  =  31)
fromMonth  =  input(defval  =  6,  title  =  "From  Month",  minval  =  1,  maxval  =  12)
fromYear  =  input(defval  =  2020,  title  =  "From  Year",  minval  =  1970)

//  To  Date  Inputs
toDay  =  input(defval  =  1,  title  =  "To  Day",  minval  =  1,  maxval  =  31)
toMonth  =  input(defval  =  12,  title  =  "To  Month",  minval  =  1,  maxval  =  12)
toYear  =  input(defval  =  2020,  title  =  "To  Year",  minval  =  1970)

//  Calculate  start/end  date  and  time  condition
DST  =  1  //day  light  saving  for  usa
//---  Europe
London  =  iff(DST==0,"0000-0900","0100-1000")
//---  America
NewYork  =  iff(DST==0,"0400-1500","0500-1600")
//---  Pacific
Sydney  =  iff(DST==0,"1300-2200","1400-2300")
//---  Asia
Tokyo  =  iff(DST==0,"1500-2400","1600-0100")
//--  Time  In  Range
timeinrange(res,  sess)  =>  time(res,  sess)  !=  0
london  =  timeinrange(timeframe.period,  London)
newyork  =  timeinrange(timeframe.period,  NewYork)
startDate  =  timestamp(fromYear,  fromMonth,  fromDay,  00,  00)
finishDate  =  timestamp(toYear,  toMonth,  toDay,  00,  00)
time_cond  =  time  >=  startDate  and  time  <=  finishDate  and  (london  or  newyork)
//
//
//  rsi
length  =  input(  5  )
overSold  =  input(  23  )
overBought  =  input(  72  )
price  =  close
vrsi  =  rsi(price,  length)
co  =  crossover(vrsi,  overSold)
cu  =  crossunder(vrsi,  overBought)
//  macd
fast_length_macd  =  input(title="Fast  Length",  type=input.integer,  defval=12)
slow_length_macd  =  input(title="Slow  Length",  type=input.integer,  defval=26)
src_macd  =  input(title="Source",  type=input.source,  defval=close)
signal_length  =  input(title="Signal  Smoothing",  type=input.integer,  minval  =  1,  maxval  =  50,  defval  =  9)
sma_source  =  input(title="Simple  MA(Oscillator)",  type=input.bool,  defval=true)
sma_signal  =  input(title="Simple  MA(Signal  Line)",  type=input.bool,  defval=true)
//  Plot  colors
col_grow_above  =  #26A69A
col_grow_below  =  #FFCDD2
col_fall_above  =  #B2DFDB
col_fall_below  =  #EF5350
col_macd  =  #0094ff
col_signal  =  #ff6a00
//  Calculating
fast_ma  =  sma_source  ?  sma(src_macd,  fast_length_macd)  :  ema(src_macd,  fast_length_macd)
slow_ma  =  sma_source  ?  sma(src_macd,  slow_length_macd)  :  ema(src_macd,  slow_length_macd)
macd  =  fast_ma  -  slow_ma
signal  =  sma_signal  ?  sma(macd,  signal_length)  :  ema(macd,  signal_length)
hist  =  macd  -  signal
//plot(hist,  title="Histogram",  style=plot.style_columns,  color=(hist>=0  ?  (hist[1]  <  hist  ?  col_grow_above  :  col_fall_above)  :  (hist[1]  <  hist  ?  col_grow_below  :  col_fall_below)  ),  transp=0  )
//  sar
start  =  input(0.02)
increment  =  input(0.02)
maximum  =  input(0.2)
var  bool  uptrend  =  na
var  float  EP  =  na
var  float  SAR  =  na
var  float  AF  =  start
var  float  nextBarSAR  =  na
if  bar_index  >  0
        firstTrendBar  =  false
        SAR  :=  nextBarSAR

        if  bar_index  ==  1
                float  prevSAR  =  na
                float  prevEP  =  na
                lowPrev  =  low[1]
                highPrev  =  high[1]
                closeCur  =  close
                closePrev  =  close[1]
                ifcloseCur>closePrev
uptrend:=true
EP:=high
prevSAR:=lowPrev
prevEP:=high
else
uptrend:=false
EP:=low
prevSAR:=highPrev
prevEP:=low

firstTrendBar:=true
SAR:=prevSAR+start*(prevEP-prevSAR)

ifuptrend
ifSAR>low
firstTrendBar:=true
uptrend:=false
SAR:=max(EP,high)
EP:=low
AF:=start
else
ifSAR<high
firstTrendBar:=true
uptrend:=true
SAR:=min(EP,low)
EP:=high
AF:=start

ifnotfirstTrendBar
ifuptrend
ifhigh>EP
EP:=high
AF:=min(AF+increment,maximum)
else
iflow<EP
EP:=low
AF:=min(AF+increment,maximum)

ifuptrend
SAR:=min(SAR,low[1])
ifbar_index>1
SAR:=min(SAR,low[2])
else
SAR:=max(SAR,high[1])
ifbar_index>1
SAR:=max(SAR,high[2])

nextBarSAR:=SAR+AF*(EP-SAR)

//plot(SAR,style=plot.style_cross,linewidth=3,color=color.orange)
//plot(nextBarSAR,style=plot.style_cross,linewidth=3,color=color.aqua)
//plot(strategy.equity,title="equity",color=color.red,linewidth=2,style=plot.style_areabr)
//bb
length_bb=input(17,minval=1)
src_bb=input(close,title="Source")
mult_bb=input(2.0,minval=0.001,maxval=50,title="StdDev")
basis_bb=sma(src_bb,length_bb)
dev_bb=mult_bb*stdev(src_bb,length_bb)
upper_bb=basis_bb+dev_bb
lower_bb=basis_bb-dev_bb
offset=input(0,"Offset",type=input.integer,minval=-500,maxval=500)
//plot(basis_bb,"Basis",color=#872323,offset=offset)
//p1_bb=plot(upper_bb,"Upper",color=color.teal,offset=offset)
//p2_bb=plot(lower_bb,"Lower",color=color.teal,offset=offset)
//fill(p1_bb,p2_bb,title="Background",color=#198787,transp=95)
//ema
len_ema=input(10,minval=1,title="Length")
src_ema=input(close,title="Source")
offset_ema=input(title="Offset",type=input.integer,defval=0,minval=-500,maxval=500)
out_ema=ema(src_ema,len_ema)
//plot(out_ema,title="EMA",color=color.blue,offset=offset_ema)
//out_emaeemaul
//basis_bbemiddledelabb
//histehistograma
//rsicuband0crossptrsi
//confirmarea
shortCondition=(uptrend==falseandcrossunder(ema(src_ema,len_ema),sma(src_bb,length_bb))andhist<0andvrsi<overSold)//andtime_cond
longCondition=(uptrend==trueandcrossover(ema(src_ema,len_ema),sma(src_bb,length_bb))andhist>0andvrsi>overBought)//andtime_cond
//tp=input(0.0025,type=input.float,title="tp")
//sl=input(0.001,type=input.float,title="sl")
//INDICATOR---------------------------------------------------------------------
//AverageTrueRange(1.RISK)
atr_period=input(14,"AverageTrueRangePeriod")
atr=atr(atr_period)
//MONEYMANAGEMENT--------------------------------------------------------------
balance=strategy.netprofit+strategy.initial_capital//currentbalance
floating=strategy.openprofit//floatingprofit/loss
risk=input(2,type=input.float,title="Risk%")/100//risk%pertrade
isTwoDigit=input(false,"Isthisa2digitpair?(JPY,XAU,XPD...")
equity_protector=input(1,type=input.float,title="EquityProtection%")/100//equityprotection%
equity_protectorTP=input(2,type=input.float,title="EquityTP%")/100//equityprotection%
multtp=input(5,type=input.float,title="multiatrtp")
multsl=input(5,type=input.float,title="multiatrsl")
stop=atr*100000*input(1,"SLX")*multsl//Stoplevel
if(isTwoDigit)
stop:=stop/100
target=atr*100000*input(1,"TPX")*multtp//Stoplevel
//CalculatecurrentDDanddetermineifstopoutisnecessary
equity_stopout=false
if(floating<0andabs(floating/balance)>equity_protector)
equity_stopout:=true

equity_stopout2=false
if(floating>0andabs(floating/balance)>equity_protectorTP)
equity_stopout2:=true

//Calculatethesizeofthenexttrade
temp01=balance*risk//RiskinUSD
temp02=temp01/stop//Riskinlots
temp03=temp02*100000//Converttocontracts
size=temp03-temp03%1000//Normalizeto1000s(Tradesize)
if(size<10000)
size:=10000//Setmin.lotsize
//TRADEEXECUTION---------------------------------------------------------------
strategy.close_all(equity_stopout,comment="equitysl",alert_message="equity_sl")//Closealltradesw/equityprotector
//strategy.close_all(equity_stopout2,comment="equitytp",alert_message="equity_tp")//Closealltradesw/equityprotector
is_open=strategy.opentrades>0
strategy.entry("long",true,size,oca_name="a",oca_type=strategy.oca.cancel,when=longConditionandnotis_open)//Longentry
strategy.entry("short",false,size,oca_name="a",oca_type=strategy.oca.cancel,when=shortConditionandnotis_open)//Shortentry

strategy.exit("exit_long","long",loss=stop,profit=target)//Longexit(stoploss)
strategy.close("long",when=shortCondition)//Longexit(exitcondition)
strategy.exit("exit_short","short",loss=stop,profit=target)//Shortexit(stoploss)
strategy.close("short",when=longCondition)//Shortexit(exitcondition)
//strategy.entry("long",strategy.long,size,when=longCondition,comment="long",alert_message="long")
//strategy.entry("short",strategy.short,size,when=shortCondition,comment="short",alert_message="short")

//strategy.exit("closelong","long",profit=close*tp/syminfo.mintick,alert_message="closelong")
//strategy.exit("closeshort","short",profit=close*tp/syminfo.mintick,alert_message="closeshort")

//strategy.exit("closelong","long",size,profit=close*tp/syminfo.mintick,loss=close*sl/syminfo.mintick,alert_message="closelong")
//strategy.exit("closeshort","short",size,profit=close*tp/syminfo.mintick,loss=close*sl/syminfo.mintick,alert_message="closeshort")

//strategy.close("long",when=not(time_cond),comment="time",alert_message="closelong")
//strategy.close("short",when=not(time_cond),comment="time",alert_message="closeshort")
//strategy.close_all(when=not(time_cond),comment='time')
Expand (258 lines)
