Script Name: GAVAD - Selling after a Strong Moviment
Author: cleber.martinelli
Description: This strategy search for a moment whe the market make two candles are consistently strong, and open a Sell, searching the imediactly correction, on the new candle. It`s easy to see the bars on the histogram graph. Purple Bars represent the candle variation. when on candle cross ove the Signal line the graph plot an Yellow ci, if the second bar crossover the signal...
PineScript code:

Pine Script™ strategy
GAVAD - Selling after a Strong Moviment
//@version=4
strategy(title="GAVAD",  shorttitle="GAVAD",  overlay=false,  initial_capital=36000)
////////////////////////////////////////////////////////
//                                                                                                        //
//                                                                                                        //
//                                          GAVAD  %                                                //
//                                                                                                        //
//                                                                                                        //
////////////////////////////////////////////////////////
Sinal  =  input(6,  title="Sinal",  type=input.integer,  minval=1,  maxval=150)
//Objetivo  =  input(6,  title="Objetivo",  type=input.integer,  minval=1,  maxval=100)
Multip  =  input(10000,  title="Sinal",  type=input.integer,  minval=1,  maxval=100000)
//GavadEntrada1  =  (close  -  low  [1])/close[1]
//plot(GavadEntrada1,  style=plot.style_line,  linewidth=3,  color=color.yellow)
//sombra
//DownOL  =  (low  -  open  )  /  open  *  -10000
//plot(DownOL,  style=plot.style_area,  linewidth=3,  color=color.silver)
//  imprime  o  GAVAD
GavadEntrada  =  (close  -  close  [1])/close[1]  *  Multip
plot(GavadEntrada,  style=plot.style_histogram,  linewidth=3,  color=color.purple)
//linha  do  Sinal
plot(Sinal,  style=plot.style_line,  linewidth=1,  color=color.yellow)
//linha  do  Objetivo
//plot(Objetivo,  style=plot.style_line,  linewidth=1,  color=color.white)
Fura1  =  GavadEntrada  [0]  >=  Sinal
Fura2  =  GavadEntrada  [1]  >=  Sinal
Alert  =  Fura1
plotshape(Alert,  style=shape.circle,    location  =  location.top,  color=  color.yellow)
SinalON  =  Fura1  and  Fura2
plotshape(SinalON,  style=shape.circle,    location  =  location.bottom,  color=  color.green)
////////////////////////////////////////////////////////
//                                                                                                        //
//                                                                                                        //
//                            CONDIÇÕES  DE  OPERACAO                                  //
//                                                                                                        //
//                                                                                                        //
////////////////////////////////////////////////////////
Sell_Forte2  =  SinalON
//plotshape(Sell_Forte2,  style=shape.xcross,  color=color.yellow,  location=location.bottom)
//Call_Forte2  =  SinalON
//plotshape(Call_Forte2,  style=shape.xcross,  color=color.yellow,  location=location.top)
////////////////////////////////////////////////////////
//                                                                                                        //
//                                                                                                        //
//                                        CALENDARIO                                            //
//                                                  //
////
////////////////////////////////////////////////////////
//052)
//tradingviewsolicitaquesejainformadodataparagerarbacktestapartirdetaldata
//começabacktestdotradingsistememqualdata?
ano=input(2021,minval=1,title="Ano")
mes=input(1,minval=1,maxval=12,title="Mes")
dia=input(1,minval=1,maxval=30,title="Dia")
hora=input(0,minval=1,maxval=23,title="hora")
minuto=input(0,minval=1,maxval=59,title="minuto")
horaabertura=input(10,minval=1,maxval=23,title="horaInicioOperacaoRobo")
minutoabertura=input(40,minval=1,maxval=59,title="MinutoEncerraTudo")
horaencerra=input(17,minval=1,maxval=23,title="horaFechamento")
minutoencerra=input(50,minval=1,maxval=59,title="MinutoEncerraNovasOperacoes")
minutofinaliza=input(50,minval=1,maxval=59,title="MinutoEncerraTudo")
//validaseodiadehojeéposterioraodiainformadoacima
Validadia=year>=anoandmonth>=mesanddayofmonth>=dia
//criahorariodeaberturadenegociaçao,considerardefault10hs,poisosindicadoresjaestarãocorrigidos
abreloja=year>=anoandmonth>=mesanddayofmonth>=diaandhour>=horaabertura
//andminute>=minutoabertura)
//criahorariodefechamentodetodasasnegociaçoes,considerardefault17:00hs
//nenhumaordempodeserabertadepoisdessadataeasabertasdevemserfechadas
fechaloja=year>=anoandmonth>=mesanddayofmonth>=diaandhour>=horaencerra
//andminute>=minutoencerra)
fechaloja2=year>=anoandmonth>=mesanddayofmonth>=diaandhour>=horaencerra
//andminute>=minutofinaliza)
//validahorariodenegociação,praliberarasoperacoes.
lojaaberta=abreloja==trueandfechaloja==falseandfechaloja2==false
////////////////////////////////////////////////////////
////
////
//GERENCIAMENTODERISCO//
////
////
////////////////////////////////////////////////////////
//setametamensal
meta=input(150000,"MetadeLucro")
Contratos=input(5,"Contratos")
//setatamanhodolote(ordeminicial-unica)
tamanhodolote=Contratos
//setastopgainfinalempontos(metadedabarraanterior)
//gaintotal=input(30,"Gain")
gaintotal=input(3,"Gain")
//setastoplossfinalempontos
lossmaximo=input(8,"Loss")
//lossmaximo=(open-close)*100
////////////////////////////////////////////////////////
////
//Checkbox//
////
////////////////////////////////////////////////////////
//ativacomprasretorno=input(title="AtivarComprasRetorno",type=input.bool,defval=true)
//ativavendasretorno=input(title="AtivarVendasRetorno",type=input.bool,defval=true)
////////////////////////////////////////////////////////
////
////
//COMPRAEVENDA//
////
////
////////////////////////////////////////////////////////
Tradenumber=strategy.closedtrades+1
Batemeta=strategy.netprofit<meta
//COMPRARETORNO
//longcondition2=ValidadiaandCall_Forte2andBatemeta
//strategy.entry("Comprar",strategy.long,tamanhodolote,when=longcondition2,comment="[Oper="+tostring(Tradenumber)+"]win="+tostring(strategy.wintrades)+"|Loss="+tostring(strategy.losstrades))
//strategy.exit("SaidaCompra","Comprar",profit=gaintotal,loss=lossmaximo)
//if(CruzamentoFechaCallGG)
//strategy.close(id="Comprar")
//if(EscapeFechaCall)
//strategy.close(id="Comprar")


//plotchar(longcondition2,char="C",location=location.bottom,color=color.lime,transp=0)
//alertcondition(longcondition2,"Comprar","CompraRápida!")
//VENDARETORNO
Shortcondition2=ValidadiaandSell_Forte2andBatemeta
strategy.entry("Vender",strategy.short,tamanhodolote,when=Shortcondition2,comment="[Oper="+tostring(Tradenumber)+"]win="+tostring(strategy.wintrades)+"|Loss="+tostring(strategy.losstrades))
strategy.exit("FechaVenda","Vender",profit=gaintotal,loss=lossmaximo)
//if(CruzamentoFechaSellGG)
//strategy.close(id="Vender")
//if(EscapeFechaSell)
//strategy.close(id="Comprar")
//plotchar(CruzamentoFechaSellGG,char="Y",location=location.top,color=color.lime,transp=0)
//plotchar(longcondition2,char="S",location=location.bottom,color=color.lime,transp=0)
//alertcondition(longcondition2,"Vender","VendaRápida!")
//fimdocodigo
Expand (182 lines)
