Script Name: Grid Spot Trading Algorithm V2 - The Quant Science
Author: thequantscience
Description: Grid Spot Trading Algorithm V2  is the last grid trading algorithm made by our developer team.

Grid Spot Trading Algorithm V2 is a fixed 10-level grid trading algorithm. The grid is divided into an accumulation area (red) and a selling area (green).
In the accumulation area, the algorithm will place new buy orders, selling the long positions on the top of the...
PineScript code:

Pine Script™ strategy
Grid Spot Trading Algorithm V2 - The Quant Science
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  thequantscience
//    ██████╗  ██████╗  ██╗██████╗          ███████╗██████╗    ██████╗  ████████╗          █████╗  ██╗            ██████╗    ██████╗  ██████╗  ██╗████████╗██╗    ██╗███╗      ███╗        ██╗      ██╗██████╗
//  ██╔════╝  ██╔══██╗██║██╔══██╗        ██╔════╝██╔══██╗██╔═══██╗╚══██╔══╝        ██╔══██╗██║          ██╔════╝  ██╔═══██╗██╔══██╗██║╚══██╔══╝██║    ██║████╗  ████║        ██║      ██║╚════██╗
//  ██║    ███╗██████╔╝██║██║    ██║        ███████╗██████╔╝██║      ██║      ██║              ███████║██║          ██║    ███╗██║      ██║██████╔╝██║      ██║      ███████║██╔████╔██║        ██║      ██║  █████╔╝
//  ██║      ██║██╔══██╗██║██║    ██║        ╚════██║██╔═══╝  ██║      ██║      ██║              ██╔══██║██║          ██║      ██║██║      ██║██╔══██╗██║      ██║      ██╔══██║██║╚██╔╝██║        ╚██╗  ██╔╝██╔═══╝
//  ╚██████╔╝██║    ██║██║██████╔╝        ███████║██║          ╚██████╔╝      ██║              ██║    ██║███████╗╚██████╔╝╚██████╔╝██║    ██║██║      ██║      ██║    ██║██║  ╚═╝  ██║          ╚████╔╝  ███████╗
//    ╚═════╝  ╚═╝    ╚═╝╚═╝╚═════╝          ╚══════╝╚═╝            ╚═════╝        ╚═╝              ╚═╝    ╚═╝╚══════╝  ╚═════╝    ╚═════╝  ╚═╝    ╚═╝╚═╝      ╚═╝      ╚═╝    ╚═╝╚═╝          ╚═╝            ╚═══╝    ╚══════╝

//@version=5
strategy(
title='GridSpotTradingAlgorithmV2-TheQuantScience™',
overlay=true,
calc_on_every_tick=true,
initial_capital=10000,
commission_type=strategy.commission.percent,
commission_value=0.10,
pyramiding=5,
default_qty_type=strategy.percent_of_equity,
close_entries_rule='ANY'
)
///////////////////////////////CodedbyTheQuantScience™////////////////////////////////////
//Upgrade2.00(2022.30.07)
//Upgrade3.00(2022.11.11)
//Upgrade4.00(2022.20.01)
//Newreleaseversion2.0(2023.10.05)
////////////////////////////////////////////////////////////////////////////////////////////////////
high_price=input.price(defval=0.00,title='Highprice:',group="TOPPRICEGRID",confirm=true,tooltip="Topgridprice.")
close_price=input.price(defval=0.00,title='Lowprice:',group="BOTTOMPRICEGRID",confirm=true,tooltip="Bottomgridprice.")
grid_destroyer=input.bool(defval=false,title='Activegriddestroyer:',group="STOPLOSSCONFIGURATION",inline="SL",tooltip="Destroythegridwhenpricecrossunderthestoplosslevel.",confirm=false)
stop_level=input.price(defval=0.00,title='',group="STOPLOSSCONFIGURATION",inline="SL",confirm=false,tooltip="Stoplosspricelevel.Setpriceleveltodestroythegridandcloseallthepositions.")
grid_range=high_price-close_price
varfloatgrid_1=0
varfloatgrid_2=0
varfloatgrid_3=0
varfloatgrid_4=0
varfloatgrid_5=0
varfloatgrid_6=0
varfloatgrid_7=0
varfloatgrid_8=0
varfloatgrid_9=0
varfloatgrid_10=0
varfloatgrid_factor=0
if(high_price>0orclose_price>0)
grid_factor:=grid_range/9
grid_1:=(high_price)
grid_2:=(high_price-(grid_factor*1))
grid_3:=(high_price-(grid_factor*2))
grid_4:=(high_price-(grid_factor*3))
grid_5:=(high_price-(grid_factor*4))
grid_6:=(high_price-(grid_factor*5))
grid_7:=(high_price-(grid_factor*6))
grid_8:=(high_price-(grid_factor*7))
grid_9:=(high_price-(grid_factor*8))
grid_10:=(close_price)

varfloatlots=0
varfloataccount_balance=0
long=(ta.crossunder(close,grid_5)orta.crossover(close,grid_5))
if(high_price>0orclose_price>0)
ifstrategy.opentrades==0
account_balance:=strategy.equity
lots:=(account_balance/close)/5
iflong
strategy.order(id="O#1",direction=strategy.long,qty=lots,limit=grid_6)
strategy.order(id="O#2",direction=strategy.long,qty=lots,limit=grid_7)
strategy.order(id="O#3",direction=strategy.long,qty=lots,limit=grid_8)
strategy.order(id="O#4",direction=strategy.long,qty=lots,limit=grid_9)
strategy.order(id="O#5",direction=strategy.long,qty=lots,limit=grid_10)
Exit(type)=>

switchtype
"Gridlevel5"=>grid_1
"Gridlevel4"=>grid_2
"Gridlevel3"=>grid_3
"Gridlevel2"=>grid_4
"Gridlevel1"=>grid_5
exit_input=input.string("Gridlevel1",title="Selectexit",options=["Gridlevel1","Gridlevel2","Gridlevel3","Gridlevel4","Gridlevel5"],tooltip="Startingfromthemiddletothetop.",group="ExitConfiguration")
exit_price=Exit(exit_input)
ifta.crossover(close,exit_price)and(high_price>0orclose_price>0)
strategy.close_all("Close-Position")
strategy.cancel("O#1")
strategy.cancel("O#2")
strategy.cancel("O#3")
strategy.cancel("O#4")
strategy.cancel("O#5")
if(close<grid_10orta.crossover(close,grid_10))
strategy.cancel_all()

if(high_price>0orclose_price>0)andgrid_destroyer==true
ifta.crossunder(close,stop_level)
strategy.close_all("GridDestroyed!!!")
varfloatnew_ten_grid_1=0
varfloatnew_ten_grid_2=0
varfloatnew_ten_grid_3=0
varfloatnew_ten_grid_4=0
varfloatnew_ten_grid_5=0
varfloatnew_ten_grid_6=0
varfloatnew_ten_grid_7=0
varfloatnew_ten_grid_8=0
varfloatnew_ten_grid_9=0
varfloatnew_ten_grid_10=0
varfloatgrid_destroyed_ten=0
if(high_price>0orclose_price>0)
new_ten_grid_1:=grid_1
new_ten_grid_2:=grid_2
new_ten_grid_3:=grid_3
new_ten_grid_4:=grid_4
new_ten_grid_5:=grid_5
new_ten_grid_6:=grid_6
new_ten_grid_7:=grid_7
new_ten_grid_8:=grid_8
new_ten_grid_9:=grid_9
new_ten_grid_10:=grid_10
ifgrid_destroyer==true
grid_destroyed_ten:=stop_level
else
new_ten_grid_1:=na
new_ten_grid_2:=na
new_ten_grid_3:=na
new_ten_grid_4:=na
new_ten_grid_5:=na
new_ten_grid_6:=na
new_ten_grid_7:=na
new_ten_grid_8:=na
new_ten_grid_9:=na
new_ten_grid_10:=na
ifgrid_destroyer==false
grid_destroyed_ten:=na
fill(plot(new_ten_grid_1,color=color.new(#35f83b,90)),
plot(new_ten_grid_2,color=color.new(#36fa3d,90)),
color=color.new(#37ff3e,90))
fill(plot(new_ten_grid_2,color=color.new(#35f53c,85)),
plot(new_ten_grid_3,color=color.new(#36f53c,85)),
color=color.new(#34fc3b,85))
fill(plot(new_ten_grid_3,color=color.new(#35fa3c,80)),
plot(new_ten_grid_4,color=color.new(#33f83a,80)),
color=color.new(#32ff39,80))
fill(plot(new_ten_grid_4,color=color.new(#35fc3c,70)),
plot(new_ten_grid_5,color=color.new(#35f83c,70)),
color=color.new(#34ff3b,70))
fill(plot(new_ten_grid_5,color=color.new(#35f13b,60)),
plot(new_ten_grid_6,color=color.new(#34fc3b,60)),
color=color.new(#37ff3d,60))
fill(plot(new_ten_grid_6,color=color.new(#f83333,60)),
plot(new_ten_grid_7,color=color.new(#fd3838,60)),
color=color.new(#ff3434,60))
fill(plot(new_ten_grid_7,color=color.new(#fa3636,70)),
plot(new_ten_grid_8,color=color.new(#fa3737,70)),
color=color.new(#ff3636,70))
fill(plot(new_ten_grid_8,color=color.new(#f83535,80)),
plot(new_ten_grid_9,color=color.new(#fa3636,80)),
color=color.new(#fd3434,80))
fill(plot(new_ten_grid_9,color=color.new(#fc3434,85)),
plot(new_ten_grid_10,color=color.new(#fc3737,85)),
color=color.new(#ff3636,85))
plot(grid_destroyed_ten,color=color.new(#fc3636,80),linewidth=10)
Expand (196 lines)
