Script Name: HYE Trend Hunter [Strategy]
Author: HYE0619
Description: *** Stratejinin Türkçe ve İngilizce açıklaması aşağıya eklenmiştir.

 HYE Trend Hunter

In this strategy, two of the most basic data (price and volume) necessary for detecting trends as early as possible and entering the trade on time are used. In this context, the approaches of some classical and new generation indicators using price and volume have been taken...
PineScript code:

Pine Script™ strategy
HYE Trend Hunter [Strategy]
//  @version=4
//  Credits
//  "Vwap  with  period"  code  which  used  in  this  strategy  to  calculate  the  leadLine  was  written  by  "neolao"  active  on  https://tr.tradingview.com/u/neolao/
//  "TSV"  code  which  used  in  this  strategy  was  written  by  "liw0"  active  on  https://www.tradingview.com/u/liw0.  The  code  is  correctedby"vitelot"December2018.
strategy("HYETrendHunter[Strategy]",overlay=true,initial_capital=1000,default_qty_value=100,default_qty_type=strategy.percent_of_equity,commission_value=0.025,pyramiding=0)

//Strategyinputs
slowtenkansenPeriod=input(9,minval=1,title="SlowTenkanSenVWAPLineLength",group="Tenkansen/Kijunsen")
slowkijunsenPeriod=input(13,minval=1,title="SlowKijunSenVWAPLineLength",group="Tenkansen/Kijunsen")
fasttenkansenPeriod=input(3,minval=1,title="FastTenkanSenVWAPLineLength",group="Tenkansen/Kijunsen")
fastkijunsenPeriod=input(7,minval=1,title="FastKijunSenVWAPLineLength",group="Tenkansen/Kijunsen")
BBlength=input(20,minval=1,title="BollingerBandLength",group="BollingerBands")
BBmult=input(2.0,minval=0.001,maxval=50,title="BollingerBandStdDev",group="BollingerBands")
tsvlength=input(20,minval=1,title="TSVLength",group="TımeSegmentedVolume")
tsvemaperiod=input(7,minval=1,title="TSVEmaLength",group="TımeSegmentedVolume")
vidyachoice=input(title="UseVidyatoFiltertheTrend?",type=input.bool,defval=false,group="VıdyaInputs")
length=input(title="VidyaLength",type=input.integer,defval=20,group="VıdyaInputs")
src=input(title="VidyaSource",type=input.source,defval=hl2,group="VıdyaInputs")
//VidyaCalculation
getCMO(src,length)=>
mom=change(src)
upSum=sum(max(mom,0),length)
downSum=sum(-min(mom,0),length)
out=(upSum-downSum)/(upSum+downSum)
out
cmo=abs(getCMO(src,length))
alpha=2/(length+1)
vidya=0.0
vidya:=src*alpha*cmo+nz(vidya[1])*(1-alpha*cmo)
//Makeinputoptionsthatconfigurebacktestdaterange

startDate=input(title="StartDate",type=input.integer,
defval=1,minval=1,maxval=31,group="BacktestRange")
startMonth=input(title="StartMonth",type=input.integer,
defval=1,minval=1,maxval=12,group="BacktestRange")
startYear=input(title="StartYear",type=input.integer,
defval=2000,minval=1800,maxval=2100,group="BacktestRange")
endDate=input(title="EndDate",type=input.integer,
defval=31,minval=1,maxval=31,group="BacktestRange")
endMonth=input(title="EndMonth",type=input.integer,
defval=12,minval=1,maxval=12,group="BacktestRange")
endYear=input(title="EndYear",type=input.integer,
defval=2021,minval=1800,maxval=2100,group="BacktestRange")

inDateRange=(time>=timestamp(syminfo.timezone,startYear,
startMonth,startDate,0,0))and
(time<timestamp(syminfo.timezone,endYear,endMonth,endDate,0,0))
//SlowTenkanSenCalculation
typicalPriceTS=(high+low+close)/3
typicalPriceVolumeTS=typicalPriceTS*volume
cumulativeTypicalPriceVolumeTS=sum(typicalPriceVolumeTS,slowtenkansenPeriod)
cumulativeVolumeTS=sum(volume,slowtenkansenPeriod)
slowtenkansenvwapValue=cumulativeTypicalPriceVolumeTS/cumulativeVolumeTS
//SlowKijunSenCalculation
typicalPriceKS=(high+low+close)/3
typicalPriceVolumeKS=typicalPriceKS*volume
cumulativeTypicalPriceVolumeKS=sum(typicalPriceVolumeKS,slowkijunsenPeriod)
cumulativeVolumeKS=sum(volume,slowkijunsenPeriod)
slowkijunsenvwapValue=cumulativeTypicalPriceVolumeKS/cumulativeVolumeKS
//FastTenkanSenCalculation
typicalPriceTF=(high+low+close)/3
typicalPriceVolumeTF=typicalPriceTF*volume
cumulativeTypicalPriceVolumeTF=sum(typicalPriceVolumeTF,fasttenkansenPeriod)
cumulativeVolumeTF=sum(volume,fasttenkansenPeriod)
fasttenkansenvwapValue=cumulativeTypicalPriceVolumeTF/cumulativeVolumeTF
//FastKijunSenCalculation
typicalPriceKF=(high+low+close)/3
typicalPriceVolumeKF=typicalPriceKS*volume
cumulativeTypicalPriceVolumeKF=sum(typicalPriceVolumeKF,fastkijunsenPeriod)
cumulativeVolumeKF=sum(volume,fastkijunsenPeriod)
fastkijunsenvwapValue=cumulativeTypicalPriceVolumeKF/cumulativeVolumeKF
//SlowLeadLineCalculation

lowesttenkansen_s=lowest(slowtenkansenvwapValue,slowtenkansenPeriod)
highesttenkansen_s=highest(slowtenkansenvwapValue,slowtenkansenPeriod)
lowestkijunsen_s=lowest(slowkijunsenvwapValue,slowkijunsenPeriod)
highestkijunsen_s=highest(slowkijunsenvwapValue,slowkijunsenPeriod)
slowtenkansen=avg(lowesttenkansen_s,highesttenkansen_s)
slowkijunsen=avg(lowestkijunsen_s,highestkijunsen_s)
slowleadLine=avg(slowtenkansen,slowkijunsen)
//FastLeadLineCalculation

lowesttenkansen_f=lowest(fasttenkansenvwapValue,fasttenkansenPeriod)
highesttenkansen_f=highest(fasttenkansenvwapValue,fasttenkansenPeriod)
lowestkijunsen_f=lowest(fastkijunsenvwapValue,fastkijunsenPeriod)
highestkijunsen_f=highest(fastkijunsenvwapValue,fastkijunsenPeriod)
fasttenkansen=avg(lowesttenkansen_f,highesttenkansen_f)
fastkijunsen=avg(lowestkijunsen_f,highestkijunsen_f)
fastleadLine=avg(fasttenkansen,fastkijunsen)
//BBleadLineCalculation

BBleadLine=avg(fastleadLine,slowleadLine)
//BollingerBandCalculation

basis=sma(BBleadLine,BBlength)
dev=BBmult*stdev(BBleadLine,BBlength)
upper=basis+dev
lower=basis-dev
//TSVCalculation
tsv=sum(close>close[1]?volume*(close-close[1]):close<close[1]?volume*(close-close[1]):0,tsvlength)
tsvema=ema(tsv,tsvemaperiod)
//RulesforEntry&Exit
if(vidyachoice?fastleadLine>fastleadLine[1]andslowleadLine>slowleadLine[1]andtsv>0andtsv>tsvemaandclose>upperandclose>vidyaandinDateRange:fastleadLine>fastleadLine[1]andslowleadLine>slowleadLine[1]andtsv>0andtsv>tsvemaandclose>upperandinDateRange)
strategy.entry("BUY",strategy.long)

if(fastleadLine<fastleadLine[1]andslowleadLine<slowleadLine[1])
strategy.close("BUY")
//Plots
plot(vidya,title="VIDYA",linewidth=2,color=color.yellow)
colorsettingS=input(title="SolidColorSlowLeadline",defval=false,type=input.bool)
plot(slowleadLine,title="SlowLeadLine",color=colorsettingS?color.aqua:slowleadLine>slowleadLine[1]?color.green:color.red,linewidth=3)
colorsettingF=input(title="SolidColorFastLeadline",defval=false,type=input.bool)
plot(fastleadLine,title="FastLeadLine",color=colorsettingF?color.orange:fastleadLine>fastleadLine[1]?color.green:color.red,linewidth=3)
p1=plot(upper,"UpperBB",color=#2962FF)
p2=plot(lower,"LowerBB",color=#2962FF)
fill(p1,p2,title="Background",color=color.blue)
Expand (153 lines)
