Script Name: Inside Bar Strategy w- SL
Author: tweakerID
Description: "Inside bars are a two -bar pattern. They can indicate either a continuation of the
existing move or a reversal. A continuation occurs when there is no significant
support or resistance level in sight, while a reversal occurs close to a strong sup-
port or resistance level...
...A lot of traders are aware of inside bars but few manage to make money with
them....
PineScript code:

Pine Script™ strategy
Inside Bar Strategy w/ SL
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  From  "Day  Trading  Cryptocurrency
//  Strategies,  Tactics,  Mindset,  and  Tools  Required  To  Build  Your
//  New  Income  Stream"
//  by  Phil  C.  Senior
//  "Inside  bars  are  a  two  -bar  pattern.  They  can  indicate  either  a  continuation  of  the
//  existing  move  or  a  reversal.  A  continuation  occurs  when  there  is  no  significant
//  support  or  resistance  level  in  sight,  while  a  reversal  occurs  close  to  a  strong  sup-
//  port  or  resistance  level...
//  ...A  lot  of  traders  are  aware  of  inside  bars  but  few  manage  to  make  money  with
//  them.  Why  is  this  so?  It  goes  back  to  interpreting  price  action.  A  lot  of  traders  look
//  to  trade  in  geometric  ways.  What  I  mean  is  that  they  search  for  fancy  shapes  on  a
//  chart  and  think  that  this  is  what  represents  true  price  action.
//  This  is  not  the  case.  A  shape  is  just  a  shape.  The  formation  by  itself  means
//  nothing  unless  underlying  order  flow  backs  it  up.  This  is  why  it’s  extremely  impor-
//  tant  that  you  look  for  inside  bars  when  a  trend  is  already  in  place.  The  best  place  to
//  look  for  them  is  in  the  beginning  of  trends."
//  ©  tweakerID
//@version=4
strategy("Inside  Bar  Strategy  w/  SL",
          overlay=true,
          default_qty_type=strategy.percent_of_equity,
          default_qty_value=100,
          initial_capital=10000,
          commission_value=0.04,
          calc_on_every_tick=false,
          slippage=0)
direction  =  input(0,  title  =  "Strategy  Direction",  type=input.integer,  minval=-1,  maxval=1)
strategy.risk.allow_entry_in(direction  ==  0  ?  strategy.direction.all  :  (direction  <  0  ?  strategy.direction.short  :  strategy.direction.long))
///////////////////////  STRATEGY  INPUTS  ////////////////////////////////////////
title1=input(true,  "-----------------Strategy  Inputs-------------------")
i_NBars  =  input(defval=1,  type=input.integer,  title="#  Of  Inside  Bars  in  pattern",  options=[1,  2,  3,  4])
i_BarsDirection  =  input(false,  title="Only  trade  using  complete  bullish  or  bearish  patterns")
i_MAFilter  =  input(true,  title="Use  MA  Trend  Filter")
i_MALen  =  input(65,  title="MA  Length")
///////////////////////  BACKTESTER  /////////////////////////////////////////////
title2=input(true,  "-----------------General  Inputs-------------------")
//  Backtester  General  Inputs
i_SL=input(true,  title="Use  Stop  Loss  and  Take  Profit")
i_SLType=input(defval="ATR  Stop",  title="Type  Of  Stop",  options=["Strategy  Stop",  "Swing  Lo/Hi",  "ATR  Stop"])
i_SPL=input(defval=10,  title="Swing  Point  Lookback")
i_PercIncrement=input(defval=1,  step=.1,  title="Swing  Point  SL  Perc  Increment")*0.01
i_ATR  =  input(14,  title="ATR  Length")
i_ATRMult  =  input(5,  step=.1,  title="ATR  Multiple")
i_TPRRR  =  input(2,  step=.1,  title="Take  Profit  Risk  Reward  Ratio")
TS=input(false,  title="Trailing  Stop")
//  Bought  and  Sold  Boolean  Signal
bought  =  strategy.position_size  >  strategy.position_size[1]
  or  strategy.position_size  <  strategy.position_size[1]
//  Price  Action  Stop  and  Take  Profit
LL=(lowest(i_SPL))*(1-i_PercIncrement)
HH=(highest(i_SPL))*(1+i_PercIncrement)
LL_price  =  valuewhen(bought,  LL,  0)
HH_price  =  valuewhen(bought,  HH,  0)
entry_LL_price  =  strategy.position_size  >  0  ?  LL_price  :  na
entry_HH_price  =  strategy.position_size  <  0  ?  HH_price  :  na
tp=strategy.position_avg_price  +  (strategy.position_avg_price  -  entry_LL_price)*i_TPRRR
stp=strategy.position_avg_price  -  (entry_HH_price  -  strategy.position_avg_price)*i_TPRRR
//  ATR  Stop
ATR=atr(i_ATR)*i_ATRMult
ATRLong  =  ohlc4  -  ATR
ATRShort  =  ohlc4  +  ATR
ATRLongStop  =  valuewhen(bought,  ATRLong,  0)
ATRShortStop  =  valuewhen(bought,  ATRShort,  0)
LongSL_ATR_price  =  strategy.position_size>0?ATRLongStop:na
ShortSL_ATR_price=strategy.position_size<0?ATRShortStop:na
ATRtp=strategy.position_avg_price+(strategy.position_avg_price-LongSL_ATR_price)*i_TPRRR
ATRstp=strategy.position_avg_price-(ShortSL_ATR_price-strategy.position_avg_price)*i_TPRRR
//StrategyStop
floatLongStop=valuewhen(bought,low[1],0)*(1-i_PercIncrement)
floatShortStop=valuewhen(bought,high[1],0)*(1+i_PercIncrement)
floatStratTP=na
floatStratSTP=na
///////////////////////STRATEGYLOGIC/////////////////////////////////////////
MAFilter=close>sma(close,i_MALen)
plot(i_MAFilter?sma(close,i_MALen):na)
bullBar=close>open
bearBar=close<open
contbullBar=barssince(notbullBar)>=(i_NBars+1)
contbearBar=barssince(notbearBar)>=(i_NBars+1)
InsideBar(NBars)=>
Inside1Bar=high<high[1]andlow>low[1]
Inside2Bar=high<high[2]andlow>low[2]andInside1Bar
Inside3Bar=high<high[3]andlow>low[3]andInside1BarandInside2Bar
Inside4Bar=high<high[4]andlow>low[4]andInside1BarandInside2BarandInside3Bar
ifNBars==1
inside1Bar=Inside1Bar
[inside1Bar]
elseifNBars==2
inside2Bar=Inside2Bar
[inside2Bar]
elseifNBars==3
inside3Bar=Inside3Bar
[inside3Bar]
elseifNBars==4
inside4Bar=Inside4Bar
[inside4Bar]
else
[na]
[insideBar]=InsideBar(i_NBars)

bullInsideBar=bar_index>40andinsideBarandbullBar
and(i_BarsDirection?contbullBar:true)and(i_MAFilter?MAFilter:true)
bearInsideBar=bar_index>40andinsideBarandbearBar
and(i_BarsDirection?contbearBar:true)and(i_MAFilter?notMAFilter:true)
BUY=bullInsideBar
SELL=bearInsideBar
//DebuggingPlots
plot(contbullBar?1:0,transp=100,title="contbullBar")
plot(contbearBar?1:0,transp=100,title="contbearBar")
//TradingInputs
DPR=input(true,"AllowDirectPositionReverse")
reverse=input(false,"ReverseTrades")
//Entries
ifreverse
ifnotDPR
strategy.entry("long",strategy.long,when=SELLandstrategy.position_size==0)
strategy.entry("short",strategy.short,when=BUYandstrategy.position_size==0)
else
strategy.entry("long",strategy.long,when=SELL)
strategy.entry("short",strategy.short,when=BUY)
else
ifnotDPR
strategy.entry("long",strategy.long,when=BUYandstrategy.position_size==0)
strategy.entry("short",strategy.short,when=SELLandstrategy.position_size==0)
else
strategy.entry("long",strategy.long,when=BUY)
strategy.entry("short",strategy.short,when=SELL)
SL=i_SLType=="SwingLo/Hi"?entry_LL_price:i_SLType=="ATRStop"?LongSL_ATR_price:LongStop
SSL=i_SLType=="SwingLo/Hi"?entry_HH_price:i_SLType=="ATRStop"?ShortSL_ATR_price:ShortStop
TP=i_SLType=="SwingLo/Hi"?tp:i_SLType=="ATRStop"?ATRtp:StratTP
STP=i_SLType=="SwingLo/Hi"?stp:i_SLType=="ATRStop"?ATRstp:StratSTP
//TrailingStop
dif=(valuewhen(strategy.position_size>0andstrategy.position_size[1]<=0,high,0))
-strategy.position_avg_price
trailOffset=strategy.position_avg_price-SL
vartstop=float(na)
ifstrategy.position_size>0
tstop:=high-trailOffset-dif
iftstop<tstop[1]
tstop:=tstop[1]
else
tstop:=na
StrailOffset=SSL-strategy.position_avg_price
varStstop=float(na)
Sdif=strategy.position_avg_price-(valuewhen(strategy.position_size<0
andstrategy.position_size[1]>=0,low,0))
ifstrategy.position_size<0
Ststop:=low+StrailOffset+Sdif
ifStstop>Ststop[1]
Ststop:=Ststop[1]
else
Ststop:=na
strategy.exit("TP&SL","long",limit=TP,stop=TS?tstop:SL,when=i_SL)
strategy.exit("TP&SL","short",limit=STP,stop=TS?Ststop:SSL,when=i_SL)
///////////////////////PLOTS//////////////////////////////////////////////////
plot(i_SLandstrategy.position_size>0andnotTS?SL:i_SLandstrategy.position_size>0andTS?tstop:na,title='SL',style=plot.style_cross,color=color.red)
plot(i_SLandstrategy.position_size<0andnotTS?SSL:i_SLandstrategy.position_size<0andTS?Ststop:na,title='SSL',style=plot.style_cross,color=color.red)
plot(i_SLandstrategy.position_size>0?TP:na,title='TP',style=plot.style_cross,color=color.green)
plot(i_SLandstrategy.position_size<0?STP:na,title='STP',style=plot.style_cross,color=color.green)
//Drawpriceactionsetuparrows
plotshape(BUY?1:na,style=shape.triangleup,location=location.belowbar,
color=color.green,title="BullishSetup",size=size.auto)
plotshape(SELL?1:na,style=shape.triangledown,location=location.abovebar,
color=color.red,title="BearishSetup",size=size.auto)

Expand (194 lines)
