Script Name: Jaws Mean Reversion [Strategy]
Author: TraderHalai
Description: This very simple strategy is an implementation of PJ Sutherlands' Jaws Mean reversion algorithm. It simply buys when a small moving average period (e.g. 2) is below
a longer moving average period (e.g. 5) by a certain percentage and closes when the small period average crosses over the longer moving average.

If you are going to use this, you may wish to apply...
PineScript code:

Pine Script™ strategy
Jaws Mean Reversion [Strategy]
//  @version=4
//
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//
//  @author  Sunil  Halai
//
//  This  very  simple  strategy  is  an  implementation  of  PJ  Sutherlands'  Jaws  Mean  reversion  algorithm.  It  simply  buys  when  a  small  moving  average  period  (e.g.  2)  is  below
//  a  longer  moving  average  period  (e.g.  8)  by  a  certain  percentage,  and  closes  when  the  small  period  average  crosses  over  the  longer  moving  average.
//
//  If  you  are  going  to  use  this,  you  may  wish  to  apply  this  to  a  range  of  investment  assets,  as  the  amount  signals  is  low.  Alternatively  you  may  wish  to  tweak  the  settings  to  provide  more
//  signals.
strategy("Jaws  Mean  Reversion  [Strategy]",  overlay  =  true)
//Strategy  inputs
source  =  input(title  =  "Source",  defval  =  close)
smallMAPeriod  =  input(title  =  "Small  Moving  Average",  defval  =  2)
bigMAPeriod  =  input(title  =  "Big  Moving  Average",  defval  =  8)
percentBelowToBuy  =  input(title  =  "Percent  below  to  buy  %",  defval  =  1)
//Strategy  calculation
smallMA  =  sma(source,  smallMAPeriod)
bigMA  =    sma(source,  bigMAPeriod)
buyMA  =  ((100  -  percentBelowToBuy)  /  100)  *  sma(source,  bigMAPeriod)[0]
if(crossunder(smallMA,  buyMA))
        strategy.entry("BUY",  strategy.long)
if(crossover(smallMA,  bigMA))
        strategy.close("BUY")
Expand (32 lines)
