Script Name: KISS Strategy- SMA + EMA
Author: MakeMoneyCoESTB2020
Description: //Hello my fellow investors
//I am creating a simple non-cluttered strategy that uses 3(+1) simple means to determine: viability, entry, and exit
//1) Has a consistent trend been maintained for several days/weeks
//2) SH SMA crossover LG SMA = Bullish entry/LG SMA crossover SH SMA = Bearish entry
//3) Use the Slope factor & Weeks in Trend (WiT) to dertermine how...
PineScript code:

Pine Script™ strategy
KISS Strategy: SMA + EMA
//@version=4
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  MakeMoneyCoESTB2020
//*********************Notes  for  continued  work***************
//************************************************************
//Hello  my  fellow  investors
//I  am  creating  a  simple  non-cluttered  strategy  that  uses  3(+1)  simple  means  to  determine:  viability,  entry,  and  exit
//1)  Has  a  consistent  trend  been  maintained  for  several  days/weeks
//2)  SH  SMA  crossover  LG  SMA  =  Bullish  entry/LG  SMA  crossover  SH  SMA  =  Bearish  entry
//3)  Use  the  Slope  factor  &  Weeks  in  Trend  (WiT)  to  dertermine  how  strong  of  an  entry  signal  you  are  comfortable  with
//3+1)  For  added  confidence  in  trend  detection:  Apply  MACD  check  -  buy-->  MACD  line  above  signal  line  and  corssover  below  histogram  \\  sell  -->  MACD  line  below  signal  line  and  crossover  above  histogram.
//4)  Exit  position  based  on  next  SMA  cross  and  trend  reversal  or  stop  loss%
//*)This  code  also  allows  you  to  determine  your  desired  backtesting  date  compliments  of  alanaster
//This  code  is  the  product  of  many  hours  of  hard  work  on  the  part  of  the  greater  tradingview  community.    The  credit  goes  to  everyone  in  the  community  who  has  put  code  out  there  for  the  greater  good.
//Happy  Hunting!
//  1.  Define  strategy  settings*************************************************************************************************************************************************************************
//Title
strategy("KISS  Strategy:  SMA  +  EMA",  shorttitle="KISS  Strat",  default_qty_type=strategy.percent_of_equity,  default_qty_value=5,  initial_capital=20000,slippage=2,  currency=currency.USD,  overlay=true,  pyramiding=2)
//define  calculations  price  source
price  =  input(title="Price  Source",  defval=close)
//Does  user  want  to  run  the  Strategy  for  Trending  Up  or  Trending  Down
RunTrend=input(title="Run  Strategy  Trending  Up,  Down,  or  Both",  defval="Both",  options=["Up",  "Down",  "Both"])
//  2.  Calculate  strategy  values*************************************************************************************************************************************************************************
//Calculate  13/30/200SMA
SH_SMA_length=  input(title="SH  SMA  Length",  defval=13)  //short  SMA  length
LG_SMA_length=  input(title="LG  SMA  Length",  defval=30)  //long  SMA  length
GV_SMA_length=  input(title="SH  SMA  Length",  defval=200)  //Gravitational  SMA  length
SH_SMA=sma(price,  SH_SMA_length)  //short  SMA
LG_SMA=sma(price,  LG_SMA_length)  //long  SMA
GV_SMA=sma(price,  GV_SMA_length)  //gravitational  SMA
//calculate  MACD
//define  variables  for  speed
fast  =  12,  slow  =  26
//define  parameters  to  calculate  MACD
fastMA  =  ema(price,  fast)
slowMA  =  ema(price,  slow)
//define  MACD  line
macd  =  fastMA  -  slowMA
//define  SIGNAL  line
signal  =  sma(macd,  9)
//Determine  what  type  of  trend  we  are  in
dcp  =  security(syminfo.tickerid,  'D',  close)      //daily  close  price
wcp  =  security(syminfo.tickerid,  'W',  close)      //weekly  close  price
WiT  =  input(title="Weeks  In  Trend",  defval=1,  maxval=5,  minval=1)        //User  input  for  how  many  weeks  of  price  action  to  evaluate  (Weeks  in  Trend  =  WiT)
BearTrend  =  false              //initialize  trend  variables  as  false
BullTrend  =  false              //initialize  trend  variables  as  false
//  BullTrend  :=  (wcp  >  SH_SMA)  and  (SH_SMA  >  LG_SMA)    //true  if  price  is  trending  up  based  on  weekly  price  close
//  BearTrend  :=  (wcp  <  SH_SMA)  and  (SH_SMA  <  LG_SMA)    //true  if  price  is  trending  down  based  on  weekly  price  close
//  BullTrend  :=  (price  >  SH_SMA)  and  (SH_SMA  >  LG_SMA)    //true  if  price  is  trending  up
//  BearTrend  :=  (price  <  SH_SMA)  and  (SH_SMA  <  LG_SMA)    //true  if  price  is  trending  down
//Determine  if  the  market  has  been  in  a  trend  for  'n'  weeks
n=WiT                                                      //create  loop  internal  counting  variable
for  i=1  to  WiT                                    //create  loop  to  determine  if  BearTrend=true  to  set  number  of  weeks
        if  (wcp[n]  <  price)                  //evaluate  if  BearTrend=false  comparing  the  current  price  to  a  paticular  week  close
                BearTrend  :=  false            //set  value  to  false  if  older  price  value  is  less  than  newer:  trending  up
                break                                      //break  out  of  for  loop  when  trend  first  falters
        if  (wcp[n]  >  price)                  //evaluate  if  BearTrend=true  comparing  the  current  price  to  a  paticular  week  close
                BearTrend  :=  true              //set  value  to  true  if  older  price  value  is  greater  than  newer:  trending  down
        n:=n-1                                            //set  internal  counter  one  day  closer  to  present
m=WiT                                                      //create  loop  internal  counting  variable
for  j=1  to  WiT                                    //create  loop  to  determine  if  BearTrend=true  to  set  number  of  weeks
        if  (wcp[m]  >  price)                  //evaluate  if  BullTrend=false  comparing  the  current  price  to  a  paticular  week  close
                BullTrend  :=  false            //set  value  to  false  if  older  price  value  is  greater  than  newer:  trending  down
                break                      //breakoutofforloopwhentrendfirstfalters
if(wcp[m]<price)//evaluateifBullTrend=truecomparingthecurrentpricetoapaticularweekclose
BullTrend:=true//setvaluetotrueifolderpricevalueislessthannewer:trendingup
m:=m-1//setinternalcounteronedayclosertopresent
//Determineifcrossingsoccur
SH_LGcrossover=crossover(SH_SMA,LG_SMA)//returnstrueifshortcrossesoverlong
SH_LGcrossunder=crossunder(SH_SMA,LG_SMA)//returnstrueifshortcrossesunderlong
//DeterminetheslopeoftheSMAswhenacrossoveroccurs
SlopeFactor=input(title="SlopeFactor",defval=.01,minval=0,step=0.001)//userinputvariableforwhatslopetoevaluateagainst
XSlopeSH=abs(SH_SMA-SH_SMA[2])//slopeofshortmovingaverage(timecancelsout)
XSlopeLG=abs(LG_SMA-LG_SMA[2])//slopeoflongmovingaverage(timecancelsout)
StrongSlope=iff(abs(XSlopeSH-XSlopeLG)>SlopeFactor,true,false)//createabooleanvariabletodetermineisslopeintensityrequirementismet
//************************************INPUTBACKTESTRANGE******************************************===coutesyofalanaster
fromMonth=input(defval=4,title="FromMonth",type=input.integer,minval=1,maxval=12)
fromDay=input(defval=1,title="FromDay",type=input.integer,minval=1,maxval=31)
fromYear=input(defval=2020,title="FromYear",type=input.integer,minval=1970)
thruMonth=input(defval=1,title="ThruMonth",type=input.integer,minval=1,maxval=12)
thruDay=input(defval=1,title="ThruDay",type=input.integer,minval=1,maxval=31)
thruYear=input(defval=2112,title="ThruYear",type=input.integer,minval=1970)
//===INPUTSHOWPLOT===
showDate=input(defval=true,title="ShowDateRange",type=input.bool)
//===FUNCTIONEXAMPLE===
start=timestamp(fromYear,fromMonth,fromDay,00,00)//backteststartwindow
finish=timestamp(thruYear,thruMonth,thruDay,23,59)//backtestfinishwindow
window()=>time>=startandtime<=finish?true:false//createfunction"withinwindowoftime"
bgcolor(color=showDateandwindow()?color.gray:na,transp=90)
//===EXECUTION===
//strategy.entry("L",strategy.long,when=window()andcrossOv)//enterlongwhen"withinwindowoftime"ANDcrossover
//strategy.close("L",when=window()andcrossUn)//exitlongwhen"withinwindowoftime"ANDcrossunder
//3.Outputstrategydata*************************************************************************************************************************************************************************
//Emboldenlineifatrendexists
trendcolorLG=BearTrend?color.red:color.black//highlightsbeartrendconditionmetgraphically
trendcolorSH=BullTrend?color.green:color.black//highlightsbeartrendconditionmetgraphically
//plotSMAs
plot(SH_SMA,title="SHSMA",color=trendcolorSH)
plot(LG_SMA,title="LGSMA",color=trendcolorLG)
plot(GV_SMA,title="GVSMA",color=color.silver,linewidth=4,transp=70)
//Highlightcrossovers
plotshape(series=SH_LGcrossover,style=shape.arrowup,location=location.belowbar,size=size.normal,color=color.green)
plotshape(series=SH_LGcrossunder,style=shape.arrowdown,location=location.abovebar,size=size.normal,color=color.red)
//4.DetermineLong&ShortEntryCalculations*************************************************************************************************************************************************************************
//Determinewhentorunthestrategybasedonuserinputforuptrendordowntrend
RunTrendUp=false//VaribileforrunningtheStrategyinanUpTrend
RunTrendUp:=iff(RunTrend=="Up"orRunTrend=="Both",true,false)
RunTrendDWN=false//VaribileforrunningtheStrategyinaDownTrend
RunTrendDWN:=iff(RunTrend=="Down"orRunTrend=="Both",true,false)
//Definecountbackvariable
countback=input(minval=0,maxval=5,title="PriceCountBack",defval=0)
//Userinputforwhatevaluationstorun:SMAorSMA+EMA
SMA_Y_N=input(defval="Y",title="RunSMA",type=input.string,options=["Y","N"])
MACD_Y_N=input(defval="N",title="RunMACD",type=input.string,options=["Y","N"])
//CalculateSMACrossentryconditions
SMAbuy=false
SMAsell=false
SMAbuy:=SH_LGcrossoverandStrongSlopeandBearTrend[WiT*7]//enterlongifshortSMAcrossesoverlongSMA&securityhasbeeninaBearTrendfor'n'daysback
SMAsell:=SH_LGcrossunderandStrongSlopeandBullTrend[WiT*7]//entershortifshortSMAcrossesunderlongSMA&securityhasbeeninaBullTrendfor'n'daysback
//CalculateMACDCrossentryconditions
MACDbuy=iff(MACD_Y_N=="Y",crossunder(signal[countback],macd[countback]),true)andiff(MACD_Y_N=="Y",macd[countback]<0,true)andStrongSlopeandBearTrend//enterlongiffastMACDcrossesoverslowMACD&thereisastrongslope&securityhasbeeninaBearTrendfor'n'daysback
MACDsell=iff(MACD_Y_N=="Y",crossunder(macd[countback],signal[countback]),true)andiff(MACD_Y_N=="Y",signal[countback]>0,true)andStrongSlopeandBullTrend//entershortiffastMACDcrossesunderslowMACD&thereisastrongslope&securityhasbeeninaBullTrendfor'n'daysback
//longentrycondition
dataHCLB=(iff(SMA_Y_N=="Y",SMAbuy,true)andiff(MACD_Y_N=="Y",MACDbuy,true)andRunTrendUp)
plotshape(dataHCLB,title="HC-LB",color=color.lime,style=shape.circle,text="HC-LB")
strategy.entry("HC-Long",strategy.long,comment="HC-Long",when=dataHCLBandwindow())
//shortentrycondition
dataHCSB=(iff(SMA_Y_N=="Y",SMAsell,true)andiff(MACD_Y_N=="Y",MACDsell,true)andRunTrendDWN)
plotshape(dataHCSB,title="HC-SB",color=color.fuchsia,style=shape.circle,text="HC-SB")
strategy.entry("HC-Short",strategy.short,comment="HC-Short",when=dataHCSBandwindow())
//5.SubmitProfitandLossExitCalculationsOrders*************************************************************************************************************************************************************************
//UserOptionstoChangeInputs
//DoesuserwanttorunaTrailingStop
trailStop_YN=input(title="RunaTrailingStop",defval="N",options=["Y","N"])
TrailPerc=input(title="TrailLoss%",type=input.float,minval=0,step=1,defval=6)/100
stopPer=input(12,title='StopLoss%',type=input.float)/100
takePer=input(25,title='TakeProfit%',type=input.float)/100
//calculateTrailstoppriceforMD_EMATGT%condition
longStopPrice=0.0//longsideentrystopvariable
longStopPrice:=if(strategy.position_size>0)
stopValue=close*(1-TrailPerc)
max(stopValue,longStopPrice[1])
else
0

shortStopPrice=0.0//shortsideentrystopvariable
shortStopPrice:=if(strategy.position_size<0)
shortStopValue=close*(1+TrailPerc)
min(shortStopValue,shortStopPrice[1])
else
999999

//Determinewhereyou'veenteredandinwhatdirection
longStop=strategy.position_avg_price*(1-stopPer)
shortStop=strategy.position_avg_price*(1+stopPer)
shortTake=strategy.position_avg_price*(1-takePer)
longTake=strategy.position_avg_price*(1+takePer)
//exitpositionconditionsandorders
ifstrategy.position_size>0//longsideexitconditions
iftrailStop_YN=="Y"
strategy.exit(id="CloseLong",when=window(),stop=longStop,limit=longTake,qty_percent=50)//sell50%wheneithertheTGTortheSLishitthentransitiontoatrailingstoploss
strategy.exit(id="CloseLongTrailingStop",when=window(),stop=longStopPrice,qty_percent=100)
iftrailStop_YN=="N"
strategy.exit(id="CloseLong",when=window(),stop=longStop,limit=longTake)//sellwheneithertheTGTortheSLishit


ifstrategy.position_size<0//shortsideexitconditions
iftrailStop_YN=="Y"
strategy.exit(id="CloseShort",when=window(),stop=shortStop,limit=shortTake,qty_percent=50)//sell50%wheneithertheTGTortheSLishitthentransitiontoatrailingstoploss
strategy.exit(id="CloseShortTrailingStop",when=window(),stop=shortStopPrice,qty_percent=100)
iftrailStop_YN=="N"
strategy.exit(id="CloseShort",when=window(),stop=shortStop,limit=shortTake)//sellwheneithertheTGTortheSLishit
//Plotstoptrailinglossvaluesforconfirmation
plot(series=(strategy.position_size>0and(trailStop_YN=="Y"))?longStopPrice:na,color=color.fuchsia,style=plot.style_cross,linewidth=2,title="LongTrailStop")//plotthetrailingstoponthechartforanuptrend
plot(series=(strategy.position_size<0and(trailStop_YN=="Y"))?shortStopPrice:na,color=color.fuchsia,style=plot.style_cross,linewidth=2,title="ShortTrailStop")//plotthetrailingstoponthechartforadowntrend
//plotfixedstoplossvalue
plot(series=(strategy.position_size>0and(trailStop_YN=="N"))?longStop:na,color=color.fuchsia,style=plot.style_cross,linewidth=2,title="LongTrailStop")//plotthestoponthechartforanuptrend
plot(series=(strategy.position_size<0and(trailStop_YN=="N"))?shortStop:na,color=color.fuchsia,style=plot.style_cross,linewidth=2,title="ShortTrailStop")//plotthestoponthechartforadowntrend
//plottheTGTprofitpoints
plot(series=(strategy.position_size>0)?longTake:na,color=color.lime,style=plot.style_cross,linewidth=2,title="ShortTrailStop")//plottheTGT%forlongposition
plot(series=(strategy.position_size<0)?shortTake:na,color=color.lime,style=plot.style_cross,linewidth=2,title="ShortTrailStop")//plottheTGT%forshortposition
////Determinewhereyou'veenteredandinwhatdirection
//longStop=strategy.position_avg_price*(1-stopPer)
//shortStop=strategy.position_avg_price*(1+stopPer)
//shortTake=strategy.position_avg_price*(1-takePer)
//longTake=strategy.position_avg_price*(1+takePer)
////exitpositionconditionsandorders
//ifstrategy.position_size>0//orcrossunder(price[countback],upperBB)
//strategy.exit(id="CloseLong",when=window(),stop=longStop,limit=longTake)
//ifstrategy.position_size<0//orcrossover(price[countback],lowerBB)
//strategy.exit(id="CloseShort",when=window(),stop=shortStop,limit=shortTake)
//Evaluate/debugequation***************************************************************************************************************************************************************************
//plotshape((n==5?true:na),title='n=5',style=shape.labeldown,location=location.abovebar,text='5',color=color.white,textcolor=color.black,transp=0)//printnvalueif5
//plotshape((n==4?true:na),title='n=4',style=shape.labeldown,location=location.abovebar,text='4',color=color.white,textcolor=color.black,transp=0)//printnvalueif4
//plotshape((n==3?true:na),title='n=3',style=shape.labeldown,location=location.abovebar,text='3',color=color.white,textcolor=color.black,transp=0)//printnvalueif3
//plotshape((n==2?true:na),title='n=2',style=shape.labeldown,location=location.abovebar,text='2',color=color.white,textcolor=color.black,transp=0)//printnvalueif2
//plotshape((n==1?true:na),title='n=1',style=shape.labeldown,location=location.abovebar,text='1',color=color.white,textcolor=color.black,transp=0)//printnvalueif1
//lineValue=11//setrandomvisiblelinevaluetocheckwhenequationistrue
//colorP=(BearTrend==true)?color.green:color.red
//plot(lineValue,title="BearTrend",color=colorP)//Plotwhenconditiontrue=green,false=red
//plot(XSlopeLG+15,color=color.white)//usedforcodedebugging
//plot(XSlopeSH+15,color=color.blue)//usedforcodedebugging
//plot(abs(XSlopeSH-XSlopeLG)+20,color=color.fuchsia)//usedforcodedebugging
Expand (266 lines)
