Script Name: Kitchen [ilovealgotrading]
Author: lovealgotrading
Description: OVERVIEW:

Kitchen is a strategy that aims to trade in the direction of the trend by using supertrend and stochRsi data by calculating at different time values.


 IMPLEMENTATION DETAILS – SETTINGS:

First of all, let's understand the supertrend and stocrsi indicators.
 How do you read and use Super Trend for trading ?
The price is often going upwards when...
PineScript code:

Pine Script™ strategy
Kitchen [ilovealgotrading]
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  Baby_whale_to_moon
//@version=5
strategy('Kitchen  [ilovealgotrading]',  overlay=true,  format=format.price,  initial_capital  =  1000)
//  BACKTEST  DATE
Start_Time  =  input.time(defval=timestamp('01  January  2017  13:30  +0000'),  title='Start_Time',  group  =  "  #################  BACKTEST  DATE  ################  "  )
End_Time  =  input.time(defval=timestamp('30  April  2024  19:30  +0000'),  title='End_Time',  group  =  "  #################  BACKTEST  DATE  ################  "  )
//  supertrend
atrPeriod  =  input(10,  'ATR  Length',  group  =  "  #################    Supertrend    ################  ")
factor  =  input(3,  'Factor',  group  =  "  #################    Supertrend    ################  ")
time1  =  input.string(title='Short  Time  Period',  defval='07  1h',  options=['01  1m','02  3m','03  5m',    '04  15m',  '05  30m',  '06  45m',  '07  1h',  '08  2h',  '09  3h',  '10  4h',  '11  1D',  '12  1W'  ],  group  =  "  #################    Supertrend    ################  ",tooltip  =  "this  timeframe  is  the  value  of  our  short-time  supertrend  indicator")
time2  =  input.string(title='Long  Time  Period',  defval='10  4h',  options=[  '01  1m','02  3m','03  5m',  '04  15m',  '05  30m',  '06  45m',  '07  1h',  '08  2h',  '09  3h',  '10  4h',  '11  1D',  '12  1W'  ],  group  =  "  #################    Supertrend    ################  ",tooltip  =  "this  timeframe  is  the  value  of  our  long-time  supertrend  indicator")
res(Resolution)  =>
        if  Resolution  ==  '00  Current'
                timeframe.period
        else
                if  Resolution  ==  '01  1m'
                        '1'
                else
                        if  Resolution  ==  '02  3m'
                                '3'
                        else
                                if  Resolution  ==  '03  5m'
                                        '5'
                                else
                                        if  Resolution  ==  '04  15m'
                                                '15'
                                        else
                                                if  Resolution  ==  '05  30m'
                                                        '30'
                                                else
                                                        if  Resolution  ==  '06  45m'
                                                                '45'
                                                        else
                                                                if  Resolution  ==  '07  1h'
                                      '60'
else
ifResolution=='082h'
'120'
else
ifResolution=='093h'
'180'
else
ifResolution=='104h'
'240'
else
ifResolution=='111D'
'1D'
else
ifResolution=='121W'
'1W'
else
ifResolution=='131M'
'1M'
//supertrendLongtimeperiod
[supertrend2,direction2]=request.security(syminfo.tickerid,res(time2),ta.supertrend(factor,atrPeriod))
bodyMiddle4=plot((open+close)/2,display=display.none)
upTrend2=plot(direction2<0?supertrend2:na,'UpTrend',color=color.new(color.green,0),style=plot.style_linebr,linewidth=2)
downTrend2=plot(direction2<0?na:supertrend2,'DownTrend',color=color.new(color.red,0),style=plot.style_linebr,linewidth=2)
//supertrendshorttimeperiod
[supertrend1,direction1]=request.security(syminfo.tickerid,res(time1),ta.supertrend(factor,atrPeriod))
bodyMiddle=plot((open+close)/2,display=display.none)
upTrend=plot(direction1<0?supertrend1:na,'UpTrend',color=color.new(color.yellow,0),style=plot.style_linebr)
downTrend=plot(direction1<0?na:supertrend1,'DownTrend',color=color.new(color.orange,0),style=plot.style_linebr)
//StochasticRSI
low_limit_stoch_rsi=input.float(title='StochRsiLowLimit',step=0.5,defval=15,group="#################StochRSI################",tooltip="whenStockrsivaluecrossoverLowLimitvaluewegetLong")
up_limit_stoch_rsi=input.float(title='StochRsiUpLimit',step=0.5,defval=85,group="#################StochRSI################",tooltip="whenStockrsivaluecrossunderUpLimitvaluewegetShort")
stocrsi_back_length=input.int(20,'StochRsiretroactivelength',minval=1,group="#################StochRSI################",tooltip="Howmanycandlesareleftbehind,evenifthereisabuyorsellsignal,itwillbevalidnow")
smoothK=input.int(3,'StochasticRSIK',minval=1,group="#################StochRSI################")
lengthRSI=input.int(14,'RSILength',minval=1,group="#################StochRSI################")
lengthStoch=input.int(14,'StochasticLength',minval=1,group="#################StochRSI################")
src_rsi=input(close,title='RSISource',group="#################StochRSI################")
rsi1=request.security(syminfo.tickerid,'240',ta.rsi(src_rsi,lengthRSI))
k=request.security(syminfo.tickerid,'240',ta.sma(ta.stoch(rsi1,rsi1,rsi1,lengthStoch),smoothK))
//Strategysettings
dollar=input.float(title='DollarCostPerPosition',defval=1000,group="#################StrategySettings################")
trade_direction=input.string(title='Trade_direction',group="#################StrategySettings################",options=['LONG','SHORT','BOTH'],defval='BOTH')
Long_message_open=input('LongOpen',title="LongOpenMessage",group="#################StrategySettings################",tooltip="ifyouwriteyouralertwindowthiscode{{strategy.order.alert_message}}.WhentriggerLongsignalyouwillgetdynamicallywhatyoupastedhereforLongOpenMessage")
Short_message_open=input('ShortOpen',title="ShortOpenMessage",group="#################StrategySettings################",tooltip="ifyouwriteyouralertwindowthiscode{{strategy.order.alert_message}}.WhentriggerLongsignalyouwillgetdynamicallywhatyoupastedhereforShortOpenMessage")
Long_message_close=input('LongClose',title="LongCloseMessage",group="#################StrategySettings################",tooltip="ifyouwriteyouralertwindowthiscode{{strategy.order.alert_message}}.WhentriggerLongsignalyouwillgetdynamicallywhatyoupastedhereforLongCloseMessage")
Short_message_close=input('ShortClose',title="ShortCloseMessage",group="#################StrategySettings################",tooltip="ifyouwriteyouralertwindowthiscode{{strategy.order.alert_message}}.WhentriggerLongsignalyouwillgetdynamicallywhatyoupastedhereforShortCloseMessage")
Time_interval=time>Start_Timeandtime<End_Time
bgcolor(Time_interval?color.rgb(255,235,59,95):na)
back_long=0
back_short=0
fori=1tostocrsi_back_lengthby1
ifta.crossover(k,low_limit_stoch_rsi)[i]==true
back_long+=i
back_long
ifta.crossunder(k,up_limit_stoch_rsi)[i]==true
back_short+=i
back_short
//bgcolor(back_long>0?color.rgb(153,246,164,54):na)
//bgcolor(back_short>0?color.rgb(246,153,153,54):na)
buy_signal=false
sell_signal=false
ifdirection2<0anddirection1<0andback_long>0
buy_signal:=true
buy_signal
ifdirection2>0anddirection1>0andback_short>0
sell_signal:=true
sell_signal
//bgcolor(buy_signal?color.new(color.lime,90):na,title="BUYbgcolor")
plotshape(buy_signal[1]==falseandstrategy.opentrades==0andTime_intervalandbuy_signal?supertrend2:na,title="Buy",text="Buy",location=location.absolute,style=shape.labelup,size=size.tiny,color=color.green,textcolor=color.white)
//bgcolor(sell_signal?color.new(color.red,90):na,title="SELLbgcolor")
plotshape(sell_signal[1]==falseandstrategy.opentrades==0andTime_intervalandsell_signal?supertrend2:na,title="Sell",text="Sell",location=location.absolute,style=shape.labeldown,size=size.tiny,color=color.red,textcolor=color.white)
//Strategyentries
ifstrategy.opentrades==0andTime_intervalandbuy_signaland(trade_direction=='LONG'ortrade_direction=='BOTH')
strategy.entry('Long_Open',strategy.long,qty=dollar/close,alert_message=Long_message_open)
ifstrategy.opentrades==0andTime_intervalandsell_signaland(trade_direction=='SHORT'ortrade_direction=='BOTH')
strategy.entry('Short_Open',strategy.short,qty=dollar/close,alert_message=Short_message_open)
//StrategyClose
ifclose<supertrend1andstrategy.position_size>0
strategy.exit('Long_Close',from_entry="Long_Open",stop=close,qty_percent=100,alert_message=Long_message_close)
ifclose>supertrend1andstrategy.position_size<0
strategy.exit('Short_Close',from_entry="Short_Open",stop=close,qty_percent=100,alert_message=Short_message_close)
Expand (146 lines)
