Script Name: LarryWillians - Simple Strategy
Author: lhcbenac
Description: A simple and classic strategy on market, created by LarryWillians using a EMA9.
The brute model use a Cross from closing price on EMA9. But occurs many false entries.
In other to correct this kind of thing, I add a SMA21 to confirm the trend and decrease numbers of false trades.
The strategy waits to break the last High (for buy) a position.
As a strategy...
PineScript code:

Pine Script™ strategy
LarryWillians - Simple Strategy
//  @_benac
//@version=5
strategy('Larry',  overlay=true  ,  initial_capital=1000  )
////////////////////////////////////////////////////////
//                                                                                                        //
//                                  //
//CodigoOperacional//
////
////
////////////////////////////////////////////////////////
//UsageforStocks,orCriptoswithvaluebiggerthen1,cuzof0.01´pip.
//Dailytimeframe
//ObservationPoint
start=timestamp(2020,00,00,00,00)//backteststartwindow
finish=timestamp(2022,01,07,23,59)//backtestfinishwindow
window()=>time>=startandtime<=finish?true:false//createfunction"withinwindowoftime"
iftime<start
strategy.close_all("ClosingAll")
//Takeinfosfrominputs.
inp_mmshort=input.int(defval=9,title="MediaCurta")
inp_mminter=input.int(defval=21,title="MediaCurta")
//RiskManager,heredefinemaxandmin
inp_max=input.int(defval=15,title="PercentualGanho")
inp_min=input.int(defval=5,title="PercentalPerda")
//Convertingtheinputto%
pmax=(inp_max/100)
pmin=(inp_min/100)
//InfosFromMovingAverage
mm_short=ta.sma(close,inp_mmshort)
mm_inter=ta.ema(close,inp_mminter)
//TrendLogic
//LongCondition
//SetupdoLarryWilliansBemSimples,mediavirouparacimaerompeuamaximadereferencia,compra.
tendencia_alta=mm_short[2]>mm_short[1]andmm_short>mm_short[1]andclose>high[1]andclose>mm_shortandmm_short>mm_inter
tendencia_baixa=mm_short[2]<mm_short[1]andmm_short<mm_short[1]andclose>low[1]andclose<mm_shortandmm_short<mm_inter
//Creatingtheentry
iftendencia_alta
strategy.entry("Compra",strategy.long,stop=low-0.01)
stop_inst=low-0.01
iftendencia_baixa
strategy.entry("Venda",strategy.short,stop=high+0.01)
stop_inst=high+0.01
//TrailingStopCreation
//SellPosition
ifstrategy.position_size<0
gain_p=strategy.opentrades.entry_price(0)-(strategy.opentrades.entry_price(0)*pmax)
stop_p=strategy.opentrades.entry_price(0)+(strategy.opentrades.entry_price(0)*pmin)
//Managingtheposition
ifclose<gain_p
strategy.close_all(comment="1-Ganho:"+str.tostring(gain_p)+"Perda:"+str.tostring(stop_p))
ifclose>stop_p
strategy.close_all(comment="2-Ganho:"+str.tostring(gain_p)+"Perda:"+str.tostring(stop_p))

ifhigh>mm_short[1]
strategy.close_all(comment="3-Ganho:"+str.tostring(gain_p)+"Perda:"+str.tostring(stop_p))

//BuyPosition
ifstrategy.position_size>0
gain_p=strategy.opentrades.entry_price(0)+(strategy.opentrades.entry_price(0)*pmax)
stop_p=strategy.opentrades.entry_price(0)-(strategy.opentrades.entry_price(0)*pmin)
//Managingtheposition
ifclose>gain_p
strategy.close_all(comment="1-Ganho:"+str.tostring(gain_p)+"Perda:"+str.tostring(stop_p))
ifclose<stop_p
strategy.close_all(comment="2-Ganho:"+str.tostring(gain_p)+"Perda:"+str.tostring(stop_p))
iflow<mm_short[1]
strategy.close_all(comment="3-Ganho:"+str.tostring(gain_p)+"Perda:"+str.tostring(stop_p))

Expand (86 lines)
