Script Name: Linear Regression MA - Strategy
Author: lazy_capitalist
Description: using the linear regression and linear regression MA to enter long and short positions.
PineScript code:

Pine Script™ strategy
Linear Regression MA - Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  lazy_capitalist
//@version=5
strategy('Linear  Regression  MA',  overlay=true,  initial_capital=10000)
datesGroup  =  "Date  Info"
startMonth  =  input.int(defval  =  1,        title  =  "Start  Month",    minval  =  1,  maxval  =  12,    group=datesGroup)
startDay      =  input.int(defval  =  1,        title  =  "Start  Day",        minval  =  1,  maxval  =  31,    group=datesGroup)
startYear    =  input.int(defval  =  2022,  title  =  "Start  Year",      minval  =  1970,                        group=datesGroup)
averagesGroup  =  "Averages"
lrLineInput          =  input.int(title="Linear  Regression  Line",      defval=55,  minval  =  1,  group=averagesGroup)
lrMAInput              =  input.int(title="Linear  Regression  MA",          defval=55,  minval  =  1,  group=averagesGroup)
emaInput                =  input.int(title="EMA  Length",                              defval=55,  minval  =  1,  group=averagesGroup)
tradesGroup  =  "Execute  Trades"
executeLongInput        =  input.bool(title="Execute  Long  Trades",              defval=true)
executeShortInput      =  input.bool(title="Execute  Short  Trades",            defval=true)
executeStopLoss          =  input.bool(title="Execute  Stop  Loss",                  defval=true)
fourHrSMAExpr              =  ta.sma(close,  200)
fourHrMA                        =  request.security(symbol=syminfo.tickerid,  timeframe="240",  expression=fourHrSMAExpr)
bullish                          =  close  >  fourHrMA  ?  true  :  false
maxProfitInput                            =  input.float(    title="Max  Profit  (%)",                  defval=10.0,      minval=0.0)*0.01
stopLossPercentageInput=input.float(title="StopLoss(%)",defval=1.75,minval=0.0)*0.01
start=timestamp(startYear,startMonth,startDay,00,00)//backteststartwindow
window()=>time>=start?true:false//createfunction"withinwindowoftime"
showDate=input(defval=true,title="ShowDateRange")
lrLine=ta.linreg(close,lrLineInput,0)
lrMA=ta.sma(lrLine,lrMAInput)
ema=ta.ema(close,emaInput)
longEntry=ema<lrMA
longExit=lrMA<ema
shortEntry=lrMA<ema
shortExit=ema<lrMA
maxProfitLong=strategy.opentrades.entry_price(0)*(1+maxProfitInput)
maxProfitShort=strategy.opentrades.entry_price(0)*(1-maxProfitInput)
stopLossPriceShort=strategy.position_avg_price*(1+stopLossPercentageInput)
stopLossPriceLong=strategy.position_avg_price*(1-stopLossPercentageInput)
if(executeLongInputandbullish)
strategy.entry(id="long_entry",direction=strategy.long,when=longEntryandwindow(),qty=10,comment="long_entry")
strategy.close(id="long_entry",when=longExit,comment="long_exit")
//strategy.close(id="long_entry",when=maxProfitLong<=close,comment="long_exit_mp")

if(executeShortInputandnotbullish)
strategy.entry(id="short_entry",direction=strategy.short,when=shortEntryandwindow(),qty=10,comment="short_entry")
strategy.close(id="short_entry",when=shortExit,comment="short_exit")
//strategy.close(id="short_entry",when=maxProfitShort<=close,comment="short_exit_mp")
if(strategy.position_size>0andexecuteStopLoss)
strategy.exit(id="long_entry",stop=stopLossPriceLong,comment="exit_long_SL")
strategy.exit(id="short_entry",stop=stopLossPriceShort,comment="exit_short_SL")

//plot(series=lrLine,color=color.green)
plot(series=lrMA,color=color.red)
plot(series=ema,color=color.blue)
Expand (69 lines)
