Script Name: Liquidity Swings Strategy bay omar achbehe
Author: ch0294123
Description: Liquidity Swings Strategy bay omar achbehe
The Liquidity Levels/Voids (VP) is a script designed to detect liquidity voids & levels by measuring traded volume at all price levels on the market between two swing points and highlighting the distribution of the liquidity voids & levels at specific price
PineScript code:

Pine Script™ strategy
Liquidity Swings Strategy bay omar achbehe
//@version=5
strategy("Liquidity  Swings  Strategy  bay  omar  achbehe",  overlay  =  true)
//------------------------------------------------------------------------------
//Settings
//-----------------------------------------------------------------------------{
length  =  input(14,  'Pivot  Lookback')
area  =  input.string('Wick  Extremity',  'Swing  Area',  options  =  ['Wick  Extremity',  'Full  Range'])
intraPrecision  =  input(false,  'Intrabar  Precision')
filterOptions  =  input.string('Count',  'Filter  Areas  By',  options  =  ['Count',  'Volume'])
filterValue  =  input.float(0,  'Filter  Value')
//-----------------------------------------------------------------------------}
//Functions
//-----------------------------------------------------------------------------{
n  =  bar_index
get_data()  =>  [high,  low,  volume]
[h,  l,  v]  =  request.security(syminfo.tickerid,  "1",  get_data())
get_counts(condition,  top,  btm)  =>
        var  count  =  0
        var  vol  =  0.
        if  condition
                count  :=  0
                vol  :=  0.
        else
                vol  +=  low[length]  <  top  and  high[length]  >  btm  ?  volume[length]  :  0
                count  +=  low[length]  <  top  and  high[length]  >  btm  ?  1  :  0
        [count,  vol]
//-----------------------------------------------------------------------------}
//Global  variables
//-----------------------------------------------------------------------------{
//Pivot  high
var  float  ph_top  =  na
var  float  ph_btm  =  na
var  bool    ph_crossed  =  na
var              ph_x1  =  0
//Pivot  low
var  float  pl_top  =  na
var  float  pl_btm  =  na
var  bool    pl_crossed  =  na
var              pl_x1  =  0
//-----------------------------------------------------------------------------}
//Strategy  logic
//-----------------------------------------------------------------------------{
ph  =  ta.pivothigh(length,  length)
//Get  ph  counts
[ph_count,  ph_vol]  =  get_counts(ph,  ph_top,  ph_btm)
//Set  ph  area  and  level
if  ph
        ph_top  :=  high[length]
        ph_btm  :=  area  ==  'Wick  Extremity'  ?  math.max(close[length],  open[length])  :  low[length]
        ph_x1  :=  n  -  length
        ph_crossed  :=  false
if  close  >  ph_top
        ph_crossed  :=  true
if  ph_crossed
        strategy.entry("Long",  strategy.long)
pl  =  ta.pivotlow(length,  length)
//Get  pl  counts
[pl_count,  pl_vol]  =  get_counts(pl,  pl_top,  pl_btm)
//Set  pl  area  and  level
if  pl
        pl_top  :=  area  ==  'Wick  Extremity'  ?  math.min(close[length],  open[length])  :  high[length]
        pl_btm  :=  low[length]
        pl_x1  :=  n  -  length
        pl_crossed  :=  false
if  close  <  pl_btm
        pl_crossed  :=  true
if  pl_crossed
        strategy.entry("Short",  strategy.short)

//-----------------------------------------------------------------------------}
Expand (94 lines)
