Script Name: London breakout GBPUSD daytrade
Author: SoftKill21
Description: Hello,

First I want to WARN THAT YOU NEED A MINIMUM OF 30X LEVERAGE FOR THIS STRATEGY IN ORDER TO WORK.
THE REASON IS THAT THE SIZE IS CALCULATED BASED ON A VERY SHORT STOP LOSS LEVEL IN PIPS

UTILIZE IT AT YOUR OWN RISK


This is a daytrading strategy, that's suited for GBPUSD 1H timechart.
It a very simple strategy that utilizes 2 moving averages : a very fast...
PineScript code:

Pine Script™ strategy
London breakout GBPUSD daytrade
//@version=4
strategy(title="2  ma  breakout",shorttitle="2  ma  breakout",  initial_capital=10000,overlay=true,  commission_type  =  strategy.commission.cash_per_contract,  commission_value  =  0.00008  )
timeinrange(res,  sess)  =>  time(res,  sess)  !=  0
//Change  false  to  false  =  You  have  to  turn  on,  won't  show  up  by  default
//****Always  use  lowercase  letters
doNYOpen  =  input(defval=false,  type  =  input.bool,  title="NY  Open  On")
doNYSession  =  input(defval=false,  type  =  input.bool,  title="NY  Session  On")
doNYClose  =  input(defval=false,  type  =  input.bool,  title="NY  Close  On")
doAussieOpen  =  input(defval=false,  type  =  input.bool,  title="Aussie  Open  On")
doAussieSession  =  input(defval=false,  type  =  input.bool,  title="Aussie  Session  On")
doAussieClose  =  input(defval=false,  type  =  input.bool,  title="Aussie  Close  On")
doAsiaOpen  =  input(defval=false,  type  =  input.bool,  title="Asia  Open  On")
doAsiaSession  =  input(defval=false,  type  =  input.bool,  title="Asia  Session  On")
doAsiaClose  =  input(defval=false,  type  =  input.bool,  title="Asia  Close  On")
doEurOpen  =  input(defval=true,  type  =  input.bool,  title="Euro  Open  On")
doEurSession  =  input(defval=true,  type  =  input.bool,  title="Euro  Session  On")
doEurClose  =  input(defval=true,  type  =  input.bool,  title="Euro  Close  On")
//You  can  copy  and  paste  these  colors.  white  -  silver  -  gray  -  maroon  -  red  -  purple  -  fuchsia  -  green  -  lime
//      olive  -  yellow  -  navy  -  blue  -  teal  -  aqua  -  orange
nySessionStart  =  color.olive
nySession  =  color.olive
nySessionEnd  =  color.olive
asiaSessionStart  =  color.blue
asiaSession  =  color.blue
asiaSessionEnd  =  color.blue
europeSessionStart  =  color.red
europeSession  =  color.red
europeSessionEnd  =  color.red
colorwhite  =  color.white
//****Note  ----  Use  Military  Times  ---  So  3:00PM  =  1500
bgcolor(doAsiaSession  and  timeinrange(timeframe.period,  "1800-0400")  ?  asiaSession  :  na,  transp=75)
//bgcolor(timeinrange(timeframe.period,  "0000-0300")  ?  color.white    :  na,  transp=75)
bgcolor(doEurSession  and  timeinrange(timeframe.period,  "0300-1100")  ?  europeSession  :  na,  transp=75)
bgcolor(doNYSession  and  timeinrange(timeframe.period,  "0800-1600")  ?  nySession  :  na,  transp=75)
active  =  input(true,  title="Show  On  Chart")
pricehigh  =  security(syminfo.tickerid,  '60',  high[0])
pricelow  =  security(syminfo.tickerid,  '60',  low[0])
//Daily  Plots
offs_daily  =  0
hiHighs  =  0
loLows  =  0
//plot(timeinrange(timeframe.period,  "0000-0300")  and  pricehigh  ?  pricehigh    :  na,  title="Previous  Daily  High",  style=plot.style_line,  linewidth=2,  color=color.gray)
//plot(timeinrange(timeframe.period,  "0000-0300")  and  pricelow  ?  pricelow  :  na,  title="Previous  Daily  Low",  style=plot.style_linebr,  linewidth=2,  color=color.gray)
if(timeinrange(timeframe.period,  "0000-0300"))
        hiHighs  =  highest(high,3)
loLows=lowest(low,3)

//FromDateInputs
fromDay=input(defval=1,title="FromDay",minval=1,maxval=31)
fromMonth=input(defval=1,title="FromMonth",minval=1,maxval=12)
fromYear=input(defval=2020,title="FromYear",minval=1970)

//ToDateInputs
toDay=input(defval=31,title="ToDay",minval=1,maxval=31)
toMonth=input(defval=12,title="ToMonth",minval=1,maxval=12)
toYear=input(defval=2020,title="ToYear",minval=1970)

//Calculatestart/enddateandtimecondition
startDate=timestamp(fromYear,fromMonth,fromDay,00,00)
finishDate=timestamp(toYear,toMonth,toDay,00,00)
time_cond=time>=startDateandtime<=finishDate
len=input(2)
src=input(close,title="Source")
out=sma(src,len)
lena=input(200,minval=1,title="Lengthslow")
srca=input(close,title="Source")
outa=ema(srca,lena)
//tp=input(100,title="tp")
sl=input(66,title="sl")
//if(smabool)
//out:=sma(src,len)
//elseif(emabool)
//out:=ema(src,len)
//elseif(hmabool)
//out:=hma(src,len)
//elseif(vmabool)
//out:=wma(src,len)
//elseif(vwmabool)
//out:=vwma(src,len)
//elseif(smmabool)
//out:=sma(src,len)

plot(out,color=color.white,title="MA")
plot(outa,color=color.white,title="MA")
longC=timeinrange(timeframe.period,"0300-0400")and(crossover(close,out)orcrossover(high,out))andclose[1]>outaandtime_cond
shortC=timeinrange(timeframe.period,"0300-0400")and(crossunder(close,out)orcrossunder(low,out))andclose[1]<outaandtime_cond
//inputlondon=input(false,title="londonsession")
//inputny=input(false,title="newyorksession")
//if(inputlondon==true)
//MONEYMANAGEMENT--------------------------------------------------------------
balance=strategy.netprofit+strategy.initial_capital//currentbalance
floating=strategy.openprofit//floatingprofit/loss
risk=input(1,type=input.float,title="Risk%ofequity")/100//risk%pertrade
temp01=balance*risk//RiskinUSD
temp02=temp01/sl//Riskinlots
temp03=temp02*100000//Converttocontracts
size=temp03-temp03%1000//Normalizeto1000s(Tradesize)
if(size<1000)
size:=1000//Setmin.lotsize
strategy.entry("long",1,size,when=longC)
//strategy.close("long",when=crossunder(close,out)ornot(timeinrange(timeframe.period,"0300-1000")))
strategy.close("long",when=not(timeinrange(timeframe.period,"0300-0945")))
strategy.exit("x_long","long",loss=sl)


strategy.entry("short",0,size,when=shortC)
//strategy.close("short",when=crossover(close,out)ornot(timeinrange(timeframe.period,"0300-1000")))
strategy.close("short",when=not(timeinrange(timeframe.period,"0300-0945")))
strategy.exit("x_short","short",loss=sl)
//strategy.exit("closelong","RSI_BB_LONG",profit=close*0.01/syminfo.mintick,loss=close*0.01/syminfo.mintick,alert_message="closelong")
//strategy.exit("closeshort","RSI_BB_SHORT",profit=close*0.01/syminfo.mintick,loss=close*0.01/syminfo.mintick,alert_message="closeshort")
Expand (144 lines)
