Script Name: MACD 50x Leveraged Short Strategy with Real Equity
Author: Noldo
Description: Hello there ,
Short version of the Macd Long strategy.
MACD Long strategy:



 Adding margin:  Forbidden or not specified. (Add Margin : No)


 Position size: (for each trade) 1%


 Stop-Loss: (2% Above Entry Level)


 Long: macd crossunder


 Exit: macd crossover



Or ofc touching the stop-Loss value as predicted.
These strategies are just examples.
The...
PineScript code:

Pine Script™ strategy
MACD 50x Leveraged Short Strategy with Real Equity
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  Noldo
//@version=4
strategy(title="MACD  SHORT  STRATEGY  REAL  EQUITY  WITH  50X  LEVERAGE",shorttitle  =  "MACD  SHORT  50X  REAL  EQUITY",  overlay=true,
                  initial_capital=100,
                  linktoseries  =  false,
                  default_qty_type=strategy.cash,
                  default_qty_value=1,
                  commission_type=strategy.commission.percent,
                  commission_value=0.0,
                  calc_on_order_fills  =  false,
                  calc_on_every_tick    =  true,
                  max_bars_back  =  5000,
                  pyramiding  =  0,
                  precision  =  3)
//  Variables
src  =  close
fromyear  =  input(2016,  defval  =  2009,  minval  =  2000,  maxval  =  2100,  title  =  "From  Year")
toyear  =  input(2100,  defval  =  2100,  minval  =  1900,  maxval  =  2100,  title  =  "To  Year")
frommonth  =  input(04,  defval  =  04,  minval  =  01,  maxval  =  12,  title  =  "From  Month")
tomonth  =  input(12,  defval  =  12,  minval  =  01,  maxval  =  12,  title  =  "To  Month")
fromday  =  input(01,  defval  =  01,  minval  =  01,  maxval  =  31,  title  =  "From  day")
today  =  input(31,  defval  =  31,  minval  =  01,  maxval  =  31,  title  =  "To  day")
term  =  (time  >  timestamp(fromyear,  frommonth,  fromday,  00,  00)  and  time  <  timestamp(toyear,  tomonth,  today,  23,59))
//STRATEGYCOMPONENTS
//SLvalues
//STOPVALUE==>
//The50xleverageexplodesatjust2%abovethecurrententrypriceandthecurrentpositionsizemelts.
//2%belowtheentrypriceisdeterminedastheliquidationpointsothatthetransactionisguaranteed.
stop_value=valuewhen(strategy.position_size!=0andstrategy.position_size[1]==0,strategy.position_avg_price*1.02,0)
//
//LEVERAGE==>50X
leverage=50
//POSITIONSIZE==>%1(0.01)
possize=1
//MACD
fastLength=input(12)
slowlength=input(26)
MACDLength=input(9)
MACD=ema(close,fastLength)-ema(close,slowlength)
aMACD=ema(MACD,MACDLength)
delta=MACD-aMACD
//STRATEGY
if(crossunder(delta,0)andterm)
strategy.entry("MacdSE",strategy.short,qty=possize)
if(crossover(delta,0)andterm)
strategy.close("MacdSE",true,comment="CLOSE")
if(high>=stop_valueanddelta<0andterm)
strategy.close("MacdSE",true)
iftime>timestamp(toyear,tomonth,today,23,59)
strategy.close_all()
//REALLEVERAGESIMULATION---
_longmovement=strategy.position_size!=0andstrategy.position_size[1]==0
_exitmovement=strategy.position_size[1]!=0andstrategy.position_size==0
//MODE:Indicatingasituationforwinnersandlosers,justlikeinthemartingalesystem,toknowifthestrategyislosingorgaining.
floatmode=na
mode:=change(strategy.wintrades)>0?1:change(strategy.losstrades)>0?-1:nz(mode[1],1)
floatcapital=0.00
chg=change(strategy.position_size)
_b=valuewhen(_longmovement,strategy.position_avg_price,0)
_s=valuewhen(_exitmovement,open,0)
pips=((_s-_b)/_b)*100
//Ifweareinprofit,howmuchwillthisaffectallofourcapitalwithleverage?
//Ifwearealreadyataloss,allofourpositionsizewillbegone.
//Nowlet'sputthisintoexpression:

capital:=_longmovement?nz(capital[1],0)+chg:_exitmovementandmode==1?(capital[1]+chg)+((-chg*leverage*pips)/100):
_exitmovementandmode!=1?capital[1]:capital[1]
//NETCAPITAL
capita=100+capital
floatnetcapital=na
netcapital:=netcapital[1]<=0?0:capita
//Now,ifweareready,it'stimetoseethefacts:
//Ifwehadmadeastrategyusing1%positionsizeand50xleverage,thatis,ourentrypointwouldbelessthan2%liquidationpoint,thechangeinourcapitalwouldbeintheformofablue-coloredarea.
//Theresultarestillnotgood.
//Thefirstmomentweswitchto-isthemomentwerunoutofcashandthegameisover.
//NOTE:Itisrecommendedtouseaschartbottomindicator.
plot(netcapital,color=color.teal,linewidth=2)
Expand (108 lines)
