Script Name: MACD Crossover trend strategy, Long and Short
Author: conflixx95493
Description: Hey everybody,

This is my first strategy and script I wrote mostly myself. There's tons of content out there to learn how to code in Pinescript and it's exactly what I wanted and needed in this time of my life.

In any case, I made a rather simple MACD crossover strategy that only takes trades in the direction of both EMA and SMA (there are inputs to change the...
PineScript code:

Pine Script™ strategy
MACD Crossover trend strategy, Long and Short
//@version=4
//  Welcome  to  yet  another  script!  This  time  I  went  back  and  see  what  worked  and  what  didn't  work.  I  went  back  to  my  previous  scripts  and  I  ended  up  finetuning  a  lot.
//  This  script  is  basically  an  MACD  +  Donchian  Channel  mix.  Where  we  use  MACD  as  our  entry  signals  and  Donchian's  upper  and  lower  channels  are  our  exit  signals.
//  It  really  is  a  mixed  bag  of  MACD  and  Donchian  Channel  because  I  copy  and  pasted  a  bit  of  code  from  both  of  them  and  just  fine  tuned  them  till  they  worked  like  I  intended.
//  Halfway  writing  this  script  I  decided  I  want  to  have  two  options  in  this  strategy.  I  wanted  an  MACD  inverse  crossover  to  be  our  exit  signal  as  well  as  the  pullback  of  the  donchian  channels  which  is  basically  either  the  high  or  low  of  the  previous  20  candles.
//  The  entry  and  exit  signals  are  explained  below  at  the  strategy  code
strategy("MACD  inverse  cross  /  pullback",  overlay  =  false,  pyramiding  =  0,  default_qty_type  =  strategy.cash,  default_qty_value  =  150,  initial_capital  =  1000,  currency  =  currency.USD,  commission_type  =  "percent",  commission_value  =  0.036)
//  Getting  inputs
fast_length          =  input(title  =  "Fast  Length",                            type  =  input.integer,      defval  =  12,                        group  =  "MACD  Inputs")
slow_length          =  input(title  =  "Slow  Length",                            type  =  input.integer,      defval  =  26,                        group  =  "MACD  Inputs")
src                          =  input(title  =  "Source",                                      type  =  input.source,        defval  =  close,                  group  =  "MACD  Inputs")
signal_length      =  input(title  =  "Signal  Smoothing",                  type  =  input.integer,      defval  =  9,                          group  =  "MACD  Inputs",            maxval  =  50,        minval  =  1)
sma_source            =  input(title  =  "Simple  MA  (Oscillator)",      type  =  input.bool,            defval  =  false,                  group  =  "MACD  Inputs")
sma_signal            =  input(title  =  "Simple  MA  (Signal  Line)",    type  =  input.bool,            defval  =  false,                  group  =  "MACD  Inputs")
emaInput                =  input(title  =  "EMA  Input",                                type  =  input.integer,      defval  =  200,                      group  =  "Indicators",              maxval  =  400,      minval  =  10,      step  =  1)
//  Basically  the  Donchian  Channels,  it's  where  I  got  the  idea  from,  we  use  this  to  determine  the  pullback  of  the  trend.  This  isn't  waterproof  but  at  least  it's  automated  and  customisable  through  the  inputs.
//  For  anyone  who  doesn't  know,  Donchian  Channels  looks  at  the  previous  highs  and  lows  of  the  period  that  we  set,  which  by  default  is  20.  So  in  the  past  20  candles,  the  upper  channel  shows  the  highest  price  of  the  previous  20  candles  and  vice  versa.
length                    =  input(title  =  "Pullback  Period",                    type  =  input.integer,      defval  =  20,                        group  =  "Pullback  Period",    minval=1)
riskreward            =  input(title  =  "Risk/Reward  Ratio",                type  =  input.float,          defval  =  1.50,                    group  =  "Risk/Reward",            maxval  =  100,      minval  =  0.01,  step  =  0.01)
strategyinput      =  input(title  =  "Strategy",                                  type  =  input.string,        defval  =  "Pullback",        group  =  "Strategy",                  options  =  ["Pullback",  "MACD  inverse  cross"])
lower                      =  lowest(length)
upper                      =  highest(length)
//  Backtest  input  range
fromMonth              =  input(defval  =  1,        title  =  "From  Month",                type  =  input.integer,      minval  =  1,          maxval  =  12,        group  =  "Backtest  Date  Range")
fromDay                  =  input(defval  =  1,        title  =  "From  Day",                    type  =  input.integer,      minval  =  1,          maxval  =  31,        group  =  "Backtest  Date  Range")
fromYear                =  input(defval  =  2000,  title  =  "From  Year",                  type  =  input.integer,      minval  =  1970,                                    group  =  "Backtest  Date  Range")
thruMonth              =  input(defval  =  1,        title  =  "Thru  Month",                type  =  input.integer,      minval  =  1,          maxval  =  12,        group  =  "Backtest  Date  Range")
thruDay                  =  input(defval  =  1,        title  =  "Thru  Day",                    type  =  input.integer,      minval  =  1,          maxval  =  31,        group  =  "Backtest  Date  Range")
thruYear                =  input(defval  =  2099,  title  =  "Thru  Year",                  type  =  input.integer,      minval  =  1970,                                    group  =  "Backtest  Date  Range")
//  Date  variable,  we  use  this  in  our  strategy.entry  condition  to  determine  whether  it  should  place  a  trade  or  not.  This  way  only  the  data  we  want  to  backtest  is  being  backtested.
inDataRange          =  (time  >=  timestamp(syminfo.timezone,  fromYear,  fromMonth,  fromDay,  0,  0))  and  (time  <  timestamp(syminfo.timezone,  thruYear,  thruMonth,  thruDay,  0,  0))
//  Calculations,fromthebuiltinMACDindicator,havenothingtosayaboutthis.
fast_ma=sma_source?sma(src,fast_length):ema(src,fast_length)
slow_ma=sma_source?sma(src,slow_length):ema(src,slow_length)
macd=fast_ma-slow_ma
signal=sma_signal?sma(macd,signal_length):ema(macd,signal_length)
hist=macd-signal
//Long/shortentryandexitconditionsalsoanEMAcheckbasedintheinputdata
longEntryCondition=crossover(macd,signal)andmacd>0andsignal>0
shortEntryCondition=crossunder(macd,signal)andmacd<0andsignal<0
longExitCondition=crossunder(macd,signal)
shortExitCondition=crossover(macd,signal)
emaCheck=ema(close,emaInput)
varpullbackLong=0.0
varpullbackShort=0.0
varlongprofit=0.0
varshortprofit=0.0
//Strategy
//Foranyonewhocan'treadthecode,strategygoesasfollows:
//LongentrysignaliswhentheMACDlinecrossesthesignallineupwards,belowthezeropointofthehistogram,whenpriceisabovetheEMAandifthere'sapositionopenwedon'topenanewone.
//ShortentrysignaliswhentheMACDlinecrossesthesignallinedownwards,abovethezeropointofthehistogram,whenthepriceisbelowtheEMAandifthere'sapositionopenwedon'topenanewone.
//Exitsignalsareeitherthe20periodlow,forlongpositions,or20periodhigh,forshortpositions.
//ProfitiscalculatedwiththeRiskRewardratioinputwhichbydefaultis1.5.
//Thedifferencebetweentheprice,whenweopenaposition,andthepullback.Multipliedbytheriskrewardratioandeitheradded,ifwe'relong,orsubtracted,ifwe'reshort,withthecurrentprice.
//Thiswayweonlytaketradesinthedirectionofthetrend,weonlyusestronglongorshortentrysignalsfromtheMACDindicatorandweusethedonchianchannelsupperandlowerchanneltocalculatethestoplossandtakeprofit.
//LikeIsaid,halfwaythroughwritingthescriptIwantedtochangealittlebit,becauseIwanttogiveusoptions,whetherwewanttousethepullbackasourstoplossorwhetherweusetheMACDcrossoveragainasourexitsignalonlywhenitinverses.
//Tobeclear,whenwesetthestrategy.inputtoMACDinversecrossthatmeanswhenweenteraposition,shortorlong,weexitthatpositionthemomenttheMACDlineinverselycrossesthesignalline.
iflongEntryConditionandstrategy.position_size==0andinDataRangeandclose>emaCheck
strategy.entry("LongEntry",strategy.long,comment="LongBuy")
pullbackLong:=lower*0.99
longprofit:=((((1-lower/close)*riskreward)+1)*close)
ifstrategyinput=="Pullback"
strategy.exit("LongExit","LongEntry",limit=longprofit,stop=pullbackLong,comment="PullbackLongExit")
ifstrategyinput=="MACDinversecross"
strategy.close("LongEntry",when=longExitCondition,comment="MACDInversecrossexitLong")
ifshortEntryConditionandstrategy.position_size==0andinDataRangeandclose<emaCheck
strategy.entry("ShortEntry",strategy.short,comment="ShortBuy")
pullbackShort:=upper*1.01
shortprofit:=(close-((((1-close/upper)*riskreward)*close)))
ifstrategyinput=="Pullback"
strategy.exit("ShortExit","ShortEntry",limit=shortprofit,stop=pullbackShort,comment="PullbackShortExit")
ifstrategyinput=="MACDinversecross"
strategy.close("ShortEntry",when=shortExitCondition,comment="MACDInversecrossexitShort")
//Tomakesurethebacktestingdoesn'tleaveapositionopenbeyond,orbefore,ourapplieddates
if(notinDataRange)
strategy.close_all()
//PlottingtheMACDonthechart,thisisthebuilt-inMACDindicator.
col_grow_above=#26A69A
col_grow_below=#FFCDD2
col_fall_above=#B2DFDB
col_fall_below=#EF5350
col_macd=#0094ff
col_signal=#ff6a00
plot(hist,title="Histogram",style=plot.style_columns,color=(hist>=0?(hist[1]<hist?col_grow_above:col_fall_above):(hist[1]<hist?col_grow_below:col_fall_below)),transp=0)
plot(macd,title="MACD",color=col_macd,transp=0)
plot(signal,title="Signal",color=col_signal,transp=0)
//Thesetwoplotsaretheretocheckwhetherthepullbackcalculationisworkingasintended.Ifyouwanttousetheseyouhavetosetoverlaytotrueintheveryfirststringofcode.
//Also,maketheMACDplots(thethreeabovethisone)commentswith//beforeit.Otherwiseyourchartwillbeunreadable.
//AddingtheDonchianChannelshelpsyouvisualisewhetherthepullbackvariablesareworkingproperly.
//plot(pullbackShort)
//plot(pullbackLong)
Expand (103 lines)
