Script Name: Master Supertrend Strategy [Trendoscope]
Author: Trendoscope
Description: Here is the strategy version of the indicator -  Master Supertrend 

Options and variations are same throughout.

 🎲 Variations 
Following variations are provided in the form of settings.

 🎯 Range Type 
Instead of ATR, different types of ranges can be used for stop calculation. Here is the complete list used in the script.

 Plus/Minus Range*  - Calculates plus...
PineScript code:

Pine Script™ strategy
Master Supertrend Strategy [Trendoscope]
Copy code
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
//ThisworkislicensedunderCreativeCommonsAttribution-NonCommercial-ShareAlike4.0InternationalLicense(CCBY-NC-SA4.0)https://creativecommons.org/licenses/by-nc-sa/4.0/
//©TrendoscopePtyLtd
//░▒
//▒▒▒▒▒
//▒▒▒▒▒▒▒
//▒▒▒▒▒▒▒░▒▒▒
//▒▒▒▒▒▒▒▒▒
//▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//▒▒░▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
//▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░▒▒▒▒▒▒▒▒
//▓▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
//▒▒▒▒▒▒▒▒▒▒▒▒
//▒▒▒▒▒▒▒▒▒
//▒▒▒▒▒▒▒▒▒▒
//░▒▒▒▒▒▒▒▒▓████████╗██████╗███████╗███╗██╗██████╗██████╗███████╗██████╗██████╗██████╗███████╗
//▓▒▒▒▒▒▒▒▒╚══██╔══╝██╔══██╗██╔════╝████╗██║██╔══██╗██╔═══██╗██╔════╝██╔════╝██╔═══██╗██╔══██╗██╔════╝
//▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒██║██████╔╝█████╗██╔██╗██║██║██║██║██║███████╗██║██║██║██████╔╝█████╗
//▒▒▒▒▒▒▒▒▒▒██║██╔══██╗██╔══╝██║╚██╗██║██║██║██║██║╚════██║██║██║██║██╔═══╝██╔══╝
//▒▒▒▒▒▒▒▒▒▒██║██║██║███████╗██║╚████║██████╔╝╚██████╔╝███████║╚██████╗╚██████╔╝██║███████╗
//▒▒▒
//
//@version=5
//indicator("MasterSupertrend[Trendoscope]","MST[Trendoscope]",overlay=true)
strategy("MasterSupertrendStrategy[Trendoscope]","MSTS[Trendoscope]",overlay=true,initial_capital=1000,
default_qty_type=strategy.percent_of_equity,default_qty_value=10,commission_type=strategy.commission.percent,
pyramiding=1,commission_value=0.05,close_entries_rule="ANY",margin_long=100,margin_short=100,
max_lines_count=500,max_labels_count=500,max_boxes_count=500,use_bar_magnifier=false)
importHeWhoMustNotBeNamed/ta/1aseta loading...
importHeWhoMustNotBeNamed/arrayutils/22aspa loading...
supertrendType=input.string('Plus/MinusRange','RangeType',['Plus/MinusRange','LadderTR','TrueRange','StandardDeviation'],'Typeofrangeusedforsupertrendcalculation')
rangeType=input.string('high','AppliedCalculation',['sma','ema','hma','rma','wma','high','median'],'Appliedcalculationmethodontherangebeforeusingthemforcalculationofsupertrendstops')
length=input.int(60,'Length',10,1000,10,tooltip='Supertrendrangecalculationlength')
multiplier=input.int(2,'Multiplier',2,100,1,tooltip='Supertrendrangemultiplier')
useClosePrices=input.bool(true,'UseClosePrice',tooltip='Useclosepriceasreferenceinstadofhigh/lowforcalculationofstop')
waitForClose=input.bool(true,'WaitforClose',tooltip='Waitforclosebeforechangingthedirectionandchangedirectiononlyifclosepricehasbreachedthestopline')
useDiminishingRange=input.bool(true,'DiminishingStopDistance',tooltip='Whenselectedstopdistancefromreferencepricecanonlydecreaseandnotincrease')
floatladderPositiveAtr=na
floatladderNegativeAtr=na
if(supertrendType=='LadderTR')
varplusLadderAtr=array.new<float>()
varminusLadderAtr=array.new<float>()
if(open<close)
pa.push(plusLadderAtr,ta.tr,length)
else
pa.push(minusLadderAtr,ta.tr,length)
ladderPositiveAtr:=pa.ma(plusLadderAtr,rangeType,length)
ladderNegativeAtr:=pa.ma(minusLadderAtr,rangeType,length)
plusRange=supertrendType=='Plus/MinusRange'?math.max(high-open,high-close[1]):supertrendType=='LadderTR'?ladderPositiveAtr:supertrendType=='TrueRange'?ta.tr:ta.stdev(close,length,true)
minusRange=supertrendType=='Plus/MinusRange'?math.max(open-low,close[1]-low):supertrendType=='LadderTR'?ladderNegativeAtr:supertrendType=='TrueRange'?ta.tr:ta.stdev(close,length,true)
appliedPlusRange=supertrendType=='LadderTR'?plusRange:eta.ma(plusRange,rangeType,length)
appliedMinusRange=supertrendType=='LadderTR'?minusRange:eta.ma(minusRange,rangeType,length)
vardirection=1
varderivedPlusRange=appliedPlusRange*multiplier
varderivedMinusRange=appliedMinusRange*multiplier
currentDerivedPlusRange=appliedPlusRange*multiplier
derivedPlusRange:=direction<0anduseDiminishingRange?math.min(nz(derivedPlusRange,currentDerivedPlusRange),currentDerivedPlusRange):currentDerivedPlusRange
currentDerivedMinusRange=appliedMinusRange*multiplier
derivedMinusRange:=direction>0anduseDiminishingRange?math.min(nz(derivedMinusRange,currentDerivedMinusRange),currentDerivedMinusRange):currentDerivedMinusRange
buyStopCurrent=(useClosePrices?close:low)-derivedMinusRange
varbuyStop=buyStopCurrent
sellStopCurrent=(useClosePrices?close:high)+derivedPlusRange
varsellStop=sellStopCurrent
buyStop:=direction>0?math.max(nz(buyStop,buyStopCurrent),buyStopCurrent):buyStopCurrent
sellStop:=direction<0?math.min(nz(sellStop,sellStopCurrent),sellStopCurrent):sellStopCurrent
direction:=direction>0and(waitForClose?close:low)<buyStop?-1:
direction<0and(waitForClose?close:high)>sellStop?1:direction
supertrend=direction[1]>0?buyStop:sellStop
plot(supertrend,'Supertrend',direction[1]>0?color.red:color.green)
plot(direction,"direction",display=display.data_window)
plot(strategy.equity,"Equity",display=display.data_window)
plot(strategy.openprofit,"OpenProfit",display=display.data_window)
plot(strategy.opentrades,"OpenTrades",display=display.data_window)
if(direction>0)
strategy.entry("Long",strategy.long)
if(direction<0)
strategy.entry("Short",strategy.short)
Expand (93 lines)