Script Name: Maximized Moving Average Crossing (by Coinrule)
Author: Coinrule
Description: Using the crossings of two Moving Averages to trade in a trading strategy is a Trend-Following approach. As the name would suggest, to be successful, it requires the asset to be on-trend.

The general limit of a common strategy based on Moving Averages is that they underperform when the market is less volatile or trading sideways. When volatility compresses, the...
PineScript code:

Pine Script™ strategy
Maximized Moving Average Crossing (by Coinrule)
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  relevantLeader16058
//@version=4
strategy(shorttitle='Maximized  Moving  Average  Crossing  ',title='Maximized  Moving  Average  Crossing  (by  Coinrule)',  overlay=true,  initial_capital=1000,    default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  30,  commission_type=strategy.commission.percent,  commission_value=0.1)
//Backtest  dates
fromMonth  =  input(defval  =  1,      title="FromMonth",type=input.integer,minval=1,maxval=12)
fromDay=input(defval=1,title="FromDay",type=input.integer,minval=1,maxval=31)
fromYear=input(defval=2020,title="FromYear",type=input.integer,minval=1970)
thruMonth=input(defval=1,title="ThruMonth",type=input.integer,minval=1,maxval=12)
thruDay=input(defval=1,title="ThruDay",type=input.integer,minval=1,maxval=31)
thruYear=input(defval=2112,title="ThruYear",type=input.integer,minval=1970)
showDate=input(defval=true,title="ShowDateRange",type=input.bool)
start=timestamp(fromYear,fromMonth,fromDay,00,00)//backteststartwindow
finish=timestamp(thruYear,thruMonth,thruDay,23,59)//backtestfinishwindow
window()=>time>=startandtime<=finish?true:false//createfunction"withinwindowoftime"
//MAinputsandcalculations
inlong=input(50,title='MAlongperiod')
inshort=input(9,title='MAshortperiod')
MAlong=sma(close,inlong)
MAshort=sma(close,inshort)
//RSIinputsandcalculations
lengthRSI=(14)
RSI=rsi(close,lengthRSI)
RSI_Signal=input(55,title='RSITrigger',minval=1)
//EntryandExit
bullish=crossover(MAshort,MAlong)
bearish=crossunder(MAshort,MAlong)
strategy.entry(id="long",long=true,when=bullishandRSI>RSI_Signalandwindow())
strategy.close(id="long",when=bearishandwindow())

plot(MAshort,color=color.purple,linewidth=2)
plot(MAlong,color=color.red,linewidth=2)
Expand (43 lines)
