Script Name: MESA + cRSI + MA + ALMA + MACD Strategy
Author: UnknownUnicorn36161431
Description: The WHAT
=============>
Basically a combination of multiple indicators into a strategy.
As the title says - it's a combo of MESA Pivot Points, Cyclic RSI, MESA Adjusted Moving Average, ALMA and MACD.
Feel free to play around with them and turn then on/off as desired to get the best results for your coin.

Enjoy :)
PineScript code:

Pine Script™ strategy
MESA + cRSI + MA + ALMA + MACD Strategy
//  @version=5
strategy("MESA  +  cRSI  Strategy",  shorttitle="MESA  +  cRSI  Strategy",  overlay=true,  process_orders_on_close  =  true,  calc_on_order_fills  =  true,  pyramiding  =  0,  default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  75,  commission_type  =  strategy.commission.percent,  commission_value  =  0.04,  initial_capital  =  100)
GROUP_GLOBAL_OPTIONS  =  "Global  Options"
GROUP_TIME_LIMITED_BACKTESTS  =  "Time-Limit  BackTests  (0  =  disable)"
GROUP_CRSI_OPTIONS  =  "cRSI  Options"
GROUP_HTF_MESA_MA  =  "HTF  Adaptive  MESA  MA  Options"
GROUP_ALMA  =  "ALMA  Trend  Direction  Options"
GROUP_MACD  =  "MACD  Options"
GROUP_MESA  =  "MESA  Pivots  Options"
SLPerc  =  input.float(  2.5,  title="Stop  Loss  (%)",  minval=0.0,  step=0.1,  group  =  GROUP_GLOBAL_OPTIONS)
i_use_time_limited_backtesting  =  input.bool(  false,  "Use  Time-Limited  Backtesting",  group  =  GROUP_TIME_LIMITED_BACKTESTS  )
startDay  =  input.int(0,  "Start  Day",  minval  =  0,  maxval  =  31,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
startMonth  =  input.int(0,  "Start  Month",  minval  =  0,  maxval  =  12,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
startYear  =  input.int(0,  "Start  Year",  minval  =  0,  maxval  =  2100,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
endDay  =  input.int(0,  "End  Day",  minval  =  0,  maxval  =  31,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
endMonth  =  input.int(0,  "End  Month",  minval  =  0,  maxval  =  12,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
endYear  =  input.int(0,  "End  Year",  minval  =  0,  maxval  =  2100,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
i_use_crsi  =  input.bool(  true,  "Trade  by  cRSI",  group  =  GROUP_CRSI_OPTIONS  )
i_show_crsi  =  input.bool(  false,  "Show  cRSI  Pivots",  group  =  GROUP_CRSI_OPTIONS  )
i_i_len      =  input(  30,  "cRSI  EMA  period",  group  =  GROUP_CRSI_OPTIONS  )
i_src          =  input.source(  close,  'cRSI  Source',    group  =  GROUP_CRSI_OPTIONS  )
i_trade_trend_direction  =  input(  true,  "cRSI  trade  in  trend  direction  only",  group  =  GROUP_CRSI_OPTIONS  )
i_trade_trend_direction_change_percent_cancel  =  input.float(  3,  "cRSI  price  change  (%)  to  cancel  trade  in  trend  direction",  group  =  GROUP_CRSI_OPTIONS  )
i_use_htf_mesa  =  input.bool(  false,  "Trade  by  HTF  Adaptive  MESA  MA",  group  =  GROUP_HTF_MESA_MA  )
i_show_htf_mesa  =  input.bool(  false,  "Show  HFT  Adaptive  MESA  MA",  group  =  GROUP_HTF_MESA_MA  )
_tf  =  input.timeframe(  'D',  "HTF  Adaptive  MESA  MA  Resolution",  group  =  GROUP_HTF_MESA_MA  )
i_use_alma  =  input.bool(  false,  "Trade  by  ALMA  Trend  Direction",  group  =  GROUP_ALMA  )
i_show_alma  =  input.bool(  false,  "Show  ALMA",  group  =  GROUP_ALMA  )
alma_len  =  input.int(  48,  "Arnaud  Legoux  MA  Length",  minval  =  1,  group  =  GROUP_ALMA  )
alma_offset  =  input.float(  0.15,  "ALMA  Offset",  minval  =  0.0001,  group  =  GROUP_ALMA  )
alma_sigma  =  input.int(  6,  title="ALMA  Sigma  Value",  minval  =  1,  group  =  GROUP_ALMA  )
i_use_macd  =  input.bool(  false,  "Trade  by  MACD",  group  =  GROUP_MACD  )
macd_fast  =  input.int(  15,  "MACD  Fast  Length",  minval  =  1,  group  =  GROUP_MACD  )
macd_slow  =  input.int(  30,  "MACD  Slow  Length",  minval  =  1,  group  =  GROUP_MACD  )
macd_smooth  =  input.int(  9,  "MACD  Signal  Smoothing",  minval  =  0,  group  =  GROUP_MACD  )
i_use_mesa  =  input.bool(  true,  "Trade  by  MESA  Pivots",  group  =  GROUP_MESA  )
i_show_mesa  =  input.bool(  false,  "Show  MESA  Pivots",  group  =  GROUP_MESA  )
offsetNum  =  input(  0,  "MESA  offset",  group  =  GROUP_MESA)
pivot_zone_upper  =  input.float(  0.4,  "MESA  pivot  zone  upper",  step=0.1,  group  =  GROUP_MESA  )
pivot_zone_lower  =  input.float(  -0.4,  "MESA  pivot  zone  lower",  step=0.1,  group  =  GROUP_MESA  )
min_mesa_pivots_gap_minutes  =  input(  20,  "MESA  minimum  pivots  gap  (minutes)",  group  =  GROUP_MESA)
//  i_use_ashi  =  input.bool(  true,  "Trade  by  Heiking  ASHI",  group  =  "Heikin  Ashi  Options"  )
//  ashi_res  =  input.timeframe(  "60",  "Heikin  Ashi  Candle  Time  Frame",  group  =  "Heikin  Ashi  Options"  )
//  ashi_hshift  =  input(  1,  "Heikin  Ashi  Candle  Time  Frame  Shift",  group  =  "Heikin  Ashi  Options"  )
//  ashi_res1  =  input.timeframe(  "180",  "Heikin  Ashi  EMA  Time  Frame",  group  =  "Heikin  Ashi  Options"  )
//  ashi_mhshift  =  input(  0,  "Heikin  Ashi  EMA  Time  Frame  Shift",  group  =  "Heikin  Ashi  Options"  )
//  ashi_fama  =  input(  1,  "Heikin  Ashi  EMA  Period",  group  =  "Heikin  Ashi  Options"  )
//  ashi_test  =  input(  1,"Heikin  Ashi  EMA  Shift",  group  =  "Heikin  Ashi  Options"  )
//  ashi_sloma  =  input(  30,"Slow  EMA  Period",  group  =  "Heikin  Ashi  Options"  )
//  ashi_slomas  =  input(  1,"Slow  EMA  Shift"  )
//  ashi_logtransform  =  input(  false,  "Log  Transform"  )
inDateRange  =  true
//  Look  if  the  close  time  of  the  current  bar  falls  inside  the  date  range
if  i_use_time_limited_backtesting  and  startDay  !=  0  and  startMonth  !=  0  and  startYear  !=  0  and  endDay  !=  0  and  endMonth  !=  0  and  endYear  !=  0
        inDateRange  :=  (  time  >=  timestamp(  syminfo.timezone,  startYear,  startMonth,  startDay,  0,  0  )  )  and  (  time  <  timestamp(  syminfo.timezone,  endYear,  endMonth,  endDay,  0,  0  )  )
//------------------------------------------------------------------------------
//  persisting  variables
//------------------------------------------------------------------------------
var  cRSI_high_extreme_found  =  0.0
var  cRSI_high_extreme_valid  =  true
var  cRSI_low_extreme_found  =  0.0
var  cRSI_low_extreme_valid  =  true
var  last_cRSI_extreme  =  ""
var  last_pivot_ts  =time
varlast_trade_ts=time
varmesa_ma_trend_direction=""
varalma_trend_direction=""
varmacd_trend_direction=""
varmin_trade_gap_minutes=2
//------------------------------------------------------------------------------
//MESAcalculationsfromtheMESAindicator
//------------------------------------------------------------------------------
//Basic
//------------------------------------------------------------------------------
DomCycle=15
RealPart=0.0
ImagPart=0.0
forJ=0toDomCycle-1
Weight=(close[J]+close[J]+high[J]+low[J])*10000
ifDomCycle!=0
RealPart:=RealPart+math.cos(90*J/DomCycle)*Weight*2
ImagPart:=((ImagPart+math.sin(90*J/DomCycle)*Weight)+(ImagPart+math.sin(180*J/DomCycle)*Weight))/2
Phase=((math.atan(ImagPart/RealPart))-0.685)*100
//------------------------------------------------------------------------------
//Pivot
//------------------------------------------------------------------------------
ph_mesa=ta.pivothigh(Phase,1,1)
pl_mesa=ta.pivotlow(Phase,1,1)
out_zone=Phase[2]<pivot_zone_lowerorPhase[2]>pivot_zone_upper
plotshape(i_show_mesaandph_mesaandout_zone?ph_mesa:na,title="PivotHigh",color=#f23737,style=shape.circle,location=location.abovebar,offset=-1,size=size.tiny)
plotshape(i_show_mesaandpl_mesaandout_zone?pl_mesa:na,title="PivotLow",color=#169788,style=shape.circle,location=location.belowbar,offset=-1,size=size.tiny)
//------------------------------------------------------------------------------
//MESAadaptivemovingaverageindicatorcode
//------------------------------------------------------------------------------
tf1=_tf=='0'?timeframe.period:_tf
fast=0.25
slow=0.05
//Returnsscalardifferencebetweencurrenttimeframeandrequested
ResolutionToMin(tf)=>
mins=tf=="1M"?43830:tf=="1W"?10080:tf=="1D"?1440:tf=="240"?240:tf=="180"?180:tf=="120"?120:tf=="60"?60:tf=="45"?45:tf=="30"?30:tf=="15"?15:tf=="5"?5:tf=="3"?3:tf=="1"?1:-1
mins
chart_res=ResolutionToMin(timeframe.period)
if(timeframe.isdwm)
chart_res:=ResolutionToMin(str.tostring(timeframe.multiplier)+timeframe.period)
req_res=ResolutionToMin(_tf)
scale=req_res==-1orchart_res==-1orchart_res>req_res?1:chart_res/req_res


//MESAMovingAverage`
//Args:src-theseriestoperformMAMAcalculationson
//fast-limittothefastmovingaveragecalc(default0.5)
//slow-limittotheslowmovingaveragecalc(default0.05)
//hide-forusagewithmultipleMESAplots.settoTruetoreturn[na,na]
//##############################################################################
getMESA(src_in,fast,slow,show)=>
Price=src_in
FastLimit=fast
SlowLimit=slow
MAMA=src_in
FAMA=src_in
PI=3.14159
Smooth=0.0
Detrender=0.0
I1=0.0
Q1=0.0
jI=0.0
jQ=0.0
I2=0.0
Q2=0.0
Re=0.0
Im=0.0
Period=0.0
SmoothPeriod=0.0
Phase=0.0
DeltaPhase=0.0
alpha=0.0
if(na(Price))
MAMA:=MAMA[1]
FAMA:=FAMA[1]
Smooth:=Smooth[1]
Detrender:=Detrender[1]
I1:=I1[1]
Q1:=Q1[1]
I2:=I2[1]
Q2:=Q2[1]
Re:=Re[1]
Im:=Im[1]
Period:=Period[1]
SmoothPeriod:=SmoothPeriod[1]
Phase:=Phase[1]

if(bar_index>5andshowandnotna(Price))
Smooth:=(4*Price+3*Price[1]+2*Price[2]+Price[3])/10
Detrender:=(0.0962*Smooth+0.5769*Smooth[2]-0.5769*Smooth[4]-0.0962*Smooth[6])*
(0.075*Period[1]+0.54)
//GettheInphase&QuadtratureComponents
Q1:=(0.0962*Detrender+0.5769*Detrender[2]-0.5769*Detrender[4]-
0.0962*Detrender[6])*(0.075*Period[1]+0.54)
I1:=Detrender[3]
//Advancephaseangleby90deg
jI:=(0.0962*I1+0.5769*I1[2]-0.5769*I1[4]-0.0962*I1[6])*
(0.075*Period[1]+0.54)
jQ:=(0.0962*Q1+0.5769*Q1[2]-0.5769*Q1[4]-0.0962*Q1[6])*
(0.075*Period[1]+0.54)
//Phasoradditionfor3-baraveraging
I2:=I1-jQ
Q2:=Q1+jI
//SmooththeIandQcomponentsbeforeapplyingthediscriminator
I2:=0.2*I2+0.8*I2[1]
Q2:=0.2*Q2+0.8*Q2[1]
//HomodyneDiscriminator
Re:=I2*I2[1]+Q2*Q2[1]
Im:=I2*Q2[1]-Q2*I2[1]
Re:=0.2*Re+0.8*Re[1]
Im:=0.2*Im+0.8*Im[1]
ifIm!=0andRe!=0
Period:=2*PI/math.atan(Im/Re)
Period:=Period>1.5*Period[1]?1.5*Period[1]:Period
Period:=Period>50?50:Period
Period:=Period<0.67*Period[1]?0.67*Period[1]:Period
Period:=Period<6?6:Period
Period:=0.2*Period+0.8*Period[1]
SmoothPeriod:=0.33*Period+0.67*SmoothPeriod[1]
ifI1!=0
Phase:=180/PI*math.atan(Q1/I1)
DeltaPhase:=Phase[1]-Phase
ifDeltaPhase<1
DeltaPhase:=1
alpha:=FastLimit/DeltaPhase
alpha:=alpha<SlowLimit?SlowLimit:alpha
alpha:=alpha>FastLimit?FastLimit:alpha
MAMA:=alpha*Price+(1-alpha)*MAMA[1]
FAMA:=0.5*alpha*MAMA+(1-0.5*alpha)*FAMA[1]
if(notshow)
MAMA:=na
FAMA:=na
[MAMA,FAMA]
[M_1,F_1]=getMESA(close,fast*scale,slow*scale,true)
//SimplefunctiontograbthecolorofthefillgivenaMama/Famatuple
//Args:mama-theMesaadaptivemovingaverage
//fama-thefollowermovingaverage(generatedbyprior)
//##############################################################################
fillColor(mama,fama,show)=>
color_1=color.new(color.white,100)
ret=show?mama>fama?color.red:color.blue:color_1
ret
//##############################################################################
p_m_1=plot(M_1,"MAMAonHTFAdaptiveMESA",i_show_htf_mesa?color.maroon:na,2)
p_f_1=plot(F_1,"FAMAonHTFAdaptiveMESA",i_show_htf_mesa?color.navy:na,2)
fill_1=fillColor(M_1,F_1,i_show_htf_mesa)
fill(p_m_1,p_f_1,fill_1,"Fill1")
ifmesa_ma_trend_direction==""orta.cross(M_1,F_1)
ifM_1>F_1
mesa_ma_trend_direction:="up"
else
mesa_ma_trend_direction:="down"
//------------------------------------------------------------------------------
//ALMATrendDirectionindicatorcode
//------------------------------------------------------------------------------
trendALMA=ta.alma(close,alma_len,alma_offset,alma_sigma)
iflow>trendALMA
alma_trend_direction:="up"
else
alma_trend_direction:="down"

p0=plot(i_show_alma?trendALMA:na,color=color.new(color.black,100))
p1=plot(i_show_alma?close:na,color=color.new(color.black,100))
fill(p0,p1,color=low>trendALMA?color.new(#00ff00,82):color.new(#c2185b,81))

//------------------------------------------------------------------------------
//MACD
//------------------------------------------------------------------------------
ifi_use_macd
[macdLine,signalLine,hist]=ta.macd(close,macd_fast,macd_slow,macd_smooth)
ifmacdLine>signalLine
macd_trend_direction:="up"
else
macd_trend_direction:="down"
//------------------------------------------------------------------------------
//HekinAshistrategycode
//------------------------------------------------------------------------------
//ha_t=ticker.heikinashi(syminfo.tickerid)
//ha_close=request.security(ha_t,ashi_res,ashi_logtransform?math.log(close[ashi_hshift]):close[ashi_hshift])
//mha_close=request.security(ha_t,ashi_res1,ashi_logtransform?math.log(close[ashi_mhshift]):close[ashi_mhshift])
//fma=ta.ema(mha_close[ashi_test],ashi_fama)
//sma=ta.ema(ha_close[ashi_slomas],ashi_sloma)
////plot(showplots?(logtransform?math.exp(fma):fma):na,title="MA",color=#0094ff,linewidth=2,style=plot.style_line)
////plot(showplots?(logtransform?math.exp(sma):sma):na,title="SMA",color=#ff6a00,linewidth=2,style=plot.style_line)
//ashi_golong=ta.crossover(fma,sma)
//ashi_goshort=ta.crossunder(fma,sma)
//------------------------------------------------------------------------------
//cRSIindicatorcode
//------------------------------------------------------------------------------
crsi=0.0
vibration=10
torque=0.618/(vibration+1)
phasingLag=(vibration-1)/0.618
rsi=ta.rsi(i_src,i_i_len)
crsi:=torque*(2*rsi-rsi[phasingLag])+(1-torque)*nz(crsi[1])
floatosc=crsi
floatph=ta.highestbars(high,i_i_len)==0?osc:na
floatpl=ta.lowestbars(low,i_i_len)==0?osc:na
varintdir=0
dir:=phandna(pl)?1:plandna(ph)?-1:dir
varmax_array_size=10
vararr_zz=array.new_float(0)
older_zz=array.copy(arr_zz)
dirchanged=ta.change(dir)
add_to_zigzag(_id,floatvalue,intbindex)=>
array.unshift(_id,bindex)
array.unshift(_id,value)
ifarray.size(_id)>max_array_size
array.pop(_id)
array.pop(_id)
update_zigzag(_id,floatvalue,intbindex,intdir)=>
ifarray.size(_id)==0
add_to_zigzag(_id,value,bindex)
else
ifdir==1andvalue>array.get(_id,0)ordir==-1andvalue<array.get(_id,0)
array.set(_id,0,value)
array.set(_id,1,bindex)
0.
ifphorpl
ifdirchanged
add_to_zigzag(arr_zz,dir==1?ph:pl,bar_index)
else
update_zigzag(arr_zz,dir==1?ph:pl,bar_index,dir)
ifarray.size(arr_zz)>=6
//Variables
varlabellabel_zz=na
//Boolsforor
boolbool_or_1=array.get(arr_zz,0)!=array.get(older_zz,0)
boolbool_or_2=array.get(arr_zz,1)!=array.get(older_zz,1)

//Boolsforand
boolbool_n_1=array.get(arr_zz,2)==array.get(older_zz,2)
boolbool_n_2=array.get(arr_zz,3)==array.get(older_zz,3)

//Boolsformorethanandlessthan
boolbool_0_mt_4=array.get(arr_zz,0)>array.get(arr_zz,4)
boolbool_0_lt_4=array.get(arr_zz,0)<array.get(arr_zz,4)
ifbool_or_1orbool_or_2
ifbool_n_1andbool_n_2
label.delete(label_zz)
str_label=dir==1?bool_0_mt_4?'▼':'◍':
bool_0_lt_4?'▲':'◍'
col_label=dir==1?bool_0_mt_4?color.red:color.teal:
bool_0_lt_4?color.teal:color.red
ifi_show_crsi
label_zz:=label.new(bar_index,high,text=str_label,color=color.new(color.blue,100),textcolor=col_label,style=dir==1?label.style_label_down:label.style_label_up)
ifdir==1
cRSI_high_extreme_found:=close
cRSI_low_extreme_found:=0.0
last_cRSI_extreme:="high"
else
cRSI_low_extreme_found:=close
cRSI_high_extreme_found:=0.0
last_cRSI_extreme:="low"
//ifwefoundacRSIextremecloseanyopentradeshere
ifi_use_crsiandcRSI_high_extreme_found>0.0
strategy.close("Buy",comment="closebuy(cRSI)")
ifi_use_crsiandcRSI_low_extreme_found>0.0
strategy.close("Sell",comment="closesell(cRSI)")
//dowehaveaHeikinAshiopensignal?
//ashi_entry_found=false
//ifi_use_ashiand(ashi_golongorashi_goshort)
//ashi_entry_found=true
//ifashi_golong
////closeallshorts
//strategy.close("Sell",comment="closesell(ashi)")
////openanewBuytrade
//stopPrice=close+((SLPerc/100)*close)
//strategy.entry("Buy",strategy.long,comment="Buy(ashi,SL="+str.tostring(stopPrice)+")")
//strategy.exit("Buy",stop=stopPrice,comment="closedbySL"+str.tostring(SLPerc)+"%")
//nothingelsetodoifwe'vehadaHeikinAshiopening
//ifnotashi_entry_found
//checkthatourlastfoundhighextremeisnotmorethani_trade_trend_direction_change_percent_cancelpercentlowerthanourcurrentprice
//inwhichcasewe'llmarkitasinvalid,sowecankeeponopeningbuyentries
ifi_use_crsiandi_trade_trend_directionandcRSI_high_extreme_found>0.0
ifcRSI_high_extreme_found!=close
extreme_distance_from_last_point_percent=((cRSI_high_extreme_found-close)/cRSI_high_extreme_found)*100
cRSI_high_extreme_valid:=close<cRSI_high_extreme_foundormath.abs(extreme_distance_from_last_point_percent)<i_trade_trend_direction_change_percent_cancel
//resetthehighextremetocurrentpriceifwefoundoutthatwe'reredrawingitfurther
ifnotcRSI_high_extreme_valid
cRSI_high_extreme_found:=close
cRSI_high_extreme_valid:=false
else
cRSI_high_extreme_valid:=true
//checkthatourlastfoundlowextremeisnotmorethani_trade_trend_direction_change_percent_cancelpercenthigherthanourcurrentprice
//inwhichcasewe'llmarkitasinvalid,sowecankeeponopeningsellentries
ifi_use_crsiandi_trade_trend_directionandcRSI_low_extreme_found>0.0
ifcRSI_low_extreme_found!=close
extreme_distance_from_last_point_percent=((cRSI_low_extreme_found-close)/cRSI_low_extreme_found)*100
cRSI_low_extreme_valid:=close>cRSI_low_extreme_foundormath.abs(extreme_distance_from_last_point_percent)<i_trade_trend_direction_change_percent_cancel
//resetthehighextremetocurrentpriceifwefoundoutthatwe'reredrawingitfurther
ifnotcRSI_low_extreme_valid
cRSI_low_extreme_found:=close
cRSI_low_extreme_valid:=false
else
cRSI_low_extreme_valid:=true
//MESApivothighwasfound
if(noti_use_mesaor(ph_mesaandout_zone)?ph_mesa:na)
//closetradeifacRSIextremewaspreviouslyfound,otherwiseletthecRSIclosethetradeonceitgetsthere
ifnoti_use_crsior(cRSI_high_extreme_found>0.0andcRSI_high_extreme_valid)
strategy.close("Buy",comment="closebuy("+(i_use_mesa?"MESA":i_use_crsi?"cRSI":i_use_htf_mesa?"HTFMESA":"unknown")+")")
//openacounter-strategy,if:
//1)we'renottooclosetothelasttrade'sTS
//2)we'reinthecorrectcRSItrend(ifenabled)
//3)we'reinthecorrectMESAHTFMAtrend(ifenabled)
//4)we'reinthecorrectALMAtrend(ifenabled)
//5)we'reinthecorrectMACDtrend(ifenabled)
if(inDateRangeand((time-last_trade_ts)/1000>=(60*min_trade_gap_minutes))and(noti_use_crsiorlast_cRSI_extreme=="high")and(noti_use_mesaor(i_use_mesaand(time-last_pivot_ts)/1000>=(60*min_mesa_pivots_gap_minutes)))and(noti_use_crsiornoti_trade_trend_directionorlast_cRSI_extreme=="high")and(noti_use_htf_mesaormesa_ma_trend_direction=="down")and(noti_use_almaoralma_trend_direction=="down")and(noti_use_macdormacd_trend_direction=="down")and(strategy.opentrades==0orstrategy.opentrades.entry_id(strategy.opentrades-1)!="Sell"))
stopPrice=close+((SLPerc/100)*close)
strategy.entry("Sell",strategy.short,comment="Sell(SL="+str.tostring(stopPrice)+")")
strategy.exit("Sell",stop=stopPrice,comment="closedbySL"+str.tostring(SLPerc)+"%")
cRSI_low_extreme_found:=0.0
last_trade_ts:=time
last_pivot_ts:=time
//MESApivotlowwasfound
if(noti_use_mesaor(pl_mesaandout_zone)?pl_mesa:na)
//closetradeifacRSIextremewaspreviouslyfound,otherwiseletthecRSIclosethetradeonceitgetsthere
ifnoti_use_crsior(cRSI_low_extreme_found>0.0andcRSI_low_extreme_valid)
strategy.close("Sell",comment="closesell("+(i_use_mesa?"MESA":i_use_crsi?"cRSI":i_use_htf_mesa?"HTFMESA":"unknown")+")")
//openacounter-strategy,if:
//1)we'renottooclosetothelasttrade'sTS
//2)we'reinthecorrectcRSItrend(ifenabled)
//3)we'reinthecorrectMESAHTFMAtrend(ifenabled)
//4)we'reinthecorrectALMAtrend(ifenabled)
//5)we'reinthecorrectMACDtrend(ifenabled)
if(inDateRangeand((time-last_trade_ts)/1000>=(60*min_trade_gap_minutes))and(noti_use_crsiorlast_cRSI_extreme=="low")and(noti_use_mesaor(i_use_mesaand(time-last_pivot_ts)/1000>=(60*min_mesa_pivots_gap_minutes)))and(noti_use_crsiornoti_trade_trend_directionorlast_cRSI_extreme=="low")and(noti_use_htf_mesaormesa_ma_trend_direction=="up")and(noti_use_almaoralma_trend_direction=="up")and(noti_use_macdormacd_trend_direction=="down")and(strategy.opentrades==0orstrategy.opentrades.entry_id(strategy.opentrades-1)!="Buy"))
stopPrice=close-((SLPerc/100)*close)
//strategy.entry("Buy",strategy.long,comment="close:"+str.tostring(close)+",sl:"+str.tostring(stopPrice))
strategy.entry("Buy",strategy.long,comment="Buy(SL="+str.tostring(stopPrice)+")")
strategy.exit("Buy",stop=stopPrice,comment="closedbySL"+str.tostring(SLPerc)+"%")
cRSI_high_extreme_found:=0.0
last_trade_ts:=time
last_pivot_ts:=time
//Exitopenmarketpositionwhendaterangeends
if(notinDateRange)
strategy.close_all()
Expand (464 lines)
