Script Name: MESA + Volume + RSI Decision Points Strategy
Author: UnknownUnicorn36161431
Description: The WHAT
=============>
Combination of 3 indicators, first 2 are to get entry points, the last one (MESA) is to get exit points:

1) "Koalafied Volume Extension" by @Koalafied_3 - used to detect whether current trend candles are supported by volume


2) "Koalafied RSI Decision Points" by @Koalafied_3 - another indicator used to detect trend momentum


3) "Mesa...
PineScript code:

Pine Script™ strategy
MESA + Volume + RSI Decision Points Strategy
//  @version=5
strategy("MESA  +  Volume  +  RSI  Decision  Points  Strategy",  shorttitle="MESA  +  Volume  +  RSI",  overlay=true,  process_orders_on_close  =  true,  calc_on_order_fills  =  true,  pyramiding  =  0,  default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  75,  commission_type  =  strategy.commission.percent,  commission_value  =  0.04,  initial_capital  =  100)
GROUP_GLOBAL_OPTIONS  =  "Global  Options"
GROUP_TIME_LIMITED_BACKTESTS  =  "Time-Limit  BackTests  (0  =  disable)"
GROUP_RSI_OPTIONS  =  "RSI  Options"
GROUP_VOLUME_OPTIONS  =  "Volume  Extension  Options"
GROUP_VOLUME_COLOR_OPTIONS  =  "Volume  Extension  Color  Options"
GROUP_MESA  =  "MESA  Pivots  Options"
SLPerc  =  input.float(  2.5,  title="Stop  Loss  (%)",  minval=0.0,  step=0.1,  group  =  GROUP_GLOBAL_OPTIONS)
i_use_time_limited_backtesting  =  input.bool(  false,  "Use  Time-Limited  Backtesting",  group  =  GROUP_TIME_LIMITED_BACKTESTS  )
startDay  =  input.int(0,  "Start  Day",  minval  =  0,  maxval  =  31,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
startMonth  =  input.int(0,  "Start  Month",  minval  =  0,  maxval  =  12,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
startYear  =  input.int(0,  "Start  Year",  minval  =  0,  maxval  =  2100,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
endDay  =  input.int(0,  "End  Day",  minval  =  0,  maxval  =  31,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
endMonth  =  input.int(0,  "End  Month",  minval  =  0,  maxval  =  12,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
endYear  =  input.int(0,  "End  Year",  minval  =  0,  maxval  =  2100,  group  =  GROUP_TIME_LIMITED_BACKTESTS)
rsi_len      =  input(  14,  "RSI  Length",  group  =  GROUP_RSI_OPTIONS  )
rsi_showBG  =  input(true,  'Show  RSI  Background  State',  group  =  GROUP_RSI_OPTIONS)
rsi_showlines  =  input(true,  "Show  Decision  Point  Levels",  group  =  GROUP_RSI_OPTIONS)
rsi_plot_sel  =  input.string(title='Plot  Selection',  defval='Both',  options=['Both',  'Shapes',  'Candles'],  group  =  GROUP_RSI_OPTIONS)
rsi_transp  =  input.int(92,  "Background  Transparency",  minval  =  0,  maxval  =  100,  group  =  GROUP_RSI_OPTIONS)
i_show_volume_extension  =  input.bool(  true,  "Color  Candles  by  Volume  Extension",  group  =  GROUP_VOLUME_OPTIONS  )
vol_len  =  input(21,  "Z-Score  MA  Length",  group  =  GROUP_VOLUME_OPTIONS)
vol_MA_sel  =  input.string(title='MA  Selection',  defval='SMA',  options=['SMA',  'EMA',  'WMA'],  group  =  GROUP_VOLUME_OPTIONS)
vol_deviation_1  =  input(2.0,  "Std  Dev",  group  =  GROUP_VOLUME_OPTIONS)
vol_deviation_2  =  input(3.0,  "Std  Dev",  group  =  GROUP_VOLUME_OPTIONS)
vol_rising_sel  =  input(false,  "Colour  rising  volume  bars",  group  =  GROUP_VOLUME_OPTIONS)
vol_colup_ext2  =  input.color(color.lime,  "Bull  Extension  2",  group  =  GROUP_VOLUME_COLOR_OPTIONS)
vol_colup_ext1  =  input.color(color.blue,  "Bull  Extension  1",  group  =  GROUP_VOLUME_COLOR_OPTIONS)
vol_coldown_ext1  =  input.color(color.red,  "Bear  Extension  1",  group  =  GROUP_VOLUME_COLOR_OPTIONS)
vol_coldown_ext2  =  input.color(color.purple,  "Bear  Extension  2",  group  =  GROUP_VOLUME_COLOR_OPTIONS)
vol_col_risingUP  =  input.color(color.white,  "Rising  Candle  Color  Up",  group  =  GROUP_VOLUME_COLOR_OPTIONS)
vol_col_risingDOWN  =  input.color(color.gray,  "Rising  Candle  Color  Down",  group  =  GROUP_VOLUME_COLOR_OPTIONS)
vol_col_blank  =  input.color(color.new(color.black,100),  "Blank  Candle  Color",  group  =  GROUP_VOLUME_COLOR_OPTIONS)
i_show_mesa  =  input.bool(  false,  "Show  MESA  Pivots",  group  =  GROUP_MESA  )
offsetNum  =  input(  0,  "MESA  offset",  group  =  GROUP_MESA)
pivot_zone_upper  =  input.float(  0.4,  "MESA  pivot  zone  upper",  step=0.1,  group  =  GROUP_MESA  )
pivot_zone_lower  =  input.float(  -0.4,  "MESA  pivot  zone  lower",  step=0.1,  group  =  GROUP_MESA  )
inDateRange  =  true
//  Look  if  the  close  time  of  the  current  bar  falls  inside  the  date  range
if  i_use_time_limited_backtesting  and  startDay  !=  0  and  startMonth  !=  0  and  startYear  !=  0  and  endDay  !=  0  and  endMonth  !=  0  and  endYear  !=  0
        inDateRange  :=  (  time  >=  timestamp(  syminfo.timezone,  startYear,  startMonth,  startDay,  0,  0  )  )  and  (  time  <  timestamp(  syminfo.timezone,  endYear,  endMonth,  endDay,  0,  0  )  )
//------------------------------------------------------------------------------
//  persisting  variables
//------------------------------------------------------------------------------
var  last_trade_ts  =  time
var  min_trade_gap_minutes  =  2
//------------------------------------------------------------------------------
//  MESA  calculations  from  the  MESA  indicator
//------------------------------------------------------------------------------
//  Basic
//------------------------------------------------------------------------------
DomCycle  =  15
RealPart  =  0.0
ImagPart  =  0.0
for  J  =  0  to  DomCycle  -  1
        Weight  =  (close[J]  +  close[J]  +  high[J]  +  low[J])  *  10000
        if  DomCycle  !=  0
                RealPart  :=  RealPart  +  math.cos(90  *  J  /  DomCycle)  *  Weight  *  2
                ImagPart  :=  ((ImagPart  +  math.sin(90  *  J  /  DomCycle)  *  Weight)  +  (ImagPart  +  math.sin(180  *  J  /  DomCycle)  *  Weight))  /  2
Phase  =  ((math.atan(ImagPart  /  RealPart))  -  0.685)  *  100
//------------------------------------------------------------------------------
//Pivot
//------------------------------------------------------------------------------
ph_mesa  =  ta.pivothigh(Phase,  1,  1)
pl_mesa  =  ta.pivotlow(Phase,  1,  1)
out_zone  =  Phase[2]  <  pivot_zone_lower  or  Phase[2]  >  pivot_zone_upper
plotshape(i_show_mesa  and  ph_mesa  and  out_zone  ?  ph_mesa  :  na,  title  =  "Pivot  High",  color=#f23737,  style  =  shape.circle,  location  =  location.abovebar,  offset  =  -1,  size  =  size.tiny)
plotshape(i_show_mesa  and  pl_mesa  and  out_zone  ?  pl_mesa  :  na,  title  =  "Pivot  Low",  color=#169788,  style  =  shape.circle,  location  =  location.belowbar,  offset  =  -1,  size  =  size.tiny)
//------------------------------------------------------------------------------
//  RSI  Decision  Points  indicator  code
//------------------------------------------------------------------------------
rsi_rsi  =  ta.rsi(close,  rsi_len)
//  Trend  State
var  rsi_state  =  0
if  ta.crossover(rsi_rsi,  66.67)
        rsi_state  :=  1
        rsi_state
if  ta.crossunder(rsi_rsi,  33.33)
        rsi_state  :=  2
        rsi_state
if  rsi_state  ==  1  and  ta.crossunder(rsi_rsi,  40)
      rsi_state:=3
rsi_state
ifrsi_state==2andta.crossover(rsi_rsi,60)
rsi_state:=3
rsi_state
rsi_state:=rsi_state
//DecisionPointConditions
rsi_pause1=rsi_state==3andrsi_state[1]==1
rsi_pause2=rsi_state==3andrsi_state[1]==2
rsi_mom_bull=rsi_state==1andrsi_state[1]==3
rsi_mom_bear=rsi_state==2andrsi_state[1]==3
rsi_exit_bull=rsi_state==1andta.crossunder(rsi_rsi,66.67)
rsi_exit_bear=rsi_state==2andta.crossover(rsi_rsi,33.33)
rsi_failure_bullrev=rsi_state==1andta.crossunder(rsi_rsi[1],66.67)andta.crossover(rsi_rsi,66.67)
rsi_failure_bearrev=rsi_state==2andta.crossover(rsi_rsi[1],33.33)andta.crossunder(rsi_rsi,33.33)
varfloatrsi_pause_bull=na
varfloatrsi_pause_bear=na
rsi_pause_bull:=rsi_pause1?low:rsi_pause_bull[1]
rsi_pause_bear:=rsi_pause2?high:rsi_pause_bear[1]
rsi_candles=rsi_plot_sel=='Candles'
rsi_shapes=rsi_plot_sel=='Shapes'
rsi_both=rsi_plot_sel=='Both'
//----------PLOTS----------//
//PlotDecisionPoints
plot(rsi_showlines?rsi_pause_bull:na,title="BullDecisionPointLevel",color=color.new(color.blue,50),style=plot.style_circles)
plot(rsi_showlines?rsi_pause_bear:na,title="BearDecisionPointLevel",color=color.new(color.red,50),style=plot.style_circles)
plotshape(rsi_shapesorrsi_both?rsi_pause1:na,style=shape.square,location=location.belowbar,color=color.new(color.blue,0))
plotshape(rsi_shapesorrsi_both?rsi_pause2:na,style=shape.square,location=location.abovebar,color=color.new(color.red,0))
plotshape(rsi_shapesorrsi_both?rsi_mom_bull:na,style=shape.triangleup,location=location.belowbar,color=color.new(color.blue,0))
plotshape(rsi_shapesorrsi_both?rsi_mom_bear:na,style=shape.triangledown,location=location.abovebar,color=color.new(color.red,0))
plotshape(rsi_shapesorrsi_both?rsi_exit_bull:na,style=shape.xcross,location=location.abovebar,color=color.new(color.orange,0))
plotshape(rsi_shapesorrsi_both?rsi_exit_bear:na,style=shape.xcross,location=location.belowbar,color=color.new(color.orange,0))
plotshape(rsi_shapesorrsi_both?rsi_failure_bullrev:na,style=shape.triangleup,location=location.belowbar,color=color.new(color.lime,0))
plotshape(rsi_shapesorrsi_both?rsi_failure_bearrev:na,style=shape.triangledown,location=location.abovebar,color=color.new(color.purple,0))
rsi_candle_col=rsi_pause1orrsi_mom_bull?color.blue:rsi_pause2orrsi_mom_bear?color.red:rsi_exit_bullorrsi_exit_bear?color.orange:rsi_failure_bullrev?color.lime:rsi_failure_bearrev?color.purple:na
barcolor(rsi_candlesorrsi_both?rsi_candle_col:na)
//Trend
rsi_state_col=rsi_state==1?color.new(color.blue,rsi_transp):rsi_state==2?color.new(color.red,rsi_transp):na
bgcolor(rsi_showBG?rsi_state_col:na,title='TrendState')
//2:1Momentum
rsi_BG_col=rsi_rsi>66.67?color.new(color.blue,rsi_transp):rsi_rsi<33.33?color.new(color.red,rsi_transp):na
bgcolor(rsi_showBG?rsi_BG_col:na,title='TrendMomentum')
//4:1Momentum
rsi_OB=rsi_rsi>80?color.new(color.red,rsi_transp):na
rsi_OS=rsi_rsi<20?color.new(color.blue,rsi_transp):na
bgcolor(rsi_showBG?rsi_OB:na,title='Overbought')
bgcolor(rsi_showBG?rsi_OS:na,title='Oversold')
//------------------------------------------------------------------------------
//VolumeExtensionindicatorcode
//------------------------------------------------------------------------------
//----------FUNCTIONS----------//

vol_Z_score(_src,_length,MA_sel)=>
_mean=MA_sel=='SMA'?ta.sma(_src,_length):MA_sel=='EMA'?ta.ema(_src,_length):MA_sel=='WMA'?ta.wma(_src,_length):na
_value=(_src-_mean)/(ta.stdev(_src-_mean,_length))
//----------CALCS----------//
vol_src=volume
vol_vol=vol_Z_score(vol_src,vol_len,vol_MA_sel)
vol_extension_1=vol_vol>vol_deviation_1andvol_vol<vol_deviation_2
vol_extension_2=vol_vol>vol_deviation_2
vol_bull=close>open
vol_bear=close<open
vol_rising=volume>volume[1]
vol_rising_col=close>openandvol_rising?vol_col_risingUP:close<openandvol_rising?vol_col_risingDOWN:vol_col_blank
vol_devUp2=vol_extension_2andvol_bull
vol_devUp1=vol_extension_1andvol_bull
vol_devDown1=vol_extension_1andvol_bear
vol_devDown2=vol_extension_2andvol_bear
//----------PLOTS----------//
barcolor(i_show_volume_extension?(vol_devUp1?vol_colup_ext1:vol_devDown1?vol_coldown_ext1:na):na,title="Extension1")
barcolor(i_show_volume_extension?(vol_devUp2?vol_colup_ext2:vol_devDown2?vol_coldown_ext2:na):na,title="Extension2")
barcolor(i_show_volume_extension?(notvol_extension_1andnotvol_extension_2andnotvol_rising_sel?vol_col_blank:notvol_extension_1andnotvol_extension_2andvol_rising_sel?vol_rising_col:na):na,title="Rising/Falling")
//opentradesifVolumeExtensionandRSIDecisionPointmatch
if(vol_devUp1orvol_devUp2)andrsi_rsi>66.67and(strategy.opentrades==0orstrategy.opentrades.entry_id(strategy.opentrades-1)!="Buy")
//closeanypreviouslyopenedtradetothesellside
strategy.close("Sell",comment="closesell")
//calculateSL
stopPrice=close-((SLPerc/100)*close)
//opentrade
strategy.entry("Buy",strategy.long,comment="Long(SL="+str.tostring(stopPrice)+")")
strategy.exit("Buy",stop=stopPrice,comment="closedbySL"+str.tostring(SLPerc)+"%")
last_trade_ts:=time
if(vol_devDown1orvol_devDown2)andrsi_rsi<33.33and(strategy.opentrades==0orstrategy.opentrades.entry_id(strategy.opentrades-1)!="Sell")
//closeanypreviouslyopenedtradetothebuyside
strategy.close("Buy",comment="closebuy")
//calculateSL
stopPrice=close+((SLPerc/100)*close)
//opentrade
strategy.entry("Sell",strategy.short,comment="Short(SL="+str.tostring(stopPrice)+")")
strategy.exit("Sell",stop=stopPrice,comment="closedbySL"+str.tostring(SLPerc)+"%")
last_trade_ts:=time
//MESApivothighwasfound-closeanypendingtradestothebuyside
ifph_mesaandout_zone?ph_mesa:naandstrategy.opentrades>0andstrategy.opentrades.entry_id(strategy.opentrades-1)=="Buy"
strategy.close("Buy",comment="BuyTPreached")
//MESApivotlowwasfound-closeanypendingtradestothebuyside
ifpl_mesaandout_zone?pl_mesa:naandstrategy.opentrades>0andstrategy.opentrades.entry_id(strategy.opentrades-1)=="Sell"
strategy.close("Sell",comment="SellTPreached")
//Exitopenmarketpositionwhendaterangeends
if(notinDateRange)
strategy.close_all()
Expand (243 lines)
