Script Name: Momentum Strategy (BTC-USDT; 30m) - STOCH RSI (with source code)
Author: Drun30
Description: Here's a strategy for low time frames (30min suggested) for BTC , based on momentum Analysis using Stochastic RSI
By default the strategy will use the 50% of the specified capital for each trade; if "Gamble Sizing" is enabled, it will add the specified amount of capital (25% by default, until reaching the 100% limit or lower) for the next trade after having...
PineScript code:

Pine Script™ strategy
Momentum Strategy (BTC/USDT; 30m) - STOCH RSI (with source code)
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  Drun30  (Federico  Magnani)
//@version=4
//STRATEGIA  PRINCIPALE
///////////////////  CHANGE  THESE  VARIABLES  FOR  TV-HUB  ///////////////////
var  pair  =  "BTCUSDT"  //metti  il  valore  associato  a  "pair"  nel  JSON  generato  da  TVHUB
var  orderSizePercent  =  70  //  →  %  di  capitale  investita  per  ogni  trade,  la  percentuale  è  da  riferirsi  alla  PERCENTUALE  DI  CRIPTOVALUTA  PRESENTE  NEL  PORTAFOGLIO  SPOT  (se  ho  messo  la  coppia  "BTCUSDT",  ho  1200  USDT  liberi  nel  portafoglio  e  lascio  "orderSizePercent"=50,  mi  eseguirà  un  ordine  di  acquisto  spendendo  600  USDT  (=1200*0.5)  per  comprare  BTC  (in  caso  di  ordine  long))
var  stopLossPercent_Long  =  10  //è  lo  stop  loss  (percentuale)  per  le  posizioni  Long,  metti  il  valore  associato  a  "stopLossPercent"  nel  JSON  generato  da  TVHUB  per  le  posizioni  long
var  takeProfitPercent_Long  =  8  //è  il  take  profit  (percentuale)  per  le  posizioni  Long,  metti  il  valore  associato  a  "takeProfitPercent"  nel  JSON  generato  da  TVHUB  per  le  posizioni  long
var  stopLossPercent_Short  =  20  //è  lo  stop  loss  (percentuale)  per  le  posizioni  Short,  metti  il  valore  associato  a  "stopLossPercent"  nel  JSON  generato  da  TVHUB  per  le  posizioni  short
var  takeProfitPercent_Short  =  35  //è  il  take  profit  (percentuale)  per  le  posizioni  Short,  metti  il  valore  associato  a  "takeProfitPercent"  nel  JSON  generato  da  TVHUB  per  le  posizioni  short
var  tokenTVHUB  =  "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"  //è  il  token  associato  al  tuo  account  su  TV-HUB,  metti  il  valore  associato  a  "token"  nel  JSON  generato  da  TVHUB
var  exchange  =  "Binance-Futures-Testnet"  //metti  il  valore  associato  a  "exchange"  nel  JSON  generato  da  TVHUB
//Excgange  possibili:  Bitmex,  Bitmex-Testnet,  Binance,  Binance-Futures,  Binance-Futures-Testnet,  Bybit,  Bybit-Testnet
var  leverage  =  1  //lascia  1  se  non  stai  usando  binance  futures  o  bitmex
commissionsPercent  =  0.1  //commissioni  dell'exchange  (0.1  =  0.1%,  sono  le  commissioni  di  Binance)
////////////////////////////////////////////////////////////////////////
///////////////////  QUICK  CHANGE  VARIABLES  OF  THE  STRATEGY  ///////////////////
wantToUseGambleSizing=true  //se  "true"  aumenterà  la  size  del  trade  successivo  a  quello  perdente  per  il  valore  percentuale  associato  a  "deltasize"  (se  ho  fallito  un  trade  con  il  50%  della  size,  se  wantToUseGambleSizing=true  e  deltaSize=25,  il  trade  successivo  impiegherà  il  75%  della  valuta  in  portafoglio)
var  deltaSize  =  25  //  →  delta%  di  capitale  investito  se  trade  precedente  è  stato  in  perdita  (cumulabile:  se  parto  con  il  50%delcapitaleediltradevainperdita,iltradesuccessivouseràil75%(=50+25),sefallisceanchequellouseràil100%(=50+25+25)(ammessochesiastatoraggiuntoilvalore"sizeLimite"))
varsizeLimite=100//iltradenonimpiegheràmaiunapercentualesuperioreaquestaneitradesuccessiviaquelloandatoinperdita
capitaleIniziale=1000
varsizeordineInit=orderSizePercent
varsizeordine=sizeordineInit
//Parametriottimali30min
usiShort=true
usiLong=true
ipercomprato=85.29
ipervenduto=30.6
//
//////////////////////////////////////////////////////////////////////////////
strategy("MomentumStrategy(V7.B.4)",initial_capital=capitaleIniziale,currency="USD",default_qty_type=strategy.percent_of_equity,commission_type=strategy.commission.percent,commission_value=commissionsPercent,slippage=5,default_qty_value=sizeordineInit,overlay=false,pyramiding=0)
backtest=input(title="------------------------BacktestPeriod------------------------",defval=false)
start=timestamp(input(2020,"startyear"),input(1,"startmonth"),input(1,"startday"),00,00)
end=timestamp(input(0,"endyear"),input(0,"endmonth"),input(0,"endday"),00,00)
siamoindata=time>start?true:false
ifend>0
siamoindata:=time>startandtime<=end?true:false
basicParameters=input(title="------------------------BasicParameters------------------------",defval=false)
smoothK=input(3,minval=1)
smoothD=input(6,minval=1)
lengthRSI=input(12,minval=1)
src=input(close,title="RSISource")
rsi1=rsi(src,lengthRSI)
lengthStoch=input(12,minval=1)
k=ema(stoch(rsi1,rsi1,rsi1,lengthStoch),smoothK)
d=ema(k,smoothD)
altezzaipercomprato=input(ipercomprato,title="OverboughtHeight",minval=1,type=input.float)
altezzaipervenduto=input(ipervenduto,title="OversoldHeight",minval=1,type=input.float)
BarsDelay=input(6,title="Barsdelay",minval=0)
GambleSizing=input(wantToUseGambleSizing,title="GambleSizing?",type=input.bool)
gambleAdd=input(deltaSize,title="GambleAdd(%)",minval=0,type=input.integer)
gambleLimit=input(sizeLimite,title="GambleMAX(%)",minval=0,type=input.integer)
ifGambleSizingandstrategy.closedtrades[0]>strategy.closedtrades[1]
ifstrategy.losstrades[0]>strategy.losstrades[1]andsizeordine<gambleLimit
sizeordine:=sizeordine+gambleAdd
ifstrategy.wintrades[0]>strategy.wintrades[1]
sizeordine:=sizeordineInit
periodomediamobile_fast=input(1,title="FastEMAlength",minval=1)
periodomediamobile_slow=input(60,title="SlowEMAlength",minval=1)
plot(k,color=color.blue)
plot(d,color=color.orange)
h0=hline(altezzaipercomprato)
h1=hline(altezzaipervenduto)
fill(h0,h1,color=color.purple,transp=80)
//n=input(Vicinanzadalcentro,title="Vicinanzadalcentro",minval=0)
//sarebbeillivellodiDincuisiacquistaosivende,maggioreèlavicinanzamaggioresaràlafrequenzadeitrades,SE0èDISABILITATO
//siamoinipervenduto=d<=altezzaipervendutoandd<=d[n]andd>d[1]?true:false//andd<d[3]andd>d[1]
//siamoinipercomprato=d>=altezzaipercompratoandd>=d[n]andd<d[1]?true:false//andd>d[3]andd<d[1]
goldencross=crossover(k,d)
deathcross=crossunder(k,d)
//METTIVARIABILEINCUIAVVIENECROSSOVEROCROSSUNDER
valoreoro=valuewhen(goldencross,d,0)
valoremorte=valuewhen(deathcross,d,0)
siamoinipervenduto=goldencrossandvaloreoro<=altezzaipervenduto?true:false//d<=altezzaipervenduto?true:false
siamoinipercomprato=deathcrossandvaloremorte>=altezzaipercomprato?true:false//d>=altezzaipercomprato?true:false
long_separator=input(title="------------------------LONG------------------------",defval=usiLong)
sl_long_inp=input(stopLossPercent_Long,title="StopLossLONG%",type=input.float,step=0.1)
tp_long_inp=input(takeProfitPercent_Long,title="TakeProfitLONG%",type=input.float,step=0.1)
stop_level_long=strategy.position_avg_price*(1-(sl_long_inp/100))//strategy.position_avg_pricecorrispondealprezzoconcuisièapertalaposizione
take_level_long=strategy.position_avg_price*(1+(tp_long_inp/100))
//BINANCE
JSON_long='{"pair":"'+pair+'","isBuy":true,"isSell":false,"isMarket":true,"isLimit":false,"isClose":false,"price":"9497.59","unitsPercent":"'+tostring(sizeordine)+'","unitsType":"percentBalance","stopLoss":"8545.44","stopLossPercent":"-'+tostring(sl_long_inp)+'","stopLossType":"percent","marginType":"ISOLATED","targets":[{"idx":1,"price":"10257.32","amount":"'+tostring(100-commissionsPercent)+'","takeProfitPercent":"'+tostring(tp_long_inp)+'"}],"targetType":"percent","leverage":"'+tostring(leverage)+'","closeCurrentPosition":true,"token":"'+tokenTVHUB+'","exchange":"'+exchange+'"}'
JSON_chiusura='{"pair":"'+pair+'","isBuy":false,"isSell":false,"isMarket":true,"isLimit":false,"isClose":true,"price":"9497.36","units":"0.01","unitsPercent":"'+tostring(sizeordine)+'","unitsType":"percentBalance","stopLoss":"8545.44","stopLossPercent":"-'+tostring(sl_long_inp)+'","stopLossType":"percent","marginType":"ISOLATED","targets":[{"idx":1,"price":"10257.32","amount":"'+tostring(100-commissionsPercent)+'","takeProfitPercent":"'+tostring(tp_long_inp)+'"}],"targetType":"percent","leverage":"'+tostring(leverage)+'","closeCurrentPosition":true,"token":"'+tokenTVHUB+'","exchange":"'+exchange+'"}'
webhookLong=JSON_long
webhookClose=JSON_chiusura
trendFilterL=input(title="TRENDFILTERLONG?",defval=true)
EMAfast=ema(close,periodomediamobile_fast)
EMAslow=ema(close,periodomediamobile_slow)
siamoinuptrend_ema=EMAfast>EMAslow?true:false//close>=EMAfastandEMAfast>EMAslow
siamoinuptrend=siamoinuptrend_ema
//CondizioneAperturaLong=siamoinipervendutoandsiamoindata//andsiamoinuptrend
CondizioneAperturaLong=siamoinipervendutoandsiamoindataandlong_separator
iftrendFilterL
CondizioneAperturaLong:=siamoinipervendutoandsiamoindataandlong_separatorandsiamoinuptrend
CondizioneChiusuraLong=siamoinipercompratoandsiamoindata
possiamoAprireLong=0
iftrendFilterLandsiamoinuptrend
possiamoAprireLong:=5
plot(possiamoAprireLong,color=color.green)
sonPassateLeBarreG=barssince(CondizioneAperturaLong)==BarsDelay?true:false
sonPassateLeBarreD=barssince(CondizioneChiusuraLong)==BarsDelay?true:false
haiUnLongAncoraAperto=false
haiUnLongAncoraAperto:=strategy.position_size>0?true:false
//Sel'ultimovaloredellaserie"CondizioneAperturaLong"èTRUE,allorahaiunlongancoraaperto
//Sel'ultimovaloredellaserie"CondizioneAperturaLong"èFALSE,allora:
//Sel'ultimovaloredellaserie"CondizioneChiusuraLong"èTRUE,alloraNONhaiunlongancoraaperto
//Sel'ultimovaloredellaserie"CondizioneChiusuraLong"èFALSE,allorarestituiscel'ultimovaloredellaserie"haiUnLongAncoraAperto"
haiUnLongAncoraAperto_float=if(haiUnLongAncoraAperto==true)
10
else
0
plot(haiUnLongAncoraAperto_float,color=color.red)//FInchélalinearossasitrovaalivello"1"allorac'èunordinelongincorso
quantita=(sizeordine/100*(capitaleIniziale+strategy.netprofit))/valuewhen(haiUnLongAncoraAperto==falseandCondizioneAperturaLong,close,0)
plot(sizeordine,color=color.purple,linewidth=3)
ifstrategy.position_size<=0andCondizioneAperturaLong//andsonPassateLeBarreGandhaiUnLongAncoraAperto==falsestrategy.opentrades==0
strategy.entry("Vamonos",strategy.long,alert_message=webhookLong,comment="OPENLONG",qty=quantita)
ifstrategy.position_size>0//andsonPassateLeBarreD//andCondizioneChiusuraLong
ifsiamoinuptrend==trueandsonPassateLeBarreD
strategy.close("Vamonos",alert_message=webhookClose,comment="CLOSELONG")
elseifsiamoinuptrend==falseandCondizioneChiusuraLong
strategy.close("Vamonos",alert_message=webhookClose,comment="CLOSELONG")

ifstrategy.position_size>0andsiamoindata
strategy.exit("Vamonos",stop=stop_level_long,limit=take_level_long,alert_message=webhookClose,comment="CLOSELONG(LIMIT/STOP)")
short_separator=input(title="------------------------SHORT------------------------",defval=usiShort)
sl_short_inp=input(stopLossPercent_Short,title="StopLossSHORT%",type=input.float,step=0.1)
tp_short_inp=input(takeProfitPercent_Short,title="TakeProfitSHORT%",type=input.float,step=0.1)
stop_level_short=strategy.position_avg_price*(1+(sl_short_inp/100))
take_level_short=strategy.position_avg_price*(1-(tp_short_inp/100))
//BINANCE
JSON_short='{"pair":"'+pair+'","isBuy":false,"isSell":true,"isMarket":true,"isLimit":false,"isClose":false,"price":"9147.62","units":"'+tostring(sizeordine)+'","unitsPercent":"'+tostring(sizeordine)+'","unitsType":"percentBalance","stopLoss":"10062.41","stopLossPercent":"-'+tostring(sl_short_inp)+'","stopLossType":"percent","marginType":"ISOLATED","targets":[{"idx":1,"price":"7775.50","amount":"'+tostring(100-commissionsPercent)+'","takeProfitPercent":"'+tostring(tp_short_inp)+'"}],"targetType":"percent","leverage":"'+tostring(leverage)+'","closeCurrentPosition":true,"token":"'+tokenTVHUB+'","exchange":"'+exchange+'"}'
webhookShort=JSON_short
trendFilterS=input(title="TRENDFILTERSHORT?",defval=true)
siamoindowntrend_ema=EMAfast<EMAslow?true:false//close<=EMAfastandEMAfast<EMAslow
siamoindowntrend=siamoindowntrend_ema
CondizioneAperturaShort=short_separatorandsiamoinipercompratoandsiamoindata
iftrendFilterS
CondizioneAperturaShort:=short_separatorandsiamoinipercompratoandsiamoindataandsiamoindowntrend
CondizioneChiusuraShort=siamoinipervendutoandsiamoindata
sonPassateLeBarreGs=barssince(CondizioneAperturaShort)==BarsDelay?true:false
sonPassateLeBarreDs=barssince(CondizioneChiusuraShort)==BarsDelay?true:false
haiUnoShortAncoraAperto=false
haiUnoShortAncoraAperto:=strategy.position_size<0?true:false
haiUnoShortAncoraAperto_float=if(haiUnoShortAncoraAperto==true)
15
else
0
plot(haiUnoShortAncoraAperto_float,color=color.purple)//FInchélalineaviolasitrovaalivello"2"allorac'èunordineshortincorso
ifCondizioneAperturaShortandstrategy.position_size>=0//andhaiUnoShortAncoraAperto==false
strategy.entry("Andale",strategy.short,alert_message=webhookShort,comment="OPENSHORT")
ifstrategy.position_size<0//andsonPassateLeBarreD//andCondizioneChiusuraLong
ifsiamoindowntrend==trueandsonPassateLeBarreDs
strategy.close("Andale",alert_message=webhookClose,comment="CLOSESHORT")
elseifsiamoindowntrend==falseandCondizioneChiusuraShort
strategy.close("Andale",alert_message=webhookClose,comment="CLOSESHORT")
ifstrategy.position_size<0andsiamoindata
strategy.exit("Andale",stop=stop_level_short,limit=take_level_short,alert_message=webhookClose,comment="CLOSESHORT(LIMIT/STOP)")
Expand (208 lines)
