Script Name: Money Flow Index 5 min Strategy
Author: tweakerID
Description: 1 - Apply the 3 period Money Flow Index indicator to the 5 minute chart, using 0 and 100 as our oversold and overbought boundaries
2 - Wait for the MFI to reach overbought levels, that indicates the presence of "big sharks" in the market. Price needs to hold up
the first two MFI overbought occurrences of the day to be considered as a bullish entry signal.*
3 - We...
PineScript code:

Pine Script™ strategy
Money Flow Index 5 min Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  From  "Crypto  Day  Trading  Strategy"  PDF  file.
//  *  I'm  using  a  SMA  filter  to  avoid  buying  when  the  price  is  declining.  Time  frame  was  better  at  15  min  according  to  my  test.
//  1  -  Apply  the  3  period  Money  Flow  Index  indicator  to  the  5  minute  chart,  using  0  and  100  as  our  oversold  and  overbought  boundaries
//  2  -  Wait  for  the  MFI  to  reach  overbought  levels,  that  indicates  the  presence  of  "big  sharks"  in  the  market.  Price  needs  to  hold  up
//  the  first  two  MFI  overbought  occurrences  of  the  day  to  be  considered  as  a  bullish  entry  signal.*
//  3  -  We  buy  when  the  MFI  =  100  and  the  next  candle  is  a  bullish  candle  with  short  wicks.
//  4  -  We  place  our  Stop  Loss  below  the  low  of  the  trading  day  and  we  Take  Profit  during  the  first  60  minutes  after  taking  the  trade.
//  The  logic  above  can  be  used  in  a  mirrored  fashion  to  take  short  entries,  this  is  a  custom  parameter  that  can  be  modified  from
//  the  strategy  Inputs  panel.
//  ©  tweakerID
//@version=4
strategy("Money  Flow  Index  5  min  Strategy",
          overlay=true,
          default_qty_type=strategy.percent_of_equity,
          default_qty_value=100,
          initial_capital=10000,
          commission_value=0.04,
          calc_on_every_tick=false,
          slippage=0)
direction  =  input(0,  title  =  "Strategy  Direction",  type=input.integer,  minval=-1,  maxval=1)
strategy.risk.allow_entry_in(direction  ==  0  ?  strategy.direction.all  :  (direction  <  0  ?  strategy.direction.short  :  strategy.direction.long))
///////////////////////  STRATEGY  INPUTS  ////////////////////////////////////////
title1=input(true,  "-----------------Strategy  Inputs-------------------")
i_MFI  =  input(3,  title="MFI  Length")
OB=input(100,  title="Overbought  Level")
OS=input(0,  title="Oversold  Level")
barsizeThreshold=input(.5,  step=.05,  minval=.1,  maxval=1,title="BarBodySize,1=NoWicks")
i_MAFilter=input(true,title="UseMATrendFilter")
i_MALen=input(80,title="MALength")
i_timedexit=input(false,title="Use60minutesexitrule")
short=input(true,title="UseMirroredlogicforShorts")
///////////////////////BACKTESTER/////////////////////////////////////////////
title2=input(true,"-----------------GeneralInputs-------------------")
//BacktesterGeneralInputs
i_SL=input(true,title="UseStopLossandTakeProfit")
i_SLType=input(defval="StrategyStop",title="TypeOfStop",options=["StrategyStop","SwingLo/Hi","ATRStop"])
i_SPL=input(defval=10,title="SwingPointLookback")
i_PercIncrement=input(defval=3,step=.1,title="SwingPointSLPercIncrement")*0.01
i_ATR=input(14,title="ATRLength")
i_ATRMult=input(5,step=.1,title="ATRMultiple")
i_TPRRR=input(2.2,step=.1,title="TakeProfitRiskRewardRatio")
TS=input(false,title="TrailingStop")
//BoughtandSoldBooleanSignal
bought=strategy.position_size>strategy.position_size[1]
orstrategy.position_size<strategy.position_size[1]
//PriceActionStopandTakeProfit
LL=(lowest(i_SPL))*(1-i_PercIncrement)
HH=(highest(i_SPL))*(1+i_PercIncrement)
LL_price=valuewhen(bought,LL,0)
HH_price=valuewhen(bought,HH,0)
entry_LL_price=strategy.position_size>0?LL_price:na
entry_HH_price=strategy.position_size<0?HH_price:na
tp=strategy.position_avg_price+(strategy.position_avg_price-entry_LL_price)*i_TPRRR
stp=strategy.position_avg_price-(entry_HH_price-strategy.position_avg_price)*i_TPRRR
//ATRStop
ATR=atr(i_ATR)*i_ATRMult
ATRLong=ohlc4-ATR
ATRShort=ohlc4+ATR
ATRLongStop=valuewhen(bought,ATRLong,0)
ATRShortStop=valuewhen(bought,ATRShort,0)
LongSL_ATR_price=strategy.position_size>0?ATRLongStop:na
ShortSL_ATR_price=strategy.position_size<0?ATRShortStop:na
ATRtp=strategy.position_avg_price+(strategy.position_avg_price-LongSL_ATR_price)*i_TPRRR
ATRstp=strategy.position_avg_price-(ShortSL_ATR_price-strategy.position_avg_price)*i_TPRRR
//StrategyStop
DayStart=time==timestamp("UTC",year,month,dayofmonth,0,0,0)
plot(DayStart?1e9:na,style=plot.style_columns,color=color.silver,transp=80,title="TradeDayStart")
floatLongStop=valuewhen(DayStart,low,0)*(1-i_PercIncrement)
floatShortStop=valuewhen(DayStart,high,0)*(1+i_PercIncrement)
floatStratTP=strategy.position_avg_price+(strategy.position_avg_price-LongStop)*i_TPRRR
floatStratSTP=strategy.position_avg_price-(ShortStop-strategy.position_avg_price)*i_TPRRR
///////////////////////STRATEGYLOGIC/////////////////////////////////////////
MFI=mfi(close,i_MFI)
barsize=high-low
barbodysize=close>open?(open-close)*-1:(open-close)
shortwicksbar=barbodysize>barsize*barsizeThreshold
SMA=sma(close,i_MALen)
MAFilter=close>SMA
timesinceentry=(time-valuewhen(bought,time,0))/60000
timedexit=timesinceentry==60
BUY=MFI[1]==OBandclose>openandshortwicksbarand(i_MAFilter?MAFilter:true)
boolSELL=na
ifshort
SELL:=MFI[1]==OSandclose<openandshortwicksbarand(i_MAFilter?notMAFilter:true)
//DebuggingPlots
plot(timesinceentry,transp=100,title="TimeSinceEntry")
//TradingInputs
DPR=input(true,"AllowDirectPositionReverse")
reverse=input(false,"ReverseTrades")
//Entries
ifreverse
ifnotDPR
strategy.entry("long",strategy.long,when=SELLandstrategy.position_size==0)
strategy.entry("short",strategy.short,when=BUYandstrategy.position_size==0)
else
strategy.entry("long",strategy.long,when=SELL)
strategy.entry("short",strategy.short,when=BUY)
else
ifnotDPR
strategy.entry("long",strategy.long,when=BUYandstrategy.position_size==0)
strategy.entry("short",strategy.short,when=SELLandstrategy.position_size==0)
else
strategy.entry("long",strategy.long,when=BUY)
strategy.entry("short",strategy.short,when=SELL)
ifi_timedexit
strategy.close_all(when=timedexit)
SL=i_SLType=="SwingLo/Hi"?entry_LL_price:i_SLType=="ATRStop"?LongSL_ATR_price:LongStop
SSL=i_SLType=="SwingLo/Hi"?entry_HH_price:i_SLType=="ATRStop"?ShortSL_ATR_price:ShortStop
TP=i_SLType=="SwingLo/Hi"?tp:i_SLType=="ATRStop"?ATRtp:StratTP
STP=i_SLType=="SwingLo/Hi"?stp:i_SLType=="ATRStop"?ATRstp:StratSTP
//TrailingStop
dif=(valuewhen(strategy.position_size>0andstrategy.position_size[1]<=0,high,0))
-strategy.position_avg_price
trailOffset=strategy.position_avg_price-SL
vartstop=float(na)
ifstrategy.position_size>0
tstop:=high-trailOffset-dif
iftstop<tstop[1]
tstop:=tstop[1]
else
tstop:=na
StrailOffset=SSL-strategy.position_avg_price
varStstop=float(na)
Sdif=strategy.position_avg_price-(valuewhen(strategy.position_size<0
andstrategy.position_size[1]>=0,low,0))
ifstrategy.position_size<0
Ststop:=low+StrailOffset+Sdif
ifStstop>Ststop[1]
Ststop:=Ststop[1]
else
Ststop:=na
strategy.exit("TP&SL","long",limit=TP,stop=TS?tstop:SL,when=i_SL)
strategy.exit("TP&SL","short",limit=STP,stop=TS?Ststop:SSL,when=i_SL)
///////////////////////PLOTS//////////////////////////////////////////////////
plot(i_SLandstrategy.position_size>0andnotTS?SL:i_SLandstrategy.position_size>0andTS?tstop:na,title='SL',style=plot.style_cross,color=color.red)
plot(i_SLandstrategy.position_size<0andnotTS?SSL:i_SLandstrategy.position_size<0andTS?Ststop:na,title='SSL',style=plot.style_cross,color=color.red)
plot(i_SLandstrategy.position_size>0?TP:na,title='TP',style=plot.style_cross,color=color.green)
plot(i_SLandstrategy.position_size<0?STP:na,title='STP',style=plot.style_cross,color=color.green)
//Drawpriceactionsetuparrows
plotshape(BUY?1:na,style=shape.triangleup,location=location.belowbar,
color=color.green,title="BullishSetup",size=size.auto)
plotshape(SELL?1:na,style=shape.triangledown,location=location.abovebar,
color=color.red,title="BearishSetup",size=size.auto)

Expand (175 lines)
