Script Name: Moon Phases Strategy 2015 till 2021
Author: Joy_Bangla
Description: Moon Phases Strategy

Thank you to Author: Dustin Drummond for allowing me to use his Moon Phase strategy code and modify it. I wanted to test out the accuracy of the moon phase. And I could not have done it without his code

It was created to test the Moon Phase theory compared to just a buy and hold strategy.
It buys on full Moon and sells on the new moon. I...
PineScript code:

Pine Script™ strategy
Moon Phases Strategy 2015 till 2021
//This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//@version=4
//  Author:  Joy  Bangla
//  Full  credit  goes  to  Author:  Dustin  Drummond  https://www.tradingview.com/u/Dustin_D_RLT/
//  He  has  allowed  me  to  use  his  Moon  Phase  strategy  code  and  modify  it.
//  Thank  you  Dustin  Drummond  for  allowing  me.  I  really  wanted  to  test  out  accuracy  of  moon  phase.  And  I  could  not  done  it
//  without  your  code
//Simple  Moon  Phases  Strategy
//It  was  created  to  test  the  Moon  Phase  theory  compared  to  just  a  buy  and  hold  strategy.
//  It  buy  on  full  Moon  and  sell  on  new  Moon.
//  I  also  have  added  ability  to  add  stop  loss  and  target  profit  if  anyone  wants  to  tinker  with  it.
//This  strategy  uses  hard-coded  dates  from  1/1/2015  until  12/31/2021  only!
//Any  dates  outside  of  that  range  need  to  be  added  manually  in  the  code  or  it  will  not  work.
//I  may  or  may  not  update  this  so  please  don't  be  upset  if  it  stops  working  after  12/31/2021.
//Feel  free  to  use  any  part  of  this  code  and  please  let  me  know  if  you  can  improve  on  this  strategy.
strategy(title="Moon  Phases  Strategy  2015  till  2021",  shorttitle  =  "Moon  Phases  Strategy",  overlay  =  true,  calc_on_every_tick=true,  default_qty_value=100,  initial_capital  =  100000,  default_qty_type=strategy.percent_of_equity,  pyramiding  =  0,  process_orders_on_close=false)
//Define  Full  Moons  and  New  Moons  per  year  (idetifies  1  day  prior  so  order  entry  can  be  on  open  of  next  day)
fullMoon2015  =  year  ==  2015  and  ((month  ==  1  and  dayofmonth  ==  2)  or  (month  ==  2  and  dayofmonth  ==  3)  or  (month  ==  3  and  dayofmonth  ==  5)  or  (month  ==  4  and  dayofmonth  ==  2)  or  (month  ==  5  and  dayofmonth  ==  1)  or  (month  ==  6  and  dayofmonth  ==  2)  or  (month  ==  7  and  dayofmonth  ==  1)  or  (month  ==  7  and  dayofmonth  ==  30)  or  (month  ==  8  and  dayofmonth  ==  28)  or  (month  ==  9  and  dayofmonth  ==  25)  or  (month  ==  10  and  dayofmonth  ==  26)  or  (month  ==  11  and  dayofmonth  ==  25)  or  (month  ==  12  and  dayofmonth  ==  24))  ?  1  :  na
newMoon2015  =  year  ==  2015  and  ((month  ==  1  and  dayofmonth  ==  16)  or  (month  ==  2  and  dayofmonth  ==  18)  or  (month  ==  3  and  dayofmonth  ==  19)  or  (month  ==  4  and  dayofmonth  ==  17)  or  (month  ==  5  and  dayofmonth  ==  15)  or  (month  ==  6  and  dayofmonth  ==  16)  or  (month  ==  7  and  dayofmonth  ==  15)  or  (month  ==  8  and  dayofmonth  ==  14)  or  (month  ==  9  and  dayofmonth  ==  11)  or  (month  ==  10  and  dayofmonth  ==  12)  or  (month  ==  11  and  dayofmonth  ==  11)  or  (month  ==  12  and  dayofmonth  ==  10))  ?  1  :  na
fullMoon2016  =  year  ==  2016  and  ((month  ==  1  and  dayofmonth  ==  22)  or  (month  ==  2  and  dayofmonth  ==  22)  or  (month  ==  3  and  dayofmonth  ==  22)  or  (month  ==  4  and  dayofmonth  ==  21)  or  (month  ==  5  and  dayofmonth  ==  20)  or  (month  ==  6  and  dayofmonth  ==  17)  or  (month  ==  7  and  dayofmonth  ==  19)  or  (month  ==  8  and  dayofmonth  ==  17)  or  (month  ==  9  and  dayofmonth  ==  16)  or  (month  ==  10  and  dayofmonth  ==  14)  or  (month  ==  11  and  dayofmonth  ==  11)  or  (month  ==  12  and  dayofmonth  ==  13))  ?  1  :  na
newMoon2016  =  year  ==  2016  and  ((month  ==  1  and  dayofmonth  ==  8)  or  (month  ==  2  and  dayofmonth  ==  8)  or  (month  ==  3  and  dayofmonth  ==  8)  or  (month  ==  4  and  dayofmonth  ==  6)  or  (month  ==  5  and  dayofmonth  ==  6)  or  (month  ==  6  and  dayofmonth  ==  3)  or  (month  ==  7  and  dayofmonth  ==  1)  or  (month  ==  8  and  dayofmonth  ==  2)  or  (month  ==  8  and  dayofmonth  ==  31)  or  (month  ==  9  and  dayofmonth  ==  30)  or  (month  ==  10  and  dayofmonth  ==  28)  or  (month  ==  11  and  dayofmonth  ==  28)  or  (month  ==  12  and  dayofmonth  ==  28))  ?  1  :  na
fullMoon2017  =  year  ==  2017  and  ((month  ==  1  and  dayofmonth  ==  11)  or  (month  ==  2  and  dayofmonth  ==  10)  or  (month  ==  3  and  dayofmonth  ==  10)  or  (month  ==  4  and  dayofmonth  ==  10)  or  (month  ==  5  and  dayofmonth  ==  10)  or  (month  ==  6  and  dayofmonth  ==  8)  or  (month  ==  7  and  dayofmonth  ==  7)  or  (month  ==  8  and  dayofmonth  ==  7)  or  (month  ==  9  and  dayofmonth  ==  5)  or  (month  ==  10  and  dayofmonth  ==  5)  or  (month  ==  11  and  dayofmonth  ==  3)  or  (month  ==  12  and  dayofmonth  ==  1)  or  (month  ==  12  and  dayofmonth  ==  29))  ?  1  :  na
newMoon2017  =  year  ==  2017  and  ((month  ==  1  and  dayofmonth  ==  27)  or  (month  ==  2  and  dayofmonth  ==  24)  or  (month  ==  3  and  dayofmonth  ==  27)  or  (month  ==  4  and  dayofmonth  ==  25)  or  (month  ==  5  and  dayofmonth  ==  25)  or  (month  ==  6  and  dayofmonth  ==  23)  or  (month  ==  7  and  dayofmonth  ==  21)  or  (month  ==  8  and  dayofmonth  ==  21)  or  (month  ==  9  and  dayofmonth  ==  19)  or  (month  ==  10  and  dayofmonth  ==  19)  or  (month  ==  11  and  dayofmonth  ==  17)  or  (month  ==  12  and  dayofmonth  ==  15))  ?  1  :  na
fullMoon2018  =  year  ==  2018  and  ((month  ==  1  and  dayofmonth  ==  30)  or  (month  ==  3  and  dayofmonth  ==  1)  or  (month  ==  3  and  dayofmonth  ==  29)  or  (month  ==  4  and  dayofmonth  ==  27)  or  (month  ==  5  and  dayofmonth  ==  29)  or  (month  ==  6  and  dayofmonth  ==  27)  or  (month  ==  7  and  dayofmonth  ==  27)  or  (month  ==8anddayofmonth==24)or(month==9anddayofmonth==24)or(month==10anddayofmonth==24)or(month==11anddayofmonth==21)or(month==12anddayofmonth==21))?1:na
newMoon2018=year==2018and((month==1anddayofmonth==16)or(month==2anddayofmonth==15)or(month==3anddayofmonth==16)or(month==4anddayofmonth==13)or(month==5anddayofmonth==14)or(month==6anddayofmonth==13)or(month==7anddayofmonth==12)or(month==8anddayofmonth==10)or(month==9anddayofmonth==7)or(month==10anddayofmonth==8)or(month==11anddayofmonth==7)or(month==12anddayofmonth==6))?1:na
fullMoon2019=year==2019and((month==1anddayofmonth==18)or(month==2anddayofmonth==19)or(month==3anddayofmonth==20)or(month==4anddayofmonth==18)or(month==5anddayofmonth==17)or(month==6anddayofmonth==14)or(month==7anddayofmonth==16)or(month==8anddayofmonth==14)or(month==9anddayofmonth==13)or(month==10anddayofmonth==11)or(month==11anddayofmonth==11)or(month==12anddayofmonth==11))?1:na
newMoon2019=year==2019and((month==1anddayofmonth==4)or(month==2anddayofmonth==4)or(month==3anddayofmonth==6)or(month==4anddayofmonth==4)or(month==5anddayofmonth==3)or(month==5anddayofmonth==31)or(month==7anddayofmonth==2)or(month==7anddayofmonth==31)or(month==8anddayofmonth==29)or(month==9anddayofmonth==27)or(month==10anddayofmonth==25)or(month==11anddayofmonth==26)or(month==12anddayofmonth==24))?1:na
fullMoon2020=year==2020and((month==1anddayofmonth==10)or(month==2anddayofmonth==7)or(month==3anddayofmonth==9)or(month==4anddayofmonth==7)or(month==5anddayofmonth==6)or(month==6anddayofmonth==5)or(month==7anddayofmonth==2)or(month==8anddayofmonth==3)or(month==9anddayofmonth==1)or(month==10anddayofmonth==1)or(month==10anddayofmonth==30)or(month==11anddayofmonth==27)or(month==12anddayofmonth==29))?1:na
newMoon2020=year==2020and((month==1anddayofmonth==24)or(month==2anddayofmonth==21)or(month==3anddayofmonth==23)or(month==4anddayofmonth==22)or(month==5anddayofmonth==22)or(month==6anddayofmonth==19)or(month==7anddayofmonth==20)or(month==8anddayofmonth==18)or(month==9anddayofmonth==16)or(month==10anddayofmonth==16)or(month==11anddayofmonth==13)or(month==12anddayofmonth==14))?1:na
fullMoon2021=year==2021and((month==1anddayofmonth==28)or(month==2anddayofmonth==26)or(month==3anddayofmonth==26)or(month==4anddayofmonth==26)or(month==5anddayofmonth==25)or(month==6anddayofmonth==24)or(month==7anddayofmonth==23)or(month==8anddayofmonth==20)or(month==9anddayofmonth==20)or(month==10anddayofmonth==20)or(month==11anddayofmonth==18)or(month==12anddayofmonth==17))?1:na
newMoon2021=year==2021and((month==1anddayofmonth==12)or(month==2anddayofmonth==11)or(month==3anddayofmonth==12)or(month==4anddayofmonth==9)or(month==5anddayofmonth==11)or(month==6anddayofmonth==9)or(month==7anddayofmonth==9)or(month==8anddayofmonth==6)or(month==9anddayofmonth==6)or(month==10anddayofmonth==5)or(month==11anddayofmonth==4)or(month==12anddayofmonth==3))?1:na
//AllFullandNewMoons
fullMoon=fullMoon2015orfullMoon2016orfullMoon2017orfullMoon2018orfullMoon2019orfullMoon2020orfullMoon2021
newMoon=newMoon2015ornewMoon2016ornewMoon2017ornewMoon2018ornewMoon2019ornewMoon2020ornewMoon2021
//PlotFullandNewMoons(offset1bartomakeupfor1daypriorcalculation)
plotshape(fullMoon,"FullMoon",shape.circle,location.belowbar,color.new(color.lime,10),offset=1,size=size.normal)
plotshape(newMoon,"NewMoon",shape.circle,location.abovebar,color.new(color.red,10),offset=1,size=size.normal)
//STRATEGY
//===INPUTBACKTESTRANGE===
fromMonth=input(defval=1,title="FromMonth",type=input.integer,minval=1,maxval=12)
fromDay=input(defval=1,title="FromDay",type=input.integer,minval=1,maxval=31)
fromYear=input(defval=2015,title="FromYear",type=input.integer,minval=2015,maxval=2030)
thruMonth=input(defval=12,title="ThruMonth",type=input.integer,minval=1,maxval=11)
thruDay=input(defval=30,title="ThruDay",type=input.integer,minval=1,maxval=30)
thruYear=input(defval=2022,title="ThruYear",type=input.integer,minval=1900,maxval=2030)
//===INPUTSHOWPLOT===
showDate=input(defval=true,title="ShowDateRange",type=input.bool)
//===FUNCTIONEXAMPLE===
start=timestamp(fromYear,fromMonth,fromDay,00,00)//backteststartwindow
finish=timestamp(thruYear,thruMonth,thruDay,23,59)//backtestfinishwindow
window()=>time>=startandtime<=finish?true:false//createfunction"withinwindowoftime"
longLossPerc=input(title="LongStopLoss(%)",minval=0.0,step=0.1,defval=9)*0.01
shortLossPerc=input(title="ShortStopLoss(%)",minval=0.0,step=0.1,defval=9)*0.01
//Determinestoplossprice
longStopPrice=strategy.position_avg_price*(1-longLossPerc)
shortStopPrice=strategy.position_avg_price*(1+shortLossPerc)
testLongOnly=input(true,"TestLongOnly")
testShortOnly=input(true,"TestShortONly")
if(window()andtestLongOnly)
strategy.entry("buy",strategy.long,when=fullMoon)
strategy.close_all(when=newMoon)
if(window()andtestShortOnly)
strategy.entry("sell",strategy.short,when=newMoon)
strategy.close_all(when=fullMoon)
useLongSL=input(false,"UseLongSL")
useShorSL=input(false,"UseShortSL")
//Submitexitordersbasedoncalculatedstoplossprice
if(strategy.position_size>0anduseLongSL)
strategy.exit(id="XLSTP",stop=longStopPrice)
//Submitexitordersbasedoncalculatedstoplossprice
if(strategy.position_size<0anduseShorSL)
strategy.exit(id="XSSTP",stop=shortStopPrice)
Expand (90 lines)
