Script Name: Moving Average Band - Taylor V1
Author: TaylorTneh
Description: A Very Simple Strategy From Moving Average
- Price Breakout Upper Band = Long
- Price Breakout Lower Band = Short

Moving Average Type = Able to Change RMA, EMA, SMA, WMA
Moving Average Period = Able to Change
Upper Band & Lower Band Gap = Able to Change
With Stop Lose & Take Profit = Able to Change
PineScript code:

Pine Script™ strategy
Moving Average Band - Taylor V1
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  TaylorTneh
//@version=4
strategy("Moving  Average  Band  Taylor  V1",shorttitle="MA  Band+",overlay=true,default_qty_type=strategy.cash,default_qty_value=1000,initial_capital=1000,currency=currency.USD,commission_value=.1)
price  =  input(close,  title="Source")
mabtype  =  input(title="Moving  Average  Type",  defval="RMA",  options=["SMA",  "EMA",  "RMA",  "WMA"])
malen  =  input(10,  "MA  Period  :  10")
magap  =  input(0.6,  "Band  Gap  :  0.6",  minval  =  -10,  maxval  =  10,  step  =  0.1)
mabup  =  if  mabtype  ==  "SMA"
        sma(high,  malen)
else
        if  mabtype  ==  "EMA"
                ema(high,  malen)
        else
                if  mabtype  ==  "WMA"
                        wma(high,  malen)
                else
                        if  mabtype  ==  "RMA"
                                rma(high,  malen)

mabdn  =  if  mabtype  ==  "SMA"
        sma(low,  malen)
else
        if  mabtype  ==  "EMA"
                ema(low,  malen)
        else
                if  mabtype  ==  "WMA"
                        wma(low,  malen)
                else
                        if  mabtype  ==  "RMA"
                                rma(low,  malen)

upex=mabup*(1+magap/100)
dnex=mabdn*(1-magap/100)
plot(upex,"UpperMABand",color.orange)
plot(dnex,"LowerMABand",color.orange)
//--------------------------------------------(Strategy)
strategy.entry("Long",strategy.long,stop=upex)
strategy.entry("Short",strategy.short,stop=dnex)
//LongOnly//strategy.entry("Long",strategy.long,stop=upex)
//LongOnly//strategy.exit("Short",stop=dnex)
//ShortOnly//strategy.entry("Short",strategy.short,stop=dnex)
//ShortOnly//strategy.exit("Long",stop=upex)
//--------------------------------------------(TakeProfit&StopLose)
stopPer=input(500.0,title='#StopLoss%',type=input.float)/100
takePer=input(500.0,title='#TakeProfit%',type=input.float)/100
//Determinewhereyou'veenteredandinwhatdirection
longStop=strategy.position_avg_price*(1-stopPer)
shortStop=strategy.position_avg_price*(1+stopPer)
shortTake=strategy.position_avg_price*(1-takePer)
longTake=strategy.position_avg_price*(1+takePer)
ifstrategy.position_size>0
strategy.exit(id="L-TP/SL",stop=longStop,limit=longTake)
ifstrategy.position_size<0
strategy.exit(id="S-TP/SL",stop=shortStop,limit=shortTake)
//--------------------------------------------(SampleTimeFilterStrategy)
//fromyear=input(2018,defval=1900,minval=1900,maxval=2100,title="FromYear")
//toyear=input(2100,defval=2100,minval=1900,maxval=2100,title="ToYear")
//frommonth=input(01,defval=01,minval=01,maxval=12,title="FromMonth")
//tomonth=input(10,defval=10,minval=01,maxval=12,title="ToMonth")
//fromday=input(01,defval=01,minval=01,maxval=31,title="Fromday")
//today=input(31,defval=31,minval=01,maxval=31,title="Today")
//strategy.entry("Long",strategy.long,stop=upex,when=(time>timestamp(fromyear,frommonth,fromday,00,00)andtime<timestamp(toyear,tomonth,today,23,59)))
//strategy.entry("Short",strategy.short,stop=dnex,when=(time>timestamp(fromyear,frommonth,fromday,00,00)andtime<timestamp(toyear,tomonth,today,23,59)))
//--------------------------------------------
Expand (74 lines)
