Script Name: Moving Average, T3 and Bollinger Strategy
Author: Traaaderz
Description: This strategy uses a SMA much like an the faster EMA in many oscillators and the T3 average of the same period as the intermediate trend. Exits are defined by encounters with the Bollinger Band. The long term trend is defined by T3 moving averages of an even longer period.
PineScript code:

Pine Script™ strategy
Moving Average, T3 and Bollinger Strategy
//@version=4
strategy(shorttitle="BB  T3  Strategy",  title="BB  T3  Strategy",  overlay=true)
//T3
b  =  0.7
c1  =  -b*b*b
c2  =  3*b*b+3*b*b*b
c3  =  -6*b*b-3*b-3*b*b*b
c4  =  1+3*b+b*b*b+3*b*b
t3(len)  =>  c1  *  ema(ema(ema(ema(ema(ema(close,  len),  len),  len),  len),  len),  len)  +  c2  *  ema(ema(ema(ema(ema(close,  len),  len),  len),  len),  len)  +  c3  *  ema(ema(ema(ema(close,  len),  len),  len),  len)  +  c4  *  ema(ema(ema(close,  len),  len),  len)
//T3  end
length  =  input(20,  minval=1)
mult  =  input(2.5,  minval=0.001,  maxval=50,  title="StdDev")
basis  =  t3(length)
basisDev  =  t3(length/10)
dev  =  mult  *  stdev(basisDev,length)
upper  =  basis  +  dev
lower  =  basis  -  dev
offset  =  input(0,  "Offset",  type  =  input.integer,  minval  =  -500,  maxval  =  500)
plot(basis,  "Basis",  color=#872323,  offset  =  offset)
p1  =  plot(upper,  "Upper",  color=color.teal,  offset  =  offset)
p2  =  plot(lower,  "Lower",  color=color.teal,  offset  =  offset)
fill(p1,  p2,  title  =  "Background",  color=#198787,  transp=95)
stoploss  =  input(true,  "Stop  Loss")
basisSma  =  sma(close,  length)
p3  =  plot(basisSma,  color=color.blue,  title="MA",  offset=offset)
fastT3  =  t3(50)
slowT3  =  t3(200)
crossUp  =  crossover(basisSma,  basis)
crossDown  =  crossunder(basisSma,  basis)
bollBounce  =  crossover(close,  upper)
bollReject  =  crossunder(close,  lower)
underBasis  =  crossunder(close,  basis)
overBasis  =  crossover(close,  basis)
trendUp  =  fastT3  >  slowT3
trendDown  =  fastT3  <  slowT3
strategy.entry("long",  strategy.long,  when=(trendUp  and  crossUp),  stop=(stoploss  ?  high+syminfo.mintick  :  na))
strategy.close("long",  when=(bollBounce  or  crossDown  or  underBasis))
strategy.entry("short",  strategy.short,  when=(trendDown  and  crossDown),  stop=(stoploss  ?  low-syminfo.mintick  :  na))
strategy.close("short",  when=(bollReject  or  crossUp  or  overBasis))
Expand (51 lines)
