Script Name: Multi-X by HamidBox
Author: HamidBox
Description: Hello to All, introducing Multi Types Crossover strategy,
simply the best way of trading with Crossover and Crossunder Strategy, How it Works???
I added 5 types of Moving Averages,

1: Simple Moving Average ( SMA )
2: Exponential Moving Average ( EMA )
3: Weighted Moving Average ( WMA )
4: Volume Weighted Moving Average ( VWMA )
5: Relative Moving Average...
PineScript code:

Pine Script™ strategy
Multi-X by HamidBox
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  HAMIDBOX
//@version=4
strategy("Multi-X  for  BOT",  overlay=true,  default_qty_type=strategy.cash,  default_qty_value=100,  initial_capital=100,  currency='USD',  commission_value=0.1)
maType(source  ,  length,  type)      =>
        type        ==  "SMA"                        ?  sma(source  ,  length)    :
          type      ==  "EMA"                        ?  ema(source  ,  length)    :
          type      ==  "RMA"                        ?  rma(source,  length)      :
          type      ==  "WMA"                        ?  wma(source,  length)      :
          type      ==  "VWMA"                      ?  vwma(source,  length)    :
          na

////////////////////////////////////////////////////////////////////////////////
colorup                          =  #11ff00
colordn                          =  #e91e63
///////////////////////////  MOVING  AVERAGE  №1  INPUTS  ///////////////////////////
ma1_show                        =  input(title="MA  №1",  defval=true,  type=input.bool,  inline="ma1")
ma1type                          =  input(title="",  defval="EMA",  options=["SMA","EMA","RMA","WMA","VWMA"],  inline="ma1")
ma1src                          =input(title="",defval=close,type=input.source,inline="ma1")
ma1Len=input(title="",defval=9,type=input.integer,inline="ma1")
ma1col=input(colorup,"MA№1Line ",type=input.color,inline="maz1")
ma1_zon=input(color.new(color.lime,70),"   Zone    ",type=input.color,inline="maz1")
ma1_width=input(title="   Width   ",defval=2,type=input.integer,inline="maz1")
ma1=maType(ma1src,ma1Len,ma1type)
ma1p=plot(ma1_show?ma1:na,linewidth=ma1_width,color=color.new(ma1col,0))
///////////////////////////MOVINGAVERAGE№2INPUTS///////////////////////////
ma2_show=input(title="MA№2",defval=true,type=input.bool,inline="ma2")
ma2type=input(title="",defval="SMA",options=["SMA","EMA","RMA","WMA","VWMA"],inline="ma2")
ma2src=input(title="",defval=close,type=input.source,inline="ma2")
ma2Len=input(title="",defval=21,type=input.integer,inline="ma2")
ma2col=input(colordn,"MA№2Line ",type=input.color,inline="maz2")
ma2_zon=input(color.new(#e91e63,70),"   Zone    ",type=input.color,inline="maz2")
ma2_width=input(title="   Width   ",defval=2,type=input.integer,inline="maz2")
ma2=maType(ma2src,ma2Len,ma2type)
ma2p=plot(ma2_show?ma2:na,linewidth=ma2_width,color=color.new(ma2col,0))
///////////////////////////MOVINGAVERAGE№3INPUTS///////////////////////////
read=input(title="ForSafeSide=ReadThis>>>",defval=true,group="Movingaveragezonesection",tooltip="Ifyouwanttoplayonthesafeside,CheckONMovingAverage№3,MA№3showsthemajortrend,itsworkasaTrend-Zone,\nRule:DonotopentradesifthemarketisbelowMA№3,WHY?becauseTrendisBearishanditwillmakemoreDown,NOTE::ItispossibleafteraddingMA№3,itwillgiveyouasmallprofit.Butthegreatadvantageofthat,itwillreduceyourlossanditwillalsoincreaseyourProfitFactor.\nAndifyounothaveanyissuewithRiskthenyoucanLeaveMovingAverageNo3")
ma3_show=input(title="MA№3",defval=false,type=input.bool,inline="ma3",group="Movingaveragezonesection")
ma3type=input(title="",defval="SMA",options=["SMA","EMA","RMA","WMA","VWMA"],inline="ma3",group="Movingaveragezonesection")
//ma3srcH=input(title="",defval=high,type=input.source,inline="ma3")
//ma3srcL=input(title="",defval=low,type=input.source,inline="ma3")
ma3Len=input(title="",defval=50,type=input.integer,inline="ma3",group="Movingaveragezonesection")
ma3col=input(colordn,"",type=input.color,inline="ma3",group="Movingaveragezonesection")
zone_col_on=input(title="",defval=false,inline="ma3",group="Movingaveragezonesection")
ma3col_up=input(color.new(color.lime,70),"",type=input.color,inline="ma3",group="Movingaveragezonesection")
ma3col_dn=input(color.new(#e91e63,70),"",type=input.color,inline="ma3",group="Movingaveragezonesection")
ma3H=maType(high,ma3Len,ma3type)
ma3L=maType(low,ma3Len,ma3type)
ma3p=plot(ma3_show?ma3H:na,linewidth=1,color=color.new(ma3col,50))
ma3p2=plot(ma3_show?ma3L:na,linewidth=1,color=color.new(ma3col,50))
Bigcross_zone_color=ifzone_col_onandclose>ma3H
ma3col_up
else
ifzone_col_onandclose<ma3L
ma3col_dn
fill(ma3p,ma3p2,color=Bigcross_zone_color,title="CrossBackgroundColor")
BigCrossSignal=close>ma3H
ZoneCrossover=crossover(close,ma3H)
ZoneCrossunder=crossunder(close,ma3L)
////////////////////////////PLOTINGANDCOOLORING/////////////////////////////
Cross=input(true,"CrossSignON/OFF   |",inline="col",group="Movingaveragezonesection")
maCrossOver=crossover(ma1,ma2)
maCrossUnder=crossunder(ma1,ma2)
col_buy=input(title="UP",type=input.color,defval=color.white,inline="col",group="Movingaveragezonesection")
col_sell=input(title="DN",type=input.color,defval=#e91e63,inline="col",group="Movingaveragezonesection")
cross_zone_color=ma1>ma2?ma1_zon:ma2_zon
plotshape(Cross?maCrossOver:na,title="CrossUPSign",style=shape.triangleup,location=location.belowbar,color=col_buy,size=size.tiny)
plotshape(Cross?maCrossUnder:na,title="CrossDNSign",style=shape.xcross,location=location.abovebar,color=col_sell,size=size.tiny)
fill(ma1p,ma2p,color=cross_zone_color,title="CrossBackgroundColor")
//////////////////////////////////////////////////////////////////
backtest_on=input(false,"BackTestingON/OFF",group="BacktestingSection🕖🕔🕟🕤")
/////////////////////////////BACKTESTINGINPUTS//////////////////////////////
startTime=input(title="StartTime",type=input.time,defval=timestamp("01Jan2021"),group="BacktestingSection🕖🕔🕟🕤")
endTime=input(title="EndTime",type=input.time,defval=timestamp("01Jan2100"),group="BacktestingSection🕖🕔🕟🕤")
inDateRange=(time>=startTime)and(time<endTime)
/////////////////////////////////(CONDITIONS)/////////////////////////////////
bot_id=input(title="BOTID       ",defval='',inline="bot",group="BOTSECTION")
email_token=input(title="  Token",defval='',inline="bot",group="BOTSECTION")
enter_msg='{"message_type":"bot","bot_id":'+bot_id+',"email_token":"'+email_token+'","delay_seconds":0}'
exit_msg='{"message_type":"bot","bot_id":'+bot_id+',"email_token":"'+email_token+'","delay_seconds":0,"action":"close_at_market_price_all"}'
//COPYPASTETHISMSGTOTRADINGVIEW
//{{strategy.order.alert_message}}
/////////////////////////////////(CONDITIONS)/////////////////////////////////
ifmaCrossOverandinDateRangeandbacktest_onandma1_showandma2_show
strategy.entry("BUY",strategy.long,alert_message=enter_msg)
ifmaCrossUnderandinDateRangeandbacktest_onandma1_showandma2_show
strategy.close("BUY",comment="Exit",alert_message=exit_msg)
ifZoneCrossoverandbacktest_onandinDateRangeandma3_showandnotma1_showandnotma2_show
strategy.entry("BUYzone",strategy.long,alert_message=enter_msg)
ifZoneCrossunderandbacktest_onandinDateRangeandma3_show
strategy.close("BUYzone",comment="Exit",alert_message=exit_msg)
if(notinDateRange)
strategy.close_all()
Expand (133 lines)
