Script Name: Negroni MA & RSI Strategy, plus trade entry and SL-TP options
Author: RoyalNegroni
Description: I will start with the context, and some things to think about when using a strategy tool to back-test ideas.

CONTEXT
FIRST: This is derived from other people's work, but I honestly hadn't found a mixed indicator MA strategy tool that does what this now does.  If it is out there, apologies!!

This tool can help back-test various MA trends (SMA, EMA, HMA, VWMA); as...
PineScript code:

Pine Script™ strategy
Negroni MA & RSI Strategy, plus trade entry and SL/TP options
//@version=5
//  ***  USE  AT  YOUR  OWN  RISK  ***
//  FIRST:  This  is  MASSIVELY  derived  from  other  people's  work...
//  I  honestly  hadn't  found  a  mixed  indicator  MA  strategy  tool  that  does  what  this  now  does.    If  it  is  out  there,  apologies!!
//  This  tool  can  help  backtest  various  MA  trends;  can  factor  in  RSI  levels  (or  not);  and  can  factor  in  a  fixed  HTF  MA  (or  not).
//  You  can  apply  a  'retest  entry'  or  a  'breakout  entry',  and  you  can  apply  various  risk  mgt  for  SL/TP  orders  based  on:
//  1)  No  SL/TP  or  2)  a  fixed  %,  or  3)  dynamic  ATR  multipliers.
//  For  those  of  us  who  love  indicators  &  analysis,  and  make  no  money...  and  LOVE  every  day  of  it  :)
//  Thank  you,  tack,  salute!
strategy('Negroni  MA  &  RSI  Strategy',  shorttitle='Negroni  MA  &  RSI  Strategy',  overlay=true,  pyramiding=3,  default_qty_type=strategy.percent_of_equity,  default_qty_value=3,  initial_capital=100000)
//  ===  Inputs  ===
//
//  Retest  or  Breakout  Strategy
s1  =  input(true,  title='Retest  Entry  strategy',  group="Trade  entry  strategy",  tooltip  =  "RETEST  entry  strat:  price  crosses  UNDER  FastMA  INTO  the  'MA  trend  zone'.  CONFLUENCE  checks:  1)  Fast  MA  >  Trend  MA  >  SlowMA;  AND  2)  Price  (close)  is  above  fixed  HTF  MA;  AND  3)  RSI  is  above  your  chosen  level.  [and  vice  versa  for  shorts].  You  can  effectively  'disable'  confluence  checks  (see  info  tooltips  when  selecting  your  options).")
s2  =  input(false,  title='Breakout  Entry  strategy',  group="Trade  entry  strategy",  tooltip  =  "BREAKOUT  entry  strat:  price  crosses  OVER  FastMA  OUT  the  'MA  trend  zone'.  CONFLUENCE  checks:  1)  Fast  MA  >  Trend  MA  >  SlowMA;  AND  2)  Price  (close)  is  above  fixed  HTF  MA;  AND  3)  RSI  is  above  your  chosen  level.  [and  vice  versa  for  shorts].  You  can  effectively  'disable'  confluence  checks  (see  info  tooltips  when  selecting  your  options).")
//  Stop-loss  and  Take-profit  Inputs
v1  =  input(false,  title='Strat  1)  No  SL/TP',  group="Risk  Mgt  strategy",  tooltip  =  "Long  trades  are  closed  when  the  LOW  crosses  back  UNDER  the  fastMA  again,  and  shorts  are  closed  when  the  HIGH  crosses  back  OVER  the  fastMA  again.  (You  can  select  more  than  1  strategy.)")
v2  =  input(false,  title='Strat  2)  Static  %  SL/TP',  group="Risk  Mgt  strategy",  tooltip  =  "Your  SL/TP  will  be  a  fixed  %  away  from  avg.  position  price...  WARNING:  You  should  change  this  for  various  asset  classes;  FX  vol  is  not  the  same  as  crypto  altcoin  vol!  (You  can  select  more  than  1  strategy.)")
v3  =  input(true,  title='Strat  3)  Dynamic  ATR  SL/TP',  group="Risk  Mgt  strategy",  tooltip  =  "Your  SL/TP  is  a  multiple  of  your  selected  ATR  range  (default  is  50,  see  'info'  when  you  select  ATR  range).  ATR  accounts  for  the  change  in  vol  of  different  asset  classes  somewhat,  HOWEVER...  you  should  probably  still  not  have  the  same  multiplier  trading  S&P500  as  you  would  trading  crypto  altcoins!  (You  can  select  more  than  1  strategy.)")
v2stoploss_input  =  input.float(2.5,  title='2)  Fixed  Stop  Loss  %',  minval=0.01,  tooltip  =  "e.g.  Avg.  long  BTCUSDT  position  price  is  $23000,  and  SL  is  2.5%.  The  SL  price  is:  23000  x  (1-0.025)  =  $22425")  /  100
v2takeprofit_input  =  input.float(3.0,  title='2)  Fixed  Take  Profit  %',  minval=0.01,  tooltip  =  "e.g.  Avg.  long  BTCUSDT  position  price  is  $23000,  and  TP  is  3.0%.  The  TP  price  is:  23000  x  (1+0.030)  =  $23690")  /  100
atrLength=input.int(defval=50,  title=  '3)  ATR  Length',  minval=1,  tooltip  =  "Standard  ATR  length  is  usually  14,  however...  your  SL/TP  will  move  POST  entry,  and  can  tighten  or  widen  your  initial  SL/TP...  for  better  AND  usually  for  worse!  Find  a  trade  (strat  3)  on  the  chart,  look  at  the  SL/TP  lines,  now  change  the  number  to  5,  you'll  see.")
v3stoploss_input  =  input.float(defval=2.0,  title=  '3)  ATR  SL  Multiplier',  minval=1,  tooltip  =  "e.g.  Avg.  long  BTCUSDT  position  price  is  $23000,  and  ATR  SL  mutliplier  is  2.0.  Lets  say  ATR  is  200  on  this  day,  then  SL  price  is:  23000  -  (2  x  ATR)  =  $22600")
v3takeprofit_input  =  input.float(defval=2.5,  title=  '3)  ATR  TP  Multiplier',  minval=1,  tooltip  =  "e.g.  Avg.  long  BTCUSDT  position  price  is  $23000,  and  ATR  TP  mutliplier  is  2.5.  Lets  say  ATR  is  200  on  this  day,  then  TP  price  is:  23000  +  (2.5  x  ATR)  =  $23500")
longv2stoploss_level  =  strategy.position_avg_price  *  (1  -  v2stoploss_input)
longv2takeprofit_level  =  strategy.position_avg_price  *  (1  +  v2takeprofit_input)
shortv2stoploss_level  =  strategy.position_avg_price  *  (1  +  v2stoploss_input)
shortv2takeprofit_level  =  strategy.position_avg_price  *  (1  -  v2takeprofit_input)
longv3stoploss_level  =  strategy.position_avg_price  -  (v3stoploss_input*(ta.atr(atrLength)))
longv3takeprofit_level  =  strategy.position_avg_price  +  (v3takeprofit_input*(ta.atr(atrLength)))
shortv3stoploss_level  =  strategy.position_avg_price  +  (v3stoploss_input*(ta.atr(atrLength)))
shortv3takeprofit_level  =  strategy.position_avg_price  -  (v3takeprofit_input*(ta.atr(atrLength)))
//  Plots  both  long  and  short  SL  and  TP  lines  (I  wasn't  good  enough  to  make  this  only  plot  the  SL/TP  conditional  on  theentry:()
plot(v2andv2stoploss_inputandlongv2stoploss_level?longv2stoploss_level:na,title='Strat2)longSL',color=color.new(#e7f6e9,40),style=plot.style_linebr,linewidth=2,title='v2longStoploss')
plot(v2andv2takeprofit_input?longv2takeprofit_level:na,title='Strat2)longTP',color=color.new(#e7f6e9,40),style=plot.style_linebr,linewidth=2,title='v2longProfit')
plot(v2andv2stoploss_inputandshortv2stoploss_level?shortv2stoploss_level:na,title='Strat2)shortSL',color=color.new(#ebf951,40),style=plot.style_linebr,linewidth=2,title='v2shortStoploss')
plot(v2andv2takeprofit_input?shortv2takeprofit_level:na,title='Strat2)shortTP',color=color.new(#ebf951,40),style=plot.style_linebr,linewidth=2,title='v2shortProfit')
plot(v3andv3stoploss_inputandlongv3stoploss_level?longv3stoploss_level:na,title='Strat3)longSL',color=color.new(#e7f6e9,40),style=plot.style_linebr,linewidth=2,title='v3longStoploss')
plot(v3andv3takeprofit_input?longv3takeprofit_level:na,title='Strat3)longTP',color=color.new(#e7f6e9,40),style=plot.style_linebr,linewidth=2,title='v3longProfit')
plot(v3andv3stoploss_inputandshortv3stoploss_level?shortv3stoploss_level:na,title='Strat3)shortSL',color=color.new(#ebf951,40),style=plot.style_linebr,linewidth=2,title='v3shortStoploss')
plot(v3andv3takeprofit_input?shortv3takeprofit_level:na,title='Strat3)shortTP',color=color.new(#ebf951,40),style=plot.style_linebr,linewidth=2,title='v3shortProfit')
//RSI
rsiLength=input.int(defval=14,title='RSIlength',minval=1,group="RSIoptions")
rsiBuyLevel=input.int(defval=55,title='RSIBuysignal',minval=1,group="RSIoptions",tooltip="RSIoversoldlevelsareusually20-30,somelikeusing50assupport.Ifyoudon'tcareforRSIlevels,thensetbuysignalat1...i.ealwaysbuys!")
rsiSellLevel=input.int(defval=45,title='RSISellsignal',minval=1,group="RSIoptions",tooltip="RSIoverboughtlevelsareusually70-80,somelikeusing50asresistance.Ifyoudon'tcareforRSIlevels,thensetsellsignalat99...i.ealwayssells!")
src=close
up=ta.rma(math.max(ta.change(src),0),rsiLength)
down=ta.rma(-math.min(ta.change(src),0),rsiLength)
rsi=down==0?100:up==0?0:100-100/(1+up/down)
/////Movingaveragetypesandvariables////////
//FastMA
fastMAtype=input.string(title='FastMAType',defval='EMA',options=['EMA','SMA','VWMA','HMA'],group="FastMAoptions",tooltip="The'FastMA'and'TrendMA'willformtheMAzonefromwhichyourentrieswilltrigger.")
maFastSource=input(defval=close,title='FastMASource',group="FastMAoptions")
maFastLength=input.int(defval=13,title='FastMAPeriod',minval=1,group="FastMAoptions")
fastMA=fastMAtype=='EMA'?ta.ema(maFastSource,maFastLength):fastMAtype=='SMA'?ta.sma(maFastSource,maFastLength):fastMAtype=='VWMA'?ta.vwma(maFastSource,maFastLength):ta.hma(maFastSource,maFastLength)
//TrendMA
trendMAtype=input.string(title='TrendMAType',defval='EMA',options=['EMA','SMA','VWMA','HMA'],group="TrendMAoptions",tooltip="The'FastMA'and'TrendMA'willformtheMAzonefromwhichyourentrieswilltrigger.")
maTrendSource=input(defval=close,title='TrendMASource',group="TrendMAoptions")
maTrendLength=input.int(defval=32,title='TrendMAPeriod',minval=1,group="TrendMAoptions")
trendMA=trendMAtype=='EMA'?ta.ema(maTrendSource,maTrendLength):trendMAtype=='SMA'?ta.sma(maTrendSource,maTrendLength):trendMAtype=='VWMA'?ta.vwma(maTrendSource,maTrendLength):ta.hma(maTrendSource,maTrendLength)
//SlowMA
slowMAtype=input.string(title='SlowMAType',defval='EMA',options=['EMA','SMA','VWMA','HMA'],group="SlowMAoptions",tooltip="The'SlowMA'actsasconfluencei.e.Onlytriggers'longs'abovethis,andonlytriggers'shorts'belowit.Ifyoudon'tcarefor'SlowMA'confluence,justchangetheoptionstomatchthe'TrendMA'optionsyou'vechosen.")
maSlowSource=input(defval=close,title='SlowMASource',group="SlowMAoptions")
maSlowLength=input.int(defval=64,title='SlowMAPeriod',minval=1,group="SlowMAoptions")
slowMA=slowMAtype=='EMA'?ta.ema(maSlowSource,maSlowLength):slowMAtype=='SMA'?ta.sma(maSlowSource,maSlowLength):slowMAtype=='VWMA'?ta.vwma(maSlowSource,maSlowLength):ta.hma(maSlowSource,maSlowLength)
//PlotMAsandcolour-fillsinbetweenthefastMA&trendMAtomakeprettyclouds...
//(ifyouaren'tmakingartwhilsttrading,thenwhyevenbother!)
fastMAline=plot(fastMA,title='FastMA',color=color.new(#b9cbef,60))
trendMAline=plot(trendMA,title='TrendMA',color=color.new(#4b21f3,50),style=plot.style_stepline)
slowMAline=plot(slowMA,title='SlowMA',color=color.new(#3b3eff,30))
fill(fastMAline,trendMAline,color=fastMA>trendMA?color.rgb(232,234,163,70):color.rgb(155,17,30,60),title='MATrendZone',editable=true)
//Fixed100MA(e.g.ifyouareonthe4H,thenthiswillshowthe1D100MA)
fixedMA1type=input.string(title='FixedMAType',defval='EMA',options=['EMA','SMA','VWMA','HMA'],group="FixedHTFMA1options",tooltip="ThisisthefixedHTFMAusedasconfluencei.e.Onlytriggers'longs'abovethis,andonlytriggers'shorts'belowit.Ifyoudon'tcareforHTFconfluence,justchangethetimeframe/optionstomatchthe'SlowMA'optionsyou'vechosen.")
ema1FixSource=input(defval=close,title='FixedEMASource',group="FixedHTFMA1options")
ema1FixLength=input.int(defval=100,title='FixedEMAPeriod',minval=1,group="FixedHTFMA1options")
ema1Res=input.timeframe(title="FixedEMATimeframe",defval="D",group="FixedHTFMA1options")
ema1col=input.bool(title="FixedHTFEMAbull/bearcolouring",defval=true,group="FixedHTFMA1options",tooltip="Meh...thiscangivethefixedHTFMAlineabull/bearcolour.Nothingtoseeherereally.")
ema1smooth=input.bool(title="Smoothed?",defval=false,group="FixedHTFMA1options",tooltip="Justsmoothestheabove.")
fixedMA1=fixedMA1type=='EMA'?ta.ema(ema1FixSource,ema1FixLength):fixedMA1type=='SMA'?ta.sma(ema1FixSource,ema1FixLength):fixedMA1type=='VWMA'?ta.vwma(ema1FixSource,ema1FixLength):ta.hma(ema1FixSource,ema1FixLength)
ema1Step=request.security(syminfo.tickerid,ema1Res,fixedMA1[barstate.isrealtime?1:0])
ema1Smooth=request.security(syminfo.tickerid,ema1Res,fixedMA1[barstate.isrealtime?1:0],gaps=barmerge.gaps_on)
plot(ema1smooth?ema1Smooth:ema1Step,color=ema1col?(close>ema1Step?color.rgb(240,232,73,30):color.rgb(240,232,73,70)):color.rgb(240,222,23,20),linewidth=3,title="FixedHTF100MA")
//Fixed200MA(e.g.ifyouareonthe4H,thenthiswillshowthe1D200MA)
fixedMA2type=input.string(title='FixedMAType',defval='EMA',options=['EMA','SMA','VWMA','HMA'],group="FixedHTFMA2options",tooltip="Thisispurelyacosmeticadditionalfeature,forthoseofuswhoneedmoreindicators!")
ema2FixSource=input(defval=close,title='FixedEMASource',group="FixedHTFMA2options")
ema2FixLength=input.int(defval=200,title='FixedEMAPeriod',minval=1,group="FixedHTFMA2options")
ema2Res=input.timeframe(title="FixedEMATimeframe",defval="D",group="FixedHTFMA2options")
ema2col=input.bool(title="FixedHTFEMAbull/bearcolouring",defval=true,group="FixedHTFMA2options",tooltip="Meh...thiscangivethefixedHTFMAlineabull/bearcolour.Nothingtoseeherereally.")
ema2smooth=input.bool(title="Smoothed?",defval=false,group="FixedHTFMA2options",tooltip="Justsmoothestheabove.")
fixedMA2=fixedMA2type=='EMA'?ta.ema(ema2FixSource,ema2FixLength):fixedMA2type=='SMA'?ta.sma(ema2FixSource,ema2FixLength):fixedMA2type=='VWMA'?ta.vwma(ema2FixSource,ema2FixLength):ta.hma(ema2FixSource,ema2FixLength)
ema2Step=request.security(syminfo.tickerid,ema2Res,fixedMA2[barstate.isrealtime?1:0])
ema2Smooth=request.security(syminfo.tickerid,ema2Res,fixedMA2[barstate.isrealtime?1:0],gaps=barmerge.gaps_on)
plot(ema2smooth?ema2Smooth:ema2Step,color=ema2col?(close>ema2Step?color.rgb(155,17,30,20):color.rgb(155,17,30,60)):color.rgb(155,17,30,20),linewidth=3,title="FixedHTF200MA")
////////////////////////////////////////////////
//==========TRADEENTRYPARAMETERS============
//v1RetestStrategyParameters
BBLongTrigger1=ta.crossunder(close,fastMA)
BBShortTrigger1=ta.crossover(close,fastMA)
BBcloseLongTrigger1=ta.crossunder(low,fastMA)
BBcloseShortTrigger1=ta.crossover(high,fastMA)
MABuyGuard1=fastMA>trendMAandtrendMA>slowMA
MASellGuard1=fastMA<trendMAandtrendMA<slowMA
longFixedMAGuard1=close>ema1Step
shortFixedMAGuard1=close<ema1Step
rsiBuyGuard1=rsi>rsiBuyLevel
rsiSellGuard1=rsi<rsiSellLevel
//v1BreakoutStrategyParameters
brBBLongTrigger1=ta.crossover(close,fastMA)
brBBShortTrigger1=ta.crossunder(close,fastMA)
//v2RetestStrategyParameters
BBLongTrigger2=ta.crossunder(close,fastMA)
BBShortTrigger2=ta.crossover(close,fastMA)
BBcloseLongTrigger2=ta.crossunder(low,fastMA)
BBcloseShortTrigger2=ta.crossover(high,fastMA)
MABuyGuard2=trendMA>slowMAandtrendMA>slowMA
MASellGuard2=trendMA<slowMAandtrendMA<slowMA
longFixedMAGuard2=close>ema1Step
shortFixedMAGuard2=close<ema1Step
rsiBuyGuard2=rsi>rsiBuyLevel
rsiSellGuard2=rsi<rsiSellLevel
//v2BreakoutStrategyParameters
brBBLongTrigger2=ta.crossover(close,fastMA)
brBBShortTrigger2=ta.crossunder(close,fastMA)
//v3RetestStrategyParameters
BBLongTrigger3=ta.crossunder(close,fastMA)
BBShortTrigger3=ta.crossover(close,fastMA)
BBcloseLongTrigger3=ta.crossunder(low,fastMA)
BBcloseShortTrigger3=ta.crossover(high,fastMA)
MABuyGuard3=trendMA>slowMAandtrendMA>slowMA
MASellGuard3=trendMA<slowMAandtrendMA<slowMA
longFixedMAGuard3=close>ema1Step
shortFixedMAGuard3=close<ema1Step
rsiBuyGuard3=rsi>rsiBuyLevel
rsiSellGuard3=rsi<rsiSellLevel
//v3BreakoutStrategyParameters
brBBLongTrigger3=ta.crossover(close,fastMA)
brBBShortTrigger3=ta.crossunder(close,fastMA)
////////////////////////////////////////////////
//======TRADEENTRYTRIGGERS======
//v1RetestSignals
Long_1=BBLongTrigger1andMABuyGuard1andrsiBuyGuard1andlongFixedMAGuard1
closeLong_1=BBcloseLongTrigger1
Short_1=BBShortTrigger1andMASellGuard1andrsiSellGuard1andshortFixedMAGuard1
closeShort_1=BBcloseShortTrigger1
ifs1==trueandv1==true
strategy.entry("Strat1'Retest'Long",strategy.long,when=Long_1,alert_message="Strat1'Retest'-BuySignal!")
strategy.close("Strat1'Retest'Long",when=closeLong_1,alert_message="Strat1'Retest'-CloseSignal!")
strategy.entry("Strat1'Retest'Short",strategy.short,when=Short_1,alert_message="Strat1'Retest'-ShortSignal!")
strategy.close("Strat1'Retest'Short",when=closeShort_1,alert_message="Strat1'Retest'-CloseSignal!")
//v1BreakoutSignals
brLong_1=brBBLongTrigger1andMABuyGuard1andrsiBuyGuard1andlongFixedMAGuard1
brcloseLong_1=BBcloseLongTrigger1
brShort_1=brBBShortTrigger1andMASellGuard1andrsiSellGuard1andshortFixedMAGuard1
brcloseShort_1=BBcloseShortTrigger1
ifs2==trueandv1==true
strategy.entry("Strat1'Breakout'Long",strategy.long,when=brLong_1,alert_message="Strat1'Breakout'-BuySignal!")
strategy.close("Strat1'Breakout'Long",when=closeLong_1,alert_message="Strat1'Breakout'-CloseSignal!")
strategy.entry("Strat1'Breakout'Short",strategy.short,when=brShort_1,alert_message="Strat1'Breakout'-ShortSignal!")
strategy.close("Strat1'Breakout'Short",when=closeShort_1,alert_message="Strat1'Breakout'-CloseSignal!")
//v2RetestSignals
Long_2=BBLongTrigger2andMABuyGuard2andrsiBuyGuard2andlongFixedMAGuard2
Short_2=BBShortTrigger2andMASellGuard2andrsiSellGuard2andshortFixedMAGuard2
ifs1==trueandv2==true
strategy.entry("Strat2RetestLong",strategy.long,when=Long_2,alert_message="Strat2Retest-BuySignal!")
strategy.exit("SL/TPStrat2Retestlong","Strat2RetestLong",stop=longv2stoploss_level,limit=longv2takeprofit_level)
strategy.entry("Strat2RetestShort",strategy.short,when=Short_2,alert_message="Strat2Retest-ShortSignal!")
strategy.exit("SL/TPStrat2Retestshort","Strat2RetestShort",stop=shortv2stoploss_level,limit=shortv2takeprofit_level)
//v2BreakoutSignals
brLong_2=brBBLongTrigger2andMABuyGuard2andrsiBuyGuard2andlongFixedMAGuard2
brShort_2=brBBShortTrigger2andMASellGuard2andrsiSellGuard2andshortFixedMAGuard2
ifs2==trueandv2==true
strategy.entry("Strat2BreakoutLong",strategy.long,when=brLong_2,alert_message="Strat2Breakout-BuySignal!")
strategy.exit("SL/TPStrat2Breakoutlong","Strat2BreakoutLong",stop=longv2stoploss_level,limit=longv2takeprofit_level)
strategy.entry("Strat2BreakoutShort",strategy.short,when=brShort_2,alert_message="Strat2Breakout-ShortSignal!")
strategy.exit("SL/TPStrat2Breakoutshort","Strat2BreakoutShort",stop=shortv2stoploss_level,limit=shortv2takeprofit_level)
//v3RetestSignals
Long_3=BBLongTrigger3andMABuyGuard3andrsiBuyGuard3andlongFixedMAGuard3
Short_3=BBShortTrigger3andMASellGuard3andrsiSellGuard3andshortFixedMAGuard3
ifs1==trueandv3==true
strategy.entry("Strat3RetestLong",strategy.long,when=Long_3,alert_message="Strat3Retest-BuySignal!")
strategy.exit("SL/TPStrat3Retestlong","Strat3RetestLong",stop=longv3stoploss_level,limit=longv3takeprofit_level)
strategy.entry("Strat3RetestShort",strategy.short,when=Short_3,alert_message="Strat3Retest-ShortSignal!")
strategy.exit("SL/TPStrat3Retestshort","Strat3RetestShort",stop=shortv3stoploss_level,limit=shortv3takeprofit_level)
//v3BreakoutSignals
brLong_3=brBBLongTrigger3andMABuyGuard3andrsiBuyGuard3andlongFixedMAGuard3
brShort_3=brBBShortTrigger3andMASellGuard3andrsiSellGuard3andshortFixedMAGuard3
ifs2==trueandv3==true
strategy.entry("Strat3BreakoutLong",strategy.long,when=brLong_3,alert_message="Strat3Breakout-BuySignal!")
strategy.exit("SL/TPStrat3Breakoutlong","Strat3BreakoutLong",stop=longv3stoploss_level,limit=longv3takeprofit_level)
strategy.entry("Strat3BreakoutShort",strategy.short,when=brShort_3,alert_message="Strat3Breakout-ShortSignal!")
strategy.exit("SL/TPStrat3Breakoutshort","Strat3BreakoutShort",stop=shortv3stoploss_level,limit=shortv3takeprofit_level)
////////////////////////////////////////////////
Expand (243 lines)
