Script Name: Noro's RiskTurtle Strategy
Author: ROBO_Trading
Description: The idea of ​ this strategy script was taken here:
(PDF-Book, English) bigpicture.typepad.com

 Strategy

2 Donchian price channels are being created. Fast and slow. The number of candles for the channels is selected by the user. By default, 20 bars for fast and 50 bars for slow. Blue lines show a slow price channel . And used to enter positions. Using market...
PineScript code:

Pine Script™ strategy
Noro's RiskTurtle Strategy
//Noro
//2020
//@version=4
strategy("Noro's  RiskTurtle  Strategy",  shorttitle  =  "RiskTurtle  str",  overlay  =  true,  default_qty_type  =  strategy.percent_of_equity,  initial_capital  =  100,  default_qty_value  =  100,  commission_value  =  0.1)
//Settings
needlong    =  input(true,  defval  =  true,  title  =  "Long")
needshort  =  input(true,  defval  =  true,  title  =  "Short")
risklong    =  input(2.0,  minval  =  0.0,  maxval  =  99.9,  title  =  "Risk  size  for  long,  %")
riskshort  =  input(2.0,  minval  =  0.0,  maxval  =  99.9,  title  =  "Risk  size  for  short,  %")
fast            =  input(20,  minval  =  1,  title  =  "Fast  channel  (for  stop-loss)")
slow=input(40,minval=1,title="Slowchannel(forentries)")
usetick=input(false,defval=false,title="+1tick")
showof=input(true,defval=true,title="Showoffset")
showll=input(true,defval=true,title="Showlines")
showdd=input(true,defval=true,title="Showlabel(drawdown)")
showbg=input(true,defval=true,title="Showbackground")
fromyear=input(1900,defval=1900,minval=1900,maxval=2100,title="FromYear")
toyear=input(2100,defval=2100,minval=1900,maxval=2100,title="ToYear")
frommonth=input(01,defval=01,minval=01,maxval=12,title="FromMonth")
tomonth=input(12,defval=12,minval=01,maxval=12,title="ToMonth")
fromday=input(01,defval=01,minval=01,maxval=31,title="Fromday")
today=input(31,defval=31,minval=01,maxval=31,title="Today")
//Donchianpricechannelfast
hf=highest(high,fast)
lf=lowest(low,fast)
center=(hf+lf)/2
//Donchianpricechennalslow
tick=usetick?syminfo.mintick:0
hs=highest(high,slow)+tick
ls=lowest(low,slow)-tick
//Lines
colorpc=showll?color.blue:na
colorsl=showll?color.red:na
offset=showof?1:0
plot(hs,offset=offset,color=colorpc,title="Slowchannelhigh")
plot(ls,offset=offset,color=colorpc,title="Slowchannellow")
plot(center,offset=offset,color=colorsl,title="Fastchannelstop-loss")
//Background
size=strategy.position_size
colorbg=showbg==false?na:size>0?color.lime:size<0?color.red:na
bgcolor(colorbg,transp=70)
//Var
loss=0.0
maxloss=0.0
equity=0.0
truetime=time>timestamp(fromyear,frommonth,fromday,00,00)andtime<timestamp(toyear,tomonth,today,23,59)
//Lotsize
risksizelong=-1*risklong
risklonga=((center/hs)-1)*100
coeflong=abs(risksizelong/risklonga)
lotlong=(strategy.equity/close)*coeflong
risksizeshort=-1*riskshort
riskshorta=((center/ls)-1)*100
coefshort=abs(risksizeshort/riskshorta)
lotshort=(strategy.equity/close)*coefshort
//Orders
strategy.entry("Long",strategy.long,lotlong,stop=hs,when=needlongandstrategy.position_size==0andhs>0andtruetime)
strategy.entry("Short",strategy.short,lotshort,stop=ls,when=needshortandstrategy.position_size==0andls>0andtruetime)
strategy.exit("LongExit","Long",stop=center,when=needlongandstrategy.position_size>0)
strategy.exit("ShortExit","Short",stop=center,when=needshortandstrategy.position_size<0)
iftime>timestamp(toyear,tomonth,today,23,59)
strategy.close_all()
strategy.cancel("Long")
strategy.cancel("Short")

ifshowdd
//Drawdown
max=0.0
max:=max(strategy.equity,nz(max[1]))
dd=(strategy.equity/max-1)*100
min=100.0
min:=min(dd,nz(min[1]))

//Maxlosssize
equity:=strategy.position_size==0?strategy.equity:equity[1]
loss:=equity<equity[1]?((equity/equity[1])-1)*100:0
maxloss:=min(nz(maxloss[1]),loss)

//Shift
shift=abs(((close/center)-1)*100)

//Label
min:=round(min*100)/100
maxloss:=round(maxloss*100)/100
shift:=round(shift*100)/100
labeltext="Drawdown:"+tostring(min)+"%"+"\nMax.loss"+tostring(maxloss)+"%"+"\nShift"+tostring(shift)+"%"
varlabella=na
label.delete(la)
tc=min>-100?color.white:color.red
osx=timenow+round(change(time)*10)
osy=highest(100)
la:=label.new(x=osx,y=osy,text=labeltext,xloc=xloc.bar_time,yloc=yloc.price,color=color.black,style=label.style_labelup,textcolor=tc)
Expand (102 lines)
