Script Name: Open Close Cross Strategy plus Explorer
Author: roses27
Description: Open Close Cross Strategy plus Explorer
V 1.0
There is a code that can control sensitivity. try to change 'ATR Multiplier' menu
There is a code for prevent 'repaint'. If you want it check 'Forces Non-Repainting' menu

thanks to
PMax Explorer STRATEGY & SCREENER KivancOzbilgic
Open Close Cross Strategy R5 revised by JustUncleL JustUncleL
PineScript code:

Pine Script™ strategy
Open Close Cross Strategy plus Explorer
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//@version=4
//author  roses27
//  V  1.464
//  There  is  a  code  that  can  control  sensitivity.
//  There  is  a  code  for  prevent  'repaint'
//  There  is  a  code  for  data  sorting  and  display.
//  thanks  to  @JustUncleL  @JayRogers  about  'BASE  FUNCTIONS'
strategy(title  =  "Open  Close  Cross  Strategy  plus  Explorer",    shorttitle  =  "OCC  plus  Explorer",overlay=true,  calc_on_every_tick=false,
                  initial_capital=100000,  default_qty_type=  strategy.cash,  default_qty_value=100000,  process_orders_on_close  =  true,
                  pyramiding  =  0,  commission_type=strategy.commission.percent,  commission_value=0.25)
//  ===  INPUTS  ===
tradeType              =  input("LONG",                  title  =  "What  trades  should  be  taken  :  ",  options=["LONG",  "SHORT",  "BOTH",  "NONE"])
resMultiplier      =  input(defval  =  5,          title  =  "Multiplier  for  Alternate  Resolution('1'  is  original)",      minval  =  1,    tooltip  =  "The  current  resolution  is  multiplied  by  this  number  and  calculated  at  Alternate  Resolution.")
basisType              =  input(defval  =  "TEMA",title  =  "MA  Type:  ",  options=["SMA",  "EMA",  "DEMA",  "TEMA",  "WMA",  "VWMA",  "SMMA",  "HullMA",  "LSMA",  "ALMA",  "SSMA",  "TMA"],  tooltip  =  "Moving  Average  Type")
basisLen                =  input(defval  =  50,          title  =  "MA  Period",  minval  =  1)
alma_offset          =  input(defval  =  0.85,    title  =  "Offset  for  ALMA",            minval  =  0.0,  step  =  0.01)
alma_sigma            =  input(defval  =  6.0,      title  =  "Sigma  for  ALMA",              minval  =  0.0,  step  =  0.1)
lsma_offset          =  input(defval  =  5,          title  =  "Offset  for  LSMA",            minval  =  0,      step  =  1)
useStartPeriodTime    =  input(true,  "Start",                                    input.bool,          group  =  "Date  Range",      inline  =  "Start  Period")
startPeriodTime          =  input(timestamp("  4  Mar  2021"),  "",      input.time,          group  =  "Date  Range",      inline  =  "Start  Period")
useEndPeriodTime        =  input(false,"End    ",                                    input.bool,          group  =  "Date  Range",      inline  =  "End  Period")
endPeriodTime              =  input(timestamp("19  Apr  2021"),  "",      input.time,          group  =  "Date  Range",      inline  =  "End  Period")
enableHighlight          =  input(false,  "Highlight",                          input.bool,          group  =  "Date  Range",      inline  =  "Highlight")
highlightType              =  input(            "Anchors","",                          input.string,  options  =  ["Anchors",  "Background"],    group  =  "Date  Range",inline  =  "Highlight")
highlightColor            =  input(color.red,          "",  input.color,group="DateRange",inline="Highlight")
scolor=input(defval=true,title="ShowcolouredBarstoindicateTrend?",group="DateRange")
//===Codetoadjustsensitivity'Multiplier*atr'===
Periods=input(defval=30,title="ATRLength",group="Sensitivity",minval=1)
Multiplier=input(defval=0.3,title="ATRMultiplier",group="Sensitivity",minval=0.0,step=0.01,tooltip="Thelargerthevalue,enterlateandexitlate.")
Non_Repainting=input(defval=2,title="ForcestoNon-Repainting",options=[0,1,2],group="Sensitivity",tooltip="0:Theresultsaredelayedasmuchas'0'.1:Theresultsaredelayedasmuchasthecurrentresolution.2:TheresultsaredelayedasmuchastheAlternateResolution.Thelargertheprobabilityof'repainting'decreases.")
//===/Codetoadjustsensitivity'Multiplier*atr'===
//===/INPUTS===
start=useStartPeriodTime?startPeriodTime>=time:false
end=useEndPeriodTime?endPeriodTime<=time:false
calcPeriod=notstartandnotend
varlinestartAnchor=line.new(na,na,na,na,xloc.bar_time,extend.both,highlightColor,width=2)
varlineendAnchor=line.new(na,na,na,na,xloc.bar_time,extend.both,highlightColor,width=2)
useBgcolor=false
//{——————————PineCodersMTFSelectionFrameworkfunctions
//—————Convertscurrent"timeframe.multiplier"plustheTFintominutesoftypefloat.
f_resInMinutes()=>
_resInMinutes=timeframe.multiplier*(
timeframe.isseconds?1./60.:
timeframe.isminutes?1.:
timeframe.isdaily?1440.:
timeframe.isweekly?10080.:
timeframe.ismonthly?43800.:na)
//—————Returnsresolutionof_resolutionperiodinminutes.
f_tfResInMinutes(_resolution)=>
//_resolution:resolutionofanyTF(in"timeframe.period"stringformat).
security(syminfo.tickerid,_resolution,f_resInMinutes())
//—————Givencurrentresolution,returnsnextstepofHTF.
f_resNextStep(_res)=>
//_res:currentTFinfractionalminutes.
_res<=1?"60":
_res<=60?"1D":
_res<=360?"3D":
_res<=1440?"1W":
_res<=10080?"1M":"12M"
//—————Returnsamultipleofcurrentresolutionasastringin"timeframe.period"formatusablewith"security()".
f_multipleOfRes(_res,_mult)=>
//_res:currentresolutioninminutes,inthefractionalformatsuppliedbyf_resInMinutes()companionfunction.
//_mult:MultipleofcurrentTFtobecalculated.
//ConvertcurrentfloatTFinminutestotargetstringTFin"timeframe.period"format.
_targetResInMin=_res*max(_mult,1)
//Findbeststringtoexpresstheresolution.
_targetResInMin<=0.083?"5S":
_targetResInMin<=0.251?"15S":
_targetResInMin<=0.501?"30S":
_targetResInMin<=1440?tostring(round(_targetResInMin)):
_targetResInMin<=43800?tostring(round(min(_targetResInMin/1440,365)))+"D":
tostring(round(min(_targetResInMin/43800,12)))+"M"
//—————HTFcalcs
//}——————————PineCodersMTFSelectionFrameworkfunctions
//{===BASEFUNCTIONS===
variant(_type,_src,_len,_alma_offset,_alma_sigma,_lsma_offset)=>
v1=sma(_src,_len)//Simple
v2=ema(_src,_len)//Exponential
v3=2*v2-ema(v2,_len)//DoubleExponential
v4=3*(v2-ema(v2,_len))+ema(ema(v2,_len),_len)//TripleExponential
v5=wma(_src,_len)//Weighted
v6=vwma(_src,_len)//VolumeWeighted
v7=0.0
v7:=na(v7[1])?sma(_src,_len):(v7[1]*(_len-1)+_src)/_len//Smoothed
v8=wma(2*wma(_src,_len/2)-wma(_src,_len),round(sqrt(_len)))//Hull
v9=linreg(_src,_len,_lsma_offset)//LeastSquares
v10=alma(_src,_len,_alma_offset,_alma_sigma)//ArnaudLegoux
v11=sma(v1,_len)//Triangular(extremesmooth)
//SuperSmootherfilter
//©2013JohnF.Ehlers
a1=exp(-1.414*3.14159/_len)
b1=2*a1*cos(1.414*3.14159/_len)
c2=b1
c3=(-a1)*a1
c1=1-c2-c3
v12=0.0
v12:=c1*(_src+nz(_src[1]))/2+c2*nz(v12[1])+c3*nz(v12[2])
_type=="EMA"?v2:_type=="DEMA"?v3:_type=="TEMA"?v4:_type=="WMA"?v5:_type=="VWMA"?v6:_type=="SMMA"?v7:
_type=="HullMA"?v8:_type=="LSMA"?v9:_type=="ALMA"?v10:_type=="TMA"?v11:_type=="SSMA"?v12:v1
//}===/BASEFUNCTIONS===
//{====Codeforprevent'repaint'===
//securitywrapperforrepeatcalls
f_security(_id,_res,_exp,_non_rep)=>
security(_id,_res,_exp[_non_rep==2?1:0],gaps=barmerge.gaps_off,
lookahead=barmerge.lookahead_on)[_non_rep==1?1:0]
//}====/Codeforprevent'repaint'===
//Getcurrentresolutioninfloatminutes.
varvResInMinutes=f_resInMinutes()
stratRes=f_multipleOfRes(vResInMinutes,resMultiplier)
atr=atr(Periods)
//===SERIESSETUP===
closeSeries=variant(basisType,close,basisLen,alma_offset,alma_sigma,lsma_offset)
openSeries=variant(basisType,open,basisLen,alma_offset,alma_sigma,lsma_offset)
//===/SERIES===
//GetAlternateresolutionSeriesifselected.
closeSeriesAlt=f_security(syminfo.tickerid,stratRes,closeSeries,Non_Repainting)
openSeriesAlt=f_security(syminfo.tickerid,stratRes,openSeries,Non_Repainting)
//{===PLOTTING===
trendColour=(closeSeriesAlt>openSeriesAlt+Multiplier*atr)?color.green:(closeSeriesAlt<openSeriesAlt-Multiplier*atr)?color.red:color.yellow
bcolour=(closeSeriesAlt>openSeriesAlt)?color.green:color.red
barcolor(scolorandcalcPeriod?bcolour:na,title="BarColours")
closeP=plot(series=scolorandcalcPeriod?closeSeriesAlt:na,title="CloseSeries",color=trendColour,linewidth=2,style=plot.style_line,transp=20)
openP=plot(series=scolorandcalcPeriod?openSeriesAlt:na,title="OpenSeries",color=trendColour,linewidth=2,style=plot.style_line,transp=20)
fill(closeP,openP,color=trendColour,transp=80)
ifenableHighlight
ifhighlightType=="Anchors"
ifuseStartPeriodTime
line.set_xy1(startAnchor,startPeriodTime,low)
line.set_xy2(startAnchor,startPeriodTime,high)
ifuseEndPeriodTime
line.set_xy1(endAnchor,calcPeriod?time:line.get_x1(endAnchor),low)
line.set_xy2(endAnchor,calcPeriod?time:line.get_x1(endAnchor),high)

ifhighlightType=="Background"
useBgcolor:=true
bgcolor(useBgcolorandcalcPeriod?highlightColor:na,editable=false)
//plot"calcPeriodoftime"
//}===/PLOTTING===
//
//{===STRATEGYconditions
long=crossover(closeSeriesAlt,openSeriesAlt+Multiplier*atr)//Codetoadjustsensitivity'Multiplier*atr'
short=crossunder(closeSeriesAlt,openSeriesAlt-Multiplier*atr)//Codetoadjustsensitivity'Multiplier*atr'
//===/STRATEGYconditions.
//===STRATEGY===
//stoploss
//stopLoss=input(defval=0,title="StopLossPoints(zerofordisable)",group="StopCondition",minval=0)
//targetProfit=input(defval=0,title="TargetProfitPoints(zerofordisable)",group="StopCondition",minval=0)
//STEP1:
//Configuretrailstoplevelwithinputoptions(optional)
//longTrailPerc=input(title="TrailLongLoss(%)(zerofordisable)",type=input.float,minval=0.0,step=0.1,defval=5.0,group="StopCondition",tooltip="fromhighestpoint")*0.01
//shortTrailPerc=input(title="TrailShortLoss(%)(zerofordisable)",type=input.float,minval=0.0,step=0.1,defval=5.0,group="StopCondition",tooltip="fromlowestpoint")*0.01
longTrailPerc=input(title="TrailLongLoss(%)(zerofordisable)",type=input.float,minval=0.0,step=0.1,defval=0.0,group="StopCondition",tooltip="Fromtheprevious'close'value")*0.01
shortTrailPerc=input(title="TrailShortLoss(%)(zerofordisable)",type=input.float,minval=0.0,step=0.1,defval=0.0,group="StopCondition",tooltip="Fromtheprevious'close'value")*0.01
//STEP2:
//Determinetrailstoplossprices
longStopPrice=0.0,shortStopPrice=0.0
longStopPrice:=if(strategy.position_size>0)
stopValue=close*(1-longTrailPerc)
//stopValue=high*(1-longTrailPerc)
max(stopValue,longStopPrice[1])
else
0
shortStopPrice:=if(strategy.position_size<0)
stopValue=close*(1+shortTrailPerc)
//stopValue=low*(1+shortTrailPerc)
min(stopValue,shortStopPrice[1])
else
9999999999
//Plotstoplossvaluesforconfirmation
plot(series=(strategy.position_size>0)andcalcPeriodandlongTrailPerc!=0.0?longStopPrice:na,
color=color.fuchsia,style=plot.style_linebr,
linewidth=2,title="LongTrailStop",transp=0)

plot(series=(strategy.position_size<0)andcalcPeriodandshortTrailPerc!=0.0?shortStopPrice:na,
color=color.purple,style=plot.style_linebr,
linewidth=2,title="ShortTrailStop",transp=0)
//exitparameters
//TP=targetProfit>0?targetProfit:na
//SL=stopLoss>0?stopLoss:na
if(calcPeriodandtradeType!="NONE")
strategy.entry("long",strategy.long,when=long==trueandtradeType!="SHORT",comment="EL",alert_message="Long")
strategy.entry("short",strategy.short,when=short==trueandtradeType!="LONG",comment="ES",alert_message="Short")
strategy.close("long",when=short==trueandtradeType=="LONG",comment="ELclose",alert_message="Longclose")
strategy.close("short",when=long==trueandtradeType=="SHORT",comment="ESclose",alert_message="Shortclose")
//strategy.exit("XL",from_entry="long",profit=TP,loss=SL,comment="XLlong",alert_message="exitlong")
//strategy.exit("XS",from_entry="short",profit=TP,loss=SL,comment="XLshort",alert_message="exitshort")
strategy.exit(id="long",when=strategy.position_size>0andlongTrailPerc!=0.0,stop=longStopPrice,comment="LongTRLSTP",alert_message="LongTRLSTP")
strategy.exit(id="short",when=strategy.position_size<0andshortTrailPerc!=0.0,stop=shortStopPrice,comment="ShortTRLSTP",alert_message="ShortTRLSTP")
//}===/STRATEGY===
//eof
//{Toviewtrendsstart
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//////////////////////////////////////////////////////////////////////////////////
////
//Ifyoudon'twanta[screenlabel],commentordeletethelinebelowall.//
////
//////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//{inputforLabelstart
showLabel=input(defval=true,title="ShowScreenerLabelwithTextColor",group="Label",inline="ShowLabel")
textColor=input(color.blue,"",input.color,group="Label",inline="ShowLabel")
rmCurrency=input(defval=true,title="RemoveCurrencyDisplay",group="Label",inline="RemoveCurrency")
Currency=input(defval="USDT,USD,KRW",title="",type=input.string,confirm=false,group="Label",inline="RemoveCurrency")
sort_by=input(defval="ChangeRate",title="LabelSortby:",options=["Profit","ChangeRate","None"],group="Label")
posX_scr=input(defval=100,title="LabelPositionx-axis(#bars)",group="Label",tooltip="Thelabelmovestotherightbythenumberofbars..")
posY_scr=input(defval=100.0,title="LabelPositiony-axis(ohlc4[100]*%/100)",step=0.1,group="Label",tooltip="Thelabelmovesupanddowndependingontheinputvalue.100%isoriginalpoint.ex)99.5,ex)105")
//}inputforLabelend
//{Functionforhandlingstringsstart
//—————Functionreturningastringrepresentationofanumeric`_val`usingaspecial`_fmt`stringallowingallstringstobeofthesamewidth,tohelpaligncolumnsofvalues.
f_tostringPad(_val,_fmt)=>
//float_val:stringtoseparate.
//string_fmt:formattingstringsimilartothoseusedinthe`tostring()`formatstring,with"?"usedtoindicatepadding,
//e.g.,"??0.00"toensurethatnumbersalwayscontainthreecharactersleftofthedecimalpoint.
//WARNING:AminussignMUSTbegintheformat("-??0.00")ifnegativevaluesaretobehandled,otherwisenegativevalueswillhavenominussign.
//Characterusedtopadnumbers:Unicodefigurespace(U+2007).
varstringFIGURE_SPACE=" "
//Characterusedtopadminussigns:Unicodepunctuationspace(U+2008).
varstringPUNCTUATION_SPACE=" "
//Preliminaryconversionofthevaluetoastring.
string_formattedVal=tostring(_val,_fmt)
//Removeminussignfromformatstring.
_formattedVal:=str.replace_all(_formattedVal,"-","")
//Splitvalueandformatstringintocharacters.
string[]_chars=str.split(_formattedVal,"")
string[]_charsFmt=str.split(_fmt,"")

//Detectifweneedtohandlenegativevalues,andifso,removetheminussignfromformat.
bool_handleNegs=array.get(_charsFmt,0)=="-"
if_handleNegs
array.shift(_charsFmt)
//Detectifvalueorformatstringarewithoutadecimalpointandifso,addatemporaryoneforourlogic,whichwe'llremovelater.
int_pointPos=array.indexof(_chars,".")
int_pointPosFmt=array.indexof(_charsFmt,".")
bool_noPoint=_pointPos==-1
bool_noPointFmt=_pointPosFmt==-1
if_noPoint
array.push(_chars,".")
_pointPos:=array.indexof(_chars,".")
if_noPointFmt
array.push(_charsFmt,".")
_pointPosFmt:=array.indexof(_charsFmt,".")
//Removeextrainstancesof"?"infrontofvalue.
_extraChars=_pointPos-_pointPosFmt
if_extraChars>0
for_i=0to_extraChars-1
array.shift(_chars)
//Addminussignorspaceifneeded.
if_handleNegs
//Formataccountsfornegativevalues;insertminussignorspace.
array.unshift(_chars,(_val<0?"-":PUNCTUATION_SPACE))
//Removetemporarydecimalpointifneeded.
if_noPointFmtor_noPoint
array.pop(_chars)
//Rejoinourarrayandreplacethe"?"charsleftinourresultwithfigurespacepadding.
string_return=array.join(_chars,"")
_return:=str.replace_all(_return,"?",FIGURE_SPACE)
f_rmDnC(_str,_space,_rmCurrency,_Currency)=>
//string_str:stringtoseparate.
//int_space:spaceforid
//bool_rmCurrency:iftrueremovecurrencydisplay
//string_Currency:Separatedby','listofCurrency
varstringFIGURE_SPACE=" "
varstring_str0=_str
if_rmCurrency
_Currencys0=str.split(str.replace_all(_Currency,"",""),",")
fori=0toarray.size(_Currencys0)-1
_str0:=str.replace_all(_str0,array.get(_Currencys0,i),'')
string[]_chars=str.split(_str0,"")
int_len=array.size(_chars)
int_ofPos=array.indexof(_chars,":")
string[]_substr=array.new_string(0)
if_ofPos>=0and_ofPos<_len-1
_substr:=array.slice(_chars,_ofPos+1,_len)//removeDealercode
int_len2=array.size(_substr)
if_len2<_space
for_i=_len2+1to_space
array.push(_substr,FIGURE_SPACE)
//array.unshift(_substr,FIGURE_SPACE)
elseif_len<_space
_len:=_str==''?0:_len//sizeof'string[]_chars=str.split('',"")'is1not0
for_i=_len+1to_space
array.push(_chars,FIGURE_SPACE)
//array.unshift(_chars,FIGURE_SPACE)
string_return=_ofPos>=0and_ofPos<_len-1?array.join(_substr,""):array.join(_chars,"")
//}Functionforhandlingstringsend
OCCmax(_id,_multiplier,_non_rep)=>
varTrend=0
varPosition=0
varprofit=0.0
varchangeRate=0.0
vartm=0
varto_num=0
if_id==''
Trend:=0,Position:=0,profit:=-99999999.9,changeRate:=-99999999.9,tm:=0
if_id!=''
Trend:=closeSeries[1]>(openSeries[1]+_multiplier*atr)?1:
closeSeries[1]<(openSeries[1]-_multiplier*atr)?-1:0
Position:=Trend!=0?Trend:Position[1]
to_num:=barssince(Position[1]!=Position[0])+1
profit:=100.0*(close[0]-close[to_num])/close[to_num]
tm:=to_num*resMultiplier
changeRate:=100.0*profit/(tm*vResInMinutes)
[Trend,Position,profit,changeRate,tm]
//////////////////////////////////////////////////////////////////////////////////////////////
//Ifyouwanttoreducetheinputspace,adjustthe'array_size'.//
//Andcommenttheidnumberasmanyasyouwantfromthelinebelow.//
//'array_size'is1largerthanthe'IDnumber'.array_sizecannotbegreaterthan38.//
//////////////////////////////////////////////////////////////////////////////////////////////
array_size=38
spaceSize=rmCurrency?4:6//fortickeriddisplay
//{Labelliststart
varid_=array.new_string(array_size),vart_=array.new_int(array_size),varp_=array.new_int(array_size)
varpr_=array.new_float(array_size),varcr_=array.new_float(array_size),vartm_=array.new_int(array_size)
id00=syminfo.tickerid,[t00,p00,pr00,cr00,tm00]=security(id00,stratRes,OCCmax(id00,Multiplier,Non_Repainting)),array.set(id_,0,f_rmDnC(id00,spaceSize,rmCurrency,Currency)),array.set(t_,0,t00),array.set(p_,0,p00),array.set(pr_,0,pr00),array.set(cr_,0,cr00),array.set(tm_,0,tm00)
id01=input('',title='Symbol01',type=input.symbol,group="Inputstoviewtrends"),[t01,p01,pr01,cr01,tm01]=security(id01,stratRes,OCCmax(id01,Multiplier,Non_Repainting)),array.set(id_,1,f_rmDnC(id01,spaceSize,rmCurrency,Currency)),array.set(t_,1,t01),array.set(p_,1,p01),array.set(pr_,1,pr01),array.set(cr_,1,cr01),array.set(tm_,1,tm01)
id02=input('',title='Symbol02',type=input.symbol,group="Inputstoviewtrends"),[t02,p02,pr02,cr02,tm02]=security(id02,stratRes,OCCmax(id02,Multiplier,Non_Repainting)),array.set(id_,2,f_rmDnC(id02,spaceSize,rmCurrency,Currency)),array.set(t_,2,t02),array.set(p_,2,p02),array.set(pr_,2,pr02),array.set(cr_,2,cr02),array.set(tm_,2,tm02)
id03=input('',title='Symbol03',type=input.symbol,group="Inputstoviewtrends"),[t03,p03,pr03,cr03,tm03]=security(id03,stratRes,OCCmax(id03,Multiplier,Non_Repainting)),array.set(id_,3,f_rmDnC(id03,spaceSize,rmCurrency,Currency)),array.set(t_,3,t03),array.set(p_,3,p03),array.set(pr_,3,pr03),array.set(cr_,3,cr03),array.set(tm_,3,tm03)
id04=input('',title='Symbol04',type=input.symbol,group="Inputstoviewtrends"),[t04,p04,pr04,cr04,tm04]=security(id04,stratRes,OCCmax(id04,Multiplier,Non_Repainting)),array.set(id_,4,f_rmDnC(id04,spaceSize,rmCurrency,Currency)),array.set(t_,4,t04),array.set(p_,4,p04),array.set(pr_,4,pr04),array.set(cr_,4,cr04),array.set(tm_,4,tm04)
id05=input('',title='Symbol05',type=input.symbol,group="Inputstoviewtrends"),[t05,p05,pr05,cr05,tm05]=security(id05,stratRes,OCCmax(id05,Multiplier,Non_Repainting)),array.set(id_,5,f_rmDnC(id05,spaceSize,rmCurrency,Currency)),array.set(t_,5,t05),array.set(p_,5,p05),array.set(pr_,5,pr05),array.set(cr_,5,cr05),array.set(tm_,5,tm05)
id06=input('',title='Symbol06',type=input.symbol,group="Inputstoviewtrends"),[t06,p06,pr06,cr06,tm06]=security(id06,stratRes,OCCmax(id06,Multiplier,Non_Repainting)),array.set(id_,6,f_rmDnC(id06,spaceSize,rmCurrency,Currency)),array.set(t_,6,t06),array.set(p_,6,p06),array.set(pr_,6,pr06),array.set(cr_,6,cr06),array.set(tm_,6,tm06)
id07=input('',title='Symbol07',type=input.symbol,group="Inputstoviewtrends"),[t07,p07,pr07,cr07,tm07]=security(id07,stratRes,OCCmax(id07,Multiplier,Non_Repainting)),array.set(id_,7,f_rmDnC(id07,spaceSize,rmCurrency,Currency)),array.set(t_,7,t07),array.set(p_,7,p07),array.set(pr_,7,pr07),array.set(cr_,7,cr07),array.set(tm_,7,tm07)
id08=input('',title='Symbol08',type=input.symbol,group="Inputstoviewtrends"),[t08,p08,pr08,cr08,tm08]=security(id08,stratRes,OCCmax(id08,Multiplier,Non_Repainting)),array.set(id_,8,f_rmDnC(id08,spaceSize,rmCurrency,Currency)),array.set(t_,8,t08),array.set(p_,8,p08),array.set(pr_,8,pr08),array.set(cr_,8,cr08),array.set(tm_,8,tm08)
id09=input('',title='Symbol09',type=input.symbol,group="Inputstoviewtrends"),[t09,p09,pr09,cr09,tm09]=security(id09,stratRes,OCCmax(id09,Multiplier,Non_Repainting)),array.set(id_,9,f_rmDnC(id09,spaceSize,rmCurrency,Currency)),array.set(t_,9,t09),array.set(p_,9,p09),array.set(pr_,9,pr09),array.set(cr_,9,cr09),array.set(tm_,9,tm09)
id10=input('',title='Symbol10',type=input.symbol,group="Inputstoviewtrends"),[t10,p10,pr10,cr10,tm10]=security(id10,stratRes,OCCmax(id10,Multiplier,Non_Repainting)),array.set(id_,10,f_rmDnC(id10,spaceSize,rmCurrency,Currency)),array.set(t_,10,t10),array.set(p_,10,p10),array.set(pr_,10,pr10),array.set(cr_,10,cr10),array.set(tm_,10,tm10)
id11=input('',title='Symbol11',type=input.symbol,group="Inputstoviewtrends"),[t11,p11,pr11,cr11,tm11]=security(id11,stratRes,OCCmax(id11,Multiplier,Non_Repainting)),array.set(id_,11,f_rmDnC(id11,spaceSize,rmCurrency,Currency)),array.set(t_,11,t11),array.set(p_,11,p11),array.set(pr_,11,pr11),array.set(cr_,11,cr11),array.set(tm_,11,tm11)
id12=input('',title='Symbol12',type=input.symbol,group="Inputstoviewtrends"),[t12,p12,pr12,cr12,tm12]=security(id12,stratRes,OCCmax(id12,Multiplier,Non_Repainting)),array.set(id_,12,f_rmDnC(id12,spaceSize,rmCurrency,Currency)),array.set(t_,12,t12),array.set(p_,12,p12),array.set(pr_,12,pr12),array.set(cr_,12,cr12),array.set(tm_,12,tm12)
id13=input('',title='Symbol13',type=input.symbol,group="Inputstoviewtrends"),[t13,p13,pr13,cr13,tm13]=security(id13,stratRes,OCCmax(id13,Multiplier,Non_Repainting)),array.set(id_,13,f_rmDnC(id13,spaceSize,rmCurrency,Currency)),array.set(t_,13,t13),array.set(p_,13,p13),array.set(pr_,13,pr13),array.set(cr_,13,cr13),array.set(tm_,13,tm13)
id14=input('',title='Symbol14',type=input.symbol,group="Inputstoviewtrends"),[t14,p14,pr14,cr14,tm14]=security(id14,stratRes,OCCmax(id14,Multiplier,Non_Repainting)),array.set(id_,14,f_rmDnC(id14,spaceSize,rmCurrency,Currency)),array.set(t_,14,t14),array.set(p_,14,p14),array.set(pr_,14,pr14),array.set(cr_,14,cr14),array.set(tm_,14,tm14)
id15=input('',title='Symbol15',type=input.symbol,group="Inputstoviewtrends"),[t15,p15,pr15,cr15,tm15]=security(id15,stratRes,OCCmax(id15,Multiplier,Non_Repainting)),array.set(id_,15,f_rmDnC(id15,spaceSize,rmCurrency,Currency)),array.set(t_,15,t15),array.set(p_,15,p15),array.set(pr_,15,pr15),array.set(cr_,15,cr15),array.set(tm_,15,tm15)
id16=input('',title='Symbol16',type=input.symbol,group="Inputstoviewtrends"),[t16,p16,pr16,cr16,tm16]=security(id16,stratRes,OCCmax(id16,Multiplier,Non_Repainting)),array.set(id_,16,f_rmDnC(id16,spaceSize,rmCurrency,Currency)),array.set(t_,16,t16),array.set(p_,16,p16),array.set(pr_,16,pr16),array.set(cr_,16,cr16),array.set(tm_,16,tm16)
id17=input('',title='Symbol17',type=input.symbol,group="Inputstoviewtrends"),[t17,p17,pr17,cr17,tm17]=security(id17,stratRes,OCCmax(id17,Multiplier,Non_Repainting)),array.set(id_,17,f_rmDnC(id17,spaceSize,rmCurrency,Currency)),array.set(t_,17,t17),array.set(p_,17,p17),array.set(pr_,17,pr17),array.set(cr_,17,cr17),array.set(tm_,17,tm17)
id18=input('',title='Symbol18',type=input.symbol,group="Inputstoviewtrends"),[t18,p18,pr18,cr18,tm18]=security(id18,stratRes,OCCmax(id18,Multiplier,Non_Repainting)),array.set(id_,18,f_rmDnC(id18,spaceSize,rmCurrency,Currency)),array.set(t_,18,t18),array.set(p_,18,p18),array.set(pr_,18,pr18),array.set(cr_,18,cr18),array.set(tm_,18,tm18)
id19=input('',title='Symbol19',type=input.symbol,group="Inputstoviewtrends"),[t19,p19,pr19,cr19,tm19]=security(id19,stratRes,OCCmax(id19,Multiplier,Non_Repainting)),array.set(id_,19,f_rmDnC(id19,spaceSize,rmCurrency,Currency)),array.set(t_,19,t19),array.set(p_,19,p19),array.set(pr_,19,pr19),array.set(cr_,19,cr19),array.set(tm_,19,tm19)
id20=input('',title='Symbol20',type=input.symbol,group="Inputstoviewtrends"),[t20,p20,pr20,cr20,tm20]=security(id20,stratRes,OCCmax(id20,Multiplier,Non_Repainting)),array.set(id_,20,f_rmDnC(id20,spaceSize,rmCurrency,Currency)),array.set(t_,20,t20),array.set(p_,20,p20),array.set(pr_,20,pr20),array.set(cr_,20,cr20),array.set(tm_,20,tm20)
id21=input('',title='Symbol21',type=input.symbol,group="Inputstoviewtrends"),[t21,p21,pr21,cr21,tm21]=security(id21,stratRes,OCCmax(id21,Multiplier,Non_Repainting)),array.set(id_,21,f_rmDnC(id21,spaceSize,rmCurrency,Currency)),array.set(t_,21,t21),array.set(p_,21,p21),array.set(pr_,21,pr21),array.set(cr_,21,cr21),array.set(tm_,21,tm21)
id22=input('',title='Symbol22',type=input.symbol,group="Inputstoviewtrends"),[t22,p22,pr22,cr22,tm22]=security(id22,stratRes,OCCmax(id22,Multiplier,Non_Repainting)),array.set(id_,22,f_rmDnC(id22,spaceSize,rmCurrency,Currency)),array.set(t_,22,t22),array.set(p_,22,p22),array.set(pr_,22,pr22),array.set(cr_,22,cr22),array.set(tm_,22,tm22)
id23=input('',title='Symbol23',type=input.symbol,group="Inputstoviewtrends"),[t23,p23,pr23,cr23,tm23]=security(id23,stratRes,OCCmax(id23,Multiplier,Non_Repainting)),array.set(id_,23,f_rmDnC(id23,spaceSize,rmCurrency,Currency)),array.set(t_,23,t23),array.set(p_,23,p23),array.set(pr_,23,pr23),array.set(cr_,23,cr23),array.set(tm_,23,tm23)
id24=input('',title='Symbol24',type=input.symbol,group="Inputstoviewtrends"),[t24,p24,pr24,cr24,tm24]=security(id24,stratRes,OCCmax(id24,Multiplier,Non_Repainting)),array.set(id_,24,f_rmDnC(id24,spaceSize,rmCurrency,Currency)),array.set(t_,24,t24),array.set(p_,24,p24),array.set(pr_,24,pr24),array.set(cr_,24,cr24),array.set(tm_,24,tm24)
id25=input('',title='Symbol25',type=input.symbol,group="Inputstoviewtrends"),[t25,p25,pr25,cr25,tm25]=security(id25,stratRes,OCCmax(id25,Multiplier,Non_Repainting)),array.set(id_,25,f_rmDnC(id25,spaceSize,rmCurrency,Currency)),array.set(t_,25,t25),array.set(p_,25,p25),array.set(pr_,25,pr25),array.set(cr_,25,cr25),array.set(tm_,25,tm25)
id26=input('',title='Symbol26',type=input.symbol,group="Inputstoviewtrends"),[t26,p26,pr26,cr26,tm26]=security(id26,stratRes,OCCmax(id26,Multiplier,Non_Repainting)),array.set(id_,26,f_rmDnC(id26,spaceSize,rmCurrency,Currency)),array.set(t_,26,t26),array.set(p_,26,p26),array.set(pr_,26,pr26),array.set(cr_,26,cr26),array.set(tm_,26,tm26)
id27=input('',title='Symbol27',type=input.symbol,group="Inputstoviewtrends"),[t27,p27,pr27,cr27,tm27]=security(id27,stratRes,OCCmax(id27,Multiplier,Non_Repainting)),array.set(id_,27,f_rmDnC(id27,spaceSize,rmCurrency,Currency)),array.set(t_,27,t27),array.set(p_,27,p27),array.set(pr_,27,pr27),array.set(cr_,27,cr27),array.set(tm_,27,tm27)
id28=input('',title='Symbol28',type=input.symbol,group="Inputstoviewtrends"),[t28,p28,pr28,cr28,tm28]=security(id28,stratRes,OCCmax(id28,Multiplier,Non_Repainting)),array.set(id_,28,f_rmDnC(id28,spaceSize,rmCurrency,Currency)),array.set(t_,28,t28),array.set(p_,28,p28),array.set(pr_,28,pr28),array.set(cr_,28,cr28),array.set(tm_,28,tm28)
id29=input('',title='Symbol29',type=input.symbol,group="Inputstoviewtrends"),[t29,p29,pr29,cr29,tm29]=security(id29,stratRes,OCCmax(id29,Multiplier,Non_Repainting)),array.set(id_,29,f_rmDnC(id29,spaceSize,rmCurrency,Currency)),array.set(t_,29,t29),array.set(p_,29,p29),array.set(pr_,29,pr29),array.set(cr_,29,cr29),array.set(tm_,29,tm29)
id30=input('',title='Symbol30',type=input.symbol,group="Inputstoviewtrends"),[t30,p30,pr30,cr30,tm30]=security(id30,stratRes,OCCmax(id30,Multiplier,Non_Repainting)),array.set(id_,30,f_rmDnC(id30,spaceSize,rmCurrency,Currency)),array.set(t_,30,t30),array.set(p_,30,p30),array.set(pr_,30,pr30),array.set(cr_,30,cr30),array.set(tm_,30,tm30)
id31=input('',title='Symbol31',type=input.symbol,group="Inputstoviewtrends"),[t31,p31,pr31,cr31,tm31]=security(id31,stratRes,OCCmax(id31,Multiplier,Non_Repainting)),array.set(id_,31,f_rmDnC(id31,spaceSize,rmCurrency,Currency)),array.set(t_,31,t31),array.set(p_,31,p31),array.set(pr_,31,pr31),array.set(cr_,31,cr31),array.set(tm_,31,tm31)
id32=input('',title='Symbol32',type=input.symbol,group="Inputstoviewtrends"),[t32,p32,pr32,cr32,tm32]=security(id32,stratRes,OCCmax(id32,Multiplier,Non_Repainting)),array.set(id_,32,f_rmDnC(id32,spaceSize,rmCurrency,Currency)),array.set(t_,32,t32),array.set(p_,32,p32),array.set(pr_,32,pr32),array.set(cr_,32,cr32),array.set(tm_,32,tm32)
id33=input('',title='Symbol33',type=input.symbol,group="Inputstoviewtrends"),[t33,p33,pr33,cr33,tm33]=security(id33,stratRes,OCCmax(id33,Multiplier,Non_Repainting)),array.set(id_,33,f_rmDnC(id33,spaceSize,rmCurrency,Currency)),array.set(t_,33,t33),array.set(p_,33,p33),array.set(pr_,33,pr33),array.set(cr_,33,cr33),array.set(tm_,33,tm33)
id34=input('',title='Symbol34',type=input.symbol,group="Inputstoviewtrends"),[t34,p34,pr34,cr34,tm34]=security(id34,stratRes,OCCmax(id34,Multiplier,Non_Repainting)),array.set(id_,34,f_rmDnC(id34,spaceSize,rmCurrency,Currency)),array.set(t_,34,t34),array.set(p_,34,p34),array.set(pr_,34,pr34),array.set(cr_,34,cr34),array.set(tm_,34,tm34)
id35=input('',title='Symbol35',type=input.symbol,group="Inputstoviewtrends"),[t35,p35,pr35,cr35,tm35]=security(id35,stratRes,OCCmax(id35,Multiplier,Non_Repainting)),array.set(id_,35,f_rmDnC(id35,spaceSize,rmCurrency,Currency)),array.set(t_,35,t35),array.set(p_,35,p35),array.set(pr_,35,pr35),array.set(cr_,35,cr35),array.set(tm_,35,tm35)
id36=input('',title='Symbol36',type=input.symbol,group="Inputstoviewtrends"),[t36,p36,pr36,cr36,tm36]=security(id36,stratRes,OCCmax(id36,Multiplier,Non_Repainting)),array.set(id_,36,f_rmDnC(id36,spaceSize,rmCurrency,Currency)),array.set(t_,36,t36),array.set(p_,36,p36),array.set(pr_,36,pr36),array.set(cr_,36,cr36),array.set(tm_,36,tm36)
id37=input('',title='Symbol37',type=input.symbol,group="Inputstoviewtrends"),[t37,p37,pr37,cr37,tm37]=security(id37,stratRes,OCCmax(id37,Multiplier,Non_Repainting)),array.set(id_,37,f_rmDnC(id37,spaceSize,rmCurrency,Currency)),array.set(t_,37,t37),array.set(p_,37,p37),array.set(pr_,37,pr37),array.set(cr_,37,cr37),array.set(tm_,37,tm37)
//{Labellistend
//{forLabeldisplaystart
varstringscr_label=''
varstringpot_label=''
varstringup_label=''
varstringdn_label=''
pot_label:=rmCurrency?'[PotentialReversal:        ]\n':'[PotentialReversal:            ]\n'
up_label:=rmCurrency?'[Uptrend:Profit,ChgRate,#Bars\n':'[Uptrend: Profit%, ChgRate,#Bars\n'
dn_label:=rmCurrency?'[Downtrend:              ]\n':'[Downtrend:                  ]\n'
scr_label:=rmCurrency?'[ConfirmedReversal:       ]\n':'[ConfirmedReversal:           ]\n'
up_label:=sort_by=="Profit"?(rmCurrency?up_label+'|         -------           |\n':up_label+'|          -----------           |\n'):up_label
up_label:=sort_by=="ChangeRate"?(rmCurrency?up_label+'|               --------    |\n':up_label+'|                 ---------     |\n'):up_label
up_label:=sort_by=="None"?(rmCurrency?up_label+'|                         |\n':up_label+'|                           |\n'):up_label
//{sortingstart
varnot_blank=array.indexof(id_,rmCurrency?"    ":"      ")!=-1?array.indexof(id_,rmCurrency?"    ":"      "):array_size
arrayForSort=sort_by=="Profit"?array.copy(pr_):array.copy(cr_)
array.sort(arrayForSort,order.descending)
stock_info=''
sorted_index=0
fori=0tonot_blank
ifi==0
sorted_index:=0//forid00=syminfo.tickerid
else
sorted_index:=sort_by=="None"?i-1:sort_by=="Profit"?array.indexof(pr_,array.get(arrayForSort,i-1)[0]):array.indexof(cr_,array.get(arrayForSort,i-1)[0])
sorted_index:=sorted_index!=-1?sorted_index:0
stock_info:=array.get(id_,sorted_index)[0]+' '+
f_tostringPad(array.get(pr_,sorted_index)[0],"-??0.00")+' '+
f_tostringPad(array.get(cr_,sorted_index)[0],"-?0.00")+' '+
f_tostringPad(array.get(tm_,sorted_index)[0],"???0")+'\n'
scr_label:=array.get(p_,sorted_index)[0]!=array.get(p_,sorted_index)[1]andarray.get(t_,sorted_index)[0]!=0?scr_label+stock_info:scr_label
pot_label:=array.get(t_,sorted_index)[0]==0?pot_label+stock_info:pot_label
up_label:=array.get(t_,sorted_index)[0]==1?up_label+stock_info:up_label
dn_label:=array.get(t_,sorted_index)[0]==-1?dn_label+stock_info:dn_label
//}sortingend
f_printscr(_txtscr)=>
var_lblscr=label(na),
label.delete(_lblscr),
_lblscr:=label.new(
time+(time-time[1])*posX_scr,
ohlc4[100]*posY_scr/100.0,
_txtscr,
xloc.bar_time,
yloc.price,
showLabel?#00000000:na,
textcolor=showLabel?textColor:na,
size=size.normal,
style=label.style_label_center,
textalign=text.align_right
)
f_printscr(scr_label+'\n'+pot_label+'\n'+up_label+'\n'+dn_label)
//}forLabeldisplayend
//}Toviewtrendsend
Expand (450 lines)
