Script Name: Optimised RSI strategy for Reversals (by Coinrule)
Author: Coinrule
Description: The most common way to use the RSI to spot a good buy opportunity is to check for values lower than 30. Unfortunately, the RSI can remain in oversold territory for long periods, and that could leave you trapped in a trade in loss. It would be appropriate to wait for a confirmation of the trend reversal.

In the example above I use a short-term Moving Average (in...
PineScript code:

Pine Script™ strategy
Optimised RSI strategy for Reversals (by Coinrule)
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  Coinrule
//@version=4
strategy(shorttitle='MARSI',title='Moving  Average',  overlay=true,  initial_capital=1000,    default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  100)
//Backtest  dates
fromMonth  =  input(defval  =  1,        title  =  "From  Month",            type  =  input.integer,  minval  =  1,  maxval  =  12)
fromDay      =  input(defval  =  1,        title  =  "From  Day",                type  =  input.integer,  minval  =  1,  maxval  =  31)
fromYear    =  input(defval  =  2020,  title  =  "From  Year",              type  =  input.integer,  minval  =  1970)
thruMonth  =  input(defval  =  1,        title  =  "Thru  Month",            type  =  input.integer,  minval  =  1,  maxval  =  12)
thruDay      =  input(defval  =  1,        title  =  "Thru  Day",                type  =  input.integer,  minval  =  1,  maxval  =  31)
thruYear    =  input(defval  =  2112,  title  =  "Thru  Year",              type  =  input.integer,  minval  =  1970)
showDate    =  input(defval  =  true,  title  =  "Show  Date  Range",  type  =  input.bool)
start=timestamp(fromYear,fromMonth,fromDay,00,00)//backteststartwindow
finish=timestamp(thruYear,thruMonth,thruDay,23,59)//backtestfinishwindow
window()=>time>=startandtime<=finish?true:false//createfunction"withinwindowoftime"
//MAinputsandcalculations
inshort=input(9,title='MAshortperiod')
MAshort=sma(close,inshort)
//RSIinputsandcalculations
lengthRSI=input(14,title='RSIperiod',minval=1)
RSI=rsi(close,lengthRSI)
//Entry
strategy.entry(id="long",long=true,when=MAshort<closeandRSI<40andwindow())
//Exit
longLossPerc=input(title="LongStopLoss(%)",
type=input.float,minval=0.0,step=0.1,defval=1.5)*0.01
longTakePerc=input(title="LongTakeProfit(%)",
type=input.float,minval=0.0,step=0.1,defval=3)*0.01
longSL=strategy.position_avg_price*(1-longLossPerc)
longTP=strategy.position_avg_price*(1+longTakePerc)
if(strategy.position_size>0andwindow())
strategy.exit(id="TP/SL",stop=longSL,limit=longTP)
bgcolor(color=showDateandwindow()?color.gray:na,transp=90)
plot(MAshort,color=color.purple,linewidth=4)
Expand (46 lines)
