Script Name: Perfect Order
Author: 110takaaki1127
Description: Entry Point

How to Entry
Perfect Order Entry
SMA5,13,21 & EMA75,90,200

Please enjoy your entry
PineScript code:

Pine Script™ strategy
Perfect Order
//@version=4
strategy(title="my_strategy_name",  shorttitle="MS1",  overlay=true,  initial_capital=10000,  default_qty_type=strategy.percent_of_equity,  default_qty_value=100,  commission_type=strategy.commission.percent,  commission_value=0.15,  pyramiding=0,  currency=currency.USD)
source  =  close
//  MAの長さ
len1  =  5
len2  =  13
len3  =  21
//  MAの計算
ma1  =  sma(source,  len1)
ma2  =  sma(source,  len2)
ma3  =  sma(source,  len3)
//  計算したMAをプロットする
plot(ma1,color=color.red)
plot(ma2,color=color.orange)
plot(ma3,color=color.blue)
//  EMAの長さ
len4  =  75
len5  =  90
len6  =  200
//  MAの計算
ema1  =  ema(source,  len4)
ema2  =  ema(source,  len5)
ema3  =  ema(source,  len6)
//  計算したMAをプロットする
plot(ema1,color=color.red)
plot(ema2,color=color.orange)
plot(ema3,color=color.blue)
longCondition  =  (ma1>ma2  and  ma2>ma3  and  ma3>ema1  and  ema1>ema2  and  ema2>ema3)//ロングにエントリーする条件
if  (longCondition)
        strategy.entry("My  Long  Entry",  strategy.long,  comment="Long")
shortCondition  =  (ma1<ma2  and  ma2<ma3  and  ma3<ema1  and  ema1<ema2  and  ema2<ema3)//ショートにエントリーする条件
if  (shortCondition)
        strategy.entry("My  Short  Entry",  strategy.short,  comment="Short")

        //エグジット条件
strategy.exit("My  Long  Exit",  "My  Long  Entry",  profit=200,  loss=100)
strategy.exit("My  Short  Exit",  "My  Short  Entry",  profit=200,  loss=100)



Expand (52 lines)
