Script Name: PineScript v4 - Forex Pin-Bar Trading Strategy
Author: TsangYouJun
Description: PineScript v4, forex trading robot based on the commonly used bullish / bearish pin-bar piercing the moving averages strategy. 

I coded this robot to stress-test the PineScript v4 language to see how advanced it is, and whether I could port a forex trading strategy from MT4 to TradingView. 

In my opinion, PineScript v4 is still not a professional coding...
PineScript code:

Pine Script™ strategy
PineScript v4 - Forex Pin-Bar Trading Strategy
//@version=4
//BacktestedTimeFrame:H1
//DefaultSettings:Aremeanttorunsuccessfullyonallcurrencypairstoreduceover-fitting.
//RiskWarning:Thisisaforextradingrobot,backtestperformancewillnotequalfutureperformance,USEATYOUROWNRISK.
//CodeWarning:Althougheveryefforthasbeenmadeforrobustness,thiscodehasnotbeenvettedbyindependent3rdparties.
strategy("PinBarStrategyv1",overlay=true)
//UserInput
usr_risk=input(title="EquityRisk(%)",type=input.integer,minval=1,maxval=100,step=1,defval=3,confirm=false)
atr_mult=input(title="StopLoss(x*ATR,Float)",type=input.float,minval=0.1,maxval=100,step=0.1,defval=1.9,confirm=false)
trd_rewd=input(title="Risk:Reward(1:x*SL,Float)",type=input.float,minval=0.1,maxval=100,step=0.1,defval=3.1,confirm=false)
sma_fast=input(title="FastMA(Period)",type=input.integer,minval=1,maxval=500,step=1,defval=20,confirm=false)
sma_slow=input(title="SlowMA(Period)",type=input.integer,minval=1,maxval=500,step=1,defval=50,confirm=false)
atr_valu=input(title="ATR(Period)",type=input.integer,minval=1,maxval=500,step=1,defval=14,confirm=false)
use_slpe=input(title="UseMASlope(Boolean)",type=input.bool,defval=true,confirm=false)
slp_long=input(title="BullSlopeAngle(Deg)",type=input.integer,minval=-90,maxval=90,step=1,defval=1,confirm=false)
slp_shrt=input(title="BearSlopeAngle(Deg)",type=input.integer,minval=-90,maxval=90,step=1,defval=-1,confirm=false)
emg_exit=input(title="ExitWhenMARe-Cross(Boolean)",type=input.bool,defval=true,confirm=false)
ent_canc=input(title="CancelEntryAfterXBars(Period)",type=input.integer,minval=1,maxval=500,step=1,defval=3,confirm=false)
//CreateIndicators
fastSMA=sma(close,sma_fast)
slowSMA=sma(close,sma_slow)
bullishPinBar=((close>open)and((open-low)>0.66*(high-low)))or((close<open)and((close-low)>0.66*(high-low)))
bearishPinBar=((close>open)and((high-close)>0.66*(high-low)))or((close<open)and((high-open)>0.66*(high-low)))
atr=atr(atr_valu)
//SpecifyTrendConditions
smaUpTrend=(fastSMA>slowSMA)and(fastSMA[1]>slowSMA[1])and(fastSMA[2]>slowSMA[2])and(fastSMA[3]>slowSMA[3])and(fastSMA[4]>slowSMA[4])
smaDnTrend=(fastSMA<slowSMA)and(fastSMA[1]<slowSMA[1])and(fastSMA[2]<slowSMA[2])and(fastSMA[3]<slowSMA[3])and(fastSMA[4]<slowSMA[4])
candleUpTrend=(close[5]>fastSMA[5])and(open[5]>fastSMA[5])and(close[6]>fastSMA[6])and(open[6]>fastSMA[6])and(close[7]>fastSMA[7])and(open[7]>fastSMA[7])and(close[8]>fastSMA[8])and(open[8]>fastSMA[8])and(close[9]>fastSMA[9])and(open[9]>fastSMA[9])and(close[10]>fastSMA[10])and(open[10]>fastSMA[10])
candleDnTrend=(close[5]<fastSMA[5])and(open[5]<fastSMA[5])and(close[6]<fastSMA[6])and(open[6]<fastSMA[6])and(close[7]<fastSMA[7])and(open[7]<fastSMA[7])and(close[8]<fastSMA[8])and(open[8]<fastSMA[8])and(close[9]<fastSMA[9])and(open[9]<fastSMA[9])and(close[10]<fastSMA[10])and(open[10]<fastSMA[10])
//SpecifyPiercingConditions
bullPierce=((low<fastSMA)and(open>fastSMA)and(close>fastSMA))or((low<slowSMA)and(open>slowSMA)and(close>slowSMA))
bearPierce=((high>fastSMA)and(open<fastSMA)and(close<fastSMA))or((high>slowSMA)and(open<slowSMA)and(close<slowSMA))
//MASlopeFunction
angle(_source)=>
rad2degree=180/3.14159265359
ang=rad2degree*atan((_source[0]-_source[1])/atr(atr_valu))
//CalculateMASlope
fastSlope=angle(fastSMA)
slowSlope=angle(slowSMA)
slopingUp=fastSlope>slp_long
slopingDn=fastSlope<slp_shrt

//SpecifyEntryConditions
longEntry=smaUpTrendandbullishPinBarandbullPierce
shortEntry=smaDnTrendandbearishPinBarandbearPierce
longEntryWithSlope=smaUpTrendandbullishPinBarandbullPierceandslopingUp
shortEntryWithSlope=smaDnTrendandbearishPinBarandbearPierceandslopingDn
//SpecifySecondaryExitConditions
longExit=crossunder(fastSMA,slowSMA)
shortExit=crossover(fastSMA,slowSMA)
//LongEntryFunction
enterlong()=>
risk=usr_risk*0.01*strategy.equity
stopLoss=low[1]-atr[1]*atr_mult
entryPrice=high[1]
units=risk/(entryPrice-stopLoss)
takeProfit=entryPrice+trd_rewd*(entryPrice-stopLoss)
strategy.entry("long",strategy.long,units,stop=entryPrice)
strategy.exit("exitlong","long",stop=stopLoss,limit=takeProfit)

//ShortEntryFunction
entershort()=>
risk=usr_risk*0.01*strategy.equity
stopLoss=high[1]+atr[1]*atr_mult
entryPrice=low[1]
units=risk/(stopLoss-entryPrice)
takeProfit=entryPrice-trd_rewd*(stopLoss-entryPrice)
strategy.entry("short",strategy.short,units,stop=entryPrice)
strategy.exit("exitshort","short",stop=stopLoss,limit=takeProfit)

//ExecuteLongEntryw/oSlope
if(longEntryanduse_slpe==false)
enterlong()

//ExecuteLongEntryw/Slope
if(longEntryWithSlopeanduse_slpe==true)
enterlong()
//ExitLongDuetoRe-Cross
if(longExitandstrategy.position_size>0andemg_exit)
strategy.order("exitlong,re-cross",strategy.short,abs(strategy.position_size))
//CanceltheLongEntry
strategy.cancel("long",barssince(longEntry)>ent_canc)
//ExecuteShortEntryw/oSlope
if(shortEntryanduse_slpe==false)
entershort()

//ExecuteShortEntryw/Slope
if(shortEntryWithSlopeanduse_slpe==true)
entershort()
//ExitShortDuetoRe-Cross
if(shortExitandstrategy.position_size<0andemg_exit)
strategy.order("exitshort,re-cross",strategy.long,abs(strategy.position_size))
//CanceltheShortEntry
strategy.cancel("short",barssince(shortEntry)>ent_canc)
//PlotMovingAveragestoChart
plot(fastSMA,color=color.red)
plot(slowSMA,color=color.blue)
//PlotPinBarstoChart
plotshape(bullishPinBar,style=shape.arrowup,location=location.abovebar,color=#FF0000,text='')
plotshape(bearishPinBar,style=shape.arrowdown,location=location.belowbar,color=#0000FF,text='')
Expand (115 lines)
