Script Name: Position management strategy framework [LM]
Author: lmatl
Description: Hi Traders,

This is backtest framework for position management of indicators based on systems that are used for position management of gambling systems. All examples describes situation that position unit is 100$ of given asset. For tracking there are used pinescript arrays. In all strategies I have built some max extremes for given strategy(not originaly part of...
PineScript code:

Pine Script™ strategy
Position management strategy framework [LM]
//@version=4
strategy("Position  management  strategy  framework  [LM]",  shorttitle="PMSF  [LM]",  overlay=true,  initial_capital=1000.0)
var  LABOUCHERE  =  'Labouchere',  var  MARTINGALE  =  'Martingale'
var  DLAMBERT  =  'D‘  Alembert',  var  OSCARS_GRIND  =  'Oscar‘s  grind'
var  FIBONACCI  =  'Fibonacci'
//  general  strategy  settings
i_startDate                                                          =  input(timestamp("02  Jan  2021  00:00  +0000"),  title="Start  Date",  type=input.time,  group="general  strategy  settings")
i_endDate                                                              =  input(timestamp("14  Apr  2099  00:00  +0000"),  title="End  Date",  type=input.time,  group="general  strategy  settings")
i_indicatorPlotting                                          =  input(false,  title='show  plots',  group="general  strategy  settings")
i_strategyOption                                                =  input(LABOUCHERE,  "Management  strategy",  options=[LABOUCHERE,  FIBONACCI,  MARTINGALE,  DLAMBERT,  OSCARS_GRIND])
//  position  sizing  settings
i_positionUnit                                                    =  input(100.0,        title="Position  unit",  group="position  sizing  settings")
i_leverage                                                            =  input(1.0,            title="leverage",  group="position  sizing  settings")
//  Labouchere  settings
i_laboucherePositionSerie                              =  input(3,            title="Labouchere  serie",  group="Labouchere  settings")
i_labouchereMaxArraySize                                =  input(10,          title="max  labouchere  serie  size",  group="Labouchere  settings")
//  Fibonacci  settings
i_fibonacciMaxArraySize                                  =  input(10,          title="max  fibonacci  serie  size",  group="Fibonacci  settings")
//  Martingale  settings
i_martingaleMult                                                =  input(2,            title="Martingale  multipler",  group="Martingale  settings")
i_isGranMartingale                                            =  input(false,    title="Gran  Martingale?",  group="Martingale  settings")
i_maxMartingaleMultiplier                              =  input(32,          title="Max  multipler",  group="Martingale  settings")
//  D  Lambert  settings
i_maxDLambertMultiplier                          =input(64,title="Maxmultipler",group="D‘Alembertsettings")
//Oscarsgrindsettings
i_maxOscarsGrindLoss=input(-100000,title="Maxpositionlosses",group="Oscar‘sgrindsettings")
varint[]positionArray=array.new_int()
varint[]positionLossTrackerArray=array.new_int()
varintfunctionReturnPlaceholder=0
//LABOUCHERE
f_labouchereArrayInit()=>
array.clear(positionArray)
forvari=1toi_laboucherePositionSerie
array.push(positionArray,i)


f_getLaboucherePosition()=>
arraySize=array.size(positionArray)

arraySize>1
?i_positionUnit/close*(array.get(positionArray,0)+array.get(positionArray,arraySize-1))*i_leverage
:i_positionUnit/close*array.get(positionArray,0)*i_leverage

f_failedLabouchereTrade()=>
arraySize=array.size(positionArray)
if(arraySize>1)
array.push(positionArray,array.get(positionArray,0)+array.get(positionArray,arraySize-1))
else
array.push(positionArray,array.get(positionArray,0))

if(arraySize+1==i_labouchereMaxArraySize)
f_labouchereArrayInit()
functionReturnPlaceholder


f_successLabouchereTrade()=>
arraySize=array.size(positionArray)


if(arraySize==1)
f_labouchereArrayInit()

if(arraySize>1)
array.remove(positionArray,0)
array.pop(positionArray)
functionReturnPlaceholder

//laboucherearrayinit
if(i_strategyOption==LABOUCHEREandarray.size(positionArray)==0)
f_labouchereArrayInit()
//LABOUCHERE
//FIBONACCI


f_getFibonacciPosition()=>
arraySize=array.size(positionArray)

arraySize>1
?i_positionUnit/close*(array.get(positionArray,arraySize-1)+array.get(positionArray,arraySize-2))*i_leverage
:i_positionUnit/close*array.get(positionArray,0)*i_leverage

f_failedFibonacciTrade()=>
arraySize=array.size(positionArray)
if(arraySize>1)
array.push(positionArray,array.get(positionArray,arraySize-1)+array.get(positionArray,arraySize-2))
else
array.push(positionArray,array.get(positionArray,0))

if(arraySize+1==i_fibonacciMaxArraySize)
array.clear(positionArray)
array.push(positionArray,1)
functionReturnPlaceholder


f_successFibonacciTrade()=>
arraySize=array.size(positionArray)


if(arraySize>1)
array.pop(positionArray)
array.pop(positionArray)

if(array.size(positionArray)==0)
array.push(positionArray,1)
functionReturnPlaceholder

//laboucherearrayinit
if(i_strategyOption==FIBONACCIandarray.size(positionArray)==0)
array.push(positionArray,1)
//FIBONACCI
//MARTINGALE
f_getMartinagalePosition()=>
positionMultiplier=array.get(positionArray,0)

i_isGranMartingale
?i_positionUnit/close*positionMultiplier*i_leverage+(i_positionUnit/close)
:i_positionUnit/close*positionMultiplier*i_leverage

f_failedMartingaleTrade()=>
positionMultiplier=array.get(positionArray,0)
value=i_maxMartingaleMultiplier>=positionMultiplier*i_martingaleMult?positionMultiplier*i_martingaleMult:1
array.set(positionArray,0,value)
functionReturnPlaceholder

f_successMartingaleTrade()=>
array.set(positionArray,0,1)
functionReturnPlaceholder
//martingalearrayinit
if(i_strategyOption==MARTINGALEandarray.size(positionArray)==0)
array.push(positionArray,1)
//MARTINGALE
//DLAMBERT
f_getDLambertPosition()=>
i_positionUnit/close*array.get(positionArray,0)*i_leverage

f_failedDLambertTrade()=>
positionMultiplier=array.get(positionArray,0)
value=i_maxDLambertMultiplier>=positionMultiplier+1?positionMultiplier+1:1
array.set(positionArray,0,value)
functionReturnPlaceholder

f_successDLambertTrade()=>
positionMultiplier=array.get(positionArray,0)
array.set(positionArray,0,positionMultiplier==1?1:positionMultiplier-1)
functionReturnPlaceholder
//dlambertarrayinit
if(i_strategyOption==DLAMBERTandarray.size(positionArray)==0)
array.push(positionArray,1)
//DLAMBERT
//OSCARS_GRIND
f_getOscarsGrindPosition()=>
i_positionUnit/close*array.get(positionArray,0)*i_leverage

f_failedOscarsGrindTrade()=>
positionMultiplier=array.get(positionArray,0)
losses=array.get(positionLossTrackerArray,0)

value=i_maxOscarsGrindLoss<=losses-positionMultiplier?positionMultiplier:1
lossPositionValue=i_maxOscarsGrindLoss<=losses-positionMultiplier?losses-positionMultiplier:0

array.set(positionArray,0,value)
array.set(positionLossTrackerArray,0,lossPositionValue)
functionReturnPlaceholder

f_successOscarsGrindTrade()=>
positionMultiplier=array.get(positionArray,0)
losses=array.get(positionLossTrackerArray,0)

value=losses+positionMultiplier>=0?1:losses+positionMultiplier>positionMultiplier+1?abs(losses):positionMultiplier+1
lossPositionValue=losses+positionMultiplier>=0?0:losses+positionMultiplier

array.set(positionArray,0,value)
array.set(positionLossTrackerArray,0,lossPositionValue)
functionReturnPlaceholder
//oscarsgrindarrayinit
if(i_strategyOption==OSCARS_GRINDandarray.size(positionArray)==0)
array.push(positionArray,1)
array.push(positionLossTrackerArray,0)
//OSCARS_GRIND
//COMMONFUNCTIONS
f_getPosition()=>
i_strategyOption==LABOUCHERE?f_getLaboucherePosition():
i_strategyOption==FIBONACCI?f_getFibonacciPosition():
i_strategyOption==MARTINGALE?f_getMartinagalePosition():
i_strategyOption==DLAMBERT?f_getDLambertPosition():
i_strategyOption==OSCARS_GRIND?f_getOscarsGrindPosition():0.0

f_successTrade()=>
i_strategyOption==LABOUCHERE?f_successLabouchereTrade():
i_strategyOption==FIBONACCI?f_successFibonacciTrade():
i_strategyOption==MARTINGALE?f_successMartingaleTrade():
i_strategyOption==DLAMBERT?f_successDLambertTrade():
i_strategyOption==OSCARS_GRIND?f_successOscarsGrindTrade():na

f_failedTrade()=>
i_strategyOption==LABOUCHERE?f_failedLabouchereTrade():
i_strategyOption==FIBONACCI?f_failedFibonacciTrade():
i_strategyOption==MARTINGALE?f_failedMartingaleTrade():
i_strategyOption==DLAMBERT?f_failedDLambertTrade():
i_strategyOption==OSCARS_GRIND?f_failedOscarsGrindTrade():na

//COMMONFUNCTIONS
//PUTYOURSTRATEGYHERE
varintlongSetup=0
longSetup:=(close>close[4])?longSetup[1]==9?0:longSetup[1]+1:0
varintshortSetup=0
shortSetup:=(close<close[4])?shortSetup[1]==9?0:shortSetup[1]+1:0
inDateRange=time>=i_startDateandtime<=i_endDate
longCondition=longSetup==2andclose>close[1]
longConditionStopLoss=longSetup[1]>=2andlongSetup[1]<9andshortSetup==1andbarssince(longCondition)==longSetup[1]-1
longConditionCloseSuccess=longSetup==9or(longConditionStopLossandclose>=close[barssince(longCondition)])
shortCondition=shortSetup==2andclose<close[1]
shortConditionStopLoss=shortSetup[1]>=2andshortSetup[1]<9andlongSetup==1andbarssince(shortCondition)==shortSetup[1]-1
shortConditionCloseSuccess=shortSetup==9or(shortConditionStopLossandclose<=close[barssince(shortCondition)])
//PUTYOURSTRATEGYHERE
//positionopeningandclosing
positionAmount=f_getPosition()
if(inDateRangeandlongCondition)
strategy.order("L",long=strategy.long,qty=positionAmount)

if(inDateRangeandshortCondition)
strategy.order("S",long=strategy.short,qty=positionAmount)

if(inDateRangeand(shortConditionCloseSuccessorlongConditionCloseSuccess))
strategy.close_all()
f_successTrade()
if(inDateRangeand((longConditionStopLossandnotlongConditionCloseSuccess)or(shortConditionStopLossandnotshortConditionCloseSuccess)))
strategy.close_all()
f_failedTrade()
//plotting
plotshape(i_indicatorPlottingandlongSetup==1?true:na,style=shape.triangledown,text="1",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandlongSetup==2?true:na,style=shape.triangledown,text="2",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandlongSetup==3?true:na,style=shape.triangledown,text="3",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandlongSetup==4?true:na,style=shape.triangledown,text="4",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandlongSetup==5?true:na,style=shape.triangledown,text="5",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandlongSetup==6?true:na,style=shape.triangledown,text="6",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandlongSetup==7?true:na,style=shape.triangledown,text="7",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandlongSetup==8?true:na,style=shape.triangledown,text="8",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandlongSetup==9?true:na,style=shape.triangledown,text="9",color=color.green,location=location.abovebar)
plotshape(i_indicatorPlottingandshortSetup==1?true:na,style=shape.triangleup,text="1",color=color.red,location=location.belowbar)
plotshape(i_indicatorPlottingandshortSetup==2?true:na,style=shape.triangleup,text="2",color=color.red,location=location.belowbar)
plotshape(i_indicatorPlottingandshortSetup==3?true:na,style=shape.triangleup,text="3",color=color.red,location=location.belowbar)
plotshape(i_indicatorPlottingandshortSetup==4?true:na,style=shape.triangleup,text="4",color=color.red,location=location.belowbar)
plotshape(i_indicatorPlottingandshortSetup==5?true:na,style=shape.triangleup,text="5",color=color.red,location=location.belowbar)
plotshape(i_indicatorPlottingandshortSetup==6?true:na,style=shape.triangleup,text="6",color=color.red,location=location.belowbar)
plotshape(i_indicatorPlottingandshortSetup==7?true:na,style=shape.triangleup,text="7",color=color.red,location=location.belowbar)
plotshape(i_indicatorPlottingandshortSetup==8?true:na,style=shape.triangleup,text="8",color=color.red,location=location.belowbar)
plotshape(i_indicatorPlottingandshortSetup==9?true:na,style=shape.triangleup,text="9",color=color.red,location=location.belowbar)
Expand (305 lines)
