Script Name: PowerX Strategy Backtest
Author: drg86
Description: This script implements the Power X trading strategy by Markus Heitkoetter and Rockwell Trading. The strategy is described in detail in "The PowerX Strategy: How to Trade Stocks and Options in Only 15 Minutes a Day" written by Markus Heitkoetter.

The Power X trading strategy uses RSI, Slow Stochastic and MACD indicators. When RSI and Slow Stochastic are both...
PineScript code:

Pine Script™ strategy
PowerX Strategy Backtest
//@version=5
strategy('PowerX  Strategy  Backtest',  overlay  =  true,  initial_capital  =  10000)
//  Make  input  options  that  configure  backtest  date  range
var  startDate  =  input.int(title  =  "Start  Date",  defval  =  15,  minval  =  1,  maxval  =  31)
var  startMonth  =  input.int(title  =  "Start  Month",  defval  =  9,  minval  =  1,  maxval  =  12)
var  startYear  =  input.int(title  =  "Start  Year",  defval  =  2019,  minval  =  1800,  maxval  =  2100)
var  endDate  =  input.int(title  =  "End  Date",  defval  =  15,  minval  =  1,  maxval  =  31)
var  endMonth  =  input.int(title  =  "End  Month",  defval  =  9,  minval  =  1,  maxval  =  12)
var  endYear  =  input.int(title  =  "End  Year",  defval  =  2021,minval  =  1800,  maxval  =  2100)

//  Make  input  options  that  select  the  direction  of  trades
var  short  =  input.bool(title  =  "Short  positions",  defval  =  false)
var  long  =  input.bool(title  =  "Long  positions",  defval  =  true)
//  Make  input  option  for  thecapitalatrisk
varcapital_at_risk=input.float(title="Capitalatrisk[%]",minval=0,maxval=100,defval=2)/100
//Makeinputoptionsforriskandreward
varrisk=input.float(title="Risk",minval=0,defval=1.5)
varreward=input.float(title="Reward",minval=0,defval=3)
//Makeinputoptionforthedurationofpendingtrades
//Ifatradeispendingformorethan<decay>timeunitsitiscancelledanda
//newtradeisopened
vardecay=input.int(title="Max.durationofpendingtrades",minval=0,defval=7)
//DefinePowerXsignal
[macdLine,signalLine,histLine]=ta.macd(close,12,26,9)
rsiLine=ta.rsi(close,7)
stochLine=ta.sma(ta.sma(ta.stoch(close,high,low,14),3),3)
signal=histLine>0andrsiLine>50andstochLine>50?'buy':histLine<=0andrsiLine<=50andstochLine<=50?'sell':'none'
palette=signal=='buy'?color.lime:signal=='sell'?color.red:color.black
plotbar(open,high,low,close,color=palette)
//Definevariablestodefineentryandexitprices
varentry=float(na)
varquantity=int(na)
varstop_loss=float(na)
vartake_profit=float(na)
//Variabletotrackthestate
//-2=pendingshort
//-1=activeshort
//0=ready
//1=activelong
//2=pendinglong
varstate=0
adr=ta.sma(high-low,7)
//Lookiftheclosetimeofthecurrentbarfallsinsidethedaterange
inDateRange=(time>=timestamp(syminfo.timezone,startYear,
startMonth,startDate,0,0))and
(time<=timestamp(syminfo.timezone,endYear,endMonth,endDate,0,0))
if(inDateRange)
//Reducethedecaytoinvalidatependingpositions
decay:=decay-1

//Ifcurrentopenpositionistoooldopenanewone
if(state==2anddecay<=0)
state:=0

//Onaneutralsignalexitall(pending)positions
if(signal=='none')
strategy.close("long")
strategy.close("short")
strategy.cancel("long")
strategy.cancel("short")
state:=0

//Onsignaldirectionchangeresetthestate
if(signal!=signal[1])
//Ifopenpositionclose
if(state==-1orstate==1)
strategy.close("long")
strategy.close("short")
//Ifpendingpositioncancel
else
strategy.cancel("long")
strategy.cancel("short")
state:=0

//Ifpendingpositionhasbeenfilledchangestatetoactive
if(state==2andstrategy.opentrades>0)
state:=1

if(state==-2andstrategy.opentrades<0)
state:=-1

//Ifactivepositionhasbeenclosedchangestatetoready
if((state==-1orstate==1)andstrategy.opentrades==0)
state:=0
//Onabuysignaldefineentryandexitpricesandplaceorders
if(signal=='buy'andlong)
if(state==0)
entry:=high+0.01
quantity:=math.floor(strategy.initial_capital*capital_at_risk/(risk*adr))
stop_loss:=entry-risk*adr
take_profit:=entry+reward*adr
state:=2
decay:=7
strategy.entry(id="long",direction=strategy.long,qty=quantity,stop=entry)
strategy.exit(id="long",qty_percent=100,limit=take_profit,stop=stop_loss)

//Onasellsignaldefineentryandexitpricesandplaceorders
if(signal=='sell'andshort)
if(state==0)
entry:=low-0.01
quantity:=math.floor(strategy.initial_capital*capital_at_risk/(risk*adr))
stop_loss:=entry+risk*adr
take_profit:=entry-reward*adr
state:=-2
decay:=7
strategy.entry(id="short",direction=strategy.short,qty=quantity,stop=entry)
strategy.exit(id="short",qty_percent=100,limit=take_profit,stop=stop_loss)

//Debugging
plotchar(state,"state","",location.top)
plotchar(decay,"decay","",location.top)
plotchar(adr,"ADR","",location.top)
plotchar(entry,"entry","",location.top)
plotchar(quantity,"quantity","",location.top)
plotchar(stop_loss,"stoploss","",location.top)
plotchar(take_profit,"takeprofit","",location.top)
Expand (130 lines)
