Script Name: Profit Maximizer PMax Strategy - Long-Short
Author: melihtuna
Description: I developed a different strategy perspective for the Profit Maximizer PMax indicator prepared by Kıvanç Özbilgiç.

When you come to the settings section;
- You will see 2 options as Straregy Type. You can test the price and pmax intersections as different strategies.
- I added the Long-Short option for spot traders to calculate the profitability rate correctly....
PineScript code:

Pine Script™ strategy
Profit Maximizer PMax Strategy - Long-Short
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  melihtuna
//developer:  @KivancOzbilgic
//author:  @KivancOzbilgic
//stretegy  converter:  @crypto_melih
//@version=4
strategy("Profit  Maximizer  Strategy  Long-Short",  shorttitle="PMax-Strategy",  overlay=true,  default_qty_type=strategy.cash,  default_qty_value=10000,  initial_capital=10000,  currency=currency.USD,  commission_value=0,  commission_type=strategy.commission.percent)
src  =  input(hl2,  title="Source")
Periods  =  input(title="ATR  Length",  type=input.integer,  defval=10)
Multiplier  =  input(title="ATR  Multiplier",  type=input.float,  step=0.1,  defval=3.0)
mav  =  input(title="Moving  Average  Type",  defval="EMA",  options=["SMA",  "EMA",  "WMA",  "TMA",  "VAR",  "WWMA",  "ZLEMA",  "TSF"])
length  =input(10,  "Moving  Average  Length",  minval=1)
condition  =  input(title="Signal  Type",  defval="Only  Crossing  Signals",  options=["Only  Crossing  Signals",  "Only  Price/Pmax  Crossing  Signals"])
changeATR=  input(title="Change  ATR  Calculation  Method  ?",  type=input.bool,  defval=true)
showsupport  =  input(title="Show  Moving  Average?",  type=input.bool,  defval=true)
//showsignalsk  =  input(title="Show  Crossing  Signals?",  type=input.bool,  defval=true)
//showsignalsc  =  input(title="Show  Price/Pmax  Crossing  Signals?",  type=input.bool,  defval=false)
highlighting  =  input(title="Highlighter  On/Off  ?",  type=input.bool,  defval=true)
long_short  =  input(defval  =  false,  title  =  "Long-Short",  type=input.bool)
atr2  =  sma(tr,  Periods)
atr=  changeATR  ?  atr(Periods)  :  atr2
valpha=2/(length+1)
vud1=src>src[1]  ?  src-src[1]  :  0
vdd1=src<src[1]  ?  src[1]-src  :  0
vUD=sum(vud1,9)
vDD=sum(vdd1,9)
vCMO=nz((vUD-vDD)/(vUD+vDD))
VAR=0.0
VAR:=nz(valpha*abs(vCMO)*src)+(1-valpha*abs(vCMO))*nz(VAR[1])
wwalpha  =  1/  length
WWMA  =  0.0
WWMA  :=  wwalpha*src  +  (1-wwalpha)*nz(WWMA[1])
zxLag  =  length/2==round(length/2)  ?  length/2  :  (length  -  1)  /  2
zxEMAData  =  (src  +  (src  -  src[zxLag]))
ZLEMA  =  ema(zxEMAData,  length)
lrc  =  linreg(src,  length,  0)
lrc1  =  linreg(src,length,1)
lrs  =  (lrc-lrc1)
TSF  =  linreg(src,  length,  0)+lrs
getMA(src,  length)  =>
        ma  =  0.0
        if  mav  ==  "SMA"
                ma  :=  sma(src,  length)
                ma
        if  mav  ==  "EMA"
                ma  :=  ema(src,  length)
                ma
        if  mav  ==  "WMA"
                ma  :=  wma(src,  length)
                ma
        if  mav  ==  "TMA"
                ma  :=  sma(sma(src,  ceil(length  /  2)),  floor(length  /  2)  +  1)
                ma
        if  mav  ==  "VAR"
                ma  :=  VAR
                ma
        if  mav  ==  "WWMA"
                ma  :=  WWMA
                ma
        if  mav  ==  "ZLEMA"
                ma  :=  ZLEMA
                ma
        if  mav  ==  "TSF"
    ma:=TSF
ma
ma

MAvg=getMA(src,length)
longStop=MAvg-Multiplier*atr
longStopPrev=nz(longStop[1],longStop)
longStop:=MAvg>longStopPrev?max(longStop,longStopPrev):longStop
shortStop=MAvg+Multiplier*atr
shortStopPrev=nz(shortStop[1],shortStop)
shortStop:=MAvg<shortStopPrev?min(shortStop,shortStopPrev):shortStop
dir=1
dir:=nz(dir[1],dir)
dir:=dir==-1andMAvg>shortStopPrev?1:dir==1andMAvg<longStopPrev?-1:dir
PMax=dir==1?longStop:shortStop
plot(showsupport?MAvg:na,color=#0585E1,linewidth=2,title="MovingAvgLine")
pALL=plot(PMax,color=color.red,linewidth=2,title="PMax",transp=0)
alertcondition(cross(MAvg,PMax),title="CrossAlert",message="PMax-MovingAvgCrossing!")
alertcondition(crossover(MAvg,PMax),title="CrossoverAlarm",message="MovingAvgBUYSIGNAL!")
alertcondition(crossunder(MAvg,PMax),title="CrossunderAlarm",message="MovingAvgSELLSIGNAL!")
alertcondition(cross(src,PMax),title="PriceCrossAlert",message="PMax-PriceCrossing!")
alertcondition(crossover(src,PMax),title="PriceCrossoverAlarm",message="PRICEOVERPMax-BUYSIGNAL!")
alertcondition(crossunder(src,PMax),title="PriceCrossunderAlarm",message="PRICEUNDERPMax-SELLSIGNAL!")
buySignalk=crossover(MAvg,PMax)
//plotshape(buySignalkandshowsignalsk?PMax*0.995:na,title="Buy",text="Buy",location=location.absolute,style=shape.labelup,size=size.tiny,color=color.green,textcolor=color.white,transp=0)
sellSignallk=crossunder(MAvg,PMax)
//plotshape(sellSignallkandshowsignalsk?PMax*1.005:na,title="Sell",text="Sell",location=location.absolute,style=shape.labeldown,size=size.tiny,color=color.red,textcolor=color.white,transp=0)
buySignalc=crossover(src,PMax)
//plotshape(buySignalcandshowsignalsc?PMax*0.995:na,title="Buy",text="Buy",location=location.absolute,style=shape.labelup,size=size.tiny,color=#0F18BF,textcolor=color.white,transp=0)
sellSignallc=crossunder(src,PMax)
//plotshape(sellSignallcandshowsignalsc?PMax*1.005:na,title="Sell",text="Sell",location=location.absolute,style=shape.labeldown,size=size.tiny,color=#0F18BF,textcolor=color.white,transp=0)
mPlot=plot(ohlc4,title="",style=plot.style_circles,linewidth=0,display=display.none)
longFillColor=highlighting?(MAvg>PMax?color.green:na):na
shortFillColor=highlighting?(MAvg<PMax?color.red:na):na
fill(mPlot,pALL,title="UpTrendHighligter",color=longFillColor)
fill(mPlot,pALL,title="DownTrendHighligter",color=shortFillColor)
if(condition=="OnlyCrossingSignals")
strategy.entry("BUY",strategy.long,when=buySignalk)
else
strategy.entry("BUY",strategy.long,when=buySignalc)
if(long_short)
if(condition=="OnlyCrossingSignals")
strategy.entry("SELL",strategy.short,when=sellSignallk)
else
strategy.entry("SELL",strategy.short,when=sellSignallc)
else
if(condition=="OnlyCrossingSignals")
strategy.close("BUY",when=sellSignallk)
else
strategy.close("BUY",when=sellSignallc)





Expand (130 lines)
