Script Name: PSAR + EMA-TEMA-RSI-OBV
Author: UnknownUnicorn19826629
Description: The Parabolic Stop-and-Reservse (PSAR) is a trend indicator, intended to capture reversal signals and show entry and exit points.  The PSAR is bullish when the PSAR is below the candle body (usually indicated by a dot) and bearish when the PSAR is above the candle body.  The PSAR generally only moves in the direction of the trend, making it useful for markets with...
PineScript code:

Pine Script™ strategy
PSAR + EMA/TEMA/RSI/OBV
//
//  ██╗            █████╗  ███████╗  ██████╗██╗██╗      ██╗██╗  ██████╗  ██╗      ██╗███████╗        ███╗      ███╗  ██████╗  ███╗      ██╗██╗    ██╗
//  ██║          ██╔══██╗██╔════╝██╔════╝██║██║      ██║██║██╔═══██╗██║      ██║██╔════╝        ████╗  ████║██╔═══██╗████╗    ██║██║  ██╔╝
//  ██║          ███████║███████╗██║          ██║██║      ██║██║██║      ██║██║      ██║███████╗        ██╔████╔██║██║      ██║██╔██╗  ██║█████╔╝
//  ██║          ██╔══██║╚════██║██║          ██║╚██╗  ██╔╝██║██║      ██║██║      ██║╚════██║        ██║╚██╔╝██║██║      ██║██║╚██╗██║██╔═██╗
//  ███████╗██║    ██║███████║╚██████╗██║  ╚████╔╝  ██║╚██████╔╝╚██████╔╝███████║        ██║  ╚═╝  ██║╚██████╔╝██║  ╚████║██║    ██╗
//  ╚══════╝╚═╝    ╚═╝╚══════╝  ╚═════╝╚═╝    ╚═══╝    ╚═╝  ╚═════╝    ╚═════╝  ╚══════╝        ╚═╝          ╚═╝  ╚═════╝  ╚═╝    ╚═══╝╚═╝    ╚═╝
//                                                                                                                                              https://www.tradingview.com/u/LasciviousMonk/
//                                                                                                                                                                                                        ©  LasciviousMonk
//
//
//    This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//    This  script  provided  freely.    No  guarantee  of  functionality  is  provided.    You  are  welcome  to  use,  revise,  or  modify
//    this  code  in  any  way  you  wish.    However,  I  kindly  request  that  you  publish  any  scripts  originating  from  this  code  as
//    'Public'.    Please  do  not  use  this  code  as  a  basis  for  "Protected"  or  "Invite  Only"  scripts.
//
//
//  PSAR  +  EMA  +  TEMA  combines  Parabolic  PSAR  plus  EMA  and  TEMA  trendlines.
//            -  EMA  and  TEMA  crossovers  have  an  up  or  down  triangle  to  indicate  direction  of  cross.    Please  note
//                    that  because  these  are  Moving  Averages  (MAs),  the  triangle  may  not  exactly  line  up  with  the  crossover.
//            -  Added  MESA  Adaptive  Moving  Average  (eMAMA).    Crossovers  of  the  fast  and  slow  eMAMA  may  be  used  instead  of
//                    EMA  or  TEMA.
//            -  Added  third  EMA  line.    May  be  used  to  filter  entries.    For  example,  set  the  additional  EMA  to  200.    Buy  signals
//                    wil  only  be  sent  if  the  price  is  greater  than  the  additional  EMA.
//            -  Added  RSI  and  OBV  as  alternative  PSAR  confirmations.
//
//  "Traffic  Light"  table:  summarizes  PSAR,  RSI,  SRSI,  TEMA,  EMA,  eMAMA,  MACD,  OBV,  and  CMF  indicators  in  a  table.
//    This  is  intended  as  a  quick  "heads  up",  not  to  replace  the  indicators  themselves.
//            -  Arrows  indicate  direction  of  change  since  the  last  bar.
//            -  Moving  average  indicators  are  indicated  as  green  if  the  fast  MA  >  slow  MA  and  fast  [T]EMA  is  increasing,  red  otherwise.
//                    [T]EMA  will  be  yellow  if  fast  MA  has  increased  over  the  last  2  periods  but  fast  MA  <  slow  MA.
//            -  PSAR  is  as  green  if  the  PSAR  is  increasing,  red  if  it  is  decreasing.
//            -  RSI  is  indicated  as  green  if  RSI  <  oversold,  red  if  RSI  >  overbought,  yellow  otherwise.
//            -  SRSI  is  indicated  as  green  K  <  oversold,  and  red  if  K  >  overbought.    If  oversold  <  K  <  overbought,
//                    green  if  K  >  D  and  red  if  K  <  D.
//            -  MACD,  OBV  and  CMF  are  green  if  bullish,  red  if  bearish.
//
//
//    Suggestions  for  use:
//            -  Use  fast  EMA  crossing  above  slow  EMA  as  a  confirmation  for  PSAR  signals.
//            -  TEMA  or  eMAMA  can  also  be  used  for  confirmation  signals  insead.
//            -  Instead  of  using  a  moving  average  (EMA,  TEMA,  etc)  for  confirmation,  you  may  use  RSI  or  OBV.
//            -  The  "traffic  light"  table  is  intended  as  a  "heads  up"  to  call  your  attention  to  other  indicators
//                    you  may  want  to  check.    I  suggest  Cipher  B/VMC  Cipher_B,  Neglected  Volume,  and/or  CM_Ult_MacD_MTF
//                    as  useful  comparions.
//
//  Please  don't  rely  solely  on  the  table.    It  is  intended  to  alert  you  to  look  more  closely  at  a  plot,  not  to
//        provide  all  the  information  you  need  to  enter  or  exit  a  position.    I  find  the  table  to  be  a  nice  companion
//        to  VMC  Cipher_B,  which  can  be  overwhelming  in  its  complexity.
//
//  Code  used:
//            -  TEMA  With  Alert  by  BerkSay
//            -  Parabolic  SAR  by  Alex  Orekhov  (everget)
//            -  Ehlers  MESA  Adaptive  Moving  Average  [LazyBear]
//            -  EMA,  RSI  and  SRSI  built-ins.
//@version=4
strategy(overlay=true,  title="PSAR  +  EMA/TEMA/RSI/OBV",  currency  =  'USD',  shorttitle="PSAR+",
  pyramiding  =  0,  default_qty_type=strategy.percent_of_equity,  default_qty_value=20,
  initial_capital=5000,  calc_on_every_tick=true,  calc_on_order_fills=false,
  commission_type=strategy.commission.percent,  commission_value=0.1)
//  ------------------------------------------------<[  ColorConstants]>----------------------------------------------
//ColorvaluesusedfromPineMagic.https://www.tradingview.com/script/yyDYIrRQ-Pine-Color-Magic-and-Chart-Theme-Simulator/
vartransparent=color.new(color.black,100)
vardarkpurple=#550055,dpurple=darkpurple//Aliasfordarkpurple,Notrecommendedforuseon"DarkCharts"
varpurple=#990099
varfuchsia=#FF00FF
varviolet=#AA00FF
varhanpurple=#6000FF
varblue=#0000FF
varcichlid=#0040FF
varazure=#0080FF
varskyblue=#00C0FF
varaqua=#00FFFF//Notrecommendedforuseon"LightCharts"with1pxlinethickness
varmint=#00FF80
varlime=#00FF00
varchartreuse=#80FF00
varyellow=#FFFF00//Notrecommendedforuseon"LightCharts"
varamber=#FFCC00
varorange=#FF8000
varredorange=#FF4000
varred=#FF0000
varhotpink=#FF0080
varpink=#FF80FF//Notrecommendedforuseon"LightCharts"
//------------------------------------------------<[UserInput]>---------------------------------------------------
sourceGlobal=input(title="Sourceforindicator",defval=close,type=input.source,group="Global")
tradeLong=input(title="Createlongpositions?",defval=true,type=input.bool,group="Global")
tradeShort=input(title="Createshortpositions?",defval=false,type=input.bool,group="Global")
showPSAR=input(true,"ShowPSAR?",group="PSAR")
psarStart=input(title="PSARStart",type=input.float,step=0.001,defval=0.02,group="PSAR")
psarIncrement=input(title="PSARIncrement",type=input.float,step=0.001,defval=0.02,group="PSAR")
psarMaximum=input(title="PSARMaximum",type=input.float,step=0.01,defval=0.2,group="PSAR")
psarConfirmation=input(title="Confirmationsignal:",defval="EMA",
options=["EMA","TEMA","eMAMA","RSI","OBV"],group="PSAR")
psarHighlightStartPoints=input(title="PSARHighlightStartPoints?",type=input.bool,defval=true,group="PSAR")
psarShowLabels=input(title="PSARShowBuy/SellLabels?",type=input.bool,defval=true,group="PSAR")
psarHighlightState=input(title="PSARHighlightState?",type=input.bool,defval=false,group="PSAR")
colorPSARLong=input(title="Long",type=input.color,defval=lime,group="PSAR",inline="colors")
colorPSARShort=input(title="Short",type=input.color,defval=red,group="PSAR",inline="colors")
useSL=input(defval=false,type=input.bool,title="SetstoplosstoPSARplot?")
showTEMA=input(false,"ShowTEMA?",group="TripleEMA",inline="showTEMA")
showTEMAfill=input(title="ShadeTEMA?",defval=false,type=input.bool,group="TripleEMA",inline="showTEMA")
lengthTEMAFast=input(title="TEMAFastlength",defval=13,minval=1,group="TripleEMA",inline="TemaFast")
colorTEMAFast=input(title="",type=input.color,defval=lime,inline="TemaFast",group="TripleEMA")
lengthTEMASlow=input(title="TEMASlowlength",defval=34,minval=1,group="TripleEMA",inline="TemaSlow")
colorTEMASlow=input(title="",type=input.color,defval=red,group="TripleEMA",inline="TemaSlow")
thicknessTEMA=input(title="Linethickness",defval=2,type=input.integer,minval=1,maxval=4,step=1,group="TripleEMA")
showEMA=input(defval=true,type=input.bool,title="ShowEMA?",group="EMA",inline="showEMA")
showEMAfill=input(title="ShadeEMA?",defval=false,type=input.bool,group="EMA",inline="showEMA")
lengthEMAFast=input(9,title='EMAFastLength',step=1,type=input.integer,group="EMA",inline="EmaFast")
colorEMAFast=input(title="",type=input.color,defval=lime,inline="EmaFast",group="EMA")
lengthEMASlow=input(21,title='EMASlowLength',step=1,type=input.integer,group="EMA",inline="EmaSlow")
colorEMASlow=input(title="",type=input.color,defval=red,group="EMA",inline="EmaSlow")
lengthEMA200=input(200,title='EMAAdditionalLength',step=1,type=input.integer,group="EMA",inline="EMA200")
colorEMA200=input(title="",type=input.color,defval=orange,group="EMA",inline="EMA200")
filterEMA200=input(title="Useasfilter?",defval=false,type=input.bool,group="EMA",inline="EMA200",tooltip="BuyandsellsignalsarefilteredontheadditionalEMAline,commonlysetto200.ThistakeseffectevenifthePSARconfirmationissettosomethingotherthanEMA.")
thicknessEMA=input(title="Linethickness",defval=2,type=input.integer,minval=1,maxval=4,step=1,group="EMA")
lengthRSI=input(title="RSILength",type=input.integer,defval=14,group="RSI")
rsiOverbought=input(title="OverboughtLevel",type=input.integer,defval=60,group="RSI",inline="levels")
rsiOversold=input(title="OversoldLevel",type=input.integer,defval=40,group="RSI",inline="levels")
showeMAMA=input(defval=false,title="ShoweMAMA?",type=input.bool,group="Ehler'sMESAAdaptiveMovingAverage",inline="fill")
showEMAMAfill=input(title="ShadeeMAMA?",defval=false,type=input.bool,group="Ehler'sMESAAdaptiveMovingAverage",inline="fill")
fastlimitEMAMA=input(.5,title="FastLimit",group="Ehler'sMESAAdaptiveMovingAverage")
slowlimitEMAMA=input(.05,title="SlowLimit",group="Ehler'sMESAAdaptiveMovingAverage")
thicknessEMAMA=input(title="Linethickness",defval=2,type=input.integer,minval=1,maxval=4,step=1,group="Ehler'sMESAAdaptiveMovingAverage")
coloreMAMA=input(title="eMAMA",type=input.color,defval=lime,group="Ehler'sMESAAdaptiveMovingAverage",inline="colors")
coloreFAMA=input(title="eFAMA",type=input.color,defval=red,group="Ehler'sMESAAdaptiveMovingAverage",inline="colors")
lengthOBV=input(defval=20,title="OBVLength",type=input.integer,group="OnBalanceVolume")
emaOBV=input(defval=9,title="EMAlength",type=input.integer,group="OnBalanceVolume")
lengthStoch=input(14,"StochasticLength",minval=1,group="SRSI")
smoothK=input(3,"SRSIKSmoothing",minval=1,group="SRSI")
smoothD=input(3,"SRSIDSmoothing",minval=1,group="SRSI")
srsiOverbought=input(defval=80,title="Overboughtlevel",type=input.integer,group="SRSI",inline="levels")
srsiOversold=input(defval=20,title="Oversoldlevel",type=input.integer,group="SRSI",inline="levels")
lengthMACDfast=input(title="FastLength",type=input.integer,defval=12,group="MACD")
lengthMACDslow=input(title="SlowLength",type=input.integer,defval=26,group="MACD")
lengthMACDsignal=input(title="SignalSmoothing",type=input.integer,minval=1,maxval=50,defval=9,group="MACD")
lengthCMF=input(20,minval=1,group="ChaikenMoneyFlow")
showTable=input(defval=false,title="Showsummarytable?",type=input.bool,group="SummaryTable")
tablePosition=input(title="SummaryTablePosition",defval=position.bottom_left,
options=[position.bottom_left,
position.top_left,position.bottom_right,position.top_right],group="SummaryTable")
tableTextSize=input(title="TableTextSize",defval=size.tiny,
options=[size.auto,size.tiny,size.small,size.normal,size.large,size.huge],group="SummaryTable")
useDateRange=input(defval=true,title="Limitbacktestingbydate",type=input.bool,group="Limitbydate",
tooltip="Limitwindowforbacktesting.ThisallowsyoutocomparedifferentTFsoverthesameperiod.")
rangeType=input(defval="30Days",title="Daterange:",options=["Custom","30Days","90Days","180Days","YeartoDate"],group="Limitbydate")
startDate=input(title="StartDate(DD/MM/YYYY)",type=input.time,
defval=timestamp("1Jan20211:01-0400"),group="Limitbydate")
endDate=input(title="EndDate(DD/MM/YYYY)",type=input.time,
defval=timestamp("31Dec210019:59-0400"),group="Limitbydate",tooltip="Youlikelywanttoleavethisfarinthefuture.")
startDate:=rangeType=="Custom"?startDate:
rangeType=="30Days"?timenow-2592000000:
rangeType=="90Days"?timenow-7776000000:
rangeType=="180Days"?timenow-15552000000:
rangeType=="YeartoDate"?timestamp(syminfo.timezone,year(timenow),01,01,00,01):na

inDateRange=(time>=startDate)and(time<endDate)
inDateRange:=useDateRange?inDateRange:1
//------------------------------------------------<[VariableDeclarations]>----------------------------------------------
varboolpsarConfirmationBuy=na
varboolpsarConfirmationSell=na
varfloateMAMA=na
varfloateFAMA=na
varfloathistoricalHigh=0//forOBVscaling
//-------------------------------------------------------<[Functions]>----------------------------------------------------
fDirection(series,length)=>
rising(series,length)?"↑":"↓"
fTEMA(sourceTEMA,length)=>
Tema1=ema(sourceTEMA,length)
Tema2=ema(Tema1,length)
Tema3=ema(Tema2,length)
3*Tema1-3*Tema2+Tema3
fMAMA(sourceEMAMA,slowlimitEMAMA,fastlimitEMAMA)=>
varfloatp=na
varfloati2=na
varfloatq2=na
varfloatre=na
varfloatim=na
varfloatspp=na
sp=(4*sourceEMAMA+3*sourceEMAMA[1]+2*sourceEMAMA[2]+sourceEMAMA[3])/10.0
dt=(.0962*sp+.5769*nz(sp[2])-.5769*nz(sp[4])-.0962*nz(sp[6]))*(.075*nz(p[1])+.54)
q1=(.0962*dt+.5769*nz(dt[2])-.5769*nz(dt[4])-.0962*nz(dt[6]))*(.075*nz(p[1])+.54)
i1=nz(dt[3])
jI=(.0962*i1+.5769*nz(i1[2])-.5769*nz(i1[4])-.0962*nz(i1[6]))*(.075*nz(p[1])+.54)
jq=(.0962*q1+.5769*nz(q1[2])-.5769*nz(q1[4])-.0962*nz(q1[6]))*(.075*nz(p[1])+.54)
i2_=i1-jq
q2_=q1+jI
i2:=.2*i2_+.8*nz(i2[1])
q2:=.2*q2_+.8*nz(q2[1])
re_=i2*nz(i2[1])+q2*nz(q2[1])
im_=i2*nz(q2[1])-q2*nz(i2[1])
re:=.2*re_+.8*nz(re[1])
im:=.2*im_+.8*nz(im[1])
p1=iff(im!=0andre!=0,360/atan(im/re),nz(p[1]))
p2=iff(p1>1.5*nz(p1[1]),1.5*nz(p1[1]),iff(p1<0.67*nz(p1[1]),0.67*nz(p1[1]),p1))
p3=iff(p2<6,6,iff(p2>50,50,p2))
p:=.2*p3+.8*nz(p3[1])
spp:=.33*p+.67*nz(spp[1])
phaseEMAMA=atan(q1/i1)
dphase_=nz(phaseEMAMA[1])-phaseEMAMA
dphase=iff(dphase_<1,1,dphase_)
alpha_=fastlimitEMAMA/dphase
alpha=iff(alpha_<slowlimitEMAMA,slowlimitEMAMA,iff(alpha_>fastlimitEMAMA,fastlimitEMAMA,alpha_))
fOBV(src)=>
changeOBV=change(src)
cum(changeOBV>0?volume:changeOBV<0?-volume:0*volume)
//-------------------------------------------<[VariableCalculations]>------------------------------------------
temaSlow=fTEMA(sourceGlobal,lengthTEMASlow)
temaFast=fTEMA(sourceGlobal,lengthTEMAFast)
shortTema=crossover(temaSlow,temaFast)
longTema=crossunder(temaSlow,temaFast)
fillTema=temaFast>temaSlow?color.new(colorTEMAFast,80):color.new(colorTEMASlow,80)
emaFast=ema(sourceGlobal,lengthEMAFast)
emaSlow=ema(sourceGlobal,lengthEMASlow)
ema200=ema(sourceGlobal,lengthEMA200)
longEMA=crossover(emaFast,emaSlow)
shortEMA=crossunder(emaFast,emaSlow)
fillEMA=emaFast>emaSlow?color.new(colorEMAFast,80):color.new(colorEMASlow,80)
cumOBV=fOBV(sourceGlobal)
oscOBV=(cumOBV-ema(cumOBV,lengthOBV))
changeOBV=change(sourceGlobal)
shortOBV=ema(cumOBV,lengthOBV)
psar=sar(psarStart,psarIncrement,psarMaximum)
psarDir=psar<close?1:-1
colorPSAR=psarDir==1?color.new(#3388bb,0):color.new(#fdcc02,0)
colorPSARFill=psarHighlightState?(psarDir==1?color.new(colorPSARLong,90):color.new(colorPSARShort,90)):na
psarChangeCond=psarDir!=psarDir[1]
valueRSI=rsi(sourceGlobal,lengthRSI)
ifpsarConfirmation=="EMA"
ifemaFast>emaSlow
psarConfirmationBuy:=true
psarConfirmationSell:=false
elseifemaFast<emaSlow
psarConfirmationSell:=true
psarConfirmationBuy:=false
elseifpsarConfirmation=="TEMA"
iftemaFast>temaSlow
psarConfirmationBuy:=true
psarConfirmationSell:=false
elseiftemaFast<temaSlow
psarConfirmationSell:=true
psarConfirmationBuy:=false
elseifpsarConfirmation=="eMAMA"
ifeMAMA>eFAMA
psarConfirmationBuy:=true
psarConfirmationSell:=false
elseifeMAMA<eFAMA
psarConfirmationSell:=true
psarConfirmationBuy:=false
elseifpsarConfirmation=="RSI"
ifvalueRSI<40
psarConfirmationBuy:=true
psarConfirmationSell:=false
elseifvalueRSI>60
psarConfirmationSell:=true
psarConfirmationBuy:=false
elseifpsarConfirmation=="OBV"
ifoscOBV>0
psarConfirmationBuy:=true
psarConfirmationSell:=false
elseifoscOBV<0
psarConfirmationSell:=true
psarConfirmationBuy:=false
psarBuySignal=psarDir==1andpsarDir[1]==-1and(filterEMA200?open>ema200:true)andinDateRange
psarSellSignal=psarDir==-1andpsarDir[1]==1and(filterEMA200?open<ema200:true)andinDateRange
eMAMA:=fMAMA(sourceGlobal,slowlimitEMAMA,fastlimitEMAMA)*sourceGlobal+(1-fMAMA(sourceGlobal,slowlimitEMAMA,fastlimitEMAMA))*nz(eMAMA[1])
eFAMA:=.5*fMAMA(sourceGlobal,slowlimitEMAMA,fastlimitEMAMA)*eMAMA+(1-.5*fMAMA(sourceGlobal,slowlimitEMAMA,fastlimitEMAMA))*nz(eFAMA[1])
longMAMA=crossover(eMAMA,eFAMA)
shortMAMA=crossunder(eMAMA,eFAMA)
fillEMAMA=eMAMA>eFAMA?color.new(coloreMAMA,80):color.new(coloreFAMA,80)
srsiK=sma(stoch(valueRSI,valueRSI,valueRSI,lengthStoch),smoothK)
srsiD=sma(srsiK,smoothD)
fastMACD=ema(sourceGlobal,lengthMACDfast)
slowMACD=ema(sourceGlobal,lengthMACDslow)
macd=fastMACD-slowMACD
signalMACD=ema(macd,lengthMACDsignal)
adCMF=close==highandclose==loworhigh==low?0:((2*close-low-high)/(high-low))*volume
mfCMF=sum(adCMF,lengthCMF)/sum(volume,lengthCMF)
//==================================//
//---->ConditionalParameters<----//
//==================================//

//==================================//
//------->RiskMitigation<--------//
//==================================//

//==================================//
//-------->LogicalOrder<---------//
//==================================//

//-------------------------------------------<[GraphicalDisplay]>------------------------------------------
//TEMAplots
plotTemaSlow=plot(showTEMA?temaSlow:na,color=color.new(colorTEMASlow,20),title="TEMASlowplot",linewidth=thicknessTEMA)
plotTemaFast=plot(showTEMA?temaFast:na,color=color.new(colorTEMAFast,20),title="TEMAFastplot",linewidth=thicknessTEMA)
plotshape(showTEMAandlongTema?temaFast:na,style=shape.triangleup,location=location.absolute,
size=size.tiny,title="TEMACrossUp",color=color.new(colorTEMAFast,10))
plotshape(showTEMAandshortTema?temaSlow:na,style=shape.triangledown,location=location.absolute,
size=size.tiny,title="TEMACrossDown",color=color.new(colorTEMASlow,10))
fill(plotTemaFast,plotTemaSlow,color=showTEMAfill?fillTema:transparent,title="TEMAfill")
//EMAplots
plotEmaFast=plot(showEMA?emaFast:na,title='EMAFastPlot',color=colorEMAFast,linewidth=thicknessEMA)
plotEmaSlow=plot(showEMA?emaSlow:na,title='EMASlowPlot',color=colorEMASlow,linewidth=thicknessEMA)
plotEMA200=plot(showEMA?ema200:na,title='EMAAdditionalPlot',color=colorEMA200,linewidth=thicknessEMA)
plotshape(showEMAandlongEMA?emaFast:na,style=shape.triangleup,location=location.absolute,size=size.tiny,
title="EMACrossUp",color=colorEMAFast)
plotshape(showEMAandshortEMA?emaFast:na,style=shape.triangledown,location=location.absolute,size=size.tiny,
title="EMACrossDown",color=colorEMASlow)
fill(plotEmaFast,plotEmaSlow,color=showEMAfill?fillEMA:transparent,title="EMAfill")
//PSARplots
psarPlot=plot(showPSAR?psar:na,title="PSAR",style=plot.style_circles,linewidth=1,color=colorPSAR)
plotshape(showPSARandpsarBuySignalandpsarHighlightStartPoints?psar:na,title="PSARLongStart",location=location.absolute,
style=shape.circle,size=size.tiny,color=colorPSARLong)
plotshape(showPSARandpsarBuySignalandpsarShowLabelsandpsarConfirmationBuy?psar:na,title="PSARBuyLabel",text="Buy",location=location.absolute,
style=shape.labelup,size=size.tiny,color=colorPSARLong,textcolor=color.white)
plotshape(showPSARandpsarSellSignalandpsarHighlightStartPoints?psar:na,title="PSARShortStart",location=location.absolute,
style=shape.circle,size=size.tiny,color=colorPSARShort)
plotshape(showPSARandpsarSellSignalandpsarShowLabelsandpsarConfirmationSell?psar:na,title="PSARSellLabel",text="Sell",location=location.absolute,
style=shape.labeldown,size=size.tiny,color=colorPSARShort,textcolor=color.white)
psarMidPricePlot=plot(ohlc4,title="",display=display.none,editable=false)
fill(psarMidPricePlot,psarPlot,title="PSARTradeStateFilling",color=colorPSARFill)
ploteMAMA=plot(showeMAMA?eMAMA:na,title="Ehler'sMAMA",linewidth=thicknessEMAMA,style=plot.style_line,color=coloreMAMA)
ploteFAMA=plot(showeMAMA?eFAMA:na,title="Ehler'sFAMA",linewidth=thicknessEMAMA,style=plot.style_line,color=coloreFAMA)
plotshape(showeMAMAandlongMAMA?eFAMA:na,style=shape.triangleup,location=location.absolute,size=size.tiny,title="eMAMACrossUp",
color=color.new(coloreMAMA,10))
plotshape(showeMAMAandshortMAMA?eFAMA:na,style=shape.triangledown,location=location.absolute,size=size.tiny,title="eMAMACrossDown",
color=color.new(coloreFAMA,10))
fill(ploteMAMA,ploteFAMA,color=showEMAMAfill?fillEMAMA:transparent,title="eMAMAfill")
//---------------------------------------------------<[StrategyExecution]>-------------------------------------------------
strategy.entry(id="long",long=strategy.long,comment="enL",when=psarBuySignalandpsarConfirmationBuyandtradeLong)
ifuseSL
strategy.exit(id="long",stop=psar,comment="SL")
strategy.close(id="long",comment="exL",when=psarSellSignalandpsarConfirmationSellandtradeLong)
strategy.entry(id="short",long=strategy.short,comment="enS",when=psarSellSignalandpsarConfirmationSellandtradeShort)
ifuseSL
strategy.exit(id="short",stop=psar,comment="SL")
strategy.close(id="short",comment="exS",when=psarBuySignalandpsarConfirmationBuyandtradeShort)
//-------------------------------------------------------<[Tables]>---------------------------------------------------------
//Showsredforbearishsignals,greenforbullishsignals.
vartablesummaryTable=table.new(tablePosition,3,3)

if(barstate.islastandshowTable)
table.cell(summaryTable,0,0,"PSAR",text_size=tableTextSize,bgcolor=psarDir==1?color.green:color.red)
rsiDirection=fDirection(valueRSI,1)
table.cell(summaryTable,0,1,"RSI"+tostring(round(valueRSI,0))+rsiDirection,text_size=tableTextSize,
bgcolor=iff(valueRSI>rsiOverbought,color.red,iff(valueRSI<rsiOversold,color.green,color.yellow)))
srsiDirection=fDirection(srsiK,1)
table.cell(summaryTable,0,2,"K"+tostring(round(srsiK,0))+srsiDirection,text_size=tableTextSize,
bgcolor=iff(srsiK>srsiOverbought,color.red,iff(srsiK<srsiOversold,color.green,srsiK>srsiD?color.green:color.red)))
emaDirection=fDirection(emaFast,1)
table.cell(summaryTable,1,0,"EMA"+emaDirection,text_size=tableTextSize,
bgcolor=emaFast>emaSlowandemaFast>emaFast[1]?color.green:color.red)
//SeeifemaFasthasincreasedoverthelasttwoperiods.
ifrising(emaFast,2)andemaFast<emaSlow
table.cell_set_bgcolor(summaryTable,1,0,color.yellow)
directionTEMA=fDirection(temaFast,1)
table.cell(summaryTable,1,1,"TEMA"+directionTEMA,text_size=tableTextSize,
bgcolor=temaFast>temaSlowandtemaFast>temaFast[1]?color.green:color.red)
//SeeiftemaFasthasincreasedoverthelasttwoperiods.
ifrising(temaFast,2)andtemaFast<temaSlow
table.cell_set_bgcolor(summaryTable,1,1,color.yellow)
directionMAMA=fDirection(eMAMA,1)
table.cell(summaryTable,1,2,"eMAMA"+directionMAMA,text_size=tableTextSize,
bgcolor=eMAMA>eFAMAandeMAMA>eFAMA[1]?color.green:color.red)
//SeeiftemaFasthasincreasedoverthelasttwoperiods.
ifrising(eMAMA,2)andeMAMA<eFAMA
table.cell_set_bgcolor(summaryTable,1,2,color.yellow)
directionMACD=fDirection(macd,2)
table.cell(summaryTable,2,0,"MACD"+directionMACD,text_size=tableTextSize,bgcolor=macd>signalMACD?color.green:color.red)
directionOBV=fDirection(shortOBV,2)
table.cell(summaryTable,2,1,"OBV"+directionOBV,text_size=tableTextSize,bgcolor=shortOBV>0?color.green:color.red)
directionCMF=fDirection(mfCMF,2)
table.cell(summaryTable,2,2,"CMF"+directionCMF+tostring(mfCMF,"#.##"),text_size=tableTextSize,bgcolor=mfCMF>0?color.green:color.red)
//---------------------------------------------------<[Alerts]>-------------------------------------------------
ifpsarBuySignalandpsarConfirmationBuy
alert("PSARbuy/longsignalconfirmedfor{{ticker}}on{{interval}}.",alert.freq_once_per_bar)
ifpsarSellSignalandpsarConfirmationSell
alert("PSARsell/shortsignalconfirmedfor{{ticker}}on{{interval}}.",alert.freq_once_per_bar)
ifpsarChangeCond
alert("PSARhaschangeddirectionfor{{ticker}}on{{interval}}.",alert.freq_once_per_bar)
Expand (456 lines)
