Script Name: Qullamaggie Breakout
Author: millerrh
Description: The intent of this strategy is to buy breakouts with a tight stop on smaller timeframes in the direction of the longer term trend.  Default longer term trend is the daily, but the user can choose any timeframe to use for the SMAs (which act as filters and trailing stops).

Exit the trade using a trailing stop of a close below either the 10 MA or 20 MA (user...
PineScript code:

Pine Script™ strategy
Qullamaggie Breakout
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  millerrh
//  The  intent  of  this  strategy  is  to  buy  breakouts  with  a  tight  stop  on  smaller  timeframes  in  the  direction  of  the  longer  term  trend.
//  Then  use  a  trailing  stop  of  a  close  below  either  the  10  MA  or  20  MA  (user  choice)  on  that  larger  timeframe  as  the  position
//  moves  in  your  favor  (i.e.  whenever  position  price  rises  above  the  MA).
//  Option  of  using  daily  ATR  as  a  measure  of  finding  contracting  ranges  and  ensuring  a  decent  risk/reward.
//  (If  the  difference  between  the  breakout  point  and  your  stop  level  is  below  a  certain  %  of  ATR,  it  could  possibly  find  those  consolidating  periods.)
//@version=4
strategy("Qullamaggie  Breakout",  overlay=true,  initial_capital=10000,  currency='USD',
      default_qty_type=strategy.percent_of_equity,  default_qty_value=100,  commission_type=strategy.commission.percent,  commission_value=0.1)

//  ===  BACKTEST  RANGE  ===
Start  =  input(defval  =  timestamp("01  Jan  2019  06:00  +0000"),  title  =  "Backtest  Start  Date",  type  =  input.time)
Finish  =  input(defval  =  timestamp("01  Jan  2100  00:00  +0000"),  title  =  "Backtest  End  Date",  type  =  input.time)
//  Inputs
lb  =  input(defval  =  3,  title  ="LookbackPeriodforSwingHigh",minval=1,
tooltip="Lookbackperiodfordefiningthebreakoutlevel.")
lbStop=input(defval=3,title="LookbackBarsforStopLevel",minval=1,
tooltip="Initialstopplacementisthelowestlowthismanybarsback.Allowsfortighterstopplacementthanreferencingswinglows.")
htf=input(defval="D",title="TimeframeofMovingAverages",type=input.resolution,
tooltip="Allowsyoutosetadifferenttimeframeforthemovingaverages.Thedefaultbehavioristoidentifygoodtighteningsetupsonalargertimeframe
(likedaily)andenterthetradeonabreakoutoccuringonasmallertimeframe,usingthemovingaveragesofthelargertimeframetotrailyourstop.")
maType=input(defval="SMA",options=["EMA","SMA"],title="MovingAverageType")
ma1Length=input(defval=10,title="1stMovingAverageLength",minval=1)
ma2Length=input(defval=20,title="2ndMovingAverageLength",minval=1)
ma3Length=input(defval=50,title="3rdMovingAverageLength",minval=1)
useMaFilter=input(title="Use3rdMovingAverageforFiltering?",type=input.bool,defval=true,
tooltip="Signalswillbeignoredwhenpriceisunderthisslowestmovingaverage.Theintentistokeepyououtofbearperiodsandonly
buyingwhenpriceisshowingstrengthortradingwiththelongertermtrend.")
trailMaInput=input(defval="2ndMovingAverage",options=["1stMovingAverage","2ndMovingAverage"],title="TrailingStop")
//MACalculations
ma(maType,src,length)=>
maType=="EMA"?ema(src,length):sma(src,length)//TernaryOperator(ifmaTypeequalsEMA,thendoemacalc,elsedosmacalc)
ma1=security(syminfo.tickerid,htf,ma(maType,close,ma1Length))
ma2=security(syminfo.tickerid,htf,ma(maType,close,ma2Length))
ma3=security(syminfo.tickerid,htf,ma(maType,close,ma3Length))
plot(ma1,color=color.purple,style=plot.style_line,title="MA1",linewidth=2,transp=60)
plot(ma2,color=color.yellow,style=plot.style_line,title="MA2",linewidth=2,transp=60)
plot(ma3,color=color.white,style=plot.style_line,title="MA3",linewidth=2,transp=60)
//===USEATRFORFILTERING===
//Theideahereisthatyouwanttobuyinaconsolodatingrangeforbestrisk/reward.Sohereyoucancomparethecurrentdistancebetween
//support/resistancevs.theATRandmakesureyouaren'tbuyingatapointthatistooextendedfromnormal.
useAtrFilter=input(title="UseATRforFiltering?",type=input.bool,defval=false,
tooltip="Signalswillbeignoredifthedistancebetweensupportandresistanceislargerthanauser-definedpercentageofDailyATR.
Thisallowstheusertoensuretheyarenotbuyingsomethingthatistooextendedandinsteadfocusonnamesthatareconsolidatingmore.")
atrPerc=input(defval=100,title="%ofDailyATRValue",minval=1)
atrValue=security(syminfo.tickerid,"D",atr(14))*atrPerc*.01
//===PLOTSWINGHIGH/LOWANDMOSTRECENTLOWTOUSEASSTOPLOSSEXITPOINT===
//Changethesevaluestoadjustthelookbackandlookforwardperiodsforyourswinghigh/lowcalculations
pvtLenL=lb
pvtLenR=lb
//GetHighandLowPivotPoints
pvthi_=pivothigh(high,pvtLenL,pvtLenR)
pvtlo_=pivotlow(low,pvtLenL,pvtLenR)
//ForcePivotcompletionbeforeplotting.
Shunt=1//Waitforclosebeforeprintingpivot?1fortrue0forflase
maxLvlLen=0//MaximumExtensionLength
pvthi=pvthi_[Shunt]
pvtlo=pvtlo_[Shunt]
//CountHowmanycandlesforcurrentPivotLevel,Ifnewreset.
counthi=barssince(notna(pvthi))
countlo=barssince(notna(pvtlo))

pvthis=fixnan(pvthi)
pvtlos=fixnan(pvtlo)
hipc=change(pvthis)!=0?na:color.maroon
lopc=change(pvtlos)!=0?na:color.green
//DisplayPivotlines
plot((maxLvlLen==0orcounthi<maxLvlLen)?pvthis:na,color=hipc,transp=0,linewidth=1,offset=-pvtLenR-Shunt,title="TopLevels")
//plot((maxLvlLen==0orcountlo<maxLvlLen)?pvtlos:na,color=lopc,transp=0,linewidth=1,offset=-pvtLenR-Shunt,title="BottomLevels")
plot((maxLvlLen==0orcounthi<maxLvlLen)?pvthis:na,color=hipc,transp=0,linewidth=1,offset=0,title="TopLevels2")
//plot((maxLvlLen==0orcountlo<maxLvlLen)?pvtlos:na,color=lopc,transp=0,linewidth=1,offset=0,title="BottomLevels2")
//BUYCONDITIONS
stopLevelCalc=valuewhen(pvtlo_,low[pvtLenR],0)//StopLevelatSwingLow
buyLevel=valuewhen(pvthi_,high[pvtLenR],0)//BuylevelatSwingHigh
plot(buyLevel,style=plot.style_line,color=color.blue,title="CurrentBreakoutLevel",show_last=1,linewidth=1,transp=50,trackprice=true)
//Conditionsforentryandexit
stopLevel=float(na)//Definestoplevelhereas"na"sothatIcanreferenceitintheinPosition
//variableandtheATRcalculationbeforethestopLevelisactuallydefined.
buyConditions=(useMaFilter?buyLevel>ma3:true)and
(useAtrFilter?(buyLevel-stopLevel[1])<atrValue:true)and
time>Startandtime<Finish
//buySignal=high>buyLevelandbuyConditions
buySignal=crossover(high,buyLevel)andbuyConditions
trailMa=trailMaInput=="1stMovingAverage"?ma1:ma2
sellSignal=crossunder(close,trailMa)
//sellSignal=security(syminfo.tickerid,htf,close<trailMa)andsecurity(syminfo.tickerid,htf,close[1]<trailMa)
//STOPANDPRICELEVELS
inPosition=bool(na)
inPosition:=buySignal[1]?true:sellSignal[1]?false:low<=stopLevel[1]?false:inPosition[1]
lowDefine=lowest(low,lbStop)
stopLevel:=inPosition?stopLevel[1]:lowDefine
//plot(stopLevel)
buyPrice=buyLevel
buyPrice:=inPosition?buyPrice[1]:buyLevel
plot(stopLevel,style=plot.style_line,color=color.orange,title="CurrentStopLevel",show_last=1,linewidth=1,transp=50,trackprice=true)
plot(inPosition?stopLevel:na,style=plot.style_circles,color=color.orange,title="HistoricalStopLevels",transp=50,trackprice=false)
//plot(buyPrice,style=plot.style_line,color=color.blue,linewidth=1,transp=50,trackprice=true)
//(STRATEGYONLY)CommentoutforStudy
strategy.entry("Long",strategy.long,stop=buyLevel,when=buyConditions)
strategy.exit("ExitLong",from_entry="Long",stop=stopLevel[1])
if(low[1]>trailMa)
strategy.close("Long",when=sellSignal)
//if(low[1]>trailMa)
//strategy.exit("ExitLong",from_entry="Long",stop=trailMa)//togetthistoworkright,Ineedtoreferencehighesthighsinsteadofswinghighs
//becauseitcanhavemebuyrightbackinaftersellingifthestoplevelisabovethelastregisteredswinghighpoint.
Expand (124 lines)
