Script Name: R19 STRATEGY
Author: SenatorVonShaft
Description: Hello again.

Let me introduce you R19 Strategy I wrote for mostly BTC long/short signals
This is an upgrated version of STRATEGY R18 F BTC strategy.

I checked this strategy on different timeframes and different assest and found it very usefull for BTC 1 Hour and 5 minutes chart.

Strategy is basically takes BTC/USDT as a main indicator, so you can apply this...
PineScript code:

Pine Script™ strategy
R19 STRATEGY
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  onurenginogutcu
//@version=4
strategy("R19  STRATEGY",  overlay=true,  calc_on_every_tick=true  ,  margin_long=100,  margin_short=100  ,    process_orders_on_close=true  )
sym  =  input(title="Symbol",  type=input.symbol,  defval="BINANCE:BTCUSDT"  ,  group  =  "SYMBOL")
timeFrame  =  input(title="Strategy  Decision  Time  Frame",  type  =  input.resolution  ,    defval="60")
adxlen  =  input(14,  title="ADX  Smoothing"  ,  group  =  "ADX")
dilen  =  input(14,  title="ADX  DI  Length",  group  =  "ADX")
adxemalenght  =  input(30,  title="ADX  EMA",  group  =  "ADX")
adxconstant  =  input(19,  title="ADX  CONSTANT",  group  =  "ADX")
fibvar  =  input  (title  =  "Fibo  Look  Back  Canles"  ,  defval  =  50  ,  minval  =  0  ,  group  =  "FIBO  MACD  SMA")
smaLookback  =  input  (title  =  "SMA  Look  Back  Candles"  ,  defval  =  30  ,  minval  =  0  ,  group  =  "FIBO  MACD  SMA")
MACDFast  =  input  (title  =  "MACD  Fast  Lenght"  ,  defval  =  15  ,  minval  =  0  ,  group  =  "FIBO  MACD  SMA")
MACDSlow  =  input  (title  =  "MACD  Slow  Lenght"  ,  defval  =  30  ,  minval  =  0  ,  group  =  "FIBO  MACD  SMA")
MACDSmooth  =  input  (title  =  "MACD  Signal  Smoothing"  ,  defval  =  9  ,  minval  =  0  ,  group  =  "FIBO  MACD  SMA")
MACDLookback  =  input  (title  =  "MACD  Look  Back  Candles"  ,  defval  =  100  ,  minval  =  0  ,  group  =  "FIBO  MACD  SMA")
trailingStopLong  =  input  (title  =  "Trailing  Long  Stop  %"  ,  defval  =  2.0  ,  step  =  0.1,  group  =  "TP  &  SL")  *  0.01
trailingStopShort  =  input  (title  =  "Trailing  Short  Stop  %"  ,  defval  =  2.0  ,  step  =  0.1  ,  group  =  "TP  &  SL")  *  0.01
LongTrailingProfitStart  =  input  (title  =  "Long  Profit  Start  %"  ,  defval  =  2.0  ,  step  =  0.1  ,  group  =  "TP  &  SL")  *  0.01
ShortTrailingProfitStart  =  input  (title  =  "Short  Profit  Start  %"  ,  defval  =  2.0  ,  step  =  0.1,  group  =  "TP  &  SL")  *  0.01
lsl  =  input(title="Max  Long  Stop  Loss  (%)",
          minval=0.0,  step=0.1,  defval=3.0,  group  =  "TP  &  SL")  *  0.01

ssl  =  input(title="Max  Short  Stop  Loss  (%)",
          minval=0.0,  step=0.1,  defval=2.5,  group  =  "TP  &  SL")  *  0.01

longtp  =  input(title="Long  Take  Profit  (%)",
          minval=0.0,  step=0.1,  defval=100,  group  =  "TP  &  SL")  *  0.01

shorttp  =  input(title="Short  Take  Profit  (%)",
          minval=0.0,  step=0.1,  defval=100,  group  =  "TP  &  SL")  *  0.01

capperc  =  input(title="Capital  Percentage  to  Invest  (%)",
          minval=0.0,  maxval=100,  step=0.1,  defval=95,  group  =  "CAPITAL  TO  INVEST")  *  0.01

symClose  =  security(sym,  timeFrame,  close)
symHigh  =  security(sym,  timeFrame,  high)
symLow  =  security(sym,  timeFrame,  low)
atr  =  atr  (14)
/////////adx  code
dirmov(len)  =>
        up  =  change(symHigh)
        down  =  -change(symLow)
        plusDM  =  na(up)  ?  na  :  (up  >  down  and  up  >  0  ?  up  :  0)
        minusDM  =  na(down)  ?  na  :  (down  >  up  and  down  >  0  ?  down  :  0)
        truerange  =  rma(tr,  len)
        plus  =  fixnan(100  *  rma(plusDM,  len)  /  truerange)
        minus  =  fixnan(100  *  rma(minusDM,  len)  /  truerange)
        [plus,  minus]
adx(dilen,  adxlen)  =>
        [plus,  minus]  =  dirmov(dilen)
        sum  =  plus  +  minus
        adx  =  100  *  rma(abs(plus  -  minus)  /  (sum  ==  0  ?  1  :  sum),  adxlen)
sig  =  adx(dilen,  adxlen)
emasig  =  ema  (sig  ,  adxemalenght  )
////////adx  code  over
i  =  ema  (symClose  ,  MACDFast)  -  ema  (symClose  ,  MACDSlow)
r  =  ema  (i  ,  MACDSmooth)
sapust  =  highest  (i  ,  MACDLookback)  *  0.729
sapalt  =  lowest  (i  ,  MACDLookback)  *  0.729
simRSI  =  rsi  (symClose  ,  50  )
fibtop  =  lowest  (symLow  ,  fibvar)  +  ((highest  (symHigh  ,  fibvar)  -  lowest  (symLow  ,  fibvar))  *  0.50)
fibbottom  =  lowest  (symLow  ,  fibvar)  +  ((highest  (symHigh  ,  fibvar)  -  lowest  (symLow  ,  fibvar))  *  0.50)
cond1  =  0
cond2  =  0
cond3  =  0
cond4  =  0
longCondition  =  crossover(i,  r)  and  i  <  sapalt  and  sig  >  adxconstant  and  symClose  <  sma  (symClose  ,  smaLookback)  and  simRSI  <  sma  (simRSI  ,  50)  and  symClose  <  fibbottom
shortCondition  =  crossunder(i,  r)  and  i  >  sapust  and  sig  >  adxconstant  and    symClose  >  sma  (symClose  ,  smaLookback)  and  simRSI  >  sma  (simRSI  ,  50)  and  symClose  >  fibtop
//////////////////////probability  long/short
if  (crossover(i,  r)  and  i  <  sapalt)
        cond1  :=  35
else  if  (crossunder(i,  r)  and  i  >  sapust)
        cond1  :=  -35
else
        cond1  :=  0

if  (symClose  <  sma(symClose,smaLookback))
cond2:=30
elseif(symClose>sma(symClose,smaLookback))
cond2:=-30
else
cond2:=0

if(simRSI<sma(simRSI,50))
cond3:=25
elseif(simRSI>sma(simRSI,50))
cond3:=-25
else
cond3:=0

if(symClose<fibbottom)
cond4:=10
elseif(symClose>fibbottom)
cond4:=-10
else
cond4:=0

probab=cond1+cond2+cond3+cond4
////////////////////////////////////////////////////////////////
///////////////////////////////////////////STRATEGYENTRIESANDSTOPLOSSES/////
varstartTrail=0
vartrailingLongPrice=0.0
vartrailingShortPrice=0.0
if(longConditionandstrategy.position_size==0)
strategy.entry("Long",strategy.long,qty=capperc*strategy.equity/close)
if(shortConditionandstrategy.position_size==0)
strategy.entry("Short",strategy.short,qty=capperc*strategy.equity/close)


if(strategy.position_size==0)
trailingShortPrice:=0.0
trailingLongPrice:=0.0
startTrail:=0
/////////////////////////////////strategyexit
if(strategy.position_size>0andclose>=strategy.position_avg_price*(1+LongTrailingProfitStart))
startTrail:=1
if(strategy.position_size<0andclose<=strategy.position_avg_price*(1-ShortTrailingProfitStart))
startTrail:=-1

trailingLongPrice:=ifstrategy.position_size>0andstartTrail==1
stopMeasure=close*(1-trailingStopLong)
max(stopMeasure,trailingLongPrice[1])
elseifstrategy.position_size>0andstartTrail==0
strategy.position_avg_price*(1-lsl)
trailingShortPrice:=ifstrategy.position_size<0andstartTrail==-1
stopMeasure=close*(1+trailingStopShort)
min(stopMeasure,trailingShortPrice[1])
elseifstrategy.position_size<0andstartTrail==0
strategy.position_avg_price*(1+ssl)
if(strategy.position_size>0)
strategy.exit("ExitLong","Long",stop=trailingLongPrice,limit=strategy.position_avg_price*(1+longtp))

if(strategy.position_size<0)
strategy.exit("ExitShort","Short",stop=trailingShortPrice,limit=strategy.position_avg_price*(1-shorttp))
////////////////////////verticalcolouringsignals
bgcolor(color=longCondition?color.new(color.green,70):na)
bgcolor(color=shortCondition?color.new(color.red,70):na)
plot(trailingLongPrice,color=color.green)///longpricetrailingstop
plot(trailingShortPrice,color=color.red)///shortpricetrailingstop
plot(startTrail,color=color.yellow)
plot(probab,color=color.white)////probability
Expand (194 lines)
