Script Name: Random Entries Work!
Author: gregoirejohnb
Description: " tHe MaRkEtS aRe RaNdOm ", say moron academics.

The purpose of this study is to show that most markets are NOT random! Most markets show a clear bias where we can make such easy money, that a random number generator can do it.

 === HOW THE INDICATOR WORKS ===


 The study will randomly enter the market
 The study will randomly exit the market if in a trade
...
PineScript code:

Pine Script™ strategy
Random Entries Work!
//@version=4
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  gregoirejohnb
//
//  "tHe  MaRkEtS  aRe  RaNdOm",  say  moron  academics.
//
//  The  purpose  of  this  study  is  to  show  that  most  markets  are  NOT  random!  Most  markets  show  a  clear  bias  where  we  can  make  such  easy  money,  that  a  random  number  generator  can  do  it.
//
//  ===  HOW  THE  INDICATOR  WORKS  ===
//
//  -The  study  will  randomly  enter  the  market
//  -The  study  will  randomly  exit  the  market  if  in  a  trade
//  -You  can  choose  a  Long  Only,  Short  Only,  or  Bidirectional  strategy
//
//  ===  DEFAULT  VALUES  AND  THEIR  LOGIC  ===
//
//  Percent  Chance  to  Enter  Per  Bar:  10%
//  Percent  Chance  to  Exit  Per  Bar:  1%
//  Direction:  Long  Only
//  Commission:  0
//
//  Each  bar  has  a  10%  chance  to  enter  the  market.  Each  bar  has  a  1%  to  exit  the  market  [if  in  a  trade].  It  will  only  enter  long.
//
//  I  included  zero  commission  for  simplication.  It's  a  good  exercise  to  include  a  commission/slippage  to  see  just  how  much  trading  fees  take  from  you.
//
//===TIPS===
//
//-Increasing"PercentChancetoExit"willshortenthetimeinatrade.Youcanseethe"Avg#BarsInTrade"godownasyouincrease.If"PercentChancetoExit"istoohigh,thestudywon'tbeinthemarketlongenoughtocatchanymovement,possiblyexitingonthesamebarmostofthetime.
//-Ifyou'regettingtheredscreen,thatmeansthestrategylostsomuchmoneyitwentbroke.TryreducingthepercentequityonthePropertiestab.
//-Switchthestartyeartoavoidblackswaneventslikethecoviddropin2020.
//-
//===FINDINGS===
//
//Mostmarketslosemoneywitha"Random"directionstrategy.
//MostmarketsloseALLmoneywitha"ShortOnly"strategy.
//Mostmarketsmakemoneywitha"LongOnly"strategy.
//
//Trythisstrategyon:Bitcoin(BTCUSD)andtheNASDAQ(QQQ).
//
//Therearetwopopularmemesrightnow:"Bitcointothemoon"and"Stocksonlygoup".Bothareseeminglytrue.Bitcoinwasthebestperformingassetofthe2010's,gainingseveralbillionpercentingains.Thestockmarketisona100yearlonguptrend.Why?BECAUSEFIATCURRENCIESALWAYSGODOWN!Thisisinflation.Ifwemeasurethemarketintermsofothersassetsinsteadoffiat,theLongOnlystrategydoesn'tworkanymore.
//Trythisstrategyon:Bitcoin/GLD(BTCUSD/GLD),theEurodollar(EURUSD),andtheS&P500measuredingold(SPY/GLD).
//
//Bitcoinmeasuredingold(BTCUSD/GLD)stillworkswithaLongOnlystrategybecauseBitcoinincreasedinvalueoverbothUSDandgold.
//TheEurodollar(EURUSD)generallylosesmoneynomatterwhat,especiallyifyouaddanycommission.Thismakessenseastheyarebothfiatcurrencieswithsimilarinflationschedules.
//GoldandtheS&P500havegainedroughlythesameamountsince~2000.Someyearswillshowbetterresultsforalongstrategy,whileotherswillfavorashortstrategy.NowlookatjustSPYorGLD(whicharebothmeasuredinUSDbydefault!)andyou'llseethesametrendagain:aLongOnlystrategycrushesevenwhenenteringandexitingrandomly.
//
//==="JUSTTELLMEWHATTODO,YOUNERD!"===
//
//BullsalwayswinandBearsalwayslosebecausefiatcurrenciesgotozero.
//
strategy(title="RandomEntriesWork",shorttitle="REW",overlay=true,pyramiding=0,default_qty_type=strategy.percent_of_equity,default_qty_value=100,currency=currency.USD,commission_type=strategy.commission.percent,commission_value=0)
//===GENERALINPUTS===
strategy=input(defval="LongOnly",title="Direction",options=["LongOnly","ShortOnly","Random"])
enter_frequency=input(defval=10,minval=1,maxval=100,title="PercentChancetoEnter")
exit_frequency=input(defval=3,minval=0,maxval=100,title="PercentChancetoExit",tooltip="ThisshouldbemuchlowerthanPercentChancetoEnter.Highervaluesdecreasetimeinmarket.Lowervaluesincreasetimeinmarket.")
start_year=input(defval=2020,title="StartYear")
//===LOGIC===
r=random(0,100)
enter=enter_frequency>r[0]
exit=exit_frequency>r[0]
direction=random(0,100)>=50
//===STRATEGY-LONGPOSITIONEXECUTION===
enterLong()=>
strategy.opentrades==0andenterand(strategy=="LongOnly"or(strategy=="Random")anddirection)and
time>timestamp(start_year,01,01,01,01)
exitLong()=>
exit
strategy.entry(id="Long",long=strategy.long,when=enterLong())
strategy.close(id="Long",when=exitLong())
//===STRATEGY-SHORTPOSITIONEXECUTION===
enterShort()=>
strategy.opentrades==0andenterand(strategy=="ShortOnly"or(strategy=="Random"andnotdirection))and
time>timestamp(start_year,01,01,01,01)
exitShort()=>
exit
strategy.entry(id="Short",long=strategy.short,when=enterShort())
strategy.close(id="Short",when=exitShort())
Expand (81 lines)
