Script Name: Ranged Volume DCA Strategy - R3c0nTrader
Author: R3c0nTrader
Description: Update: Republishing this as Public Open-Source script.

Credits:
Thank you "EvoCrypto" for granting me permission to use "Ranged Volume" to create this strategy.
Thank you "junyou0424" for granting me permission to use "DCA Bot with SuperTrend Emulator" which I used for adding bot inputs, calculations, and strategy

What does this do?
This script is mainly used...
PineScript code:

Pine Script™ strategy
Ranged Volume DCA Strategy - R3c0nTrader
//  ©  Ranged  Volume  DCA  Strategy  -  R3c0nTrader  ver  2022-07-30
//  For  backtesting  with  3Commas  DCA  Bot  settings
//  Thank  you  "EvoCrypto"  for  granting  me  permission  to  use  "Ranged  Volume"  to  create  this  strategy
//  Thank  you  "junyou0424"  for  granting  me  permission  to  use  "DCA  Bot  with  SuperTrend  Emulator"  which  I  used  for  adding  bot  inputs,  calculations,  and  strategy
//@version=5
strategy("Ranged  Volume  DCA  Strategy  -  R3c0nTrader",  shorttitle="Ranged  Vol  DCA  Strategy",  format=format.volume,  overlay=true,  pyramiding=999,  default_qty_type=strategy.cash,  initial_capital=10000,  commission_value=0.0,  max_labels_count=500)
//  Declare  Variables
var  pnl_pct  =  0.0
var  stopValue  =  float(0.0)
var  trailing_price  =  float(0.0)
Close  =  0.0
Open  =  0.0
buy  =  bool(false)
sell  =  bool(false)
use_labels  =  bool(false)
buy_message  =  ""
sell_message  =  ""
//  INPUTS
//  Start  and  End  Dates----------------------------------------------------------
i_startTime  =  input.time(defval=timestamp('01  Jan  2015  00:00  +0000'),  title='Start  Time',  group="Date  Range")
i_endTime  =  input.time(defval=timestamp('31Dec205023:59+0000'),title='EndTime',group="DateRange")
inDateRange=time>=i_startTimeandtime<=i_endTime
//------------------------------------------------------------------------------
//Start:Preventrepainting----------------------------------------------------
stop_repainting_choice=input.bool(false,title='Disablerepainting?',
tooltip='PerPinev5UserManual:Youcanverywelldecidetouserepaintingindicatorsifyouunderstandhowtheybehave,andthatbehaviormeetsyourtradingmethodology’srequirements.'+
'Don’tbeoneofthosenewcomerstotradingwhoslap“repaint”sentencesonpublishedscriptsasifitdiscreditsthem.Doingsoonlyrevealsyourincomprehensionofthesubject.'+
'What’simportantisthatyouunderstandhowthetoolsyouusework,andiftheirbehavioriscompatiblewithyourobjectives,repaintingornot.Repaintingisacomplexmatter.Ithasmanyfacesandmanycauses.',
group='Repainting')
nonRepaintingSecurity(sym,tf,src)=>
request.security(sym,tf,src[barstate.isrealtime?1:0])[barstate.isrealtime?0:1]
//End:Preventrepainting------------------------------------------------------
//Start:Bull/SellIndicatorOptions-------------------------------------------
highlight_trades=input.bool(true,title='Highlightbackgroundcolorfortrades?',tooltip='Usedtoaddagreenorredbackgroundcolorwiththebuyandsellarrows.',group="Buy/SellIndicatorOptions")
buy_color=input.color(color.new(color.green,70),'Buybackgroundcolor',group="Buy/SellIndicatorOptions")
sell_color=input.color(color.new(color.red,70),'Sellbackgroundcolor',group="Buy/SellIndicatorOptions")
use_labels:=input.bool(false,title='UseLabels?',tooltip='Enabletoshowlabels.Toremovetheothertext,youmustopenthe"Style"menuanduncheck"Signallabels"and"Quantity".\n\nOnly500labelscanbedisplayedonthechart.',group="Buy/SellIndicatorOptions")
//End:Bull/SellIndicatorOptions---------------------------------------------
//Start:3CommasBot----------------------------------------------------------
boolcfg_enable_bot_control=input.bool(title='Enable3CommasWebhook?',defval=false,group='3commasBotSettings',
tooltip='IfthisisenabledthestrategycancontrolsomebotoperationsviaWebhookcalls.\n\nToenableWebhookcalls,checkthisoption,selectthebottype,'+
'entertheBotidandEmailToken.\n\nAfterthestrategyisconfigured,createanalertonthestrategy,select"alert()functioncallsonly",'+
'check"WebhookURL",enterthe3CommaswebhookURL,andenterthe"AlertName"')
bot_type=input.string("Simplebot",title="Selectthebottype",options=["Simplebot","Compositebot"],group='3commasBotSettings',
tooltip='Selectthebottype.If"Simplebot"isselectedthecurrencypair(e.g.BTCUSDorBTCUSDT)willnotbepassedinthealert.'+
'\nIf"Compositebot"isselectedthecurrencypairwillbepassedinthealert.')
stringcfg_bot_id=input.string(title='Botid',defval='bot_id',tooltip='Gotoyour3Commasbotsettings>Expand"Messagefordealstartsignal"',group='3commasBotSettings')
stringcfg_email_token=input.string(title='Emailtoken',defval='email_token',tooltip='Gotoyour3Commasbotsettings>Expand"Messagefordealstartsignal"',group='3commasBotSettings')
ifcfg_enable_bot_control
ifbot_type=="Simplebot"
buy_message:='{"message_type":"bot","bot_id":"'+cfg_bot_id+'","email_token":"'+cfg_email_token+'","delay_seconds":0}'
sell_message:='{"action":"close_at_market_price_all","message_type":"bot","bot_id":"'+cfg_bot_id+'","email_token":"'+cfg_email_token+'","delay_seconds":0}'
elseifbot_type=="Compositebot"
buy_message:='{"message_type":"bot","bot_id":"'+cfg_bot_id+'","email_token":"'+cfg_email_token+'","delay_seconds":0,"pair":"'+str.tostring(syminfo.currency)+'_'+str.tostring(syminfo.basecurrency)+'"}'
sell_message:='{"action":"close_at_market_price_all","message_type":"bot","bot_id":"'+cfg_bot_id+'","email_token":"'+cfg_email_token+'","delay_seconds":0,"pair":"'+str.tostring(syminfo.currency)+'_'+str.tostring(syminfo.basecurrency)+'"}'
//End:3CommasBot------------------------------------------------------------
//RangedVolumeSettings
Range_Length=input.int(5,title="VolumeRangeLength",minval=1)
Heikin_Ashi=input(false,title="HeikinAshi")
Display_Bars=input(true,title="ShowBarColors")
Display_Break=input(true,title="ShowBreak-Out")
Display_Range=input(true,title="ShowRange")
truncate(number,decimals)=>
factor=math.pow(10,decimals)
int(number*factor)/factor
//3CommasInputs
sourceInput=input.source(close,"Source")
price_deviation=input.float(6.0,title='Pricedeviationtoopensafetyorders(%)',step=0.25,minval=0.0)/100
take_profit=input.float(22.0,title='TargetTakeProfit(%)',step=0.5,minval=0.0)/100
trailing=input.float(0.0,title='Trailingdeviation.Default=0.0(%)',step=0.1,minval=0.0)/100
base_order=input(100.0,title='Baseorder')
safe_order=input(200.0,title='Safetyorder')
safe_order_volume_scale=input.float(2.0,step=0.5,title='Safetyordervolumescale')
safe_order_step_scale=input.float(1.4,step=0.1,title='Safetyorderstepscale')
max_safe_order=input(5,title='Maxsafetyorders')
sourceInput01_func()=>
sourceInput01_f=stop_repainting_choice?nonRepaintingSecurity(syminfo.tickerid,timeframe.period,sourceInput):sourceInput
varcurrent_so=0
varinitial_order=0.0
varprevious_high_value=0.0
varoriginal_ttp_value=0.0
//Calculateourkeylevels
take_profit_level=strategy.position_avg_price*(1+take_profit)
//SETTINGS
Close:=Heikin_Ashi?request.security(ticker.heikinashi(syminfo.tickerid),timeframe.period,sourceInput01_func()):sourceInput01_func()
Open:=Heikin_Ashi?request.security(ticker.heikinashi(syminfo.tickerid),timeframe.period,open):open
Positive=volume
Negative=-volume
Highest=stop_repainting_choice?ta.highest(volume,Range_Length)[1]:ta.highest(volume,Range_Length)
Lowest=stop_repainting_choice?ta.lowest(-volume,Range_Length)[1]:ta.lowest(-volume,Range_Length)
Up=Highest>Highest[1]andClose>Open
Dn=Highest>Highest[1]andClose<Open
Volume_Color=
Display_BreakandUp?color.new(#ffeb3b,20):
Display_BreakandDn?color.new(#f44336,20):
Close>Open?color.new(#00c0ff,20):
Close<Open?color.new(#0001f6,20):na
//Plotbarcolorforvolumerangeindicator
barcolor(Volume_Color,title='RangedVolumeBarColoring:(Youmustdisablebarcoloringinanystudiesyouaddedorthismaynotworkproperly)')
//OpenFirstPosition
//ifstrategy.position_size==0andsourceInput>0and(Up)andinDateRange
ifstrategy.position_size==0andsourceInput01_func()>0andUpandinDateRange
ifuse_labels
label.new(bar_index,sourceInput01_func(),'Long@'+str.tostring(math.round(sourceInput01_func(),4)),style=label.style_label_up,color=color.green)
strategy.entry('Long@'+str.tostring(sourceInput01_func())+'💎✋🤚',strategy.long,qty=base_order/sourceInput01_func())
else
strategy.entry('Long@'+str.tostring(sourceInput01_func())+'💎✋🤚',strategy.long,qty=base_order/sourceInput01_func())
initial_order:=sourceInput
current_so:=1
previous_high_value:=0.0
original_ttp_value:=0
buy:=true
threshold=0.0
ifsafe_order_step_scale==1.0
threshold:=initial_order-initial_order*price_deviation*safe_order_step_scale*current_so
elseifcurrent_so<=max_safe_order
threshold:=initial_order-initial_order*((price_deviation*math.pow(safe_order_step_scale,current_so)-price_deviation)/(safe_order_step_scale-1))
elseifcurrent_so>max_safe_order
threshold:=initial_order-initial_order*((price_deviation*math.pow(safe_order_step_scale,max_safe_order)-price_deviation)/(safe_order_step_scale-1))

//Averagedownwhenlowestcandlevaluecrossesbelowthreshold
ifcurrent_so>0andlow<=thresholdandcurrent_so<=max_safe_orderandprevious_high_value==0.0
//TriggerasafetyorderattheSafetyOrder"threshold"price
strategy.entry('😨🙏SO'+str.tostring(current_so)+'@'+str.tostring(threshold),direction=strategy.long,qty=safe_order*math.pow(safe_order_volume_scale,current_so-1)/threshold)
current_so+=1
//TakeProfit!
//Takeprofitwhentakeprofitlevelisequaltoorhigherthanthehighofthecandle
iftake_profit_level<=highandstrategy.position_size>0orprevious_high_value>0.0
pnl_pct:=truncate((close-strategy.position_avg_price)/strategy.position_avg_price*100,3)
iftrailing>0.0
//'trailing_price'willcontainthelargestpercentage-basedstopvalue
trailing_price:=if(strategy.position_size>0)
stopValue:=close*(1-trailing)
//The'max'functioniswhatallowsthepercentage-basedstopto'Trail'.
//IfthestopValueishigherthantheprevioustrailing_price(whichwastheoldstopValue)thenwekeepthehighervalue
//Thetrailing_pricecanonlyincreaseorremainthesame.
math.max(stopValue,trailing_price[1])
else
0
take_profit_level:=trailing_price
ifprevious_high_value>0.0
ifhigh>=previous_high_value
previous_high_value:=sourceInput
ifhigh<=trailing_price
ifuse_labels
label.new(bar_index,sourceInput01_func(),text='Close(trailing)@'+str.tostring(math.round(close,4))+','+str.tostring(pnl_pct)+'%',style=label.style_label_down,color=color.yellow)
strategy.close_all(comment='Close(trailing)@'+str.tostring(math.round(close,4))+','+str.tostring(pnl_pct)+'%')
else
strategy.close_all(comment='Close(trailing)@'+str.tostring(math.round(close,4))+','+str.tostring(pnl_pct)+'%')
sell:=true
//SendSellAlertto3Commasbot
alert(sell_message,alert.freq_once_per_bar_close)
elseifclose<=trailing_price
ifuse_labels
label.new(bar_index,sourceInput01_func(),text='Close(trailing)@'+str.tostring(math.round(close,4))+','+str.tostring(pnl_pct)+'%',style=label.style_label_down,color=color.yellow)
strategy.close_all(comment='Close(trailing)@'+str.tostring(math.round(close,4))+','+str.tostring(pnl_pct)+'%')
else
strategy.close_all(comment='Close(trailing)@'+str.tostring(math.round(close,4))+','+str.tostring(pnl_pct)+'%')
sell:=true
//SendSellAlertto3Commasbot
alert(sell_message,alert.freq_once_per_bar_close)
else
previous_high_value:=high
original_ttp_value:=high
else
ifuse_labelsandstrategy.position_size>0andsell==false
label.new(bar_index,sourceInput01_func(),text='Close@'+str.tostring(math.round(high,4))+','+str.tostring(pnl_pct)+'%',style=label.style_label_down,color=color.yellow)
strategy.close_all(comment='💰Close@'+str.tostring(math.round(close,4))+','+str.tostring(pnl_pct)+'%')
else
strategy.close_all(comment='💰Close@'+str.tostring(math.round(close,4))+','+str.tostring(pnl_pct)+'%')
sell:=true
//SendSellAlertto3Commasbot
alert(sell_message,alert.freq_once_per_bar_close)

//Zerooutvaluesaftertradeisclosed
ifsell
current_so:=0
previous_high_value:=0
original_ttp_value:=0
stopValue:=0
trailing:=0
trailing_price:=0
//EndTakeProfit--------------------------------------------------------------
//Start:Clearthetrailingvaluesifnoopentrades---------------------------
ifstrategy.opentrades==0
original_ttp_value:=0
stopValue:=0
//End:Clearthetrailingvaluesifnoopentrades-----------------------------
//Start:Plots-----------------------------------------------------------------
//PlotTrailingStopLossandassociatedoriginalTTPvalue
plot(original_ttp_value>0?original_ttp_value:na,style=plot.style_linebr,color=color.white,linewidth=3,title="OriginalTTPValue",editable=true)
plot(stopValue>0?stopValue:na,style=plot.style_linebr,color=color.red,linewidth=3,title="StopValue",editable=true)
plot(trailing_price>0?trailing_price:na,style=plot.style_linebr,color=color.yellow,linewidth=3,title="Trailingstoploss",editable=true)
//PlotTP
plot(strategy.position_size>0?take_profit_level:na,style=plot.style_linebr,color=color.green,linewidth=2,title="TakeProfit")
//PlotAllSafetyOrderlinesexceptforlastoneasbrightblue
plot(strategy.position_size>0andcurrent_so<=max_safe_orderandcurrent_so>0?threshold:na,style=plot.style_linebr,color=color.new(#00ffff,0),linewidth=2,title="SafetyOrder")
//PlotLastSafetyOrderLineasRed
plot(strategy.position_size>0andcurrent_so>max_safe_order?threshold:na,style=plot.style_linebr,color=color.red,linewidth=2,title="NoSafetyOrdersLeft")
//PlotAveragePositionPriceLineasOrange
plot(strategy.position_size>0?strategy.position_avg_price:na,style=plot.style_linebr,color=color.orange,linewidth=2,title="AvgPositionPrice")
//FillTPAreaandSOArea
h1=plot(strategy.position_avg_price,color=color.new(#000000,100),title="AvgPricePlotArea",display=display.none,editable=false)
h2=plot(take_profit_level,color=color.new(#000000,100),title="TakeProfitPlotArea",display=display.none,editable=false)
h3=plot(threshold,color=color.new(#000000,100),title="SOPlotArea",display=display.none,editable=false)
//TPArea
fill(h1,h2,color=color.new(#38761d,70),title="TakeProfitPlotArea")
//CurrentSOArea
fill(h1,h3,color=color.new(#3d85c6,70),title="SOPlotArea")
//Thiswillremovetheextraneoussellsignalsbeforeweusethemtoplotwith
sell:=strategy.position_size>0?sell:false
//PlotHighlightforBuy/SellArrows
sessioncolor=ifhighlight_trades
switch
buy=>buy_color
sell=>sell_color
=>color(na)
bgcolor(sessioncolor,editable=false)
//SendBuyAlertto3Commasbot
ifbuy
alert(buy_message,alert.freq_once_per_bar_close)
buy:=false
//End:Plots-------------------------------------------------------------------
Expand (259 lines)
