Script Name: Renko Strategy T3 V1
Author: dman103
Description: An interesting strategy using Renko calculations and Tilson T3 on normal charts targeted for cryptocurrencies but can work with different assets.
Tested on Daily but can work with lower frames  using Renko Size and T3 Length adjustments.

 == Description ==
Strategy get Renko close/open/high/low values and smooth them with T3 Tilson.
Base on these results the...
PineScript code:

Pine Script™ strategy
Renko Strategy T3 V1
//@version=4
//  This  work  is  licensed  under  a  Creative  Commons  Attribution-ShareAlike  4.0  International  License  https://creativecommons.org/licenses/by-sa/4.0/
//  ©  dman103
//  An  interesting  strategy  using  Renko  calculations  and  T3  Tilson  on  normal  charts  targeted  for  cryptocurrencies  but  canworkwithdifferentassets.
//TestedonDailybutcanworkwithlowerframes(notoolow)usingRenkoSizeandT3Lengthadjustments.
//==Description==
//StrategygetRenkoclose/open/high/lowvaluesandsmooththemwithT3Tilson.
//Baseontheseresultsthestrategytriggersalongandshortorders,wheregreenuptrendingandreddowntrending.
//IncludingAlerts
//
//==Repaint==
//Thereseemstobesomesortofinconsistencywhendoing'Replay'tothestrategy,whichmeansusingReplayfunctionwon'ttradelikeifyouseethetradingresultswithoutReplay.
//Regardingrealtime,itdoesnotrepaint.Ofcourseyouneedtowaitforthelastactivebartocompleteforittogiveyouindication.
//Youcandisablestrategytouseithasasoleindicator.
//TheremightbeanewscriptofRenkoStrategyV2inthefutureasihaveaprototype,followtogetupdated:https://www.tradingview.com/u/dman103/#published-scripts
strategy(title="RenkoStrategyT3V1",shorttitle="RenkoStrategyT3V1",overlay=true,precision=3,commission_value=0.0,default_qty_type=strategy.cash,default_qty_value=10000,initial_capital=10000)
useDate=input(true,title='----------------TradeRange----------------',type=input.bool)
FromMonth=input(defval=1,title="FromMonth",minval=1,maxval=12)
FromDay=input(defval=1,title="FromDay",minval=1,maxval=31)
FromYear=input(defval=2017,title="FromYear",minval=2000)
ToMonth=input(defval=1,title="ToMonth",minval=1,maxval=12)
ToDay=input(defval=1,title="ToDay",minval=1,maxval=31)
ToYear=input(defval=2021,title="ToYear",minval=2010)
start=timestamp(FromYear,FromMonth,FromDay,00,00)//backteststartwindow
finish=timestamp(ToYear,ToMonth,ToDay,23,59)//backtestfinishwindow
window()=>time>=startandtime<=finish?true:false//timerangefunction
settings=input(true,title='----------------Settings----------------',type=input.bool)
renkoSize=input(5,title="Renkosize",step=1)
renkoTimePeriod=input("",title="Timeframe")//Forexperimenting,Leavethisblankforcurrenttimeframe,Disforday,Wisforweekandsoon.Numbersforminues.
renko_tickerid=renko(syminfo.tickerid,"ATR",renkoSize)
allow_short=input(true,title="AllowShort")
color_bars=input(false,title="ColorBars")
disable_strategy=input(false,title="DisableStrategy")
//===TilsonT3===
T3Factor=input(defval=0.5,minval=0,maxval=100,step=0.05,title="T3Factor")
T3Length=input(defval=2,minval=1,title="T3Length")
T3FactorCalc=T3Factor*.10
gd(src,T3Length,T3FactorCalc)=>ema(src,T3Length)*(1+T3FactorCalc)-ema(ema(src,T3Length),T3Length)*T3FactorCalc
t3(src,T3Length,T3FactorCalc)=>gd(gd(gd(src,T3Length,T3FactorCalc),T3Length,T3FactorCalc),T3Length,T3FactorCalc)
//===RenkoLogic===
renko_close=security(renko_tickerid,renkoTimePeriod,close[1],lookahead=barmerge.lookahead_on)
renko_open=security(renko_tickerid,renkoTimePeriod,open[1],lookahead=barmerge.lookahead_on)
renko_high=security(renko_tickerid,renkoTimePeriod,high[1],lookahead=barmerge.lookahead_on)
renko_low=security(renko_tickerid,renkoTimePeriod,low[1],lookahead=barmerge.lookahead_on)
o2=t3(renko_open,T3Length,T3FactorCalc)
c2=t3(renko_close,T3Length,T3FactorCalc)
h2=t3(renko_high,T3Length,T3FactorCalc)
l2=t3(renko_low,T3Length,T3FactorCalc)
//===Plotting===
crossPlot=0.0
if(o2<c2)
crossPlot:=l2
else
crossPlot:=h2
//Usedtomakesurethatevenifo2andc2areequaltheresult(shortorlong)willbebasedonprevioustrend.UsuallyhappenswhenT3Tilsonlengthissmall.
bars_since_up=barssince(o2<c2)
bars_since_down=barssince(o2>c2)
go_long=(bars_since_up<bars_since_down)ando2<c2
go_short=(bars_since_up>bars_since_down)ando2>c2
plotColor=go_longando2<c2?color.green:go_shortando2>c2?color.red:color.white
plot(crossPlot,color=plotColor,style=plot.style_circles,linewidth=2,join=false)
barcolor(color_bars?plotColor==color.green?color.lime:color.red:na)
changeCond=plotColor!=plotColor[1]
//===Buy/Sell===
closeStatus=strategy.openprofit>0?"win":"lose"
long_entry=plotColor==color.greenandwindow()andchangeCond
long_exit_entry=plotColor==color.red//or(allow_alternative_slandclose<low_result)
short_entry=plotColor==color.redandwindow()andchangeCond
short_exit_entry=plotColor==color.green//or(allow_alternative_slandclose>high_result)
if(disable_strategy==false)
strategy.entry("long",true,when=long_entry)
strategy.close("long",when=long_exit_entry,comment=closeStatus)
if(allow_short)
strategy.entry("short",false,when=short_entry)
strategy.close("short",when=short_exit_entry,comment=closeStatus)
//===Alerts===
alertcondition(go_longandchangeCond,title='RenkoBuySignal',message='RenkoReveredtoBuySignal')
alertcondition(go_shortandchangeCond,title='RenkoSellSignal',message='RenkoReveredtoSellSignal')
Expand (91 lines)
