Script Name: Reversal with Bollinger Bands + RSI + ADX + ATR (Upgraded)
Author: conflixx95493
Description: Hi,

Welcome to my 4th script.
Someone asked me some questions about the Bollinger Band strategy I previously published. When I went back to my published script I couldn't help myself but simply try and make it better. Which I did.
Since I've published that script, I've gained much more knowledge about how Pinescript functions. As well as gaining more and more...
PineScript code:

Pine Script™ strategy
Reversal with Bollinger Bands + RSI + ADX + ATR (Upgraded)
//@version=4
strategy(shorttitle  =  "BB  +  EMA  +  RSI  +  ADX  +  ATR  Reversal",  title  =  "Bollinger  Bands  Reversal",  overlay  =  true,  default_qty_type  =  strategy.cash,  default_qty_value  =  100,  initial_capital  =  1000,  currency  =  currency.USD,  commission_type  =  strategy.commission.percent,  commission_value  =  0.036)
//  Inputs
strategyinput              =  input(title  =  "Active  Strategies",                                type  =  input.string,        defval  =  "Both",                                options  =  ["Both",  "Reversal",  "Breakout"],          group  =  "Strategy")
atrMultiplier              =  input(title  =  "ATR  Multiplier",                                      type  =  input.float,          defval  =  1.0,      minval  =  0.1,                                      step  =  0.25,                                        group  =  "Strategy")
ema1Input                      =  input(title  =  "EMA1  Input",                                              type  =  input.integer,      defval  =  200,      minval  =  10,        maxval  =  400,      step  =  10,                                            group  =  "Indicators")
ema2Input                      =  input(title  =  "EMA2  Input",                                              type  =  input.integer,      defval  =  100,      minval  =  10,        maxval  =  400,      step  =  10,                                            group  =  "Indicators")
stochMaxLongEntry      =  input(title  =  "Stochastic  Max  Long",                            type  =  input.integer,      defval  =  60,        minval  =  0,          maxval  =  100,                                                                      group  =  "Ranging  Indicators")
stochMinLongEntry      =  input(title  =  "Stochastic  Min  Long",                            type  =  input.integer,      defval  =  40,        minval  =  0,          maxval  =  100,                                                                      group  =  "Ranging  Indicators")
stochMaxShortEntry    =  input(title  =  "Stochastic  Max  Short",                          type  =  input.integer,      defval  =  60,        minval  =  0,          maxval  =  100,                                                                      group  =  "Ranging  Indicators")
stochMinShortEntry    =  input(title  =  "Stochastic  Min  Short",                          type  =  input.integer,      defval  =  40,        minval  =  0,          maxval  =  100,                                                                      group  ="RangingIndicators")
rsiMaxLongEntry=input(title="RSIMaxLong",type=input.integer,defval=60,minval=0,maxval=100,group="RangingIndicators")
rsiMinLongEntry=input(title="RSIMinLong",type=input.integer,defval=50,minval=0,maxval=100,group="RangingIndicators")
rsiMaxShortEntry=input(title="RSIMaxShort",type=input.integer,defval=40,minval=0,maxval=100,group="RangingIndicators")
rsiMinShortEntry=input(title="RSIMinShort",type=input.integer,defval=50,minval=0,maxval=100,group="RangingIndicators")
sigMaxValue=input(title="ADXMaxValue",type=input.integer,defval=30,minval=0,maxval=100,step=1,group="RangingIndicators")
rsiTrendingLongMax=input(title="RSIMaxTrendingLong",type=input.integer,defval=100,minval=0,maxval=100,group="TrendingIndicators")
rsiTrendingLongMin=input(title="RSIMinTrendingLong",type=input.integer,defval=65,minval=0,maxval=100,group="TrendingIndicators")
rsiTrendingShortMax=input(title="RSIMaxTrendingShort",type=input.integer,defval=35,minval=0,maxval=100,group="TrendingIndicators")
rsiTrendingShortMin=input(title="RSIMinTrendingShort",type=input.integer,defval=0,minval=0,maxval=100,group="TrendingIndicators")
sigMinValue=input(title="ADXMinValue",type=input.integer,defval=50,minval=0,maxval=100,step=1,group="TrendingIndicators")
adxlen=input(title="ADXSmoothing",type=input.integer,defval=14,group="ADXIndicator")
dilen=input(title="DILength",type=input.integer,defval=14,group="ADXIndicator")
atrLength=input(title="ATRLength",type=input.integer,defval=14,minval=1,group="ATRIndicator")
useStructure=input(title="UseTrailingStop?",type=input.bool,defval=true,group="ATRIndicator")
atrlookback=input(title="ATRLookbackPeriod",type=input.integer,defval=7,minval=1,group="ATRIndicator")
length=input(title="BBLength",type=input.integer,defval=20,minval=1,group="BollingerBandIndicator")
bbsrc=input(title="BBSource",type=input.source,defval=close,group="BollingerBandIndicator")
mult=input(title="BBStandardDeviation",type=input.float,defval=2.0,minval=0.001,maxval=50,group="BollingerBandIndicator")
offset=input(title="BBOffset",type=input.integer,defval=0,minval=-500,maxval=500,group="BollingerBandIndicator")
stochLength=input(title="StochasticLength",type=input.integer,defval=14,minval=1,group="StochasticIndicator")
rsilen=input(title="RSILength",type=input.integer,defval=14,minval=1,group="RSIIndicator")
rsisrc=input(title="RSISource",type=input.source,defval=close,group="RSIIndicator")
//Dateinput
fromMonth=input(defval=1,title="FromMonth",type=input.integer,minval=1,maxval=12,group="BacktestDateRange")
fromDay=input(defval=1,title="FromDay",type=input.integer,minval=1,maxval=31,group="BacktestDateRange")
fromYear=input(defval=2000,title="FromYear",type=input.integer,minval=1970,group="BacktestDateRange")
thruMonth=input(defval=1,title="ThruMonth",type=input.integer,minval=1,maxval=12,group="BacktestDateRange")
thruDay=input(defval=1,title="ThruDay",type=input.integer,minval=1,maxval=31,group="BacktestDateRange")
thruYear=input(defval=2099,title="ThruYear",type=input.integer,minval=1970,group="BacktestDateRange")
inDataRange=(time>=timestamp(syminfo.timezone,fromYear,fromMonth,fromDay,0,0))and(time<timestamp(syminfo.timezone,thruYear,thruMonth,thruDay,0,0))
//BuiltinBollingerBand
basis=sma(bbsrc,length)
dev=mult*stdev(bbsrc,length)
upper=basis+dev
lower=basis-dev
//BuiltinRSI
up=rma(max(change(rsisrc),0),rsilen)
down=rma(-min(change(rsisrc),0),rsilen)
rsi=down==0?100:up==0?0:100-(100/(1+up/down))
//BuiltinADX
dirmov(len)=>
up=change(high)
down=-change(low)
plusDM=na(up)?na:(up>downandup>0?up:0)
minusDM=na(down)?na:(down>upanddown>0?down:0)
truerange=rma(tr,len)
plus=fixnan(100*rma(plusDM,len)/truerange)
minus=fixnan(100*rma(minusDM,len)/truerange)
[plus,minus]
adx(dilen,adxlen)=>
[plus,minus]=dirmov(dilen)
sum=plus+minus
adx=100*rma(abs(plus-minus)/(sum==0?1:sum),adxlen)
sig=adx(dilen,adxlen)
//Variables
RangingStrategy=strategyinput=="Reversal"orstrategyinput=="Both"
BreakoutStrategy=strategyinput=="Breakout"orstrategyinput=="Both"
ema1=ema(close,ema1Input)
ema2=ema(close,ema2Input)
atr=atr(atrLength)
lookback=1
varStopLong=0.0
varStopShort=0.0
emaCheckLong=close>ema1andclose>ema2
emaCheckShort=close<ema1andclose<ema2
ReverseCandleLong=close[1]<open[1]andclose>open
ReverseCandleShort=close[1]>open[1]andclose<open
RangingLongStoch=stoch(close,high,low,stochLength)>stochMinLongEntryandstoch(close,high,low,stochLength)<stochMaxLongEntry
RangingShortStoch=stoch(close,high,low,stochLength)>stochMinShortEntryandstoch(close,high,low,stochLength)<stochMaxShortEntry
RangingLongRSI=rsi<rsiMaxLongEntryandrsi>rsiMinLongEntry
RangingShortRSI=rsi>rsiMaxShortEntryandrsi<rsiMinShortEntry
TrendingLongRSI=rsi<rsiTrendingLongMaxandrsi>rsiTrendingLongMin
TrendingShortRSI=rsi<rsiTrendingShortMaxandrsi>rsiTrendingShortMin
RangingADX=sig<sigMaxValue
TrendingADX=sig>sigMinValue
BreakoutLong=close>=upper
BreakoutShort=close<=lower
PriceBelowLower=false
fori=0tolookback
ifclose[i]<=lower[i]
PriceBelowLower:=true
PriceAboveUpper=false
fori=0tolookback
ifclose[i]>=upper[i]
PriceAboveUpper:=true
//Entry
CrossLongEntry=PriceBelowLowerandReverseCandleLongandRangingADXandRangingStrategyandRangingLongStochandemaCheckLongandsig<sigMaxValueandinDataRangeandstrategy.position_size==0//andRangingLongRSI
CrossShortEntry=PriceAboveUpperandReverseCandleShortandRangingADXandRangingStrategyandRangingShortStochandemaCheckShortandsig<sigMaxValueandinDataRangeandstrategy.position_size==0//andRangingShortRSI
TrendLongEntry=BreakoutLongandemaCheckLongandTrendingLongRSIandTrendingADXandBreakoutStrategyandinDataRangeandstrategy.position_size==0
TrendShortEntry=BreakoutShortandemaCheckShortandTrendingShortRSIandTrendingADXandBreakoutStrategyandinDataRangeandstrategy.position_size==0
//CalculatingATRstoplossandlettingittrail
StopLossLong=(useStructure?lowest(low,atrlookback):close)-atr*atrMultiplier
StopLossShort=(useStructure?highest(high,atrlookback):close)+atr*atrMultiplier
ifCrossLongEntryorTrendLongEntry
StopLong:=StopLossLong
ifCrossShortEntryorTrendShortEntry
StopShort:=StopLossShort
ifstrategy.position_size>0andStopLossLong>StopLong
StopLong:=StopLossLong
ifstrategy.position_size<0andStopLossShort<StopShort
StopShort:=StopLossShort

//Exitsignals
CrossLongExit=(PriceAboveUpperandReverseCandleShortandinDataRangeandstrategy.position_size>0)orclose<StopLongandRangingStrategy
CrossShortExit=(PriceBelowLowerandReverseCandleLongandinDataRangeandstrategy.position_size<0)orclose>StopShortandRangingStrategy
TrendLongExit=crossover(close,basis)orBreakoutStrategyandclose<=StopLongandstrategy.position_size>0
TrendShortExit=crossunder(close,basis)orBreakoutStrategyandclose>=StopShortandstrategy.position_size<0
//Strategy
strategy.entry("CrossLong",strategy.long,when=CrossLongEntry,comment="CrossLong")
strategy.close("CrossLong",when=CrossLongExit,comment="CrossLongExit")
strategy.entry("TrendLong",strategy.long,when=TrendLongEntry,comment="TrendLong")
strategy.close("TrendLong",when=TrendLongExit,comment="TrendLongExit")
strategy.entry("CrossShort",strategy.short,when=CrossShortEntry,comment="CrossShort")
strategy.close("CrossShort",when=CrossShortExit,comment="CrossShortExit")
strategy.entry("TrendShort",strategy.short,when=TrendShortEntry,comment="TrendShort")
strategy.close("TrendShort",when=TrendShortExit,comment="TrendShortExit")
//PlotstheBollingerBand
plot(basis,"Basis",color=#872323,offset=offset)
p1=plot(upper,"Upper",color=color.teal,offset=offset)
p2=plot(lower,"Lower",color=color.teal,offset=offset)
fill(p1,p2,title="Background",color=#198787,transp=95)
//Usethisifyouwanttoseethestoplossvisualised,beawarethoughplottingthesecanbeconfusing
//plot(StopLong)
//plot(StopShort)
Expand (149 lines)
