Script Name: Risk to Reward - FIXED SL Backtester
Author: TZack88
Description: Don't know how to code? No problem! TradingView is an excellent platform for you.  ✅ ✅

If you have an indicator that you want to backtest using a risk-to-reward ratio or fixed take profit/stop loss levels, then the  Risk to Reward - FIXED SL Backtester  script is the perfect solution for you.

introducing  Risk to Reward - FIXED SL Backtester  Script which will...
PineScript code:

Pine Script™ strategy
Risk to Reward - FIXED SL Backtester
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  TZack88
//@version=5
strategy(title='RR  -  FIXED  SL  Backtester',  shorttitle='ZCrypto  Backtester',overlay=true,pyramiding=1,  initial_capital=10000,
      commission_type=strategy.commission.percent,  commission_value=0.075,default_qty_value  =  33,  default_qty_type  =  strategy.percent_of_equity)

var  float  slVal                                          =  0.0
float  longTP                                                =  na
var  float  SL                                                =  na
float  BreakevenTP                                      =  na
float  BreakevenSL                                      =  na
var  float  TPlong                                        =  na
deal_start_condition                                =  false
var  float  long_sl_level                          =  na
color  bgray                                                  =  color.rgb(128,  223,  236,  81)
color  WHITE                                                  =  color.rgb(210,  210,  210)
color  red                                                      =  color.rgb(163,  46,  46,  29)
color  white                                                  =  color.rgb(248,  248,  248,  14)
color  olive                                                  =  color.olive
color  blue                                                    =  color.rgb(23,  43,  77)
color  Green                                                =  color.rgb(10,  218,  103,  34)
string  core                                                  =    "➞  Main  Core  Settings  🔸"
string  Breakeeven                                      =    "➞  Breakeven  Settings  🔸"
string  SLZ2          ="➞TP/SL(RiskSystem)🔸"
stringRRS="➞RisktoReward🔸"
stringFTPS="➞FixedTP&SL🔸"
stringBES="➞BreakEvenSettings🔸"
floatsmma=ta.sma(low,14)
stringSLZ2TOOL="SelectWhichrisksystemyouwannause?!RisktoRewardorfixedsystem"
stringRRT="YourRisktoRewardRatio?2:1thenput2"
string_tooltip3="Selectexternalindicatorplot"
stringSLSelect="SelecttheStoplossMethod"
floatexternal_indicator=input.source(defval=close,title='Externalindicator         ',group=core,tooltip=_tooltip3,inline="00")
floatdeal_start_value=input.int(defval=100,title='ExternalValue               ',group=core,tooltip="PlotValue",inline="01")
boolRisktype=input.string('RiskToReward',title='   🌀RiskType',group=SLZ2,inline="000",options=['RiskToReward','FixedTP&SL'],tooltip=SLZ2TOOL)=='RiskToReward'
floatRRTP=input.float(1.5,minval=0,step=0.1,title="RiskToRewardRatio",group=RRS,inline="01",tooltip=RRT)
stringstoploss=input.string("ATRSL",title="   ⬇️StoplossType",options=["ATRSL","Pivotlow","VWAPSL"],group=RRS,inline="02",tooltip=SLSelect)
floatATRSL=input.float(1.4,"         ATRFactor           ",step=0.1,group=RRS,inline="03",tooltip="OnlyusedwithATRSL")
intLB=input.int(8,minval=0,title="         PivotLookback     ",group=RRS,inline="04",tooltip="looksforlowerlow,OnlyusedwithPivotLow")
floatVWAPSL=input.float(2.5,"         VwapMultiplier    ",step=0.1,group=RRS,inline="05",tooltip="GetstheSMMAvalue,OnlyusedwithSMMASL")
floatFixedTP=input.float(1.5,minval=0,step=0.1,title="FixedTP",group=FTPS,inline="01")/100
floatFixedSL=input.float(1.5,minval=0,step=0.1,title="FixedSL",group=FTPS,inline="01")/100
boolbreakon=input.bool(true,"BreakEven?",group=BES,inline="06",tooltip="Breakevenw")
floatbreakRR=input.float(1.0,"    RiskToRewardRatio",step=0.1,group=BES,inline="07")
floatBEper=input.float(0.1,"      PercentAboveEntry",step=0.1,group=BES,inline="08",tooltip="MUSTbehigherthan'0'.Thisinputfrontloadsthenewbreakevenstoplosssothatitisactuallyinprofit.")/100
deal_start_condition:=ifexternal_indicator==deal_start_value
true
//-----SLcorecalculation-----{
x2=low-ta.rma(ta.tr(true),14)*ATRSL
stopLong=ta.lowest(low,LB)
vwap=math.sum(ta.vwap(ta.tr(true)),14)*volume
volumz=math.sum(volume,14)
atr_vwap_volume=math.abs(vwap/volumz)
longstoploss=low-atr_vwap_volume*VWAPSL
//}
//LetsgettheSLandreturnit
my_stop()=>
switchstoploss
"ATRSL"=>x2
"Pivotlow"=>stopLong
"SMMASL"=>longstoploss
sl=Risktype?my_stop():close*(1-FixedSL)
//letssettheSL,TPValues
ifdeal_start_conditionandstrategy.position_size==0
slVal:=sl
else
slVal:=slVal
longDiffSL=math.abs(close-slVal)
longTP:=deal_start_conditionandstrategy.position_size==0?Risktype?close+(RRTP*longDiffSL):close*(1+FixedTP):longTP[1]
//--BacktestDate?!{
limit_date_range=input.bool(title='LimitDateRange',defval=true,group='Backtestdaterange')
start_time=input.time(defval=timestamp('01Aug202200:00+0000'),title='StartTime',group='Backtestdaterange')
end_time=input.time(defval=timestamp('31Dec202500:00+0000'),title='EndTime',group='Backtestdaterange')
in_date_range=true
iflimit_date_range
in_date_range:=time>=start_timeandtime<=end_time

else
in_date_range:=true
//--}
longCondition=(deal_start_condition==true)andstrategy.position_size==0
//Breakeven
BreakevenTP:=longCondition?close+(breakRR*longDiffSL):BreakevenTP[1]
BREAKPLOT=strategy.position_size>0?BreakevenTP:na
BreakevenSL:=strategy.position_size>0?strategy.position_avg_price*(1+BEper):na
long_tp_hit=close>=BreakevenTPorhigh>=BreakevenTP
long_sl_level:=longCondition?slVal:long_tp_hit?BreakevenSL:long_sl_level[1]
if(in_date_rangeandlongCondition)
strategy.entry("LONG",strategy.long)
strategy.exit("Long3","LONG",
limit=longTP,
stop=(breakon?long_sl_level:slVal),
comment_profit="TPHIT",
comment_loss=breakon?"BEClose":"Loss"
)

//PLOTS
SLplot=strategy.position_size>0?slVal:na
SSL=plot(SLplot,title='LONGSTOPLOSS',linewidth=2,style=plot.style_linebr,color=red)
longPlotTP=strategy.position_size>0?longTP:na
TTP=plot(longPlotTP,title='LONGTAKEPROFIT',linewidth=2,style=plot.style_linebr,color=Green)
avg=plot(strategy.position_avg_price,style=plot.style_linebr,color=WHITE)
BREKEVENLINE=strategy.position_size>0?long_sl_level:na
plot(breakon?BREKEVENLINE:na,'AVGPrice',color=color.white,style=plot.style_linebr,editable=false,linewidth=2)
fill(TTP,avg,color=color.new(Green,80))
fill(avg,SSL,color=color.new(red,80))
Expand (133 lines)
