Script Name: Risk Management Strategy Template
Author: kevinmck100
Description: This strategy is intended to be used as a base template for building new strategies.

It incorporates the following features:

 Risk management:

 Configurable X% loss per stop loss
 Configurable R:R ratio


 Trade entry:

 Calculated position size based on risk tolerance


 Trade exit:

 Stop Loss currently configurable ATR multiplier but can be replaced...
PineScript code:

Pine Script™ strategy
Risk Management Strategy Template
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  kevinmck100
//  @description
//  This  strategy  is  intended  to  be  used  as  a  base  template  for  building  new  strategies.
//
//  It  incorporates  the  following  features:
//
//            -  Risk  management:    Configurable  X%  loss  per  stop  loss
//                                                    Configurable  R:R  ratio
//
//            -  Trade  entry:            Calculated  position  size  based  on  risk  tolerance
//
//            -  Trade  exit:              Stop  Loss  currently  configurable  ATR  multiplier  but  can  be  replaced  based  on  strategy
//                                                    Take  Profit  calculated  from  Stop  Loss  using  R:R  ratio
//
//            -  Backtesting:            Configurable  backtesting  range  by  date
//
//            -  Trade  drawings:      TP/SL  boxes  drawn  for  all  trades.  Can  be  turned  on  and  off
//                                                    Trade  exit  information  labels.  Can  be  turned  on  and  off
//                                                    NOTE:  Trade  drawings  will  only  be  applicable  when  using  overlay  strategies
//
//            -  Debugging:                Includes  section  with  useful  debugging  techniques
//
//  Strategy  conditions:
//
//            -  Trade  entry:            LONG:      C1:  Price  is  above  EMA  line
//                                                                    C2:  RSI  is  crossing  out  of  oversold  area
//                                                    SHORT:    C1:  Price  is  below  EMA  line
//                                                                    C2:  RSI  is  crossing  out  of  overbought  area
//
//            -  Trade  exit:              Stop  Loss:            Stop  Loss  ATR  multiplier  is  hit
//                                                    Take  Profit:        R:R  multiplier  *  Stop  Loss  is  hit
//
//  The  idea  is  to  use  RSI  to  catch  pullbacks  within  the  main  trend.  Note  that
//  this  strategy  is  intended  to  be  a  simple  base  strategy  for  building  upon.
//  It  was  not  designed  to  be  traded  in  its  current  form.
//@version=5
INITIAL_CAPITAL  =  1000
DEFAULT_COMMISSION  =  0.02
MAX_DRAWINGS  =  500
IS_OVERLAY  =  true
strategy("Risk  Management  Strategy  Template",  "Strategy  Template",  overlay  =  IS_OVERLAY,  initial_capital  =  INITIAL_CAPITAL,  currency  =  currency.NONE,  max_labels_count  =  MAX_DRAWINGS,  max_boxes_count  =  MAX_DRAWINGS,  max_lines_count  =  MAX_DRAWINGS,  default_qty_type  =  strategy.cash,  commission_type  =  strategy.commission.percent,  commission_value  =  DEFAULT_COMMISSION)
//  =============================================================================
//  INPUTS
//  =============================================================================
//  ------------------------  Replacable  section  -  Start  -------------------------
//  ------------------
//  Indicator  Settings
//  ------------------
emaLength                      =  input.int  (200,      "EMA  Length          ",                          group  =  "Indicators:  Settings",                  inline  =  "IS1",  minval  =  1,                                  tooltip  =  "EMA  line  to  identify  trend  direction.  Above  EMA  trend  line  is  bullish.  Below  EMA  trend  line  is  bearish")
rsiLength                      =  input.int  (10,    "RSILength          ",group="Indicators:Settings",inline="IS2",minval=1)
//----------------------
//TradeEntryConditions
//----------------------
rsiOverbought=input.int(60,"RSIOverbought        ",group="Strategy:Conditions",inline="SC1",minval=50,maxval=100,tooltip="RSIoverboughtlevelusedtoidentifypullbackswithinthemaintrend.RSIcrossingBELOWthisleveltriggersaSHORTwheninaDOWNtrend")
rsiOversold=input.int(40,"RSIOversold         ",group="Strategy:Conditions",inline="SC2",minval=0,maxval=50,tooltip="RSIoverboughtlevelusedtoidentifypullbackswithinthemaintrend.RSIcrossingABOVEthisleveltriggersaLONGwheninanUPtrend")
//---------------------
//TradeExitConditions
//---------------------
atrLength=input.int(14,"StopLossATRLength     ",group="Strategy:ExitConditions",inline="EC1",minval=0,tooltip="LengthofATRusedtocalculateStopLoss.")
slAtrMultiplier=input.float(4,"StopLossATRMultiplier    ",group="Strategy:ExitConditions",inline="EC2",minval=0,step=0.1,tooltip="SizeofStopLossisdeterminedbymultiplicationofATRvalue.TakeProfitisderivedfromthisalsobymultiplyingtheStopLossvaluebytheRisk:Rewardmultiplier.")
//-------------------------Replacablesection-End--------------------------
//---------------
//RiskManagement
//---------------
riskReward=input.float(2,"Risk:Reward        1:",group="Strategy:RiskManagement",inline="RM1",minval=0,step=0.1,tooltip="Previoushighorlow(long/shortdependant)isusedtodetermineTPlevel.'Risk:Reward'ratioisthenusedtocalculateSLbasedofprevioushigh/lowlevel.\n\nInshort,thehighertheR:Rratio,thesmallertheSLsinceTPtargetisfixedbyprevioushigh/lowpricedata.")
accountRiskPercent=input.float(1,"PortfolioRisk%        ",group="Strategy:RiskManagement",inline="RM1",minval=0,step=0.1,tooltip="PercentageofportfolioyouloseiftradehitsSL.\n\nYouthenstandtogain\nPortfolioRisk%*Risk:Reward\niftradehitsTP.")
//----------
//DateRange
//----------
startYear=input.int(2022,"StartDate     ",group='Strategy:DateRange',inline='DR1',minval=1900,maxval=2100)
startMonth=input.int(1,"",group='Strategy:DateRange',inline='DR1',options=[1,2,3,4,5,6,7,8,9,10,11,12])
startDate=input.int(1,"",group='Strategy:DateRange',inline='DR1',options=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])
endYear=input.int(2100,"EndDate      ",group='Strategy:DateRange',inline='DR2',minval=1900,maxval=2100)
endMonth=input.int(1,"",group='Strategy:DateRange',inline='DR2',options=[1,2,3,4,5,6,7,8,9,10,11,12])
endDate=input.int(1,"",group='Strategy:DateRange',inline='DR2',options=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])
//----------------
//DrawingSettings
//----------------
showTpSlBoxes=input.bool(true,"ShowTP/SLBoxes",group="Strategy:Drawings",inline="D1",tooltip="ShoworhideTPandSLpositionboxes.\n\nNote:TradingViewlimitsthemaximumnumberofboxesthatcanbedisplayedto500sotheymaynotappearforallpricedataundertest.")
showLabels=input.bool(false,"ShowTradeExitLabels",group="Strategy:Drawings",inline="D2",tooltip="UsefullabelstoidentifyProfit/Lossandcumulativeportfoliocapitalaftereachtradecloses.\n\nAlsonotethatTradingViewlimitsthemaxnumberof'boxes'thatcanbedisplayedonachart(max500).ThismeanswhenyoulookbackfarenoughonthechartyouwillnotseetheTP/SLboxes.Howeveryoucancheckthisoptiontoidentifywheretradesexited.")
//=============================================================================
//INDICATORS
//=============================================================================
//------------------------Replacablesection-Start-------------------------
//---
//EMA
//---
ema=ta.ema(close,emaLength)
plot(ema,"EMATrendLine",color.white)
//---
//RSI
//---
rsi=ta.rsi(close,rsiLength)
//-------------------------Replacablesection-End--------------------------
//=============================================================================
//STRATEGYLOGIC
//=============================================================================
//---------
//FUNCTIONS
//---------
percentAsPoints(pcnt)=>
math.round(pcnt/100*close/syminfo.mintick)

calcStopLossPrice(pointsOffset,isLong)=>
priceOffset=pointsOffset*syminfo.mintick
ifisLong
close-priceOffset
else
close+priceOffset
calcProfitTrgtPrice(pointsOffset,isLong)=>
calcStopLossPrice(-pointsOffset,isLong)


printLabel(barIndex,msg)=>label.new(barIndex,close,msg)
printTpSlHitBox(left,right,slHit,tpHit,entryPrice,slPrice,tpPrice)=>
ifshowTpSlBoxes
box.new(left=left,top=entryPrice,right=right,bottom=slPrice,bgcolor=slHit?color.new(color.red,60):color.new(color.gray,90),border_width=0)
box.new(left=left,top=entryPrice,right=right,bottom=tpPrice,bgcolor=tpHit?color.new(color.green,60):color.new(color.gray,90),border_width=0)
line.new(x1=left,y1=entryPrice,x2=right,y2=entryPrice,color=color.new(color.yellow,20))
line.new(x1=left,y1=slPrice,x2=right,y2=slPrice,color=color.new(color.red,20))
line.new(x1=left,y1=tpPrice,x2=right,y2=tpPrice,color=color.new(color.green,20))

printTpSlNotHitBox(left,right,entryPrice,slPrice,tpPrice)=>
ifshowTpSlBoxes
box.new(left=left,top=entryPrice,right=right,bottom=slPrice,bgcolor=color.new(color.gray,90),border_width=0)
box.new(left=left,top=entryPrice,right=right,bottom=tpPrice,bgcolor=color.new(color.gray,90),border_width=0)
line.new(x1=left,y1=entryPrice,x2=right,y2=entryPrice,color=color.new(color.yellow,20))
line.new(x1=left,y1=slPrice,x2=right,y2=slPrice,color=color.new(color.red,20))
line.new(x1=left,y1=tpPrice,x2=right,y2=tpPrice,color=color.new(color.green,20))

printTradeExitLabel(x,y,posSize,entryPrice,pnl)=>
ifshowLabels
labelStr="PositionSize:"+str.tostring(math.abs(posSize),"#.##")+"\nPNL:"+str.tostring(pnl,"#.##")+"\nCapital:"+str.tostring(strategy.equity,"#.##")+"\nEntryPrice:"+str.tostring(entryPrice,"#.##")
label.new(x=x,y=y,text=labelStr,color=pnl>0?color.new(color.green,60):color.new(color.red,60),textcolor=color.white,style=label.style_label_down)
//----------
//CONDITIONS
//----------
inDateRange=time>=timestamp(syminfo.timezone,startYear,startMonth,startDate,0,0)andtime<timestamp(syminfo.timezone,endYear,endMonth,endDate,0,0)
//------------------------Replacablesection-Start-------------------------
//Condition1:PriceaboveEMAindicatesbullishtrend,pricebelowEMAindicatesbearishtrend
bullEma=close>ema
bearEma=close<ema
//Condition2:RSIcrossingbackfromoverbought/oversoldindicatespullbackwithintrend
bullRsi=ta.crossover(rsi,rsiOversold)
bearRsi=ta.crossunder(rsi,rsiOverbought)
//Combineallentryconditions
goLong=inDateRangeandbullEmaandbullRsi
goShort=inDateRangeandbearEmaandbearRsi
//-------------------------Replacablesection-End--------------------------
//Tradeentryandexitvariables
vartradeEntryBar=bar_index
varprofitPoints=0.
varlossPoints=0.
varslPrice=0.
vartpPrice=0.
varinLong=false
varinShort=false
//Entrydecisions
openLong=(goLongandnotinLong)
openShort=(goShortandnotinShort)
flippingSides=(goLongandinShort)or(goShortandinLong)
enteringTrade=openLongoropenShort
inTrade=inLongorinShort
//------------------------Replacablesection-Start-------------------------
//Exitcalculations
atr=ta.atr(atrLength)
slAmount=atr*slAtrMultiplier
slPercent=math.abs((1-(close-slAmount)/close)*100)
tpPercent=slPercent*riskReward
//-------------------------Replacablesection-End--------------------------
//Riskcalculations
riskAmt=strategy.equity*accountRiskPercent/100
entryQty=math.abs(riskAmt/slPercent*100)/close
ifopenLong
ifstrategy.position_size<0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)
printTradeExitLabel(bar_index+1,math.max(tpPrice,slPrice),strategy.position_size,strategy.position_avg_price,strategy.openprofit)
strategy.entry("Long",strategy.long,qty=entryQty,alert_message="LongEntry")
enteringTrade:=true
inLong:=true
inShort:=false
ifopenShort
ifstrategy.position_size>0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)
printTradeExitLabel(bar_index+1,math.max(tpPrice,slPrice),strategy.position_size,strategy.position_avg_price,strategy.openprofit)
strategy.entry("Short",strategy.short,qty=entryQty,alert_message="ShortEntry")
enteringTrade:=true
inShort:=true
inLong:=false
ifenteringTrade
profitPoints:=percentAsPoints(tpPercent)
lossPoints:=percentAsPoints(slPercent)
slPrice:=calcStopLossPrice(lossPoints,openLong)
tpPrice:=calcProfitTrgtPrice(profitPoints,openLong)
tradeEntryBar:=bar_index
strategy.exit("TP/SL",profit=profitPoints,loss=lossPoints,comment_profit="TPHit",comment_loss="SLHit",alert_profit="TPHitAlert",alert_loss="SLHitAlert")
//=============================================================================
//DRAWINGS
//=============================================================================
//-----------
//TP/SLBoxes
//-----------
slHit=(inShortandhigh>=slPrice)or(inLongandlow<=slPrice)
tpHit=(inLongandhigh>=tpPrice)or(inShortandlow<=tpPrice)
exitTriggered=slHitortpHit
entryPrice=strategy.closedtrades.entry_price(strategy.closedtrades-1)
pnl=strategy.closedtrades.profit(strategy.closedtrades-1)
posSize=strategy.closedtrades.size(strategy.closedtrades-1)
//Printboxesfortradesclosedatprofitorloss
if(inTradeandexitTriggered)
inShort:=false
inLong:=false
printTpSlHitBox(tradeEntryBar+1,bar_index,slHit,tpHit,entryPrice,slPrice,tpPrice)
printTradeExitLabel(bar_index,math.max(tpPrice,slPrice),posSize,entryPrice,pnl)
//PrintTP/SLboxforcurrentopentrade
ifbarstate.islastconfirmedhistoryandstrategy.position_size!=0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)

//=============================================================================
//DEBUGGING
//=============================================================================
//Datawindowplots
plotchar(slPrice,"StopLossPrice","")
plotchar(tpPrice,"TakeProfitPrice","")
//Labelplots
plotDebugLabels=false
ifplotDebugLabels
ifbar_index==tradeEntryBar
printLabel(bar_index,"Positionsize:"+str.tostring(entryQty*close,"#.##"))
Expand (270 lines)
