Script Name: RSI Mean Reversion Bot Strategy
Author: Solutions1978
Description: I started developing this strategy as a way to plug in and test values before defining them in the bots on 3Commas, Coinrule, and Quadency. None of those bots performed the same way my script did and I kept working on it until the strategy finally yielded the same simulated results when paired with the Tradingview bot on Quadency. I looked at all the different RSI...
PineScript code:

Pine Script™ strategy
RSI Mean Reversion Bot Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//@version=4
//  ██████╗██████╗  ███████╗  █████╗  ████████╗███████╗██████╗          ██████╗  ██╗      ██╗
//██╔════╝██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██╔════╝██╔══██╗        ██╔══██╗╚██╗  ██╔╝
//██║          ██████╔╝█████╗    ███████║      ██║      █████╗    ██║    ██║        ██████╔╝  ╚████╔╝
//██║          ██╔══██╗██╔══╝    ██╔══██║      ██║      ██╔══╝    ██║    ██║        ██╔══██╗    ╚██╔╝
//╚██████╗██║    ██║███████╗██║    ██║      ██║      ███████╗██████╔╝        ██████╔╝      ██║
//  ╚═════╝╚═╝    ╚═╝╚══════╝╚═╝    ╚═╝      ╚═╝      ╚══════╝╚═════╝          ╚═════╝        ╚═╝

//███████╗██████╗██╗██╗██╗████████╗██╗██████╗███╗██╗███████╗██╗█████╗███████╗█████╗
//██╔════╝██╔═══██╗██║██║██║╚══██╔══╝██║██╔═══██╗████╗██║██╔════╝███║██╔══██╗╚════██║██╔══██╗
//███████╗██║██║██║██║██║██║██║██║██║██╔██╗██║███████╗╚██║╚██████║██╔╝╚█████╔╝
//╚════██║██║██║██║██║██║██║██║██║██║██║╚██╗██║╚════██║██║╚═══██║██╔╝██╔══██╗
//███████║╚██████╔╝███████╗╚██████╔╝██║██║╚██████╔╝██║╚████║███████║██║█████╔╝██║╚█████╔╝
//╚══════╝╚═════╝╚══════╝╚═════╝╚═╝╚═╝╚═════╝╚═╝╚═══╝╚══════╝╚═╝╚════╝╚═╝╚════╝

strategy(shorttitle='RSIBotStrategyv3',title='HolyGrailRSIStrategy',overlay=true,scale=scale.left,initial_capital=1000,process_orders_on_close=true,default_qty_type=strategy.percent_of_equity,default_qty_value=100,commission_type=strategy.commission.percent,commission_value=0.18,calc_on_every_tick=true)
kcolor=color.new(#0094FF,60)
dcolor=color.new(#FF6A00,60)
//-----------------StrategyInputs-------------------------------------------------------------
//Backtestdateswithautofinishdateoftoday
start=input(defval=timestamp("01April202100:00-0500"),title="StartTime",type=input.time)
finish=input(defval=timestamp("31December202100:00-0600"),title="EndTime",type=input.time)
window()=>time>=startandtime<=finish?true:false//createfunction"withinwindowoftime"
//StrategySelection-Long,Short,orBoth
stratinfo=input(true,"Long/ShortforMixedMarket,LongforBull,ShortforBear")
strat=input(title="TradeTypes",defval="Long/Short",options=["LongOnly","Long/Short","ShortOnly"])
strat_val=strat=="LongOnly"?1:strat=="Long/Short"?0:-1
//RiskManagementInputs
sl=input(10.0,"StopLoss%",minval=0,maxval=100,step=0.01)
tp=input(20.0,"TargetProfit%",minval=0,maxval=100,step=0.01)
stoploss=sl/100
TargetProfit=tp/100
//RSIInputs
RSIinfo=input(true,"RSIStrategyInputs")
length=input(14,minval=1)
source=input(title="Source",type=input.source,defval=close)
overbought=input(60,"Overbought")
oversold=input(30,"Oversold")
//StochasticInputs
Stochinfo=input(true,"StochasticOverlayInputs")
smoothK=input(3,"K",minval=1)
smoothD=input(3,"D",minval=1)
k_mode=input("SMA","KMode",options=["SMA","EMA","WMA"])
//EMAInputs
EMAInfo=input(true,"EMAFastandSlowLengthInputs")
fastLength=input(5,minval=1,title="EMAFastLength")
slowLength=input(10,minval=1,title="EMASlowLength")
VWAPSource=input(title="VWAPSource",type=input.source,defval=close)
//Selectionstoshoworhidetheoverlays
showZones=input(true,title="ShowBullish/BearishZones")
showStoch=input(true,title="ShowStochasticOverlays")
//------------------BackgroundColorsbasedonEMAIndicators-----------------------------------
haClose(gap)=>(open[gap]+high[gap]+low[gap]+close[gap])/4
rsi_ema=rsi(haClose(0),length)
v2=ema(rsi_ema,length)
v3=2*v2-ema(v2,length)
emaA=ema(rsi_ema,fastLength)
emaFast=2*emaA-ema(emaA,fastLength)
emaB=ema(rsi_ema,slowLength)
emaSlow=2*emaB-ema(emaB,slowLength)
vwapVal=vwap(VWAPSource)
//bullishsignalrule:
bullishRule=emaFast>emaSlowandclose>openandclose>vwapVal
//bearishsignalrule:
bearishRule=emaFast<emaSlowandclose<openandclose<vwapVal
//currenttradingState
ruleState=0
ruleState:=bullishRule?1:bearishRule?-1:nz(ruleState[1])
ruleColor=ruleState==1?color.new(color.blue,90):ruleState==-1?color.new(color.red,90):ruleState==0?color.new(color.gray,90):na
bgcolor(showZones?ruleColor:na,title="Bullish/BearishZones")
//------------------StochasticIndicatorOverlay-----------------------------------------------
//Calculation
rsi1=rsi(source,length)
stoch=stoch(rsi1,rsi1,rsi1,length)
k=
k_mode=="EMA"?ema(stoch,smoothK):
k_mode=="WMA"?wma(stoch,smoothK):
sma(stoch,smoothK)
d=sma(k,smoothD)
k_c=change(k)
d_c=change(d)
kd=k-d
//Plot
signalColor=k>oversoldandd<overboughtandk>dandk_c>0andd_c>0?kcolor:
k<overboughtandd>oversoldandk<dandk_c<0andd_c<0?dcolor:na
kp=plot(showStoch?k:na,"K",color=kcolor)
dp=plot(showStoch?d:na,"D",color=dcolor)
fill(kp,dp,color=signalColor,title="K-D")
signalUp=showStoch?notna(signalColor)andkd>0:na
signalDown=showStoch?notna(signalColor)andkd<0:na
plot(signalUp?kd:na,"SignalUp",color=kcolor,style=plot.style_columns)
plot(signalDown?(kd+100):na,"SignalDown",color=dcolor,style=plot.style_columns,histbase=100)
//AddRSICandlePlottoStrategyforbettervisualization
//overlayRSI
h0=hline(oversold,title="Oversold",color=color.green)
h1=hline(overbought,title="Overbought",color=color.red)
RSIFill=color.new(#9915FF,95)
fill(h0,h1,RSIFill,title="BandBackground")
plot(rsi1,title="RSI",color=color.yellow,linewidth=3)
//EndPlotCode
//--------------------------------EntryandExitLogic------------------------------------
//EntryLogic
GoLong=strat_val>-1andcrossover(rsi1,oversold)andstrategy.position_size==0andwindow()
GoShort=strat_val<1andcrossunder(rsi1,overbought)andstrategy.position_size==0andwindow()
//StrategyEntryandExitwithbuiltinRiskManagement
if(GoLong)
strategy.entry("LONG",strategy.long)
if(GoShort)
strategy.entry("SHORT",strategy.short)
CloseLong=strat_val>-1andstrategy.position_size>0andcrossover(rsi1,overbought)andwindow()
CloseShort=strat_val<1andstrategy.position_size<0andcrossunder(rsi1,oversold)andwindow()
if(CloseLong)
strategy.close("LONG")
if(CloseShort)
strategy.close("SHORT")

//Determinewhereyou'veenteredandinwhatdirection
longStopPrice=strategy.position_avg_price*(1-stoploss)
longTakePrice=strategy.position_avg_price*(1+TargetProfit)
shortStopPrice=strategy.position_avg_price*(1+stoploss)
shortTakePrice=strategy.position_avg_price*(1-TargetProfit)
if(strategy.position_size>0)
strategy.exit(id="ExitLong",from_entry="LONG",stop=longStopPrice,limit=longTakePrice)

if(strategy.position_size<0)
strategy.exit(id="ExitShort",from_entry="SHORT",stop=shortStopPrice,limit=shortTakePrice)
//PLOTFIXEDSLTPLINE
plot(strategy.position_size>0?longStopPrice:na,style=plot.style_linebr,color=color.red,linewidth=1,title="LongFixedSL")
plot(strategy.position_size<0?shortStopPrice:na,style=plot.style_linebr,color=color.red,linewidth=1,title="ShortFixedSL")
plot(strategy.position_size>0?longTakePrice:na,style=plot.style_linebr,color=color.green,linewidth=1,title="LongTakeProfit")
plot(strategy.position_size<0?shortTakePrice:na,style=plot.style_linebr,color=color.green,linewidth=1,title="ShortTakeProfit")
Expand (177 lines)
