Script Name: RSI and MA with Trailing Stop Loss and Take Profit (by Coinrule)
Author: Coinrule
Description: The relative strength index is a momentum indicator used in technical analysis. It measures the speed and magnitude of a coin's recent price changes to evaluate overvalued or undervalued conditions in the price of that coin. The RSI is displayed as an oscillator (a line graph essentially) on a scale of zero to 100. When the RSI reaches oversold levels, it can...
PineScript code:

Pine Script™ strategy
RSI and MA with Trailing Stop Loss and Take Profit (by Coinrule)
//@version=5
strategy("RSI  and  MA  Strategy  with  Trailing  Stop  Loss  and  Take  Profit",
                  overlay=true,
                  initial_capital=1000,
                  process_orders_on_close=true,
                  default_qty_type=strategy.percent_of_equity,
                  default_qty_value=100,
                  commission_type=strategy.commission.percent,
                  commission_value=0.1)
showDate  =  input(defval=true,  title='Show  Date  Range')
timePeriod  =  time  >=  timestamp(syminfo.timezone,  2022,  1,  1,  0,  0)
notInTrade  =  strategy.position_size  <=  0
//==================================Buy  Conditions============================================
//RSI
length  =  input(14)
rsi  =  ta.rsi(close,  length)
buyCondition1  =  rsi  >  50
//MA
SMA9  =  ta.sma(close,  9)
SMA50  =  ta.sma(close,  50)
SMA100  =  ta.sma(close,  100)
plot(SMA9,  color  =  color.green)
plot(SMA50,  color  =  color.orange)
plot(SMA100,  color  =  color.blue)
buyCondition2  =  SMA9  >  SMA50//ta.crossover(SMA9,  SMA100)
//RSI  Increase
increase  =  5
buyCondition3  =  (rsi  >  rsi[1]  +  increase)
if  (buyCondition1  and  buyCondition2  and  buyCondition3  and  timePeriod)  //and  buyCondition
        strategy.entry("Long",  strategy.long)
//==================================SellConditions============================================
//TrailingStopLossandTakeProfit
longTrailPerc=input.float(title='TrailLongLoss(%)',minval=0.0,step=0.1,defval=2)*0.01
shortTrailPerc=input.float(title='TrailShortLoss(%)',minval=0.0,step=0.1,defval=1)*0.01
longStopPrice=0.0
shortStopPrice=0.0
longStopPrice:=ifstrategy.position_size>0
stopValue=close*(1-longTrailPerc)
math.max(stopValue,longStopPrice[1])
else
0
shortStopPrice:=ifstrategy.position_size<0
stopValue=close*(1+shortTrailPerc)
math.min(stopValue,shortStopPrice[1])
else
999999
strategy.exit(id="Exit",stop=longStopPrice,limit=shortStopPrice)
Expand (61 lines)
