Script Name: Sideways Strategy DMI + Bollinger Bands (by Coinrule)
Author: Coinrule
Description: Markets don’t always trade in a clear direction. At a closer look, most of the time, they move sideways.  Relying on trend-following strategies all the time can thus lead to repeated false signals in such conditions.

However, before you can safely trade sideways, you have to identify the most suitable market conditions.

The main features of such strategies...
PineScript code:

Pine Script™ strategy
Sideways Strategy DMI + Bollinger Bands (by Coinrule)
//@version=4
strategy(shorttitle='Sideways  Strategy  DMI  +  Bollinger  Bands',title='Sideways  Strategy  DMI  +  Bollinger  Bands  (by  Coinrule)',  overlay=true,  initial_capital  =  100,  process_orders_on_close=true,  default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  100,  commission_type=strategy.commission.percent,  commission_value=0.1)
//  Works  on  ETHUSD  3h,  1h,  2h,  4h
//Backtest  dates
fromMonth  =  input(defval  =  1,        title  =  "From  Month",            type  =  input.integer,  minval  =  1,  maxval  =  12)
fromDay      =  input(defval  =  1,        title  =  "From  Day",                type  =  input.integer,  minval  =  1,  maxval  =  31)
fromYear    =  input(defval  =  2021,  title  =  "From  Year",              type  =  input.integer,  minval  =  1970)
thruMonth  =  input(defval  =  12,        title  =  "Thru  Month",            type  =  input.integer,  minval  =  1,  maxval  =  12)
thruDay      =  input(defval  =  31,        title  =  "Thru  Day",                type  =  input.integer,  minval  =  1,  maxval  =  31)
thruYear    =  input(defval  =  2022,  title  =  "Thru  Year",              type  =  input.integer,  minval  =  1970)
showDate    =  input(defval  =  true,  title  =  "Show  Date  Range",  type  =  input.bool)
start          =  timestamp(fromYear,  fromMonth,  fromDay,  00,  00)                //  backtest  start  window
finish        =  timestamp(thruYear,  thruMonth,  thruDay,  23,  59)                //  backtest  finish  window
window()    =>  time  >=  start  and  time  <=  finish  ?  true  :  false              //  create  function  "within  window  of  time"
[pos_dm,  neg_dm,  adx]  =  dmi(14,  14)
lengthBB  =  input(20,  minval=1)
src  =  input(close,  title="Source")
mult  =  input(2.0,  minval=0.001,  maxval=50,  title="StdDev")
basis  =  sma(src,  lengthBB)
dev  =  mult  *  stdev(src,  lengthBB)
upper  =  basis  +  dev
lower  =  basis  -  dev
offset  =  input(0,  "Offset",  type  =  input.integer,  minval  =  -500,  maxval  =  500)
sideways  =  (abs(pos_dm  -  neg_dm)  <  20)
//Stop_loss=  ((input  (3))/100)
//Take_profit=  ((input  (2))/100)
//longStopPrice    =  strategy.position_avg_price  *  (1  -  Stop_loss)
//longTakeProfit  =  strategy.position_avg_price  *  (1  +  Take_profit)
//closeLong  =  close  <  longStopPrice  or  close  >  longTakeProfit  or  StopRSI
//Entry
strategy.entry(id="long",  long  =  true,  when  =  sideways  and  (crossover(close,  lower))  and  window())
//Exit
strategy.close("long",  when  =  (crossunder(close,  upper)))
Expand (51 lines)
