Script Name: Simple and Profitable Scalping Strategy (ForexSignals TV)
Author: kevinmck100
Description: Strategy is based on the "SIMPLE and PROFITABLE Forex Scalping Strategy" taken from YouTube channel ForexSignals TV.
See video for a detailed explaination of the whole strategy.

I'm not entirely happy with the performance of this strategy yet however I do believe it has potential as the concept makes a lot of sense.
I'm open to any ideas people have on how it...
PineScript code:

Pine Script™ strategy
Simple and Profitable Scalping Strategy (ForexSignals TV)
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  kevinmck100
//  @description
//
//  Strategy  called  SIMPLE  and  PROFITABLE  Forex  Scalping  Strategy  taken  from  YouTube  channel  ForexSignals  TV.
//  See  video  for  a  detailed  explaination  of  the  whole  strategy.
//
//  It  works  on  the  basis  of  waiting  for  pullbacks  into  the  EMAs  while  trading  in  the  direction  of  the  higher  timeframe  trend
//
//  Strategy  incorporates  the  following  features:
//
//            -  Risk  management:    Configurable  X%  loss  per  stop  loss
//                                                    Configurable  R:R  ratio
//
//            -  Trade  entry:            Calculated  position  size  based  on  risk  tolerance
//                                                    Entry  price  is  a  stop  order  set  just  above  the  recent  swing  high/low  (long/short)
//
//            -  Trade  exit:              Stop  Loss  is  set  just  below  trigger  candle's  low/high  (long/short)
//                                                    Take  Profit  calculated  from  Stop  Loss  using  R:R  ratio
//
//            -  Backtesting:            Configurable  backtesting  range  by  date
//
//            -  Trade  drawings:      TP/SL  boxes  drawn  for  all  trades.  Can  be  turned  on  and  off
//                                                    Trade  exit  information  labels.  Can  be  turned  on  and  off
//                                                    NOTE:  Trade  drawings  will  only  be  applicable  when  using  overlay  strategies
//
//            -  Debugging:                Includes  section  with  useful  debugging  techniques
//
//  Strategy  conditions:
//
//            -  Trade  entry:            LONG:      C1:  On  higher  timeframe  trend  EMAs,  Fast  EMA  must  be  above  Slow  EMA
//                                                                    C2:  On  higher  timeframe  trend  EMAs,  price  must  be  above  Fast  EMA
//                                                                    C3:  On  current  timeframe  entry  EMAs,  Fast  EMA  must  be  above  Medium  EMA  and  Medium  EMA  must  be  above  Slow  EMA
//                                                                    C4:  On  current  timeframe  entry  EMAs,  all  3  EMA  lines  must  have  fanned  out  in  upward  direction  for  previous  X  candles
//                                                                    C5:  On  current  timeframe  entry  EMAs,  previous  candle  must  have  closed  above  and  not  touched  any  EMA  lines
//                                                                    C6:  On  current  timeframe  entry  EMAs,  current  candle  must  have  pulled  back  to  touch  the  EMA  line(s)
//                                                                    C7:  Price  must  break  through  the  high  of  the  last  X  candles  to  trigger  entry
//
//                                                    SHORT:    C1:  On  higher  timeframe  trend  EMAs,  Fast  EMA  must  be  below  Slow  EMA
//                                                                    C2:  On  higher  timeframe  trend  EMAs,  price  must  be  below  Fast  EMA
//                                                                    C3:  On  current  timeframe  entry  EMAs,  Fast  EMA  must  be  below  Medium  EMA  and  Medium  EMA  must  be  below  Slow  EMA
//                                                                    C4:  On  current  timeframe  entry  EMAs,  all  3  EMA  lines  must  have  fanned  out  in  downward  direction  for  previous  X  candles
//                                                                    C5:  On  current  timeframe  entry  EMAs,  previous  candle  must  have  closed  above  and  not  touched  any  EMA  lines
//                                                                    C6:  On  current  timeframe  entry  EMAs,  current  candle  must  have  pulled  back  to  touch  the  EMA  line(s)
//                                                                    C7:  Price  must  break  through  the  low  of  the  last  X  candles  to  trigger  entry
//
//            -  Trade  exit:              Trade  Invalidation:  Price  closes  below/above  (long/short)  the  current  timeframe  Slow  EMA
//                                                    Stop  Loss:                    Placed  just  below  trigger  candle  low/high  (long/short)
//                                                    Take  Profit:                R:R  multiplier  *  Stop  Loss  is  hit
//                                                                                            NOTE:  The  original  strategy  uses  2  TP  levels.  I  may  add  this  in  futurebutwouldliketoseesomebetterresultsfromasingleTPbeforeIgototheefforttoaddthis
//@version=5
INITIAL_CAPITAL=1000
DEFAULT_COMMISSION=0.02
MAX_DRAWINGS=500
IS_OVERLAY=true
strategy("SimpleandProfitableScalpingStrategy(ForexSignalsTV)","ScalpingStrategy",overlay=IS_OVERLAY,initial_capital=INITIAL_CAPITAL,currency=currency.NONE,max_labels_count=MAX_DRAWINGS,max_boxes_count=MAX_DRAWINGS,max_lines_count=MAX_DRAWINGS,default_qty_type=strategy.cash,commission_type=strategy.commission.percent,commission_value=DEFAULT_COMMISSION)
//=============================================================================
//INPUTS
//=============================================================================
trendFilterTf=input.timeframe("60","TrendTimeframe        ",group="Strategy:HigherTimeframeTrendFilter",inline="TF1",tooltip="Highertimeframetouseforfindingmaintranddirection")
trendFastEmaLen=input.int(8,"FastEMALength        ",group="Strategy:HigherTimeframeTrendFilter",inline="TF2",minval=1,tooltip="LengthofFastEMAofhighertimeframe")
trendSlowEmaLen=input.int(21,"SlowEMALength       ",group="Strategy:HigherTimeframeTrendFilter",inline="TF3",minval=1,tooltip="LengthofSlowEMAofhighertimeframe")
//----------------------
//TradeEntryConditions
//----------------------
entryFastEmaLen=input.int(8,"FastEMALength       ",group="Strategy:TradeEntryConditions",inline="TE1",minval=1,tooltip="FastEMAusedtofindentrycandleswhenpricepullsbackintothisline")
entryMedEmaLen=input.int(13,"MediumEMALength      ",group="Strategy:TradeEntryConditions",inline="TE2",minval=1,tooltip="MediumEMAusedtofilteroutentrieswhenlinesarenotfannedoutornottrendinginthedesireddirection")
entrySlowEmaLen=input.int(21,"SlowEMALength       ",group="Strategy:TradeEntryConditions",inline="TE3",minval=1,tooltip="SlowEMAusedtofilteroutentrieswhenlinesarenotfannedoutornottrendinginthedesireddirection.\n\nAlsousedtocancelopenorderswhichclosebelowthisEMAbeforeentryhasbeentriggered")
fanoutAtrMult=input.float(0.5,"EMAFanoutATRMultiplier   ",group="Strategy:TradeEntryConditions",inline="TE4",step=0.1,tooltip="ATRmultipliertodeterminehowbutthefanoutgapmustbebetweentheFastEMAandSlowEMAoverthespecifiednumberofcandles")
fanoutLookback=input.int(3,"EMAFanoutLookback     ",group="Strategy:TradeEntryConditions",inline="TE5",minval=1,tooltip="NumberofcandlesoverwhichtheentryEMAlinesmustbefannedoutbythespecifiedamount")
priceBufferAtrMult=input.float(0.5,"PriceBufferATRMultiplier   ",group="Strategy:TradeEntryConditions",inline="TE6",step=0.1,tooltip="ATRmultipliertodeterminehowbigofabuttershouldbesetabove/belowtradeentryandstoploss")
localHighLookback=input.int(5,"EntryPriceHigh/LowLookback ",group="Strategy:TradeEntryConditions",inline="TE7",minval=1,tooltip="Numberofcandlestolookbackontofindthelocalhigh/lowwhichisusedtoestablishthestoporderentryprice")
//---------------
//RiskManagement
//---------------
riskReward=input.float(2,"Risk:Reward        1:",group="Strategy:RiskManagement",inline="RM1",minval=0,step=0.1,tooltip="Previoushighorlow(long/shortdependant)isusedtodetermineTPlevel.'Risk:Reward'ratioisthenusedtocalculateSLbasedofprevioushigh/lowlevel.\n\nInshort,thehighertheR:Rratio,thesmallertheSLsinceTPtargetisfixedbyprevioushigh/lowpricedata.")
accountRiskPercent=input.float(1,"PortfolioRisk%        ",group="Strategy:RiskManagement",inline="RM2",minval=0,step=0.1,tooltip="PercentageofportfolioyouloseiftradehitsSL.\n\nYouthenstandtogain\nPortfolioRisk%*Risk:Reward\niftradehitsTP.")
//----------
//DateRange
//----------
startYear=input.int(2022,"StartDate     ",group='Strategy:DateRange',inline='DR1',minval=1900,maxval=2100)
startMonth=input.int(1,"",group='Strategy:DateRange',inline='DR1',options=[1,2,3,4,5,6,7,8,9,10,11,12])
startDate=input.int(1,"",group='Strategy:DateRange',inline='DR1',options=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])
endYear=input.int(2100,"EndDate      ",group='Strategy:DateRange',inline='DR2',minval=1900,maxval=2100)
endMonth=input.int(1,"",group='Strategy:DateRange',inline='DR2',options=[1,2,3,4,5,6,7,8,9,10,11,12])
endDate=input.int(1,"",group='Strategy:DateRange',inline='DR2',options=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31])
//----------------
//DrawingSettings
//----------------
showTpSlBoxes=input.bool(true,"ShowTP/SLBoxes",group="Strategy:Drawings",inline="D1",tooltip="ShoworhideTPandSLpositionboxes.\n\nNote:TradingViewlimitsthemaximumnumberofboxesthatcanbedisplayedto500sotheymaynotappearforallpricedataundertest.")
showLabels=input.bool(false,"ShowTradeExitLabels",group="Strategy:Drawings",inline="D2",tooltip="UsefullabelstoidentifyProfit/Lossandcumulativeportfoliocapitalaftereachtradecloses.\n\nAlsonotethatTradingViewlimitsthemaxnumberof'boxes'thatcanbedisplayedonachart(max500).ThismeanswhenyoulookbackfarenoughonthechartyouwillnotseetheTP/SLboxes.Howeveryoucancheckthisoptiontoidentifywheretradesexited.")
//=============================================================================
//INDICATORS
//=============================================================================
//--------------------------
//TrendHigherTimeframeEMA
//--------------------------
varfloatcurrTrendFastEma=na
varfloatcurrTrendSlowEma=na
varcoloremaFillColor=na
trendFastEma=ta.ema(close,trendFastEmaLen)
trendSlowEma=ta.ema(close,trendSlowEmaLen)
fastSec=request.security(syminfo.tickerid,trendFilterTf,trendFastEma,barmerge.gaps_off,barmerge.lookahead_off)
slowSec=request.security(syminfo.tickerid,trendFilterTf,trendSlowEma,barmerge.gaps_off,barmerge.lookahead_off)
currTrendFastEma:=na(fastSec)?currTrendFastEma[1]:fastSec
currTrendSlowEma:=na(slowSec)?currTrendSlowEma[1]:slowSec
fastEmaPlot=plot(fastSec,color=color.green)
slowEmaPlot=plot(slowSec,color=color.red)
emaFillColor:=fastSec>slowSec?color.new(color.green,80):fastSec<slowSec?color.new(color.red,80):emaFillColor[1]
fill(fastEmaPlot,slowEmaPlot,color=emaFillColor,fillgaps=true)
//---------------
//TradeEntryEMA
//---------------
entryFastEma=ta.ema(close,entryFastEmaLen)
entryMedEma=ta.ema(close,entryMedEmaLen)
entrySlowEma=ta.ema(close,entrySlowEmaLen)
plot(entryFastEma,color=color.orange)
plot(entryMedEma,color=color.yellow)
plot(entrySlowEma,color=color.purple)
//=============================================================================
//STRATEGYLOGIC
//=============================================================================
//---------
//FUNCTIONS
//---------
printLabel(barIndex,msg)=>label.new(barIndex,close,msg)
percentAsPoints(pcnt)=>
math.round(pcnt/100*close/syminfo.mintick)

calcStopLossPrice(pointsOffset,entryPrice,isLong)=>
priceOffset=pointsOffset*syminfo.mintick
ifisLong
entryPrice-priceOffset
else
entryPrice+priceOffset
calcProfitTrgtPrice(pointsOffset,entryPrice,isLong)=>calcStopLossPrice(-pointsOffset,entryPrice,isLong)


printTpSlHitBox(left,right,slHit,tpHit,entryPrice,slPrice,tpPrice)=>
ifshowTpSlBoxes
box.new(left=left,top=entryPrice,right=right,bottom=slPrice,bgcolor=slHit?color.new(color.red,60):color.new(color.gray,90),border_width=0)
box.new(left=left,top=entryPrice,right=right,bottom=tpPrice,bgcolor=tpHit?color.new(color.green,60):color.new(color.gray,90),border_width=0)
line.new(x1=left,y1=entryPrice,x2=right,y2=entryPrice,color=color.new(color.yellow,20))
line.new(x1=left,y1=slPrice,x2=right,y2=slPrice,color=color.new(color.red,20))
line.new(x1=left,y1=tpPrice,x2=right,y2=tpPrice,color=color.new(color.green,20))

printTpSlNotHitBox(left,right,entryPrice,slPrice,tpPrice)=>
ifshowTpSlBoxes
box.new(left=left,top=entryPrice,right=right,bottom=slPrice,bgcolor=color.new(color.orange,90),border_width=0)
box.new(left=left,top=entryPrice,right=right,bottom=tpPrice,bgcolor=color.new(color.orange,90),border_width=0)
line.new(x1=left,y1=entryPrice,x2=right,y2=entryPrice,color=color.new(color.yellow,20))
line.new(x1=left,y1=slPrice,x2=right,y2=slPrice,color=color.new(color.red,20))
line.new(x1=left,y1=tpPrice,x2=right,y2=tpPrice,color=color.new(color.green,20))

printTradeExitLabel(x,y,posSize,entryPrice,pnl)=>
ifshowLabels
labelStr=pnl!=0?"PositionSize:"+str.tostring(math.abs(posSize),"#.##")+"\nPNL:"+str.tostring(pnl,"#.##")+"\nCapital:"+str.tostring(strategy.equity,"#.##")+"\nEntryPrice:"+str.tostring(entryPrice,"#.##"):"TradeCancelled"
label.new(x=x,y=y,text=labelStr,color=pnl>0?color.new(color.green,60):pnl<0?color.new(color.red,60):color.new(color.orange,60),textcolor=color.white,style=label.style_label_down)
printVerticalLine(col)=>line.new(bar_index,close,bar_index,close*1.01,extend=extend.both,color=col)
//----------
//CONDITIONS
//----------
inDateRange=time>=timestamp(syminfo.timezone,startYear,startMonth,startDate,0,0)andtime<timestamp(syminfo.timezone,endYear,endMonth,endDate,0,0)
//Condition1:HighertimeframetrendEMAsmustbeincorrectorder
bullTrendDir=currTrendFastEma>currTrendSlowEma
bearTrendDir=currTrendFastEma<currTrendSlowEma
//Condition2:PricemustbeoutsidetheEMAtrendband
bullTrendPrice=close>currTrendFastEma
bearTrendPrice=close<currTrendFastEma
//Condition3:EMAlinesmustbeincorrectorder
bullEmaOrder=entryFastEma>entryMedEmaandentryMedEma>entrySlowEma
bearEmaOrder=entryFastEma<entryMedEmaandentryMedEma<entrySlowEma
//Condition4:EMAlinesmustfannedoutforpreviousXcandles
fanOutGap=ta.atr(14)*fanoutAtrMult
varbullFanOutGap=false
varbearFanOutGap=false
bullFanOutGap:=false
bearFanOutGap:=false
forlookback=0tofanoutLookback-1
bullFanOutGap:=(entryFastEma[lookback]-fanOutGap)>entrySlowEma[lookback]
ifbullFanOutGap==false
break
forlookback=0tofanoutLookback-1
bearFanOutGap:=(entryFastEma[lookback]+fanOutGap)<entrySlowEma[lookback]
ifbearFanOutGap==false
break

//ThiswillensureagivenfannoutgapexistsbetweenEACHEMAline,ratherthanjustcheckingbetweenFastandSlow
//LeavingithereincaseIdecidetogobacktoit,ormakeitconfigurablebetweenthetwo
//forlookback=0to3-1
//bullFanOutGap:=(entryFastEma[lookback]-fanOutGap)>entryMedEma[lookback]and(entryMedEma[lookback]-fanOutGap)>entrySlowEma[lookback]
//ifbullFanOutGap==false
//break
//forlookback=0to3-1
//bearFanOutGap:=(entryFastEma[lookback]+fanOutGap)<entryMedEma[lookback]and(entryMedEma[lookback]+fanOutGap)<entrySlowEma[lookback]
//ifbearFanOutGap==false
//break
//Condition5:PreviouscandlemustnothavetouchedanyentryEMAlines
bullBreakout=low[1]>entryFastEma[1]
bearBreakout=high[1]<entryFastEma[1]
//Condition6:CurrentcandlemusthavetouchedtheFastEMA
bullPullback=low<entryFastEma
bearPullback=high>entryFastEma
//Combineallentryconditions
goLong=inDateRangeandbullTrendDirandbullTrendPriceandbullEmaOrderandbullFanOutGapandbullBreakoutandbullPullback
goShort=inDateRangeandbearTrendDirandbearTrendPriceandbearEmaOrderandbearFanOutGapandbearBreakoutandbearPullback
//Tradeentryandexitvariables
vartradeEntryBar=bar_index
varprofitPoints=0.
varlossPoints=0.
varslPrice=0.
varslAmount=0.
varslPercent=0.
vartpPrice=0.
vartpPercent=0.
varinLong=false
varinShort=false
varfloatentryPrice=na
vartradeCancelled=false
vartradeActive=false
//Entrydecisions
openLong=(goLongandnotinLong)
openShort=(goShortandnotinShort)
flippingSides=(goLongandinShort)or(goShortandinLong)
enteringTrade=openLongoropenShort
inTrade=inLongorinShort
//Exitcalculations
//Condition7:Pricewhichmustbebrokentoentertrade
priceBuffer=ta.atr(14)*priceBufferAtrMult
localHigh=ta.highest(high,localHighLookback)
localLow=ta.lowest(low,localHighLookback)
ifenteringTrade
entryPrice:=goLong?localHigh+priceBuffer:goShort?localLow-priceBuffer:na
slPrice:=openLong?low-priceBuffer:openShort?high+priceBuffer:na
slAmount:=math.abs(entryPrice-slPrice)
slPercent:=math.abs((1-(entryPrice-slAmount)/entryPrice)*100)
tpPercent:=slPercent*riskReward
//Riskcalculations
riskAmt=strategy.equity*accountRiskPercent/100
entryQty=math.abs(riskAmt/slPercent*100)/close
ifopenLong
ifstrategy.position_size<0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)
printTradeExitLabel(bar_index+1,math.max(tpPrice,slPrice),strategy.position_size,strategy.position_avg_price,strategy.openprofit)
strategy.entry("Long",strategy.long,stop=entryPrice,qty=entryQty,alert_message="LongEntry")
enteringTrade:=true
inLong:=true
inShort:=false
printVerticalLine(color.new(color.green,60))
ifopenShort
ifstrategy.position_size>0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)
printTradeExitLabel(bar_index+1,math.max(tpPrice,slPrice),strategy.position_size,strategy.position_avg_price,strategy.openprofit)
strategy.entry("Short",strategy.short,stop=entryPrice,qty=entryQty,alert_message="ShortEntry")
enteringTrade:=true
inShort:=true
inLong:=false
printVerticalLine(color.new(color.red,60))
//Checkiftradeisactiveornot
longActive=strategy.position_size[1]>0
shortActive=strategy.position_size[1]<0
activeTrade=longActiveorshortActive
//IfpriceclosesbeyondtheSlowEMA,thencancelanypendingorders
ifnotactiveTradeand((inLongandclose<entrySlowEma)or(inShortandclose>entrySlowEma))
printVerticalLine(color.new(color.silver,60))
inLong:=false
inShort:=false
strategy.cancel_all()
tradeCancelled:=true

ifenteringTrade
profitPoints:=percentAsPoints(tpPercent)
lossPoints:=percentAsPoints(slPercent)
tpPrice:=calcProfitTrgtPrice(profitPoints,entryPrice,openLong)
tradeEntryBar:=bar_index
strategy.exit("TP/SL",profit=profitPoints,loss=lossPoints,comment_profit="TPHit",comment_loss="SLHit",alert_profit="TPHitAlert",alert_loss="SLHitAlert")
//=============================================================================
//DRAWINGS
//=============================================================================
//-----------
//TP/SLBoxes
//-----------
exitedOnCurrentBar=strategy.closedtrades.entry_bar_index(strategy.closedtrades-1)==bar_index
slHit=((shortActiveorexitedOnCurrentBar)andhigh>=slPrice)or((longActiveorexitedOnCurrentBar)andlow<=slPrice)
tpHit=((longActiveorexitedOnCurrentBar)andhigh>=tpPrice)or((shortActiveorexitedOnCurrentBar)andlow<=tpPrice)
exitTriggered=slHitortpHit
pnl=strategy.closedtrades.profit(strategy.closedtrades-1)
posSize=strategy.closedtrades.size(strategy.closedtrades-1)
//Printboxesfortradesclosedatprofitorloss
if(inTradeandexitTriggeredandnottradeCancelledorexitedOnCurrentBar)
inShort:=false
inLong:=false
printTpSlHitBox(tradeEntryBar,bar_index,slHit,tpHit,entryPrice,slPrice,tpPrice)
printTradeExitLabel(bar_index,math.max(tpPrice,slPrice),posSize,entryPrice,pnl)
//PrintTP/SLboxforcurrentopentrade
elseifbarstate.islastconfirmedhistoryandstrategy.position_size!=0
printTpSlNotHitBox(tradeEntryBar+1,bar_index+1,strategy.position_avg_price,slPrice,tpPrice)
//Tradecancelledbeforeentry
elseiftradeCancelled
tradeCancelled:=false
printTpSlNotHitBox(tradeEntryBar,bar_index,entryPrice,slPrice,tpPrice)
printTradeExitLabel(bar_index+1,math.max(tpPrice,slPrice),strategy.position_size,strategy.position_avg_price,strategy.openprofit)

//=============================================================================
//DEBUGGING
//=============================================================================
//Datawindowplots
//Leavingalldebuggingplotsinfornowastheymaybeusefulduringfuturedevelopment/improvementsforthisstrategy
plotchar(currTrendFastEma,"currTrendFastEma","")
plotchar(currTrendSlowEma,"currTrendSlowEma","")
plotchar(fanOutGap,"fanGap","")
plotchar(bullTrendDir,"bullTrendDir","")
plotchar(bullTrendPrice,"bullTrendPrice","")
plotchar(bullEmaOrder,"bullEmaOrder","")
plotchar(bullFanOutGap,"bullFanOutGap","")
plotchar(bullBreakout,"bullBreakout","")
plotchar(bullPullback,"bullPullback","")
plotchar(goLong,"goLong","")
plotchar(inLong,"inLong","")
plotchar(bearTrendDir,"bearTrendDir","")
plotchar(bearTrendPrice,"bearTrendPrice","")
plotchar(bearEmaOrder,"bearEmaOrder","")
plotchar(bearFanOutGap,"bearFanOutGap","")
plotchar(bearBreakout,"bearBreakout","")
plotchar(bearPullback,"bearPullback","")
plotchar(goShort,"goShort","")
plotchar(inShort,"inShort","")
plotchar(openLong,"openLong","")
plotchar(openShort,"openShort","")
plotchar(enteringTrade,"enteringTrade","")
plotchar(entryPrice,"entryPrice","")
plotchar(slPrice,"slPrice","")
plotchar(tpPrice,"tpPrice","")
plotchar(tpPercent,"tpPercent","")
plotchar(slPercent,"slPercent","")
plotchar(longActive,"longActive","")
plotchar(shortActive,"shortActive","")
plotchar(exitedOnCurrentBar,"exitedOnCurrentBar","")
plotchar(strategy.position_size,"position_sizeAfter","")
plotchar(slHit,"slHit","")
plotchar(tpHit,"tpHit","")
//Labelplots
//plotDebugLabels=false
//ifplotDebugLabels
//ifbar_index==tradeEntryBar
//printLabel(bar_index,"Positionsize:"+str.tostring(entryQty*close,"#.##"))
Expand (395 lines)
