Script Name: SPY 1 Minute Day Trader
Author: fbearman2000
Description: When scalping options, users are looking for where breakouts are going to occur instead of sitting thru areas choppy price action that drain delta and cause them to lose value even if price is up trending. This script tries to identify when a trend reversal is expected based on one minute price action on the SPY. It alerts users to prepare for potential breakout...
PineScript code:

Pine Script™ strategy
SPY 1 Minute Day Trader
//@version=5
strategy(title="SPY  1  Minute  Day  Trader",  initial_capital=1800000,  default_qty_type=strategy.percent_of_equity,  default_qty_value=7,  pyramiding=0,  commission_type=strategy.commission.cash_per_order,  commission_value=2.6,  overlay=true,  calc_on_every_tick=false,  process_orders_on_close=true,  max_labels_count=500)
//This  script  has  been  created  to  take  into  account  how  the  following  variables  impact  trend  for  SPY  1  Minute
//The  SPY  stop  losses/take  profit  have  been  set  to  0.00075%  which  equates  to  10%ish  on  SPY  1  DTE  ATM  contracts
//5  ema  vs  13  ema  :  A  cross  establishes  start  of  trend
//Stoicastic  smoothed  line:  Establish  over  bought  vs  over  sold
//MACD  (Line,  Signal  &  Slope)  :  If  you  have  momentum
//ADX  :  if  you  are  trending
//RSI  :  If  the  trend  has  strength
//MACD  Difference  between  line  and  signal  line  to  wait  on  buying
//Root  Mean  Square  of  ATR  to(Average  True  Range)  Want  to  buy  during  lower  values
//When  the  bounce  up  or  bounce  down  is  detected  it  shows  yellow  tick  marks  above  and  below  the  orange  triangle
//marker  so  users  have  an  idea  where  potential  run  ends  or  to  better  understand  when  the  analytic  is  wrong.
//White  L's  indicate  that  7  of  8  conditions  are  met  due  to  impending  uptrend  w/  missing  one  in  green  below  it
//Yellow  L's  indicate  that  8  of  8  conditions  still  are  met
//White  S's  indicate  that  7  of  8  conditions  are  met  due  to  impending  downtrend  w/  missing  condition  in  red  above  it
//Yellow  S's  indicate  that  8  of  8  conditions  still  are  met
//Logic  is  available  for  trades  to  repeat  before  re-opening  but  has  been  disabled,  since  noisy  trades  have  been  removed.
//Won't  close  position  until  either  it  gets  stopped  based  on  0.00075  *  stock  price  or  higher  degree  trend
//changes  (as  long  as  trending)  or  loses  trend  as  determined  by  ADX.
//Won't  open  any  trades  on  last  two  minutes  of  day  and  won't  trade  during  first  5  minutes  of  day
//Will  close  any  open  trades  going  into  10AM  and  4PM
//For  4  option  contracts  set  account  to  $1,800,000  with  7%  trade  and  option  cost  of  $2.60  for  each  trade
//Forgot  to  remove  lines  and  indicators
//  Initialize  variables
var  float  long_entry_price  =  na
var  float  short_entry_price  =  na
var  float  stop_loss  =  na
var  float  take_profit  =  na
var  float  twoxtake_profit  =  na
var  float  threextake_profit  =  na
var  float  short_stop_loss  =  na
var  float  short_take_profit  =  na
var  float  twoxshort_take_profit  =  na
var  float  threexshort_take_profit  =  na
//var  float  option_SL_P  =  0.00075//approx  10%  on  SPY  1  DTE
//var  float  option_TP_P  =  0.00075//approx  10%  on  SPY  1  DTE
var  long_entry_time  =  0
var  long_entry_minute  =  0
var  short_entry_time  =  0
var  short_entry_minute  =  0
var  allow_long_entry  =  true
var  allow_short_entry  =  true
var  allow_trades  =  true
var  hourlyclose  =  0
var  notify  =  0
var  shortnotify  =  0
var  adxinput  =  18
var  entry  =  0
var  tooltipnote  =  "Emtpy"
var  signal  =  "Empty"
var  show  =  0
float  upperBandValue  =  na
float  lowerBandValue  =  na
//  Trade  pin  bars  reversals
shortpinbars  =  input.bool(true,  "Trade  3x  tail  to  body  short  pin  bar  reversals")
longpinbars  =  input.bool(true,  "Trade  3x  tail  to  body  long  pin  bar  reversals")
//  Show  1  missing  parameter  by  default
D1  =  input.bool(false,  "Show  missing  parameters  for  all  time  /  Unchecked  (default)  will  allow  descriptive  tooltip  for  last  500  entries")
//  Disable  trading  during  tough  times  by  default
notrade  =  input.bool(true,  "Trade  from  10:30  until  Noon  EST")
notradelunch  =  input.bool(true,  "Trade  during  lunchtime  from  noon  until  1  EST")
notrade1to3  =  input.bool(true,  "Trade  from  1  until  3  EST")
notradePH  =  input.bool(true,  "Trade  during  Power  Hour  3  until  4  EST")
//  Calculate  VWAP  and  upper  and  lower  bands
vwapmid  =  request.security(syminfo.tickerid,  "1",  ta.vwap(hlc3))
vwap_array  =  array.new_float()
array.push(vwap_array,  vwapmid)
array.push(vwap_array,  vwapmid  +  1)
array.push(vwap_array,  vwapmid  -  1)
std_dev  =  array.stdev(vwap_array)
upperBandValue  :=  vwapmid  +  std_dev  *  2
lowerBandValue  :=  vwapmid  -  std_dev  *  2
plot(vwapmid,  title="VWAP",  color=color.aqua,  linewidth  =  2)
plot(upperBandValue,  title="Upper  VWAP",  color=color.aqua,  linewidth  =  1)
plot(lowerBandValue,  title="Lower  VWAP",  color=color.aqua,  linewidth  =  1)
//  Calculate  the  EMAs  &  SMAs
ema5  =  ta.ema(close,  5)
ema13  =  ta.ema(close,  13)
sma20  =  ta.sma(close,  20)
//  Input  Stop  Losses  and  Take  Profits
option_SL_P  =  input.float(0.00075,  title  =  "Stop  Loss  Percentage  in  Decimal  Form")  //approx  10%  on  SPY  1  DTE
option_TP_P  =  input.float(0.00075,  title  =  "Take  Profit  Percentage  in  Decimal  Form")  //approx  10%  on  SPY  1  DTE
//From  Date
TSTAMP  =  input.time(title="From  this  date.  To  see  entire  backtest  range  set  to  a  year  ago.",  defval=timestamp("2022-05-12T09:30:00"))
//  Input  parameters
fastLength  =  input.int(12,  minval=1,  title="MACD  Fast  Length")
slowLength  =  input.int(26,  minval=1,  title="MACD  Slow  Length")
signalLength  =  input.int(9,  minval=1,  title="MACD  Signal  Smoothing")
//  Inputs
length  =  input.int(14,  "Stochastic  Length")
smoothK  =  input.int(3,  "Stoicastic  Smooth  K")
src  =  input(close,  "Stoicastic  Source")
//Stochastic  Calculation
highestHigh  =  ta.highest(src,  length)
lowestLow  =  ta.lowest(src,  length)
k  =  100  *  ((src  -  lowestLow)  /  (highestHigh  -  lowestLow))
d  =  ta.sma(k,  smoothK)
//  Calculate  the  RSI
rsiValue  =  ta.rsi(close,  5)
//  Calculate  the  signal  line  as  the  SMA  of  the  RSI  for  5  minute  over  9  periods
rsiSignal  =  ta.sma(rsiValue,  9)
//  Calculate  MACD
[macdLine,  signalLine,  _]  =  ta.macd(close,  fastLength,  slowLength,  signalLength)
//  Calculate  slope  of  MACD  line
macdSlope=(macdLine-macdLine[3])/(bar_index-bar_index[3])
//LengthoftheATR
atr_length=input.int(14,title="ATRLength",minval=1)
//CalculatetheTrueRange
tr=ta.tr(true)
//CalculatetheATR
atr=ta.atr(atr_length)
//SquaretheATRvalues
atr_squared=math.pow(atr,2)
//CalculatethemeanofthesquaredATRvaluesoverawindowof20bars
mean_atr_squared=ta.sma(atr_squared,20)
//TakethesquarerootofthemeantogettheRMS
rms_atr=math.sqrt(mean_atr_squared)
//LengthoftheADX
len=input.int(14,title="ADXLength",minval=1)
//Setminimumnumberofbarsbetweentrades
min_bars_between_trades=12
//CalculatetheDirectionalMovement
up=ta.change(high)
down=-ta.change(low)
plusDM=na(up)?na:(up>downandup>0?up:0)
minusDM=na(down)?na:(down>upanddown>0?down:0)
//CalculatetheSmoothedDirectionalMovement
plusDI=100*ta.ema(plusDM,len)/ta.ema(tr,len)
minusDI=100*ta.ema(minusDM,len)/ta.ema(tr,len)
//CalculatetheDirectionalIndex(DX)
DX=100*math.abs(plusDI-minusDI)/(plusDI+minusDI)
//CalculatetheADX
adx=ta.ema(DX,len)
//Calculate5-minuteclosepriceona1-minutechart
src_5m=request.security(syminfo.tickerid,"5",close)//,lookahead=barmerge.lookahead_on)
ema_5m_20=ta.ema(src_5m,20)
ema_5m=ta.ema(src_5m,13)
ema_5m_5=ta.ema(src_5m,5)
plot(ema_5m,"5Min13EMA",color=color.orange,linewidth=2)
plot(ema_5m_5,"5Min5EMA",color=color.blue,linewidth=2)
//Gethigh,low,andcloseprices
highPrice=high
lowPrice=low
closePrice=close
//GettheUnixtimestampofthecurrentbar
unixTimestamp=time_close
//ExtracttheminutevaluefromtheUnixtimestamp
minuteValue=minute(unixTimestamp)
//Calculatethetradingminuteoftheday
tradingMinute=(minuteValue+(hour(unixTimestamp)-9)*60)-30
//Getthelowestlowoftheday
lowOfDay=ta.lowest(low,tradingMinute)
highOfDay=ta.highest(high,tradingMinute)
//Checkifthecurrentbarisafter10:30AM
isAfter1030=request.security(syminfo.tickerid,"60",tradingMinute>=0)
//Getthehighesthighandlowestlowofthelasthour
highOfLastHour=ta.highest(high,90)
lowOfLastHour=ta.lowest(low,90)
//Plottheminutevalueandthelowofthedayonthechart
plot(lowOfDay,"LowofDay",color.fuchsia)
plot(highOfDay,"HighofDay",color.fuchsia)

//Determinebuyandsellsignals
buy_signal=(ema5>ema13andema_5m>ema_5m_5andrsiSignal<49andtradingMinute<=60andbarstate.isconfirmed)or
(notrade==1andema5>ema13andema_5m>ema_5m_5andrsiSignal<49andtradingMinute>60andtradingMinute<=150andbarstate.isconfirmed)or
(notradelunch==1andema5>ema13andema_5m>ema_5m_5andrsiSignal<49andtradingMinute>150andtradingMinute<=210andbarstate.isconfirmed)or
(notrade1to3andema5>ema13andema_5m>ema_5m_5andrsiSignal<49andtradingMinute>210andtradingMinute<=330andbarstate.isconfirmed)or
(notradePH==1andema5>ema13andema_5m>ema_5m_5andrsiSignal<49andtradingMinute>330andbarstate.isconfirmed)
short_buy_signal=(ema5<ema13andema_5m<ema_5m_5andrsiSignal>0andtradingMinute<=60andbarstate.isconfirmed)or
(notrade==1andema5<ema13andema_5m<ema_5m_5andrsiSignal>60andtradingMinute>60andtradingMinute<=150andbarstate.isconfirmed)or
(notradelunch==1andema5<ema13andema_5m<ema_5m_5andrsiSignal>60andtradingMinute>150andtradingMinute<=210andbarstate.isconfirmed)or
(notrade1to3andema5<ema13andema_5m<ema_5m_5andrsiSignal>60andtradingMinute>210andtradingMinute<=330andbarstate.isconfirmed)or
(notradePH==1andema5<ema13andema_5m<ema_5m_5andrsiSignal>65andtradingMinute>330andbarstate.isconfirmed)
//short_buy_signal=false
//Definelongentryconditions
C1=ema5>ema13?1:0//Ebelowbarwhenonlyonemissing
C2=d>=0?1:0//dSmoothedStoicasticbelowbarwhenwhenonlyonemissing
//C3=macdLine<.5?1:0//Mbelowbarwhenonlyonemissing
C4=adx>0?1:0//Abelowbarwhenonlyonemissing
C5=macdSlope>0?1:0//%belowbarwhenonlyonemissing
//C6=signalLine>-.2?1:0//S(MACDSignal)belowbarwhenonlyonemissing
//C7=rsiSignal>30?1:0//Rbelowbarwhenonlyonemissing
//C17=math.abs(macdLine-signalLine)>0.00?1:0//DMACDDifferencebelowbarwhenonlyonemissing
C18=rms_atr<0.75?1:0//TRootMeanSquareofATRbelowbarwhenonlyonemissing
C19=((ema_5m-ema_5m_5)/close>0.0005andtradingMinute<=60)or((ema_5m-ema_5m_5)/close>0.0005andtradingMinute>60andtradingMinute<=150)or(math.abs(ema_5m-ema_5m_5)/close>0.0002andtradingMinute>150andtradingMinute<=210)or((ema_5m-ema_5m_5)/close>0.0001andtradingMinute>210andtradingMinute<=330)or(math.abs(ema_5m-ema_5m_5)/close>0.0002andtradingMinute>330)?1:0//5minute5EMA/13EMAdifferencebelowbarwhenonlyonemissing
C22=close>open?1:0//Cdifferencebelowbarwhenonlyonemissing
C23=(math.abs(close-highOfDay)/close>0.0006andtradingMinute<=150)or(math.abs(close-highOfDay)/close>0.0006andtradingMinute>150andtradingMinute<=210)or(math.abs(close-highOfDay)/close>0.0002andtradingMinute>210andtradingMinute<=330)or(math.abs(close-highOfDay)/close>0.0006andtradingMinute>330)?1:0//HTooclosetoHighofDay
C25=close>=lowerBandValue?1:0//VcloseabovelowerbandofVWAPbelowbarwhenonlyonemissing
//Defineshortentryconditions
C8=ema5<ema13?1:0//Eabovebarwhenonlyonemissing
C9=d>=0?1:0//dSmoothedStoicasticabovebarwhenwhenonlyonemissing
//C10=macdLine>-0.5?1:0//Mabovebarwhenonlyonemissing
C11=adx>20?1:0//Aabovebarwhenonlyonemissing
C12=macdSlope<0?1:0//%abovebarwhenonlyonemissing
//C13=signalLine<.2?1:0//S(MACDSignal)abovebarwhenonlyonemissing
//C14=rsiSignal<70?1:0//Rabovebarwhenonlyonemissing
//C15=math.abs(macdLine-signalLine)>0.00?1:0//DMACDDifferenceabovebarwhenonlyonemising
C16=rms_atr<0.75?1:0//TRootMeanSquareofATRabovebarwhenonlyonemissing
C20=((ema_5m-ema_5m_5)/close>0.0005andtradingMinute<=60)or(math.abs(ema_5m-ema_5m_5)/close>0.0002andtradingMinute>60andtradingMinute<=150)or(math.abs(ema_5m-ema_5m_5)/close>0.0003andtradingMinute>150andtradingMinute<=210)or((ema_5m-ema_5m_5)/close>0.0003andtradingMinute>210andtradingMinute<=330)or((ema_5m-ema_5m_5)/close>0.0003andtradingMinute>330)?1:0//5minute5EMA/13EMAdifferenceabovebarwhenonlyonemissing
C21=open>close?1:0//Cdifferenceabovebarwhenonlyonemissing
C24=(math.abs(close-lowOfDay)/close>0.0006andtradingMinute<=150)or(math.abs(close-lowOfDay)/close>0.0006andtradingMinute>150andtradingMinute<=210)or(math.abs(close-lowOfDay)/close>0.0002andtradingMinute>210andtradingMinute<=330)or(math.abs(close-lowOfDay)/close>0.0006andtradingMinute>330)?1:0//LTooclosetoLowofDay
C26=close<=upperBandValue?1:0//VcloseaboveupperbandofVWAPabovebarwhenonlyonemissing
//labelsfortooltips
if(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C1)==0andbarstate.isconfirmed
tooltipnote:="1min13EMA>5EMA(decreasingtrend)"
signal:="↓"
show:=1
elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C2)==0andbarstate.isconfirmed
tooltipnote:="Stoichastic>90(overboughtmaydump)"
signal:="d"
show:=1
//elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C3)==0andbarstate.isconfirmed
//tooltipnote:="MACD>0.5(toomuchmomentumalready)"
//signal:="M\nA\nC\nD"
//show:=1
elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C4)==0andbarstate.isconfirmed
tooltipnote:="ADX<20(nottrending)"
signal:="A\nD\nX"
show:=1
elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C5)==0andbarstate.isconfirmed
tooltipnote:="MACDhasdownwardslope(losingmomentum)"
signal:="M\n/"
show:=1
elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C18)==0andbarstate.isconfirmed
tooltipnote:="ATR>0.75(increasedvolatility)"
signal:="A\nT\nR"
show:=1
elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C19)==0andbarstate.isconfirmed
tooltipnote:="5Min5/13EMAdifferencetooclose(noisytrade)"
signal:="5"
show:=1
elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C22)==0andbarstate.isconfirmed
tooltipnote:="Candleclosesbelowopen(trendreversing?)"
signal:="C"
show:=1
elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C23)==0andbarstate.isconfirmed
tooltipnote:="Tooclosetohighofday(outofrunway?)"
signal:="H"
show:=1
elseif(C1+C2+C4+C5+C18+C19+C22+C23+C25)==8and(C25)==0andbarstate.isconfirmed
tooltipnote:="BelowVWAP2standarddeviations(onarun!)"
signal:="V"
show:=1
if(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C8)==0andbarstate.isconfirmed
tooltipnote:="1min5EMA>13EMA(increasingtrend)"
signal:="↑"
show:=2
elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C9)==0andbarstate.isconfirmed
tooltipnote:="Stoichastic>0(oversoldmaycausebounce)"
signal:="d"
show:=2
//elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C10)==0andbarstate.isconfirmed
//tooltipnote:="MACD<-0.5(toolittlemomentumalready)"
//signal:="M\nA\nC\nD"
//show:=2
elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C11)==0andbarstate.isconfirmed
tooltipnote:="ADX<20(nottrending)"
signal:="A\nD\nX"
show:=2
elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C12)==0andbarstate.isconfirmed
tooltipnote:="MACDhasupwardslope(gainingmomentum)"
signal:="M\n/"
show:=2
elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C16)==0andbarstate.isconfirmed
tooltipnote:="ATR>0.75(increasedvolatility)"
signal:="A\nT\nR"
show:=2
elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C20)==0andbarstate.isconfirmed
tooltipnote:="5Min5/13EMAdifferencetooclose(noisytrade)"
signal:="5"
show:=2
elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C21)==0andbarstate.isconfirmed
tooltipnote:="Candleclosesaboveopen(trendreversing?)"
signal:="C"
show:=2
elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C24)==0andbarstate.isconfirmed
tooltipnote:="Tooclosetolowofday(outofrunway?)"
signal:="L"
show:=2
elseif(C8+C9+C11+C12+C16+C20+C21+C24+C26)==8and(C26)==0andbarstate.isconfirmed
tooltipnote:="AboveVWAP2standarddeviations(onarun!)"
signal:="V"
show:=2
ifshow==1orshow==2
show:=0
if((buy_signalandstrategy.position_size==0andallow_tradesandallow_long_entryandbarstate.isconfirmed))andtime>=TSTAMP
long_entry_price:=open
strategy.entry("PivotUp",strategy.long,alert_message="PivotingUp")
stop_loss:=long_entry_price-(option_SL_P*open)
take_profit:=long_entry_price+(option_TP_P*open)
twoxtake_profit:=long_entry_price+(2*option_TP_P*open)
threextake_profit:=long_entry_price+(3*option_TP_P*open)
long_entry_time:=time
long_entry_minute:=tradingMinute
allow_long_entry:=false
allow_trades:=false
notify:=1
entry:=0
if((high==open)and((close-low>=3*(open-close))andopen>=closeand(high-low)/high>=option_TP_Pandstrategy.position_size<=0andlongpinbars==1andbarstate.isconfirmed))andtime>=TSTAMP
long_entry_price:=open
strategy.entry("PivotPinBarUp",strategy.long,alert_message="PivotingPinBarUp")
stop_loss:=long_entry_price-(option_SL_P*open)
take_profit:=long_entry_price+(option_TP_P*open)
twoxtake_profit:=long_entry_price+(2*option_TP_P*open)
threextake_profit:=long_entry_price+(3*option_TP_P*open)
long_entry_time:=time
long_entry_minute:=tradingMinute
allow_long_entry:=false
allow_trades:=false
notify:=1
entry:=0
plot(notify==1?open-(option_SL_P*open):na,"StopLoss",color.yellow,style=plot.style_linebr,offset=1,linewidth=3,display=display.pane)
plot(notify==1?open+(option_TP_P*open):na,"TakeProfit",color.yellow,style=plot.style_linebr,offset=1,linewidth=3,display=display.pane)
plot(notify==1?open+2*(option_TP_P*open):na,"2xTakeProfit",color.orange,style=plot.style_linebr,offset=1,linewidth=2,display=display.pane)
ifnotify==1
notify:=notify-1
if((short_buy_signalandstrategy.position_size==0andallow_tradesandallow_short_entry))andtime>=TSTAMP
short_entry_price:=open
strategy.entry("PivotDown",strategy.short,alert_message="PivotingDown")
short_stop_loss:=short_entry_price+(option_SL_P*open)
short_take_profit:=short_entry_price-(option_TP_P*open)
twoxshort_take_profit:=short_entry_price-(2*option_TP_P*open)
threexshort_take_profit:=short_entry_price-(3*option_TP_P*open)
short_entry_time:=time
short_entry_minute:=tradingMinute
allow_short_entry:=false
allow_trades:=false
shortnotify:=1
entry:=0
if((close==low)and(high-close>=3*(close-open))andopen<=closeand(high-low)/high>=option_TP_Pandstrategy.position_size>=0andshortpinbars==1andbarstate.isconfirmed)andtime>=TSTAMP
short_entry_price:=open
strategy.entry("PivotPinBarDown",strategy.short,alert_message="PivotingPinBarDown")
short_stop_loss:=short_entry_price+(option_SL_P*open)
short_take_profit:=short_entry_price-(option_TP_P*open)
twoxshort_take_profit:=short_entry_price-(2*option_TP_P*open)
threexshort_take_profit:=short_entry_price-(3*option_TP_P*open)
short_entry_time:=time
short_entry_minute:=tradingMinute
allow_short_entry:=false
allow_trades:=false
shortnotify:=1
entry:=0
plot(shortnotify==1?open+(option_SL_P*open):na,"StopLoss",color.yellow,style=plot.style_linebr,offset=1,linewidth=3,display=display.pane)
plot(shortnotify==1?open-(option_TP_P*open):na,"TakeProfit",color.yellow,style=plot.style_linebr,offset=1,linewidth=3,display=display.pane)
plot(shortnotify==1?open-2*(option_TP_P*open):na,"2xTakeProfit",color.orange,style=plot.style_linebr,offset=1,linewidth=2,display=display.pane)
ifshortnotify==1andbarstate.isconfirmed
shortnotify:=shortnotify-1
ifstrategy.position_size>0andbarstate.isconfirmed
ifclose<stop_lossandbarstate.isconfirmed
strategy.close("PivotUp","ExitLongsStopped",alert_message="ExitLongsStopped")
strategy.close("PivotPinBarUp","ExitLongsStopped",alert_message="ExitLongsStopped")
elseifclose>=twoxtake_profitand(adx<=25orclose<close[3])andbarstate.isconfirmed
ifentry==1andbarstate.isconfirmed
take_profit:=threextake_profit
ifentry==0andbarstate.isconfirmed
entry:=1
stop_loss:=take_profit
strategy.exit("ExitLongs","PivotUp",stop=stop_loss,limit=take_profit,alert_message="ExitLongs")
strategy.exit("ExitLongs","PivotPinBarUp",stop=stop_loss,limit=take_profit,alert_message="ExitLongs")
elseifsrc_5m<ema_5mandtradingMinute-long_entry_minute>3and(adx<=25orclose<close[3])andbarstate.isconfirmed
strategy.exit("ExitLongs5MinEMACross","PivotUp",stop=stop_loss,limit=take_profit,alert_message="ExitLongs5MinEMACross")
strategy.exit("ExitLongs5MinEMACross","PivotPinBarUp",stop=stop_loss,limit=take_profit,alert_message="ExitLongs5MinEMACross")
elseifstrategy.position_size<0andbarstate.isconfirmed
ifclose>short_stop_lossandbarstate.isconfirmed
strategy.close("PivotDown","ExitShortsStopped",alert_message="ExitShortsStopped")
strategy.close("PivotPinBarDown","ExitShortsStopped",alert_message="ExitShortsStopped")
elseifclose<=twoxshort_take_profitand(adx<=25orclose>close[3])andbarstate.isconfirmed
ifentry==1andbarstate.isconfirmed
take_profit:=threexshort_take_profit
ifentry==0andbarstate.isconfirmed
entry:=1
stop_loss:=short_take_profit
strategy.exit("ExitShorts","PivotDown",stop=short_stop_loss,limit=short_take_profit,alert_message="ExitShorts")
strategy.exit("ExitShorts","PivotPinBarDown",stop=short_stop_loss,limit=short_take_profit,alert_message="ExitShorts")
elseifsrc_5m>ema_5mandtradingMinute-short_entry_minute>3and(adx<=25orclose>close[3])andbarstate.isconfirmed
strategy.exit("ExitShorts5MinEMACross","PivotDown",stop=short_stop_loss,limit=short_take_profit,alert_message="ExitShorts5MinEMACross")
strategy.exit("ExitShorts5MinEMACross","PivotPinBarDown",stop=short_stop_loss,limit=short_take_profit,alert_message="ExitShorts5MinEMACross")
//Resetallow_tradesaftercool-downperiodofmin_bars_between_tradesbarssetabove
iftime>long_entry_time+(time-time[1])*min_bars_between_tradesandbarstate.isconfirmed
allow_long_entry:=true
allow_trades:=true
iftime>short_entry_time+(time-time[1])*min_bars_between_tradesandbarstate.isconfirmed
allow_short_entry:=true
allow_trades:=true
ifhour==15andminute>=55andbarstate.isconfirmed//Lastfiveminutesoftradingday
allow_trades:=false
ifhour==9andminute<=35andbarstate.isconfirmed//Firstfiveminutesoftradingday
allow_trades:=false
//Closeallpositionsattheendoftradingday
if((hour==15andminute==57))andstrategy.position_size!=0andbarstate.isconfirmed
strategy.close("PivotUp",alert_message="MarketClosing")
strategy.close("PivotDown",alert_message="MarketClosing")
strategy.close("PivotPinBarUp",alert_message="MarketClosing")
strategy.close("PivotPinBarDown",alert_message="MarketClosing")
hourlyclose:=1
//plotshape(hourlyclose==1?1:na,"SuggestedVolatileHourClose",text="Closepositionspriortoclose",offset=1,style=shape.triangledown,location=location.abovebar,size=size.tiny,textcolor=color.orange,color=color.orange,display=display.pane)
ifhourlyclose==1andbarstate.isconfirmed
hourlyclose:=0
Expand (461 lines)
