Script Name: SSL Strategy + EMA 200 AND Stop Loss
Author: LittleSneaky
Description: If you want to see the funcionality of this strategy on detail, please go to:
"Estrategia De Scalping Para Criptomonedas Con SSL y Média Móvil Probada 100 Veces" on Youtube

Note: This strategy can be perfectly improved
         To see the Stop loss levels, increase the thickness of plot number one
PineScript code:

Pine Script™ strategy
SSL Strategy + EMA 200 AND Stop Loss
//@version=5
//@Isaac
//Estrategia  vista  en  ▼▼
//YT:  Trading  Zone
strategy('SSL  Strategy  +  EMA  200  AND  Stop  Loss',  overlay=true)
ema  =  ta.ema(close,  200)
stop_loss  =  input.float(2.00,  title='Stop  Loss',  step=0.10)
period  =  input(title='Period',  defval=10)
len  =  input(title='Period',  defval=10)
smaHigh  =  ta.sma(high,  len)
smaLow  =  ta.sma(low,  len)
Hlv  =  int(na)
Hlv  :=  close  >  smaHigh  ?  1  :  close  <  smaLow  ?  -1  :  Hlv[1]
sslDown  =  Hlv  <  0  ?  smaHigh  :  smaLow
sslUp  =  Hlv  <  0  ?  smaLow  :  smaHigh
cruceArriba  =  ta.crossover(sslUp,  sslDown)
cruceAbajo  =  ta.crossunder(sslUp,  sslDown)
alcista  =  (close  >  ema  )  and  (cruceArriba)
bajista  =  (close  <  ema)  and  (cruceAbajo)
var  SL  =  0.0
//Cerrar  compra  por  cruce
por_cruce  =  ta.crossunder(sslUp,  sslDown)
//Cerrar  venta  por  cruce
por_cruceAB  =  ta.crossunder(sslDown,  sslUp)
//Cerrar  compra  y  venta  por  stop  loss
Stop  =  SL
comprado  =  strategy.position_size  >  0
vendido  =  strategy.position_size  <  0
UTmpconvertL  =  strategy.position_avg_price  *  (1  +  0.1)
UTmpdefineL  =  (UTmpconvertL  >  close  and  strategy.openprofit  >  0.1)
UTSPL  =  UTmpdefineL
SPL  =  UTSPL
///////////////////////////////////////////////////////////////////////
UTmpconvertLS  =  strategy.position_avg_price*(1+0.1)
UTmpdefineLS=(UTmpconvertLS>closeandstrategy.openprofit>0.1)
UTSPLS=UTmpdefineLS
SPLS=UTSPLS
////////////////////////////////////////////////////////////////////////
ifnotcompradoandnotvendidoandalcista
cantidad=(strategy.equity/close)
strategy.entry('Compra',strategy.long,qty=cantidad,comment="Long")
SL:=sslDown
ifcompradoandnotvendidoandpor_cruceandSPL
strategy.close("Compra",comment="ExitLong")
SL:=0

ifcompradoandnotvendidoandStop
strategy.exit('Compra',stop=Stop,comment="SL")
SL:=0
///////////////////////////////////////////////////////////////////
ifnotcompradoandnotvendidoandbajista
cantidad=(strategy.equity/close)
strategy.entry('Venta',strategy.short,qty=cantidad,comment="Short")
SL:=sslDown
ifnotcompradoandvendidoandpor_cruceABandSPLS
strategy.close("Venta",comment="ExitShort")
SL:=0

ifnotcompradoandvendidoandStop
strategy.exit('Venta',stop=Stop,comment="SLS")
SL:=0
plot(Stop>0?Stop:na,style=plot.style_circles,color=color.new(color.yellow,0))
plot(ema)
plot(sslDown,linewidth=2,color=color.new(color.red,0))
plot(sslUp,linewidth=2,color=color.new(color.lime,0))
Expand (93 lines)
