Script Name: Strategy Template - V2
Author: Trendoscope
Description: This is an educational script created to demonstrate few basic building blocks of a trend based strategy and how to achieve different entry and exit types. My initial intention was to create a comprehensive strategy template which covers all the aspects of strategy. But, ended up creating fully fledged strategy based on trend following.

This is an enhancement on ...
PineScript code:

Pine Script™ strategy
Strategy Template - V2
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  HeWhoMustNotBeNamed
//      __        __                        __              __    __                                    __              __                                                __            __        __                            __            _______                          __        __                                                                                    __
//    /    |    /    |                    /    |    _    /    |/    |                                /    \          /    |                                            /    |        /    \    /    |                        /    |        /              \                      /    \    /    |                                                                                /    |
//    $$  |    $$  |    ______    $$  |  /  \  $$  |$$  |____        ______    $$    \      /$$  |  __        __      _______    _$$  |_      $$    \  $$  |    ______      _$$  |_      $$$$$$$    |    ______    $$    \  $$  |    ______      _____    ____        ______        ____$$  |
//    $$  |__$$  |  /            \  $$  |/$    \$$  |$$            \    /            \  $$$    \  /$$$  |/    |    /    |  /              |/  $$      |    $$$    \$$  |  /            \  /  $$      |    $$  |__$$  |  /            \  $$$    \$$  |  /            \  /          \/        \    /            \    /        $$  |
//    $$        $$  |/$$$$$$    |$$  /$$$    $$  |$$$$$$$    |/$$$$$$    |$$$$    /$$$$  |$$  |    $$  |/$$$$$$$/  $$$$$$/      $$$$    $$  |/$$$$$$    |$$$$$$/      $$        $$<  /$$$$$$    |$$$$    $$  |  $$$$$$    |$$$$$$  $$$$    |/$$$$$$    |/$$$$$$$  |
//    $$$$$$$$  |$$        $$  |$$  $$/$$  $$  |$$  |    $$  |$$  |    $$  |$$  $$  $$/$$  |$$  |    $$  |$$            \      $$  |  __  $$  $$  $$  |$$  |    $$  |    $$  |  __  $$$$$$$    |$$        $$  |$$  $$  $$  |  /        $$  |$$  |  $$  |  $$  |$$        $$  |$$  |    $$  |
//    $$  |    $$  |$$$$$$$$/  $$$$/    $$$$  |$$  |    $$  |$$  \__$$  |$$  |$$$/  $$  |$$  \__$$  |  $$$$$$    |    $$  |/    |$$  |$$$$  |$$  \__$$  |    $$  |/    |$$  |__$$  |$$$$$$$$/  $$  |$$$$  |/$$$$$$$  |$$  |  $$  |  $$  |$$$$$$$$/  $$  \__$$  |
//    $$  |    $$  |$$              |$$$/        $$$  |$$  |    $$  |$$        $$/  $$  |  $/    $$  |$$        $$/  /          $$/      $$    $$/  $$  |  $$$  |$$        $$/      $$    $$/  $$        $$/  $$              |$$  |  $$$  |$$        $$  |$$  |  $$  |  $$  |$$              |$$        $$  |
//    $$/      $$/    $$$$$$$/  $$/            $$/  $$/      $$/    $$$$$$/    $$/            $$/    $$$$$$/    $$$$$$$/          $$$$/    $$/      $$/    $$$$$$/          $$$$/    $$$$$$$/      $$$$$$$/  $$/      $$/    $$$$$$$/  $$/    $$/    $$/    $$$$$$$/    $$$$$$$/
//
//
//
//@version=5
//###########################################  Strategydefinition######################################################/
strategy('StrategyTemplate-V2',overlay=true,initial_capital=20000,default_qty_type=strategy.percent_of_equity,
default_qty_value=100,commission_type=strategy.commission.percent,pyramiding=1,commission_value=0.11,
max_lines_count=500,max_labels_count=500,max_boxes_count=500)
//###########################################Entryandexitparameters######################################################/
i_entryType=input.string('Stop',title='EntryType',options=['Market','Stop','Limit','Stop-Limit'],group='EntryParameters')
i_dcLength=input.int(40,step=10,title='DonchianLength',group='EntryParameters')
i_htfResolution=input.timeframe('W',title='HigherTimeframe',group='EntryParameters')
i_stopType=input.string('Stop',title='StopType',options=['Market','Stop'],group='ExitParameters')
i_takeProfit=input.bool(false,title='TakeInitialProfit',group='ExitParameters')
i_takeProfitRR=input.float(10,step=0.5,title='Risk/Reward(TakeProfit)',group='ExitParameters')
i_takeProfitQty=input.int(30,step=5,minval=5,maxval=100,title='TakeProfitPercent',group='ExitParameters')
i_atrMaType=input.string('sma',title='ATRMAType(Stop-Limit)',options=['sma','ema','hma','rma','vwma','wma'],group='ExitParameters')
i_atrLength=input.int(22,title='ATRLength(Stop-Limit',step=5,group='ExitParameters')
i_atrMultStop=input.float(0.5,step=0.5,title='ATRMultiplier(Stop-Limit)',group='ExitParameters')
//############################################GenericStrategyParameters###################################################/
i_tradeDirection=input.string(title='TradeDirection',defval=strategy.direction.all,options=[strategy.direction.all,strategy.direction.long,strategy.direction.short],group='TradeFilters')
strategy.risk.allow_entry_in(i_tradeDirection)
i_startTime=input.time(defval=timestamp('01Jan201000:00+0000'),title='StartTime',group='TradeFilters')
i_endTime=input.time(defval=timestamp('01Jan209900:00+0000'),title='EndTime',group='TradeFilters')
inDateRange=time>=i_startTimeandtime<=i_endTime
//##################################################GenericMethods#########################################################/
f_secureSecurity(_symbol,_res,_src,_offset)=>
request.security(_symbol,_res,_src[_offset],lookahead=barmerge.lookahead_on)
f_getMovingAverage(source,MAType,MALength)=>
ma=ta.sma(source,MALength)
ifMAType=='ema'
ma:=ta.ema(source,MALength)
ma
ifMAType=='hma'
ma:=ta.hma(source,MALength)
ma
ifMAType=='rma'
ma:=ta.rma(source,MALength)
ma
ifMAType=='vwma'
ma:=ta.vwma(source,MALength)
ma
ifMAType=='wma'
ma:=ta.wma(source,MALength)
ma
ma
f_getCustomAtr(MAType,MALength)=>
f_getMovingAverage(ta.tr,MAType,MALength)
f_get_donchian(dcLength,resolution)=>
top=resolution==''?ta.highest(dcLength):f_secureSecurity(syminfo.tickerid,resolution,ta.highest(dcLength),1)
bottom=resolution==''?ta.lowest(dcLength):f_secureSecurity(syminfo.tickerid,resolution,ta.lowest(dcLength),1)
mid=(top+bottom)/2
[mid,top,bottom]
//######################################################Calculationandplot##########################################################/
[mid,top,bottom]=f_get_donchian(i_dcLength,'')
[hmid,htop,hbottom]=f_get_donchian(i_dcLength,i_htfResolution)
atrStop=f_getCustomAtr(i_atrMaType,i_atrLength)*i_atrMultStop
p_top=plot(top,'TOP',color=color.new(color.lime,80))
p_bottom=plot(bottom,'BOTTOM',color=color.new(color.orange,80))
p_mid=plot(mid,'MID',color=color.new(color.blue,80))
fill(p_top,p_mid,title='Upper',color=color.new(color.lime,80))
fill(p_bottom,p_mid,title='Lower',color=color.new(color.orange,80))
p_htop=plot(htop,'HTOP',color=color.new(color.green,80))
p_hbottom=plot(hbottom,'HBOTTOM',color=color.new(color.red,80))
p_hmid=plot(hmid,'HMID',color=color.new(color.purple,80))
fill(p_htop,p_hmid,title='HTFUpper',color=color.new(color.green,80))
fill(p_hbottom,p_hmid,title='HTFLower',color=color.new(color.red,80))
//###########################################Tradeconditionsandlevels################################################/
longBias=bottom>hmidandinDateRange
shortBias=top<hmidandinDateRange
closeBuyCondition=strategy.position_size>0
closeSellCondition=strategy.position_size<0
//Marketorderconditions
buyMarketCondition=ta.crossover(high,top[1])andi_entryType=='Market'
sellMarketCondition=ta.crossunder(low,bottom[1])andi_entryType=='Market'
closeBuyMarketCondition=ta.crossunder(low,bottom[1])andi_stopType=='Market'andnotlongBias
closeSellMarketCondition=ta.crossover(high,top[1])andi_stopType=='Market'andnotshortBias
//Stoporderconditions
buySellStopCondition=i_entryType=='Stop'
closeBuySellStopCondition=i_stopType=='Stop'
//Limitandstoplimitconditions
buyLimitCondition=i_entryType=='Limit'andhigh>mid
sellLimitCondition=i_entryType=='Limit'andlow<mid
buyStopLimitCondition=i_entryType=='Stop-Limit'andta.crossover(high,top[1])
sellStopLimitCondition=i_entryType=='Stop-Limit'andta.crossunder(low,bottom[1])
//EntrylevelsforlongandshortordersviaStop,LimitandStop-Limit
buyLevel=top
sellLevel=bottom
buyStopLimit=top+atrStop
sellStopLimit=bottom-atrStop
//Exitlevelsforlongandshort-tobeusedinStoporders
closeBuyStop=bottom
closeSellStop=top
//Takeprofitconditionsandlevelsforlongandshort-tobeusedinTakeProfitexitorders
takeProfitBuyCondition=longBiasandstrategy.position_size>0andi_takeProfit
takeProfitSellCondition=shortBiasandstrategy.position_size<0andi_takeProfit
profitLong=top+i_takeProfitRR*(top-bottom)
profitShort=bottom-i_takeProfitRR*(top-bottom)
profitLong:=strategy.position_size<=0?profitLong:high[1]>profitLong[1]?profitLong[1]+i_takeProfitRR*(top-bottom):profitLong[1]
profitShort:=strategy.position_size>=0?profitShort:low[1]<profitShort[1]?profitShort[1]-i_takeProfitRR*(top-bottom):profitShort[1]
//###########################################TradeStatementsUsingIf-Blocks################################################/
//EntryforLongOrders
iflongBias
//Cancelshortpendingordersandcloseexistingshorttrades
strategy.cancel('Short')
strategy.close('Short')
//Longentrybasedonentrytype-market,stop,limitorstop-limit
ifbuyMarketCondition
strategy.entry('Long',strategy.long,comment='Long-Market-Order')
ifbuySellStopCondition
strategy.entry('Long',strategy.long,stop=buyLevel,oca_name='oca_buy',oca_type=strategy.oca.cancel,comment='Long-Stop-Order')
ifbuyLimitCondition
strategy.entry('Long',strategy.long,limit=buyLevel,oca_name='oca_buy',oca_type=strategy.oca.cancel,comment='Long-Limit-Order')
ifbuyStopLimitCondition
strategy.entry('Long',strategy.long,limit=buyStopLimit,stop=buyLevel,oca_name='oca_buy',oca_type=strategy.oca.cancel,comment='Long-Stop-Limit-Order')
//EntryforShortOrders
ifshortBias
//Cancellongpendingordersandcloseexistinglongtrades
strategy.cancel('Long')
strategy.close('Long')
//Shortentrybasedonentrytype-market,stop,limitorstop-limit
ifsellMarketCondition
strategy.entry('Short',strategy.short,comment='Short-Market-Order')
ifbuySellStopCondition
strategy.entry('Short',strategy.short,stop=sellLevel,oca_name='oca_sell',oca_type=strategy.oca.cancel,comment='Short-Stop-Order')
ifsellLimitCondition
strategy.entry('Short',strategy.short,limit=sellLevel,oca_name='oca_sell',oca_type=strategy.oca.cancel,comment='Short-Limit-Order')
ifsellStopLimitCondition
strategy.entry('Short',strategy.short,limit=sellStopLimit,stop=sellLevel,oca_name='oca_sell',oca_type=strategy.oca.cancel,comment='Short-Stop-Limit-Order')
//ExitLongordermarketcondition
ifcloseBuyConditionandcloseBuyMarketCondition
strategy.close('Long',comment='Close-Long-Market')
//ExitShortorderbymarketcondition
ifcloseSellConditionandcloseSellMarketCondition
strategy.close('Short',comment='Close-Short-Market')
//Exitbystoploss-Setstoplossbeforehand
ifcloseBuySellStopCondition
ifcloseBuyCondition
strategy.exit('StopLong','Long',stop=closeBuyStop,comment='Close-Buy-Stop')
ifcloseSellCondition
strategy.exit('StopShort','Short',stop=closeSellStop,comment='Close-Sell-Stop')
//TakeProfitforLongOrder
iftakeProfitBuyCondition
strategy.exit('ProfitLong','Long',limit=profitLong,qty_percent=i_takeProfitQty,comment='Close-Buy-Profit')
//TakeProfitforShortOrder
iftakeProfitSellCondition
strategy.exit('ProfitShort','Short',limit=profitShort,qty_percent=i_takeProfitQty,comment='Close-Sell-Profit')
//###########################################TradeStatementsUsingWhen-Alternativemethod################################################/
////Cancenpendingorderswhenmarketchangesitsbias
//strategy.cancel("Long",when=shortBias)
//strategy.cancel("Short",when=longBias)
////Closeexistingtradeswhenmarketchangesitsbias
//strategy.close("Long",when=shortBias)
//strategy.close("Short",when=longBias)
////MarketorderswhenEntryType=Market
//strategy.entry("Long",strategy.long,when=longBiasandbuyMarketCondition,comment="Long-Market-Order")
//strategy.entry("Short",strategy.short,when=shortBiasandsellMarketCondition,comment="Short-Market-Order")
////StoporderswhenEntryType=Stop(Buyathigherpriceandsellatlowerprice)-suitablefortrendfollowingmethods
//strategy.entry("Long",strategy.long,when=longBiasandbuySellStopCondition,stop=buyLevel,
//oca_name="oca_buy",oca_type=strategy.oca.cancel,comment="Long-Stop-Order")
//strategy.entry("Short",strategy.short,when=shortBiasandbuySellStopCondition,stop=sellLevel,
//oca_name="oca_sell",oca_type=strategy.oca.cancel,comment="Short-Stop-Order")
////LimitorderswhenEntryType=Limit
//strategy.entry("Long",strategy.long,when=longBiasandbuyLimitCondition,limit=buyLevel,
//oca_name="oca_buy",oca_type=strategy.oca.cancel,comment="Long-Limit-Order")
//strategy.entry("Short",strategy.short,when=shortBiasandsellLimitCondition,stop=sellLevel,
//oca_name="oca_sell",oca_type=strategy.oca.cancel,comment="Short-Limit-Order")
////Stop-limitorderswhenEntryType=Stop-Limit(Buyathigherpriceandsellatlowerpricebutwithprotection)-suitablefortrendfollowingmethods
//strategy.entry("Long",strategy.long,when=longBiasandbuyStopLimitCondition,limit=buyStopLimit,stop=buyLevel,
//oca_name="oca_buy",oca_type=strategy.oca.cancel,comment="Long-Stop-Limit-Order")
//strategy.entry("Short",strategy.short,when=shortBiasandsellStopLimitCondition,limit=sellStopLimit,stop=sellLevel,
//oca_name="oca_sell",oca_type=strategy.oca.cancel,comment="Short-Stop-Limit-Order")
////Stoploss-Exitbymarket
//strategy.close("Long",when=closeBuyConditionandcloseBuyMarketCondition,comment="Close-Long-Market")
//strategy.close("Short",when=closeSellConditionandcloseSellMarketCondition,comment="Close-Short-Market")
////Stoploss-Exitbystop
//strategy.exit("StopLong","Long",stop=closeBuyStop,when=closeBuyConditionandcloseBuySellStopCondition,comment="Close-Buy-Stop")
//strategy.exit("StopShort","Short",stop=closeSellStop,when=closeSellConditionandcloseBuySellStopCondition,comment="Close-Sell-Stop")
////TakeProfit
//strategy.exit("ProfitLong","Long",limit=profitLong,when=takeProfitBuyCondition,qty_percent=i_takeProfitQty,comment="Close-Buy-Profit")
//strategy.exit("ProfitShort","Short",limit=profitShort,when=takeProfitSellCondition,qty_percent=i_takeProfitQty,comment="Close-Sell-Profit")
Expand (224 lines)
