Script Name: SuperTrend Multi Time Frame Long and Short Trading Strategy
Author: ranga_technologies
Description: Hello All

This is non-repainting Supertrend  Multi Time Frame  script,  I got so many request on Supertrend with Multi Time Frame. This is for all of them ..I am making it open for all so you can change its coding according to your need.

 How the Basic Indicator works

SuperTrend is one of the most common ATR based trailing stop indicators.

In this version...
PineScript code:

Pine Script™ strategy
SuperTrend Multi Time Frame Long and Short Trading Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  ranga_trading
//@version=5
strategy(title='SuperTrend  Multi  Time  Frame  Long  and  Short  Trading  Strategy  with  Take  Profit,  Stop  Loss  and  in  build  alerts  V01',  shorttitle='SuperTrend  Multi  Time  Frame  Long  and  Short  Trading  Strategy  with  Take  Profit,  Stop  Loss  and  in  build  alerts  V01  ',  overlay=true,  default_qty_value=60,  initial_capital=2000,  default_qty_type=strategy.percent_of_equity,  pyramiding=0,  process_orders_on_close=true)
tf1  =  input.timeframe('D',  title='Timeframe  1')
tf2  =  input.timeframe('W',  title='Timeframe  2')
length  =  input(title='ATR  Period',  defval=22)
mult  =  input.float(title='ATR  Multiplier',  step=0.1,  defval=3.0)
showLabels  =  input(title='Show  Buy/Sell  Labels  ?',  defval=true)
useClose  =  input(title='Use  Close  Price  for  Extremums  ?',  defval=true)
highlightState  =  input(title='Highlight  State  ?',  defval=true)
atr=mult*ta.atr(length)
longStop=(useClose?ta.highest(close,length):ta.highest(length))-atr
longStopPrev=nz(longStop[1],longStop)
longStop:=close[1]>longStopPrev?math.max(longStop,longStopPrev):longStop
shortStop=(useClose?ta.lowest(close,length):ta.lowest(length))+atr
shortStopPrev=nz(shortStop[1],shortStop)
shortStop:=close[1]<shortStopPrev?math.min(shortStop,shortStopPrev):shortStop
varintdir=1
dir:=close>shortStopPrev?1:close<longStopPrev?-1:dir
varcolorlongColor=color.green
varcolorshortColor=color.red
longStopPlot=plot(dir==1?longStop:na,title='LongStop',style=plot.style_linebr,linewidth=2,color=color.new(longColor,0))
buySignal=dir==1anddir[1]==-1
plotshape(buySignal?longStop:na,title='LongStopStart',location=location.absolute,style=shape.circle,size=size.tiny,color=color.new(longColor,0))
shortStopPlot=plot(dir==1?na:shortStop,title='ShortStop',style=plot.style_linebr,linewidth=2,color=color.new(shortColor,0))
sellSignal=dir==-1anddir[1]==1
plotshape(sellSignal?shortStop:na,title='ShortStopStart',location=location.absolute,style=shape.circle,size=size.tiny,color=color.new(shortColor,0))
midPricePlot=plot(ohlc4,title='',style=plot.style_circles,linewidth=0,display=display.none,editable=false)
longFillColor=highlightState?dir==1?longColor:na:na
shortFillColor=highlightState?dir==-1?shortColor:na:na
fill(midPricePlot,longStopPlot,title='LongStateFilling',color=longFillColor,transp=90)
fill(midPricePlot,shortStopPlot,title='ShortStateFilling',color=shortFillColor,transp=90)
//CEFunction
ce()=>
atr2=mult*ta.atr(length)
longStop2=(useClose?ta.highest(close,length):ta.highest(length))-atr2
longStop2Prev=nz(longStop2[1],longStop2)
longStop2:=close[1]>longStop2Prev?math.max(longStop2,longStop2Prev):longStop2
shortStop2=(useClose?ta.lowest(close,length):ta.lowest(length))+atr2
shortStop2Prev=nz(shortStop2[1],shortStop2)
shortStop2:=close[1]<shortStop2Prev?math.min(shortStop2,shortStop2Prev):shortStop2
varintdir2=1
dir2:=close>shortStop2Prev?1:close<longStop2Prev?-1:dir2
ce=dir2==1?longStop2:shortStop2
[dir2,ce]
[side,ce_plot]=ce()
ce1_plot=request.security(syminfo.tickerid,tf1,ce_plot[1],barmerge.gaps_off,barmerge.lookahead_on)
ce2_plot=request.security(syminfo.tickerid,tf2,ce_plot[1],barmerge.gaps_off,barmerge.lookahead_on)
ce1=request.security(syminfo.tickerid,tf1,side[1],barmerge.gaps_off,barmerge.lookahead_on)
ce2=request.security(syminfo.tickerid,tf2,side[1],barmerge.gaps_off,barmerge.lookahead_on)
long=buySignalandce1>0andce2>0
short=sellSignalandce1<0andce2<0
tradeType=input.string('BOTH',title='Whattradesshouldbetaken:',options=['LONG','SHORT','BOTH'])
//PositionManagementTools
pos=0.0
iftradeType=='BOTH'
pos:=long?1:short?-1:pos[1]
pos
iftradeType=='LONG'
pos:=long?1:pos[1]
pos
iftradeType=='SHORT'
pos:=short?-1:pos[1]
pos
longCond=longand(pos[1]!=1orna(pos[1]))
shortCond=shortand(pos[1]!=-1orna(pos[1]))
plot(ce1_plot,title='Timeframe1CE',color=ce1>0?#008000:#800000,linewidth=2)
plot(ce2_plot,title='Timeframe2CE',color=ce2>0?color.green:color.red,linewidth=2)
//EXITFUNCTIONS//
i_sl=input.float(5.0,title='StopLoss%',minval=0,group='Trades')
sl=i_sl>0?i_sl/100:99999
long_entry=ta.valuewhen(longCond,close,0)
short_entry=ta.valuewhen(shortCond,close,0)
//SimpleStopLoss+2TakeProfits
sl_long=strategy.position_avg_price*(1-sl)
sl_short=strategy.position_avg_price*(1+sl)
//PositionAdjustment
long_sl=low<sl_longandpos[1]==1
short_sl=high>sl_shortandpos[1]==-1
iflong_slorshort_sl
pos:=0
pos
long_exit=sellSignalandpos[1]==1
short_exit=buySignalandpos[1]==-1
iflong_exitorshort_exit
pos:=0
pos
tp1percent=input.int(5,title='TP1%',group='Trades')/100.0
tp2percent=input.int(10,title='TP2%',group='Trades')/100.0
tp3percent=input.int(15,title='TP3%',group='Trades')/100.0
tp1amt=input.int(10,title='TP1Amount%',group='Trades')
tp2amt=input.int(15,title='TP2Amount%',group='Trades')
tp3amt=input.int(20,title='TP3Amount%',group='Trades')
//StrategyBacktestLimitingAlgorithm
i_startTime=input.time(defval=timestamp('01Jun202113:30+0000'),title='BacktestingStartTime')
i_endTime=input.time(defval=timestamp('30Sep209919:30+0000'),title='BacktestingEndTime')
timeCond=time>i_startTimeandtime<i_endTime
KeepLastPosition=input(false)
//Makesurewearewithinthebarrange,Setupentriesandexitconditions
strategy.entry('long',strategy.long,when=longCond==trueandtradeType!='SHORT'andtimeCond)
strategy.entry('short',strategy.short,when=shortCond==trueandtradeType!='LONG'andtimeCond)
varfloatQty1=na
varfloatQty2=na
varfloatQty3=na
varfloatQty4=na
ifstrategy.position_size==0
equity_q=(strategy.initial_capital+strategy.netprofit)/close
Qty1:=equity_q*tp1amt/100.0
Qty2:=equity_q*tp2amt/100.0
Qty3:=equity_q*tp3amt/100.0
Qty4:=equity_q-Qty1-Qty2-Qty3
Qty4
strategy.exit('Exit1',qty=Qty1,stop=sl_long,limit=strategy.position_avg_price*(1+tp1percent),when=strategy.position_size>0)
strategy.exit('Exit2',qty=Qty2,stop=sl_long,limit=strategy.position_avg_price*(1+tp2percent),when=strategy.position_size>0)
strategy.exit('Exit3',qty=Qty3,stop=sl_long,limit=strategy.position_avg_price*(1+tp3percent),when=strategy.position_size>0)
strategy.exit('Exit4',qty=Qty4,stop=sl_long,when=strategy.position_size>0andKeepLastPosition==false)
strategy.close('long',when=long_exit,comment='CEExit')
strategy.exit('Exit1',qty=Qty1,stop=sl_short,limit=strategy.position_avg_price*(1-tp1percent),when=strategy.position_size<0)
strategy.exit('Exit2',qty=Qty2,stop=sl_short,limit=strategy.position_avg_price*(1-tp2percent),when=strategy.position_size<0)
strategy.exit('Exit3',qty=Qty3,stop=sl_short,limit=strategy.position_avg_price*(1-tp3percent),when=strategy.position_size<0)
strategy.exit('Exit4',qty=Qty4,stop=sl_short,when=strategy.position_size<0andKeepLastPosition==false)
strategy.close('short',when=short_exit,comment='CEExit')
plot(strategy.position_size>0?strategy.position_avg_price*(1+tp1percent):na,color=color.new(color.green,0),style=plot.style_linebr)
plot(strategy.position_size>0?strategy.position_avg_price*(1+tp2percent):na,color=color.new(color.green,0),style=plot.style_linebr)
plot(strategy.position_size>0?strategy.position_avg_price*(1+tp3percent):na,color=color.new(color.green,0),style=plot.style_linebr)
plot(strategy.position_size>0?sl_long:na,color=color.new(color.red,0),style=plot.style_linebr)
plot(strategy.position_size>0?strategy.position_avg_price:na,color=color.new(color.gray,0),style=plot.style_linebr)
plot(strategy.position_size<0?strategy.position_avg_price*(1-tp1percent):na,color=color.new(color.green,0),style=plot.style_linebr)
plot(strategy.position_size<0?strategy.position_avg_price*(1-tp2percent):na,color=color.new(color.green,0),style=plot.style_linebr)
plot(strategy.position_size<0?strategy.position_avg_price*(1-tp3percent):na,color=color.new(color.green,0),style=plot.style_linebr)
plot(strategy.position_size<0?sl_short:na,color=color.new(color.red,0),style=plot.style_linebr)
plot(strategy.position_size<0?strategy.position_avg_price:na,color=color.new(color.gray,0),style=plot.style_linebr)
Expand (189 lines)
