Script Name: SUPPORT RESISTANCE STRATEGY [5MIN TF]
Author: The_Bull_Chartist
Description: A SUPPORT RESISTANCE BREAKOUT STRATEGY for  5 minute Time-Frame  , that has the time condition for Indian Markets
The  Timing can be changed  to fit other markets,  scroll down  to "TIME CONDITION" to know more.
The commission is also included in the strategy .

The basic idea is when ,

1) Price crosses above  Resistance  Level ,indicated by Red Line, is a Long...
PineScript code:

Pine Script™ strategy
SUPPORT RESISTANCE STRATEGY [5MIN TF]
//      ____________                                _________                                            _____________
//    |____________|                          ||________|                                            ||__________|
//              ||                        ____        ||                ||                                          ||                                        ______  ________        _____  ________
//              ||        |      ||  ||              ||________||  |      ||  ||        ||          ||          |      ||      /\\      |      //  |______|  ||  ||        |______|
//              ||        |===||  |===          ||__________  |      ||  ||        ||          ||          |===||    /__\\    |===            ||        ||      \\          ||
//              ||        |      ||  ||___        ||                ||  |___||  ||___  ||___    ||          |      ||  /        \\  |      \\        ||        ||  ___||        ||
//              ||                                        ||________||                                          ||__________
//              ||                                        ||________|                                            ||__________|

//@version=5
strategy("SUPPORT  RESISTANCE  STRATEGY  [5MIN  TF]",overlay=true  ,commission_type  =  strategy.cash,  commission_value  =  30  ,  slippage  =  2,  default_qty_value  =  40,  currency  =  currency.NONE,  pyramiding  =  0)
L_Bars  =  input.int(defval  =  10,  minval  =  1  ,  maxval  =  50,  step  =1)
R_Bars  =  input.int(defval  =  15,  minval  =  1  ,  maxval  =  50,  step  =1)
volumeRange  =  input.int(20,  title='Volume  Break  [threshold]',  minval  =  1)
//  ═══════════════════════════  //
//  ——————————>  INPUT  <———————  //
//  ═══════════════════════════  //
EMA1  =  input.int(title='PRICE  CROSS  EMA',  defval  =  150,  minval  =  10  ,maxval  =  400)
factor1  =  input.float(title='_ATR  LONG',defval  =  3.2  ,  minval  =  1  ,  maxval  =  5  ,  step  =  0.1,  tooltip  =  "ATR  TRAIL  LONG")
factor2  =  input.float(title='_ATR  SHORT',defval  =  3.2  ,  minval  =  1  ,  maxval  =  5  ,  step  =  0.1,  tooltip  =  "ATR  TRAIL  SHORT")
risk  =  input.float(title='RISK',defval  =  200  ,  minval  =  1  ,  maxval  =  5000  ,  step  =  50,  tooltip  =  "RISK  PER  TRADE")
var  initialCapital  =  strategy.equity
t  =  time(timeframe.period,  '0915-1445:1234567')
time_cond  =  not  na(t)
//  ══════════════════════════════════  //
//  ———————————>  EMA  DATA  <———————————  //
//  ══════════════════════════════════  //
ema1  =  ta.ema(close,  EMA1)
plot(ema1,  color=color.new(color.yellow,  0),  style=plot.style_linebr,  title='ema1')
//  ══════════════════════════════════  //
//  ————————>  TRAIL  DATA  <————————————  //
//  ══════════════════════════════════  //
//  *******Calculate  LONG  TRAIL  data*****
ATR_LO  =  ta.atr(14)*factor1
//  *******Calculate  SHORT  TRAIL  data*****
ATR_SH  =  ta.atr(14)*factor2
long_trail  =  close  -  ATR_LO
short_trail  =  close  +  ATR_SH
//  Plot  atr  data
//plot(longStop,  color=color.new(color.green,  0),  style=plot.style_linebr,  title='Long  Trailing  Stop')
//plot(shortStop  ,  color=color.new(color.red,  0),  style=plot.style_linebr,  title='Short  Trailing  Stop')
//  ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════  //
//  ————————————————————————————————————————————————————————>  RESISTANCE/SUPPORT  LEVELS  DATA  <—————————————————————————————————————————————————————————————————————————————————————————————  //
//  ══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════  //
Resistance_pi  =  fixnan(ta.pivothigh(L_Bars,  R_Bars)[1])
Support_pi  =  fixnan(ta.pivotlow(L_Bars,  R_Bars)[1])
r1  =  plot(Resistance_pi,  color=ta.change(Resistance_pi)  ?  na  :  color.red,    offset=-(R_Bars  +  1),linewidth=2,  title='RESISTANCE')
s1  =  plot(Support_pi,  color=ta.change(Support_pi)  ?  na  :  color.green,  offset=-(R_Bars  +  1),linewidth=2,  title='SUPPORT')
//Volume
vol_1  =  ta.ema(volume,  5)
vol_2  =  ta.ema(volume,  10)
osc_vol  =  100  *  (vol_1  -  vol_2)  /  vol_2
//  ══════════════════════════════════//
//  ————————>  LONG  POSITIONS  <————————//
//  ══════════════════════════════════//
//******barinstate.isconfirmed  used  to  avoid  repaint  in  real  time*******
if  (  ta.crossover(close,  Resistance_pi)  and  osc_vol>volumeRangeandnot(open-low>close-open)andstrategy.opentrades==0andbarstate.isconfirmedandtime_condandclose>=ema1)
strategy.entry(id="Long",direction=strategy.long,comment="BUY")

plot(long_trail,color=color.new(color.blue,0),style=plot.style_linebr,title='longStop')
ifstrategy.position_size>0
strategy.exit("longtsl","Long",stop=long_trail,comment='SELL')

//═════════════════════════════════════//
//————————>SHORTPOSITIONS<—————————//
//═════════════════════════════════════//
if(ta.crossunder(close,Support_pi)andosc_vol>volumeRangeandnot(open-close<high-open)andstrategy.opentrades==0andbarstate.isconfirmedandtime_condandclose<=ema1)
strategy.entry(id="Short",direction=strategy.short,comment="SELL")
ifstrategy.position_size<0
strategy.exit("shorttsl","Short",stop=short_trail,comment='BUY')
//════════════════════════════════════════════════//
//————————>CLOSEALLPOSITIONSBY3PM<—————————//
//════════════════════════════════════════════════//
strategy.close_all(when=hour==14andminute==55)
//════════════════════════════════════════//
//————————>MAXINTRADAYLOSS<—————————//
//════════════════════════════════════════//
strategy.risk.max_intraday_loss(type=strategy.cash,value=risk)
Expand (99 lines)
