Script Name: Take Profit On Trend v2 (by BHD_Trade_Bot)
Author: BHD_Trade_Bot
Description: The purpose of strategy is to detect  long-term uptrend  and  short-term downtrend  so that you can easy to take profit.

The strategy also using  BHD unit  to detect how big you win and lose, so that you can use this strategy for all coins without worry about it have different percentage of price change.


 ENTRY

The buy order is placed on assets that have...
PineScript code:

Pine Script™ strategy
Take Profit On Trend v2 (by BHD_Trade_Bot)
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  BHD_Trade_Bot
//  @version=5
strategy(
  shorttitle                        =  'Take  Profit  On  Trend',
  title                                  =  'Take  Profit  On  Trend  (by  BHD_Trade_Bot)',
  overlay                              =  true,
  calc_on_every_tick        =  true,
  calc_on_order_fills      =  true,
  use_bar_magnifier          =  true,
  initial_capital              =  1000,
  default_qty_type            =  strategy.percent_of_equity,
  default_qty_value          =  100,
  commission_type              =  strategy.commission.percent,
  commission_value            =  0.1)
//  Backtest  Time  Period
start_year      =  input(title='Start  year'      ,defval=2021)
start_month    =  input(title='Start  month'  ,defval=1)
start_day=input(title='Startday',defval=1)
start_time=timestamp(start_year,start_month,start_day,00,00)
end_year=input(title='endyear',defval=2050)
end_month=input(title='endmonth',defval=1)
end_day=input(title='endday',defval=1)
end_time=timestamp(end_year,end_month,end_day,23,59)
is_back_test_time()=>time>=start_timeandtime<=end_time?true:false
//EMA
ema50=ta.ema(close,50)
ema200=ta.ema(close,200)
//RSI
rsi200=ta.rsi(close,200)
//EMA_CD
emacd=ema50-ema200
emacd_signal=ta.ema(emacd,50)
hist=emacd-emacd_signal
//BHDUnit
bhd_unit=ta.rma(high-low,200)*2
bhd_upper=ema200+bhd_unit
bhd_lower=ema200-bhd_unit
//Allncandlesisgoingdown
all_body_decrease(n)=>
isValid=true
fori=0to(n-1)
if(close[i]>close[i+1])
isValid:=false
break
isValid
//ENTRYCONDITIONS
//Long-termuptrend
entry_condition1=rsi200>51andhist>0
//Short-termdowntrend
entry_condition2=all_body_decrease(2)
ENTRY_CONDITIONS=entry_condition1andentry_condition2
ifENTRY_CONDITIONSandis_back_test_time()
strategy.entry('entry',strategy.long)
//CLOSECONDITIONS
//Priceincrease2BHDunit
take_profit=close>strategy.position_avg_price+bhd_unit*2
//Pricedecrease3BHDunit
stop_loss=close<strategy.position_avg_price-bhd_unit*3
CLOSE_CONDITIONS=take_profitorstop_loss
ifCLOSE_CONDITIONS
strategy.close('entry')
//Draw
plot(ema50,color=color.orange,linewidth=2)
plot(ema200,color=color.purple,linewidth=2)
bhd_upper_line=plot(bhd_upper,color=color.teal)
bhd_lower_line=plot(bhd_lower,color=color.teal)
fill(bhd_upper_line,bhd_lower_line,color=color.new(color.teal,90))
Expand (100 lines)
