Script Name: Technicals Rating Strategy v420
Author: SeaSide420
Description: Ichimoku, HMA, RSI, Stoch, CCI, MACD, Technicals Rating Strategy is a trading Bot that looks at these chosen indicators and assigns a value to each, then calculates the result of adding each indicators result value to a overall rating, which is then compared to a user set level. Here seen on Bitcoin, it has the broker fee included in the testing result. If you...
PineScript code:

Pine Script™ strategy
Technicals Rating Strategy v420
//@version=4
strategy(title="Ichi  HMA  RSI  Stoch  CCI  MACD  Technicals  Rating  Strategy",shorttitle="TRSv420",overlay=true,default_qty_type=strategy.percent_of_equity,default_qty_value=50,commission_type=strategy.commission.percent,commission_value=0.05)
res  =  input("",  title="Indicator  Timeframe",  type=input.resolution)
Period  =  input(defval  =  14,  title  =  "Period  Length",  minval  =  2)
MinSignalStrength=  input(title="Minimum  Signal  Strength",  type=input.float,  defval=1.1,  minval=0.00,  maxval=2.00,  step=0.1)
Price  =  input(defval=open,  title="Price  Source",  type=input.source)
Use_Only_Buy=  input(false,  title  =  "Use  ONLY  BUY  mode",type=input.bool)
Use_Only_Sell=  input(false,  title  =  "Use  ONLY  SELL  mode",type=input.bool)
Use_ATR_SL_TP=  input(true,  title  =  "Use  ATR  for  TP  &  SL",type=input.bool)
Use_Ichimoku=  input(true,  title  =  "Use  Ichimoku",type=input.bool)
Use_HMA=  input(true,  title  =  "Use  Hull  MA",type=input.bool)
Use_RSI=  input(true,  title  =  "Use  RSI",type=input.bool)
Use_Stoch=  input(true,  title  =  "Use  Stoch",type=input.bool)
Use_CCI=  input(true,  title  =  "Use  CCI",type=input.bool)
Use_MACD=  input(true,  title  =  "Use  MacD",type=input.bool)
//  Ichimoku  Cloud
donchian(len)  =>  avg(lowest(len),  highest(len))
ichimoku_cloud()  =>
        conversionLine  =  donchian(9)
        baseLine  =  donchian(26)
        leadLine1  =  avg(conversionLine,  baseLine)
        leadLine2  =  donchian(52)
        [conversionLine,  baseLine,  leadLine1,  leadLine2]
[IC_CLine,  IC_BLine,  IC_Lead1,  IC_Lead2]  =  ichimoku_cloud()
calcRatingMA(ma,  src)  =>na(ma)orna(src)?na:(ma==src?0:(ma<src?1:-1))
calcRating(buy,sell)=>buy?1:(sell?-1:0)
calcRatingAll()=>
//==============HMA=================
HMA10=hma(Price,Period)
HMA20=hma(Price,20)
HMA30=hma(Price,30)
HMA50=hma(Price,50)
HMA100=hma(Price,100)
HMA200=hma(Price,200)
//RelativeStrengthIndex,RSI
RSI=rsi(Price,14)
//Stochastic
lengthStoch=14
smoothKStoch=3
smoothDStoch=3
kStoch=sma(stoch(Price,high,low,lengthStoch),smoothKStoch)
dStoch=sma(kStoch,smoothDStoch)
//CommodityChannelIndex,CCI
CCI=cci(Price,20)
//MovingAverageConvergence/Divergence,MACD
[macdMACD,signalMACD,_]=macd(Price,12,26,9)
//-------------------------------------------
PriceAvg=hma(Price,Period)
DownTrend=Price<PriceAvg
UpTrend=Price>PriceAvg
floatratingMA=0
floatratingMAC=0
if(Use_HMA)
ifnotna(HMA10)
ratingMA:=ratingMA+calcRatingMA(HMA10,Price)
ratingMAC:=ratingMAC+1
ifnotna(HMA20)
ratingMA:=ratingMA+calcRatingMA(HMA20,Price)
ratingMAC:=ratingMAC+1
ifnotna(HMA30)
ratingMA:=ratingMA+calcRatingMA(HMA30,Price)
ratingMAC:=ratingMAC+1
ifnotna(HMA50)
ratingMA:=ratingMA+calcRatingMA(HMA50,Price)
ratingMAC:=ratingMAC+1
ifnotna(HMA100)
ratingMA:=ratingMA+calcRatingMA(HMA100,Price)
ratingMAC:=ratingMAC+1
ifnotna(HMA200)
ratingMA:=ratingMA+calcRatingMA(HMA200,Price)
ratingMAC:=ratingMAC+1
if(Use_Ichimoku)
floatratingIC=na
ifnot(na(IC_Lead1)orna(IC_Lead2)orna(Price)orna(Price[1])orna(IC_BLine)orna(IC_CLine))
ratingIC:=calcRating(
IC_Lead1>IC_Lead2andPrice>IC_Lead1andPrice<IC_BLineandPrice[1]<IC_CLineandPrice>IC_CLine,
IC_Lead2>IC_Lead1andPrice<IC_Lead2andPrice>IC_BLineandPrice[1]>IC_CLineandPrice<IC_CLine)
ifnotna(ratingIC)
ratingMA:=ratingMA+ratingIC
ratingMAC:=ratingMAC+1
ratingMA:=ratingMAC>0?ratingMA/ratingMAC:na
floatratingOther=0
floatratingOtherC=0
if(Use_RSI)
ratingRSI=RSI
ifnot(na(ratingRSI)orna(ratingRSI[1]))
ratingOtherC:=ratingOtherC+1
ratingOther:=ratingOther+calcRating(ratingRSI<30andratingRSI[1]<ratingRSI,ratingRSI>70andratingRSI[1]>ratingRSI)
if(Use_Stoch)
ifnot(na(kStoch)orna(dStoch)orna(kStoch[1])orna(dStoch[1]))
ratingOtherC:=ratingOtherC+1
ratingOther:=ratingOther+calcRating(kStoch<20anddStoch<20andkStoch>dStochandkStoch[1]<dStoch[1],kStoch>80anddStoch>80andkStoch<dStochandkStoch[1]>dStoch[1])
if(Use_CCI)
ratingCCI=CCI
ifnot(na(ratingCCI)orna(ratingCCI[1]))
ratingOtherC:=ratingOtherC+1
ratingOther:=ratingOther+calcRating(ratingCCI<-100andratingCCI>ratingCCI[1],ratingCCI>100andratingCCI<ratingCCI[1])
if(Use_MACD)
ifnot(na(macdMACD)orna(signalMACD))
ratingOtherC:=ratingOtherC+1
ratingOther:=ratingOther+calcRating(macdMACD>signalMACD,macdMACD<signalMACD)
ratingOther:=ratingOtherC>0?ratingOther/ratingOtherC:na
floatratingTotal=0
floatratingTotalC=0
ifnotna(ratingMA)
ratingTotal:=ratingTotal+ratingMA
ratingTotalC:=ratingTotalC+1
ratingTotal:=ratingTotal+ratingOther
ratingTotalC:=ratingTotalC+1
ratingTotal:=ratingTotalC>0?ratingTotal/ratingTotalC:na
[ratingTotal,ratingOther,ratingMA,ratingOtherC,ratingMAC]
[ratingTotal,ratingOther,ratingMA,ratingOtherC,ratingMAC]=security(syminfo.tickerid,res,calcRatingAll(),lookahead=false)
tradeSignal=ratingTotal+ratingOther+ratingMA
dynSLpoints(factor)=>factor*atr(14)/syminfo.mintick
ifnot(Use_Only_Sell)
strategy.entry("long",strategy.long,when=tradeSignal>MinSignalStrength)
ifnot(Use_Only_Buy)
strategy.entry("short",strategy.short,when=tradeSignal<-MinSignalStrength)
if(Use_ATR_SL_TP)
strategy.exit("sl/tp",loss=dynSLpoints(3),trail_points=dynSLpoints(5),trail_offset=dynSLpoints(2))
Expand (120 lines)
