Script Name: test_-_down_up
Author: luboremenar
Description: Strategy for testing efficiency of strategies based on % retrace from local top based on modifiable range.
PineScript code:

Pine Script™ strategy
test_%_down_up
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  luboremenar
//@version=4
strategy("test_%_down_up",  overlay  =  false,  initial_capital  =  1000,  pyramiding  =  0,  default_qty_value  =  1000,
          default_qty_type  =  strategy.cash,  precision  =  8,  commission_type  =  strategy.commission.percent,  commission_value  =  0.1)
//  inputs
range_of_tops  =  input(title="Range  of  candles  to  find  highest  value  from.",  defval=90,  type=input.integer,  minval=1  )
basis_points  =  input(title="Basis  points,  if  asset  has  two  decimals  use  100,  three  decimals  1000,  etc.",  defval=100,  type=input.integer,  minval=1)
retrace_percent  =  input(title="Percent  value  retrace  from  the  top.",  type=input.integer,  defval=3,  minval  =  1,  maxval=99)
take_profit_percent  =  input(title="Percent  value  of  take  profit  from  entry  price.",  type=input.integer,  defval=6,  minval=1)
//  strategy  definition
three_months_top  =  highest(range_of_tops)
longCondition1  =  (close  <=  float((three_months_top*(1-(take_profit_percent/100))))  and  strategy.position_size  ==  0)
if  (longCondition1)
        strategy.entry("Long1",  strategy.long,  qty  =  strategy.equity/close)
strategy.exit(id="TP1",  from_entry="Long1",  profit=((close*(1  +  take_profit_percent/100)-close)*basis_points),
          when=  crossover(strategy.position_size,  0))
//  plot
plot(strategy.equity)
//  for  testing,  debugging
//test=0.0
//if(crossover(strategy.position_size,  0))
//        test  :=  (close*1.06-close)*basis_points
//plot(test)
Expand (32 lines)
