Script Name: TradingView Alerts to MT4 MT5 - Forex, indices, commodities
Author: Peter_O
Description: Howdy Algo-Traders! This example script has been created for educational purposes - to present how to use and automatically execute TradingView Alerts on real markets.

I'm posting this script today for a reason. TradingView has just released a new feature of the PineScript language - ALERT() function. Why is it important? It is finally possible to set alerts...
PineScript code:

Pine Script™ strategy
TradingView Alerts to MT4 MT5 - Forex, indices, commodities
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  Peter_O
//@version=4
strategy(title="TradingView  Alerts  to  MT4  MT5  -  Forex,  indices,  commodities,  stocks,  crypto",  commission_type=strategy.commission.cash_per_contract,  commission_value=0.00003,  overlay=false,  default_qty_value=20000,  initial_capital=1000)
//
//  This  script  was  created  for  educational  purposes  only.
//  It  is  showing  how  to  use  Alerts-Straight-From-Strategies  and
//  dynamic  variables  in  TradingView  alerts.
//  And  how  to  auto-execute  them  in  Forex,  indices,  commodities  markets
//
//  (This  method  will  also  work  with  stocks  and  crypto  -  anything  your
//  broker  is  offering  via  their  MT4/MT5  platform).

TakeProfitLevel=input(400)
TakePartialProfitLevel=input(150)
//  ****  Entries  logic  ****  {
periodK  =  input(13,  title="K",minval=1)
periodD=input(3,title="D",minval=1)
smoothK=input(4,title="Smooth",minval=1)
k=sma(stoch(close,high,low,periodK),smoothK)
d=sma(k,periodD)
plot(k,title="%K",color=color.blue)
plot(d,title="%D",color=color.orange)
h0=hline(80)
h1=hline(20)
fill(h0,h1,color=color.purple,transp=75)
GoLong=crossover(k,d)andk<80andyear>2009
GoShort=crossunder(k,d)andk>20andyear>2009
AlertTest=open>closeoropen<closeoropen==close
//}Endofentrieslogic
//****Pivot-pointsandstop-losslogic****{
piv_high=pivothigh(high,1,1)
piv_low=pivotlow(low,1,1)
varfloatstoploss_long=low
varfloatstoploss_short=high
pl=valuewhen(piv_low,piv_low,0)
ph=valuewhen(piv_high,piv_high,0)
ifGoLong
stoploss_long:=low<pl?low:pl
ifGoShort
stoploss_short:=high>ph?high:ph
//}EndofPivot-pointsandstop-losslogic
//****Tradecounterandpartialclosingmechanism****{
varinttrade_id=0
ifGoLongorGoShort
trade_id:=trade_id+1
TakePartialProfitLong=barssince(GoLong)<barssince(GoShort)andcrossover(high,(valuewhen(GoLong,close,0)+TakePartialProfitLevel*syminfo.mintick))
TakePartialProfitShort=barssince(GoLong)>barssince(GoShort)andcrossunder(low,(valuewhen(GoShort,close,0)-TakePartialProfitLevel*syminfo.mintick))
//}EndofTradecounterandpartialclosingmechanism
strategy.entry("Long",strategy.long,when=GoLong)
strategy.exit("XPartLong",from_entry="Long",qty_percent=50,profit=TakePartialProfitLevel)
strategy.exit("XLong",from_entry="Long",stop=stoploss_long,profit=TakeProfitLevel)
strategy.entry("Short",strategy.short,when=GoShort)
strategy.exit("XPartShort",from_entry="Short",qty_percent=50,profit=TakePartialProfitLevel)
strategy.exit("XShort",from_entry="Short",stop=stoploss_short,profit=TakeProfitLevel)
ifGoLong
alertsyntax_golong='longslprice='+tostring(stoploss_long)+'tradeid='+tostring(trade_id)+'tp='+tostring(TakeProfitLevel)
alert(message=alertsyntax_golong,freq=alert.freq_once_per_bar_close)
ifGoShort
alertsyntax_goshort='shortslprice='+tostring(stoploss_short)+'tradeid='+tostring(trade_id)+'tp='+tostring(TakeProfitLevel)
alert(message=alertsyntax_goshort,freq=alert.freq_once_per_bar_close)
ifTakePartialProfitLong
alertsyntax_closepartlong='closeparttradeid='+tostring(trade_id)+'part=0.5'
alert(message=alertsyntax_closepartlong,freq=alert.freq_once_per_bar_close)
ifTakePartialProfitShort
alertsyntax_closepartshort='closeparttradeid='+tostring(trade_id)+'part=0.5'
alert(message=alertsyntax_closepartshort,freq=alert.freq_once_per_bar_close)
Expand (79 lines)
