Script Name: TradePro's 2 EMA + Stoch RSI + ATR Strategy
Author: PtGambler
Description: Saw TradePro's "NEW BEST HIGHEST PROFITING STRATEGY WITH CRAZY RESULTS - 2 EMA+ Stochastic RSI+ ATR", and was curious on the back testing results. This strategy is an attempt to recreate it.

This strategy uses 50 / 200 EMAs, Stochastic RSI and ATR.

Long Entry Criteria:
 - 50 EMA > 200 EMA
 - Price closes below 50 EMA
 - Stochastic RSI has gone into oversold <...
PineScript code:

Pine Script™ strategy
TradePro's 2 EMA + Stoch RSI + ATR Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  PtGambler
//@version=5
strategy("2  EMA  +  Stoch  RSI  +  ATR  [Pt]",  shorttitle  =  "2EMA+Stoch+ATR",  overlay=true,  initial_capital  =  10000,  default_qty_type  =  strategy.percent_of_equity,  default_qty_value  =  100,  calc_on_order_fills  =  false,  max_bars_back  =  500)
//  **********************************  Trade  Period  /  Strategy  Setting  **************************************
startY  =  input(title='Start  Year',  defval=2011,  group  =  "Backtesting  window")
startM  =  input.int(title='Start  Month',  defval=1,  minval=1,  maxval=12,  group  =  "Backtesting  window")
startD  =  input.int(title='Start  Day',  defval=1,  minval=1,  maxval=31,  group  =  "Backtesting  window")
finishY  =  input(title='Finish  Year',  defval=2050,  group  =  "Backtesting  window")
finishM  =  input.int(title='Finish  Month',  defval=12,  minval=1,  maxval=12,  group  =  "Backtesting  window")
finishD  =  input.int(title='Finish  Day',  defval=31,  minval=1,  maxval=31,  group  =  "Backtesting  window")
timestart  =  timestamp(startY,  startM,  startD,  00,  00)
timefinish  =  timestamp(finishY,  finishM,  finishD,  23,  59)
//  ******************************************************************************************
group_ema  =  "EMA"
group_stoch  =  "Stochastic  RSI"
group_atr  =  "ATR  Stoploss  Finder"
//  -----------------------------------------  2  EMA  -------------------------------------
ema1_len  =  input.int(50,  "EMA  Length  1",  group  =  group_ema)
ema2_len  =  input.int(200,  "EMA  Length  2",  group  =  group_ema)
ema1  =  ta.ema(close,  ema1_len)
ema2  =  ta.ema(close,  ema2_len)
plot(ema1,  "ema1",  color.white,  linewidth  =  2)
plot(ema2,  "ema2",  color.orange,  linewidth  =  2)
ema_bull  =  ema1  >  ema2
ema_bear  =  ema1  <  ema2
//  --------------------------------------  Stochastic  RSI  -----------------------------
smoothK  =  input.int(3,  "K",  minval=1,  group  =  group_stoch)
smoothD  =  input.int(3,  "D",  minval=1,  group  =  group_stoch)
lengthRSI  =  input.int(14,  "RSI  Length",  minval=1,  group  =  group_stoch)
lengthStoch  =  input.int(14,  "Stochastic  Length",  minval=1,  group  =  group_stoch)
src  =  close
rsi1  =  ta.rsi(src,lengthRSI)
k=ta.sma(ta.stoch(rsi1,rsi1,rsi1,lengthStoch),smoothK)
d=ta.sma(k,smoothD)
vartrigger_stoch_OB=k>80
vartrigger_stoch_OS=k<20
stoch_crossdown=ta.crossunder(k,d)
stoch_crossup=ta.crossover(k,d)
P_hi=ta.pivothigh(k,1,1)
P_lo=ta.pivotlow(k,1,1)
previous_high=ta.valuewhen(P_hi,k,1)
previous_low=ta.valuewhen(P_lo,k,1)
recent_high=ta.valuewhen(P_hi,k,0)
recent_low=ta.valuewhen(P_lo,k,0)
//---------------------------------------ATRstoplossfinder------------------------
length=input.int(title='Length',defval=14,minval=1,group=group_atr)
smoothing=input.string(title='Smoothing',defval='EMA',options=['RMA','SMA','EMA','WMA'],group=group_atr)
m=input.float(0.7,'Multiplier',step=0.1,group=group_atr)
src1=input(high,"Sourceforupperband",group=group_atr)
src2=input(low,"Sourceforlowerband",group=group_atr)
showatr=input.bool(true,'ShowATRBands',group=group_atr)
collong=input.color(color.purple,'LongATRSL',inline='1',group=group_atr)
colshort=input.color(color.purple,'ShortATRSL',inline='2',group=group_atr)
ma_function(source,length)=>
ifsmoothing=='RMA'
ta.rma(source,length)
else
ifsmoothing=='SMA'
ta.sma(source,length)
else
ifsmoothing=='EMA'
ta.ema(source,length)
else
ta.wma(source,length)
a=ma_function(ta.tr(true),length)*m
up=ma_function(ta.tr(true),length)*m+src1
down=src2-ma_function(ta.tr(true),length)*m
p1=plot(showatr?up:na,title='ATRShortStopLoss',color=colshort)
p2=plot(showatr?down:na,title='ATRLongStopLoss',color=collong)
//*******************************ProfitTarget/StopLoss*********************************************
RR=input.float(2.0,"RewardtoRiskratio(XtimesSL)",step=0.1,group="ProfitTarget")
breakeven=input.bool(true,"MoveSLtobreakevenwhenRRhit",group="ProfitTarget",inline='breakenven')
be_RR=input.float(1.0,"",inline='breakeven',group="ProfitTarget")
varL_PT=0.0
varS_PT=0.0
varL_SL=0.0
varS_SL=0.0
varL_be_PT=0.0
varS_be_PT=0.0
BSLE=ta.barssince(strategy.opentrades.entry_bar_index(0)==bar_index)
entry_price=strategy.position_size!=0?strategy.opentrades.entry_price(0):na
ifstrategy.position_size>0//andBSLE==1
L_PT:=L_PT[1]
L_SL:=(breakevenandhigh>=L_be_PT)?entry_price:L_SL[1]
S_PT:=close-(up-close)*RR
S_SL:=up
L_be_PT:=L_be_PT[1]
S_be_PT:=close-(up-close)*be_RR
elseifstrategy.position_size<0//andBSLE==1
S_PT:=S_PT[1]
S_SL:=(breakevenandlow<=S_be_PT)?entry_price:S_SL[1]
L_PT:=close+(close-down)*RR
L_SL:=down
S_be_PT:=S_be_PT[1]
L_be_PT:=close+(close-down)*be_RR
elseifstrategy.position_size!=0
L_PT:=L_PT[1]
S_PT:=S_PT[1]
else
L_PT:=close+(close-down)*RR
L_SL:=down
S_PT:=close-(up-close)*RR
S_SL:=up
L_be_PT:=close+(close-down)*be_RR
S_be_PT:=close-(up-close)*be_RR
entry_line=plot(entry_price,"EntryPrice",color.white,linewidth=1,style=plot.style_linebr)
L_PT_line=plot(strategy.position_size>0andBSLE>0?L_PT:na,"LPT",color.green,linewidth=2,style=plot.style_linebr)
S_PT_line=plot(strategy.position_size<0andBSLE>0?S_PT:na,"SPT",color.green,linewidth=2,style=plot.style_linebr)
L_SL_line=plot(strategy.position_size>0andBSLE>0?L_SL:na,"LSL",color.red,linewidth=2,style=plot.style_linebr)
S_SL_line=plot(strategy.position_size<0andBSLE>0?S_SL:na,"SSL",color.red,linewidth=2,style=plot.style_linebr)
L_be_PT_line=plot(strategy.position_size>0andBSLE>0?L_be_PT:na,"LBEPT",color.blue,linewidth=2,style=plot.style_linebr)
S_be_PT_line=plot(strategy.position_size<0andBSLE>0?S_be_PT:na,"SBEPT",color.blue,linewidth=2,style=plot.style_linebr)
fill(L_PT_line,entry_line,color=color.new(color.green,90))
fill(S_PT_line,entry_line,color=color.new(color.green,90))
fill(L_SL_line,entry_line,color=color.new(color.red,90))
fill(S_SL_line,entry_line,color=color.new(color.red,90))
//----------------------------------strategysetup------------------------------------------------------
varL_entry_trigger1=false
varS_entry_trigger1=false
L_entry_trigger1:=ema_bullandclose<ema1andk<20andstrategy.position_size==0
S_entry_trigger1:=ema_bearandclose>ema1andk>80andstrategy.position_size==0
L_entry1=L_entry_trigger1[1]andstoch_crossupandrecent_low>previous_low
S_entry1=S_entry_trigger1[1]andstoch_crossdownandrecent_high<previous_high
//debugging
plot(L_entry_trigger1[1]?1:0,"LEntryTrigger")
plot(stoch_crossup?1:0,"StochCrossUp")
plot(recent_low>previous_low?1:0,"Higherlow")
plot(S_entry_trigger1[1]?1:0,"SEntryTrigger")
plot(stoch_crossdown?1:0,"StochCrossdown")
plot(recent_high<previous_high?1:0,"Lowerhigh")
ifL_entry1
strategy.entry("Long",strategy.long)
ifS_entry1
strategy.entry("Short",strategy.short)
strategy.exit("ExitLong","Long",limit=L_PT,stop=L_SL,comment_profit="ExitLong,PThit",comment_loss="ExitLong,SLhit")
strategy.exit("ExitShort","Short",limit=S_PT,stop=S_SL,comment_profit="ExitShort,PThit",comment_loss="ExitShort,SLhit")
//resettingtriggers
L_entry_trigger1:=L_entry_trigger1[1]?L_entry1orema_bearorS_entry1?false:true:L_entry_trigger1
S_entry_trigger1:=S_entry_trigger1[1]?S_entry1orema_bullorL_entry1?false:true:S_entry_trigger1
//Triggerzones
bgcolor(L_entry_trigger1?color.new(color.green,90):na)
bgcolor(S_entry_trigger1?color.new(color.red,90):na)
Expand (186 lines)
