Script Name: Trend Following with Donchian Channels and MACD
Author: Robrecht99
Description: This is a trend following system based on the Donchian Channels. Instead of using a simple moving average crossover, this system uses the MACD as the trendfilter:

Long positions:
* Price makes a new 50 day high,
* The MACD-line crosses above or is above the Signal-line.
* Both the MACD and the Signal-lines are above the zero-line. 

Short positions:
* Price makes...
PineScript code:

Pine Script™ strategy
Trend Following with Donchian Channels and MACD
//ThissourcecodeissubjecttothetermsoftheMozillaPublicLicense2.0athttps://mozilla.org/MPL/2.0/
//©Robrecht99
//@version=5
strategy("TrendFollowingwithDonchianChannelsandMACD",overlay=true,margin_long=0,margin_short=0,pyramiding=1)
//DonchianChannels//
Length1=input.int(title="LengthUpperChannel",defval=50,minval=1,group="DonchianChannelsInputs")
Length2=input.int(title="LengthLowerChannel",defval=50,minval=1,group="DonchianChannelsInputs")
h1=ta.highest(high[1],Length1)
l1=ta.lowest(low[1],Length2)
fillColor=input.color(color.new(color.purple,95),title="FillColor",group="DonchianChannelsInputs")
upperColor=input.color(color.new(color.orange,0),title=" ColorUpperChannel",group="DonchianChannelsInputs",inline="upper")
lowerColor=input.color(color.new(color.orange,0),title=" ColorLowerChannel",group="DonchianChannelsInputs",inline="lower")
u=plot(h1,"Upper",color=upperColor)
l=plot(l1,"Lower",color=upperColor)
fill(u,l,color=fillColor)
//MACD//
fast_length=input(title="FastLength",defval=12)
slow_length=input(title="SlowLength",defval=26)
src=input(title="Source",defval=close)
signal_length=input.int(title="SignalSmoothing",minval=1,maxval=50,defval=9)
sma_source=input.string(title="OscillatorMAType",defval="EMA",options=["SMA","EMA"])
sma_signal=input.string(title="SignalLineMAType",defval="EMA",options=["SMA","EMA"])
fast_ma=sma_source=="SMA"?ta.sma(src,fast_length):ta.ema(src,fast_length)
slow_ma=sma_source=="SMA"?ta.sma(src,slow_length):ta.ema(src,slow_length)
macd=fast_ma-slow_ma
signal=sma_signal=="SMA"?ta.sma(macd,signal_length):ta.ema(macd,signal_length)
hist=macd-signal
//ATRandPositionSize//
leverage=input.int(title="LeverageUsed",defval=1,minval=1,group="ATRPositionSizeInputs")
pointvalue=input.int(title="PointValue/ATRMultipliersfromEntry",defval=4,minval=1,group="ATRPositionSizeInputs")
length=input.int(title="ATRPeriod",defval=14,minval=1,group="ATRPositionSizeInputs")
risk=input(title="RiskPerTrade",defval=0.01,group="ATRPositionSizeInputs")
atr=ta.atr(length)
amount=(risk*strategy.initial_capital/(pointvalue*atr*leverage))
//ATRTrailingStops//
xATRPeriod=input.int(14,"ATRPeriod",group="ATRTrailingStopInputs")
xATRMultiplier=input.float(4,"ATRMultiplier",step=.1,group="ATRTrailingStopInputs")
xATR=ta.atr(xATRPeriod)
Stop=xATRMultiplier*xATR
varxATRTrailingStop=0.0
xATRTrailingStop:=ifclose>xATRTrailingStop[1]andclose[1]>xATRTrailingStop[1]
math.max(xATRTrailingStop[1],close-Stop)
elseifclose<xATRTrailingStop[1]andclose[1]<xATRTrailingStop[1]
math.min(xATRTrailingStop[1],close+Stop)
elseifclose>xATRTrailingStop[1]
close-Stop
else
close+Stop
varPosition=0.0
Position:=ifclose[1]<xATRTrailingStop[1]andclose>xATRTrailingStop[1]
1
elseifclose[1]>xATRTrailingStop[1]andclose<xATRTrailingStop[1]
-1
else
Position[1]
PlotColor=Position==-1?color.orange:Position==1?color.orange:color.orange
plot(xATRTrailingStop,color=PlotColor,linewidth=input(2,"LineWidth",group="ATRTrailingStopInputs"),style=plot.style_circles,title="ATRTrailingStop")
//BuyandSellConditions//
entrycondition1=ta.crossover(macd,signal)
entrycondition2=macd>signal
entrycondition3=macdandsignal>0
sellcondition1=ta.crossover(signal,macd)
sellcondition2=signal>macd
sellcondition3=macdandsignal<0
//BuyandSellSignals//
if(close>h1andentrycondition2andentrycondition3)
strategy.entry("long",strategy.long,qty=amount)
stoploss=close-atr*xATRMultiplier
strategy.exit("exitsl",stop=stoploss,trail_offset=stoploss)
if(sellcondition1andsellcondition2andsellcondition3)
strategy.close(id="long")
if(close<l1andsellcondition2andsellcondition3)
strategy.entry("short",strategy.short,qty=amount)
stoploss=close+atr*xATRMultiplier
strategy.exit("exitsl",stop=stoploss,trail_offset=stoploss)
if(entrycondition1andentrycondition2andentrycondition3)
strategy.close(id="short")
Expand (93 lines)
