Script Name: Trendlines Strategy
Author: tweakerID
Description: Using the clever calculations and code by BacktestRookies, here is a strategy that buys
when the price breaks above the trend line and sells (or shorts) when it crosses below.
This logic can be reversed, which seems to work better with recent market conditions.
PineScript code:

Pine Script™ strategy
Trendlines Strategy
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  tweakerID  and  ©  BacktestRookies
//  Using  the  clever  calculations  and  code  by  BacktestRookies,  here  is  a  strategy  that  buys
//  when  the  price  breaks  above  a  trendline  and  sells  (or  shorts)  when  it  crosses  below.
//  This  logic  can  be  reversed,  which  seems  to  work  better  with  recent  market  conditions.
//  "A  general  explanation  of  the  indicator  would  be  a  good  place  to  start.  In  it,  we  plot  two
//  trend  lines  at  any  given  time.  A  resistance  trend  line  and  a  support  trend  line.  The  resistance
//  trend  is  shown  with  red  circles  and  is  created  by  joining  swing  highs  together.  The  second  is  a
//  support  trend  which  is  created  by  joining  swing  lows.
//  Since  we  need  swings  to  make  the  trend,  the  trend  line  code  contains  code  for  the  swing  detection.
//  You  can  play  around  with  the  swing  detection  to  alter  how  frequently  new  trend  lines  are  detected.
//  Relying  on  swings  also  means  that  there  will  be  some  delay  in  trend  detection  depending  on  how  you
//  configure  the  swing  detection.  The  higher  you  set  rightbars,  the  more  lag  you  will  have  before  a  trend
//  is  detected.  However,  at  the  same  time  the  quality  of  the  pivots  found  will  increase.  So  it  is  a
//  trade-off  you  need  to  come  to  terms  with  and  decide  what  the  best  settings  are  for  you."
//@version=4
strategy("Trendlines  Strategy",
          overlay=true,
          default_qty_type=strategy.percent_of_equity,
          default_qty_value=100,
          initial_capital=10000,
          commission_value=0.04,
          calc_on_every_tick=false,
          slippage=0)
direction  =  input(0,  title  =  "Strategy  Direction",  type=input.integer,  minval=-1,  maxval=1)
strategy.risk.allow_entry_in(direction  ==  0  ?  strategy.direction.all  :
  (direction  <  0  ?  strategy.direction.short  :  strategy.direction.long))
//  Bought  and  Sold  Boolean  Signal
bought  =  strategy.position_size  >  strategy.position_size[1]
  or  strategy.position_size  <  strategy.position_size[1]
///////////////////////  STRATEGY  INPUTS  ////////////////////////////////////////
title1=input(true,  "-----------------Strategy  Inputs-------------------")
leftbars  =  input(100,  minval=1,  title='Pivot  Detection:  Left  Bars')
rightbars  =  input(15,  minval=1,  title='Pivot  Detection:  Right  Bars')
plotpivots  =  input(true,  title='Plot  Pivots')
///////////////////////  BACKTESTER  /////////////////////////////////////////////
title2=input(true,  "-----------------General  Inputs-------------------")
//  Backtester  General  Inputs
i_SL=input(true,  title="Use  Stop  Loss  and  Take  Profit")
TS=input(false,  title="Use  Trailing  Stop")
i_SLType=input(defval="ATR  Stop",  title="Type  Of  Stop",  options=["Strategy  Stop",  "Swing  Lo/Hi",  "ATR  Stop"])
i_SPL=input(defval=10,  title="Swing  Point  Lookback")
i_PercIncrement=input(defval=3,  step=.1,  title="Swing  Point  SL  Perc  Increment")*0.01
i_ATR  =  input(14,  title="ATR  Length")
i_ATRMult  =  input(4,  step=.1,  title="ATR  Multiple")
i_TPRRR  =  input(2,  step=.1,  title="Take  Profit  Risk  Reward  Ratio")
DPR=input(true,  "Allow  Direct  Position  Reverse")
reverse=input(true,  "Reverse  Trades")
//  Swing  Points  Stop  and  Take  Profit
SwingStopProfit()  =>
        LL=(lowest(i_SPL))*(1-i_PercIncrement)
        HH=(highest(i_SPL))*(1+i_PercIncrement)
        LL_price  =  valuewhen(bought,  LL,  0)
        HH_price  =  valuewhen(bought,  HH,  0)
        entry_LL_price  =  strategy.position_size  >  0  ?  LL_price  :  na
        entry_HH_price  =  strategy.position_size  <  0  ?  HH_price  :  na
        tp=strategy.position_avg_price  +  (strategy.position_avg_price  -  entry_LL_price)*i_TPRRR
        stp=strategy.position_avg_price  -  (entry_HH_price  -  strategy.position_avg_price)*i_TPRRR
        [entry_LL_price,  entry_HH_price,  tp,  stp]
//  ATR  Stop
ATRStop()  =>
        ATR=atr(i_ATR)*i_ATRMult
        ATRLong  =  ohlc4  -  ATR
        ATRShort  =  ohlc4  +  ATR
        ATRLongStop  =  valuewhen(bought,  ATRLong,  0)
        ATRShortStop  =  valuewhen(bought,  ATRShort,  0)
        LongSL_ATR_price  =  strategy.position_size  >  0  ?  ATRLongStop  :  na
        ShortSL_ATR_price  =  strategy.position_size  <  0  ?  ATRShortStop  :  na
        ATRtp=strategy.position_avg_price  +  (strategy.position_avg_price  -  LongSL_ATR_price)*i_TPRRR
        ATRstp=strategy.position_avg_price  -  (ShortSL_ATR_price  -  strategy.position_avg_price)*i_TPRRR
        [LongSL_ATR_price,  ShortSL_ATR_price,  ATRtp,  ATRstp]

//  Strategy  Stop
StrategyStop(bought)  =>
        float  LongStop  =  na
        float  ShortStop  =  na
        float  StratTP  =  na
        float  StratSTP  =  na
        [LongStop,  ShortStop,  StratTP,  StratSTP]
//TrailingStop
TrailingStop(SL,SSL)  =>
        dif=(valuewhen(strategy.position_size>0  and  strategy.position_size[1]<=0,  high,0))
          -strategy.position_avg_price
        trailOffset          =  strategy.position_avg_price  -  SL
        var  tstop  =  float(na)
        if  strategy.position_size  >  0
                tstop  :=  high-  trailOffset  -  dif
                if  tstop<tstop[1]
                        tstop:=tstop[1]
        else
                tstop  :=  na
        StrailOffset          =  SSL  -  strategy.position_avg_price
        var  Ststop  =  float(na)
        Sdif=strategy.position_avg_price-(valuewhen(strategy.position_size<0
          and  strategy.position_size[1]>=0,  low,0))
        if  strategy.position_size  <  0
                Ststop  :=  low+  StrailOffset  +  Sdif
                if  Ststop>Ststop[1]
                        Ststop:=Ststop[1]
        else
                Ststop  :=  na
        [tstop,  Ststop]

//Stop  Loss  &  Take  Profit  Switches
SLTPLogic(LongStop,  ShortStop,  StratTP,StratSTP,LongSL_ATR_price,ShortSL_ATR_price,ATRtp,ATRstp,
entry_LL_price,entry_HH_price,tp,stp)=>
SL=i_SLType=="SwingLo/Hi"?entry_LL_price:i_SLType=="ATRStop"?LongSL_ATR_price:LongStop
SSL=i_SLType=="SwingLo/Hi"?entry_HH_price:i_SLType=="ATRStop"?ShortSL_ATR_price:ShortStop
TP=i_SLType=="SwingLo/Hi"?tp:i_SLType=="ATRStop"?ATRtp:StratTP
STP=i_SLType=="SwingLo/Hi"?stp:i_SLType=="ATRStop"?ATRstp:StratSTP
[SL,SSL,TP,STP]
///////////////////////STRATEGYLOGIC/////////////////////////////////////////
//Pivots
ph=pivothigh(high,leftbars,rightbars)
pl=pivotlow(low,leftbars,rightbars)
phv1=valuewhen(ph,high[rightbars],0)
phb1=valuewhen(ph,bar_index[rightbars],0)
phv2=valuewhen(ph,high[rightbars],1)
phb2=valuewhen(ph,bar_index[rightbars],1)
plv1=valuewhen(pl,low[rightbars],0)
plb1=valuewhen(pl,bar_index[rightbars],0)
plv2=valuewhen(pl,low[rightbars],1)
plb2=valuewhen(pl,bar_index[rightbars],1)

plotshape(ph,style=shape.circle,location=location.abovebar,color=color.orange,title='PivotHigh',offset=-rightbars)
plotshape(pl,style=shape.circle,location=location.belowbar,color=color.blue,title='PivotLow',offset=-rightbars)
plot(ph?high[rightbars]:na,color=color.orange,offset=-rightbars)
plot(pl?low[rightbars]:na,color=color.purple,offset=-rightbars)
//TRENDLINECODE
//--------------
get_slope(x1,x2,y1,y2)=>
m=(y2-y1)/(x2-x1)

get_y_intercept(m,x1,y1)=>
b=y1-m*x1
get_y(m,b,ts)=>
Y=m*ts+b
intres_x1=na
floatres_y1=na
intres_x2=na
floatres_y2=na
intsup_x1=na
floatsup_y1=na
intsup_x2=na
floatsup_y2=na
//Resistance
res_x1:=ph?phb1:res_x1[1]
res_y1:=ph?phv1:res_y1[1]
res_x2:=ph?phb2:res_x2[1]
res_y2:=ph?phv2:res_y2[1]
res_m=get_slope(res_x1,res_x2,res_y1,res_y2)
res_b=get_y_intercept(res_m,res_x1,res_y1)
res_y=get_y(res_m,res_b,bar_index)
//Support
sup_x1:=pl?plb1:sup_x1[1]
sup_y1:=pl?plv1:sup_y1[1]
sup_x2:=pl?plb2:sup_x2[1]
sup_y2:=pl?plv2:sup_y2[1]
sup_m=get_slope(sup_x1,sup_x2,sup_y1,sup_y2)
sup_b=get_y_intercept(sup_m,sup_x1,sup_y1)
sup_y=get_y(sup_m,sup_b,bar_index)
//plot(line.get_y2(line1))
plot(res_y,color=color.red,title='ResistanceTrendline',linewidth=2,style=plot.style_circles)
plot(sup_y,color=color.lime,title='SupportTrendline',linewidth=2,style=plot.style_circles)
ifph
line.new(phb1,phv1,bar_index,res_y,style=line.style_dashed,color=color.blue)

ifpl
line.new(plb1,plv1,bar_index,sup_y,style=line.style_dashed,color=color.blue)

//Breaks
long_break=crossover(close,res_y)
short_break=crossunder(close,sup_y)
plotshape(long_break,style=shape.triangleup,color=color.green,size=size.tiny,location=location.belowbar,title='LongBreak')
plotshape(short_break,style=shape.triangledown,color=color.red,size=size.tiny,location=location.abovebar,title='ShortBreak')
BUY=long_break
SELL=short_break
///////////////////////FUNCTIONCALLS/////////////////////////////////////////
//StopsandProfits
[entry_LL_price,entry_HH_price,tp,stp]=SwingStopProfit()
[LongSL_ATR_price,ShortSL_ATR_price,ATRtp,ATRstp]=ATRStop()
[LongStop,ShortStop,StratTP,StratSTP]=StrategyStop(bought)
[SL,SSL,TP,STP]=SLTPLogic(LongStop,ShortStop,StratTP,StratSTP,
LongSL_ATR_price,ShortSL_ATR_price,ATRtp,ATRstp,entry_LL_price,entry_HH_price,tp,stp)
[tstop,Ststop]=TrailingStop(SL,SSL)
//Entries
ifreverse
ifnotDPR
strategy.entry("long",strategy.long,when=SELLandstrategy.position_size==0)
strategy.entry("short",strategy.short,when=BUYandstrategy.position_size==0)
else
strategy.entry("long",strategy.long,when=SELL)
strategy.entry("short",strategy.short,when=BUY)
else
ifnotDPR
strategy.entry("long",strategy.long,when=BUYandstrategy.position_size==0)
strategy.entry("short",strategy.short,when=SELLandstrategy.position_size==0)
else
strategy.entry("long",strategy.long,when=BUY)
strategy.entry("short",strategy.short,when=SELL)
//Exits
ifi_SL
strategy.exit("TP&SL","long",limit=TP,stop=TS?tstop:SL)
strategy.exit("TP&SL","short",limit=STP,stop=TS?Ststop:SSL)
///////////////////////PLOTS//////////////////////////////////////////////////
plot(i_SLandstrategy.position_size>0andnotTS?SL:i_SLand
strategy.position_size>0andTS?tstop:na,title='SL',style=plot.style_cross,color=color.red)
plot(i_SLandstrategy.position_size<0andnotTS?SSL:i_SLand
strategy.position_size<0andTS?Ststop:na,title='SSL',style=plot.style_cross,color=color.red)
plot(i_SLandstrategy.position_size>0?TP:na,title='TP',style=plot.style_cross,color=color.green)
plot(i_SLandstrategy.position_size<0?STP:na,title='STP',style=plot.style_cross,color=color.green)
//Drawpriceactionsetuparrows
plotshape(BUY?1:na,style=shape.triangleup,location=location.belowbar,
color=color.green,title="BullishSetup",size=size.auto)
plotshape(SELL?1:na,style=shape.triangledown,location=location.abovebar,
color=color.red,title="BearishSetup",size=size.auto)

Expand (259 lines)
