Script Name: TRM Strategy
Author: RolandoSantos
Description: This is a strategy version of the "True Relative Movement" script:

It is virtually identical to the original script, except now you can back test different conditions and parameters.

TRM has 3 different conditions:Buy (Blue Bars), Hold/Take Profit (Gray Bars), and Sell (Pink Bars).

This script is only coded for Long only condition. It will exit the position...
PineScript code:

Pine Script™ strategy
TRM Strategy
//  "True  relative  Movement"  or  "TRM"  for  short  is  a  system  that  combines  my  two  favorite  indicators:  RSI  and  TSI.  I  strived  to  put  together  an  indicator  that  combined  the  best  of  both
//  in  order  to  help  discretionary  traders  predict  market  direction,  weakness  and  strength.  As  with  most  technical  indicators  there  are  "Buy  and  sell"  signals.  Similiar  to  Elder  Impulse  system,
///TRM  paints  bars  3  different  colors  to  display  3  different  conditions:  Blue  for  "Buy",  Pink  for  "Sell",  and  gray  for  "Take  profit/Hold".  When  the  bars  turn  blue,  that  means  all  conditions
///  have  been  met.  When  they  turn  pink,  no  conditions  have  been  met.  When  they  are  gray,  only  one  condition  has  been  met.  The  system  is  simple,  yet  effective.  A  buy  signal  is  prodcued  when
///  TSI  is  above  the  signal  line,andRSIisabove50,andviceversaforsellsignals.IhavemodifiedthedefaultparametersforTSIandRSIformore"aggressive"entriesandexits.Imaylateron
///namethiscondition"Fast-TRM"and"Slow-TRM"forwhendefaultsettingsforTSIandRSIareapplies,asthisisaveryrobustsystemaswell.
///******ES1HR,15MIN/5MINSYSTEM*****Golong,whenalltimeframeonabuysignalandviceversa.Takeprofitwhenthe5minchartflipstobuyorselldependingonwhatsideofthetradeyouareon.Closeorflip
////long/shortwhentimealltimeframesfliptoBuy/HoldifshortandSell/Holdiflong.Use20EMAforadditionalconfirmation.
//@version=4
strategy("TKP-TRMStrategy",overlay=true,shorttitle="TRMStrategy",default_qty_type=strategy.cash,default_qty_value=10000,initial_capital=10000)
Note=input(0,title="TSIstandardvaluesare25,13,13,andRSIis14.Canchangethedefaultvaluestothesefor'SlowTRM'")
long=input(title="TSI-LongLength",type=input.integer,defval=25)
short=input(title="TSI-ShortLength",type=input.integer,defval=5)
signal=input(title="TSI-SignalLength",type=input.integer,defval=14)
price=close
double_smooth(src,long,short)=>
fist_smooth=ema(src,long)
ema(fist_smooth,short)
pc=change(price)
double_smoothed_pc=double_smooth(pc,long,short)
double_smoothed_abs_pc=double_smooth(abs(pc),long,short)
tsi_value=100*(double_smoothed_pc/double_smoothed_abs_pc)
TSI_Signal_Line=(ema(tsi_value,signal))
/////////////////////////////RSI////////////////////////////////////////////////
src=close,len=input(5,minval=1,title="RSILength")
up=rma(max(change(src),0),len)
down=rma(-min(change(src),0),len)
rsi=down==0?100:up==0?0:100-(100/(1+up/down))
rsiBuyfilterlevel=input(50,minval=1,title="RSIcrossaboveBuyLevel")
rsiSellfilterlevel=input(50,minval=1,title="RSIcrossbelowSellLevel")
////////////////////////////BarColoring//////////////////////////////////////////////////////////
TRM_Buy=((tsi_value>TSI_Signal_Line)and(rsi>rsiBuyfilterlevel))
TRM_Sell=((tsi_value<TSI_Signal_Line)and(rsi<rsiSellfilterlevel))
TRM_Color=TRM_Buy?#3BB3E4:TRM_Sell?#FF006E:#b2b5be
barcolor(TRM_Color)
///Startdate
startDate=input(title="StartDate",defval=1,minval=1,maxval=31)
startMonth=input(title="StartMonth",defval=1,minval=1,maxval=12)
startYear=input(title="StartYear",defval=1970,minval=1800,maxval=2100)
//Seeifthisbar'stimehappenedon/afterstartdate
afterStartDate=(time>=timestamp(syminfo.timezone,startYear,startMonth,startDate,0,0))
///////////////////////////StrategyParamters////////////////////////////////////////
if(afterStartDateandTRM_Buy)
strategy.entry("Long",strategy.long,comment="Long")
if(afterStartDateandTRM_Sell)
strategy.close("Long",comment="Sell")
Expand (65 lines)
