Script Name: tvbot Trend Following with Mean Reversion algo
Author: tvbot-
Description: Default settings are for the ETHUSDT 5 min Binance Chart regular candles.
Back test Default settings are 10,000 usd to start, Commission 0.075%, capital deployment per position is 10%, slippage value of 1.

This algo uses the EMA to set the trend line . You are also able to turn the trend line into a range instead of just a static line. The algo uses the VWMA to...
PineScript code:

Pine Script™ strategy
tvbot Trend Following with Mean Reversion algo
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  tvbot
//@version=5
strategy("tvbot  Trend  Following  Algo",  overlay=true,  precision=2,  commission_value=0.075,  commission_type=strategy.commission.percent,  initial_capital=10000,  currency=currency.USD,  default_qty_type=strategy.percent_of_equity,  default_qty_value=10,  slippage=1,  pyramiding=0)
//////////////////////////////////////////////  USER  INPUT  ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//Code  below  this  line  is  the  start  of  the  Automated  Trading  Platform(ATP)  code.    It  sets  the  parameters  to  send  the  webhook  message  to  the  Automated  Trading  Platform(ATP)  to  execute  the  trade///
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
enableLong  =  input.bool(true,  "Enable  Long",  group  =  "Enable  /  Disable")
enableShort  =  input.bool(true,  "Enable  Short",  group  =  "Enable  /  Disable")

////////////////////  SERVER  DATA  INPUT

exchange  =  input.string(title="Exchange",  defval="Coinex",  options=["Coinex"],  group  =  "SERVER  SIDE")
ordertype  =  input.string(title="Ordertype",  defval="Market",  options=["Market",  "Limit"],  group  =  "SERVER  SIDE")

cash  =  input.float(title="Cash  per  Trade",  defval=10,  minval=-100,  group  =  "SERVER  SIDE")
leverage  =  input.int(title="Leverage",  defval=0,  minval=0,  group  =  "SERVER  SIDE")

i_time  =  input.time(defval  =  timestamp("01  Jan  2021  13:30  +0000"),  title  =  "Start  Time",    group  =  "SERVER  SIDE")
afterStartDate  =  (time  >=  i_time)

passphrase  =  input.string(title="Passphrase",  defval='',  group  =  "SERVER  SIDE")

key  =  input.string(title="key",  defval='',  group  =  "SERVER  SIDE")
secret  =  input.string(title="Secret",  defval='',  group  =  "SERVER  SIDE")

//////////////////  FILTER  SERVER  DATA

message  =  ''
var  pair  =  ""
var  ordervolume  =  0.0

if  leverage  ==  0
        pair  :=  syminfo.basecurrency  +  "/"  +  syminfo.currency

else  if  exchange  ==  "Coinex"  and  leverage  >  0
        pair  :=  syminfo.basecurrency  +  "/"  +  syminfo.currency  +  ":"  +  syminfo.currency

if  cash  >  0
        ordervolume  :=  math.round(cash  /  close,  5)
else  if  cash  <  0
        ordervolume  :=  cash

///////////////////////////////////////////////  ALERT  MESSAGE

LEmessage  =  exchange  +  "  long/buy  "  +  pair  +  "  "  +  ordertype  +  "  "  +  str.tostring(ordervolume)  +  "  "  +  str.tostring(close)  +  "  "  +  str.tostring(leverage)  +  "  "  +  passphrase  +  "  "  +  key  +  "  "  +  secret
LCmessage  =  exchange  +  "  long/sell  "  +  pair  +  "  "  +  ordertype  +  "  "  +  str.tostring(ordervolume)  +  "  "  +  str.tostring(close)  +  "  "  +  str.tostring(leverage)  +  "  "  +  passphrase  +  "  "  +  key  +  "  "  +  secret

SEmessage  =  exchange  +  "  short/buy  "  +  pair  +  "  "  +  ordertype  +  "  "  +  str.tostring(ordervolume)  +  "  "  +  str.tostring(close)  +  "  "  +  str.tostring(leverage)  +  "  "  +  passphrase  +  "  "  +  key  +  "  "  +  secret
SCmessage  =  exchange  +  "  short/sell  "  +  pair  +  "  "  +  ordertype  +  "  "  +  str.tostring(ordervolume)  +  "  "  +  str.tostring(close)  +  "  "  +  str.tostring(leverage)  +  "  "  +  passphrase  +  "  "  +  key  +  "  "  +  secret

/////////////////////////////////////////////////////////////////
//The  code  for  the  Automated  Trading  Platform(ATP)  ends  here/////
/////////////////////////////////////////////////////////////////

//  Inputs
averageData  =  input.source(close,  title="Source",  group  =  "TrendLine")
length  =  input.int(94,  minval=1,  title="Entry",  group  =  "TrendLine")
length3  =  input.int(420,  minval=1,  title="ma",  group  =  "TrendLine")

ma  =  ta.ema(averageData,  length3)  //ema  is  used  as  the  trendline
hull  =  ta.vwma(averageData,  length)  //Base  entry  parameters  use  the  vwma
//section  of  code  below  turns  the  trendline  into  a  range  instead  of  a  static  line.////////////////////////////////////
Perc  =  input.float(title="SMA  Touch  Difference  (%)",  minval=0.0,  step=0.1,  defval=0.2,  group  =  "SMA  Touch")  /  100/////
                                                                                                                                                                                                                                  /////
longExitPrice    =  ma  *  (1  +  Perc)                                                                                                                                                                  /////
shortExitPrice  =  ma  *  (1  -  Perc)                                                                                                                                                                  /////
                                                                                                                                                                                                                                  /////
plot(longExitPrice,    color  =  color.red,  display  =  display.none)                                                                                                    /////
plot(shortExitPrice,  color  =  color.red,  display  =  display.none)                                                                                                    /////
                                                                                                                                                                                                    /////
//sectionofcodeaboveturnsthetrendlineintoarangeinsteadofastaticline.////////////////////////////////////
//Codebelowthislineiswhatsetsthebaseentrycondition.Whenacandleclosesaboveorbelowthevwma,thealgorithmrecordstheclosepriceofthatcandle.
//thenitwaitsforthevwmatomeetthatclosedprice.Whenvwmaandtheclosedbeachingcandlemeetthentheconditionissatisfied.
//ifthecandlebreaksbackbeloworabovethelineitresetsthecondition.
varisbuy=true
varisfirstBuyCdnMeet=false
varlastbuyClosePrice=0.0

varisfirstSellCdnMeet=false
varlastsellClosePrice=0.0

buyhullcross=ta.crossover(close,hull)
sellhullcross=ta.crossunder(close,hull)

buycdn=isfirstBuyCdnMeetandta.crossover(hull,lastbuyClosePrice)andisbuy
sellcdn=isfirstSellCdnMeetandta.crossunder(hull,lastsellClosePrice)andnotisbuy

ifbuyhullcrossandbarstate.isconfirmed
isfirstBuyCdnMeet:=true
lastbuyClosePrice:=close
isfirstSellCdnMeet:=false

ifsellhullcrossandbarstate.isconfirmed
isfirstSellCdnMeet:=true
lastsellClosePrice:=close
isfirstBuyCdnMeet:=false

ifsellcdn
isfirstSellCdnMeet:=false
isbuy:=true

ifbuycdn
isfirstBuyCdnMeet:=false
isbuy:=false
/////endofbaseentrycondition/////////////////////////////
//thissectionofcodecheckstoseeifthetrendlinehasbeentested.Ifthetrendlinehasbeentestedthentheconditionalsocheckstoseeifyouralreadyinapositionornot
//abaseentrysignalfromthecodeaboveistriggeredwillresetthetrendlinetestcondition.
varis_sma_touch=false
is_new_pos=((strategy.position_size[1]==0)and(strategy.position_size!=0))or((strategy.position_size[1]*strategy.position_size)==-1)//Newposition:Eitherwewerenotinapositionbefore,ordirectionchanged(short->longorlong->short)
sma_touch=(high>longExitPrice)and(low<longExitPrice)or(high>shortExitPrice)and(low<shortExitPrice)or(close<longExitPrice)and(close>shortExitPrice)or(high>ma)and(low<ma)//SMAshouldbebetweenhighandlowforatouch
is_sma_touch:=is_new_pos?false:sma_touch?true:is_sma_touch//Resetflagwhenitisanewposition.Thencheckifthereisatouch,keepitsoldvalueotherwise
is_sma_touch:=(isbuyandsellcdn)?false:(notisbuyandbuycdn)?false:is_sma_touch//Resetwhenanoppositesignaltakesplace
//////////endoftrendlinetestcondition///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
////////////////////////////////////////////////////////////////////////REVERSIONINDICATOR////////////////////
length2=input.int(277,minval=1,title="Entry",group="Reversion")
length33=input.int(1100,minval=1,title="ma",group="Reversion")

hull1=ta.wma(2*ta.wma(averageData,length2/2)-ta.wma(averageData,length2),math.floor(math.sqrt(length2)))
ma1=ta.ema(averageData,length33)

///Codebelowistheentryconditionforthemeanreversiontrade,itssimilartothetrendfollowingentryconditionbutitusestheHMAinsteadoftheVWMA
varisbuy1=true
varisfirstBuyCdnMeet1=false
varlastbuyClosePrice1=0.0

varisfirstSellCdnMeet1=false
varlastsellClosePrice1=0.0

buyhullcross1=ta.crossover(close,hull1)
sellhullcross1=ta.crossunder(close,hull1)

buycdn1=isfirstBuyCdnMeet1andta.crossover(hull1,lastbuyClosePrice1)andisbuy1
sellcdn1=isfirstSellCdnMeet1andta.crossunder(hull1,lastsellClosePrice1)andnotisbuy1

ifbuyhullcross1andbarstate.isconfirmed
isfirstBuyCdnMeet1:=true
lastbuyClosePrice1:=close
isfirstSellCdnMeet1:=false

ifsellhullcross1andbarstate.isconfirmed
isfirstSellCdnMeet1:=true
lastsellClosePrice1:=close
isfirstBuyCdnMeet1:=false

ifsellcdn1
isfirstSellCdnMeet1:=false
isbuy1:=true

ifbuycdn1
isfirstBuyCdnMeet1:=false
isbuy1:=false
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//thiscodeishowfarthepriceneedstomoveawayfromthetrendline/meanbeforeameanreversionentryisconsidered.
triggerup=1.01*ma1
triggerdown=0.99*ma1

//////////////////////////////////////////ENTRYANDEXITcode////////////////////////////////////////////////////////////////////////////
//"alert_message=LCmessage"isthecodetotellthealgotosendaLONGCLOSEmessagetotheAutomatedTradingPlatform(ATP)///
//"alert_message=SCmessage"isthecodetotellthealgotosendaSHORTCLOSEmessagetotheAutomatedTradingPlatform(ATP)//
//"alert_message=LEmessage"isthecodetotellthealgotosendaLONGENTRYmessagetotheAutomatedTradingPlatform(ATP)///
//"alert_message=SEmessage"isthecodetotellthealgotosendaSHORTENTRYmessagetotheAutomatedTradingPlatform(ATP)//
//"enableLongandafterStartDate"isrequiredforyourlongentryparameters//
//"enableShortandafterStartDate"isrequiredforyourshortentryparameters//
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//takeprofitconditions////////////////////
strategy.close('BuyTrend',when=sellcdnorsellcdn1andaverageData>triggerup,alert_message=LCmessage)//thisisthetakeprofitcondition,whenthebaseentryistriggereditwilltakeprofitoranentrycondtionfromthemeanreversionsystem
strategy.close('SellTrend',when=buycdnorbuycdn1andaverageData<triggerdown,alert_message=SCmessage)//thisisthetakeprofitcondition,whenthebaseentryistriggereditwilltakeprofitoranentrycondtionfromthemeanreversionsystem
strategy.close('BuyReversion',when=sellcdn1orsellcdnand(averageData<ma)andis_sma_touch[1],alert_message=LCmessage)//thisisthetakeprofitcondition,whenthebaseentryistriggereditwilltakeprofitoranentryconditionfromthetrendfollowingsystem
strategy.close('SellReversion',when=buycdn1orbuycdnand(averageData>ma)andis_sma_touch[1],alert_message=SCmessage)//thisisthetakeprofitcondition,whenthebaseentryistriggereditwilltakeprofitoranentrycondtionfromthetrendfollowingsystem
/////////////////////////////////
//trendfollowingentryconditions///
ifbuycdnand(averageData>ma)andis_sma_touch[1]andenableLongandafterStartDate//thisistheentrycondition,baseentrycondition,price>trendlineandtrendlinetest,longenabledandafterdatesetneedtobetruebeforeapositionistaken
strategy.entry('BuyTrend',direction=strategy.long,alert_message=LEmessage)

ifsellcdnand(averageData<ma)andis_sma_touch[1]andenableShortandafterStartDate//thisistheentrycondition,baseentrycondition,price<trendline,trendlinetest,shortenabledandafterspecifieddateneedtobetruebeforeashortpositonistaken
strategy.entry('SellTrend',direction=strategy.short,alert_message=SEmessage)

/////////////////////REVERSIONentry

ifbuycdn1andaverageData<triggerdownandenableLongandafterStartDate
strategy.entry('BuyReversion',direction=strategy.long,alert_message=LEmessage)

ifsellcdn1andaverageData>triggerupandenableShortandafterStartDate
strategy.entry('SellReversion',direction=strategy.short,alert_message=SEmessage)

//////////////////////////////////////////PLOTDATAONTHECHART
plot(ma,color=color.blue,title="trendmean")
plot(hull,color=color.white,title="trendfollowing")
plot(hull1,color=color.black,title="Reversion")

//plotshape(buycdn,title='BuyLabelforTrendIndicator',text='Buy',location=location.belowbar,style=shape.labelup,size=size.small,color=color.new(#0000FF,0),textcolor=color.new(#FFFFFF,0))
//plotshape(sellcdn,title='SellLabelforTrendIndicator',text='Sell',location=location.abovebar,style=shape.labeldown,size=size.small,color=color.new(#FF0000,0),textcolor=color.new(#FFFFFF,0))

//plotshape(buycdn1,title='BuyLabelforReversionIndicator',text='Buy',location=location.belowbar,style=shape.labelup,size=size.small,color=color.new(#0000FF,0),textcolor=color.new(#FFFFFF,0))
//plotshape(sellcdn1,title='SellLabelforReversionIndicator',text='Sell',location=location.abovebar,style=shape.labeldown,size=size.small,color=color.new(#FF0000,0),textcolor=color.new(#FFFFFF,0))
Expand (208 lines)
