Script Name: Up-Down Strategy - Contrarian
Author: REV0LUTI0N
Description: This is a consecutive bar up/down strategy for going long when the short condition is met or going short when the long condition is met. This is known in trading as taking contrarian signals and is helpful when an asset can provide only losses with a given strategy. In theory taking the opposing trade should produce a profit. With this strategy you can specify how...
PineScript code:

Pine Script™ strategy
Up/Down Strategy - Contrarian
//@version=4
//  Strategy
strategy("Up/Down  Strategy  -  Contrarian",  overlay=true,  initial_capital  =  10000,  default_qty_value  =  10000,  default_qty_type  =  strategy.cash)
consecutiveBarsUp  =  input(1,  title='Consecutive  Bars  Up')
consecutiveBarsDown  =  input(1,  title='Consecutive  Bars  Down')
price  =  close
ups  =  0.0
ups  :=  price  >  price[1]  ?  nz(ups[1])  +  1  :  0
dns  =  0.0
dns  :=  price  <  price[1]  ?  nz(dns[1])  +  1  :  0
//  Strategy  Backtesting
startDate    =  input(timestamp("2021-01-01T00:00:00"),  type  =  input.time,  title='Backtesting  Start  Date')
finishDate  =  input(timestamp("2021-12-31T00:00:00"),  type  =  input.time,  title='Backtesting  End  Date')
time_cond    =  time  >=  startDate  and  time  <=  finishDate
//Time  Restriction  Settings
startendtime  =  input("",  title='Time  Frame  To  Enter  Trades')
enableclose  =  input(false,  title='Enable  Close  Trade  At  End  Of  Time  Frame')
timetobuy  =  (time(timeframe.period,  startendtime))
timetoclose  =  na(time(timeframe.period,  startendtime))
//  Stop  Loss  &  Take  Profit  Tick  Based
enablesltp  =  input(false,  title='Enable  Take  Profit  &  Stop  Loss')
stopTick  =  input(5.0,  title='Stop  Loss  Ticks',  type=input.float)  /  100
takeTick  =  input(10.0,  title='Take  Profit  Ticks',  type=input.float)  /  100
longStop  =  strategy.position_avg_price  -  stopTick
shortStop  =  strategy.position_avg_price  +  stopTick
shortTake  =  strategy.position_avg_price  -  takeTick
longTake  =  strategy.position_avg_price  +  takeTick
plot(strategy.position_size  >  0  and  enablesltp  ?  longStop  :  na,  style=plot.style_linebr,  color=color.red,  linewidth=1,  title="Long  Fixed  SL")
plot(strategy.position_size  <  0  and  enablesltp  ?  shortStop  :  na,  style=plot.style_linebr,  color=color.red,  linewidth=1,  title="Short  Fixed  SL")
plot(strategy.position_size  >  0  and  enablesltp  ?  longTake  :  na,  style=plot.style_linebr,  color=color.green,  linewidth=1,  title="Long  Take  Profit")
plot(strategy.position_size  <  0  and  enablesltp  ?  shortTake  :  na,  style=plot.style_linebr,  color=color.green,  linewidth=1,  title="Short  Take  Profit")
//  Alert  messages
message_enterlong    =  input("",  title="Long  Entry  message")
message_entershort  =  input("",  title="Short  Entry  message")
message_closelong  =  input("",  title="Close  Long  message")
message_closeshort  =  input("",  title="Close  Short  message")
//  Strategy  Execution
if  (dns  >=  consecutiveBarsDown)  and  time_cond  and  timetobuy
        strategy.entry("Long",  strategy.long,  stop  =  high  +  syminfo.mintick,  alert_message  =  message_enterlong)

if  (ups  >=  consecutiveBarsUp)  and  time_cond  and  timetobuy
        strategy.entry("Short",  strategy.short,  stop  =  low  +  syminfo.mintick,  alert_message  =  message_entershort)

if  strategy.position_size  <  0  and  timetoclose  and  enableclose
        strategy.close_all(alert_message  =  message_closelong)
if  strategy.position_size  >  0  and  timetoclose  and  enableclose
        strategy.close_all(alert_message  =  message_closeshort)

if  strategy.position_size  <  0  and  enablesltp  and  time_cond
        strategy.exit(id="Close  Long",  stop=longStop,  limit=longTake,  alert_message  =  message_closelong)
if  strategy.position_size  >  0  and  enablesltp  and  time_cond
        strategy.exit(id="Close  Short",  stop=shortStop,  limit=shortTake,  alert_message  =  message_closeshort)
Expand (70 lines)
