Script Name: WOMBO COMBO- EMA & VWAP & MACD & BB & STC
Author: MakeMoneyCoESTB2020
Description: Hello my fellow investors,

After hours of reading, backtesting, and YouTube video watching I discovered that EMA, VWAP, BB, MACD, and STC produce the most consistent results for investment planning.  This strategy allows you to pick between the aforementioned indicators or layer them together.

It works on the pricipal of:
1) Always follow the market trend -...
PineScript code:

Pine Script™ strategy
WOMBO COMBO: EMA & VWAP & MACD & BB & STC
//@version=4
//  This  source  code  is  subject  to  the  terms  of  the  Mozilla  Public  License  2.0  at  https://mozilla.org/MPL/2.0/
//  ©  MakeMoneyCoESTB2020
//Edition  383  update  -  window  condition  for  code  execution  added  (compliments  to  allanster  for  approach)
//Edition  380  update  -  BB  condition  coded  out  of  exit  strategy
//*********************Notes  for  continued  work***************
//3)  add  a  Table  of  contents  to  each  section  of  code
//4)  add  candle  stick  pattern  considerations  to  chart
//9)
//************************************************************
//Hello  my  fellow  investors
//After  hours  of  reading,  backtesting,  and  YouTube  video  watching
//I  discovered  that  200EMA,  VWAP,  BB,  MACD,  and  STC
//produce  the  most  consistent  results  for  investment  planning.
//This  strategy  allows  you  to  pick  between  the  aforementioned  indicators  or  layer  them  together.
//It  works  on  the  pricipal  of:
//1)  Always  follow  the  market  trend  -  buy/sell  above/below  200EMA
//2)  Follow  corporate  investing  trends  -  buy/sell  above/below  VWAP
//3)  Apply  MACD  check  -  buy-->  MACD  line  above  signal  line
//  and  corssover  below  histogram  \\  sell  -->  MACD  line  below  signal  line
//  and  crossover  above  histogram.
//4)  Check  volitility  with  price  against  BB  limits  upper/Sell  or  lower/buy
//5)  When  STC  crosses  about  10  buy  and  when  it  drops  below  90  sell
//6)  Exit  position  when  stop  loss  is  triggered  or  profit  target  is  hit.    BB  also  provides  a  parameter  to  exit  positions.
//This  code  is  the  product  of  many  hours  of  hard  work  on  the  part  of  the  greater  tradingview  community.    The  credit  goes  to  everyone  in  the  community  who  has  put  code  out  there  for  the  greater  good.
//Happy  Hunting!
//Title
strategy("WOMBO  COMBO:  100/200EMA  &  VWAP  &  MACD",  shorttitle="WOMBO  COMBO",  default_qty_type=strategy.percent_of_equity,  default_qty_value=5,  initial_capital=20000,slippage=2,  currency=currency.USD,  overlay=true,  pyramiding  =  2)
//define  calculations  price  source
price  =  input(title="Price  Source",  defval=close)
//Does  user  want  to  run  the  Strategy  for  Trending  Up  or  Trending  Down
RunTrend=input(title="Run  Strategy  Trending  Up,  Down,  or  Both",  defval="Both",  options=["Up",  "Down",  "Both"])
//***************************
//Calculate  20/50/100/200EMA
EMAlength  =  input(title="EMA_Length",  defval=200)
EMA=ema(price,  EMAlength)
//plot  EMA
ColorEMA=EMAlength==200?color.blue:EMAlength==100?color.aqua:EMAlength==50?color.orange:color.red
plot(EMA,  title  =  "EMA",  color  =  ColorEMA)
//*****************************
//calculate  VWAP
ColorVWAP  =  (price  >  vwap)  ?  color.lime  :  color.maroon
plot(vwap,  title  =  "VWAP",  color=ColorVWAP,  linewidth=2)
//*****************************
//calculate  MACD
//define  variables  for  speed
fast  =  12,  slow  =  26
//define  parameters  to  calculate  MACD
fastMA  =  ema(price,  fast)
slowMA  =  ema(price,  slow)
//define  MACD  line
macd  =  fastMA  -  slowMA
//define  SIGNAL  line
signal  =  sma(macd,  9)
//plot  MACD  line
//plot(macd,  title  =  "MACD",    color=color.orange)
//plot  signal  line
//plot(signal,  title  =  "Signal",  color=color.purple)
//plot  histogram
//define  histogram  colors
//col_grow_above  =  color.green
//col_grow_below  =  color.red
//col_fall_above  =  color.lime
//col_fall_below  =  color.maroon
//define  histogram  value
//hist  =  macd  -  signal
//plot  histogram
//plot(hist,  title="Histogram",  style=plot.style_columns,  color=(hist>=0  ?  (hist[1]  <  hist  ?  col_grow_above  :  col_fall_above)  :  (hist[1]  <  hist  ?  col_grow_below  :  col_fall_below)  ),  transp=0  )
//***************************************
//Calculate  Bollinger  Bands
//Define  BB  input  variables
//lengthBB  =  input(20,  minval=1)
//multBB  =  input(2.0,  minval=0.001,  maxval=50)
lengthBB  =  20
multBB  =  2
//define  BB  average
basisBB  =  sma(price,  lengthBB)
//define  BB  standar  deviation
devBB  =  multBB  *  stdev(price,  lengthBB)
//define  BB  upper  and  lower  limits
upperBB  =  basisBB  +  devBB
lowerBB  =  basisBB  -  devBB
//Plot  BB  graph
ShowBB  =  input(title="Show  BB",  defval="Y",  type=input.string,  options=["Y",  "N"])
transP  =  (ShowBB=="Y")  ?  0  :  100
plot  (upperBB,  title  =  "BB  Upper  Band",  color  =  color.aqua,  transp=transP)
plot  (basisBB,  title  =  "BB  Average",  color  =  color.red,  transp=transP)
plot  (lowerBB,  title  =  "BB  Lower  Band",  color  =  color.aqua,  transp=transP)
//*************************************************
//Calculate  STC
//fastLength  =  input(title="MACD  Fast  Length",  type=input.integer,  defval=12)
//slowLength  =  input(title="MACD  Slow  Length",  type=input.integer,  defval=26)
fastLength  =  23
slowLength  =  50
cycleLength  =  input(title="Cycle  Length",  type=input.integer,  defval=40)
//d1Length  =  input(title="1st  %D  Length",  type=input.integer,  defval=3)
//d2Length  =  input(title="2nd  %D  Length",  type=input.integer,  defval=3)
d1Length  =  3
d2Length  =  3
srcSTC  =  close
macdSTC  =  ema(srcSTC,  fastLength)  -  ema(srcSTC,  slowLength)
k  =  nz(fixnan(stoch(macdSTC,  macdSTC,  macdSTC,  cycleLength)))
d  =  ema(k,  d1Length)
kd  =  nz(fixnan(stoch(d,  d,  d,  cycleLength)))
stc  =  ema(kd,  d2Length)
stc  :=    stc  >  100  ?  100  :  stc  <  0  ?  0  :  stc
upperSTC  =  input(title="Upper  STC  limit",  defval=85)
lowerSTC  =  input(  title="Lower  STC  limit",  defval=15)
ma1length=35
ma1  =  ema(close,ma1length)
ma2  =  ema(close,EMAlength)
//STCbuy  =  crossover(stc,  lowerSTC)  and  ma1>ma2  and  close>ma1
//STCsell  =  crossunder(stc,  upperSTC)  and  ma1<ma2  and  close<ma1
STCbuy  =  crossover(stc,  lowerSTC)
STCsell  =  crossunder(stc,  upperSTC)
//*************************************************
//Candle  stick  patterns
//DojiSize  =  input(0.05,  minval=0.01,  title="Doji  size")
//data=(abs(open  -  close)  <=  (high  -  low)  *  DojiSize)
//plotchar(data,  title="Doji",  text='Doji',  color=color.white)
data2=(close[2]  >  open[2]  and  min(open[1],  close[1])  >  close[2]  and  open  <  min(open[1],  close[1])  and  close  <  open  )
//plotshape(data2,  title=  "Evening  Star",  color=color.red,  style=shape.arrowdown,  text="Evening\nStar")
data3=(close[2]  <  open[2]  and  max(open[1],  close[1])  <  close[2]  and  open  >  max(open[1],  close[1])  and  close  >  open  )
//plotshape(data3,    title=  "Morning  Star",  location=location.belowbar,  color=color.lime,  style=shape.arrowup,  text="Morning\nStar")
data4=(open[1]  <  close[1]  and  open  >  close[1]  and  high  -  max(open,  close)  >=  abs(open  -  close)  *  3  and  min(close,  open)  -  low  <=  abs(open  -  close))
//plotshape(data4,  title=  "Shooting  Star",  color=color.red,  style=shape.arrowdown,  text="Shooting\nStar")
data5=(((high  -  low)>3*(open  -close))  and    ((close  -  low)/(.001  +  high  -  low)  >  0.6)  and  ((open  -  low)/(.001  +  high  -  low)  >  0.6))
//plotshape(data5,  title=  "Hammer",  location=location.belowbar,  color=color.white,  style=shape.diamond,  text="H")
data5b=(((high  -  low)>3*(open  -close))  and    ((high  -  close)/(.001  +  high  -  low)  >  0.6)  and  ((high  -  open)/(.001  +  high  -  low)  >  0.6))
//plotshape(data5b,  title=  "Inverted  Hammer",  location=location.belowbar,  color=color.white,  style=shape.diamond,  text="IH")
data6=(close[1]  >  open[1]  and  open  >  close  and  open  <=  close[1]  and  open[1]  <=  close  and  open  -  close  <  close[1]  -  open[1]  )
//plotshape(data6,  title=  "Bearish  Harami",    color=color.red,  style=shape.arrowdown,  text="Bearish\nHarami")
data7=(open[1]  >  close[1]  and  close  >  open  and  close  <=  open[1]  and  close[1]  <=  open  and  close  -  open  <  open[1]  -  close[1]  )
//plotshape(data7,    title=  "Bullish  Harami",  location=location.belowbar,  color=color.lime,  style=shape.arrowup,  text="Bullish\nHarami")
data8=(close[1]  >  open[1]  and  open  >  close  and  open  >=  close[1]  and  open[1]  >=  close  and  open  -  close  >  close[1]  -  open[1]  )
//plotshape(data8,    title=  "Bearish  Engulfing",  color=color.red,  style=shape.arrowdown,  text="Bearish\nEngulfing")
data9=(open[1]  >  close[1]  and  close  >  open  and  close  >=  open[1]  and  close[1]  >=  open  and  close  -  open  >  open[1]  -close[1])
//plotshape(data9,title="BullishEngulfing",location=location.belowbar,color=color.lime,style=shape.arrowup,text="Bullish\nEngulfling")
upper=highest(10)[1]
data10=(close[1]<open[1]andopen<low[1]andclose>close[1]+((open[1]-close[1])/2)andclose<open[1])
//plotshape(data10,title="PiercingLine",location=location.belowbar,color=color.lime,style=shape.arrowup,text="Piercing\nLine")
lower=lowest(10)[1]
data11=(low==openandopen<lowerandopen<closeandclose>((high[1]-low[1])/2)+low[1])
//plotshape(data11,title="BullishBelt",location=location.belowbar,color=color.lime,style=shape.arrowup,text="Bullish\nBelt")
data12=(open[1]>close[1]andopen>=open[1]andclose>open)
//plotshape(data12,title="BullishKicker",location=location.belowbar,color=color.lime,style=shape.arrowup,text="Bullish\nKicker")
data13=(open[1]<close[1]andopen<=open[1]andclose<=open)
//plotshape(data13,title="BearishKicker",color=color.red,style=shape.arrowdown,text="Bearish\nKicker")
data14=(((high-low>4*(open-close))and((close-low)/(.001+high-low)>=0.75)and((open-low)/(.001+high-low)>=0.75))andhigh[1]<openandhigh[2]<open)
//plotshape(data14,title="HangingMan",color=color.red,style=shape.arrowdown,text="Hanging\nMan")
data15=((close[1]>open[1])and(((close[1]+open[1])/2)>close)and(open>close)and(open>close[1])and(close>open[1])and((open-close)/(.001+(high-low))>0.6))
//plotshape(data15,title="DarkCloudCover",color=color.red,style=shape.arrowdown,text="Dark\nCloudCover")
//************************************INPUTBACKTESTRANGE******************************************===
fromMonth=input(defval=1,title="FromMonth",type=input.integer,minval=1,maxval=12)
fromDay=input(defval=1,title="FromDay",type=input.integer,minval=1,maxval=31)
fromYear=input(defval=2020,title="FromYear",type=input.integer,minval=1970)
thruMonth=input(defval=1,title="ThruMonth",type=input.integer,minval=1,maxval=12)
thruDay=input(defval=1,title="ThruDay",type=input.integer,minval=1,maxval=31)
thruYear=input(defval=2112,title="ThruYear",type=input.integer,minval=1970)
//===INPUTSHOWPLOT===
showDate=input(defval=true,title="ShowDateRange",type=input.bool)
//===FUNCTIONEXAMPLE===
start=timestamp(fromYear,fromMonth,fromDay,00,00)//backteststartwindow
finish=timestamp(thruYear,thruMonth,thruDay,23,59)//backtestfinishwindow
window()=>time>=startandtime<=finish?true:false//createfunction"withinwindowoftime"
bgcolor(color=showDateandwindow()?color.gray:na,transp=90)
//===EXECUTION===
//strategy.entry("L",strategy.long,when=window()andcrossOv)//enterlongwhen"withinwindowoftime"ANDcrossover
//strategy.close("L",when=window()andcrossUn)//exitlongwhen"withinwindowoftime"ANDcrossunder
//**********Long&ShortEntryCalculations***********************************
//Determinewhentorunthestrategybasedonuserinputforuptrendordowntrend
RunTrendUp=false//VaribileforrunningtheStrategyinanUpTrend
RunTrendUp:=iff(RunTrend=="Up"orRunTrend=="Both",true,false)
RunTrendDWN=false//VaribileforrunningtheStrategyinaDownTrend
RunTrendDWN:=iff(RunTrend=="Down"orRunTrend=="Both",true,false)
//Definecountbackvariable
countback=input(minval=0,maxval=5,title="PriceCountBack",defval=0)
//Userinputforwhatevaluationstorun:EMA,VWAP,MACD,BB
EMA_Y_N=input(defval="Y",title="RunEMA",type=input.string,options=["Y","N"])
VWAP_Y_N=input(defval="Y",title="RunVWAP",type=input.string,options=["Y","N"])
MACD_Y_N=input(defval="N",title="RunMACD",type=input.string,options=["Y","N"])
BB_Y_N=input(defval="N",title="RunBB",type=input.string,options=["Y","N"])
STC_Y_N=input(defval="Y",title="RunSTC",type=input.string,options=["Y","N"])
//longentrycondition
dataHCLB=(RunTrendUpandiff(STC_Y_N=="Y",STCbuy,true)andiff(EMA_Y_N=="Y",price[countback]>EMA,true)andiff(VWAP_Y_N=="Y",price[countback]>vwap,true)andiff(MACD_Y_N=="Y",crossunder(signal[countback],macd[countback]),true)andiff(MACD_Y_N=="Y",macd[countback]<0,true)andiff(BB_Y_N=="Y",crossunder(price[countback],lowerBB),true))
plotshape(dataHCLB,title="HC-LB",color=color.lime,style=shape.circle,text="HC-LB")
strategy.entry("HC-Long",strategy.long,comment="HC-Long",when=dataHCLBandwindow())
//shortentrycondition
dataHCSB=(RunTrendDWNandiff(STC_Y_N=="Y",STCsell,true)andiff(EMA_Y_N=="Y",price[countback]<EMA,true)andiff(VWAP_Y_N=="Y",price[countback]<vwap,true)andiff(MACD_Y_N=="Y",crossunder(macd[countback],signal[countback]),true)andiff(MACD_Y_N=="Y",signal[countback]>0,true)andiff(BB_Y_N=="Y",crossover(price[countback],upperBB),true))
plotshape(dataHCSB,title="HC-SB",color=color.fuchsia,style=shape.circle,text="HC-SB")
strategy.entry("HC-Short",strategy.short,comment="HC-Short",when=dataHCSBandwindow())
//******************ExitConditions******************************
//ProfitandLossExitCalculations
//UserOptionstoChangeInputs
//DoesuserwanttorunaTrailingStop
trailStop_YN=input(title="RunaTrailingStop",defval="N",options=["Y","N"])
TrailPerc=input(title="TrailLoss%",type=input.float,minval=0,step=1,defval=6)/100
//UserOptionstoChangeInputs(%)
stopPer=input(15,title='StopLoss%',type=input.float)/100
takePer=input(25,title='TakeProfit%',type=input.float)/100
//calculateTrailstoppriceforMD_EMATGT%condition
longStopPrice=0.0//longsideentrystopvariable
longStopPrice:=if(strategy.position_size>0)
stopValue=close*(1-TrailPerc)
max(stopValue,longStopPrice[1])
else
0

shortStopPrice=0.0//shortsideentrystopvariable
shortStopPrice:=if(strategy.position_size<0)
shortStopValue=close*(1+TrailPerc)
min(shortStopValue,shortStopPrice[1])
else
999999

//Determinewhereyou'veenteredandinwhatdirection
longStop=strategy.position_avg_price*(1-stopPer)
shortStop=strategy.position_avg_price*(1+stopPer)
shortTake=strategy.position_avg_price*(1-takePer)
longTake=strategy.position_avg_price*(1+takePer)
//exitpositionconditionsandorders
ifstrategy.position_size>0//orcrossunder(price[countback],upperBB)
strategy.exit(id="CloseLong",when=window(),stop=longStop,limit=longTake)
ifstrategy.position_size<0//orcrossover(price[countback],lowerBB)
strategy.exit(id="CloseShort",when=window(),stop=shortStop,limit=shortTake)//exitpositionconditionsandorders
ifstrategy.position_size>0//longsideexitconditions
iftrailStop_YN=="Y"
strategy.exit(id="CloseLong",when=window(),stop=longStop,limit=longTake,qty_percent=50)//sell50%wheneithertheTGTortheSLishitthentransitiontoatrailingstoploss
strategy.exit(id="CloseLongTrailingStop",when=window(),stop=longStopPrice,qty_percent=100)
iftrailStop_YN=="N"
strategy.exit(id="CloseLong",when=window(),stop=longStop,limit=longTake)//sellwheneithertheTGTortheSLishit


ifstrategy.position_size<0//shortsideexitconditions
iftrailStop_YN=="Y"
strategy.exit(id="CloseShort",when=window(),stop=shortStop,limit=shortTake,qty_percent=50)//sell50%wheneithertheTGTortheSLishitthentransitiontoatrailingstoploss
strategy.exit(id="CloseShortTrailingStop",when=window(),stop=shortStopPrice,qty_percent=100)
iftrailStop_YN=="N"
strategy.exit(id="CloseShort",when=window(),stop=shortStop,limit=shortTake)//sellwheneithertheTGTortheSLishit
//Plotstoptrailinglossvaluesforconfirmation
plot(series=(strategy.position_size>0and(trailStop_YN=="Y"))?longStopPrice:na,color=color.fuchsia,style=plot.style_cross,linewidth=2,title="LongTrailStop")//plotthetrailingstoponthechartforanuptrend
plot(series=(strategy.position_size<0and(trailStop_YN=="Y"))?shortStopPrice:na,color=color.fuchsia,style=plot.style_cross,linewidth=2,title="ShortTrailStop")//plotthetrailingstoponthechartforadowntrend
//plotfixedstoplossvalue
plot(series=(strategy.position_size>0and(trailStop_YN=="N"))?longStop:na,color=color.fuchsia,style=plot.style_cross,linewidth=2,title="LongTrailStop")//plotthestoponthechartforanuptrend
plot(series=(strategy.position_size<0and(trailStop_YN=="N"))?shortStop:na,color=color.fuchsia,style=plot.style_cross,linewidth=2,title="ShortTrailStop")//plotthestoponthechartforadowntrend
//plottheTGTprofitpoints
plot(series=(strategy.position_size>0)?longTake:na,color=color.lime,style=plot.style_cross,linewidth=2,title="ShortTrailStop")//plottheTGT%forlongposition
plot(series=(strategy.position_size<0)?shortTake:na,color=color.lime,style=plot.style_cross,linewidth=2,title="ShortTrailStop")//plottheTGT%forshortposition
Expand (317 lines)
