Script Name: XAU-USD RSI EMA 1hour strategy
Author: SoftKill21
Description: This is a strategy made for gold 1h.

Its made of RSI and EMA .

The rules are simple we are above ema and the rsi > oversold area we enter long. For short we are belowe ema and rsi < oversold area


IF you have any questions private message me !
PineScript code:

Pine Script™ strategy
XAU/USD RSI EMA 1hour strategy
//@version=4
strategy("My  Strategy",  overlay  =  false,  commission_value  =  0.01,  overlay=true)
//  Custom  RSI
RSIlength  =  input(  14,  minval=1  ,  title="lookback  length  of  RSI")
RSIOverBought  =  input(65,  title="OB")
RSIOverSold  =  input(35,  title="OS")
RSIprice  =  close
vrsi  =  rsi(RSIprice,  RSIlength)
//Bollinger  Bands
BBlength  =  input(40,  minval=1,title="Bollinger  Period  Length")
BBmult  =  2  //  input(2.0,  minval=0.001,  maxval=50,title="Bollinger  Bands  Standard  Deviation")
BBbasis  =  sma(close,  BBlength)
BBdev  =  BBmult  *  stdev(close,  BBlength)
BBupper  =  BBbasis  +  BBdev
BBlower  =  BBbasis  -  BBdev
source  =  close
emaLength=input(162)
strategy.entry("short",  strategy.short,  when  =  close  >  ema(close,  emaLength)  and  vrsi  <  RSIOverSold)
strategy.exit("short",  when  =  vrsi  >  RSIOverBought  and  close  <  ema(close,  emaLength))
strategy.entry("long",  strategy.long,  when  =  close  <  ema(close,  emaLength)  and  vrsi  >  RSIOverSold)
strategy.exit("long",  when  =  vrsi  >  RSIOverBought  and  close  >  ema(close,  emaLength))

Expand (30 lines)
